### ISSUE TITLE
Can't open user permissions

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10169]
After todays update I cant open user permissions

**Comment by strixaluco** [comment]
Frappe/ERPNext versions? Steps to replicate and expected/actual behavior?

**Comment by rmehta** [comment]
Please reload. User Permission is now a DocType

**Comment by applepipe** [comment]
Hello @strixaluco @rmehta,

This is the error I get when I try to click on "User Permissions Manager"

"Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 32, in getpage
    doc = get(page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 15, in get
    page.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/page/page.py", line 143, in load_assets
    self.script += get_lang_js("page", self.name)
AttributeError: 'Page' object has no attribute 'script'"

I'm on developer branch, I always test new functionality to contribute reporting bugs.

I just updated now and the problem persists, also, some users can't see documents from other companies without any configuration being made.

**Comment by rmehta** [comment]
Please restore from backup and run the patch again... there was a bug that was fixed.

Where did you access the page from? It has been removed.

**Comment by applepipe** [comment]
hi @rmehta after last update the link was really removed, but until the post it wasnt. I re-ran the patch deleting the patch from tabPatch Log and doing a bench update. Apparently everything went well but now I cant see employees, companies, orders, and my user is system admin.
