### ISSUE TITLE
Dropbox Broken

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10367]
When I add a Dropbox access key and secret key in the Dropbox Settings in Integrations, and then I click Allow Dropbox Access, I get an error with the following traceback:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 221, in get_dropbox_authorize_url
    app_details = get_dropbox_settings(redirect_uri=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 196, in get_dropbox_settings
    + '/api/method/dropbox_erpnext_broker.www.setup_dropbox.generate_dropbox_access_token',
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

**Comment by saurabh6790** [comment]
Seems you haven't setup app_access_key and app_secret_key in Dropbox settings.

**Comment by asmith1** [comment]
That's exactly what I was doing when I got this error. I was unable to successfully set it up in Dropbox Settings

**Comment by hanselsen** [comment]
Any solution for this?

**Comment by sathishpy** [comment]
I thought of trying Dropbox feature and ended up with the same issue.

**Comment by saurabh6790** [comment]
Ref https://erpnext.org/docs/user/manual/en/setting-up/integrations/dropbox-backup to setup dropbox service.

**Comment by sathishpy** [comment]
btw, I tried this again in recently after seeing a discuss update and it worked. So we can mark this issue as closed in the latest release.
