### ISSUE TITLE
MySQL syntax error if the customer name contains special characters

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#10503]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/desk/query_report.py", line 95, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-2017-08-21/apps/erpnext/erpnext/regional/report/gst_itemised_sales_register/gst_itemised_sales_register.py", line 26, in execute
    'gst_hsn_code'
  File "/home/frappe/benches/bench-2017-08-21/apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 28, in _execute
    so_dn_map = get_delivery_notes_against_sales_order(item_list)
  File "/home/frappe/benches/bench-2017-08-21/apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 135, in get_delivery_notes_against_sales_order
    """ % (', '.join(['%s']*len(so_item_rows))), tuple(so_item_rows), as_dict=1)
  File "/home/frappe/benches/bench-2017-08-21/apps/frappe/frappe/database.py", line 165, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2017-08-21/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-08-21/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')\n\t\tgroup by so_detail, parent' at line 3")
```

**Comment by mudux** [comment]
Am having a similar issue.

This is what I get from this code:

`party_nm = frappe.db.sql("""select customer from 'tabSales Invoice' where name=%s""",
					line["invoice_paid_against"])`

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/batch_list/batch_list.py", line 33, in create_jv_entry
    line["invoice_paid_against"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 138, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''tabSales Invoice' where name='SINV-RET-00315'' at line 1")`

**Comment by tundebabzy** [comment]
> party_nm = frappe.db.sql("""select customer from 'tabSales Invoice' where name=%s""",
line["invoice_paid_against"])

Shouldn't this be 
```(sql)
party_nm = frappe.db.sql("""select customer from `tabSales Invoice` where name=%s""",
line["invoice_paid_against"])
```

Thats aside, please ask questions on the forum
