### ISSUE TITLE
Warehouse Query Bug

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10537]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/desk/search.py", line 13, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_length=page_length, filters=filters)
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/desk/search.py", line 34, in search_widget
    searchfield, start, page_length, filters, as_dict=as_dict)
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-08-23/apps/erpnext/erpnext/controllers/queries.py", line 392, in warehouse_query
    "page_len": page_len
  File "/home/frappe/benches/bench-2017-08-23/apps/frappe/frappe/database.py", line 154, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/benches/bench-2017-08-23/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 238, in execute
    query = query % args
ValueError: unsupported format character '"' (0x22) at index 220
```

Request Data

```
{
	"type": "GET",
	"args": {
		"txt": "",
		"doctype": "Warehouse",
		"filters": "[[\"Warehouse\",\"company\",\"in\",[\"\",\"Modista Resortwear\"]],[\"Warehouse\",\"is_group\",\"=\",0],[\"Bin\",\"item_code\",\"=\",\"Lining Blackout 80 %\"]]",
		"query": "erpnext.controllers.queries.warehouse_query",
		"cmd": "frappe.desk.search.search_link"
	},
	"url": "/"
}
```

**Comment by tundebabzy** [comment]
#10538
