### ISSUE TITLE
New VM .ova Production setup, can't chose the chart of accounts for any language, any company

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#10569]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 108, in get_charts_for_country
    if (fname.startswith(country_code) or fname.startswith(country)) and fname.endswith(".json"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)

**Comment by krnkris** [comment]
This conflict seem to be the same as of:

https://discuss.erpnext.com/t/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-19-ordinal-not-in-range-128/27424

**Comment by krnkris** [comment]
OK here is the solution:

Please rename the 
fr_plan_comptable_général.json
to
fr_plan_comptable_general.json

on terminal 
mv fr_plan_comptable_général.json fr_plan_comptable_general.json

Please update the file name on the Production Master + Develop.
Thank you!

**Comment by krnkris** [comment]
https://github.com/frappe/erpnext/pull/10620
