### ISSUE TITLE
erpnext make-demo not working

### ISSUE THREAD

**Issue by vishalseshagiri** [frappe/erpnext#10631]
erpnext make-demo does'nt seem to be working.
```
frappe@b61e9e949dbe:~/frappe-bench$ bench --site t_erp make-demo --reinstall

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
*** Scheduler is enabled ***
Complete Setup...
Simulating 2017-06-01: Day 9Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/commands/__init__.py", line 45, in make_demo
    demo.make(domain, days)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/demo.py", line 39, in make
    simulate(domain, days)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/demo.py", line 76, in simulate
    accounts.work()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/user/accounts.py", line 72, in work
    make_pos_invoice()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/user/accounts.py", line 113, in make_pos_invoice
    si.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 741, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 730, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 280, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 793, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 870, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 121, in on_submit
    self.update_prevdoc_status()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 110, in update_prevdoc_status
    self.update_qty()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 227, in update_qty
    self._update_percent_field_in_targets(args, update_modified)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 272, in _update_percent_field_in_targets
    self._update_percent_field(args, update_modified)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 287, in _update_percent_field
    where name='%(name)s'""" % args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 165, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.OperationalError: (1365, 'Division by 0')
```

**Comment by pratu16x7** [comment]
This no longer appears to be an issue. Another one does crop up though:
![screen shot 2017-09-05 at 5 13 44 pm](https://user-images.githubusercontent.com/5196925/30060165-d440cacc-925f-11e7-8e63-67623f82e39c.png)

Fixed via #10681
