### ISSUE TITLE
pull_from_email_account - error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by vijayendrarock** [frappe/erpnext#10655]
I have Cpanel mail
Incoming mail server: mail.domain.com
IMAP and SSL enabled
Outgoing mail server: mail.domain.com
Port: Blank (as it denoted 465).

Here is error log:

{'retry': 0, 'log': <function log at 0xb5ba15dc>, 'site': u'VAA', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb556341c>, 'user': u'Administrator', 'kwargs': {'email_account': u'Sales'}, 'async': True, 'job_name': u'pull_from_email_account|Sales'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 71, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 699, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 253, in receive
    emails = email_server.get_messages()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 105, in get_messages
    if not self.connect():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 44, in connect
    return self.connect_imap()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 52, in connect_imap
    self.imap = Timed_IMAP4_SSL(self.settings.host, timeout=frappe.conf.get("pop_timeout"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 550, in __init__
    self._super.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/imaplib.py", line 1165, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python2.7/imaplib.py", line 172, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/imaplib.py", line 1176, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by umairsy** [comment]
Hello,

Please post such queries on the ERPNext community forum.

https://discuss.erpnext.com

Once validated as a bug or feature suggestion needed by many users, we can add it as a Github Issue.
