### ISSUE TITLE
Balance Sheet Report error

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10680]
Hi

Getting the error below when trying to view Balance Sheet report on an ERPNext Cloud account

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-08-30/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-08-30/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-08-30/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-08-30/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-08-30/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-2017-08-30/apps/erpnext/erpnext/accounts/report/balance_sheet/balance_sheet.py", line 16, in execute
    accumulated_values=filters.accumulated_values)
  File "/home/frappe/benches/bench-2017-08-30/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 135, in get_data
    calculate_values(accounts_by_name, gl_entries_by_account, period_list, accumulated_values, ignore_accumulated_values_for_fy)
  File "/home/frappe/benches/bench-2017-08-30/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 156, in calculate_values
    d[period.key] = d.get(period.key, 0.0) + flt(entry.debit) - flt(entry.credit)
AttributeError: 'NoneType' object has no attribute 'get'
```

Please fix asap

Thanks

**Comment by Olawale1** [comment]
Any update on this? The balance sheet report is quite an important one!

Thanks

**Comment by tundebabzy** [comment]
#10768

**Comment by nabinhait** [comment]
The issue is related to your data. Can't say much without seeing the account data.

Seems like `nestedset` model is broken for Account.

**Comment by Olawale1** [comment]
Hi @nabinhait 

Thanks for your response. The account is hosted on the ERPNext cloud so I guess we need to send an email to support to look into this

Kind regards,
