### ISSUE TITLE
Timeout while uploading backups to dropbox

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#10739]
```
YM_7176119_PO_005.pdf - Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-09-07/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 141, in upload_from_folder
    upload_file_to_dropbox(filepath, dropbox_folder, dropbox_client)
  File "/home/frappe/benches/bench-2017-09-07/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 156, in upload_file_to_dropbox
    dropbox_client.files_upload(f.read(), path, mode)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/dropbox/dropbox.py", line 239, in request
    timeout=timeout)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/dropbox/dropbox.py", line 330, in request_json_string_with_retry
    timeout=timeout)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/dropbox/dropbox.py", line 414, in request_json_string
    timeout=timeout,
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 270, in recv
    rd = util.wait_for_read(self.socket, self.socket.gettimeout())
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/util/wait.py", line 26, in _wait_for_io_events
    selector.select(timeout) if key[1] & events]
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/util/selectors.py", line 438, in select
    maxevents=max_events)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/urllib3/util/selectors.py", line 94, in _syscall_wrapper
    result = func(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-09-07/env/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (1500 seconds)

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-09-07/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 46, in take_backup_to_dropbox
    if did_not_upload: raise Exception
Exception
```

**Comment by Priyanka-IAS** [comment]
Hi,

When can we expect this to be fixed? We have been getting this exception for over two months now and our weekly backup shows "failed".

Regards,

Priyanka

**Comment by saurabh6790** [comment]
Potential Fix: https://github.com/frappe/frappe/pull/4492

**Comment by Priyanka-IAS** [comment]
Hi,

Our Backups have been failing since mid Sept'17. Its been 6 months. As a company we simply CANNOT take this risk of running for so long without backups. 

Please let us know if you are unable to fix this issue within the next week. We need to seriously look at options to save ourselves from a potential catastrophe.

Regards,

Priyanka

**Comment by Priyanka-IAS** [comment]
Hi,

When can we expect to see a fix for this? We are really getting worried now. Any update would be appreciated. 

Regards,

Priyanka

**Comment by saurabh6790** [comment]
https://github.com/frappe/frappe/pull/5450
