### ISSUE TITLE
Balance sheet is not Generated

### ISSUE THREAD

**Issue by gunvantnehete** [frappe/erpnext#10805]
When i clicked balance sheet it shows following error

"Server Error: Please check your server logs or contact tech support."

Please let me know the resolution for same

**Comment by rohitwaghchaure** [comment]
Hi @gunvantnehete 

Any error on console log? If yes kindly share the complete traceback of an error

**Comment by gunvantnehete** [comment]
@rohitwaghchaure  I am not much of techie can you please explain where to find console log error report so that i can give you detailed input.

Thanks,
Gunvant

**Comment by gunvantnehete** [comment]
@rohitwaghchaure  please check following console log 

?report_name=Balance+Sheet&filters=%7B%22company%22%3A%22Green+Pyramid+Energy%22%2C%22from_fiscal_year%22%3A%222017-2018%22%2C%22to_fiscal_year%22%3A%222017-2018%22%2C%22periodicity%22%3A%22Monthly%22%2C%22accumulated_values%22%3A1%7D&cmd=frappe.desk.query_report.run&_=1505536374593 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
desk.min.js?ver=1505383748.0:1557 Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-09-14/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-09-14/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-09-14/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-09-14/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-09-14/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-2017-09-14/apps/erpnext/erpnext/accounts/report/balance_sheet/balance_sheet.py", line 16, in execute
    accumulated_values=filters.accumulated_values)
  File "/home/frappe/benches/bench-2017-09-14/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 135, in get_data
    calculate_values(accounts_by_name, gl_entries_by_account, period_list, accumulated_values, ignore_accumulated_values_for_fy)
  File "/home/frappe/benches/bench-2017-09-14/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 156, in calculate_values
    d[period.key] = d.get(period.key, 0.0) + flt(entry.debit) - flt(entry.credit)
AttributeError: 'NoneType' object has no attribute 'get'

PLease let me know is it of any help

Thanks,
Gunvant

**Comment by tundebabzy** [comment]
Hi @gunvantnehete 
This was also reported by another user in #10680. Without having access to your data, it's practically impossible to debug so we've added  #10768 to make it clearer to know what's going on. It should be live as soon as by Tuesday or so.
