### ISSUE TITLE
Server error on every login

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10835]
Hello,

I'm using developer branch with latest updates, and every time a user log in a message that there was a server error pops up, the console shows this error:

"Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
desk.min.js?ver=1505763207.0:1565 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/user_progress.py", line 17, in get_user_progress_slides
    slides += frappe.get_attr(fn)()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/utilities/user_progress.py", line 262, in get_user_progress_slides
    s.done = get_action_completed_state(s.action_name) or 0
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/setup_progress/setup_progress.py", line 20, in get_action_completed_state
    if d.action_name == action_name][0]
IndexError: list index out of range"

**Comment by pratu16x7** [comment]
Most likely the patch `add_setup_progress_actions.py` hasn't rerun. Have you tried migrating?

**Comment by applepipe** [comment]
hello, @pratu16x7 thanks for responding, I've updated again and ran bench --site all migrate with no luck.

**Comment by applepipe** [comment]
@pratu16x7 

Besides the reruning of the patch and bench --site all migrate, is there anything else I could do? No error are shown running the patch or during migration

**Comment by applepipe** [comment]
https://github.com/frappe/erpnext/issues/10908
