### ISSUE TITLE
Error when updating from v6 to v7/v8

### ISSUE THREAD

**Issue by nimrodflores** [frappe/erpnext#10899]
This occurred when trying to update an ERPNext v6 instance to the latest. The rest of the preceding patches were executed successfully until this part:

```
.....
.....
Success
Executing erpnext.patches.v6_27.fix_recurring_order_status in erp.example.com (1234567890)
Success
Executing erpnext.patches.v6_20x.update_product_bundle_description in erp.example.com (1234567890)
Success
Executing erpnext.patches.v7_0.update_party_status #2016-09-22 in erp.example.com (1234567890)
Success
Executing erpnext.patches.v7_0.update_item_projected in erp.example.com (1234567890)
Success
Executing erpnext.patches.v7_0.remove_features_setup in erp.example.com (1234567890)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/user/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/user/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/user/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/user/frappe-bench/apps/erpnext/erpnext/patches/v7_0/remove_features_setup.py", line 14, in execute
    create_compact_item_print_custom_field()
  File "/home/user/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 54, in create_compact_item_print_custom_field
    'insert_after': 'with_letterhead'
  File "/home/user/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 106, in create_custom_field
    "hidden": df.hidden or 0
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 219, in insert
    self.run_post_save_methods()
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 870, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/user/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 51, in on_update
    validate_fields_for_doctype(self.dt)
  File "/home/user/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 384, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/user/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 616, in validate_fields
    check_link_table_options(d)
  File "/home/user/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 430, in check_link_table_options
    frappe.throw(_("Options must be a valid DocType for field {0} in row {1}").format(d.label, d.idx))
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
frappe.exceptions.ValidationError: Options must be a valid DocType for field Print Style in row 16
```

Likely related to issue [10839](https://github.com/frappe/erpnext/issues/10839)

command ran: `bench update --upgrade --reset`

bench itself is already updated to the latest. It's just the apps now that are to be upgraded to the latest stable.

**Comment by nabinhait** [comment]
Pushed a fix in the latest version, please update again.

**Comment by nimrodflores** [comment]
Hi @nabinhait , thanks. I just retried. Still the same error.

I'd like to point out that [the fix](https://github.com/frappe/erpnext/commit/4ebac3380dc33da15feb70b855b2e38dace7f44a) mentioned in #10839 is for the error generated in `erpnext.patches.v8_9.set_print_zero_amount_taxes`, while this one here is coming from `erpnext.patches.v7_0.remove_features_setup`

Although, I'm not really sure if that makes a difference.

**Comment by nimrodflores** [comment]
Guys, can I ask that this issue be re-opened? @nabinhait

**Comment by soloincc** [comment]
I skipped this patch for now following the **NOT RECOMMENDED** way on [url](https://discuss.erpnext.com/t/how-to-skip-patch-application-if-its-faulty/6666)

I moved to other problems

**Comment by krnkris** [comment]
@nimrodflores 

Refer to:
https://github.com/frappe/erpnext/issues/11712
