### ISSUE TITLE
[Retail Domain : v9.0.0 (master)] New POS Module throwing error while discounting item {only with discount as amount}

### ISSUE THREAD

**Issue by aaimaawebs** [frappe/erpnext#10918]
Very excited to get brand New(v9.0.0) ERPNext to the machine. Applauds for Community & Team.

Fresh installed ERPNext v9.0.0 (master) and testing enhanced POS module. Sounds Good. Almost Enhanced.
One issue I had faced: While **discounting item as amount**, throwing errors while discounting item as the percentage is working very well.

I had tested it with another server as well, with another item as well, but error with discounting module  {only with discount as amount}.

The error is: **Server Error: Please check your server logs or contact tech support.**
& Console Log is:

`base_amount: could not find docfield in method precision() desk.min.js?ver=1506425641.0:2647`

```
Error in Template:
desk.min.js?ver=1506425641.0:2648 var _p=[],print=function(){_p.push.apply(_p,arguments)};with(obj){
_p.push('<p class='frappe-confirm-message\'>Permanently Submit New Sales Invoice 1?</p>');}return _p.join(''); Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
desk.min.js?ver=1506425641.0:1565
```

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 68, in submit_invoice
    doc.run_method("calculate_taxes_and_totals")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 671, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 665, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 88, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 15, in __init__
    self.calculate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 23, in calculate
    self.apply_discount_amount()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 360, in apply_discount_amount
    self.doc.base_discount_amount = flt(self.doc.discount_amount * self.doc.conversion_rate,
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by rohitwaghchaure** [comment]
@aaimaawebs 

Thanks for reporting an issue, we have fixed the issue and soon we'll release it
