### ISSUE TITLE
Error on Company List

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10980]
As mentioned by @nabinhait 

https://discuss.erpnext.com/t/error-on-company-list/28863

Error appear on Company doctype

```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/goal.py", line 86, in get_monthly_goal_graph_data
    month_word = getdate(month_value).strftime('%b')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/data.py", line 41, in getdate
    return parser.parse(string_date).date()
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 404, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
```

**Comment by tundebabzy** [comment]
Hi @addymuliady 
I've not been able to replicate this. Please add steps to replicate.

**Comment by tundebabzy** [comment]
@addymuliady any change?

**Comment by ci2014** [comment]
@tundebabzy I have the error as well.

```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/goal.py", line 86, in get_monthly_goal_graph_data
    month_word = getdate(month_value).strftime('%b')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/data.py", line 42, in getdate
    return parser.parse(string_date).date()
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 404, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
```

**Comment by ci2014** [comment]
The error is gone, so it seems it happens somehow on the beginning or on the end of a month.

**Comment by addymuliady** [comment]
@tundebabzy can you try it now?

It appears again.

**Comment by ci2014** [comment]
@tundebabzy For me as well! Always by end of the month, like now.

**Comment by tundebabzy** [comment]
Can you check what version of `python-dateutil` you have installed? It still works well for me

**Comment by kardmode** [comment]
Got this error today. frappe v10.0.4  (master) and erpnext v10.0.2 (master)
version of python-dateutil is 2.6.1
Setup a new production image and updated with to the latest version of frappe v10.0.5 and erpnext v10.0.4 and no error.

**Comment by kardmode** [comment]
Nevermind dateutil in the virtualenv was older. Updating fixed the error.

**Comment by ci2014** [comment]
@kardmode Can you explain how to update it, so I can try and report if it solves the problem? Thank you.

**Comment by kardmode** [comment]
Got this from a post on the forums
# Assuming you are logged in as frappe or equivalent user who have access to Bench / Frappe / ERPNext
$ cd frappe-bench/
$ source env/bin/activate
$ pip install --upgrade python-dateutil

**Comment by jvfiel** [comment]
@kardmode tried upgrading but mine is already upto date. Still experience the error

**Comment by kardmode** [comment]
I haven't had the issue since updating dateutil and still running the same version of frappe/erpnext as before.
