### ISSUE TITLE
[BUG] __init__() got an unexpected keyword argument 'base_in_words' On Document Save

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#11026]
Updated to V9 Develop Branch and experiencing this issue on the following Doctypes:

- Quotation
- Sales Order
- Delivery Note
- Sales Invoice
- Purchase Order
- Purchase Receipt
- Purchase Invoice

![quotation](https://user-images.githubusercontent.com/21003054/31107075-7c66bcb6-a822-11e7-9dec-8a121cc4c068.png)

**Traceback**

```
Traceback (most recent call last):
  File "/home/staging/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/staging/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/staging/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/staging/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/staging/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 12, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "/home/staging/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/staging/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'base_in_words'
```

**Comment by nabinhait** [comment]
This has already been fixed in develop yesterday.

**Comment by creamdory** [comment]
@nabinhait , yes this is okay now. Thanks!

**Comment by nga168** [comment]
i still error.

**Comment by nabinhait** [comment]
@nga168 Which version and branch are you using?
