### ISSUE TITLE
Test patches by upgrading old version site to new

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#11034]
- Checkout an older version (vx.x.x) for frappe and erpnext
- Create a new site
- Run demo
- bench update

**Comment by tundebabzy** [comment]
My work flow:
- Create a new bench and init
- Checkout frappe to vX.X.X
- Create a new site
- Install ERPNext vX.X.X
- Run demo
- bench update

**Comment by tundebabzy** [comment]
### Patch Failure
#### v7.x.x
```(python)
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2017-03-09 in old (c00dbbc9dadfbe1e)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in execute_patch
    exec(patchmodule.split("execute:")[1],globals())
  File "<string>", line 1, in <module>
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/__init__.py", line 679, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/utils.py", line 153, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 131, in import_doc
    doc.insert()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 245, in insert
    self.run_post_save_methods()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 827, in run_post_save_methods
    self.run_method("on_update")
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 924, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 907, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 206, in on_update
    make_module_and_roles(self)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 767, in make_module_and_roles
    if doc.restrict_to_domain and not frappe.db.exists('Domain', doc.restrict_to_domain):
AttributeError: 'DocType' object has no attribute 'restrict_to_domain'
```

**Comment by tundebabzy** [comment]
### Next Failure
```(python)
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2017-03-09 in old (c00dbbc9dadfbe1e)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in execute_patch
    exec(patchmodule.split("execute:")[1],globals())
  File "<string>", line 1, in <module>
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/__init__.py", line 679, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/utils.py", line 153, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 131, in import_doc
    doc.insert()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self.db_insert()
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 299, in db_insert
    ), list(d.values()))
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/apps/frappe/frappe/database.py", line 154, in sql
    self._cursor.execute(query, values)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/src/mysqlclient/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/tunde/PycharmProjects/bench-repo/frappe-bench/env/src/mysqlclient/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.OperationalError: (1048, "Column 'in_dialog' cannot be null")
```

**Comment by tundebabzy** [comment]
frappe/frappe#4312
