### ISSUE TITLE
DocType object has no attribute 'restrict_to_domain'

### ISSUE THREAD

**Issue by doejon** [frappe/erpnext#11086]
Hi guys!
I just tried to migrate from 7.2 (Yes, I know - a long way) and ran into some issues.
Is this a known failure?

```
bench switch-to-master
Switching for frappe
INFO:bench.utils:git config --unset-all remote.upstream.fetch
INFO:bench.utils:git config --add remote.upstream.fetch '+refs/heads/*:refs/remotes/upstream/*'
INFO:bench.utils:git fetch upstream 
INFO:bench.utils:git checkout master
Already on 'master'
Your branch is up-to-date with 'upstream/master'.
INFO:bench.utils:git merge upstream/master
Already up-to-date.
remote: Counting objects: 20411, done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 20411 (delta 5929), reused 5946 (delta 5901), pack-reused 14421
Receiving objects: 100% (20411/20411), 11.11 MiB | 5.02 MiB/s, done.
Resolving deltas: 100% (17498/17498), completed with 193 local objects.
From https://github.com/frappe/erpnext
 * [new branch]      agri-farm-erpnext -> upstream/agri-farm-erpnext
   57a47a8..7eaeec9  develop    -> upstream/develop
 * [new branch]      fixes_10840 -> upstream/fixes_10840
 + dd133f1...cc71930 gh-pages   -> upstream/gh-pages  (forced update)
 * [new branch]      hofix      -> upstream/hofix
   c99f85d..e0dfd16  hotfix     -> upstream/hotfix
 * [new branch]      revert-10986-uom_fix1 -> upstream/revert-10986-uom_fix1
 * [new branch]      staging    -> upstream/staging
 * [new branch]      v7.x.x     -> upstream/v7.x.x
 * [new branch]      v8.x.x     -> upstream/v8.x.x
 * [new tag]         v7.2.28    -> v7.2.28
 * [new tag]         v7.2.29    -> v7.2.29
 * [new tag]         v7.2.30    -> v7.2.30
 * [new tag]         v7.2.31    -> v7.2.31
 * [new tag]         v7.2.32    -> v7.2.32
 * [new tag]         v8.0.0     -> v8.0.0
 * [new tag]         v8.0.1     -> v8.0.1
 * [new tag]         v8.0.10    -> v8.0.10
 * [new tag]         v8.0.11    -> v8.0.11
 * [new tag]         v8.0.12    -> v8.0.12
 * [new tag]         v8.0.13    -> v8.0.13
 * [new tag]         v8.0.14    -> v8.0.14
 * [new tag]         v8.0.15    -> v8.0.15
 * [new tag]         v8.0.16    -> v8.0.16
 * [new tag]         v8.0.17    -> v8.0.17
 * [new tag]         v8.0.18    -> v8.0.18
 * [new tag]         v8.0.19    -> v8.0.19
 * [new tag]         v8.0.2     -> v8.0.2
 * [new tag]         v8.0.20    -> v8.0.20
 * [new tag]         v8.0.21    -> v8.0.21
 * [new tag]         v8.0.22    -> v8.0.22
 * [new tag]         v8.0.23    -> v8.0.23
 * [new tag]         v8.0.24    -> v8.0.24
 * [new tag]         v8.0.25    -> v8.0.25
 * [new tag]         v8.0.26    -> v8.0.26
 * [new tag]         v8.0.27    -> v8.0.27
 * [new tag]         v8.0.28    -> v8.0.28
 * [new tag]         v8.0.29    -> v8.0.29
 * [new tag]         v8.0.3     -> v8.0.3
 * [new tag]         v8.0.30    -> v8.0.30
 * [new tag]         v8.0.31    -> v8.0.31
 * [new tag]         v8.0.32    -> v8.0.32
 * [new tag]         v8.0.33    -> v8.0.33
 * [new tag]         v8.0.34    -> v8.0.34
 * [new tag]         v8.0.35    -> v8.0.35
 * [new tag]         v8.0.36    -> v8.0.36
 * [new tag]         v8.0.37    -> v8.0.37
 * [new tag]         v8.0.38    -> v8.0.38
 * [new tag]         v8.0.39    -> v8.0.39
 * [new tag]         v8.0.4     -> v8.0.4
 * [new tag]         v8.0.40    -> v8.0.40
 * [new tag]         v8.0.41    -> v8.0.41
 * [new tag]         v8.0.42    -> v8.0.42
 * [new tag]         v8.0.43    -> v8.0.43
 * [new tag]         v8.0.44    -> v8.0.44
 * [new tag]         v8.0.45    -> v8.0.45
 * [new tag]         v8.0.46    -> v8.0.46
 * [new tag]         v8.0.47    -> v8.0.47
 * [new tag]         v8.0.48    -> v8.0.48
 * [new tag]         v8.0.49    -> v8.0.49
 * [new tag]         v8.0.5     -> v8.0.5
 * [new tag]         v8.0.50    -> v8.0.50
 * [new tag]         v8.0.51    -> v8.0.51
 * [new tag]         v8.0.6     -> v8.0.6
 * [new tag]         v8.0.7     -> v8.0.7
 * [new tag]         v8.0.8     -> v8.0.8
 * [new tag]         v8.0.9     -> v8.0.9
 * [new tag]         v8.1.0     -> v8.1.0
 * [new tag]         v8.1.1     -> v8.1.1
 * [new tag]         v8.1.2     -> v8.1.2
 * [new tag]         v8.1.3     -> v8.1.3
 * [new tag]         v8.1.4     -> v8.1.4
 * [new tag]         v8.1.5     -> v8.1.5
 * [new tag]         v8.1.6     -> v8.1.6
 * [new tag]         v8.1.7     -> v8.1.7
 * [new tag]         v8.10.0    -> v8.10.0
 * [new tag]         v8.10.1    -> v8.10.1
 * [new tag]         v8.10.2    -> v8.10.2
 * [new tag]         v8.11.0    -> v8.11.0
 * [new tag]         v8.11.1    -> v8.11.1
 * [new tag]         v8.11.2    -> v8.11.2
 * [new tag]         v8.11.3    -> v8.11.3
 * [new tag]         v8.11.4    -> v8.11.4
 * [new tag]         v8.11.5    -> v8.11.5
 * [new tag]         v8.11.6    -> v8.11.6
 * [new tag]         v8.2.0     -> v8.2.0
 * [new tag]         v8.2.1     -> v8.2.1
 * [new tag]         v8.2.2     -> v8.2.2
 * [new tag]         v8.2.3     -> v8.2.3
 * [new tag]         v8.2.4     -> v8.2.4
 * [new tag]         v8.2.5     -> v8.2.5
 * [new tag]         v8.3.0     -> v8.3.0
 * [new tag]         v8.3.1     -> v8.3.1
 * [new tag]         v8.3.2     -> v8.3.2
 * [new tag]         v8.3.3     -> v8.3.3
 * [new tag]         v8.3.4     -> v8.3.4
 * [new tag]         v8.3.5     -> v8.3.5
 * [new tag]         v8.3.6     -> v8.3.6
 * [new tag]         v8.4.0     -> v8.4.0
 * [new tag]         v8.4.1     -> v8.4.1
 * [new tag]         v8.4.2     -> v8.4.2
 * [new tag]         v8.4.3     -> v8.4.3
 * [new tag]         v8.5.0     -> v8.5.0
 * [new tag]         v8.5.1     -> v8.5.1
 * [new tag]         v8.5.2     -> v8.5.2
 * [new tag]         v8.5.3     -> v8.5.3
 * [new tag]         v8.5.4     -> v8.5.4
 * [new tag]         v8.5.5     -> v8.5.5
 * [new tag]         v8.6.0     -> v8.6.0
 * [new tag]         v8.6.1     -> v8.6.1
 * [new tag]         v8.6.2     -> v8.6.2
 * [new tag]         v8.6.3     -> v8.6.3
 * [new tag]         v8.6.4     -> v8.6.4
 * [new tag]         v8.6.5     -> v8.6.5
 * [new tag]         v8.6.6     -> v8.6.6
 * [new tag]         v8.7.0     -> v8.7.0
 * [new tag]         v8.7.1     -> v8.7.1
 * [new tag]         v8.7.2     -> v8.7.2
 * [new tag]         v8.7.3     -> v8.7.3
 * [new tag]         v8.8.0     -> v8.8.0
 * [new tag]         v8.8.1     -> v8.8.1
 * [new tag]         v8.8.2     -> v8.8.2
 * [new tag]         v8.8.3     -> v8.8.3
 * [new tag]         v8.8.4     -> v8.8.4
 * [new tag]         v8.8.5     -> v8.8.5
 * [new tag]         v8.8.6     -> v8.8.6
 * [new tag]         v8.9.0     -> v8.9.0
 * [new tag]         v8.9.1     -> v8.9.1
 * [new tag]         v8.9.2     -> v8.9.2
 * [new tag]         v9.0.0     -> v9.0.0
 * [new tag]         v9.0.1     -> v9.0.1
 * [new tag]         v9.0.2     -> v9.0.2
 * [new tag]         v9.0.3     -> v9.0.3
 * [new tag]         v9.0.4     -> v9.0.4
 * [new tag]         v9.0.5     -> v9.0.5
 * [new tag]         v9.0.6     -> v9.0.6
 * [new tag]         v9.0.7     -> v9.0.7
 * [new tag]         v9.0.8     -> v9.0.8
 * [new tag]         v9.0.9     -> v9.0.9
 * [new tag]         v9.1.0     -> v9.1.0
 * [new tag]         v9.1.1     -> v9.1.1
Switching for erpnext
INFO:bench.utils:git config --unset-all remote.upstream.fetch
INFO:bench.utils:git config --add remote.upstream.fetch '+refs/heads/*:refs/remotes/upstream/*'
INFO:bench.utils:git fetch upstream 
INFO:bench.utils:git checkout master
Already on 'master'
Your branch is up-to-date with 'upstream/master'.
INFO:bench.utils:git merge upstream/master
Already up-to-date.
Successfully switched branches for:
frappe
erpnext
()
Switched to master
Please run `bench update --patch` to be safe from any differences in database schema
dev@office:~/frappe-bench$ bench update --patch
Backing up sites...
Patching sites...
Migrating site1.local
Executing execute:frappe.utils.global_search.setup_global_search_table() in site1.local (1bd3e0294d)
Success
Executing frappe.patches.v8_0.update_global_search_table in site1.local (1bd3e0294d)
Success
Executing frappe.patches.v7_2.remove_in_filter in site1.local (1bd3e0294d)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2017-03-09 in site1.local (1bd3e0294d)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dev/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/dev/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/dev/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/dev/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in execute_patch
    exec(patchmodule.split("execute:")[1],globals())
  File "<string>", line 1, in <module>
  File "/home/dev/frappe-bench/apps/frappe/frappe/__init__.py", line 679, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/utils.py", line 153, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/dev/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 131, in import_doc
    doc.insert()
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 245, in insert
    self.run_post_save_methods()
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 827, in run_post_save_methods
    self.run_method("on_update")
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 924, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 907, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/dev/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/dev/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 206, in on_update
    make_module_and_roles(self)
  File "/home/dev/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 767, in make_module_and_roles
    if doc.restrict_to_domain and not frappe.db.exists('Domain', doc.restrict_to_domain):
AttributeError: 'DocType' object has no attribute 'restrict_to_domain'

```

**Comment by doejon** [comment]
Resolved by manually migrating db as mentioned here:

https://discuss.erpnext.com/t/bench-upgrade-error--mysql-exceptions-operationalerror-1048-column-in-dialog-cannot-be-null/22892/5
