### ISSUE TITLE
Error on upgrade, domianification of platform

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11166]
From https://discuss.erpnext.com/t/v8-to-v9-upgrade-error-domianification/29228

No one has responded to my post in a couple days, but in looking at this more it seems the function being called is not aware that my current database does not have any of the domain stuff in it and is now causing an error. I think the function needs to be corrected to take this into account.

**Comment by jwrober** [comment]
Forgot to add the traceback here

```
Executing frappe.patches.v8_0.update_records_in_global_search #11-05-2017 in erpnext-dev (0acfbbe28584367f)
Updating Global Search              : [========================================]Success
Executing execute:frappe.reload_doc('core', 'doctype', 'role') #2017-05-23 in erpnext-dev (0acfbbe28584367f)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/erpnext-dev/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/patch_handler.py", line 81, in execute_patch
    exec(patchmodule.split("execute:")[1],globals())
  File "<string>", line 1, in <module>
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/__init__.py", line 679, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/utils.py", line 153, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/modules/import_file.py", line 131, in import_doc
    doc.insert()
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 245, in insert
    self.run_post_save_methods()
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 827, in run_post_save_methods
    self.run_method("on_update")
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 924, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 907, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 206, in on_update
    make_module_and_roles(self)
  File "/home/erpnext/erpnext-dev/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 767, in make_module_and_roles
    if doc.restrict_to_domain and not frappe.db.exists('Domain', doc.restrict_to_domain):
AttributeError: 'DocType' object has no attribute 'restrict_to_domain'
```

**Comment by dvdl16** [comment]
I'm also stuck with this one. Can someone provide any help, short of me doing an install from scratch?

**Comment by dvdl16** [comment]
Adding the row ‘restrict_to_domain’ VARCHAR(40) to the table tabDocType fixed it for me

**Comment by jwrober** [comment]
@dvdl16 - how did you know to add this column to the table? is that the correct data type?

**Comment by jwrober** [comment]
I don't see this issue fixed, but here is the workaround steps to upgrade from v8 to v9

```
bench mysql
ALTER TABLE tabDocType ADD COLUMN restrict_to_domain VARCHAR(40);
bench --force reload-doc core doctype page
bench update
bench restart
```

**Comment by tundebabzy** [comment]
frappe/frappe#4312 should fix it

**Comment by tundebabzy** [comment]
Please follow progress on this frappe/frappe#4312
