### ISSUE TITLE
[Bug] Production Planning: Material Request creation not working

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11190]
![screen shot 2017-10-14 at 12 53 51 am](https://user-images.githubusercontent.com/910238/31562766-4f84ec4e-b07a-11e7-9d49-8ba7825040b3.png)

error log

```
Failed to load resource: the server responded with a status of 417 (EXPECTATION FAILED)
desk.min.js:1565 Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/handler.py", line 81, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/desk/form/run_method.py", line 36, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/model/document.py", line 924, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/model/document.py", line 907, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-10-11/apps/erpnext/erpnext/manufacturing/doctype/production_planning_tool/production_planning_tool.py", line 433, in raise_material_requests
    frappe.throw(_("Please enter Warehouse for which Material Request will be raised"))
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-10-11/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Please enter Warehouse for which Material Request will be raised
```

**Comment by Zlash65** [comment]
The error is only raised when no Warehouse is selected for me. Can you maybe try it again ?

**Comment by tundebabzy** [comment]
Also works for me except Warehouse isn't selected.

**Comment by Kishan0330** [comment]
Getting the Server Error when **not selected any warehouse** in filter.
[Screencast from 10-06-24 09:12:09 PM IST.webm](https://github.com/frappe/erpnext/assets/117427350/71ac26bd-f3c2-49ee-8f0f-5085b05e22f7)
