### ISSUE TITLE
v8.x.x - Error on Setup

### ISSUE THREAD

**Issue by brownharryb** [frappe/erpnext#11254]
Hi all,
This gives error upon setup because the ```create_custom_fields``` is missing in source module 
https://github.com/frappe/frappe/blob/v8.x.x/frappe/custom/doctype/custom_field/custom_field.py (v8.x.x)

https://github.com/frappe/erpnext/blob/f55a33890f1167ef2c575c38fcb3c7d1208f9b56/erpnext/setup/setup_wizard/healthcare.py#L3

Regards

**Comment by joolsr** [comment]
Healthcare module wasn't merged until version 9.xx .

**Comment by brownharryb** [comment]
Hi @joolsr 
Thanks for the reply.
The thing is the healthcare module is not really the issue, the issue is when I try to setup frappe v8.x.x against erpnext v8.x.x, it results in an error and I tracked it to this. If someone has successfully setup frappe v8.x.x with erpnext v8.x.x, please diregard this issue and point me in the right direction(maybe I am doing something wrong).

Thanks.

**Comment by tundebabzy** [comment]
@brownharryb 
Please post the full traceback. Perhaps it's a circular import situation but we can't investigate that without the full traceback

**Comment by brownharryb** [comment]
Hi @tundebabzy 
Please see below.
It displays this on setup wizard completion
![v8 x x_err_setup](https://user-images.githubusercontent.com/17238907/31882592-34957194-b7df-11e7-9b7e-9ceaef15833f.png)

and gives this traceback in logs
```
Request Error
Traceback (most recent call last):
  File "/home/boma/benches/bench1/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/boma/benches/bench1/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/boma/benches/bench1/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/boma/benches/bench1/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/boma/benches/bench1/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 40, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/boma/benches/bench1/apps/frappe/frappe/__init__.py", line 903, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/boma/benches/bench1/apps/frappe/frappe/__init__.py", line 688, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/boma/benches/bench1/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 13, in <module>
    from .healthcare import setup_healthcare
  File "/home/boma/benches/bench1/apps/erpnext/erpnext/setup/setup_wizard/healthcare.py", line 3, in <module>
    from frappe.custom.doctype.custom_field.custom_field import create_custom_fields
```

Thanks.

**Comment by tundebabzy** [comment]
#11289
