### ISSUE TITLE
System Setting Password Policy Issue 

### ISSUE THREAD

**Issue by ShehataGhattas** [frappe/erpnext#11255]
when we enable this feature there is an system error at any place has password filed

**Comment by tundebabzy** [comment]
What is the error?

**Comment by ShehataGhattas** [comment]
https://egypro.erpnext.com/?new_password=XXXXXX&cmd=frappe.core.doctype.user.user.test_password_strength&_=1508435186166 500 (Internal Server Error)


https://egypro.erpnext.com/?new_password=XXXXXXFGGF&cmd=frappe.core.doctype.user.user.test_password_strength&_=1508435186168

**Comment by tundebabzy** [comment]
```(python)
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/core/doctype/user/user.py", line 567, in test_password_strength
    result = _test_password_strength(new_password, user_inputs=user_data)
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/utils/password_strength.py", line 14, in test_password_strength
    "feedback": get_feedback(result.get('score'), result.get('sequence'))
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/utils/password_strength.py", line 57, in get_feedback
    feedback = get_match_feedback(longest_match, len(sequence) == 1)
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/utils/password_strength.py", line 153, in get_match_feedback
    return (pattern_fn())
  File "/home/frappe/benches/bench-2017-10-18/apps/frappe/frappe/utils/password_strength.py", line 106, in fun_repeat
    if len(match["repeated_char"]) == 1:
KeyError: u'repeated_char'
```

**Comment by tundebabzy** [comment]
Please follow progress of the fix of the issue on frappe/frappe#4353

**Comment by ShehataGhattas** [comment]
@tundebabzy 
i have done your change but with no success please once your commit was published let me know may be i have done something wrong .

**Comment by strixaluco** [comment]
@ShehataGhattas, please try to type with punctuation marks and capital letters, as it's hard to read the text.

**Comment by tundebabzy** [comment]
@ShehataGhattas fix has been merged. Might take a day or two before it's live

**Comment by ShehataGhattas** [comment]
Thanks alot for your suppoort
