### ISSUE TITLE
PayPal credentials fail to validate

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#11293]
New user reports this https://discuss.erpnext.com/t/invalid-payment-gateway-credentials/29596/3

A similar report with v7 in December https://discuss.erpnext.com/t/does-paypal-integration-app-work-with-v7/18392/4

**Comment by saurabh6790** [comment]
Not able to reproduce the issue! Are you still facing the same issue?

**Comment by clarkejj** [comment]
Thank you saurabh6790 -

jpkuhn responds in his forum post:

I still have the issue.
I also have asked the question to Paypal, in case my Paypal account has a problem. Waiting for an answer.
For the time being, I have used a workaround by creating a Paypal button in a Standard Reply email.

**Comment by ATHRIBIS** [comment]
erpnext 13.7.0
frappe 13.7.0

Hello,
I looked at all the issues, I did not find an answer to the problem.
@clarkejj Did you get an answer from paypal about a possible problem with the paypal account?

Someone proposed this solution (which does not work for me) :

> My problem was, when I copied the stuff over from Paypal, naturally there would be some spaces at the end depending if you dragged over the signature with your mouse.
> Just check that there are no stray spaces like ___ this ____ (without the underscores, of course) at the end of your signature/API ID/API password when you do it on ERPNext.


It worked perfectly with a paypal sandbox account, but with a real paypal account it gives me this error :

```
16:05:21 web.1            | Traceback (most recent call last):
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/paypal_settings/paypal_settings.py", line 131, in validate_paypal_credentials
16:05:21 web.1            |     raise Exception
16:05:21 web.1            | Exception
16:05:21 web.1            | 
16:05:21 web.1            | During handling of the above exception, another exception occurred:
16:05:21 web.1            | 
16:05:21 web.1            | Traceback (most recent call last):
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
16:05:21 web.1            |     response = frappe.api.handle()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
16:05:21 web.1            |     return frappe.handler.handle()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
16:05:21 web.1            |     data = execute_cmd(cmd)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
16:05:21 web.1            |     return frappe.call(method, **frappe.form_dict)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
16:05:21 web.1            |     return fn(*args, **newargs)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
16:05:21 web.1            |     doc.save()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
16:05:21 web.1            |     return self._save(*args, **kwargs)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 320, in _save
16:05:21 web.1            |     self.run_before_save_methods()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 961, in run_before_save_methods
16:05:21 web.1            |     self.run_method("validate")
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_method
16:05:21 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1148, in composer
16:05:21 web.1            |     return composed(self, method, *args, **kwargs)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in runner
16:05:21 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 853, in <lambda>
16:05:21 web.1            |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/paypal_settings/paypal_settings.py", line 94, in validate
16:05:21 web.1            |     self.validate_paypal_credentials()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/paypal_settings/paypal_settings.py", line 134, in validate_paypal_credentials
16:05:21 web.1            |     frappe.throw(_("Invalid payment gateway credentials"))
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 432, in throw
16:05:21 web.1            |     msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
16:05:21 web.1            |     _raise_exception()
16:05:21 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
16:05:21 web.1            |     raise raise_exception(msg)
16:05:21 web.1            | frappe.exceptions.ValidationError: Identifiant de la Passerelle de Paiement Invalides
16:05:21 web.1            | 
16:05:21 web.1            | 10.0.2.2 - - [22/Jul/2021 16:05:21] "POST /api/method/frappe.desk.form.save.savedocs HTTP/1.1" 417 -
```


(frappe.exceptions.ValidationError: Identifiant de la Passerelle de Paiement Invalides 
means --->
frappe.exceptions.ValidationError: Invalides Payment Gateway ID)

**Comment by ATHRIBIS** [comment]
In fact, i just understand that the paypal account was not verified. I think this connection problem comes from the fact that the paypal account is not verified / is suspended, thus preventing the login.
