### ISSUE TITLE
Auto email reports are not working

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#11313]
Hello,

The report that is sent daily to the email of users are not working anymore, this is the error on the error log

"{'retry': 0, 'log': <function log at 0xb5dc3224>, 'site': u'site1.local', 'event': u'daily', 'method_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily', 'method': <function send_daily at 0xb5689294>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 92, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 180, in send_daily
    auto_email_report.send()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 122, in send
    data = self.get_report_content()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 72, in get_report_content
    return self.get_html_table(columns, data)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 101, in get_html_table
    self.name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 67, in render_template
    return get_jenv().get_template(template).render(context)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/emails/auto_email_report.html", line 33, in top-level template code
    {{- frappe.format(row[col.fieldname], col, row) -}}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1213, in format_value
    return frappe.utils.formatters.format_value(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/formatters.py", line 52, in format_value
    return format_time(value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/data.py", line 237, in format_time
    formatted_time = babel.dates.format_time(get_time(txt), locale=(frappe.local.lang or "").replace("-", "_"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/data.py", line 196, in get_time
    return parser.parse(time_str).time()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date."

**Comment by manassolanki** [comment]
I have tried to replicate this, but this is working fine in my local account. Could you please let us know which report are you trying?

**Comment by applepipe** [comment]
Sorry, I've forgot to mention that I use pt-BR as default language, also it is a custom report with the filters below:

"{"add_total_row": 0, "sort_by": "Leave Application.creation", "add_totals_row": 0, "sort_order": "asc", "sort_by_next": null, "filters": [["Leave Application", "docstatus", "!=", "2"], ["Leave Application", "status", "!=", "Approved"], ["Leave Application", "status", "!=", "Rejected"], ["Leave Application", "department", "!=", "TI"], ["Leave Application", "department", "!=", "Projetos"], ["Leave Application", "department", "!=", "Recursos Humanos"], ["Leave Application", "department", "!=", "Financeiro"], ["Leave Application", "department", "!=", "Jur\u00eddico"], ["Leave Application", "department", "!=", "Fiscal"], ["Leave Application", "department", "!=", "Limpeza"], ["Leave Application", "department", "!=", "Vendas"], ["Leave Application", "department", "!=", "Comercial"], ["Leave Application", "department", "!=", "Faturamento"]], "sort_order_next": "desc", "columns": [["name", "Leave Application"], ["status", "Leave Application"], ["leave_type", "Leave Application"], ["from_date", "Leave Application"], ["to_date", "Leave Application"], ["a_partir_da_hora", "Leave Application"], ["ate_a_hora", "Leave Application"], ["total_leave_days", "Leave Application"], ["employee", "Leave Application"], ["employee_name", "Leave Application"], ["department", "Leave Application"], ["designation", "Leave Application"], ["leave_approver", "Leave Application"], ["leave_approver_name", "Leave Application"]]}"

**Comment by umairsy** [comment]
Hello,

That's too many filters. After applying all the filters, if there is no result found, then also auto-email of the report is not generated. Please try with the lesser report, just to check if the feature of auto-email report working fine in your account or no. Default language should not be issue in sending an email. Since this is working for us and other users, closing this Github Issue for now. If issue still replicates in your account, feel free to reopen.
