### ISSUE TITLE
Search crashes each time

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#11350]
Dear Erpnext,

I installed ERPnext on different systems (vps and local) with 2 different machines but both of them has the same issue. When you try to search you get an error.

5b9ca8263c68d9bb.help how can I put that table where it belongs?

Here is the error log: 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 30, in get_help
    return HelpDatabase().search(text)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 87, in search
    select title, intro, path from help where match(content) against (%s) limit 10''', ('%'+words+'%', words))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 152, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1146, "Table '5b9ca8263c68d9bb.help' doesn't exist")

**Comment by Ferohers** [comment]
bench migrate solved the issue.
