### ISSUE TITLE
bulk import of item re-order level and re-order quantity not working

### ISSUE THREAD

**Issue by jpkuhn** [frappe/erpnext#11378]
In Data Import Tool,
- Select Type of document to download : Item
- Click unselect all,
- Select "Re-order Level" and "Re-order Qty"
- Click Download with data (Excel format)

I get SERVER ERROR
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/api.py", line 53, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/core/page/data_import_tool/exporter.py", line 273, in get_template
    build_field_columns(doctype)
  File "/home/frappe/benches/bench-2017-10-25/apps/frappe/frappe/core/page/data_import_tool/exporter.py", line 81, in build_field_columns
    if field and ((select_columns and f[0] in select_columns[dt]) or not select_columns):
KeyError: u'Item'

**Comment by umairsy** [comment]
If you want to over-write values in the existing items, then Name column must be there. In the Name column, Item Code should be entered. Please update your excel file and try again.

If issue still prevails, please post this issue on the forum. https://discuss.erpnext.com
