### ISSUE TITLE
user_permissions file not found

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#11374]
This http query url in my browser (I don't recall what link where or what action wrote it there) - 

https://aproposcomputing.com/desk#user-permissions

resulted in a blank webpage with this message box:

 Something went wrong
Close
Server Error: Please check your server logs or contact tech support.

So I found this in logs/frappe.log:

Site: aproposcomputing.com
Form Dict: {
 "cmd": "frappe.desk.desk_page.getpage",
 "name": "user-permissions"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 32, in getpage
    doc = get(page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 15, in get
    page.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/page/page.py", line 118, in load_assets
    for fname in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/frappe/frappe/core/page/user_permissions'
[ERROR] 2017-10-27 13:48:33,852 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-10-27 13:48:33.846725-192.168.0.1-052

I checked and indeed no user_permissions file there:

frappe@erpnext:~/frappe-bench$ ls -al apps/frappe/frappe/core/page/
total 40
drwxrwxr-x 8 frappe frappe 4096 Oct 13 20:13 .
drwxrwxr-x 6 frappe frappe 4096 Oct 13 20:13 ..
drwxrwxr-x 2 frappe frappe 4096 Oct 13 20:15 background_jobs
drwxrwxr-x 2 frappe frappe 4096 Oct 13 20:15 data_import_tool
drwxrwxr-x 2 frappe frappe 4096 Oct 13 20:15 desktop
-rw-rw-r-- 1 frappe frappe  141 Oct 12  2016 __init__.py
-rw-rw-r-- 1 frappe frappe  220 Oct 13 20:13 __init__.pyc
drwxrwxr-x 3 frappe frappe 4096 Oct 13 20:15 modules_setup
drwxrwxr-x 2 frappe frappe 4096 Oct 13 20:15 permission_manager
drwxrwxr-x 2 frappe frappe 4096 Oct 13 20:15 usage_info

**Comment by clarkejj** [comment]
fix here by simply scp'ing missing files from other box to this one...
