### ISSUE TITLE
No module named recurring_document

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#11382]
Hello there,

I get this error, when running bench trigger-schedule-event hourly:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 30, in trigger_scheduler_event
    frappe.utils.scheduler.trigger(site, event, now=True)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 165, in trigger
    scheduler_task(site=site, event=event, handler=handler, now=True)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 258, in scheduler_task
    frappe.get_attr(handler)()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 915, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 700, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named recurring_document

I was trying to do this manually, because I got the feeling, that my hourly scheduler is not working anymore.

In the Error Log I have:

Title: erpnext.controllers.recurring_document.create_recurring_documents

Error:

Method: hourly, Handler: erpnext.controllers.recurring_document.create_recurring_documents
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 258, in scheduler_task
    frappe.get_attr(handler)()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 915, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 700, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named recurring_document

Versions are:

erpnext 9.2.2
frappe 9.2.3

Any ideas how to get rid of this?

I've already ran bench migrate several times and checked the hooks.py file for things, which might trigger this. I didn't find something.

**Comment by rohitwaghchaure** [comment]
run below commands under frappe-bench folder
`bench clear-cache`
`bench build`

**Comment by ci2014** [comment]
I think bench build did the trick. Thank you.
