### ISSUE TITLE
backup migration error from v7 to v9

### ISSUE THREAD

**Issue by zkhan44499** [frappe/erpnext#11408]
Hi , my old server was running v7 but due to some hardware problem, i lost HDD. I have a backup copy of the database , I had restored to the new server . after restoring I had done bench migrate but I am getting following error. 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN frappe@ No description
Success
Executing frappe.patches.v8_0.set_currency_field_precision      # 2017-05-09 in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_0.rename_print_to_printing in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_0.update_desktop_icons in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_0.update_gender_and_salutation in dltce.local (1521d944b6e92b2d)
Success
Executing execute:frappe.db.sql('update tabReport set module="Desk" where name="ToDo"') in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_1.enable_allow_error_traceback_in_system_settings in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_1.update_format_options_in_auto_email_report in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_1.delete_custom_docperm_if_doctype_not_exists in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_5.delete_email_group_member_with_invalid_emails in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_x.update_user_permission in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_5.patch_event_colors in dltce.local (1521d944b6e92b2d)
Success
Executing frappe.patches.v8_7.update_email_queue_status in dltce.local (1521d944b6e92b2d)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v8_7/update_email_queue_status.py", line 7, in execute
    default_email_account = get_default_outgoing_email_account()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 101, in get_default_outgoing_email_account
    email_account.password = email_account.get_password(raise_exception=False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 663, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password.py", line 16, in get_decrypted_password
    return decrypt(auth[0][0])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password.py", line 106, in decrypt
    frappe.throw(_('Encryption key is invalid, Please check site_config.json'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
frappe.exceptions.ValidationError: Encryption key is invalid, Please check site_config.json
[frappe@eibsol frappe-bench]$ ^C
[frappe@eibsol frappe-bench]$ bench --site dltce.local migrate
Migrating dltce.local
Executing frappe.patches.v8_7.update_email_queue_status in dltce.local (1521d944b6e92b2d)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v8_7/update_email_queue_status.py", line 7, in execute
    default_email_account = get_default_outgoing_email_account()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 101, in get_default_outgoing_email_account
    email_account.password = email_account.get_password(raise_exception=False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 663, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password.py", line 16, in get_decrypted_password
    return decrypt(auth[0][0])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password.py", line 106, in decrypt
    frappe.throw(_('Encryption key is invalid, Please check site_config.json'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
frappe.exceptions.ValidationError: Encryption key is invalid, Please check site_config.json

as i don't have any data from the old server only backup copy of database. 
is their any way to restore.

**Comment by clarkejj** [comment]
Unfortunately without a copy of the original key used to encrypt it, your database cannot be unencrypted. This may explain your case https://discuss.erpnext.com/t/frappe-exceptions-validationerror-encryption-key-is-invalid-please-check-site-config-json/27244

This is a data related issue that is beyond the means of ERPNext to fix or restore.

**Comment by Spixmaster** [comment]
@clarkejj I think your information is misleading. It is not the whole database that is encrypted. From what I have read, it is only sensible data like payment API keys and e-mail passwords.
