### ISSUE TITLE
Can't Explore Module page

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#11548]
POST  500 (INTERNAL SERVER ERROR)

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 920, in call
    return fn(*args, **newargs)
TypeError: get() takes exactly 1 argument (0 given)

**Comment by rmehta** [comment]
Can you share steps for replication?

**Comment by AlaaBadry** [comment]
Dear @rmehta 
Thanks for your help what is the replication

**Comment by tundebabzy** [comment]
@AlaaBadry
Can you share steps to  reproduce the issue

**Comment by pratu16x7** [comment]
Possible case: https://github.com/frappe/frappe/issues/4117
