### ISSUE TITLE
Unable to cancel Production Order

### ISSUE THREAD

**Issue by sunnyakaxd** [frappe/erpnext#11576]
While trying to cancel a production order, following error is thrown
```
Traceback (most recent call last):
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/desk/form/save.py", line 45, in cancel
    doc.cancel()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 783, in cancel
    self._cancel()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 773, in _cancel
    self.save()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_post_save_methods()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 832, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 964, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 947, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 192, in on_cancel
    self.update_reserved_qty_for_production()
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 418, in update_reserved_qty_for_production
    stock_bin.update_reserved_qty_for_production()
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 93, in update_reserved_qty_for_production
    self.db_set('reserved_qty_for_production', self.reserved_qty_for_production)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 897, in db_set
    self.modified, self.modified_by, update_modified=update_modified)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/database.py", line 674, in set_value
    values, debug=debug)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'reserved_qty_for_production' cannot be null")

Traceback (most recent call last):
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/desk/form/save.py", line 45, in cancel
    doc.cancel()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 783, in cancel
    self._cancel()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 773, in _cancel
    self.save()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_post_save_methods()
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 832, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 964, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 947, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 192, in on_cancel
    self.update_reserved_qty_for_production()
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 418, in update_reserved_qty_for_production
    stock_bin.update_reserved_qty_for_production()
  File "/home/ntexadmin/new-ip-bench/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 93, in update_reserved_qty_for_production
    self.db_set('reserved_qty_for_production', self.reserved_qty_for_production)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/model/document.py", line 897, in db_set
    self.modified, self.modified_by, update_modified=update_modified)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/database.py", line 674, in set_value
    values, debug=debug)
  File "/home/ntexadmin/new-ip-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ntexadmin/new-ip-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'reserved_qty_for_production' cannot be null")
```
While debugging the same, [following code line](https://github.com/frappe/erpnext/blob/50616da9050a425a53f7b1fb82d5efe5b9a32164/erpnext/stock/doctype/bin/bin.py#L87)

Snippet from apps/erpnext/erpnext/stock/doctype/bin/bin.py
```
	def update_reserved_qty_for_production(self):
		'''Update qty reserved for production from Production Item tables
			in open production orders'''
		self.reserved_qty_for_production = frappe.db.sql('''select sum(required_qty - transferred_qty)
			from `tabProduction Order` pro, `tabProduction Order Item` item
			where
				item.item_code = %s
				and item.parent = pro.name
				and pro.docstatus = 1 
				and item.source_warehouse = %s
				and pro.status not in ("Stopped", "Completed")''', (self.item_code, self.warehouse))[0][0]

		self.set_projected_qty()

		self.db_set('reserved_qty_for_production', self.reserved_qty_for_production)
		self.db_set('projected_qty', self.projected_qty)
```

caused the issue, as i had no production orders not in completed or stopped stage, hence causing a None value to be returned. Will a simple None handling solve the issue, or am i missing something.

Versions:
erpnext 9.2.4
frappe 9.2.6

**Comment by sunnyakaxd** [comment]
Is it simply a non None handling error which should be 0 if nothing is found? -_-

**Comment by tundebabzy** [comment]
> Will a simple None handling solve the issue, or am i missing something.

Yes it should
