### ISSUE TITLE
frappe.exceptions.DuplicateEntryError: (u'Opportunity Type', u'Sales', IntegrityError(1062, u"Duplicate entry 'Sales' for key 'PRIMARY'"))

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#11619]
```python
Executing erpnext.patches.v9_1.create_issue_opportunity_type in site1.local (1bd3e0294da19198)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vagrant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/vagrant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/vagrant/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/vagrant/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/vagrant/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/vagrant/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/vagrant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/vagrant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/vagrant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/vagrant/frappe-bench/apps/erpnext/erpnext/patches/v9_1/create_issue_opportunity_type.py", line 34, in execute
    frappe.get_doc(dict(doctype = 'Opportunity Type', name=name)).insert()
  File "/vagrant/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in insert
    raise e
frappe.exceptions.DuplicateEntryError: (u'Opportunity Type', u'Sales', IntegrityError(1062, u"Duplicate entry 'Sales' for key 'PRIMARY'"))
```

I think the line https://github.com/frappe/erpnext/blob/d9978d9c4f2e9301e031b6e57901b12979e8aaef/erpnext/patches/v9_1/create_issue_opportunity_type.py#L33 should be

```python
if not frappe.db.exists("Opportunity Type", name):
```

**Comment by nabinhait** [comment]
fixed
