### ISSUE TITLE
Syntax error when i start the bench using bench start.Fresh installation

### ISSUE THREAD

**Issue by maneshom** [frappe/erpnext#11645]
16:09:26 watch.1          | Cannot babelify /home/ubuntu/frappe-bench/apps/erpne                                                                                        xt/erpnext/public/js/controllers/transaction.js
16:09:26 watch.1          | { SyntaxError: unknown: Unexpected token, expected ;                                                                                         (1154:11)
16:09:26 watch.1          |   1152 |                    return s
16:09:26 watch.1          |   1153 |                            query : "erpnext                                                                                        .controllers.queries.get_batch_no",
16:09:26 watch.1          | > 1154 |                            filters: filters
16:09:26 watch.1          |        |                                   ^
16:09:26 watch.1          |   1155 |                    }
16:09:26 watch.1          |   1156 |            }
16:09:26 watch.1          |   1157 |    },

**Comment by maneshom** [comment]
After i updated the bench.it changed to the following error

 Wrote js/item-dashboard.min.js - 8.14 KB
16:24:49 watch.1          | events.js:160
16:24:49 watch.1          |       throw er; // Unhandled 'error' event
16:24:49 watch.1          |       ^
16:24:49 watch.1          |
16:24:49 watch.1          | Error: watch /home/ubuntu/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order_calendar.js ENOSPC
16:24:49 watch.1          |     at exports._errnoException (util.js:1020:11)
16:24:49 watch.1          |     at FSWatcher.start (fs.js:1451:19)
16:24:49 watch.1          |     at Object.fs.watch (fs.js:1478:11)
16:24:49 watch.1          |     at createFsWatchInstance (/home/ubuntu/frappe-bench/node_modules/chokidar/lib/nodefs-handler.js:37:15)
16:24:49 watch.1          |     at setFsWatchListener (/home/ubuntu/frappe-bench/node_modules/chokidar/lib/nodefs-handler.js:80:15)

**Comment by maneshom** [comment]
Now i executing bench start for every local host hit
