### ISSUE TITLE
v9 update filled with errors

### ISSUE THREAD

**Issue by mjomane** [frappe/erpnext#11781]
Hi

All i did was run bench update. I got the following error:
```
frappe@erpnext:~$ cd frappe-bench
frappe@erpnext:~/frappe-bench$ bench update

INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up-to-date.
remote: Counting objects: 239, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 239 (delta 193), reused 210 (delta 191), pack-reused 25
Receiving objects: 100% (239/239), 53.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (197/197), completed with 99 local objects.
From https://github.com/frappe/frappe
   d5af6dd..bb813c7  develop    -> upstream/develop
   cd32e87..3a65e4f  hotfix     -> upstream/hotfix
   b9855e8..3a65e4f  master     -> upstream/master
   adfc650..3f41695  staging    -> upstream/staging
 * [new tag]         v9.2.13    -> v9.2.13
 * [new tag]         v9.2.11    -> v9.2.11
 * [new tag]         v9.2.12    -> v9.2.12
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solv
e this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWar
ning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/lates
t/security.html#insecureplatformwarning.
  InsecurePlatformWarning
INFO:bench.app:pulling frappe
INFO:bench.utils:git pull  upstream develop
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Updating d5af6dd..bb813c7
Fast-forward
 frappe/__init__.py                                                   |  6 ++++-
 frappe/build.js                                                      |  5 +++++
 frappe/core/doctype/domain/domain.py                                 | 26 ++++++++++++++++++++++
 frappe/custom/doctype/customize_form/customize_form.py               |  2 +-
 frappe/desk/doctype/calendar_view/calendar_view.json                 | 22 +++++++++++++++++-
 frappe/desk/page/activity/activity.js                                |  3 ++-
 frappe/integrations/doctype/s3_backup_settings/s3_backup_settings.py |  2 +-
 frappe/model/base_document.py                                        | 13 ++++++++---
 frappe/model/document.py                                             | 76 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------
 frappe/model/meta.py                                                 |  6 +++++
 frappe/patches.txt                                                   |  3 ++-
 frappe/patches/v9_1/resave_domain_settings.py                        |  9 ++++++--
 frappe/patches/v9_1/revert_domain_settings.py                        | 10 +++++++++
 frappe/public/build.json                                             |  2 +-
 frappe/public/js/frappe/form/controls/base_control.js                |  4 +---
 frappe/public/js/frappe/form/controls/password.js                    |  2 +-
 frappe/public/js/frappe/form/dashboard.js                            |  3 ++-
 frappe/public/js/frappe/form/grid.js                                 |  2 +-
 frappe/public/js/frappe/form/quick_entry.js                          | 18 +++++++++------
 frappe/public/js/frappe/views/reports/query_report.js                |  5 ++++-
 frappe/public/js/legacy/form.js                                      | 12 ++++++++--
 frappe/public/js/lib/frappe-charts/frappe-charts.min.iife.js         |  1 +
 frappe/public/js/lib/frappe-charts/frappe-charts.min.js              |  2 --
 frappe/tests/test_permissions.py                                     | 37 ++++++++++++++++++++++++++-----
 frappe/tests/ui/test_test_runner.py                                  | 23 ++++++++++---------
 frappe/utils/goal.py                                                 |  4 ++--
 frappe/utils/print_format.py                                         |  4 ++--
 frappe/utils/selenium_testdriver.py                                  |  2 +-
 frappe/website/doctype/web_form/templates/web_form.html              |  6 ++---
 frappe/www/update-password.html                                      | 18 +++++++--------
 requirements.txt                                                     |  2 +-
 31 files changed, 258 insertions(+), 72 deletions(-)
 create mode 100644 frappe/patches/v9_1/revert_domain_settings.py
 create mode 100755 frappe/public/js/lib/frappe-charts/frappe-charts.min.iife.js
 delete mode 100644 frappe/public/js/lib/frappe-charts/frappe-charts.min.js
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
INFO:bench.utils:git pull  upstream develop
remote: Counting objects: 337, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 337 (delta 252), reused 278 (delta 248), pack-reused 42
Receiving objects: 100% (337/337), 65.19 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (258/258), completed with 126 local objects.
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
   4ec4e3f..50616da  develop    -> upstream/develop
Updating 4ec4e3f..50616da
Fast-forward
 erpnext/__init__.py                                                                     |   2 +-
 erpnext/accounts/doctype/asset/depreciation.py                                          |  19 +-
 erpnext/accounts/doctype/asset/test_asset.py                                            |   4 +-
 erpnext/accounts/doctype/payment_entry/payment_entry.js                                 |   1 -
 erpnext/accounts/doctype/sales_invoice/sales_invoice.js                                 |  25 ++-
 erpnext/accounts/doctype/sales_invoice/sales_invoice.py                                 |  26 +--
 erpnext/accounts/doctype/sales_invoice/tests/test_sales_invoice_with_margin.js          |  36 ++++
 erpnext/accounts/doctype/sales_invoice_item/sales_invoice_item.json                     |  35 +++-
 erpnext/accounts/party.py                                                               |  49 +++---
 erpnext/accounts/utils.py                                                               |   2 +-
 erpnext/buying/doctype/request_for_quotation/request_for_quotation.py                   |   2 +-
 erpnext/config/schools.py                                                               |  14 +-
 erpnext/config/stock.py                                                                 |  29 +--
 erpnext/controllers/accounts_controller.py                                              |   9 +-
 erpnext/controllers/item_variant.py                                                     |  17 ++
 erpnext/controllers/taxes_and_totals.py                                                 |   6 +-
 erpnext/crm/doctype/opportunity/opportunity.py                                          |  18 +-
 erpnext/docs/user/manual/en/stock/item/index.txt                                        |   1 +
 erpnext/docs/user/manual/en/stock/setup/stock-settings.md                               |   8 +
 erpnext/erpnext_integrations/__init__.py                                                |   0
 erpnext/erpnext_integrations/connectors/__init__.py                                     |   0
 erpnext/erpnext_integrations/connectors/github_connection.py                            |  45 +++++
 erpnext/erpnext_integrations/data_migration_mapping/__init__.py                         |   0
 erpnext/erpnext_integrations/data_migration_mapping/issue_to_task/__init__.py           |  11 ++
 erpnext/erpnext_integrations/data_migration_mapping/issue_to_task/issue_to_task.json    |  36 ++++
 erpnext/erpnext_integrations/data_migration_mapping/milestone_to_project/__init__.py    |   6 +
 .../data_migration_mapping/milestone_to_project/milestone_to_project.json               |  36 ++++
 erpnext/erpnext_integrations/data_migration_plan/github_sync/github_sync.json           |  22 +++
 erpnext/hr/doctype/upload_attendance/upload_attendance.json                             |  76 +++++++-
 erpnext/manufacturing/doctype/production_order/production_order.json                    |  32 +++-
 erpnext/manufacturing/doctype/production_order/production_order.py                      |   7 +
 erpnext/modules.txt                                                                     |   1 +
 erpnext/patches.txt                                                                     |   1 +
 erpnext/patches/v9_2/__init__.py                                                        |   0
 erpnext/patches/v9_2/delete_healthcare_domain_default_items.py                          |  16 ++
 erpnext/public/build.json                                                               |   4 +-
 erpnext/public/js/controllers/taxes_and_totals.js                                       |   2 +
 erpnext/public/js/controllers/transaction.js                                            |  38 ++--
 erpnext/public/js/templates/item_quick_entry.html                                       |   3 +
 erpnext/public/js/utils/item_quick_entry.js                                             | 408 +++++++++++++++++++++++++++++++++++++++++++
 erpnext/schools/doctype/assessment_result/assessment_result.js                          |   2 +-
 erpnext/schools/doctype/assessment_result_tool/assessment_result_tool.js                |   3 +-
 erpnext/schools/doctype/fee_schedule/fee_schedule.py                                    |   5 +
 erpnext/schools/report/assessment_plan_status/__init__.py                               |   0
 erpnext/schools/report/assessment_plan_status/assessment_plan_status.js                 |  28 +++
 erpnext/schools/report/assessment_plan_status/assessment_plan_status.json               |  23 +++
 erpnext/schools/report/assessment_plan_status/assessment_plan_status.py                 | 179 +++++++++++++++++++
 erpnext/selling/doctype/quotation/quotation.py                                          |  42 +++++
 erpnext/selling/doctype/quotation/tests/test_quotation_with_margin.js                   |  36 ++++
 erpnext/selling/doctype/quotation_item/quotation_item.json                              |  35 +++-
 erpnext/selling/doctype/sales_order/sales_order.js                                      |   4 +-
 erpnext/selling/doctype/sales_order/sales_order.py                                      |  19 +-
 erpnext/selling/doctype/sales_order/test_sales_order.py                                 |  36 ++++
 erpnext/selling/doctype/sales_order/tests/test_sales_order_with_margin.js               |  38 ++++
 erpnext/selling/doctype/sales_order_item/sales_order_item.json                          |  35 +++-
 erpnext/stock/dashboard/item_dashboard.js                                               |   2 +-
 erpnext/stock/doctype/delivery_note/test_delivery_note_with_margin.js                   |  37 ++++
 erpnext/stock/doctype/delivery_note_item/delivery_note_item.json                        |  35 +++-
 erpnext/stock/doctype/item/item.js                                                      |  23 +--
 erpnext/stock/doctype/item/item.json                                                    |  24 +--
 erpnext/stock/doctype/item/item.py                                                      | 130 ++++++--------
 erpnext/{crm/doctype/item => stock/doctype/item/tests}/test_item.js                     |   1 +
 erpnext/stock/doctype/item_price/test_item_price.js                                     |  22 +++
 erpnext/stock/doctype/item_variant_settings/item_variant_settings.json                  |   6 +-
 erpnext/stock/doctype/stock_settings/stock_settings.json                                |  79 ++++++++-
 erpnext/stock/doctype/stock_settings/stock_settings.py                                  |  32 +++-
 erpnext/stock/doctype/stock_settings/test_stock_settings.js                             |  23 +++
 erpnext/stock/doctype/stock_settings/test_stock_settings.py                             |  54 ++++++
 erpnext/stock/doctype/warehouse/warehouse.py                                            |   4 +-
 erpnext/tests/ui/tests.txt                                                              |   7 +-
 requirements.txt                                                                        |   1 +
 71 files changed, 1758 insertions(+), 254 deletions(-)
 create mode 100644 erpnext/accounts/doctype/sales_invoice/tests/test_sales_invoice_with_margin.js
 create mode 100644 erpnext/erpnext_integrations/__init__.py
 create mode 100644 erpnext/erpnext_integrations/connectors/__init__.py
 create mode 100644 erpnext/erpnext_integrations/connectors/github_connection.py
 create mode 100644 erpnext/erpnext_integrations/data_migration_mapping/__init__.py
 create mode 100644 erpnext/erpnext_integrations/data_migration_mapping/issue_to_task/__init__.py
 create mode 100644 erpnext/erpnext_integrations/data_migration_mapping/issue_to_task/issue_to_task.json
 create mode 100644 erpnext/erpnext_integrations/data_migration_mapping/milestone_to_project/__init__.py
 create mode 100644 erpnext/erpnext_integrations/data_migration_mapping/milestone_to_project/milestone_to_project.json
 create mode 100644 erpnext/erpnext_integrations/data_migration_plan/github_sync/github_sync.json
 create mode 100644 erpnext/patches/v9_2/__init__.py
 create mode 100644 erpnext/patches/v9_2/delete_healthcare_domain_default_items.py
 create mode 100644 erpnext/public/js/templates/item_quick_entry.html
 create mode 100644 erpnext/public/js/utils/item_quick_entry.js
 create mode 100644 erpnext/schools/report/assessment_plan_status/__init__.py
 create mode 100644 erpnext/schools/report/assessment_plan_status/assessment_plan_status.js
 create mode 100644 erpnext/schools/report/assessment_plan_status/assessment_plan_status.json
 create mode 100644 erpnext/schools/report/assessment_plan_status/assessment_plan_status.py
 create mode 100644 erpnext/selling/doctype/quotation/tests/test_quotation_with_margin.js
 create mode 100644 erpnext/selling/doctype/sales_order/tests/test_sales_order_with_margin.js
 create mode 100644 erpnext/stock/doctype/delivery_note/test_delivery_note_with_margin.js
 rename erpnext/{crm/doctype/item => stock/doctype/item/tests}/test_item.js (99%)
 create mode 100644 erpnext/stock/doctype/item_price/test_item_price.js
 create mode 100644 erpnext/stock/doctype/stock_settings/test_stock_settings.js
 create mode 100644 erpnext/stock/doctype/stock_settings/test_stock_settings.py
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext_demo
INFO:bench.utils:git pull  upstream master
From https://github.com/frappe/erpnext_demo
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.utils:find . -name "*.pyc" -delete
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solv
e this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWar
ning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/lates
t/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
INFO:bench.utils:./env/bin/pip install -q -r /home/frappe/bench-repo/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solv
e this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWar
ning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/lates
t/security.html#insecureplatformwarning.
  InsecurePlatformWarning
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext_demo/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe/requirements.txt
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solv
e this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWar
ning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/lates
t/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Updating node libraries...
INFO:bench.utils:npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":
"linux","arch":"ia32"})
npm WARN frappe@ No description
Backing up sites...
Patching sites...
Migrating erpnext.vm
Executing frappe.patches.v9_1.resave_domain_settings in erpnext.vm (d56cb677ea)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v9_1/resave_domain_settings.py", line 10, in execute
domain.setup_domain()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/domain/domain.py", line 32, in setup_domain
frappe.get_attr(self.data.on_setup)()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/setup.py", line 16, in setup_healthcare
create_lab_test_items()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/setup.py", line 204, in create_lab_test_items
insert_record(records)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/setup.py", line 265, in insert_record
doc = frappe.new_doc(r.get("doctype"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 614, in new_doc
return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 20, in get_new_doc
frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 41, in make_new_doc
set_user_and_static_default_values(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 56, in set_user_and_static_default_values
user_default_value = get_user_default_value(df, defaults, user_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 71, in get_user_default_value
if (frappe.get_meta(df.options).document_type=="Setup"
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 655, in get_meta
return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 33, in get_meta
lambda: Meta(doctype))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 173, in hget
value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 33, in <lambda>
lambda: Meta(doctype))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 72, in __init__
super(Meta, self).__init__("DocType", doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__
self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 77, in load_from_db
super(Meta, self).load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 140, in load_from_db
frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
_raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
raise raise_exception(encode(msg))
frappe.exceptions.DoesNotExistError: DocType Hub Category not found
```

**Comment by umairsy** [comment]
Technical queries on the community forum please.

https://discuss.frappe.io
