### ISSUE TITLE
bench update invalid dependency

### ISSUE THREAD

**Issue by execmd** [frappe/erpnext#11828]
Hello,

Im trying to update with `bench update --reset `but Im stuck with error
  ```
frappe@vps461047:/opt/frappe/frappe$ bench update --reset
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up-to-date.
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages
Requirement already satisfied: olefile in ./env/lib/python2.7/site-packages (from Pillow)
INFO:bench.app:pulling frappe
INFO:bench.utils:git fetch --all
Fetching upstream
INFO:bench.utils:git reset --hard upstream/master
HEAD is now at 08b80bafd Merge branch 'hotfix'
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
INFO:bench.utils:git fetch --all
Fetching upstream
INFO:bench.utils:git reset --hard upstream/develop
HEAD is now at 11938a47e fixed typo (#11825)
INFO:bench.utils:find . -name "*.pyc" -delete
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
INFO:bench.utils:./env/bin/pip install -q -r /opt/frappe/bench-repo/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
Updating node libraries...
INFO:bench.utils:npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch"
:"x64"})
npm WARN frappe@ No description
Backing up sites...
Patching sites...
Migrating erp.rootapi.net
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [=======================                 ]Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/frappe/frappe/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/opt/frappe/frappe/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/frappe/frappe/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/frappe/frappe/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/frappe/frappe/apps/frappe/frappe/commands/site.py", line 217, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/opt/frappe/frappe/apps/frappe/frappe/migrate.py", line 33, in migrate
    frappe.model.sync.sync_all(verbose=verbose)
  File "/opt/frappe/frappe/apps/frappe/frappe/model/sync.py", line 19, in sync_all
    sync_for(app, force, verbose=verbose, reset_permissions=reset_permissions)
  File "/opt/frappe/frappe/apps/frappe/frappe/model/sync.py", line 45, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/opt/frappe/frappe/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/opt/frappe/frappe/apps/frappe/frappe/modules/import_file.py", line 131, in import_doc
    doc.insert()
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 245, in insert
    self.run_post_save_methods()
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 828, in run_post_save_methods
    self.run_method("on_update")
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 965, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 948, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/frappe/frappe/apps/frappe/frappe/model/document.py", line 696, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/frappe/frappe/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 220, in on_update
    self.run_module_method("on_doctype_update")
  File "/opt/frappe/frappe/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 273, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/opt/frappe/frappe/apps/frappe/frappe/modules/utils.py", line 178, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Delivery Trip (erpnext.stock.doctype.delivery_trip.delivery_trip Error: No module named google_maps.google_maps)
```

**Comment by tundebabzy** [comment]
What branch of frappe are you on?

**Comment by execmd** [comment]
```
frappe@vps461047:/opt/frappe/bench-repo$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

```
frappe@vps461047:/opt/frappe/frappe/apps/erpnext$ git status
On branch develop
Your branch is up-to-date with 'upstream/develop'.
```
```
frappe@vps461047:/opt/frappe/frappe/apps/frappe$ git status
On branch master
Your branch is up-to-date with 'upstream/master'.
```

**Comment by tundebabzy** [comment]
Google maps has not yet made it to master branch. It's only on develop. You can either switch frappe to develop branch or switch erpnext to master branch

**Comment by execmd** [comment]
Thanks!
