### ISSUE TITLE
[V10] Delivery Trip - Error message when emailing to Customers

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11889]
Steps:

1. Created new Delivery Trip
2. Submitted.
3. Clicked on Notify Customer's via Email

When clicking on that button, then field "Initial Email Notification Sent" gets ticked, but get this error log.

Traceback (most recent call last):
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_trip/delivery_trip.py", line 188, in notify_customers
    sender_designation=sender_designation)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 69, in render_template
    return get_jenv().from_string(template).render(context)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'doc' is undefined

**Comment by KanchanChauhan** [comment]
@umairsy Can you share the standard reply template you using for this as well to be sure if that is creating issue.

**Comment by umairsy** [comment]
@KanchanChauhan thanks for the hint. It had jinja template {{doc.customer_name}}. Placed it with {{customer_name}} only.

The next issue in the same line is related to print Format.

![screen shot 2017-12-08 at 4 40 35 pm](https://user-images.githubusercontent.com/910238/33763489-ab2f4a16-dc36-11e7-9d68-1f91de2bcaa6.png)

However, email is queued and delivery correctly.

**Comment by KanchanChauhan** [comment]
@umairsy Sent a PR to fix print format issue. Thanks for reporting these issues.
