### ISSUE TITLE
Error in Opening Invoice creation Tool

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11938]
Steps:

1. Inserted two row for the Customer of Sales Invoice.

2. Clicked on Make Invoices button.

Getting Server error on clicking Make Invoice button.

```
Traceback (most recent call last):
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 81, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 36, in runserverobj
    r = doc.run_method(method)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/accounts/doctype/opening_invoice_creation_tool/opening_invoice_creation_tool.py", line 68, in make_invoices
    if not row.qty:
AttributeError: 'OpeningInvoiceCreationToolItem' object has no attribute 'qty'
```

**Comment by tundebabzy** [comment]
#11941
