### ISSUE TITLE
Unable to Backup to Dropbox

### ISSUE THREAD

**Issue by anggras** [frappe/erpnext#11966]
It was working fine for almost a year but it failed recently with error:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox
    did_not_upload, error_log = backup_to_dropbox()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox
    upload_file_to_dropbox(filename, "/database", dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 148, in upload_file_to_dropbox
    create_folder_if_not_exists(folder, dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 172, in create_folder_if_not_exists
    dropbox_client.files_get_metadata(folder)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/base.py", line 482, in files_get_metadata
    None,
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 239, in request
    timeout=timeout)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 330, in request_json_string_with_retry
    timeout=timeout)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 414, in request_json_string
    timeout=timeout,
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

ERPNext: v9.2.21 (master)
Frappe Framework: v9.2.22 (master)

pip packages:
```
ansible (2.0.2.0)
asn1crypto (0.23.0)
bcrypt (3.1.3)
bench (4.1.0, /home/frappe/.bench)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
cryptography (2.1.4)
enum34 (1.1.6)
gitdb (0.6.4)
GitPython (0.3.2rc1)
honcho (1.0.1)
idna (2.6)
ipaddress (1.0.18)
Jinja2 (2.9.6)
MarkupSafe (1.0)
meld3 (1.0.2)
MySQL-python (1.2.5)
paramiko (2.2.1)
pip (9.0.1)
psutil (5.2.2)
pyasn1 (0.2.3)
pycparser (2.18)
pycrypto (2.6.1)
PyNaCl (1.1.2)
pyOpenSSL (17.5.0)
python-apt (1.1.0b1)
python-crontab (2.2.2)
python-dateutil (2.6.0)
PyYAML (3.12)
requests (2.18.4)
semantic-version (2.6.0)
setuptools (36.0.1)
six (1.11.0)
smmap (0.9.0)
supervisor (3.2.0)
urllib3 (1.22)
virtualenv (15.1.0)
wheel (0.29.0)
```

**Comment by umairsy** [comment]
There has been couple of fixes made in the dropbox connector. Please upgrade your ERPNext to the latest version.

Request you to post upgrade related queries on the ERPNext community forum.

https://discuss.erpnext.com
