### ISSUE TITLE
Server Error when saving default All Land Unit

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11994]
App Versions

{
	"erpnext": "9.2.22",
	"erpnext_shopify": "2.0.20",
	"frappe": "9.2.23"
}
Route

Form/Land Unit/All Land Units
Error Report

Traceback (most recent call last):
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/agriculture/doctype/land_unit/land_unit.py", line 42, in validate
    self.area_difference = new_area - self.area
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

Traceback (most recent call last):
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/agriculture/doctype/land_unit/land_unit.py", line 42, in validate
    self.area_difference = new_area - self.area
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Request Data

{
	"type": "POST",
	"args": {
		"doc": "{\"creation\":\"2017-12-13 17:12:36.794925\",\"is_container\":1,\"lft\":1,\"linked_soil_analysis\":[],\"owner\":\"umair.sayyed@icloud.com\",\"rgt\":2,\"area\":null,\"location\":\"{\\\"type\\\":\\\"FeatureCollection\\\",\\\"features\\\":[{\\\"type\\\":\\\"Feature\\\",\\\"properties\\\":{},\\\"geometry\\\":{\\\"type\\\":\\\"Polygon\\\",\\\"coordinates\\\":[[[74.131681,19.722307],[74.132668,19.722368],[74.132443,19.721388],[74.131553,19.721393],[74.131681,19.722307]]]}},{\\\"type\\\":\\\"Feature\\\",\\\"properties\\\":{},\\\"geometry\\\":{\\\"type\\\":\\\"Polygon\\\",\\\"coordinates\\\":[[[74.820457,15.40681],[74.834018,15.402466],[74.82964,15.397873],[74.818225,15.396383],[74.817367,15.403583],[74.820457,15.40681]]]}},{\\\"type\\\":\\\"Feature\\\",\\\"properties\\\":{},\\\"geometry\\\":{\\\"type\\\":\\\"Polygon\\\",\\\"coordinates\\\":[[[74.684114,14.869557],[74.702482,14.86292],[74.688749,14.855868],[74.682827,14.864164],[74.684114,14.869557]]]}}]}\",\"latitude\":null,\"docstatus\":0,\"linked_plant_analysis\":[],\"parent\":null,\"parent_land_unit\":null,\"is_group\":1,\"doctype\":\"Land Unit\",\"modified_by\":\"umair.sayyed@icloud.com\",\"name\":\"All Land Units\",\"idx\":0,\"land_unit_name\":\"All Land Units\",\"modified\":\"2017-12-13 17:29:38.883967\",\"longitude\":null,\"old_parent\":\"\",\"parenttype\":null,\"linked_soil_texture\":[],\"parentfield\":null,\"__last_sync_on\":\"2017-12-13T11:59:39.217Z\"}",
		"action": "Save",
		"cmd": "frappe.desk.form.save.savedocs"
	},
	"btn": {
		"jQuery2240413425997616640341": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 134,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"freeze_message": "Saving",
	"url": "/"
}
Response JSON

{
	"_server_messages": "[\"{\\\"message\\\": \\\"Did not save\\\"}\"]"
}

**Comment by umairsy** [comment]
This error occurs when I clear values in the Longitude, Latitude, Clear all from the Map and try to plot a new land unit.

![screen shot 2017-12-13 at 5 31 57 pm](https://user-images.githubusercontent.com/910238/33937986-a443d714-e02b-11e7-8553-2332b9d99fb2.png)
