### ISSUE TITLE
Error while migrating old sites to v10

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12026]
```
Executing frappe.patches.v8_0.update_records_in_global_search #11-05-2017 in test_site 
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nabinhait/projects/erpnext5/env/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/patches/v8_0/update_records_in_global_search.py", line 7, in execute
    doctypes_with_global_search = get_doctypes_with_global_search(with_child_tables=False)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/utils/global_search.py", line 51, in get_doctypes_with_global_search
    return frappe.cache().get_value('doctypes_with_global_search', _get)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/utils/redis_wrapper.py", line 72, in get_value
    val = generator()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/utils/global_search.py", line 48, in _get
    if frappe.local.module_app[frappe.scrub(d.module)] in installed_apps]
KeyError: u'schools'

```

**Comment by nabinhait** [comment]
Already fixed via https://github.com/frappe/frappe/pull/4617, but it was sent to hotfix branch
