### ISSUE TITLE
Issue in the User Progress.

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#12022]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/user_progress.py", line 17, in get_user_progress_slides
    slides += frappe.get_attr(fn)()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/utilities/user_progress.py", line 279, in get_user_progress_slides
    s.done = get_action_completed_state(s.action_name) or 0
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/setup_progress/setup_progress.py", line 20, in get_action_completed_state
    if d.action_name == action_name][0]
IndexError: list index out of range

**Comment by shreyashah115** [comment]
Hi @manassolanki, how to replicate this?

**Comment by manassolanki** [comment]
Check if user progress isn't completed

**Comment by tundebabzy** [comment]
I switched to develop branch, bench update. The error pops up in Doctype list pages
![screenshot from 2017-12-15 09-49-12](https://user-images.githubusercontent.com/818803/34034265-08c25758-e17e-11e7-9a70-601e046191f4.png)

**Comment by netchampfaris** [comment]
@tundebabzy 
Can you post a screenshot of **Setup Progress** Form?

**Comment by tundebabzy** [comment]
@netchampfaris 
![screenshot-2017-12-15 setup progress](https://user-images.githubusercontent.com/818803/34042099-58b8d92c-e19b-11e7-823c-1fb545abcb54.png)

**Comment by pratu16x7** [comment]
https://github.com/frappe/erpnext/commit/228c341d126ca6f5f21192f3e2f9f7fa91ab6e5c
