### ISSUE TITLE
Payment schedule error updating documents

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12126]
Hello,

After saving and sending, documents that have payment schedule when opened shows status as not saved, but when I try to save it shows this error on console:

Failed to load resource: the server responded with a status of 404 (NOT FOUND)
desk.min.js?ver=1513798557.0:1649 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 684, in validate_update_after_submit
    d._validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 557, in _validate_update_after_submit
    db_values = frappe.get_doc(self.doctype, self.name).as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 638, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 140, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
DoesNotExistError: Payment Schedule None not found"

**Comment by tundebabzy** [comment]
Hi @applepipe
This is already fixed in #12124
