### ISSUE TITLE
error in the setup wizard

### ISSUE THREAD

**Issue by dalwadani** [frappe/erpnext#12153]
App Versions

{
	"erpnext": "9.2.23",
	"frappe": "9.2.24",
	"sijil_schools": "0.0.1"
}
Route

setup-wizard
Error Report

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 40, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 26, in setup_complete
    create_fiscal_year_and_company(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 83, in create_fiscal_year_and_company
    'domain': args.get('domain')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 245, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 828, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 78, in on_update
    install_country_fixtures(self.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 327, in install_country_fixtures
    .format(company_doc.country.lower()))(company_doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 915, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 700, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named saudi arabia.setup
Request Data

{
	"type": "POST",
	"args":{
  "args": {
    "language": "English",
    "country": "Saudi Arabia",
    "timezone": "Asia/Riyadh",
    "currency": "SAR",
    "full_name": "***",
    "email": "***@gmail.com",
    "password": "***",
    "domain": "Education",
    "company_name": "***",
    "company_abbr": "***",
    "company_tagline": "***",
    "bank_account": "بنك الراجحي",
    "fy_start_date": "2017-01-01",
    "fy_end_date": "2017-12-31",
    "cmd": "frappe.desk.page.setup_wizard.setup_wizard.setup_complete"
  }
}

	"url": "/"
}
Response JSON

{
	"_server_messages": "[\"{\\\"message\\\": \\\"Duplicate name Domain Retail\\\"}\", \"{\\\"message\\\": \\\"Duplicate name Domain Education\\\"}\", \"{\\\"message\\\": \\\"Duplicate name Domain Healthcare\\\"}\", \"{\\\"message\\\": \\\"Setting this Address Template as default as there is no other default\\\"}\"]"
}

**Comment by rohitwaghchaure** [comment]
@dalwadani 

Kindly pull latest update and check

**Comment by dalwadani** [comment]
Issue Fixed!
