### ISSUE TITLE
UAE VAT

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#12184]
I have tested the VAT setup in version 10. Please find below areas of attention;

1. In purchase Taxes and Charge template, Consider tax field has been set to Valuation and Total which is resulting in unnecessary increase in the item valuation rate. The VAT is not a cost for any business so it should not be included in item valuation. Please set the Consider tax field to Total and it will solve the accounting entries issue as well as compliance element as well. 

2. While posting purchase invoice error message appear "Cost Center is required in row 1 in Taxes table". This message should not appear because items are being purchased in warehouse and at this point cost center is not relevant (All the transactions are going to balance sheet). 

3. In multi company setup do we have to create all tax templates again for all the companies?

4. In detailed tax invoice print can we add one column in the sales invoice item table to show the vat rate and amount in front of each item instead of showing the item wise tax calculation again at the bottom. This will help businesses where almost every other invoice has more than 50 items per invoice.

**Comment by rohitwaghchaure** [comment]
@ushashmi 

Thanks for your feedback, please see my comments inline

1. In purchase Taxes and Charge template, Consider tax field has been set to Valuation and Total which is resulting in unnecessary increase in the item valuation rate. The VAT is not a cost for any business so it should not be included in item valuation. Please set the Consider tax field to Total and it will solve the accounting entries issue as well as compliance element as well.
:- I have check on local account and we have already set to [Total as default](https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/purchase_taxes_and_charges/purchase_taxes_and_charges.json#L22).
You can fix this using customize form, kindly set the default value as **Total** for the field **Consider Tax or Charge** for in doctype **Purchase Taxes and Charges**

1. While posting purchase invoice error message appear "Cost Center is required in row 1 in Taxes table". This message should not appear because items are being purchased in warehouse and at this point cost center is not relevant (All the transactions are going to balance sheet).
:- Set default cost center in the company master and this issue will fix.
1. In multi company setup do we have to create all tax templates again for all the companies?
:- Yes
1. In detailed tax invoice print can we add one column in the sales invoice item table to show the vat rate and amount in front of each item instead of showing the item wise tax calculation again at the bottom. This will help businesses where almost every other invoice has more than 50 items per invoice.
:- Is there any use case where vat and excise both will be apply on the invoice or only one tax(vat or excise) at a time will be apply. If one tax will be apply at a time then this issue can be fix, but if there are multiple taxes with different rate then it's difficult to show in the item table.

**Comment by ushashmi** [comment]
Excise and VAT will not appear on same invoice because excise will be paid directly by the manufacturer and will be added to item cost. There is no requirement to mention excise separatly on invoice. In almost 95% business we have in uae their all items ate taxable on 5% straight rate. Other 5% are on 0 rate which can be tackled by given tax rate on item master

**Comment by rohitwaghchaure** [comment]
@ushashmi 

Thanks for the details, we have [fixed](https://github.com/frappe/erpnext/pull/12202) this issue and soon we'll release it

**Comment by rohitwaghchaure** [comment]
Kindly pull latest update and check, closing this issue. Feel free to reopen if issue still persists

**Comment by ushashmi** [comment]
@rohitwaghchaure after update to 10.0.3 purchase invoice is giving following error whenever we attach VAT tax template. if we dont attach any tax template then purchase invoice can be submitted 

   doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 51, in validate
    super(PurchaseReceipt, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 31, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 45, in validate
    self.calculate_taxes_and_totals()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 113, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 15, in __init__
    self.calculate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 29, in calculate
    self.set_item_wise_tax_breakup()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 525, in set_item_wise_tax_breakup
    self.doc.other_charges_calculation = get_itemised_tax_breakup_html(self.doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 547, in get_itemised_tax_breakup_html
    update_itemised_tax_data(doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/__init__.py", line 106, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/united_arab_emirates/utils.py", line 12, in update_itemised_tax_data
    row.tax_rate = flt(tax_rate, row.precision("tax_rate"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 666, in precision
    if df.fieldtype in ("Currency", "Float", "Percent"):
AttributeError: 'NoneType' object has no attribute 'fieldtype'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 51, in validate
    super(PurchaseReceipt, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 31, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 45, in validate
    self.calculate_taxes_and_totals()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 113, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 15, in __init__
    self.calculate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 29, in calculate
    self.set_item_wise_tax_breakup()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 525, in set_item_wise_tax_breakup
    self.doc.other_charges_calculation = get_itemised_tax_breakup_html(self.doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 547, in get_itemised_tax_breakup_html
    update_itemised_tax_data(doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/__init__.py", line 106, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/united_arab_emirates/utils.py", line 12, in update_itemised_tax_data
    row.tax_rate = flt(tax_rate, row.precision("tax_rate"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 666, in precision
    if df.fieldtype in ("Currency", "Float", "Percent"):
AttributeError: 'NoneType' object has no attribute 'fieldtype'
