### ISSUE TITLE
Odd SQL Error

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#12295]
Getting odd sql error:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 604, in get_count
    where {1}""".format(','.join(tables), ' and '.join(conditions)), debug=0)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 232, in sql_list
    return [r[0] for r in self.sql(query, values, debug=debug)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 176, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1064, u'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'"[u\'Completed\', u\'Closed\']" and `tabPurchase Receipt Item`.item_code = "00000291\' at line 2')
```

Actually no custom code is there ..can some one double check and confirm?

ERPNext: v9.x.x-develop (15b8801) (develop)
Frappe Framework: v9.x.x-develop (9299103) (develop)

**Comment by tundebabzy** [comment]
Whats the context?

**Comment by joezsweet** [comment]
what you mean?

**Comment by joezsweet** [comment]
can this help?

```
GET /?doctype=Purchase+Receipt&fields=%5B%22%60tabPurchase+Receipt%60.%60name%60%22%2C%22%60tabPurchase+Receipt%60.%60owner%60%22%2C%22%60tabPurchase+Receipt%60.%60docstatus%60%22%2C%22%60tabPurchase+Receipt%60.%60_user_tags%60%22%2C%22%60tabPurchase+Receipt%60.%60_comments%60%22%2C%22%60tabPurchase+Receipt%60.%60modified%60%22%2C%22%60tabPurchase+Receipt%60.%60modified_by%60%22%2C%22%60tabPurchase+Receipt%60.%60_assign%60%22%2C%22%60tabPurchase+Receipt%60.%60_liked_by%60%22%2C%22%60tabPurchase+Receipt%60.%60title%60%22%2C%22%60tabPurchase+Receipt%60.%60grand_total%60%22%2C%22%60tabPurchase+Receipt%60.%60currency%60%22%2C%22%60tabPurchase+Receipt%60.%60supplier%60%22%2C%22%60tabPurchase+Receipt%60.%60supplier_name%60%22%2C%22%60tabPurchase+Receipt%60.%60base_grand_total%60%22%2C%22%60tabPurchase+Receipt%60.%60is_subcontracted%60%22%2C%22%60tabPurchase+Receipt%60.%60transporter_name%60%22%2C%22%60tabPurchase+Receipt%60.%60is_return%60%22%2C%22%60tabPurchase+Receipt%60.%60status%60%22%2C%22%60tabPurchase+Receipt%60.%60per_billed%60%22%2C%22%60tabPurchase+Receipt%60.%60creation%60%22%2C%22%60tabPurchase+Receipt%60.%60parent%60%22%2C%22%60tabPurchase+Receipt%60.%60parenttype%60%22%2C%22%60tabPurchase+Receipt%60.%60parentfield%60%22%2C%22%60tabPurchase+Receipt%60.%60idx%60%22%5D&filters=%5B%5B%22Purchase+Receipt%22%2C%22docstatus%22%2C%22%3C%22%2C%222%22%5D%2C%5B%22Purchase+Receipt%22%2C%22status%22%2C%22not+in%22%2C%5B%22Completed%22%2C%22Closed%22%5D%5D%2C%5B%22Purchase+Receipt+Item%22%2C%22item_code%22%2C%22%3D%22%2C%22000002915%22%5D%5D&order_by=%60tabPurchase+Receipt%60.%60modified%60+desc&start=0&page_length=20&with_comment_count=true&cmd=frappe.desk.reportview.get&_=1514891721366 HTTP/1.1" 200 -
12:44:18 web.1            | 172.18.0.1 - - [02/Jan/2018 12:44:18] "POST / HTTP/1.1" 200 -
12:44:18 web.1            | INFO:werkzeug:172.18.0.1 - - [02/Jan/2018 12:44:18] "POST / HTTP/1.1" 200 -
12:44:18 web.1            | 172.18.0.1 - - [02/Jan/2018 12:44:18] "POST / HTTP/1.1" 200 -
12:44:18 web.1            | INFO:werkzeug:172.18.0.1 - - [02/Jan/2018 12:44:18] "POST / HTTP/1.1" 200 -
12:44:18 web.1            | Traceback (most recent call last):
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
12:44:18 web.1            |     response = frappe.handler.handle()
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
12:44:18 web.1            |     data = execute_cmd(cmd)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
12:44:18 web.1            |     return frappe.call(method, **frappe.form_dict)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
12:44:18 web.1            |     return fn(*args, **newargs)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 604, in get_count
12:44:18 web.1            |     where {1}""".format(','.join(tables), ' and '.join(conditions)), debug=0)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 232, in sql_list
12:44:18 web.1            |     return [r[0] for r in self.sql(query, values, debug=debug)]
12:44:18 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 176, in sql
12:44:18 web.1            |     self._cursor.execute(query)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
12:44:18 web.1            |     result = self._query(query)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
12:44:18 web.1            |     conn.query(q)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
12:44:18 web.1            |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
12:44:18 web.1            |     result.read()
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
12:44:18 web.1            |     first_packet = self.connection._read_packet()
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
12:44:18 web.1            |     packet.check_error()
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
12:44:18 web.1            |     err.raise_mysql_exception(self._data)
12:44:18 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
12:44:18 web.1            |     raise errorclass(errno, errval)
12:44:18 web.1            | ProgrammingError: (1064, u'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'"[u\'Completed\', u\'Closed\']" and `tabPurchase Receipt Item`.item_code = "00000291\' at line 2')
```

**Comment by tundebabzy** [comment]
I meant what causes the error? ALso, some screenshots and stuff will help

**Comment by joezsweet** [comment]
@tundebabzy refer to previous post ..

**Comment by joezsweet** [comment]
seems to be gone ...
