### ISSUE TITLE
LDAP issue

### ISSUE THREAD

**Issue by aleksas** [frappe/erpnext#12368]
Getting 'UnboundLocalError: local variable 'conn' referenced before assignment' error when trying to save LDAP settings.

OS:   Debian GNU/Linux 8.10 (jessie)

Error report

>App Versions
{
	"erpnext": "10.0.6",
	"frappe": "10.0.7"
}
Route
Form/LDAP Settings/LDAP Settings
Error Report
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/ldap_settings/ldap_settings.py", line 14, in validate
    self.validate_ldap_credentails()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/ldap_settings/ldap_settings.py", line 31, in validate_ldap_credentails
    conn.unbind_s()
UnboundLocalError: local variable 'conn' referenced before assignment
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/ldap_settings/ldap_settings.py", line 14, in validate
    self.validate_ldap_credentails()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/ldap_settings/ldap_settings.py", line 31, in validate_ldap_credentails
    conn.unbind_s()
UnboundLocalError: local variable 'conn' referenced before assignment
Request Data
{
	"type": "POST",
	"args": {
		"doc": "{\"modified_by\":\"Administrator\",\"name\":\"LDAP Settings\",\"creation\":\"2018-01-07 20:00:19.811852\",\"enabled\":0,\"modified\":\"2018-01-07 20:00:19.811852\",\"idx\":\"0\",\"doctype\":\"LDAP Settings\",\"owner\":\"Administrator\",\"docstatus\":0,\"__last_sync_on\":\"2018-01-07T15:06:31.931Z\",\"ldap_server_url\":\"ldap.forumsys.com\",\"__unsaved\":1,\"organizational_unit\":\"cn=read-only-admin,dc=example,dc=com\",\"base_dn\":\"dc=example,dc=com\",\"password\":\"*****\",\"ldap_search_string\":\"sAMAccountName={0}\",\"ldap_first_name_field\":\"cn\",\"ldap_email_field\":\"mail\",\"ldap_username_field\":\"name\"}",
		"action": "Save",
		"cmd": "frappe.desk.form.save.savedocs"
	},
	"btn": {
		"jQuery2240154183195666936171": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 2847,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"freeze_message": "Saving",
	"url": "/"
}
Response JSON
{
	"_server_messages": "[\"{\\\"message\\\": \\\"Did not save\\\"}\"]"
}

**Comment by vishdha** [comment]
https://discuss.erpnext.com/t/solved-ldap-error-local-variable-conn-referenced-before-assignment/32456
