### ISSUE TITLE
Something went wrong Close

### ISSUE THREAD

**Issue by shahrukhas** [frappe/erpnext#12503]
Traceback (most recent call last):
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 255, in add_ac
    if ac.is_root:
AttributeError: 'Account' object has no attribute 'is_root'
Report this issue

**Comment by tundebabzy** [comment]
Hi @shahrukhas
This has been fixed. Please check again and report back if it still persists
