### ISSUE TITLE
Error on chat after login

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12608]
Hello,

I'm testing developer branch to report bugs and I'm getting this error after login, this started to happen after the updates on friday 19/01/2018:

"Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/chat/doctype/chat_profile/chat_profile.py", line 87, in create
    profile = get(user, fields = fields)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/chat/doctype/chat_profile/chat_profile.py", line 69, in get
    profile = filter_dict(profile, fields)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/chat/util/util.py", line 57, in filter_dict
    raise KeyError('{key} not in dict.'.format(key = k))
KeyError: 'display_widget not in dict.'"

**Comment by kennethsequeira** [comment]
@applepipe request you to report chat issues on the [frappe](https://github.com/frappe/frappe/issues) repository and follow this issue: https://github.com/frappe/frappe/issues/4725

Chat is built into frappe and is currently under testing. Until it is merged into the master branch, it is best to follow and report the issues in the frappe repository.

**Comment by achillesrasquinha** [comment]
Hi @applepipe, did you try a `bench migrate`?

**Comment by achillesrasquinha** [comment]
Closing this as not replicable anymore.

**Comment by applepipe** [comment]
@kennethsequeira ok, thank you!

@achillesrasquinha I didn't think that it was related, but I get this error on bench migrate:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 45, in migrate
    sync_desktop_icons()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 319, in sync_desktop_icons
    sync_from_app(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 355, in sync_from_app
    desktop_icon.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self.db_insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 318, in db_insert
    self.show_unique_validation_message(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 366, in show_unique_validation_message
    raise frappe.UniqueValidationError(self.doctype, self.name, e)
frappe.exceptions.UniqueValidationError: (u'Desktop Icon', '2de0868945', IntegrityError(1062, u"Duplicate entry 'Lab Test-Administrator-1' for key 'unique_module_name_owner_standard'"))

**Comment by achillesrasquinha** [comment]
What apps have you installed?

**Comment by applepipe** [comment]
@achillesrasquinha 

Just erpnext, I have some icons added with "add to desktop" but no apps installed or core modifications
