### ISSUE TITLE
Getting error on saving Documents

### ISSUE THREAD

**Issue by mudux** [frappe/erpnext#12607]
#### Actual Behaviour
The following erroroccurs:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 12, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 638, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 27, in __init__
    super(PurchaseInvoice, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 19, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    super(Document, self).__init__(kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 54, in __init__
    self.update(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 77, in update
    self.set(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 124, in set
    self.extend(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 152, in extend
    self.append(key, v)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 146, in append
    "Document attached to child table must be a dict or BaseDocument, not " + str(type(value))[1:-1]
ValueError: Document attached to child table must be a dict or BaseDocument, not type 'unicode'`

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 12, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 638, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 27, in __init__
    super(PurchaseInvoice, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 19, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    super(Document, self).__init__(kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 54, in __init__
    self.update(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 77, in update
    self.set(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 124, in set
    self.extend(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 152, in extend
    self.append(key, v)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 146, in append
    "Document attached to child table must be a dict or BaseDocument, not " + str(type(value))[1:-1]
ValueError: Document attached to child table must be a dict or BaseDocument, not type 'unicode'
```

#### Parsed args:
```
doc:{"__islocal":1,"base_write_off_amount":0,"supplied_items":[],"set_posting_time":0,"base_in_words":"","due_date":"2018-01-22","doctype":"Purchase Invoice","ignore_pricing_rule":0,"advances":[],"base_discount_amount":0,"base_total_taxes_and_charges":0,"supplier_name":"new supp","items":[{"__islocal":1,"po_detail":"8da992b1be","stock_qty":1,"base_price_list_rate":0,"image":"","landed_cost_voucher_amount":0,"base_amount":2,"qty":1,"item_tax_rate":"{}","rate":2,"total_weight":0,"owner":"mohamud.a.a@gmail.com","cost_center":"Main - ELPAR","received_qty":0,"stock_uom":"Nos","rm_supp_cost":0,"base_net_amount":2,"page_break":0,"base_net_rate":2,"discount_percentage":0,"item_name":"new item test","amount":2,"net_rate":2,"conversion_factor":1,"warehouse":null,"docstatus":0,"uom":"Nos","doctype":"Purchase Invoice Item","description":"new item test","item_tax_amount":0,"base_rate":2,"item_code":"ITEM-02946","rejected_qty":0,"price_list_rate":0,"allow_zero_valuation_rate":0,"idx":1,"item_group":"All Item Groups","weight_per_unit":0,"purchase_order":"PO-00946","expense_account":"Cost of Goods Sold - ELPAR","parenttype":"Purchase Invoice","valuation_rate":4,"net_amount":2,"is_fixed_asset":0,"parentfield":"items","parent":"New Purchase Invoice 2","name":"New Purchase Invoice Item 2","pricing_rule":null,"serial_no":null,"barcode":null,"last_purchase_rate":null,"income_account":"Sales - ELPAR","actual_qty":0,"supplier_part_no":null,"brand":null,"projected_qty":246,"supplier":null,"has_serial_no":0,"weight_uom":null,"min_order_qty":"","update_stock":0,"has_batch_no":0,"batch_no":null,"delivered_by_supplier":0,"gross_profit":-4,"margin_type":"","margin_rate_or_amount":0,"rate_with_margin":0}],"taxes_and_charges_added":0,"is_paid":0,"is_return":0,"taxes":[],"base_rounding_adjustment":0,"write_off_amount":0,"party_account_currency":"KES","net_total":2,"owner":"mohamud.a.a@gmail.com","price_list_currency":"KES","base_taxes_and_charges_added":0,"idx":0,"supplier":"new supp","buying_price_list":"Wholesale","is_opening":"No","base_net_total":2,"taxes_and_charges_deducted":0,"rounded_total":0,"apply_discount_on":"Grand Total","in_words":"","discount_amount":0,"additional_discount_percentage":0,"disable_rounded_total":["1","0"],"base_paid_amount":0,"conversion_rate":1,"total_advance":0,"posting_time":"21:25:54.078725","total":2,"is_subcontracted":"No","update_stock":1,"base_total":2,"company":"EVMC-PAR","base_rounded_total":0,"grand_total":2,"language":"en","rounding_adjustment":0,"posting_date":"2018-01-22","naming_series":"PINV-RET-","currency":"KES","letter_head":"EVMC LETTERHEAD","base_taxes_and_charges_deducted":0,"paid_amount":0,"credit_to":"Creditors - ELPAR","base_grand_total":2,"docstatus":0,"status":"Draft","__onload":{"load_after_mapping":true},"outstanding_amount":2,"total_net_weight":0,"payment_schedule":[],"plc_conversion_rate":1,"total_taxes_and_charges":0,"name":"New Purchase Invoice 2","__last_sync_on":"2018-01-22T18:26:01.908Z","terms":"<div>Please quote the Purchase Order No. <b>New Purchase Invoice 2</b> in your documentation and deliveries.<br></div><div><br></div><div>NB: No Delivery shall be accepted without the above Number.</div>","change_amount":0,"base_change_amount":0,"__unsaved":1,"tc_name":"Quote LPO No.","tax_id":null,"address_display":null,"taxes_and_charges":null,"payment_terms_template":null,"supplier_address":null,"contact_email":null,"contact_mobile":null,"contact_display":null,"contact_person":null}
action:Save
cmd:frappe.desk.form.save.savedocs
````

#### Steps to reproduce:
1. Cleaned up my previous DB with DBForge (tried migrating from an old erpnext v.8.0.0 ESS-LLP-healthcare branch database and failed hence the cleanup to retain essential data only)
2. Appended my essential data to a newly setup and initialized erpnext db, then stored the backup.
3. setup another erpnext site then restored my backed data in 2. above. and migrated the same.

Erpnext version: 10.0.13

**Comment by mudux** [comment]
Any one with at least a guidance on this..perhaps where i can look for problems..

I forgot to mention that this only affects Purchase Invoice...

I have a feeling my appended data has something to do with this..

I cleaned up most of the ERPNEXT specific data in my original DB and only appended customers, users, items, prices, suppliers, print formats and auth.. no custom script nor custom docfield was added..

**Comment by mudux** [comment]
Decided to trace the issue as it is not software related
