### ISSUE TITLE
Error when Import Items

### ISSUE THREAD

**Issue by staumoepeau** [frappe/erpnext#12627]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 385, in upload
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 219, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in _validate
    self.validate_set_only_once()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 482, in validate_set_only_once
    frappe.CannotChangeConstantError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
CannotChangeConstantError: Value cannot be changed for Is Fixed Asset

**Comment by manassolanki** [comment]
hi @staumoepeau 
"Is Fixed Asset" set only once so if you are trying to update that field, it will give errors.

**Comment by mridzuan** [comment]
I've been trying to import some item data and failed because the item has become Is Fixed Asset despite being imported for the first time... and the import fail.

**Comment by happy3gs** [comment]
my item import failed severally please help
