### ISSUE TITLE
Cant login after update

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12621]
Hello,

After todays update, I cant login on developer branch, the console shows this error:

frappe-web.min.js:958 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 59, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 121, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 53, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 107, in __init__
    if self.login()==False: return
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 131, in login
    self.post_login()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 137, in post_login
    self.make_session()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 178, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 229, in __init__
    self.start()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 250, in start
    "session_country": get_geo_ip_country(frappe.local.request_ip) if frappe.local.request_ip else None,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 432, in get_geo_ip_country
    match = get_geo_from_ip(ip_addr)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 425, in get_geo_from_ip
    return frappe._dict(data)
TypeError: 'NoneType' object is not iterable

**Comment by achillesrasquinha** [comment]
Fixing - [4901](https://github.com/frappe/frappe/pull/4901)

**Comment by achillesrasquinha** [comment]
Merged! Please Confirm. Closing this.

**Comment by applepipe** [comment]
@achillesrasquinha thanks, it was fixed!
