### ISSUE TITLE
frappe.email.queue.flush: attach_print() got an unexpected keyword argument 'lang'

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12644]
When trying to email an invoice:-

```
Title
frappe.email.queue.flush
Error
attach_print() got an unexpected keyword argument 'lang'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 419, in send_one
    message = prepare_message(email, recipient.recipient, recipients_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 536, in prepare_message
    print_format_file = frappe.attach_print(**attachment)
TypeError: attach_print() got an unexpected keyword argument 'lang'
```

On develop branch (5 days since last update)

**Comment by binary64** [comment]
A reboot of the server solved this issue. I am no longer seeing it.
