### ISSUE TITLE
bench update ended in error

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12648]
Snippet:-

```
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Syncing help database...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", lin                                                                                                                                                             e 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", lin                                                                                                                                                             e 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/co                                                                                                                                                             re.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/de                                                                                                                                                             corators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line                                                                                                                                                              24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222                                                                                                                                                             , in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 65, in mi                                                                                                                                                             grate
    frappe.utils.help.sync()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 25, in                                                                                                                                                              sync
    help_db.sync_pages()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 133, i                                                                                                                                                             n sync_pages
    for basepath, folders, files in os.walk(docs_folder):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/home/frappe/frappe-bench/env/lib/python2.7/posixpath.py", line 73, in j                                                                                                                                                             oin
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal                                                                                                                                                              not in range(128)
frappe@78b08a83ecaf:~/frappe-bench$
```

**Comment by joolsr** [comment]
It appears you have a non standard ie non ASCII character in your install path somewhere. It could be a tilde or related character. This is why the error is appearing. You can find other similar errors and means to find the offending character in the discuss.erpnext.com forums

**Comment by binary64** [comment]
A possible clue (making it not my fault..) @ https://stackoverflow.com/questions/24475393/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-23-ordinal

**Comment by binary64** [comment]
Been trying to help debug this myself. Treat me easy as this is my first ever Python edit..

```
Syncing help database...
('ERRORRRRR ', u'../apps/erpnext/erpnext/docs/user/manual/en/regional/france', ' b:', 'fichier_des_\xc3\xa9critures_comptables.md')
```

You can see here the mistake. Seems like someone has a german char in the helpfile..

**Comment by binary64** [comment]
erpnext/erpnext/docs/user/manual/en/regional/france/
fichier_des_écritures_comptables.md	FEC report for France (#12446)	3 days ago
@chdecultot committed with @rmehta FEC report for France (#12446)  …

**Comment by chdecultot** [comment]
Thanks for the debug @binary64 .

I just changed the name of the file and sent a fix.

Sorry about this issue!
