### ISSUE TITLE
Email Issue After Server Restore

### ISSUE THREAD

**Issue by ekpott** [frappe/erpnext#12647]
@tundebabzy please help me out.

Title
frappe.email.queue.flush

Error
{'retry': 0, 'log': <function log at 0x7f97e6b4d488>, 'site': u'largemichaels.officeplus.com.ng', 'event': u'all', 'method_name': u'frappe.email.queue.flush', 'method': <function flush at 0x7f97e606c488>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.email.queue.flush'}
Traceback (most recent call last):
  File "/home/username/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 92, in execute_job
    method(**kwargs)
  File "/home/username/frappe-bench/apps/frappe/frappe/email/queue.py", line 324, in flush
    check_email_limit([])
  File "/home/username/frappe-bench/apps/frappe/frappe/email/queue.py", line 214, in check_email_limit
    smtp_server = SMTPServer()
  File "/home/username/frappe-bench/apps/frappe/frappe/email/smtp.py", line 151, in __init__
    self.setup_email_account(append_to)
  File "/home/username/frappe-bench/apps/frappe/frappe/email/smtp.py", line 154, in setup_email_account
    self.email_account = get_outgoing_email_account(raise_exception_not_set=False, append_to=append_to, sender=sender)
  File "/home/username/frappe-bench/apps/frappe/frappe/email/smtp.py", line 66, in get_outgoing_email_account
    email_account = get_default_outgoing_email_account(raise_exception_not_set=raise_exception_not_set)
  File "/home/username/frappe-bench/apps/frappe/frappe/email/smtp.py", line 101, in get_default_outgoing_email_account
    email_account.password = email_account.get_password(raise_exception=False)
  File "/home/username/frappe-bench/apps/frappe/frappe/model/base_document.py", line 634, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/username/frappe-bench/apps/frappe/frappe/utils/password.py", line 16, in get_decrypted_password
    return decrypt(auth[0][0])
  File "/home/username/frappe-bench/apps/frappe/frappe/utils/password.py", line 106, in decrypt
    frappe.throw(_('Encryption key is invalid, Please check site_config.json'))
  File "/home/username/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/username/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/username/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Encryption key is invalid, Please check site_config.json

**Comment by vishdha** [comment]
https://discuss.erpnext.com/t/frappe-exceptions-validationerror-encryption-key-is-invalid-please-check-site-config-json/27244
