### ISSUE TITLE
Errors on "Allow Dropbox Access"

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#12668]
I am trying to set up Dropbox backup in version 10.

I have acquired all the appropriate keys but when I Click "Allow Dropbox Access" under dropbox settings the following 2 errors are recorded in the log:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/utils.py", line 41, in make_post_request
    frappe.flags.integration_request = s.post(url, data=data, auth=auth, headers=headers)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'None/api/method/dropbox_erpnext_broker.www.setup_dropbox.get_authotize_url': No schema supplied. Perhaps you meant http://None/api/method/dropbox_erpnext_broker.www.setup_dropbox.get_authotize_url?

.....................................................................................................................................................................................................................

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 220, in get_redirect_url
    response = make_post_request(url, data={"site": get_url()})
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/utils.py", line 50, in make_post_request
    raise exc
MissingSchema: Invalid URL 'None/api/method/dropbox_erpnext_broker.www.setup_dropbox.get_authotize_url': No schema supplied. Perhaps you meant http://None/api/method/dropbox_erpnext_broker.www.setup_dropbox.get_authotize_url?

**Comment by Talha-Hashmi** [comment]
same issue 💯

**Comment by jaichavan** [comment]
Hello, @mafrica @Talha-Hashmi 
Just added Dropbox account to my ERPNext account, successfully! Attaching a screenshot for your reference:
1. Dropbox Settings:

![image](https://user-images.githubusercontent.com/40264279/51407308-85bd0800-1b81-11e9-8b32-c157528580ee.png)


2. Neatly Done! :

![image](https://user-images.githubusercontent.com/40264279/51407198-35de4100-1b81-11e9-80b3-3fd4fe65fcfe.png)

The process has been articulately defined by @saurabh6790 in this documentation - https://erpnext.org/docs/user/manual/en/setting-up/integrations/dropbox-backup
