### ISSUE TITLE
Error when entering a new password with repeated characters

### ISSUE THREAD

**Issue by guilledd** [frappe/erpnext#12812]
Enter to User List
Click on any user
Get to the section to change the password
start typing a password that contains something like:  'abccc' or '333' or 'abab'
A server error message appears on screen

It seems this error is triggered when entering a password with repeated characters or expression

**Comment by vishdha** [comment]
Hi @guilledd I follow your procedure to change the password.
It set repeated character password.
Please share traceback or screenshot of error and version of ERPNext and Frappe

**Comment by guilledd** [comment]
Traceback (most recent call last):
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 577, in test_password_strength
    result = _test_password_strength(new_password, user_inputs=user_data)
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 15, in test_password_strength
    "feedback": get_feedback(result.get('score'), result.get('sequence'))
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 59, in get_feedback
    feedback = get_match_feedback(longest_match, len(sequence) == 1)
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 156, in get_match_feedback
    return (pattern_fn())
  File "/home/frappeans/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 109, in fun_repeat
    if len(match.get("repeated_char")) == 1:
TypeError: object of type 'NoneType' has no len()

**Comment by guilledd** [comment]
App Versions

{
	"erpnext": "10.0.20",
	"frappe": "10.0.21"
}

Route

Form/User/someuser@somedomain


Request Data

{
	"type": "POST",
	"args": {
		"new_password": "avvvv",
		"cmd": "frappe.core.doctype.user.user.test_password_strength"
	},
	"url": "/"
}

Response JSON

{}

**Comment by umairsy** [comment]
Issue not replicating in my test account. Can you please try again and confirm if issue is still prevailing?
