### ISSUE TITLE
Bank Reconciliation Statement in Auto Email Report throws Error

### ISSUE THREAD

**Issue by netchampfaris** [frappe/erpnext#12821]
![image](https://user-images.githubusercontent.com/9355208/35958811-c9b2f970-0cc8-11e8-892e-6f15618ab15d.png)

```
Traceback (most recent call last):
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/api.py", line 53, in handle
    return frappe.handler.handle()
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 152, in download
    data = auto_email_report.get_report_content()
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 61, in get_report_content
    filters = self.filters, as_dict=True)
  File "/Users/farisansari/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 167, in get_data
    _row[columns[i].get('fieldname')] = val
IndexError: list index out of range
```

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/4987
