### ISSUE TITLE
URGENT: Cannot submit Stock Reconciliation Voucher due to timeout error!

### ISSUE THREAD

**Issue by davidrheinbay** [frappe/erpnext#12847]
Hi,

see error code below.

I need this to work as soon as possible as my investors need to see current stock data today!

Action Failed

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 1214, in executeaction
    getattr(doc, action)(**kwargs)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 820, in _submit
    self.save()
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 256, in save
    return self.save(args, *kwargs)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 307, in save
    self.runpostsavemethods()
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 890, in runpostsavemethods
    self.runmethod("onsubmit")
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 755, in runmethod
    out = Document.hook(fn)(self, args, *kwargs)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, args, *kwargs)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 1007, in runner
    addtoreturnvalue(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/stock/doctype/stockreconciliation/stockreconciliation.py", line 33, in onsubmit
    self.updatestockledger()
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/stock/doctype/stockreconciliation/stockreconciliation.py", line 187, in updatestockledger
    self.insertentries(row)
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/stock/doctype/stockreconciliation/stockreconciliation.py", line 205, in insertentries
    self.makeslentries([args])
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/controllers/stockcontroller.py", line 265, in makeslentries
    makeslentries(slentries, isamended, allownegativestock, vialandedcostvoucher)
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/stock/stockledger.py", line 31, in makeslentries
    sleid = makeentry(sle, allownegativestock, vialandedcostvoucher)
  File "/home/frappe/benches/bench-2018-02-08/apps/erpnext/erpnext/stock/stockledger.py", line 55, in makeentry
    sle.insert()
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 212, in insert
    self.setnewname()
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/document.py", line 372, in setnewname
    setnewname(self)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/naming.py", line 50, in setnewname
    doc.name = makeautoname(autoname)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/naming.py", line 98, in makeautoname
    n = parsenamingseries(parts, doctype, doc)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/naming.py", line 113, in parsenamingseries
    part = getseries(n, digits, doctype)
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/model/naming.py", line 134, in getseries
    current = frappe.db.sql("select current from tabSeries where name=%s for update", (key,))
  File "/home/frappe/benches/bench-2018-02-08/apps/frappe/frappe/database.py", line 166, in sql
    self.cursor.execute(query, values)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self.query(query)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in query
    conn.query(q)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self.affectedrows = self.readqueryresult(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in readqueryresult
    result.read()
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 1356, in read
    self.readresultpacket(firstpacket)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 1422, in _readresultpacket
    self.readrowdatapacket()
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 1456, in readrowdatapacket
    packet = self.connection.readpacket()
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _readpacket
    packet.checkerror()
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in checkerror
    err.raisemysqlexception(self.data)
  File "/home/frappe/benches/bench-2018-02-08/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raisemysql_exception
    raise errorclass(errno, errval)
InternalError: (1205, u'Lock wait timeout exceeded; try restarting transaction')

**Comment by PawanMeh** [comment]
There seem to be some issues in your database which are causing locking. Check the Stock Ledger table for any locks. You can try this [link](https://stackoverflow.com/questions/5836623/getting-lock-wait-timeout-exceeded-try-restarting-transaction-even-though-im) for possible solutions.

**Comment by davidrheinbay** [comment]
I am on the hosted version of ERP next - how am I able to do this?
