### ISSUE TITLE
[bug] unable to update submitted sales order

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12860]
The issue can be replicated as follows:
-Create sales order
-Create material request from sales order
-Create purchase order from material request
-Try updating printing settings in the sales order.

Tested on demo.erpnext.com (see screenshot)

Traceback:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 684, in validate_update_after_submit
    d._validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 575, in _validate_update_after_submit
    frappe.UpdateAfterSubmitError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
UpdateAfterSubmitError: Not allowed to change Ordered Qty after submission
```

![capture_1](https://user-images.githubusercontent.com/10496564/36060180-5bcc1e3e-0e6a-11e8-8c00-be89d99a2004.PNG)

**Comment by manassolanki** [comment]
Fixed via https://github.com/frappe/erpnext/pull/12845
