### ISSUE TITLE
Server error when updating chart of accounts

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#12907]
We appear to randomly get the following error when updating our chart of accounts.  Subsequent attempts  with the same data appear to work ok:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 258, in update_account_number
    validate_account_number(name, account_number, account.company)
AttributeError: 'NoneType' object has no attribute 'company'

**Comment by mafrica** [comment]
We are running:

ERPNext: v10.0.19 (master)

Frappe Framework: v10.0.20 (master)

**Comment by umairsy** [comment]
Request to move this discussion on the forum. With error message, please also share the steps followed for updating CoAs.
