### ISSUE TITLE
Barcodes are not being fetched on sales invoice anymore

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12954]
Hello,

After the update on barcodes from data to table barcodes stopped being fetched on sales invoice, fields are blank now on old sales invoices, and on new sales invoices the information is not fetched on items add.

ERPNext: v9.x.x-develop (44658d4) (develop)
Frappe Framework: v9.x.x-develop (5d9d644) (develop)

**Comment by kennethsequeira** [comment]
@applepipe barcodes not fetched in the child table in Sales invoice or Print preview?

**Comment by joezsweet** [comment]
@applepipe cant reproduce the problem

**Comment by applepipe** [comment]
@kennethsequeira Yes, barcodes are not being shown on reports also, its like the field in every document is empty.

**Comment by joezsweet** [comment]
@applepipe that should not possible as the barcode is stored in the document afaik

**Comment by applepipe** [comment]
@joezsweet Yes, it is very strange, but it started to happen after the barcode modification, I cant see the barcode info on orders, on query reports and custom reports, its like the information is empty, I'll check on database if it is present on tabSales Order when as soon as I can, but on every document ou report I can't see the information filled, it was working fine before the update and I dont have any app installed, its a VM to test and report until I'm able to contribute with something more substancial

**Comment by joezsweet** [comment]
@applepipe did u apply the patch?

**Comment by applepipe** [comment]
Yes, no errors occurred, I'll try to delete the line on tabPatch and apply again.

**Comment by joezsweet** [comment]
ok, let me know ..

**Comment by joezsweet** [comment]
@applepipe oh probably i got the problem you faced .. 

https://github.com/frappe/erpnext/pull/12957

the PR should solve the issue ....

**Comment by applepipe** [comment]
I've ran again the patch, now it gave an error (It didn't before):

Executing erpnext.patches.v10_0.item_barcode_childtable_migrate in site1.local (d56cb677eaab3383)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v10_0/item_barcode_childtable_migrate.py", line 22, in execute
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 306, in _save
    self.update_children()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 324, in update_children
    self.update_child_table(df.fieldname, df)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 333, in update_child_table
    d.db_update()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 327, in db_update
    self.db_insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 314, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: (u'Item Barcode', u'7898584809941', IntegrityError(1062, u"Duplicate entry '7898584809941' for key 'PRIMARY'"))

It says that I have a duplicated entry, but I've checked and I don't have other item with same barcode.

I'll wait for the PR to be merged

**Comment by joezsweet** [comment]
That's kind of strange ..

**Comment by joezsweet** [comment]
can u access the database and clear tabItem Barcode?

**Comment by applepipe** [comment]
I dont have this access right now, there is a lot of items on the database, I was using the info to test reports and noticed the issue

**Comment by joezsweet** [comment]
@applepipe can u access ssh?  if so, run `bench --site sitename mysql` you'll be able to access mysql db

**Comment by umairsy** [comment]
Just tried replicating. It is working fine for me.

![screen shot 2018-02-16 at 12 07 54 pm](https://user-images.githubusercontent.com/910238/36296192-166876ec-1312-11e8-86b8-b4547846ec7d.png)

If it's related to specific ERPNext account, request shifting this discussion on the ERPNext community forum.

**Comment by applepipe** [comment]
hello @joezsweet, the PR unfortunately didn't solved my issue, when I try to add items to a sales order everything is fetched fine but the barcode don't, tried to delete barcodes and add again, and tried to inform barcode type with no luck, deactivate the option to show barcodes and activated again, still no luck.

This is really strange, it stopped working after the patch, now the patch doesn't run again, I'll try to delete all barcodes on the db now

@umairsy 
Since I do not have any app or custom script on the document, what could I have done to cause this? Information present on the field could cause this?

**Comment by applepipe** [comment]
Barcode field is missing on sales order item and no customisations were made on the document with developer mode on

**Comment by joezsweet** [comment]
@applepipe Can you post a video?

**Comment by applepipe** [comment]
hello @joezsweet, I've deleted all data on tabItem Barcode as you suggested, the patch ran without errors, but the issue persists

This is the screenshot of sales order item doctype, the barcode field is missing:
![screencapture-177-36-139-163-7070-desk-1518977826944](https://user-images.githubusercontent.com/18335894/36355269-759d8b62-14bf-11e8-8c6c-f536992a7233.png)

Here is a gif adding the item on sales invoice, the barcode field is empty and screen becomes grey
![untitled](https://user-images.githubusercontent.com/18335894/36355490-c28f4d22-14c2-11e8-801d-71f484e38c2c.gif)

**Comment by joezsweet** [comment]
@applepipe `barcode` not supposed to be filled when you select the item, it's used to search for the item ..

**Comment by applepipe** [comment]
But it was working before both ways, and the field on sales order is missing

**Comment by joezsweet** [comment]
Nothing related to new item barcode table
