### ISSUE TITLE
Item Update Issue - Excel

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#13002]
Please check the following error for a new update using Excel. Two types of errors in the same set of update.

First Error:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 388, in upload
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 219, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in _validate
    self.validate_set_only_once()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 482, in validate_set_only_once
    frappe.CannotChangeConstantError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
CannotChangeConstantError: Value cannot be changed for Is Fixed Asset

Second Error:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 388, in upload
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 219, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in _validate
    self.validate_set_only_once()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 482, in validate_set_only_once
    frappe.CannotChangeConstantError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
CannotChangeConstantError: Value cannot be changed for Series

**Comment by epochc** [comment]
Apologies. Excel download introduces a '123 types for numbers and the Item Codes wouldn't Vlookup. So I was try to use the Item Codes again and that gave me problems. False alarm. 

Thanks

Jay
