### ISSUE TITLE
Uploading to Dropbox Fails 

### ISSUE THREAD

**Issue by sahilburman** [frappe/erpnext#13031]
Hi Always get this error while uploading backups to dropbox.

Backup Upload Failed
Oops, your automated backup to Dropbox failed.

Error message: 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox
    did_not_upload, error_log = backup_to_dropbox()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 107, in backup_to_dropbox
    upload_from_folder(get_files_path(is_private=1), "/private/files", dropbox_client, did_not_upload, error_log)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 125, in upload_from_folder
    for root, directory, files in os.walk(path):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/home/frappe/frappe-bench/env/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)
Please contact your system manager for more information.

Unable to understand where the issue exist. 
would appropriate the help if possible

**Comment by umairsy** [comment]
Can you please report it on discuss.erpnext.com first. If it is validated as a bug, we can re-open this issue.
