### ISSUE TITLE
bench update error

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#13041]
/home/frappe/frappe-bench/apps/frappe/frappe/website/js/web_form.js, /home/frappe/frappe-bench/apps/frappe/frappe/public/js/lib/summernote/summernote.js, /home/frappe/frappe-bench/apps/frappe/frappe/public/js/lib/datepicker/datepicker.min.js, /home/frappe/frappe-bench/apps/frappe/frappe/public/js/lib/datepicker/datepicker.en.js → ../../sites/assets/js/web_form.min.js...
Killed
error Command failed with exit code 137.

**Comment by achillesrasquinha** [comment]
Did you try updating `bench`? Should work. Please update me on this. Or reopen if failed.

**Comment by YnievesDotNet** [comment]
I have same error, and yes, is updating the bench

```
✔ Built css-rtl/frappe-chat-web.css
✔ Built css-rtl/web_form.css
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/utils.py", line 44, in build
    frappe.build.bundle(
  File "/workspace/development/frappe-bench/apps/frappe/frappe/build.py", line 248, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 93, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command '/home/frappe/.nvm/versions/node/v14.18.1/bin/yarn run production --app frappe' returned non-zero exit status 137.
ERROR: 
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 33, in <module>
    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())
  File "/home/frappe/.bench/bench/cli.py", line 117, in cli
    raise e
  File "/home/frappe/.bench/bench/cli.py", line 107, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 23, in update
    update(pull=pull, apps=apps, patch=patch, build=build, requirements=requirements, restart_supervisor=restart_supervisor, restart_systemd=restart_systemd, backup=not no_backup, compile=not no_compile, force=force, reset=reset)
  File "/home/frappe/.bench/bench/utils/bench.py", line 397, in update
    bench.setup.requirements()
  File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 337, in requirements
    App(app, bench=self.bench, to_clone=False).install()
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 186, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 417, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/home/frappe/.bench/bench/utils/bench.py", line 294, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/home/frappe/.bench/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
```
Thanks.

Yoinier
