### ISSUE TITLE
Some URLs raised  Uncaught Server Exception

### ISSUE THREAD

**Issue by ibrasec** [frappe/erpnext#13123]
Hi
The following are some URLs that raises Uncaught Server Exception when i used ERPNext VM ...
i wonder if this is something normal.. i just want to point to it

http://192.168.1.145/cart_terms
http://192.168.1.145/order
http://192.168.1.145/timelog_info

```

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 39, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 134, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 150, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 157, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 173, in build_page
    context.title = frappe.render_template(title_template, context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 69, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'doc' is undefined
```

**Comment by umairsy** [comment]
Please post your technical queries on the ERPNext community forum initially. If it is validated as a bug, we can reopen this issue.
