### ISSUE TITLE
ValueError: day is out of range for month when saving Doc

### ISSUE THREAD

**Issue by jvfiel** [frappe/erpnext#13150]
same issue: https://github.com/frappe/erpnext/issues/10980

ERPNext 9.2.2
Frappe 9.2.4

`
Traceback (most recent call last):
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/__init__.py", line 935, in call
    return fn(*args, **newargs)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_post_save_methods()
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/model/document.py", line 846, in run_post_save_methods
    self.save_version()
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/model/document.py", line 921, in save_version
    if version.set_diff(self._doc_before_save, self):
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/core/doctype/version/version.py", line 15, in set_diff
    diff = get_diff(old, new)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/core/doctype/version/version.py", line 61, in get_diff
    diff = get_diff(old_row_by_name[d.name], d, for_child=True)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/core/doctype/version/version.py", line 75, in get_diff
    new_data = new.get_formatted(df.fieldname) if new_value else new_value
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/model/base_document.py", line 688, in get_formatted
    return format_value(val, df=df, doc=doc, currency=currency)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/utils/formatters.py", line 52, in format_value
    return format_time(value)
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/utils/data.py", line 238, in format_time
    formatted_time = babel.dates.format_time(get_time(txt), locale=(frappe.local.lang or "").replace("-", "_"))
  File "/home/jvfiel/frappe-bl3ndlabs/apps/frappe/frappe/utils/data.py", line 197, in get_time
    return parser.parse(time_str).time()
  File "/home/jvfiel/frappe-bl3ndlabs/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/jvfiel/frappe-bl3ndlabs/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 581, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month`

**Comment by jvfiel** [comment]
when I uncheck track changes the error is gone. I traced the error its trying to format time but its 0

**Comment by tundebabzy** [comment]
Upgrade `python-dateutil`
