### ISSUE TITLE
Party Type filter in GL does not contains Student

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#13244]
Hello;
At General Ledger (GL), there is not Student as party type which is required if we need to generate statement for certain student from the GL.
The below link is referenced for this issue:
https://discuss.erpnext.com/t/party-type-filter-in-gl-not-contains-student/34324

Regards
Bilal

**Comment by manassolanki** [comment]
Fixed

**Comment by bghayad** [comment]
Hello @manassolanki 
Thanks for your kindly help and support.
I upgraded and yes now I am able to select the party type to be Student. But when I need to select the party name (the student it self), I am getting this error:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 83, in get_value
    return frappe.db.get_value(doctype, filters, fieldname, as_dict=as_dict, debug=debug)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 443, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 487, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 619, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'student_name' in 'field list'")

Regards
Bilal

**Comment by manassolanki** [comment]
Hi @bghayad , We are aware of the issue and already send a PR (https://github.com/frappe/erpnext/pull/13374). That will be merged soon.

**Comment by bghayad** [comment]
Yes I upgraded for 10.1.15 master and now it is working fine.
Wonderful.
Thank you @manassolanki 
Regards
Bilal
