### ISSUE TITLE
Email alerts not working

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#13242]
Auto alerts on email is not working in ERP modules. Not even getting weekly reports on email as we used to get.

**Comment by rmehta** [comment]
Please check your "Error Log" table. And re-open the issue after posting a full error trace.

**Comment by unidow** [comment]
Please find below:

(535, 'Incorrect authentication data')
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2018-03-05/apps/frappe/frappe/email/queue.py", line 423, in send_one
    smtpserver.sess.sendmail(email.sender, recipient.recipient, encode(message))
  File "/home/frappe/benches/bench-2018-03-05/apps/frappe/frappe/email/smtp.py", line 213, in sess
    raise_(frappe.ValidationError, e, traceback)
  File "/home/frappe/benches/bench-2018-03-05/apps/frappe/frappe/email/smtp.py", line 195, in sess
    (self.password or "").encode('utf-8'))
  File "/usr/lib64/python2.7/smtplib.py", line 621, in login
    raise SMTPAuthenticationError(code, resp)
ValidationError: (535, 'Incorrect authentication data')

**Comment by yashodhank** [comment]
@unidow Incorrect authentication data
you will need to double check your username and password for email address.

for assistance and troubleshooting, use https://discuss.erpnext.com/
