### ISSUE TITLE
Delivery Note with 0 rate not getting submitted

### ISSUE THREAD

**Issue by umaepoch** [frappe/erpnext#13491]
Hi,

I am working on v10.1.13. I am trying to submit a delivery note with 0 rate, (it has Allow Zero Valuation rate ticked), but am getting this error. Can you please help?

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 210, in on_submit
    self.update_billing_status()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 312, in update_billing_status
    dn_doc.update_billing_percentage(update_modified=update_modified)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 311, in update_billing_percentage
    }, update_modified)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 290, in _update_percent_field
    where name='%(name)s'""" % args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 176, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1365, u'Division by 0')

**Comment by umaepoch** [comment]
Hi,

I found out the cause for the problem. The code inside delivery_note.py is

               for dn in set(updated_delivery_notes):
                        dn_doc = self if (dn == self.name) else frappe.get_doc("Delivery Note", dn)
                        dn_doc.update_billing_percentage(update_modified=update_modified)

And, on the other system, the code is:

        for dn in set(updated_delivery_notes):
            dn_doc = self if (dn == self.name) else frappe.get_doc("Delivery Note", dn)
            if dn_doc.net_total > 0:
                dn_doc.update_billing_percentage(update_modified=update_modified)

So, looks like some inconsistencies in this version. I think the bench update should be able to fix it.

**Comment by rohitwaghchaure** [comment]
@umaepoch 
We have fixed this issue, can you please pull latest update and check.

**Comment by umaepoch** [comment]
Yes, this issue was resolved. Please close the issue. Thanks
