### ISSUE TITLE
Error on Purchase Invoice save

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#13549]
```
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 46, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 35, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 41, in validate
    self.set_missing_values(for_validate=True)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 101, in set_missing_values
    super(PurchaseInvoice, self).set_missing_values(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 70, in set_missing_values
    self.set_missing_item_details(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 202, in set_missing_item_details
    ret = get_item_details(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 65, in get_item_details
    get_price_list_rate(args, item_doc, out)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 308, in get_price_list_rate
    price_list_rate = get_price_list_rate_for(args.price_list, item_doc.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 361, in get_price_list_rate_for
    {"price_list": price_list, "item_code": item_code}, "price_list_rate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 472, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 516, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 650, in _get_values_from_table
    conditions, values = self.build_conditions(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 436, in build_conditions
    _build_condition(f)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 403, in _build_condition
    _operator = value[0]
IndexError: list index out of range

request.js:300 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 943, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 46, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 35, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 41, in validate
    self.set_missing_values(for_validate=True)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 101, in set_missing_values
    super(PurchaseInvoice, self).set_missing_values(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 70, in set_missing_values
    self.set_missing_item_details(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 202, in set_missing_item_details
    ret = get_item_details(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 65, in get_item_details
    get_price_list_rate(args, item_doc, out)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 308, in get_price_list_rate
    price_list_rate = get_price_list_rate_for(args.price_list, item_doc.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 361, in get_price_list_rate_for
    {"price_list": price_list, "item_code": item_code}, "price_list_rate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 472, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 516, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 650, in _get_values_from_table
    conditions, values = self.build_conditions(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 436, in build_conditions
    _build_condition(f)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 403, in _build_condition
    _operator = value[0]
IndexError: list index out of range

jquery.min.js:4 POST https://frappe.erpnext.com/ 500 (INTERNAL SERVER ERROR)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:178
frappe.call @ request.js:62
_call @ save.js:191
save @ save.js:25
frappe.ui.form.save @ save.js:217
(anonymous) @ form.js:755
Promise.then (async)
(anonymous) @ dom.js:220
frappe.run_serially @ dom.js:218
_f.Frm._save @ form.js:746
(anonymous) @ form.js:705
setTimeout (async)
(anonymous) @ form.js:704
_f.Frm.save @ form.js:698
Save @ toolbar.js:304
(anonymous) @ page.js:160
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
request.js:300 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 46, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 35, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 41, in validate
    self.set_missing_values(for_validate=True)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 101, in set_missing_values
    super(PurchaseInvoice, self).set_missing_values(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 70, in set_missing_values
    self.set_missing_item_details(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 202, in set_missing_item_details
    ret = get_item_details(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 65, in get_item_details
    get_price_list_rate(args, item_doc, out)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 308, in get_price_list_rate
    price_list_rate = get_price_list_rate_for(args.price_list, item_doc.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 361, in get_price_list_rate_for
    {"price_list": price_list, "item_code": item_code}, "price_list_rate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 472, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 516, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 650, in _get_values_from_table
    conditions, values = self.build_conditions(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 436, in build_conditions
    _build_condition(f)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 403, in _build_condition
    _operator = value[0]
IndexError: list index out of range

request.js:300 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 943, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 46, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 35, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 41, in validate
    self.set_missing_values(for_validate=True)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 101, in set_missing_values
    super(PurchaseInvoice, self).set_missing_values(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 70, in set_missing_values
    self.set_missing_item_details(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 202, in set_missing_item_details
    ret = get_item_details(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 65, in get_item_details
    get_price_list_rate(args, item_doc, out)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 308, in get_price_list_rate
    price_list_rate = get_price_list_rate_for(args.price_list, item_doc.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 361, in get_price_list_rate_for
    {"price_list": price_list, "item_code": item_code}, "price_list_rate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 472, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 516, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 650, in _get_values_from_table
    conditions, values = self.build_conditions(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 436, in build_conditions
    _build_condition(f)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 403, in _build_condition
    _operator = value[0]
IndexError: list index out of range
```

**Comment by rohitwaghchaure** [comment]
Not abele to replicate the issue locally and prakshji has confirmed it's fixed
