### ISSUE TITLE
Could not update Frappe and ERPnext

### ISSUE THREAD

**Issue by garybsimon** [frappe/erpnext#13670]
Hi there, 

I want to do an update, but my git pull command doesn't work at all.
The problem is the following.

i have manually git stash before the update, but still don't work.
I have commited my changes and deleted the files, nothing happened.

Can you please send me some instuction how to fix that?

Failure code are below attached.

`frappe@erp:~/frappe-bench$ bench update
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Updating 3a93dfa..1712736
error: Your local changes to the following files would be overwritten by merge:
        .gitignore
        .travis.yml
        MANIFEST.in
        bench/__init__.py
        bench/commands/utils.py
        bench/config/redis.py
        bench/config/templates/Procfile
        bench/package.json
        bench/patches/patches.txt
        playbooks/__init__.py
        playbooks/develop/includes/mariadb_centos.yml
        playbooks/develop/includes/mariadb_debian.yml
        playbooks/develop/includes/mariadb_ubuntu.yml
        playbooks/develop/includes/setup_bench.yml
        playbooks/develop/includes/setup_dev_env.yml
        playbooks/develop/includes/setup_mariadb.yml
        playbooks/develop/includes/setup_selinux_policy.yml
        playbooks/develop/includes/wkhtmltopdf.yml
        playbooks/develop/install.yml
        playbooks/develop/macosx.yml
        playbooks/develop/templates/mariadb_centos.repo
        playbooks/develop/templates/simple_mariadb_config.cnf
        playbooks/develop/ubuntu.yml
        playbooks/production/includes/setup_bench_production.yml
        playbooks/production/install.yml
        playbooks/production/templates/default_nginx.j2
        playbooks/production/templates/frappe_selinux.te
        requirements.txt
        setup.py
        vm/Readme.md
        vm/ansible/base.yml
        vm/ansible/library/bench.py
        vm/ansible/roles/mariadb/README.md
        vm/ansible/roles/mariadb/defaults/main.yml
        vm/ansible/roles/mariadb/handlers/main.yml
        vm/ansible/roles/mariadb/meta/main.yml
        vm/ansible/roles/mariadb/tasks/centos.yml
        vm/ansible/roles/mariadb/tasks/main.yml
        vm/ansible/roles/mariadb/tasks/mysql_secure_installation.yml
        vm/ansible/roles/mariadb/tasks/ubuntu.yml
        vm/ansible/roles/mariadb/templates/mariadb_centos.repo.j2                                                                                                                                             
        vm/ansible/roles/mariadb/templates/mariadb_ubuntu.list.j2                                                                                                                                             
        vm/ansible/roles/mariadb/templates/my.cnf.j2                                                                                                                                                          
        vm/ansible/roles/mariadb/vars/main.yml                                                                                                                                                                
        vm/ansible/roles/nginx/.travis.yml                                                                                                                                                                    
        vm/ansible/roles/nginx/README.md                                                                                                                                                                      
        vm/ansible/roles/nginx/defaults/main.yml                                                                                                                                                              
        vm/ansible/roles/nginx/handlers/main.yml                                                                                                                                                              
        vm/ansible/roles/nginx/meta/main.yml                                                                                                                                                                  
        vm/ansible/roles/nginx/tasks/main.yml                                                                                                                                                                 
        vm/ansible/roles/nginx/tasks/setup-Debian.yml                                                                                                                                                         
        vm/ansible/roles/nginx/tasks/setup-RedHat.yml                                                                                                                                                         
        vm/ansible/roles/nginx/tasks/vhosts.yml                                                                                                                                                               
        vm/ansible/roles/nginx/templates/nginx.conf.j2                                                                                                                                                        
        vm/ansible/roles/nginx/templates/nginx.repo.j2                                                                                                                                                        
        vm/ansible/roles/nginx/templates/vhosts.j2                                                                                                                                                            
        vm/ansible/roles/nginx/tests/inventory                                                                                                                                                                
        vm/ansible/roles/nginx/tests/test.yml                                                                                                                                                                 
        vm/ansible/roles/nginx/vars/Debian.yml                                                                                                                                                                
        vm/ansible/roles/nginx/vars/RedHat.yml                                                                                                                                                                
        vm/ansible/roles/swap/defaults/main.yml                                                                                                                                                               
        vm/ansible/roles/swap/tasks/main.yml                                                                                                                                                                  
        vm/ansible/roles/wkhtmltopdf/defaults/main.yml                                                                                                                                                        
        vm/ansible/roles/wkhtmltopdf/tasks/main.yml                                                                                                                                                           
        vm/ansible/templates/mariadb_config.cnf                                                                                                                                                               
        vm/ansible/templates/nginx.conf                                                                                                                                                                       
        vm/ansible/vars.yml                                                                                                                                                                                   
        vm/ansible/vm.yml                                                                                                                                                                                     
        vm/ansible/vm_vars/all.yml                                                                                                                                                                            
        vm/build.py                                                                                                                                                                                           
        vm/scripts/install_ansible.sh                                                                                                                                                                         
        vm/scripts/set_message.sh                                                                                                                                                                             
        vm/scripts/zerofree.sh                                                                                                                                                                                
        vm/vm.json                                                                                                                                                                                            
Please, commit your changes or stash them before you can merge.                                                                                                                                               
Aborting                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                            
  File "/usr/local/bin/bench", line 11, in <module>                                                                                                                                                           
    load_entry_point('bench', 'console_scripts', 'bench')()                                                                                                                                                   
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli                                                                                                                                                    
    bench_command()                                                                                                                                                                                           
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__                                                                                                                          
    return self.main(*args, **kwargs)                                                                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main                                                                                                                              
    rv = self.invoke(ctx)                                                                                                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke                                                                                                                           
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke                                                                                                                            
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke                                                                                                                            
    return callback(*args, **kwargs)                                                                                                                                                                          
  File "/home/frappe/.bench/bench/commands/update.py", line 35, in update                                                                                                                                     
    update_bench()                                                                                                                                                                                            
  File "/home/frappe/.bench/bench/utils.py", line 246, in update_bench                                                                                                                                        
    exec_cmd("git pull", cwd=cwd)                                                                                                                                                                             
  File "/home/frappe/.bench/bench/utils.py", line 130, in exec_cmd                                                                                                                                            
    raise CommandFailedError(cmd)                                                                                                                                                                             
bench.utils.CommandFailedError: git pull                                                                                                                                                                      `

**Comment by garybsimon** [comment]
Solved, I have manually updated the .bench, then everything back to normal.
