### ISSUE TITLE
Expense Claim can't be cancelled

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#13694]
"Expense Claim", already payed can't be cancelled:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 45, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 836, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 826, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/expense_claim/expense_claim.py", line 87, in on_cancel
    self.update_claimed_amount_in_employee_advance()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/expense_claim/expense_claim.py", line 91, in update_claimed_amount_in_employee_advance
    frappe.get_doc("Employee Advance", d.employee_advance).update_claimed_amount()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/employee_advance/employee_advance.py", line 63, in update_claimed_amount
    frappe.db.set_value("Employee Advance", self.name, "claimed_amount", claimed_amount)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 678, in set_value
    values, debug=debug)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'claimed_amount' cannot be null")

**Comment by ashish-greycube** [comment]
fixed, will send a PR soon

**Comment by ashish-greycube** [comment]
PR - https://github.com/frappe/erpnext/pull/15794
