### ISSUE TITLE
Purchase Order unexpected argument 'cache'

### ISSUE THREAD

**Issue by agritheory** [frappe/erpnext#13847]
Clicking into the Item Code field in Purchase order:
![image](https://user-images.githubusercontent.com/18033666/39438632-c6cdaff4-4c72-11e8-99f8-4e0655baec4d.png)
Raises this error. 

ERPNext: v10.1.27 (master)
Frappe Framework: v10.0.16 (master)

The [spec](https://frappe.io/docs/current/api/frappe.database#count) for `frappe.db.count` does not allow for a keyword argument called `cache`:
```
count (self, dt, filters=None, debug=False)
    Returns COUNT(*) for given DocType and filters.
```
But it is passing it in [here](https://github.com/frappe/erpnext/blob/develop/erpnext/controllers/queries.py#L156):

```
def item_query(doctype, txt, searchfield, start, page_len, filters, as_dict=False):
	conditions = []

	description_cond = ''
	if frappe.db.count('Item', cache=True) < 50000:
		# scan description only if items are less than 50000
		description_cond = 'or tabItem.description LIKE %(txt)s'
```
My local develop branch has the identical code and does not raise an error, so I'm not sure what's going on. 

```
Traceback (most recent call last):
  File "/home/admin/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/admin/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/admin/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/admin/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/admin/frappe-bench/apps/frappe/frappe/desk/search.py", line 14, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_length=page_length, filters=filters)
  File "/home/admin/frappe-bench/apps/frappe/frappe/desk/search.py", line 35, in search_widget
    searchfield, start, page_length, filters, as_dict=as_dict)
  File "/home/admin/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/admin/frappe-bench/apps/erpnext/erpnext/controllers/queries.py", line 156, in item_query
    if frappe.db.count('Item', cache=True) < 50000:
TypeError: count() got an unexpected keyword argument 'cache'
```

**Comment by nabinhait** [comment]
You have to update frappe repository as well. ERPNext is always depends on Frappe.

**Comment by khaledalhashem** [comment]
I'm having the same issue when adding items to invoices etc. following is my error;

	

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 51, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_length=page_length, filters=filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 75, in search_widget
    searchfield, start, page_length, filters, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/queries.py", line 156, in item_query
    if frappe.db.count('Item', cache=True) < 50000:
TypeError: count() got an unexpected keyword argument 'cache'

I beleive @nabinhait closed this thread stating that frappe repository needs to be updated too, but does not mention how it's done. Please clarify.

Thanks :)
