### ISSUE TITLE
Issue when a product is added to a BOM

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#13915]
The error occurs when tried to add an Item which hasn't price in price list to a BOM

ERPNext: v10.1.20 (master)
Frappe Framework: v10.1.21 (master)

Thanks
```
Traceback (most recent call last):
  File "/home/erp/erpnext/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erp/erpnext/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 81, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/run_method.py", line 39, in runserverobj
    r = doc.run_method(method, args)
  File "/home/erp/erpnext/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erp/erpnext/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erp/erpnext/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erp/erpnext/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erp/erpnext/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 121, in get_bom_material_detail
    rate = self.get_rm_rate(args)
  File "/home/erp/erpnext/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 166, in get_rm_rate
    rate = flt(rate * self.conversion_rate)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by fproldan** [comment]
Did anyone face the same issue?
