### ISSUE TITLE
Error in creating ToDo

### ISSUE THREAD

**Issue by MuhammadAbouzeid** [frappe/erpnext#13935]
Hello,
I created a ToDo with little words in description (about 7 words). It is Ok.
But, when I tried to add more words in description, an error found:

Title: frappe.utils.global_search.sync_global_search
Error:
{'retry': 0, 'log': <function log at 0x7fa650951398>, 'site': u'erpviral.hypersystems', 'event': None, 'method_name': u'frappe.utils.global_search.sync_global_search', 'method': <function sync_global_search at 0x7fa65122b140>, 'user': u'admin@viral-soft.com', 'kwargs': {'flags': [{'name': '1a102fc8e8', 'title': u'This 2nd ToDo is also for testing.<div><br></div><div>Follow up email inbox problem that any incoming emails go to administrator communication instead of going directly to recipient inbox. I followed the instructions accurately. I created email domain, 2 email accounts: default inbox and default sending. I created email account for recipient and checked (can send) and (can receive) check boxes. And I tied this email account with recipient user</div>', 'route': None, 'doctype': u'ToDo', 'content': u'Status : Open ||| Allocated To : admin@viral-soft.com ||| Description : This 2nd ToDo is also for testing.Follow up email inbox problem that any incoming emails go to administrator communication instead of going directly to recipient inbox. I followed the instructions accurately. I created email domain, 2 email accounts: default inbox and default sending. I created email account for recipient and checked (can send) and (can receive) check boxes. And I tied this email account with recipient user', 'published': 0}]}, 'async': True, 'job_name': u'frappe.utils.global_search.sync_global_search'}
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/global_search.py", line 316, in sync_global_search
    content = %(content)s''', value)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 195, in sql
    self._cursor.execute(query, values)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
DataError: (1406, u"Data too long for column 'title' at row 1")

I understood that Data too long for column 'title, But, I cannot find a (Title) in ToDo form

Thanks for your effort,

**Comment by Zlash65** [comment]
Can you provide a gif or elaborate on how to replicate this error as I'm unable to do so in my instance.

**Comment by ashish-greycube** [comment]
@MuhammadAbouzeid , can you please give us exact steps? I am able create todo with long descriptions without any issue. thanks
