### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by datavici** [frappe/erpnext#13978]
When browsing website/products for the web site, the following error occurs:

Uncaught error exception:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 39, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 133, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 149, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 156, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 169, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 89, in build_context
    ret = context.doc.get_context(context)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 69, in get_context
    limit=context.page_length + 1, search=frappe.form_dict.get("search")),
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 109, in get_product_list_for_group
    data = adjust_qty_for_expired_items(data)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 121, in adjust_qty_for_expired_items
    qty = stock_qty_dict.stock_qty[0][0]
IndexError: tuple index out of range

bug referenced here:

https://discuss.erpnext.com/t/error-trying-to-show-product-category/35844

**Comment by Anurag810** [comment]
fixed
