### ISSUE TITLE
Error while bench updates after switching to master branch

### ISSUE THREAD

**Issue by paramjitrohits** [frappe/erpnext#14133]
Hello all.

I have a develop-branch of ERPNext installed. When I switch to master branch and run `bench update --patch`, I get the following error. I believe this error is part of the python3 upgrade process, and I couldn't find any help from the [single post](https://discuss.erpnext.com/t/error-typeerror-a-bytes-like-object-is-required-not-list-after-bench-update/35183/4) I saw on the forum. In my machine, `python` points to `python3` for your information.

```bash
  Backing up sites...
  Patching sites...
  Migrating site1.local
  Traceback (most recent call last):
    File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
      main()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
      click.Group(commands=commands)(prog_name='bench')
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
      ret = f(frappe._dict(ctx.obj), *args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
      migrate(context.verbose, rebuild_website=rebuild_website)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 33, in migrate
      frappe.model.sync.sync_all(verbose=verbose)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/sync.py", line 16, in sync_all
      block_user(True)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 118, in block_user
      frappe.db.set_global('__session_status', block and 'stop' or None)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/database.py", line 719, in set_global
      self.set_default(key, val, user)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/database.py", line 727, in set_default
      frappe.defaults.set_default(key, val, parent, parenttype)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/defaults.py", line 109, in set_default
      add_default(key, value, parent)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/defaults.py", line 120, in add_default
      d.insert(ignore_permissions=True)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 210, in insert
      self._set_defaults()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 585, in _set_defaults
      new_doc = frappe.new_doc(self.doctype, as_dict=True)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 614, in new_doc
      return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/create_new.py", line 20, in get_new_doc
      frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/create_new.py", line 41, in make_new_doc
      set_user_and_static_default_values(doc)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/create_new.py", line 51, in set_user_and_static_default_values
      user_permissions = get_user_permissions()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/core/doctype/user_permission/user_permission.py", line 67, in get_user_permissions
      fields=['allow', 'for_value'], filters=dict(user=user)):
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1177, in get_all
      return get_list(doctype, *args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1150, in get_list
      return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 88, in execute
      result = self.build_and_run()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 100, in build_and_run
      args = self.prepare_args()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 119, in prepare_args
      self.build_conditions()
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 279, in build_conditions
      self.build_filter_conditions(self.filters, self.conditions)
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 300, in build_filter_conditions
      conditions.append(self.prepare_filter_condition(f))
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 371, in prepare_filter_condition
      value = '"{0}"'.format(frappe.db.escape(value, percent=False))
    File "/home/username/.erpnext/frappe-bench/apps/frappe/frappe/database.py", line 904, in escape
      s = text_type(pymysql.escape_string(s), "utf-8").replace("`", "\\`")
    File "/home/username/.erpnext/frappe-bench/env/lib/python3.6/site-packages/pymysql/converters.py", line 73, in _escape_unicode
      return value.translate(_escape_table)
  TypeError: a bytes-like object is required, not 'list'
```

**Comment by paramjitrohits** [comment]
Well, my system points to `python3` via the `python` command. It seems this bug is also related to the py2 to py3 migration. I temporarily fixed it by moving my system symlinks of python to point to python2 and bench updating.
