### ISSUE TITLE
Receiving 500 in signup module

### ISSUE THREAD

**Issue by sohamnavadiya** [frappe/erpnext#14183]
I have setup ERPNEXT on AWS EC2 instance. After set it up, I tried to signup but receiving following error.
```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 783, in sign_up
    user.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in run_post_save_methods
    self.run_method("on_update")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 95, in on_update
    self.send_password_notification(self.__new_password)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 204, in send_password_notification
    self.send_welcome_mail_to_user()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 273, in send_welcome_mail_to_user
    site_url=get_url(),
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 302, in send_login_mail
    delayed=(not now) if now!=None else self.flags.delay_emails, retry=3)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 440, in sendmail
    inline_images=inline_images, header=header, print_letterhead=print_letterhead)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/email/queue.py", line 72, in send
    sender = email_account.default_sender
AttributeError: 'NoneType' object has no attribute 'default_sender'
```

Any suggestion welcome and appriciated.

**Comment by kennethsequeira** [comment]
@sohamnavadiya This is because you haven't set up a default account for sending emails. Log in as admin first and then create a user.

Set up an outgoing email account and then sign up and see.

https://erpnext.org/docs/user/manual/en/setting-up/email/email-account

**Comment by sohamnavadiya** [comment]
@kennethsequeira Thank for your suggestion. I have one question,
*Where to get the Admin username and password?*

**Comment by kennethsequeira** [comment]
You have created the admin ID and password when creating a new site.

When you do `bench new-site <sitename>` it prompts for an admin password. 

The username is Administrator. 

If you want to reset the admin password use `bench —site <sitename> set-admin-password <password>`
