### ISSUE TITLE
Bench Update Fails On Erpnext Patch Apply

### ISSUE THREAD

**Issue by vbaidak** [frappe/erpnext#14188]
This is a duplicate of the orignal issue:
[Bench Update Fails On Erpnext Patch Apply](https://github.com/frappe/frappe/issues/5549)

We are unable to **bench update** with the following stacktrace:

```python
Executing erpnext.patches.v9_0.fix_subscription_next_date #2017-10-23 in *** (erpnextdb)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/patches/v9_0/fix_subscription_next_date.py", line 16, in execute
    filters = {'reference_doctype': ('in', doctypes), 'docstatus': 1}):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1180, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1153, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
    args = self.prepare_args()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 278, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 299, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/db_query.py", line 307, in prepare_filter_condition
    f = get_filter(self.doctype, f)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/data.py", line 827, in get_filter
    if frappe.get_meta(df.options).has_field(f.fieldname):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 658, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/meta.py", line 34, in get_meta
    lambda: Meta(doctype))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 173, in hget
    value = generator()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/meta.py", line 34, in <lambda>
    lambda: Meta(doctype))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/meta.py", line 73, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 104, in __init__
    self.load_from_db()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/meta.py", line 78, in load_from_db
    super(Meta, self).load_from_db()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 327, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 313, in msgprint
    _raise_exception()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 286, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType Subscription Plan Detail not found
```

A solution was manually adding the following items into **tabDocType**:
* **Subscription Plan Detail**
* **Subscription Invoice**

**Comment by paramjitrohits** [comment]
Which branch are you using? Also please give the output of `bench version`.

**Comment by vbaidak** [comment]
Hi, **paramjitrohits**, I've updated few times after noticing this issue, so currently **bench version** won't show the failed one.

I think this were somewhere in v9.0 patch updates as you might see from the output

**Comment by vbaidak** [comment]
@paramjitrohits , the purpose of this ticket was just to inform the team that I faced with such issue - a possible bug in migration scripts.
Currently I have no problems with ERPNext since, as I wrote previously, I manually fixed the issue above. I just wanted to let the team know about it.

I think we can close the issue if no one else having it

**Comment by Olawale1** [comment]
Hi @vbaidak 

facing the same error currently. Could you please elaborate on how to manually add the entries into tabDocType?

Kind regards,

**Comment by Olawale1** [comment]
Thanks a lot for you quick response @vbaidak 

Another option is to run the following commands:

```
bench --force --site <your-site> reload-doc accounts doctype subscription_plan_detail
bench --force --site <your-site> reload-doc accounts doctype subscription_invoice
```

Cheers

**Comment by vbaidak** [comment]
Thanks, @Olawale1 , I didn't know there was such an option
