### ISSUE TITLE
After login to administrator account, Got following error.

### ISSUE THREAD

**Issue by sohamnavadiya** [frappe/erpnext#14189]
I have setup this project in EC2 instance. After signin with Administrator credential I am receiving following error.
```
10:41:39 web.1            |  * Detected change in '/home/ubuntu/frappe-bench/apps/frappe/frappe/www/__pycache__/desk.cpython-35.pyc', reloading
10:41:39 web.1            | INFO:werkzeug: * Detected change in '/home/ubuntu/frappe-bench/apps/frappe/frappe/www/__pycache__/desk.cpython-35.pyc', reloading
10:41:40 web.1            |  * Restarting with inotify reloader
10:41:41 web.1            |  * Debugger is active!
10:41:41 web.1            |  * Debugger PIN: 286-413-651
10:41:44 web.1            | b'Traceback (most recent call last):\n  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/context.py", line 48, in update_controller_context\n    ret = module.get_context(context)\n  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/www/desk.py", line 40, in get_context\n    "build_version": get_build_version(),\n  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/www/desk.py", line 84, in get_build_version\n    return str(os.path.getmtime(os.path.join(frappe.local.sites_path, \'.build\')))\n  File "/home/ubuntu/frappe-bench/env/lib/python3.5/genericpath.py", line 55, in getmtime\n    return os.stat(filename).st_mtime\nFileNotFoundError: [Errno 2] No such file or directory: \'./.build\'\n'

```

**Comment by mihir-kandoi** [comment]
This appears to be a bench / environment setup issue rather than ERPNext core, so I'm closing it here as part of issue triage. If it still happens on a current version, please open a new issue in the `frappe/bench` repository. If you think this was closed in error, mention @mihir-kandoi here.
