### ISSUE TITLE
Getting below error in development environment

### ISSUE THREAD

**Issue by sohamnavadiya** [frappe/erpnext#14181]
12:53:43 redis_socketio.1 | 11353:M 22 May 12:53:43.047 * The server is now ready to accept connections on port 12000
12:53:43 system           | worker_short.1 started (pid=11360)
12:53:43 socketio.1       | module.js:549
12:53:43 socketio.1       |     throw err;
12:53:43 socketio.1       |     ^
12:53:43 socketio.1       | 
12:53:43 socketio.1       | Error: Cannot find module 'express'
12:53:43 socketio.1       |     at Function.Module._resolveFilename (module.js:547:15)
12:53:43 socketio.1       |     at Function.Module._load (module.js:474:25)
12:53:43 socketio.1       |     at Module.require (module.js:596:17)
12:53:43 socketio.1       |     at require (internal/module.js:11:18)
12:53:43 socketio.1       |     at Object.<anonymous> (/home/ubuntu/frappe-bench/apps/frappe/socketio.js:1:73)
12:53:43 socketio.1       |     at Module._compile (module.js:652:30)
12:53:43 socketio.1       |     at Object.Module._extensions..js (module.js:663:10)
12:53:43 socketio.1       |     at Module.load (module.js:565:32)
12:53:43 socketio.1       |     at tryModuleLoad (module.js:505:12)
12:53:43 socketio.1       |     at Function.Module._load (module.js:497:3)

**Comment by paramjitrohits** [comment]
Do you have all npm modules installed? It might be helpful to try the following:
1. Move to the `frappe` directory (meaning wherever frappe is installed). There should be a `package.json` here. Use the command `npm install` here. This will install all modules needed for frappe, etc. (What confuses me is this should already have been executed while using the bench commands. In any case, using `npm install` will install all required modules)
2. Install `yarn` since you will need it by `npm install yarn` in the same directory or `npm install -g yarn` for a global install. 

I hope the above works. In any case, you can always using `npm install express` to install the `express` module. However, the above is recommended as there might be more missing dependencies.

**Comment by mihir-kandoi** [comment]
This appears to be a bench / environment setup issue rather than ERPNext core, so I'm closing it here as part of issue triage. If it still happens on a current version, please open a new issue in the `frappe/bench` repository. If you think this was closed in error, mention @mihir-kandoi here.
