### ISSUE TITLE
Consultation Diagnosis - ASCII coden

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#14194]
Can't use latin characters.

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1010, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 17, in on_update
    update_consultation_to_medical_record(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 117, in update_consultation_to_medical_record
    subject = set_subject_field(consultation)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 128, in set_subject_field
    subject = "Diagnosis: \n"+ str(consultation.diagnosis)+". "
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 18: ordinal not in range(128)

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1010, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 17, in on_update
    update_consultation_to_medical_record(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 117, in update_consultation_to_medical_record
    subject = set_subject_field(consultation)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/consultation/consultation.py", line 128, in set_subject_field
    subject = "Diagnosis: \n"+ str(consultation.diagnosis)+". "
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 18: ordinal not in range(128)
```

**Comment by kennethsequeira** [comment]
Can you add a screenshot of the characters used?

**Comment by franciscobuendiao** [comment]
Accented letters and 'ñ', it only happens in 'diagnosis'

![hospital](https://user-images.githubusercontent.com/25084259/40489030-c6838230-5f2d-11e8-98c6-a0b5d87fb76d.jpg)
