### ISSUE TITLE
Error Urgent : Not able to approve and submit the leave application

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#14216]
App Versions

{
	"erpnext": "10.1.35",
	"frappe": "10.1.33"
}

Route

Form/Leave Application/LAP/00012

Error Report

Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 759, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 30, in validate
    self.validate_max_days()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 255, in validate_max_days
    max_days = frappe.db.get_value("Leave Type", self.leave_type, "max_continuous_days_allowed")
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 482, in get_value
    order_by, cache=cache)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 526, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 666, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 199, in sql
    self._cursor.execute(query, values)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'max_continuous_days_allowed' in 'field list'")

Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 759, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 30, in validate
    self.validate_max_days()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 255, in validate_max_days
    max_days = frappe.db.get_value("Leave Type", self.leave_type, "max_continuous_days_allowed")
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 482, in get_value
    order_by, cache=cache)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 526, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 666, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 199, in sql
    self._cursor.execute(query, values)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'max_continuous_days_allowed' in 'field list'")

Request Data

{
	"type": "POST",
	"args": {
		"doc": "{\"naming_series\":\"LAP/\",\"creation\":\"2018-05-19 15:11:24.523593\",\"leave_approver\":\"siddesh@tecobytes.com\",\"doctype\":\"Leave Application\",\"owner\":\"raghu@tecobytes.com\",\"letter_head\":\"TecoBytes Solutions Pvt Ltd\",\"to_date\":\"2018-05-24\",\"half_day\":0,\"modified_by\":\"parvati@tecobytes.com\",\"leave_type\":\"Earned Leave\",\"leave_balance\":12,\"from_date\":\"2018-05-21\",\"docstatus\":0,\"status\":\"Approved\",\"description\":\"Emergency earned leave - \\n\",\"company\":\"Tecobytes Solutions Pvt. Ltd.\",\"employee\":\"EMP-TB-00011\",\"employee_name\":\"Raghu Y Diggi\",\"name\":\"LAP/00012\",\"idx\":0,\"total_leave_days\":4,\"follow_via_email\":1,\"modified\":\"2018-05-21 09:29:59.811859\",\"leave_approver_name\":\"Siddesh Hoogar\",\"posting_date\":\"2018-05-19\",\"__last_sync_on\":\"2018-05-24T11:34:53.976Z\",\"__unsaved\":1}",
		"action": "Save",
		"cmd": "frappe.desk.form.save.savedocs"
	},
	"btn": {
		"jQuery224063220900859328471": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 591,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"url": "/"
}

Response JSON

{
	"_server_messages": "[\"{\\\"message\\\": \\\"Did not save\\\"}\"]"
}

**Comment by worldofsmarty** [comment]
Any Update on this as this is very critical and due to recent update not able to add leaves to employees.

**Comment by worldofsmarty** [comment]
Big Thanks to Mr. Suraj from ERPnext team, Below is the solution which worked for me. I am sharing so that it can be helpful for anyone facing the similar issue.

Following commands should fix the issue,

1. Run bench --site <site-name> console
2. In the console enter frappe.db.sql_ddl("""ALTER TABLE `tabLeave Type` CHANGE `max_days_allowed` `max_continuous_days_allowed` int(8) NOT NULL;""")
3. Then frappe.db.commit()
4.  Exit the console and restart your bench server (Optional).

I am now closing this issue.
