### ISSUE TITLE
Exception in Property Setter

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#14221]
The following error is being generated on some of the sites in the latest build

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/migrate.py", line 41, in migrate
    frappe.model.sync.sync_all(verbose=verbose)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/sync.py", line 19, in sync_all
    sync_for(app, force, verbose=verbose, reset_permissions=reset_permissions)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 123, in import_doc
    frappe.delete_doc(doc.doctype, doc.name, force=1, ignore_doctypes=ignore, for_reload=True)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/__init__.py", line 676, in delete_doc
    ignore_permissions, flags, ignore_on_trash, ignore_missing)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 54, in delete_doc
    doc.run_method("before_reload")
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 329, in before_reload
    self.preserve_naming_series_options_in_property_setter()
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 347, in preserve_naming_series_options_in_property_setter
    make_property_setter(self.name, "naming_series", "options", naming_series[0].options, "Text", validate_fields_for_doctype=False)
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 86, in make_property_setter
    property_setter.insert()
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/document.py", line 237, in insert
    raise e
frappe.exceptions.DuplicateEntryError: (u'Property Setter', u'Sales Invoice-naming_series-options', IntegrityError(1062, u"Duplicate entry 'Sales Invoice-naming_series-options' for key
 'PRIMARY'"))

If in the database if the the value of property = “fetch_from” in table PropertySetter with name Sales Invoice-naming_series-options, then it is not able find the naming series in sales invoice and it tries to insert a new record with the same primary key leading to exception.
If the value of property=“options” then it is able to find it.

**Comment by jaichavan** [comment]
Hello, @amitsaxena01 
Thanks for reporting the issue.
