### ISSUE TITLE
 Error While accessing Leave Type Page : Developers Bug

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#14286]
Error While accessing Leave Type Page : Developers Bug 

App Versions

{
	"erpnext": "10.1.35",
	"frappe": "10.1.34"
}

Route

List/Leave Type/List

Error Report

Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/reportview.py", line 21, in get
    data = compress(execute(**args), args = args)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/reportview.py", line 26, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 111, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tabLeave Type.max_days_allowed' in 'field list'")

Request Data

{
	"type": "GET",
	"args": {
		"doctype": "Leave Type",
		"fields": "[\"`tabLeave Type`.`name`\",\"`tabLeave Type`.`owner`\",\"`tabLeave Type`.`creation`\",\"`tabLeave Type`.`modified`\",\"`tabLeave Type`.`modified_by`\",\"`tabLeave Type`.`_user_tags`\",\"`tabLeave Type`.`_comments`\",\"`tabLeave Type`.`_assign`\",\"`tabLeave Type`.`_liked_by`\",\"`tabLeave Type`.`docstatus`\",\"`tabLeave Type`.`parent`\",\"`tabLeave Type`.`parenttype`\",\"`tabLeave Type`.`parentfield`\",\"`tabLeave Type`.`idx`\",\"`tabLeave Type`.`leave_type_name`\",\"`tabLeave Type`.`max_days_allowed`\",\"`tabLeave Type`.`is_carry_forward`\",\"`tabLeave Type`.`is_encash`\"]",
		"filters": "[]",
		"order_by": "`tabLeave Type`.`modified` desc",
		"start": 0,
		"page_length": 20,
		"with_comment_count": true,
		"cmd": "frappe.desk.reportview.get"
	},
	"freeze": false,
	"freeze_message": "Loading...",
	"url": "/"
}

Response JSON

{}

**Comment by worldofsmarty** [comment]
This issue has been resolved. Thank you ERPNext team.
