### ISSUE TITLE
SQL syntax Error

### ISSUE THREAD

**Issue by mofaba** [frappe/erpnext#14320]
**App Versions**

{
	"erpnext": "10.1.36",
	"frappe": "10.1.35"
}

**Route**

Tree/Item Group

**Error Report**

Traceback (most recent call last):
  File "/home/erpnext/bench-core/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/erpnext/bench-core/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/erpnext/bench-core/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/bench-core/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/erpnext/bench-core/apps/frappe/frappe/desk/treeview.py", line 50, in get_children
    order_by='name')
  File "/home/erpnext/bench-core/apps/frappe/frappe/__init__.py", line 1153, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/erpnext/bench-core/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/erpnext/bench-core/apps/frappe/frappe/model/db_query.py", line 111, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/erpnext/bench-core/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/erpnext/bench-core/env/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1064, u'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \') = "" and ifnull(`tabItem Group`.docstatus, "") < "2"\n\t\t\t  order by name\' at line 1')

**Request Data**

{
	"type": "POST",
	"args": {
		"doctype": "Item Group",
		"cmd": "frappe.desk.treeview.get_children"
	},
	"url": "/"
}

**Comment by mofaba** [comment]
cannot create new item group

**Comment by inadric** [comment]
i have this problem too,

hope it gets fixed

**Comment by Zlash65** [comment]
This issue was probably fixed by this - https://github.com/frappe/frappe/pull/5655

Reopen this issue if its still present.
