### ISSUE TITLE
Error: Uncaught Server Exception on job listing portal

### ISSUE THREAD

**Issue by unmesh87** [frappe/erpnext#14336]
Got below error while exploring job posting on [ERPNext jobs](https://erpnext.org/erpnext-jobs). 

Issue faced on browser-

- Chrome 

- Firefox 

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/render.py", line 40, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/render.py", line 134, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/render.py", line 150, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/render.py", line 157, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/render.py", line 170, in build_page
    context = get_context(path)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/frappe/website/context.py", line 89, in build_context
    ret = context.doc.get_context(context)
  File "/home/frappe/benches/bench-2017-01-23/apps/foundation/foundation/erpnext_foundation/doctype/portal_job/portal_job.py", line 16, in get_context
    context.is_member = foundation.is_member()
  File "/home/frappe/benches/bench-2017-01-23/apps/foundation/foundation/__init__.py", line 29, in is_member
    last_membership = get_last_membership()
  File "/home/frappe/benches/bench-2017-01-23/apps/foundation/foundation/__init__.py", line 16, in get_last_membership
    return last_membership and last_membership[0]
UnboundLocalError: local variable 'last_membership' referenced before assignment
```
**Note**-
Above error is not displayed when user logs through member login.

**Comment by unmesh87** [comment]
Working now!
