### ISSUE TITLE
Installation Failure Ubuntu 14.04/16.04/Debian 9

### ISSUE THREAD

**Issue by shadowgrapher** [frappe/erpnext#14415]
Used easy script with no success on 3 _fresh_ systems (above). Same error with bench every time.
 
```
"INFO:bench.app:installing erpnext", 
        "INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext --no-cache-dir", 
        "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!", 
        "  RequestsDependencyWarning)", 
        "Traceback (most recent call last):", 
        "  File \"/usr/lib/python3.5/runpy.py\", line 193, in _run_module_as_main", 
        "    \"__main__\", mod_spec)", 
        "  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code", 
        "    exec(code, run_globals)", 
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>", 
        "    main()", 
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main", 
        "    click.Group(commands=commands)(prog_name='bench')", 
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 722, in __call__", 
        "    return self.main(*args, **kwargs)", 
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 676, in main", 
        "    _verify_python3_env()", 
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/_unicodefun.py\", line 118, in _verify_python3_env", 
        "    'for mitigation steps.' + extra)", 
        "RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.", 
        "", 
        "This system supports the C.UTF-8 locale which is recommended.", 
        "You might be able to resolve your issue by exporting the", 
        "following environment variables:", 
        "", 
        "    export LC_ALL=C.UTF-8", 
        "    export LANG=C.UTF-8"
    ], 
    "stdout": "('installing', u'erpnext')", 
    "stdout_lines": [
        "('installing', u'erpnext')"
    ]
}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=79   changed=27   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '-vvvv', '--become', '--become-user=frappe']' returned non-zero exit status 2
```
verbose log `python install.py --production --user frappe --verbose` is attached
[vps.txt](https://github.com/frappe/erpnext/files/2083402/vps.txt)

**Comment by shadowgrapher** [comment]
Even though my default python is Python 2.7, this fixed after

    apt-get remove python3.5
    apt-get install python2.7

But here is new one:

    fatal: [localhost]: FAILED! => {
        "changed": true, 
        "cmd": [
            "bench", 
            "new-site", 
            "site1.local", 
            "--admin-password", 
            "administrator", 
            "--mariadb-root-password", 
            "password"
        ], 
        "delta": "0:00:01.153891", 
        "end": "2018-06-08 10:30:09.866002", 
        "invocation": {
            "module_args": {
                "_raw_params": "bench new-site site1.local --admin-password administrator --mariadb-root-password password", 
                "_uses_shell": false, 
                "chdir": "/home/frappe/frappe-bench", 
                "creates": null, 
                "executable": null, 
                "removes": null, 
                "stdin": null, 
                "warn": true
            }
        }, 
        "msg": "non-zero return code", 
        "rc": 2, 
        "start": "2018-06-08 10:30:08.712111", 
        "stderr": "Usage: bench [OPTIONS] COMMAND [ARGS]...\n\nError: No such command \"new-site\".", 
        "stderr_lines": [
            "Usage: bench [OPTIONS] COMMAND [ARGS]...", 
            "", 
            "Error: No such command \"new-site\"."
        ], 
        "stdout": "", 
        "stdout_lines": []
    }
    	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

    PLAY RECAP ******************************************************************************************************************
    localhost                  : ok=75   changed=12   unreachable=0    failed=1   

    Traceback (most recent call last):
      File "install.py", line 417, in <module>
        install_bench(args)
      File "install.py", line 122, in install_bench
        run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
      File "install.py", line 338, in run_playbook
        success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '-vvvv', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by dottenbr** [comment]
Related? https://github.com/frappe/erpnext/issues/15889

**Comment by gavindsouza** [comment]
Closing due to inactivity. Open a new one if issue persists.
