### ISSUE TITLE
error while creating new slide show

### ISSUE THREAD

**Issue by itskaps** [frappe/erpnext#14416]
Issue: Bug report

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

**Do the checklist before filing an issue:**
 - [x] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [x] Can you replicate the issue? 
 
**Describe the bug** :chart_with_downwards_trend: 

**To R
- [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome
eproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ ] Linux
    - [ ] macOS
    - [  ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [  ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [  ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin: 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 14, in validate
    self.validate_images()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 25, in validate_images
    result = frappe.get_all("File", filters={ "file_url":("in", files) }, fields="is_private")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1180, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1153, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
    args = self.prepare_args()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 280, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 301, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 327, in prepare_filter_condition
    values = values.split(",")
AttributeError: 'map' object has no attribute 'split'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 14, in validate
    self.validate_images()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 25, in validate_images
    result = frappe.get_all("File", filters={ "file_url":("in", files) }, fields="is_private")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1180, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1153, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
    args = self.prepare_args()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 280, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 301, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 327, in prepare_filter_condition
    values = values.split(",")
AttributeError: 'map' object has no attribute 'split'

**Comment by itskaps** [comment]
hello any update on how to solve this?

**Comment by tiwiex** [comment]
Same problem here. ERPNext is cool but this error is an issue. I see it is something to do with Python 3 code compatibility.

Any help will help.

**Comment by clarkejj** [comment]
found on Frappe version: v11.0.3-beta.41 as noted here https://discuss.erpnext.com/t/website-slide-show-attributeerror-map-object-has-no-attribute-split/43904/2

**Comment by stapeldev** [comment]
Just to circle back on this issue, it should have been resolved in the following Fix: 
https://github.com/frappe/frappe/commit/e6d5a61186def4f8e8c4898c81e275d85b20b45b

**Comment by mofaba** [comment]
> 
> 
> Just to circle back on this issue, it should have been resolved in the following Fix:
> [frappe/frappe@e6d5a61](https://github.com/frappe/frappe/commit/e6d5a61186def4f8e8c4898c81e275d85b20b45b)

please merged this to master, thanks

**Comment by mihir-kandoi** [comment]
This issue has been automatically closed as it no longer appears to be valid. If you think this was closed in error, please mention me (@mihir-kandoi) in a comment here and I'll take another look.
