### ISSUE TITLE
set_update_field_and_value_in_workflow_state fails to run during bench update

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#14440]
Issue: bench update fails on running erpnext.patches.v11_0.set_update_field_and_value_in_workflow_state

When I update a developer site from 10.1 to erpnext.patches.v11_0.set_update_field_and_value_in_workflow_state then you get the error.

**Do the checklist before filing an issue:**
 - [ ] This is not a usage question.
 - [ ] Yes, can replicate issue with trying to upgrade again and again.
 - [ ] I cannot fix the problem, but the error below indicates that the statement "frappe.set_value('Workflow Document State', state.name, 'update_field', status_field)" has failed.

**Describe the bug** :chart_with_downwards_trend: 
Executing erpnext.patches.v11_0.set_update_field_and_value_in_workflow_state in mysite.com ()
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v11_0/set_update_field_and_value_in_workflow_state.py", line 17, in execute
    frappe.set_value('Workflow Document State', state.name, 'update_field', status_field)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in set_value
    return frappe.client.set_value(doctype, docname, fieldname, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 136, in set_value
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 293, in _save
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 734, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 327, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 313, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 286, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #1: Action: Approve, Row #2: Action: Reject

**To Reproduce** :page_with_curl:
1. Run "bench update --reset" as frappe user
2. See error

**Expected behavior** :chart_with_upwards_trend:
I expected that the update would be completed successfully.

**Screenshots** :crystal_ball:
Error messages pasted in description above.

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ ] n/a
 - Browser:
    - [ ] n/a

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] n/a
 - Browser:
    - [ ] n/a

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [ ] `develop` :fire: 10.1.34
- Frappe Version: Can't find out as site not opening.
- ERPNext Version: Can't find out as site not opening.

**Additional context** :page_facing_up:
Only happens when you do bench update for old sites. New sites created after bench update works. I am having new site running on Frappe Framework: v11.x.x-develop (944626e) (develop) without issues.

**Possible Solution** :bookmark_tabs:
Drop all sites and recreate them!

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin: 

Well noted.

**Comment by joolsr** [comment]
A patch has been created that should allow this to work now. Try your command again

**Comment by aakvatech** [comment]
I didn't see the patch when I did bench update. Will it come through automatically?11.06.2018, 20:11, "Julian Robbins" <notifications@github.com>:A patch has been created that should allow this to work now. Try your command again

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


Best Regards,Mitesh P ChoksiDirector, Aakvatech

**Comment by aakvatech** [comment]
Tried again and it is still not working.
