### ISSUE TITLE
[V11] Error on Saving new Company

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14443]
Traceback (most recent call last):
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 90, in on_update
    self.create_default_accounts()
  File "/Users/umairsayed/Work/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 135, in create_default_accounts
    create_charts(self.name, self.chart_of_accounts, self.existing_company)
  File "/Users/umairsayed/Work/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 56, in create_charts
    _import_accounts(chart, None, None, root_account=True)
  File "/Users/umairsayed/Work/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 50, in _import_accounts
    account.insert()
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 216, in insert
    self.set_new_name()
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 376, in set_new_name
    set_new_name(self)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/naming.py", line 39, in set_new_name
    doc.run_method("autoname")
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/umairsayed/Work/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/umairsayed/Work/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 23, in autoname
    self.name = get_account_autoname(self.account_number, self.account_name, self.company)
NameError: global name 'get_account_autoname' is not defined

**Comment by Zlash65** [comment]
https://github.com/frappe/erpnext/pull/14432 Fixed
