### ISSUE TITLE
Build failing on patch update_total_qty_field.py

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#14470]
Issue: Bug report

The build is failing on the patch update_total_qty_field.py. For `tabSales Order`  the variable when_then is blank leading the failure in the mysql.
Stack Trace:
File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erp_healthcare/frappe-bench/apps/erpnext/erpnext/patches/v11_0/update_total_qty_field.py", line 37, i
n execute
    ''' % (doctype, " ".join(when_then)))
  File "/home/erp_healthcare/frappe-bench/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in e
xecute
    result = self._query(query)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _
query
    conn.query(q)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, 
in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061,
 in _read_query_result
    result.read()
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349,
 in read
    first_packet = self.connection._read_packet()
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018,
 in _read_packet
    packet.check_error()
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, 
in check_error
    err.raise_mysql_exception(self._data)
  File "/home/erp_healthcare/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise
_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to y
our MariaDB server version for the right syntax to use near '' at line 2")

**Comment by EnSeal** [comment]
I have a similar issue while trying to bench update 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "_main_", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in _call_
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/_init_.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/patches/v11_0/update_total_qty_field.py", line 34, in execute
    ''' % (doctype, " ".join(when_then)))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2")

**Comment by shreyashah115** [comment]
#14471 This has been fixed.
