### ISSUE TITLE
error While updating

### ISSUE THREAD

**Issue by itskaps** [frappe/erpnext#14489]
Issue: Bug report

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

**Do the checklist before filing an issue:**
 - [x] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [ ] Can you replicate the issue? 
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [ ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin:

**Comment by itskaps** [comment]
Executing frappe.patches.v11_0.rename_email_alert_to_notification in acsrv.jgandhi.com (55673af97c51b10a)
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:13000. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v11_0/rename_email_alert_to_notification.py", line 6, in execute
    rename_doc('DocType', 'Email Alert', 'Notification')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 52, in rename_doc
    update_user_settings(old, new, link_fields)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 95, in update_user_settings
    sync_user_settings()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/user_settings.py", line 49, in sync_user_settings
    for key, data in iteritems(frappe.cache().hgetall('_user_settings')):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 153, in hgetall
    iteritems(super(redis.Redis, self).hgetall(self.make_key(name)))}
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py", line 1967, in hgetall
    return self.execute_command('HGETALL', name)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:13000. Connection refused.

**Comment by nabinhait** [comment]
@itskaps Are you still getting the issue? If yes, please ensure that your bench is started while migrating / updating.

**Comment by itskaps** [comment]
its updating succesfully now but getting below error in between

`Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Syncing help database...
*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/buildbot/buildbot_run.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/buildbot/buildbot_run.py", line 27
    print '@@@STEP_EXCEPTION@@@'
                               ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/gyptest.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/gyptest.py", line 199
    print test
             ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py", line 464
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py", line 161
    except OSError, e:
                  ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/__init__.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 37
    print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                         ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/common.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 366
    except OSError, e:
                  ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/flock_tool.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/flock_tool.py", line 42
    fd = os.open(lockfile, os.O_WRONLY|os.O_NOCTTY|os.O_CREAT, 0666)
                                                                  ^
SyntaxError: invalid token

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/analyzer.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/analyzer.py", line 158
    print 'AddSource', org_source, result[len(result) - 1]
                    ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/android.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/android.py", line 959
    print 'Building: %s' % arguments
                       ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/cmake.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/cmake.py", line 1183
    print 'Generating [%s]: %s' % (config_name, arguments)
                              ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py", line 99
    print 'Wrote json to %s.' % filename
                            ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1611
    print "WARNING: no output for", self.type, target
                                 ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py", line 1952
    print 'Building [%s]: %s' % (config, arguments)
                            ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py", line 475
    print "Warning: Actions/rules writing object files don't work with " \
                                                                       ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 131
    except OSError, e:
                  ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/input.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 247
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py", line 129
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 76
    print 'Warning: Ignoring unsupported variable "%s".' % variable
                                                       ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcode_ninja.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcode_ninja.py", line 31
    except OSError, e:
                  ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 694
    except TypeError, e:
                    ^
SyntaxError: invalid syntax

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/tools/graphviz.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/tools/graphviz.py", line 53
    print 'digraph D {'
                      ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_gyp.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_gyp.py", line 122
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_sln.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_sln.py", line 29
    print project
                ^
SyntaxError: Missing parentheses in call to 'print'

*** Error compiling '../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_vcproj.py'...
  File "../apps/frappe/node_modules/node-gyp/gyp/tools/pretty_vcproj.py", line 64
    print '%s%s' % (' '*indent, node.data.strip())
               ^
SyntaxError: invalid syntax
`

**Comment by silverbacknet** [comment]
I just ran into this exact problem. Is there a reason that the bench isn't started during the update script, when it obviously expects it to be started at some point? Right now, a `bench update --force` from the stable vm (--force required for some reason?) will eventually fail with the original error. Not that bench starting works from a cold update on the production VM at this point (https://discuss.erpnext.com/t/stuck-when-running-bench-start/35361), I think I'm going to take my chances with develop.
