### ISSUE TITLE
issues clicking the item button on Stock reconciliation sheet 

### ISSUE THREAD

**Issue by EnSeal** [frappe/erpnext#14497]
I tried using/clicking the item button in stock Reconciliation but it throws an error instead. I think the issue must have been from commit 087a2259d9593d218759e72afd5fe92a00160055

![image](https://user-images.githubusercontent.com/18033246/41337625-a6d8f78e-6ee7-11e8-902f-dfd1de5f26a2.png)

@manassolanki

**Comment by manassolanki** [comment]
@EnSeal Could you comment the entire error log here?

**Comment by EnSeal** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 276, in get_items
    and id.default_warehouse=%s and id.company=%s''', (warehouse, company))
TypeError: can only concatenate tuple (not "list") to tuple
