### ISSUE TITLE
General Ledger Report error

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14554]
1. Create a purchase invoice with TDS. Instructions in below video

![purchase_invoice_test](https://user-images.githubusercontent.com/20460498/41521944-c59495da-72f1-11e8-9c83-c76ef65c68da.gif)

2. Traceback

Traceback (most recent call last):
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/Users/pawan/frappe-bench-random/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 39, in execute
    res = get_result(filters, account_details)
  File "/Users/pawan/frappe-bench-random/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 102, in get_result
    gl_entries = get_gl_entries(filters)
  File "/Users/pawan/frappe-bench-random/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 136, in get_gl_entries
    filters, as_dict=1)
  File "/Users/pawan/frappe-bench-random/apps/frappe/frappe/database.py", line 199, in sql
    self._cursor.execute(query, values)
  File "/Users/pawan/frappe-bench-random/env/lib/python2.7/site-packages/pymysql/cursors.py", line 164, in execute
    query = self.mogrify(query, args)
  File "/Users/pawan/frappe-bench-random/env/lib/python2.7/site-packages/pymysql/cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
KeyError: 'from_date'

**Comment by shreyashah115** [comment]
Not able to replicate.

![tds invoice](https://user-images.githubusercontent.com/17617465/41576576-c77b34b2-73a5-11e8-9d12-1f849bf640f5.gif)

**Comment by PawanMeh** [comment]
Can you share screen shot of your witholding category setup? Also, have you tried to create multiple invoices for the same supplier and checked?

**Comment by shreyashah115** [comment]
Yep, I tried creating multiple invoices, still no error.

Here is the screenshot:

<img width="1270" alt="screen shot 2018-06-19 at 10 27 42 am" src="https://user-images.githubusercontent.com/17617465/41577620-7eee0c78-73ab-11e8-9a0d-d58729611341.png">

**Comment by PawanMeh** [comment]
This seems to be fixed now in the latest version. I am closing this one.
