### ISSUE TITLE
[BUG] Error on latest update

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#14664]
Hello,

on latest update i had several errors:

1. In property setter duplicate entry for all doctypes. I found similar topic on forum and i delete all naming series option that was in error message (SI, PI, SO, DN, QT).  
2After that i push update again. It passed previous error but now gives me this error:

Migrating builderfox
Executing erpnext.patches.v11_0.update_total_qty_field in builderfox (7fc8c448bd593458)
Success: Done in 3.404s
Executing erpnext.patches.v11_0.update_sales_partner_type in builderfox (7fc8c448bd593458)
Success: Done in 0.704s
Executing erpnext.patches.v11_0.rename_asset_adjustment_doctype in builderfox (7fc8c448bd593458)
Success: Done in 0.054s
Executing execute:frappe.db.sql("update `tabDesktop Icon` set type = 'module' where module_name = 'Restaurant'") in builderfox (7fc8c448bd593458)
Success: Done in 0.046s
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Updating DocTypes for pos_linker    : [========================================]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 43, in migrate
    sync_fixtures()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 24, in sync_fixtures
    ignore_links=True, overwrite=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 54, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process, reset_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 132, in import_doc
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 60, in on_update
    validate_fields_for_doctype(self.dt)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 428, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 675, in validate_fields
    check_illegal_default(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 507, in check_illegal_default
    frappe.throw(_("Default for {0} must be an option").format(d.fieldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 327, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 313, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 286, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <exception str() failed>

**Comment by kennethsequeira** [comment]
@vladucoju was this fixed in subsequent updates?

**Comment by vladucoju** [comment]
I will try to update again later. Hope error will be fixed.

**Comment by vladucoju** [comment]
Hi @kennethsequeira , yes this is ok now. I have now new error
 internalerror-1054-u-unknown-column-appointment-in-field-list

**Comment by kennethsequeira** [comment]
@vladucoju develop branch?

**Comment by vladucoju** [comment]
Installed Apps
ERPNext: v11.x.x-develop (9f97c97) (develop)

Frappe Framework: v11.x.x-develop (cccfa66) (develop)

**Comment by kennethsequeira** [comment]
@vladucoju 

Can you open a new thread with the latest traceback?

Will tag the new one with the develop tag. Just add the link here. Closing this topic for now.

**Comment by vladucoju** [comment]
We can close this issue. i opened new one #14923
