### ISSUE TITLE
Error When Printing Student Report Card

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#14680]
am unable to print Student Report Card.
This the error:ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ‘) and ar.student in (‘STUD00003’)\n\t\tORDER BY\n\t\t\tard.assessment_criteria’ at line 8")
Is it also possible to email it rather than printing it.
Thanks

**Comment by Fredoluka** [comment]
This I the full error message
Traceback (most recent call last):
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/api.py", line 53, in handle
    return frappe.handler.handle()
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/fredoluka2015/frappe-bench/apps/erpnext/erpnext/education/doctype/student_report_generation_tool/student_report_generation_tool.py", line 42, in preview_report_card
    doc.attendance = get_attendance_count(doc.students[0], doc.academic_year, doc.academic_term)
  File "/home/fredoluka2015/frappe-bench/apps/erpnext/erpnext/education/doctype/student_report_generation_tool/student_report_generation_tool.py", line 91, in get_attendance_count
    frappe.throw("Provide the academic year and set the starting and ending date.")
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/fredoluka2015/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Provide the academic

**Comment by manassolanki** [comment]
You haven't set the academic year and dates. Please check the following message.
`Provide the academic year and set the starting and ending date.`

You can create the GitHub issue (feature request) for emailing the Student Report Card.

**Comment by Fredoluka** [comment]
I have set the starting and ending date of the academic year,yet I am still get the error. Maybe there is something I am doing wrong.However I have created the email issue here:https://github.com/frappe/erpnext/issues/14691

**Comment by mihir-kandoi** [comment]
This issue has been automatically closed as it no longer appears to be valid. If you think this was closed in error, please mention me (@mihir-kandoi) in a comment here and I'll take another look.
