### ISSUE TITLE
Error on bench update - frappe.exceptions.DuplicateEntryError

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#14823]
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.87s.
Backing up sites...
Patching sites...
Migrating biz.tecobytes.com
Executing frappe.patches.v11_0.get_docs_apps_if_not_present in biz.tecobytes.com (4657b9a643a93473)
frappe_io required by frappe already present
foundation required by erpnext already present
Success: Done in 0.061s
Executing erpnext.patches.v11_0.move_item_defaults_to_child_table_for_multicompany #02-07-2018 in biz.tecobytes.com (4657b9a643a93473)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/opt/bench/erpnext/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/opt/bench/erpnext/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/opt/bench/erpnext/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/patches/v11_0/move_item_defaults_to_child_table_for_multicompany.py", line 64, in execute
    child_doc.db_insert()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 314, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
 : (u'Item Default', u'fbf73724bb', IntegrityError(1062, u"Duplicate entry 'fbf73724bb' for key 'PRIMARY'"))

**Comment by worldofsmarty** [comment]
Dear Team,

Kindly help me out in this issue as my whole company is stuck and are not able to move ahead. As it's stuck in between bench update. Kindly help us out.

![image](https://user-images.githubusercontent.com/5152491/42377406-d7d7d2ea-8140-11e8-8066-316b920e81f7.png)

![image](https://user-images.githubusercontent.com/5152491/42377509-2f07e316-8141-11e8-85ed-d122402ee052.png)

Regards,
Vijay Patel

**Comment by worldofsmarty** [comment]
Thank you @shreyashah115 For quick response. This issue is resolved so i am closing this issue.

[https://github.com/frappe/erpnext/pull/14834](url) #14834
