### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by Ganinakris** [frappe/erpnext#14845]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2018-06-22/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 341, in sync_erpnext_items
    sync_item_with_shopify(item, price_list, warehouse)
  File "/home/frappe/benches/bench-2018-06-22/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 428, in sync_item_with_shopify
    put_request("/admin/products/{}.json".format(item.get("shopify_product_id")), item_data)
  File "/home/frappe/benches/bench-2018-06-22/apps/erpnext_shopify/erpnext_shopify/shopify_requests.py", line 53, in put_request
    r = s.put(url, data=json.dumps(data), headers=get_header(settings))
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/requests/sessions.py", line 570, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 723, in urlopen
    retries.sleep(response)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/urllib3/util/retry.py", line 277, in sleep
    slept = self.sleep_for_retry(response)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/urllib3/util/retry.py", line 254, in sleep_for_retry
    retry_after = self.get_retry_after(response)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/urllib3/util/retry.py", line 251, in get_retry_after
    return self.parse_retry_after(retry_after)
  File "/home/frappe/benches/bench-2018-06-22/env/lib/python2.7/site-packages/urllib3/util/retry.py", line 234, in parse_retry_after
    raise InvalidHeader("Invalid Retry-After header: %s" % retry_after)
InvalidHeader: Invalid Retry-After header: 2.0
Request Data
{"shopify_variant_id": "4841827303465", "weight_uom": "G", "name": "PTOB03UN12", "shopify_description": "Tahitian South Sea Pearls Oval | Button CD Quality Unique Color 12 mm", "item_name": "Tahitian South Sea Pearls Oval | Button CD Unique 12 mm", "image": null, "item_group": "Tahitian South Sea Pearl", "item_code": "PTOB03UN12", "stock_uom": "Unit", "default_supplier": "Tahiti Pearl Market", "variant_of": null, "weight_per_unit": 0.0, "has_variants": 0, "shopify_product_id": "434224824361", "sync_qty_with_shopify": 1, "description": "Tahitian South Sea Pearls Oval | Button CD Quality Unique Color 12 mm"}

**Comment by kennethsequeira** [comment]
Can you provide the steps to reproduce this?
