### ISSUE TITLE
GST multiple tax rate error on beta.erpnext

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#15019]
![gstr1 error](https://user-images.githubusercontent.com/39449563/43271932-6eefe958-9116-11e8-9b21-d41725e2ad10.png)

Hello.
I have been trying to test erpnext and beta being on V.11 is a good test area. I started by creating two items, "goods @ 18%" and "goods @ 5%" for whom i set tax rate at respective cgst 2.5% and cgst 9%. I created a new purchase invoice where i added the goods but it did not correctly recognise tax slab in the items and for the invoice it selected 9% cgst and sgst. 
Also, submitting the invoice did not finish and it throwed the following error

"Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 830, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 311, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 901, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 318, in on_submit
    self.make_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 327, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 355, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 391, in make_item_gl_entries
    warehouse_account = get_warehouse_account_map()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/__init__.py", line 22, in get_warehouse_account_map
    d.account = get_warehouse_account(d, warehouse_account)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/__init__.py", line 36, in get_warehouse_account
    account = warehouse_account.get(warehouse.parent_warehouse).account
AttributeError: 'NoneType' object has no attribute 'account'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 830, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 311, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 901, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 318, in on_submit
    self.make_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 327, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 355, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 391, in make_item_gl_entries
    warehouse_account = get_warehouse_account_map()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/__init__.py", line 22, in get_warehouse_account_map
    d.account = get_warehouse_account(d, warehouse_account)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/__init__.py", line 36, in get_warehouse_account
    account = warehouse_account.get(warehouse.parent_warehouse).account
AttributeError: 'NoneType' object has no attribute 'account'"

**Comment by PawanMeh** [comment]
![1-screenshot](https://user-images.githubusercontent.com/20460498/47205880-de271280-d3a4-11e8-925d-541c5134a20f.png)

![2-screenshot](https://user-images.githubusercontent.com/20460498/47205889-e1ba9980-d3a4-11e8-9553-59513c91f7c2.png)

This works fine on latest v11 staging. If you still have an issue you can test and re-open
