### ISSUE TITLE
Installation failed due to pip version conflict- 

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/erpnext#15025]
**Just tried to install the ERPNext using bench get-app command and got this error**

**Pip version conflicts:**

```
~/frappe-bench$ bench get-app frappe https://github.com/frappe/erpnext --branch master
INFO:bench.app:getting app erpnext
INFO:bench.utils:git clone https://github.com/frappe/erpnext --branch master --depth 1 --origin upstream
Cloning into 'erpnext'...
remote: Counting objects: 6388, done.
remote: Compressing objects: 100% (5686/5686), done.
remote: Total 6388 (delta 1185), reused 3349 (delta 538), pack-reused 0
Receiving objects: 100% (6388/6388), 178.73 MiB | 49.90 MiB/s, done.
Resolving deltas: 100% (1185/1185), done.
Checking connectivity... done.
Checking out files: 100% (6341/6341), done.
('installing', u'erpnext')
INFO:bench.app:installing erpnext
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext --no-cache-dir
INFO:bench.app:getting app foundation
INFO:bench.utils:git clone https://github.com/erpnext/foundation --branch master --depth 1 --origin upstream
Cloning into 'foundation'...
remote: Counting objects: 2912, done.
remote: Compressing objects: 100% (2798/2798), done.
remote: Total 2912 (delta 117), reused 2023 (delta 60), pack-reused 0
Receiving objects: 100% (2912/2912), 248.95 MiB | 19.23 MiB/s, done.
Resolving deltas: 100% (117/117), done.
Checking connectivity... done.
Checking out files: 100% (3809/3809), done.
('installing', u'foundation')
INFO:bench.app:installing foundation
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/foundation --no-cache-dir
Command "python setup.py egg_info" failed with error code 1 in /home/user/frappe-bench/apps/foundation/
Traceback (most recent call last):
  File "/home/user/frappe-bench/env/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/commands/make.py", line 40, in get_app
    get_app(git_url, branch=branch)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/app.py", line 145, in get_app
    branch= 'master', postprocess = False)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/app.py", line 135, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/app.py", line 179, in install_app
    find_links=find_links))
  File "/home/user/frappe-bench/env/local/lib/python2.7/site-packages/bench/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q  -e ./apps/foundation --no-cache-dir

```

**Comment by mihir-kandoi** [comment]
This issue has been automatically closed as it no longer appears to be valid. If you think this was closed in error, please mention me (@mihir-kandoi) in a comment here and I'll take another look.
