### ISSUE TITLE
Error when migrating from master to staging

### ISSUE THREAD

**Issue by jodeq** [frappe/erpnext#15039]
I have this error when running a switch to master : 

>Executing erpnext.patches.v11_0.make_asset_finance_book_against_old_entries in xxxxxxxx (xxxxxxx)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/bench-ikkoe/apps/erpnext/erpnext/patches/v11_0/make_asset_finance_book_against_old_entries.py", line 18, in execute
    set ast.location = wh.warehouse_name where ast.warehouse = wh.name""")
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, u"Unknown column 'ast.location' in 'field list'")
`

A workaround is given in the forum [here](https://discuss.erpnext.com/t/unknown-column-ast-location-in-field-list/38736)

It would be great if this patch could be corrected.

Best regards

**Comment by jodeq** [comment]
in file  erpnext/erpnext/patches/v11_0/make_asset_finance_book_against_old_entries.py
I have added a True to force reload_doc and this patch is working right.

>  frappe.reload_doc('assets', 'doctype', 'asset_finance_book', True)
...

Regards.

**Comment by jodeq** [comment]
Thanks @Zlash65 your fix correct this issue.
So it was just updated_date doctype.

Best Regards.
