### ISSUE TITLE
TypeError: make_shopify_log() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#15037]
Hi @all 
I have a fresh erpnext installation on Ubuntu 18.xx
now in Shopify Setting when I click Save, it pops up the following error
```
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 20, in validate
    self.register_webhooks()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 62, in register_webhooks
    message=e.message, exception=False)
TypeError: make_shopify_log() got an unexpected keyword argument 'method'

Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 957, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 294, in _save
    self.run_before_save_methods()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1040, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1023, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 20, in validate
    self.register_webhooks()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 62, in register_webhooks
    message=e.message, exception=False)
TypeError: make_shopify_log() got an unexpected keyword argument 'method'
```
 please help someone

**Comment by ziagithub2018** [comment]
The error is solved now after new pull,    but now we do not have manual sync and also log to check the status of sync with shopify.
I'm not sure about auto sync as well, is it working or not.
