### ISSUE TITLE
Migration from master to staging

### ISSUE THREAD

**Issue by jodeq** [frappe/erpnext#15040]
I have an issue when migrating from master to staging branch

> Executing erpnext.patches.v11_0.update_department_lft_rgt in xxxxxxxxxxxxxxxxx(xxxxx)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/migrate.py", line 39, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/bench-ikkoe/apps/erpnext/erpnext/patches/v11_0/update_department_lft_rgt.py", line 16, in execute
    where is_group = 0""".format(_('All Departments')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)

It seems this could be with the letter `é` that I have in my french setup.

I have not found workaround today.

Regards

**Comment by Zlash65** [comment]
Can you post the output of `frappe.db.get_all("Department")` from bench console

**Comment by jodeq** [comment]
> [{u'name': u'Ventes - DA'},
 {u'name': u'Ventes'},
 {u'name': u'Service Client - DA'},
 {u'name': u'Service Client'},
 {u'name': u'Ressources Humaines - DA'},
 {u'name': u'Ressources Humaines'},
 {u'name': u'Recherche & D\xe9veloppement - DA'},
 {u'name': u'Recherche & D\xe9veloppement'},
 {u'name': u'Production - DA'},
 {u'name': u'Production'},
 {u'name': u'Op\xe9rations - DA'},
 {u'name': u'Op\xe9rations'},
 {u'name': u'Marketing - DA'},
 {u'name': u'Marketing'},
 {u'name': u'Juridique - DA'},
 {u'name': u'Juridique'},
 {u'name': u'Gestion de la Qualit\xe9 - DA'},
 {u'name': u'Gestion de la Qualit\xe9'},
 {u'name': u'Gestion - DA'},
 {u'name': u'Gestion'},
 {u'name': u'Envoi - DA'},
 {u'name': u'Envoi'},
 {u'name': u'Comptes - DA'},
 {u'name': u'Comptes'},
 {u'name': u'Achat - DA'},
 {u'name': u'Achat'},
 {u'name': u'All Departments'}]

**Comment by jodeq** [comment]
`\xe9` replace the character `é`
Could it be a python configuration ?

**Comment by jodeq** [comment]
In last develop this script is always in error.
We cannot upgrade V10 to develop with french language.

**Comment by jodeq** [comment]
Update seems OK now.
I don't know what was done but thank you :smile:
