### ISSUE TITLE
Migration from master to staging last step

### ISSUE THREAD

**Issue by jodeq** [frappe/erpnext#15059]
When running a bench update --patch here the last step

>Executing erpnext.patches.v11_0.add_item_group_defaults in xxxxxxxxx(xxxxx)
Success: Done in 0.709s
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Updating DocTypes for dashboard     : [========================================]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.get_doc('Portal Settings', 'Portal Settings').sync_menu()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/website/doctype/portal_settings/portal_settings.py", line 37, in sync_menu
    self.save()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 293, in _save
    self._validate_links()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 734, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 338, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 324, in msgprint
    _raise_exception()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 297, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: <exception str() failed>

**Comment by jodeq** [comment]
after running again

> bench update --patch
Backing up sites...
Patching sites...
Migrating xxxxxxxxxxxxx
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Updating DocTypes for dashboard     : [========================================]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.get_doc('Portal Settings', 'Portal Settings').sync_menu()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/website/doctype/portal_settings/portal_settings.py", line 37, in sync_menu
    self.save()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 293, in _save
    self._validate_links()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/model/document.py", line 734, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 338, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 324, in msgprint
    _raise_exception()
  File "/home/frappe/bench-ikkoe/apps/frappe/frappe/__init__.py", line 297, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Default Role at Time of Signup: Guardian

**Comment by jodeq** [comment]
Update is OK now, thanks :smile:
