### ISSUE TITLE
While upgrading our erpnext systems running ERPNext: v10.1.45 we get following error AttributeError: 'Lead' object has no attribute '_abbr'

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#15110]
Problem: While upgrading 

ERPNext: v10.1.45

Frappe Framework: v10.1.44

We get the following error(s)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/migrate.py", line 43, in migrate
    sync_fixtures()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 24, in sync_fixtures
    ignore_links=True, overwrite=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 54, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process, reset_permissions=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 132, in import_doc
    doc.insert()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in composer
    return composed(self, method, *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 53, in validate
    check_if_fieldname_conflicts_with_methods(self.dt, self.fieldname)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 870, in check_if_fieldname_conflicts_with_methods
    method_list = [method for method in dir(doc) if isinstance(method, str) and callable(getattr(doc, method))]
  File "/usr/home/latte/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 611, in company_abbr
    return self._abbr
AttributeError: 'Lead' object has no attribute '_abbr'

**Comment by jasonbrowne** [comment]
File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/migrate.py", line 43, in migrate
    sync_fixtures()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 24, in sync_fixtures
    ignore_links=True, overwrite=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 54, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process, reset_permissions=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 132, in import_doc
    doc.insert()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_before_save_methods
    self.run_method("validate")
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in composer
    return composed(self, method, *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 53, in validate
    check_if_fieldname_conflicts_with_methods(self.dt, self.fieldname)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 870, in check_if_fieldname_conflicts_with_methods
    method_list = [method for method in dir(doc) if isinstance(method, str) and callable(getattr(doc, method))]
  File "/usr/home/latte/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 611, in company_abbr
    return self._abbr
AttributeError: 'Lead' object has no attribute '_abbr'
[latte@erp10-jb ~/frappe-bench]$

**Comment by Mitchy25** [comment]
Im getting the same error while installing a new copy of ERPNext.

**Comment by jasonbrowne** [comment]
@Mitchy25 give it a try now Team ERPNext pushed a fix and now I can upgrade my systems.

**Comment by Mitchy25** [comment]
Thanks Jason! I’ll try it now and tell you how I go!




On Fri, Aug 10, 2018 at 4:31 AM +1200, "jasonbrowne" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Mitchy25<https://github.com/Mitchy25> give it a try now Team ERPNext pushed a fix and now I can upgrade my systems.
