### ISSUE TITLE
Permission Error while attaching files

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#15167]
Installed Apps

ERPNext: v11.x.x-develop (5f33b69) (develop)

Frappe Framework: v11.x.x-develop (445e2bd) (develop)

Web Notes App: v0.0.1 (master)

-------------------------------------------------------------

Steps to replicate issue:

Open company doctype and drag and drop a file.

Below error message is thrown.

![error_msg](https://user-images.githubusercontent.com/11595602/44320971-e4f7de80-a462-11e8-8b09-eb69e5c2302e.png)

After clicking on 'Close' button, the file uploads successfully.

Below error is shown in JS console.
```
Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
request.js:318 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 73, in get_value
    frappe.throw(_("No permission for {0}".format(doctype)), frappe.PermissionError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 325, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 298, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: No permission for System Settings
```

**Comment by tarokobear** [comment]
This also happens for me for my custom app running on frappe. I noticed that not always results in this error for all circumstances. For me the error only occurs when attaching files with ".dwg" file suffix and when I'm logged in as a non Administrator user.

You can download a test dwg file here: 
https://knowledge.autodesk.com/support/autocad-mechanical/downloads/caas/downloads/content/autocad-mechanical-2018-sample-files.html

Hope this helps you replicate the issue.

**Comment by surajshetty3416** [comment]
@asbasawaraj this has been fixed [here](https://github.com/frappe/frappe/pull/6738)
