### ISSUE TITLE
errors after upgrade 

### ISSUE THREAD

**Issue by hifyaan** [frappe/erpnext#15243]
hi i did an update last night and getting this error
and everything was working before this

Backing up sites...
Patching sites...
Migrating erp.local
Executing frappe.patches.v11_0.rename_google_maps_doctype in erpshamz.local (2f079d0c2cfb7bd4)
Traceback (most recent call last):
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 484, in connect
sock = self._connect()
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 541, in _connect
raise err
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 529, in _connect
sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/client.py", line 667, in execute_command
connection.send_command(*args)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 610, in send_command
self.send_packed_command(self.pack_command(*args))
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 585, in send_packed_command
self.connect()
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 489, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:13000. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 484, in connect
sock = self._connect()
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 541, in _connect
raise err
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 529, in _connect
sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
"main", mod_spec)
File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/server/erp/erp-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in
main()
File "/home/server/erp/erp-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
click.Group(commands=commands)(prog_name='bench')
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/server/erp/erp-bench/apps/frappe/frappe/commands/init.py", line 25, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File "/home/server/erp/erp-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
migrate(context.verbose, rebuild_website=rebuild_website)
File "/home/server/erp/erp-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
frappe.modules.patch_handler.run_all()
File "/home/server/erp/erp-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
if not run_single(patchmodule = patch):
File "/home/server/erp/erp-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
return execute_patch(patchmodule, method, methodargs)
File "/home/server/erp/erp-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
frappe.get_attr(patchmodule.split()[0] + ".execute")()
File "/home/server/erp/erp-bench/apps/frappe/frappe/patches/v11_0/rename_google_maps_doctype.py", line 6, in execute
rename_doc('DocType', 'Google Maps', 'Google Maps Settings')
File "/home/server/erp/erp-bench/apps/frappe/frappe/model/rename_doc.py", line 52, in rename_doc
update_user_settings(old, new, link_fields)
File "/home/server/erp/erp-bench/apps/frappe/frappe/model/rename_doc.py", line 95, in update_user_settings
sync_user_settings()
File "/home/server/erp/erp-bench/apps/frappe/frappe/model/utils/user_settings.py", line 49, in sync_user_settings
for key, data in iteritems(frappe.cache().hgetall('_user_settings')):
File "/home/server/erp/erp-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 153, in hgetall
iteritems(super(redis.Redis, self).hgetall(self.make_key(name)))}
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/client.py", line 1967, in hgetall
return self.execute_command('HGETALL', name)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/client.py", line 673, in execute_command
connection.send_command(*args)
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 610, in send_command
self.send_packed_command(self.pack_command(*args))
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 585, in send_packed_command
self.connect()
File "/home/server/erp/erp-bench/env/lib/python3.4/site-packages/redis/connection.py", line 489, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:13000. Connection refused.

**Comment by rmehta** [comment]
Seems your Redis was killed during an update. Can you try running this again. I don't think this is repeatable in the standard install.
