### ISSUE TITLE
erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings.schedule_get_order_details

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#15336]
{'event': u'hourly', 'retry': 0, 'log': <function log at 0x7f7b818f8d70>, 'site': u'erp.ibtechpa.com', 'job_name': u'erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings.schedule_get_order_details', 'method_name': u'erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings.schedule_get_order_details', 'method': <function schedule_get_order_details at 0x7f7b818b5b18>, 'user': u'Administrator', 'kwargs': {}, 'is_async': True}
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/background_jobs.py", line 103, in execute_job
    method(**kwargs)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/erpnext_integrations/doctype/amazon_mws_settings/amazon_mws_settings.py", line 29, in schedule_get_order_details
    after_date = dateutil.parser.parse(mws_settings.after_date).strftime("%Y-%m-%d")
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 645, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 721, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not NoneType

**Comment by PawanMeh** [comment]
We are not able to replicate this issue, the order synch is working fine via schedular. You can share screen shot of your "Amazon Settings" in case you need any more help.

**Comment by lbazan** [comment]
Default the schedule is enable and when try disable give error.

![amazon](https://user-images.githubusercontent.com/3780147/45230186-b9139000-b28d-11e8-8826-60cdb4669fd7.png)

**Comment by lbazan** [comment]
fixed.

Thanks!
