### ISSUE TITLE
Error saving customer group

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#15421]
Hello,

When I try to save any modification on customer group I get this error on console:

"Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 291, in _save
    self.validate_higher_perm_levels()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 546, in validate_higher_perm_levels
    self.reset_values_if_no_permlevel_access(has_access_to, high_permlevel_fields)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 747, in reset_values_if_no_permlevel_access
    self.parent_doc.get_latest()
AttributeError: 'CustomerGroup' object has no attribute 'parent_doc'"

This was tested on:
ERPNext: v10.1.52 (master)
Frappe Framework: v10.1.47 (master)

**Comment by crescent28** [comment]
Hello, 

I tried to create the Customer Group for the following version and it works fine. 

**ERPNext: v10.1.68 (master)

Frappe Framework: v10.1.59 (master)**

You can try updating your account to this version and try again.

**Comment by navdeepghai1** [comment]
@crescent28  @PawanMeh 
Branch: V10.x.x(Update to date with remote)
If have also faced the same issue.

I don't know why throwing this error:
```
Traceback (most recent call last):
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 291, in _save
    self.validate_higher_perm_levels()
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 545, in validate_higher_perm_levels
    self.reset_values_if_no_permlevel_access(has_access_to, high_permlevel_fields)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/base_document.py", line 746, in reset_values_if_no_permlevel_access
    self.parent_doc.get_latest()
AttributeError: 'CustomerGroup' object has no attribute 'parent_doc'

Traceback (most recent call last):
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 291, in _save
    self.validate_higher_perm_levels()
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/document.py", line 545, in validate_higher_perm_levels
    self.reset_values_if_no_permlevel_access(has_access_to, high_permlevel_fields)
  File "/home/navdeep/navdeep/master/apps/frappe/frappe/model/base_document.py", line 746, in reset_values_if_no_permlevel_access
    self.parent_doc.get_latest()
AttributeError: 'CustomerGroup' object has no attribute 'parent_doc'
```
May be it's because of user has reset the permissions or parent group value being assigned to parent field of customer group form.
It's only happening in tree view, so I also trace back this issue to find the root cause.
It's not giving error for the customer group whose parent field value isn't set.

```
Customer group parent field value list:
MariaDB [18a8dc29a751b661]> select parent from `tabCustomer Group`;
+---------------------------+
| parent                    |
+---------------------------+
| NULL                      |
| NULL                      |
| NULL                      |
| NULL                      |
| NULL                      |
| NULL                      |
|                           |
| All Customer Groups   
```
As far as I know parent and parenttype model values are only set when  doctype is child table.
