### ISSUE TITLE
Error when Subscription is created in Version 11

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#15460]
When a Subscription is created and submitted in Version 11, the following error message comes up

Traceback (most recent call last):
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 216, in insert
    self.set_new_name()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 378, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 42, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 71, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 81, in set_name_by_naming_series
    if not doc.naming_series:
AttributeError: 'Subscription' object has no attribute 'naming_series'

Traceback (most recent call last):
  File "/home/ubuntu/xlevel/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/_init_.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 216, in insert
    self.set_new_name()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 378, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 42, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 71, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/naming.py", line 81, in set_name_by_naming_series
    if not doc.naming_series:
AttributeError: 'Subscription' object has no attribute 'naming_series'

This is on Version 11 on a database that was backed up and recovered from version 10

Olamide

**Comment by rohitwaghchaure** [comment]
Hi @olamide2 

Do you have naming series for the subscription? Can you goto property setter and select the doctype as Subscription in the filter and share the output

**Comment by olamide2** [comment]
I do not have subscription in the naming series. The following is the output as requested 

Traceback (most recent call last):
  File "/home/ubuntu/xlevel/apps/frappe/frappe/app.py", line 55, in application
    try:
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 20, in handle
    if cmd!='login':
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 55, in execute_cmd
  File "/home/ubuntu/xlevel/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/search.py", line 53, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_length=page_length, filters=filters, ignore_user_permissions=ignore_user_permissions)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/search.py", line 149, in search_widget
    as_list=not as_dict)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/__init__.py", line 1235, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/db_query.py", line 112, in build_and_run
  File "/home/ubuntu/xlevel/apps/frappe/frappe/database/database.py", line 165, in sql
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/xlevel/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tab'DocType'.name' in 'field list'")

**Comment by JHeijting** [comment]
I have exact the same problem. I am unable to select 'Subscription' in the naming series. Als when I edit the 'autoname' in the doctype 'Subscription' to for instance "SUB-#####", than I still get this error: AttributeError: 'Subscription' object has no attribute 'naming_series'
