### ISSUE TITLE
Error when trying to create PDF

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#15681]
Hi ,

we’re encountering the following error when trying to create PDF of documents

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 53, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/print_format.py", line 48, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 14, in get_pdf
    html, options = prepare_options(html, options)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 71, in prepare_options
    html, html_options = read_options_from_html(html)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 86, in read_options_from_html
    soup = BeautifulSoup(html, "html5lib")
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
```
This happens on a fresh Ubuntu 16.04 install using the easy install script. Another user has complained about the same issue using the same setup https://discuss.erpnext.com/t/error-when-trying-to-create-pdf/41747

We need a resolution urgently please

Kind regards,

**Comment by AliMjawad** [comment]
same error here ..

**Comment by Olawale1** [comment]
Hi @AliMjawad 

Please see the forum thread referenced above for how I got around the issue. Hopefully there will be a proper fix deployed soon

Cheers
