### ISSUE TITLE
My test result:Remove hard coded status

### ISSUE THREAD

**Issue by mhbu50** [frappe/erpnext#15840]
1. Customize form
2. Add "Sick" to the **Status** field
3. Create new Attendance with the "Sick" status
4. Open Monthly Attendance Sheet Report
5. Error pop up:

```
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 489, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 174, in run
    result = generate_report_result(report, filters, user)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 65, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/opt/bench/erpnext/apps/erpnext/erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py", line 45, in execute
    row.append(status_map[status])
KeyError: u'Sick'
```

How to manage custom status without touching the code?

Thanks.

_Originally posted by @amardianto in https://github.com/frappe/erpnext/pull/15769#issuecomment-433329929_

**Comment by jigneshpshah** [comment]
The best way to handle is to add attendance record as status as = Leave and Leave Type = Sick Leave via  Approved Leave Application.

The Sick Leave needs to be applied through Leave Application and Submit it as approved, which will automatically create an attendance record.
