### ISSUE TITLE
QuickBooks Migrator messing up with a lot of stuff

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#15856]
## While renaming company
```
Traceback (most recent call last):
  File "/home/frappe/prod/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/prod/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/prod/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/prod/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/prod/apps/frappe/frappe/model/rename_doc.py", line 47, in rename_doc
    update_link_field_values(link_fields, old, new, doctype)
  File "/home/frappe/prod/apps/frappe/frappe/model/rename_doc.py", line 205, in update_link_field_values
    single_doc.save(ignore_permissions=True)
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 905, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/prod/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/prod/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 49, in on_update
    self.default_warehouse = frappe.get_all('Warehouse', filters={"company": self.company, "is_group": 0})[0]["name"]
IndexError: list index out of range
```

## While bench rebuild-global-search
```
Rebuilding Global Search            : [====                                    ]Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/prod/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/prod/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/commands/utils.py", line 622, in rebuild_global_search
    rebuild_for_doctype(doctype)
  File "/home/frappe/prod/apps/frappe/frappe/utils/global_search.py", line 106, in rebuild_for_doctype
    all_records = frappe.get_all(doctype, fields=fieldnames, filters=_get_filters())
  File "/home/frappe/prod/apps/frappe/frappe/__init__.py", line 1262, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/__init__.py", line 1235, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/prod/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/home/frappe/prod/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
    args = self.prepare_args()
  File "/home/frappe/prod/apps/frappe/frappe/model/db_query.py", line 117, in prepare_args
    self.set_optional_columns()
  File "/home/frappe/prod/apps/frappe/frappe/model/db_query.py", line 256, in set_optional_columns
    columns = frappe.db.get_table_columns(self.doctype)
  File "/home/frappe/prod/apps/frappe/frappe/database.py", line 903, in get_table_columns
    return self.get_db_table_columns('tab' + doctype)
  File "/home/frappe/prod/apps/frappe/frappe/database.py", line 899, in get_db_table_columns
    return [r[0] for r in self.sql("DESC `%s`" % table)]
  File "/home/frappe/prod/apps/frappe/frappe/database.py", line 210, in sql
    self._cursor.execute(query)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/prod/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, u"Table 'tar.tabQuickBooks Migrator' doesn't exist")
```

**Comment by aakvatech** [comment]
Any workarounds available apart from remarking the code?

**Comment by SaiFi0102** [comment]
I used bench console and copied and modified the rename company function or whatever function that was failing to exclude Quickbooks migrator DocType

**Comment by barredterra** [comment]
### While renaming account

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 231, in update_account_number
    frappe.rename_doc("Account", name, new_name, ignore_permissions=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 794, in rename_doc
    return rename_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 47, in rename_doc
    update_link_field_values(link_fields, old, new, doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 199, in update_link_field_values
    single_doc = frappe.get_doc(field['parent'])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 724, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 34, in __init__
    super(QuickBooksMigrator, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 104, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 130, in load_from_db
    single_doc = frappe.new_doc(self.doctype).as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 658, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 21, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 39, in make_new_doc
    "docstatus": 0
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 724, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 39, in __init__
    scope=self.scope
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 69, in __init__
    self.token = token or {}
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 119, in token
    self._client.populate_token_attributes(value)
AttributeError: 'WebApplicationClient' object has no attribute 'populate_token_attributes'
```

### Versions

* ERPNext: v11.1.13 (master)
* Frappe Framework: v11.1.13 (master)

**Comment by gbm001** [comment]
https://github.com/frappe/erpnext/issues/16012#issuecomment-519003463
Missing tabQuickBooks Migrator table causes similar issue (with fix).

**Comment by adityahase** [comment]
Fixed with https://github.com/frappe/erpnext/pull/18626 and https://github.com/frappe/erpnext/pull/18273
