### ISSUE TITLE
'Database' object has no attribute 'has_index' while installation of ERPNext

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/erpnext#15924]
Similar Issue ref:
https://github.com/frappe/erpnext/issues/8433

```
Installing erpnext...
Updating DocTypes for erpnext       : [=========================               ]Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/commands/site.py", line 165, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/installer.py", line 145, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/modules/import_file.py", line 132, in import_doc
    doc.insert()
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 905, in run_post_save_methods
    self.run_method("on_update")
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 264, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/navdeep/navdeep/staging/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 331, in run_module_method
    getattr(module, method)()
  File "/home/navdeep/navdeep/staging/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 127, in on_doctype_update
    if not frappe.db.has_index('tabStock Ledger Entry', 'posting_sort_index'):
  File "/home/navdeep/navdeep/staging/env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Database' object has no attribute 'has_index'
```

Both apps  frappe and erpnext are on staging branch.

**Comment by rmehta** [comment]
Had the same issue it was because erpnext is on develop
