### ISSUE TITLE
Error in “Trial Balance” UnicodeEncodeError: ‘ascii’ codec can not encode character u ‘\ xf3’ in position 8: ordinal not in ** range (128) 

### ISSUE THREAD

**Issue by erickrojasfigueroa** [frappe/erpnext#15933]
When entering “Trial Balance” (http://erpnext.flex.com.pe/desk#query-report/Trial%20Balance), it shows the following error:

**

> This error appears in several reports.

**

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 489, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 174, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 65, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/trial_balance/trial_balance.py", line 15, in execute
    data = get_data(filters)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/trial_balance/trial_balance.py", line 71, in get_data
    filters.to_date, min_lft, max_rgt, filters, gl_entries_by_account, ignore_closing_entries=not flt(filters.with_period_closing_entry))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 345, in set_gl_entries_by_account
    .format("', '".join([frappe.db.escape(d) for d in accounts]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 8: ordinal not in range(128)
```

**Comment by joolsr** [comment]
If you have any non ASCII chars in your company name etc eg a tilde this will cause this error
