### ISSUE TITLE
Cannot close a task

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#15943]
**Version:**
ERPNext: v11.0.3-beta.19 () (develop)
Frappe Framework: v11.0.3-beta.22 () (develop)

**Steps to replicate the issue:**
1. Create a project with one or more tasks and set the status as 'Overdue'.
 
2. Open a task which is in 'Open' status and click on 'Close' button on the top toolbar.

Following error message is shown in a popup window.

Row # X: Status cannot be "Overdue". It should be one of "Open", "Working", "Pending Review", "Closed", "Cancelled", "Reviewed"

![screen shot 2018-11-09 at 10 18 29 am](https://user-images.githubusercontent.com/11595602/48243926-e1904580-e408-11e8-8612-fd0a91d1000d.png)

Below error message shown in js console.
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 20, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 312, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 915, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 774, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/task/task.py", line 70, in on_update
    self.update_project()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/task/task.py", line 98, in update_project
    frappe.get_doc("Project", self.project).update_project()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 183, in update_project
    self.save(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 298, in _save
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 463, in _validate
    d._validate_selects()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 519, in _validate_selects
    value, comma_options))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 325, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 298, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #4: Status cannot be "Overdue". It should be one of "Open", "Working", "Pending Review", "Closed", "Cancelled", "Reviewed"
```

**Comment by rohitwaghchaure** [comment]
@asbasawaraj Fixed using customize form, please check
