### ISSUE TITLE
Upgrade ValueError: year is out of range errors when performing bench update --reset

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#15979]
Installed Apps
ERPNext: v10.1.54

Frappe Framework: v10.1.49

Running info the following error after performing bench update --reset 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/commands/site.py", line 223, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/migrate.py", line 43, in migrate
    sync_fixtures()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 24, in sync_fixtures
    ignore_links=True, overwrite=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 54, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process, reset_permissions=True)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 65, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 110, in import_doc
    old_doc = frappe.get_doc(doc.doctype, doc.name)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/__init__.py", line 709, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc
    return controller(*args, **kwargs)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__
    self.load_from_db()
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/model/document.py", line 138, in load_from_db
    d = frappe.db.get_value(self.doctype, self.name, "*", as_dict=1)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/database/database.py", line 386, in get_value
    order_by, cache=cache)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/database/database.py", line 430, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/database/database.py", line 573, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/database/database.py", line 154, in sql
    self._cursor.execute(query, values)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1356, in read
    self._read_result_packet(first_packet)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1422, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1460, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1479, in _read_row_from_packet
    data = converter(data)
  File "/usr/home/latte/frappe-bench/apps/frappe/frappe/utils/data.py", line 63, in get_datetime
    return parser.parse(datetime_str)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/home/latte/frappe-bench/env/lib/python2.7/site-packages/dateutil/parser.py", line 581, in parse
    ret = default.replace(**repl)
ValueError: year is out of range

**Comment by ankush** [comment]
probably some weird value was inserted for year in datetime field that's causing this.
