### ISSUE TITLE
Error on Opening Stock Submission-Version-ERPNext: v11.0.3-beta.10 () (staging)  and Frappe Framework: v11.0.3-beta.30 () (staging)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16111]
![capture](https://user-images.githubusercontent.com/1822868/49067039-f146c100-f233-11e8-8a80-9c776c1a0f19.PNG)

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 264, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 34, in on_submit
    self.update_stock_ledger()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 188, in update_stock_ledger
    self.insert_entries(row)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 206, in insert_entries
    self.make_sl_entries([args])
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 269, in make_sl_entries
    make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 33, in make_sl_entries
    sle_id = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 58, in make_entry
    sle.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 36, in on_submit
    process_serial_no(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 191, in process_serial_no
    update_serial_nos(sle, item_det)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 335, in update_serial_nos
    if sle.is_cancelled == "No" and not sle.serial_no and sle.actual_qty > 0 \
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 264, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 34, in on_submit
    self.update_stock_ledger()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 188, in update_stock_ledger
    self.insert_entries(row)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 206, in insert_entries
    self.make_sl_entries([args])
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 269, in make_sl_entries
    make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 33, in make_sl_entries
    sle_id = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 58, in make_entry
    sle.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 36, in on_submit
    process_serial_no(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 191, in process_serial_no
    update_serial_nos(sle, item_det)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 335, in update_serial_nos
    if sle.is_cancelled == "No" and not sle.serial_no and sle.actual_qty > 0 \
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by Anurag810** [comment]
please, can add some screenshots

**Comment by Anurag810** [comment]
Please, Add some screenshots which will helps us to replicate the error .

**Comment by muchai** [comment]
![capture1](https://user-images.githubusercontent.com/1822868/49077447-59a19c80-f24c-11e8-8d01-0f525ab931bd.PNG)
![capture2](https://user-images.githubusercontent.com/1822868/49077450-5b6b6000-f24c-11e8-908d-8ed9059a13cb.PNG)
![capture3](https://user-images.githubusercontent.com/1822868/49077453-5dcdba00-f24c-11e8-837c-1431a25ada3a.PNG)
![capture4](https://user-images.githubusercontent.com/1822868/49077456-5f977d80-f24c-11e8-8106-69c2b21e1001.PNG)

Thank you.

Here they're.
Then followed by the log above.
Initially I thought, it's due to special characters, e.g. " in item name, but even testing with a single item, still leads to same error.

**Comment by muchai** [comment]
![capture1](https://user-images.githubusercontent.com/1822868/49077892-902be700-f24d-11e8-84f3-c401f9f41a4c.PNG)
![capture2](https://user-images.githubusercontent.com/1822868/49077896-9621c800-f24d-11e8-92e9-40da43eedb72.PNG)
![capture3](https://user-images.githubusercontent.com/1822868/49077902-98842200-f24d-11e8-84cf-2a074c1d374e.PNG)
![capture4](https://user-images.githubusercontent.com/1822868/49077912-9f129980-f24d-11e8-883f-d02dcc980082.PNG)

Thank you.

Here they're, in order.
Then followed by the log above.
Initially I thought, it's due to special characters, e.g. " in item code, but even testing with a single item, with no special characters, still leads to the same error.

**Comment by muchai** [comment]
![capture1](https://user-images.githubusercontent.com/1822868/49078095-24964980-f24e-11e8-9032-238e5f73063a.PNG)

![capture2](https://user-images.githubusercontent.com/1822868/49078103-27913a00-f24e-11e8-911d-c1e36c19230c.PNG)

![capture3](https://user-images.githubusercontent.com/1822868/49078106-2bbd5780-f24e-11e8-8aa3-4a0380021744.PNG)

![capture4](https://user-images.githubusercontent.com/1822868/49078114-2fe97500-f24e-11e8-8542-faa8b2507ee3.PNG)

Thank you.

Here they're, in order.
Then followed by the log above.
Initially I thought, it's due to special characters, e.g. " in item code, but even testing with a single item, with no special characters, still leads to the same error.

**Comment by jaqobk** [comment]
hope we shall get a solution to this since am also facing the same error and cant update the stock at this time when we are doing year closing stock taking.
am using

**Installed Apps
ERPNext: v11.0.3-beta.31 () (staging)

Frappe Framework: v11.0.3-beta.40 () (staging)**
