### ISSUE TITLE
[bug] Data import does not catch errors (logged in Error Log)

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#16166]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/core/doctype/data_import/importer.py", line 395, in upload
    doc.insert()
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 221, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 861, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 1009, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2018-11-15/apps/frappe/frappe/model/document.py", line 751, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2018-11-15/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 46, in validate
    self.validate_main_item()
  File "/home/frappe/benches/bench-2018-11-15/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 267, in validate_main_item
    self.description = ret[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lxnow** [comment]
Not sure if related to this exact same problem, but data import doesn't flag invalid values if a primary key field in a table isn't correctly specified. In one case, item account defaults were specified in the data import CSV but the Company field was not included. The import went through successfully but since no Company was specified, the default accounts (for Income and Expense in this case) were not updated. Yet, data import was successful.

**Comment by deepeshgarg007** [comment]
Closing this since we have a new and improved data import tool now from version-13 onwards
