### ISSUE TITLE
Error while searching

### ISSUE THREAD

**Issue by itskaps** [frappe/erpnext#16264]
whenever i search something and press enter below error pops up

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 32, in get_help
    return HelpDatabase().search(text)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 106, in search
    select title, intro, path from help where match(content) against (%s) limit 10''', ('%'+words+'%', words))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (1146, u"Table 'f6fa4199e92fd7a1.help' doesn't exist")

**Comment by itskaps** [comment]
Open Source Applications for the Web

	Website: https://frappe.io

	Source: https://github.com/frappe

Installed Apps
ERPNext: v10.1.75 (master)

Frappe Framework: v10.1.68 (master)

**Comment by clarkejj** [comment]
Right now v11 testing is the main focus I expect.  Have you checked for eg https://discuss.erpnext.com/t/table-help-doesnt-exist/32619   If your search there does not resolve your problem, best to post your request for help to discuss.erpnext.com?

**Comment by itskaps** [comment]
Thank You
