### ISSUE TITLE
[Bug-V11] Cannot fetch items from warehouse on stock reconciliation

### ISSUE THREAD

**Issue by deepeshgarg007** [frappe/erpnext#16278]
![stock reconciliation](https://user-images.githubusercontent.com/42651287/50422696-62e54f80-0872-11e9-9804-64ad1cbcfda7.gif)

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
TypeError: get_items() missing 1 required positional argument: 'warehouse'
```

**Comment by muchai** [comment]
This error, could be related with: https://github.com/frappe/erpnext/issues/16111

**Comment by jaqobk** [comment]
facing exactly same error
