### ISSUE TITLE
V11 Child table from Clipboard Excel error, can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by ovresko** [frappe/erpnext#16284]
While testing clipboard past from excel, i can't add numerical values (like qty)

item_code      qty
TEST            10

```
Traceback (most recent call last):
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 45, in get_item_details
    out = get_basic_details(args, item)
  File "/home/frappe/erpnext-10.1.73-0/apps/erpnext/htdocs/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 287, in get_basic_details
    out.stock_qty = out.qty * out.conversion_factor
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by szufisher** [comment]
pull request https://github.com/frappe/erpnext/pull/16285 submitted
