### ISSUE TITLE
Getting NameError: global name '_' is not defined whiling saving amazon S3 backup setting

### ISSUE THREAD

**Issue by anindya2003** [frappe/erpnext#16298]
We are trying to configure amazon_S3_backup settings to take periodic backup of ERPNext instance. We have followed the below steps to install amazon_s3_backup...

    Install boto and filechunkio packages
    a) source ./frappe-bench/env/bin/activate
    b) pip install boto
    c) pip install filechunkio

    bench get-app s3_backup https://github.com/ccfiel/s3_backup.git

    bench --site install-app s3_backup

After installation new link available under Setup > Integrations > Amazon S3 Backup
But while trying the save the configuration settings its giving the below error....can someone please advise or suggest a solution to this issue...really appreciate an early response.

Traceback (most recent call last):
File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
doc.save()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
return self.save(*args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 293, in save
self.run_before_save_methods()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 861, in run_before_save_methods
self.run_method("validate")
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 757, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1026, in composer
return composed(self, method, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1009, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 751, in
fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
File "/home/frappe/frappe-bench/apps/s3_backup/s3_backup/amazon_s3_backup/doctype/amazon_s3_settings/amazon_s3_settings.py", line 29, in validate
frappe.throw(("Unable to create bucket {0}. Change it to a more unique ").format(bucket_lower))
NameError: global name '_' is not defined

Traceback (most recent call last):
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
response = frappe.handler.handle()
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
data = execute_cmd(cmd)
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 939, in call
return fn(*args, **newargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
doc.save()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
return self.save(*args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 293, in save
self.run_before_save_methods()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 861, in run_before_save_methods
self.run_method("validate")
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 757, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1026, in composer
return composed(self, method, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1009, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 751, in
fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
File "/home/frappe/frappe-bench/apps/s3_backup/s3_backup/amazon_s3_backup/doctype/amazon_s3_settings/amazon_s3_settings.py", line 29, in validate
frappe.throw(("Unable to create bucket {0}. Change it to a more unique ").format(bucket_lower))
NameError: global name '_' is not defined

**Comment by clarkejj** [comment]
Some suggestions:
- post this and search discuss.erpnext.com forum for more support traffic and all to benefit
- include your erpnext and frappe versions
- inform and seek Bai Labs support https://github.com/bailabs/s3_backup

**Comment by joolsr** [comment]
S3 integration is available in V10 in the core without using any third party apps.

I use S3 to backup in V11 without issues

**Comment by 4m3ndy** [comment]
@anindya2003 The `s3_backup` app is configured to create the bucket with IAM User who has a `Full S3 Admin Access`, so you get this error because there's an existing bucket with the same name you supported for `Bucket Name` in `Amazon S3 Backups` Form, Try to add a unique prefix to the bucket name or choose a unique one.

**Comment by kennethsequeira** [comment]
Closing this issue since the app in question causing the error is not maintained by the core team. Also, since the backup functionality is in-app, the same should be followed.
