### ISSUE TITLE
Error on clicking on Supplier Quotation, on the suplier portal -> ver11

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16294]
![image](https://user-images.githubusercontent.com/1822868/50472285-2aa45500-09c9-11e9-90c1-6e6203672b14.png)

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 139, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 155, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 162, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in build_page
    html = frappe.render_template(context.source, context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 75, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 6, in top-level template code
    {%- if page_or_generator=="Generator" %}source-type="Generator" data-doctype="{{ doctype }}"{% endif %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 37, in top-level template code
    {% block body %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 63, in block "body"
    {% block content %}{% endblock %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 49, in block "content"
    {%- block page_content -%}{%- endblock -%}
  File "<template>", line 24, in block "page_content"
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 58, in _
    if is_html(msg):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/data.py", line 571, in is_html
    return re.search('<[^>]+>', text)
  File "/home/frappe/frappe-bench/env/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by muchai** [comment]
The certifications link too, on the portal, is not pointing to any document

**Comment by muchai** [comment]
The links were not working, or return the error attached.
The supplier quotation link is Ok now, the certifications, still throwing an error.
