### ISSUE TITLE
Error when running profit and loss report-ERPNext: v11.0.3-beta.32 () (staging)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16303]
This happens on setting the filters.
This has happened with the latest updates.

Same error on running the balance sheet.

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1013, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 495, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 179, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 66, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 16, in execute
    ignore_closing_entries=True, ignore_accumulated_values_for_fy= True)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 154, in get_data
    out = prepare_data(accounts, balance_must_be, period_list, company_currency)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 216, in prepare_data
    "parent_account": _(d.parent_account),
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 58, in _
    if is_html(msg):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/data.py", line 571, in is_html
    return re.search('<[^>]+>', text)
  File "/home/frappe/frappe-bench/env/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by scmmishra** [comment]
This is happening because your parent account is not set. You can change that in Chart of Accounts as a workaround for the while as we deploy a fix for it.

**Comment by chdecultot** [comment]
I experience the same issue
