### ISSUE TITLE
[v11.0.3-beta]bench update fails

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/erpnext#16408]
> erpnext 11.0.3-beta.34
> frappe 11.0.3-beta.49
bench update fails with dashmanager app error

```
INFO:bench.app:installing erpnext
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext 
INFO:bench.app:installing dashmanager
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/dashmanager 
Command "python setup.py egg_info" failed with error code 1 in /home/ashish/frappe-bench-develop/apps/dashmanager/
Traceback (most recent call last):
  File "/home/ashish/.local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/ashish/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ashish/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, restart_systemd, requirements, no_backup, force=force, reset=reset)
  File "/home/ashish/bench-repo/bench/commands/update.py", line 76, in _update
    update_requirements(bench_path=bench_path)
  File "/home/ashish/bench-repo/bench/utils.py", line 434, in update_requirements
    install_app(app, bench_path=bench_path)
  File "/home/ashish/bench-repo/bench/app.py", line 179, in install_app
    find_links=find_links))
  File "/home/ashish/bench-repo/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q  -e ./apps/dashmanager 

```

**Comment by ashish-greycube** [comment]
The issue was resolved. Apps.txt had incorrect entry.
