### ISSUE TITLE
AttributeError: type object 'Document' has no attribute 'website'

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#16506]
Environment
ERPNext: v11.0.3-beta.37 () (staging)
Frappe Framework: v11.0.3-beta.51 () (staging)

Steps to reproduce 
1) Go To New Web Page
2) Save and Publish
3) See on Website

Below Error comes
```

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/render.py", line 142, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/render.py", line 158, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/render.py", line 165, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/render.py", line 178, in build_page
    context = get_context(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/router.py", line 36, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/router.py", line 22, in resolve_route
    return get_page_context_from_doctype(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/router.py", line 76, in get_page_context_from_doctype
    page_info = get_page_info_from_doctypes(path)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/website/router.py", line 100, in get_page_info_from_doctypes
    condition_field = meta.is_published_field or controller.website.condition_field
AttributeError: type object 'Document' has no attribute 'website'
```

**Comment by deepeshgarg007** [comment]
Working on latest v11
![image](https://user-images.githubusercontent.com/42651287/56786979-8caa8500-6818-11e9-9bd4-e05c8d0590d1.png)

**Comment by JPaulMora** [comment]
Hey I'm having the same issue on v13.13.0

**Comment by sudo-vaibhav** [comment]
Hi guys, its not a bug, its actually an omission and lack of clarity in the docs. Apart from the route field which is compulsory, you also need to create and mention a checkbox field, you can name it published.

This field will help filter out those documents which are not supposed to be shown in web view, and the error goes away when you supply this field.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/53619134/148695460-d90b4b4f-1bf5-44cb-939c-a620786dc777.png">

similarly you can mention this in docfield like so:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/53619134/148695486-f4674a7b-2d6f-42ab-a279-b17342d75e9b.png">
