### ISSUE TITLE
Having trouble with submitting a lot of documents. 

### ISSUE THREAD

**Issue by Ganinakris** [frappe/erpnext#16504]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 833, in submit
    self._submit()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 822, in _submit
    self.save()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 892, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1009, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 751, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 68, in on_submit
    self.update_stock_ledger()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 483, in update_stock_ledger
    self.make_sl_entries(sl_entries, self.amended_from and 'Yes' or 'No')
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/controllers/stock_controller.py", line 265, in make_sl_entries
    make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 38, in make_sl_entries
    update_bin(args, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/utils.py", line 144, in update_bin
    bin.update_stock(args, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 43, in update_stock
    }, allow_negative_stock=allow_negative_stock, via_landed_cost_voucher=via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 107, in __init__
    self.build()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 119, in build
    self.update_bin()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 145, in update_bin
    bin_doc.save(ignore_permissions=True)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 889, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1011, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 585, in trigger_update_item_stock
    update_item_stock(doc.item_code, shopify_settings, doc)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 630, in update_item_stock
    raise e
HTTPError: 422 Client Error: Unprocessable Entity for url: https://namaka-jewelry.myshopify.com/admin/variants/8120219074653.json

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 833, in submit
    self._submit()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 822, in _submit
    self.save()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 892, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1009, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 751, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 68, in on_submit
    self.update_stock_ledger()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 483, in update_stock_ledger
    self.make_sl_entries(sl_entries, self.amended_from and 'Yes' or 'No')
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/controllers/stock_controller.py", line 265, in make_sl_entries
    make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 38, in make_sl_entries
    update_bin(args, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/utils.py", line 144, in update_bin
    bin.update_stock(args, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 43, in update_stock
    }, allow_negative_stock=allow_negative_stock, via_landed_cost_voucher=via_landed_cost_voucher)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 107, in __init__
    self.build()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 119, in build
    self.update_bin()
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 145, in update_bin
    bin_doc.save(ignore_permissions=True)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 889, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1011, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 585, in trigger_update_item_stock
    update_item_stock(doc.item_code, shopify_settings, doc)
  File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 630, in update_item_stock
    raise e
HTTPError: 422 Client Error: Unprocessable Entity for url: https://namaka-jewelry.myshopify.com/admin/variants/8120219074653.json

**Comment by barredterra** [comment]
```
Traceback (most recent call last):
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/app.py", line 62, in application 
response = frappe.handler.handle()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/handler.py", line 22, in handle
data = execute_cmd(cmd)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/handler.py", line 53, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/**init**.py", line 939, in call
return fn(*args, **newargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
doc.submit()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 833, in submit
self._submit()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 822, in _submit
self.save()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
return self._save(*args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
self.run_post_save_methods()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 892, in run_post_save_methods
self.run_method("on_submit")
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
return composed(self, method, *args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1009, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 751, in 
fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 68, in on_submit
self.update_stock_ledger()
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 483, in update_stock_ledger
self.make_sl_entries(sl_entries, self.amended_from and 'Yes' or 'No')
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/controllers/stock_controller.py", line 265, in make_sl_entries
make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 38, in make_sl_entries
update_bin(args, allow_negative_stock, via_landed_cost_voucher)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/utils.py", line 144, in update_bin
bin.update_stock(args, allow_negative_stock, via_landed_cost_voucher)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 43, in update_stock
}, allow_negative_stock=allow_negative_stock, via_landed_cost_voucher=via_landed_cost_voucher)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 107, in **init**
self.build()
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 119, in build
self.update_bin()
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext/erpnext/stock/stock_ledger.py", line 145, in update_bin
bin_doc.save(ignore_permissions=True)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 259, in save
return self._save(*args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 310, in _save
self.run_post_save_methods()
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 889, in run_post_save_methods
self.run_method("on_update")
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 757, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1026, in composer
return composed(self, method, *args, **kwargs)
File "/home/frappe/benches/bench-2019-01-23/apps/frappe/frappe/model/document.py", line 1011, in runner
add_to_return_value(self, f(self, method, *args, **kwargs))
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 585, in trigger_update_item_stock
update_item_stock(doc.item_code, shopify_settings, doc)
File "/home/frappe/benches/bench-2019-01-23/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 630, in update_item_stock
raise e
HTTPError: 422 Client Error: Unprocessable Entity for url: https://namaka-jewelry.myshopify.com/admin/variants/8120219074653.json
```

**Comment by ankush** [comment]
This feature doesn't exist anymore. Haven't noticed it again on the refactored app: https://github.com/frappe/ecommerce_integrations
