### ISSUE TITLE
Serial No save is failing when attempting to add data to new fields added via form customization

### ISSUE THREAD

**Issue by tabalchi** [frappe/erpnext#16698]
**Problem Description:**
Serial No save is failing when attempting to add data to new fields added via form customization.

**Sequence of events:**

- I created a new Custom DocType called "Item Single Descriptive Metadata"
- This new Custom Doctype has 2 fields - A name and a value
- I saved the new Custom Doctype (successful)
- I customized the "Serial No" form
  - I added a table called "metadata" with option "Item Single Descriptive Metadata"
  - I saved the modified form (successful)
- I opened a serial number
- I added a row to the new Metadata table that appears successfully
- I entered a name and a value in the pop-up - these are displayed successfully in List View on the form page
- I tried to save the serial number and it failed

**Application versions:**
- "erpnext": "10.1.76"
- "frappe": "10.1.69"

**Error message/traceback:**
> Traceback (most recent call last):
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
>     return self._save(*args, **kwargs)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 311, in _save
>     self.update_children()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in update_children
>     self.update_child_table(df.fieldname, df)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 346, in update_child_table
>     d.db_update()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 335, in db_update
>     self.db_insert()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 312, in db_insert
>     ), list(d.values()))
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 155, in sql
>     self._cursor.execute(query, values)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
>     result = self._query(query)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
>     conn.query(q)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
>     result.read()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
>     first_packet = self.connection._read_packet()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
>     packet.check_error()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
>     raise errorclass(errno, errval)
> ProgrammingError: (1146, u"Table 'b9b38ed869e63e1f.tabItem Single Descriptive Metadata' doesn't exist")
> 
> Traceback (most recent call last):
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 20, in handle
>     data = execute_cmd(cmd)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1013, in call
>     return fn(*args, **newargs)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
>     return self._save(*args, **kwargs)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 311, in _save
>     self.update_children()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in update_children
>     self.update_child_table(df.fieldname, df)
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 346, in update_child_table
>     d.db_update()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 335, in db_update
>     self.db_insert()
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 312, in db_insert
>     ), list(d.values()))
>   File "/home/erpnext/vendor/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 155, in sql
>     self._cursor.execute(query, values)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
>     result = self._query(query)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
>     conn.query(q)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
>     result.read()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
>     first_packet = self.connection._read_packet()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
>     packet.check_error()
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/home/erpnext/vendor/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
>     raise errorclass(errno, errval)
> ProgrammingError: (1146, u"Table 'b9b38ed869e63e1f.tabItem Single Descriptive Metadata' doesn't exist")

**Comment by tabalchi** [comment]
I also tried to create a new serial number instead of modifying an existing one as described previously, and got the same error.

**Comment by mihir-kandoi** [comment]
This appears to be a Frappe framework issue rather than ERPNext core, so I'm closing it here as part of issue triage. If it still happens on a current version, please open a new issue in the `frappe/frappe` repository. If you think this was closed in error, mention @mihir-kandoi here.
