### ISSUE TITLE
 Problem with invoicing in master version-V11

### ISSUE THREAD

**Issue by Meritsystems** [frappe/erpnext#16731]
When i was making invoice with Include Payment, Update Stock and stuff (POS Invoice) and so long as the Rounding Adjustment is a negative value.
On submitting of invoice, getting below error message. Anybody tell me how to solve this?

base_amount: could not find docfield in method precision()
number_format.js:194:11
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 166, in on_submit
    self.make_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 682, in make_gl_entries
    update_outstanding=update_outstanding, merge_entries=False)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 19, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 90, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 101, in make_entry
    gle.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 19, in validate
    self.check_mandatory()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 61, in check_mandatory
    .format(self.voucher_type, self.voucher_no, self.account))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 352, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 338, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 311, in _raise_exception
    raise raise_exception(msg)
ValidationError: Sales Invoice SPIN/18-19/072: Either debit or credit amount is required for Rounded Off - SPIN

**Comment by vrms** [comment]
> _On submitting of invoice, getting below error message. Anybody tell me how to solve this?_

this looks like a support request rather then an issue/bug report. Can you post this on the forum first please? If it turns out to be cause by a bug you can reopen this issue.

**Comment by melBoh** [comment]
Hi ! I don't know if it's correct procedure, but I do think it's a bug. It happens since v11 when in GLE debit_in_account_currency equals debit as it is neutralized in new code from erpnext/accounts/general_ledger.py function make_round_off_gle

see https://discuss.erpnext.com/t/sales-invoice-spin-18-19-059-either-debit-or-credit-amount-is-required-for-rounded-off-spin/45668/3

It seems some of us encounters this.

I think the round_off_gle.update should not happen if credit and debit are 0, but I'm no accounting expert and can be completly wrong .

**Comment by Rondeus** [comment]
I have the same issue. Numbers are correct. It should not fail as @melBoh says. 
I'm facing this when having price list in USD but Order and Invoice are in local currency. Exchange Rate precision is at maximum supported by ERPNext.

Please advice on how to solve this.
Thanks.

**Comment by jay-parikh** [comment]
@vrms Please reopen this issue. It's a bug and here is the pull request for the same.
https://github.com/frappe/erpnext/pull/17091
