### ISSUE TITLE
tree mode add new warehouse error, latest dev version

### ISSUE THREAD

**Issue by ollyboy** [frappe/erpnext#16744]
Something went wrong
Server Error: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/api.py", line 56, in handle
    return frappe.handler.handle()
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/handler.py", line 20, in handle
    data = execute_cmd(cmd)
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/inforactiv1/frappe-bench/apps/frappe/frappe/desk/treeview.py", line 20, in get_all_nodes
    data = tree_method(doctype, parent, **filters)
TypeError: get_children() got an unexpected keyword argument 'data'

**Comment by sharmanakul** [comment]
i'm closing the issue for now. I'd request to please provide the steps to reproduce the issue. Please reopen it is still persists for you.
