### ISSUE TITLE
Error when trying to submit sales invoive

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#16768]
### Installed Apps
ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)

### How to reproduce

Submit a new `Sales Invoice`.

### Error
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 20, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1021, in call
    if isinstance(fn, string_types):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 856, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 845, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 312, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 918, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1055, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1012, in get_attr
    if not local.flags.in_install and app_name not in get_installed_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 797, in get_module
    """Returns a module object for given Python module name using `importlib.import_module`."""
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/italy/utils.py", line 7, in <module>
    from frappe.utils.file_manager import save_file, remove_file
ImportError: No module named file_manager
```

https://github.com/frappe/erpnext/blob/3dd7ddd838d1f25d36c82f2c6228a37dcbf3cd98/erpnext/regional/italy/utils.py#L7

@gaurav-naik

**Comment by gaurav-naik** [comment]
Is the country in Global Defaults set to Italy? Any production environment
blocked on account of the error?

On 24-Feb-2019 11:06 PM, "Raffael Meyer" <notifications@github.com> wrote:

Installed Apps

ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)
How to reproduce

Submit a new Sales Invoice.
Error

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55,
in application
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line
20, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line
55, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py",
line 1021, in call
    if isinstance(fn, string_types):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py",
line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 856, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 845, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 312, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 918, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 780, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py",
line 1055, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py",
line 1012, in get_attr
    if not local.flags.in_install and app_name not in get_installed_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py",
line 797, in get_module
    """Returns a module object for given Python module name using
`importlib.import_module`."""
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/italy/utils.py",
line 7, in <module>
    from frappe.utils.file_manager import save_file, remove_file
ImportError: No module named file_manager

https://github.com/frappe/erpnext/blob/3dd7ddd838d1f25d36c82f2c6228a37dcbf3cd98/erpnext/regional/italy/utils.py#L7

@gaurav-naik <https://github.com/gaurav-naik>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/16768>, or mute the thread

**Comment by barredterra** [comment]
Country in `Global Defaults` is Germany. For me, it's just a test server.

![sinv_italy_bug](https://user-images.githubusercontent.com/14891507/53303164-7c514a80-3867-11e9-9d6f-44344e3fcc7e.png)

**Comment by hrwX** [comment]
#### This Issue seems to be fixed as file_manager import is not visible anymore
![Screenshot 2019-08-07 at 11 48 05 AM](https://user-images.githubusercontent.com/7310479/62599219-48477e80-b909-11e9-9c90-05ce8fe6b684.png)
