### ISSUE TITLE
v8 bench update error frappe.exceptions.DoesNotExistError: DocType User Social Login not found

### ISSUE THREAD

**Issue by xavierlawrence** [frappe/erpnext#16774]
Hello 
I've updated from version 8 to 11 and when trying to migrate the database, I'm getting the error above. You can find the full stack trace below.
`sudo bench --site erpnext.skywalkinnovations.co.za migrate`

`Migrating erpnext.skywalkinnovations.co.za
Executing frappe.patches.v8_0.drop_in_dialog #2017-09-22 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.06s
Executing frappe.patches.v11_0.drop_column_apply_user_permissions in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.47s
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2017-09-22 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.418s
Executing execute:frappe.reload_doc('core', 'doctype', 'docfield', force=True) #2018-02-20 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.833s
Executing execute:frappe.reload_doc('core', 'doctype', 'docperm') #2018-05-29 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.012s
Executing execute:frappe.reload_doc('core', 'doctype', 'comment') in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.153s
Executing execute:frappe.reload_doc('core', 'doctype', 'module_def') #2017-09-22 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.012s
Executing frappe.patches.v11_0.replicate_old_user_permissions in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 6.722s
Executing frappe.patches.v11_0.reload_and_rename_view_log #2019-01-03 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.094s
Executing frappe.patches.v11_0.copy_fetch_data_from_options in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 1.068s
Executing frappe.patches.v11_0.change_email_signature_fieldtype in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.452s
Executing execute:frappe.reload_doc('core', 'doctype', 'activity_log') in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.184s
Executing execute:frappe.reload_doc('core', 'doctype', 'domain_settings') in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.097s
Executing execute:frappe.reload_doc('core', 'doctype', 'user') #2017-10-27 in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.014s
Executing frappe.patches.v9_1.add_sms_sender_name_as_parameters in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Success: Done in 0.173s
Executing frappe.patches.v9_1.resave_domain_settings in erpnext.skywalkinnovations.co.za (_beef62f5df4948a6)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/site.py", line 228, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/migrate.py", line 38, in migrate
    frappe.modules.patch_handler.run_all()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/patches/v9_1/resave_domain_settings.py", line 11, in execute
    domain.setup_domain()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/core/doctype/domain/domain.py", line 18, in setup_domain
    self.setup_roles()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/core/doctype/domain/domain.py", line 76, in setup_roles
    user.save()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 293, in _save
    self.validate_higher_perm_levels()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 566, in validate_higher_perm_levels
    high_permlevel_fields = frappe.get_meta(df.options).meta.get_high_permlevel_fields()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 749, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__
    self.load_from_db()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/meta.py", line 89, in load_from_db
    super(Meta, self).load_from_db()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 140, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 353, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in msgprint
    _raise_exception()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType User Social Login not found
`

**Comment by xavierlawrence** [comment]
I've commented out `frappe.patches.v9_1.resave_domain_settings` in the frappe patches.txt file and that fixed the issue
