### ISSUE TITLE
'NoneType' object has no attribute 'always_use_account_email_id_as_sender'

### ISSUE THREAD

**Issue by codecakes** [frappe/erpnext#16793]
After going through initial setup of a development version (whole setup is in a virtualenv)
i get this after running and setting up using `bench start`

```
{'event': u'sendmail', 'retry': 0, 'log': , 'site': 'erpnext', 'job_name': u'', 'method_name': u'sendmail', 'method': , 'user': u'Administrator', 'kwargs': {'lang': u'en', 'attachments': [], 'recipients': [u'support@erpnext.com'], 'cc': [u'admin@example.com'], 'print_letterhead': 1, 'bcc': [], 'print_html': u'', 'session': {u'data': {u'session_expiry': u'06:00:00', u'session_country': None, 'csrf_token': '355bf28de05cc8733c9a0081ba701efe3338af4e8eae8d7d335437fa', u'last_updated': '2019-02-27 02:28:41.186402', u'lang': u'en', u'user_type': u'System User', 'user': u'Administrator', u'full_name': None, u'device': u'desktop', 'session_ip': u'127.0.0.1'}, u'user': u'Administrator', u'sid': u'7d004b42cc8a9e65ae4240ae9ba9c9bee63672d944a34542b38d9c4e'}, 'communication_name': 'b61ec32709', 'print_format': u''}, 'is_async': True}
Traceback (most recent call last):
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/email.py", line 501, in sendmail
    recipients=recipients, cc=cc, bcc=bcc)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/communication.py", line 187, in _notify
    _notify(self, print_html, print_format, attachments, recipients, cc, bcc)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/email.py", line 176, in _notify
    print_letterhead=frappe.flags.print_letterhead
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 465, in sendmail
    inline_images=inline_images, header=header, print_letterhead=print_letterhead)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 140, in send
    print_letterhead=print_letterhead)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 161, in add
    email_queue = get_email_queue(recipients, sender, subject, **kwargs)
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 205, in get_email_queue
    e.message = cstr(mail.as_string())
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/email_body.py", line 239, in as_string
    self.validate()
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/email_body.py", line 176, in validate
    self.replace_sender()
  File "/home/codecakes/Documents/frappe/frappe-bench/apps/frappe/frappe/email/email_body.py", line 187, in replace_sender
    if cint(self.email_account.always_use_account_email_id_as_sender):
AttributeError: 'NoneType' object has no attribute 'always_use_account_email_id_as_sender'

```

**Comment by mihir-kandoi** [comment]
This appears to be a Frappe framework issue rather than ERPNext core, so I'm closing it here as part of issue triage. If it still happens on a current version, please open a new issue in the `frappe/frappe` repository. If you think this was closed in error, mention @mihir-kandoi here.
