### ISSUE TITLE
Italy: error with utils.py with last update

### ISSUE THREAD

**Issue by FiloSpaTeam** [frappe/erpnext#16819]
```python
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 45, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 853, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 843, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 910, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1033, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/italy/utils.py", line 285, in sales_invoice_on_cancel
    for attachment in get_e_invoice_attachments(doc):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/italy/utils.py", line 294, in get_e_invoice_attachments
    company_tax_id = invoice.company_tax_id if invoice.company_tax_id.startswith("IT") else "IT" + invoice.company_tax_id
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I need to cancel the invoice but i can't. Thx

**Comment by FiloSpaTeam** [comment]
Maybe it's related to erpnext_fattura_elettronica app. I reset database and the errore disappeared.
