### ISSUE TITLE
Document for field "shortcuts" attached to child table of "None" must be a dict or BaseDocument, not type 'unicode'

### ISSUE THREAD

**Issue by JoyceBabu** [frappe/erpnext#16838]
I am getting the following error when installing erpnext using `frappe_docker`.

```
./dbench --site <my_site_host_name> install-app erpnext

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 169, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 87, in install_app
    sync_from_app(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 356, in sync_from_app
    desktop_icon.update(m)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 83, in update
    self.set(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 130, in set
    self.extend(key, value)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 167, in extend
    self.append(key, v)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 161, in append
    self.name, str(type(value))[1:-1], value)
ValueError: Document for field "shortcuts" attached to child table of "None" must be a dict or BaseDocument, not type 'unicode' (Import Data)
```

**Comment by JoyceBabu** [comment]
Following is the the argument `m`, which is passed to `desktop_icon.update`.

```ruby
{
    u'category': u'Modules',
    u'shortcuts': [u'Import Data',
    u'Letter Head',
    u'Email Account',
    u'Item',
    u'Customer'],
    u'description': u"Dive into the basics for your organisation's needs.",
    u'color': u'#1abc9c',
    u'module_name': u'Getting Started',
    u'disable_after_onboard': 1,
    u'icon': u'fa fa-check-square-o',
    u'type': u'module',
    u'onboard_present': 1,
    u'label': u'Getting Started'
}
```

**Comment by JoyceBabu** [comment]
The above value was added in https://github.com/frappe/erpnext/commit/8aa4594b1ec4be8c13259d2603129170260ac4b6
