### ISSUE TITLE
v11,Profit and Loss Statement，when select any poject,show this error,plz check

### ISSUE THREAD

**Issue by gamma05772** [frappe/erpnext#16881]
Server Error: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 503, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 185, in run
    result = generate_report_result(report, filters, user)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 66, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/opt/bench/erpnext/apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 16, in execute
    ignore_closing_entries=True, ignore_accumulated_values_for_fy= True)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 148, in get_data
    gl_entries_by_account, ignore_closing_entries=ignore_closing_entries
  File "/opt/bench/erpnext/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 345, in set_gl_entries_by_account
    additional_conditions = get_additional_conditions(from_date, ignore_closing_entries, filters)
  File "/opt/bench/erpnext/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 388, in get_additional_conditions
    filters.project = [d.strip() for d in projects.strip().split(',') if d]
TypeError: a bytes-like object is required, not 'str'

**Comment by gamma05772** [comment]
Installed Apps
ERPNext: v11.1.14 (master)

Frappe Framework: v11.1.14 (master)

**Comment by gamma05772** [comment]
until v11.1.21,this error has not fixed

**Comment by gamma05772** [comment]
until v11.1.30,this error has not fixed

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
Thanks for raising the issue and being a valuable member of the ERPNext Community. :)
