### ISSUE TITLE
Stripe settings not found even when set after upgrade to v11.1

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#16928]
After upgrading to ERPnext v11.1 (from 10) we get:

```
Traceback (most recent call last):
  File "/home/user1/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/user1/frappe-bench/apps/frappe/frappe/api.py", line 56, in handle
    return frappe.handler.handle()
  File "/home/user1/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/user1/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/user1/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/user1/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 323, in make_payment_request
    frappe.local.response["location"] = pr.get_payment_url()
  File "/home/user1/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 113, in get_payment_url
    controller = get_payment_gateway_controller(self.payment_gateway)
  File "/home/user1/frappe-bench/apps/frappe/frappe/integrations/utils.py", line 80, in get_payment_gateway_controller
    frappe.throw(_("{0} Settings not found".format(payment_gateway)))
  File "/home/user1/frappe-bench/apps/frappe/frappe/__init__.py", line 353, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/user1/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in msgprint
    _raise_exception()
  File "/home/user1/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in _raise_exception
    raise raise_exception(msg)
ValidationError: Stripe Settings not found
```
This is still the case, if we change the payment gateway or account for the shop to Paypal. All Stripe parameters are correct.

**Comment by rasos** [comment]
Stripe is working again after deleting and then re-configuring all related settings at: 

- Webshop
- Payment Gateway Account
- Stripe Integration
- Cancel all previous SO (Sales Orders) related to previous Stripe payments (otherwise Payment account could not be deleted)

**Comment by nick9822** [comment]
@rasos it was asking for the name of the doctype/controller where settings are saved. For us it worked by simply populating fields at Payment Gateway account for Stripe as in the picture. 
![image](https://user-images.githubusercontent.com/10139291/60893312-552b7080-a27e-11e9-9a4b-6f5cb33b86c4.png)

Those who stumble upon this issue, this fix should work,
