### ISSUE TITLE
Products url Goes to Contact url

### ISSUE THREAD

**Issue by nsrtky** [frappe/erpnext#16943]
Hi,
After ı have updated to  it latest version Products links broken and started to go Contact link.Its a live at domainerp.com
below ı am going to send screen pic also.
Centos 7 nginx and Release v11.1.14
![image](https://user-images.githubusercontent.com/12385044/54517722-8c92ac00-4973-11e9-9906-06335a583ba5.png)

**Comment by jottunn** [comment]
confirming this issue on fresh install
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

**Comment by nsrtky** [comment]
confirming this issue on updates version 
ERPNext: v11.1.15 (master)
Frappe Framework: v11.1.15 (master)
you can view setting on web sites 

![image](https://user-images.githubusercontent.com/12385044/54676658-2db76900-4b12-11e9-9ce7-989122ec823e.png)

**Comment by nsrtky** [comment]
May you give us a document how we can see controllers, routes and product's links (related files) its request and response objects? how we should debug in order to be more quick not reading whole code ?

**Comment by nsrtky** [comment]
ERPNext: v11.1.18 (master)

Frappe Framework: v11.1.18 (master) version updates and still problems goes on and will go on...

**Comment by clarkejj** [comment]
Discussion is here https://discuss.erpnext.com/t/erpnext-v11-1-16-master-frappe-framework-v11-1-16-master-products-links-response-contact-form/47256

**Comment by nsrtky** [comment]
Version 11.1.19 its still go on and will go on...

**Comment by chlarsen** [comment]
I can confirm the same issue on a fresh install of the latest production version. 
I have created a item group tree, set up routing for different items and get nothing but redirections to te contact form. This is a bit embarrassing especially, as the website worked beforehand like a dream and clients start scratching their heads ;-).
Nothing to report from the Nginx front...

**Comment by chlarsen** [comment]
I am a bit at a loss on how to debug this. My routes are correctly set for item imports, but something seems to mangle them. Or is the routing for the item group tree somewhere buggy, and the Contact Us has been set intnerally as a default 404 page?

**Comment by chlarsen** [comment]
I get this, if I go to a variant and want to see its appearance on the website. This never happened prior to the last upgrade that caused all items in item group tree to redirect to the contact form (as outlined above by a number of users). Therefore, this may be related:
``````
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 142, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 158, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 165, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 187, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./templates/generators/item.html", line 1, in top-level template code
    {% extends "templates/web.html" %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 6, in top-level template code
    {%- if page_or_generator=="Generator" %}source-type="Generator" data-doctype="{{ doctype }}"{% endif %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 38, in top-level template code
    {% block body %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 64, in block "body"
    {% block content %}{% endblock %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 49, in block "content"
    {%- block page_content -%}{%- endblock -%}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./templates/generators/item.html", line 29, in block "page_content"
    {% set first_image = slideshow_items[0]['image'] %}
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: list object has no element 0
``````
Let me know, if this helps...
Chris

**Comment by chlarsen** [comment]
I have just installed the latest production upgrade, but, alas, no imrovement could be noted.
I do consider this issue as a pretty critical bug, as it (a) directly affects the external appearance of the public website and (b) happens "straight from the can" on virgin installs using the recommended install.py method. 
May I politely ask again the core developer team for some hints how to debug this beyond the little I could achieve so far? Or where to look for the (obvious?) bug?
Thank you!

**Comment by ovresko** [comment]
Found a workaround
Go to Shopping Cart Settings
enable accept payments + Set modatory fields (series, company ...)
Save and reload website
deactivate Shpping Cart after

issue here
https://github.com/frappe/erpnext/blob/5f8b358fd4746394cbe5c349b0e5bd1280c5af3a/erpnext/shopping_cart/cart.py#L390

**Comment by chlarsen** [comment]
Dear Ovresko,
Indeed! Thank you so much. This was a bit hard to find, but now, as I saw the code.... :-).
Hugely appreciated!
Chris
