### ISSUE TITLE
bench update error - 11.1.15

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#16970]
create mode 100644 frappe/website/web_form/request_to_delete_data/request_to_delete_data.py
 create mode 100644 frappe/www/_test/__init__.py
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
INFO:bench.utils:git pull  upstream develop
remote: Enumerating objects: 3610, done.
remote: Counting objects: 100% (1566/1566), done.
remote: Compressing objects: 100% (286/286), done.
remote: Total 941 (delta 739), reused 828 (delta 652), pack-reused 0
Receiving objects: 100% (941/941), 197.04 KiB | 2.29 MiB/s, done.
Resolving deltas: 100% (739/739), completed with 306 local objects.
From https://github.com/frappe/erpnext
 * branch                  develop    -> FETCH_HEAD
   94561607f0..3c95387926  develop    -> upstream/develop
Removing erpnext/templates/includes/product_page.js
Removing erpnext/templates/generators/item.html
Removing erpnext/support/doctype/issue_type/test_issue_type.js
Removing erpnext/support/doctype/issue/test_records.json
Removing erpnext/support/doctype/issue/test_issue.js
Auto-merging erpnext/public/node_modules
CONFLICT (add/add): Merge conflict in erpnext/public/node_modules
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/opt/bench/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, restart_systemd, requirements, no_backup, force=force, reset=reset)
  File "/opt/bench/bench-repo/bench/commands/update.py", line 73, in _update
    pull_all_apps(bench_path=bench_path, reset=reset)
  File "/opt/bench/bench-repo/bench/app.py", line 249, in pull_all_apps
    remote=remote, branch=get_current_branch(app, bench_path=bench_path)), cwd=app_dir)
  File "/opt/bench/bench-repo/bench/utils.py", line 159, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git pull  upstream develop

**Comment by lbazan** [comment]
Updating customizations for Web Page
Updating customizations for Item
Updating customizations for Web Form
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/utils.py", line 27, in build
    frappe.build.bundle(no_compress, app=app, make_copy=make_copy, restore = restore, verbose=verbose)
  File "/opt/bench/erpnext/apps/frappe/frappe/build.py", line 36, in bundle
    make_asset_dirs(make_copy=make_copy, restore=restore)
  File "/opt/bench/erpnext/apps/frappe/frappe/build.py", line 120, in make_asset_dirs
    os.symlink(source, target)
OSError: [Errno 17] File exists
bench@erp:~/erpnext$

**Comment by cjpit** [comment]
Yeah one of the latest commits broke it bad and has a hardcoded link for node_modules.. I'm trying to get a PR organised to fix it, but the last couple of commits seems to have created lots of conflicts

**Comment by cjpit** [comment]
@netchampfaris looks like your home dir is hardcoded in there...

**Comment by cjpit** [comment]
https://github.com/frappe/erpnext/pull/16975

**Comment by cjpit** [comment]
Some type of test that does a complete bench create site and install erpnext is needed - can that be done in travis etc for it to pass? I got bitten by a similar bug that was introduced to develop when i first started a week ago and it drove me nuts

**Comment by maxfu9** [comment]
> Updating customizations for Web Page
> Updating customizations for Item
> Updating customizations for Web Form
> Traceback (most recent call last):
> File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
> "**main**", fname, loader, pkg_name)
> File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
> exec code in run_globals
> File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in 
> main()
> File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
> click.Group(commands=commands)(prog_name='bench')
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 764, in **call**
> return self.main(*args, **kwargs)
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
> rv = self.invoke(ctx)
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/opt/bench/erpnext/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
> return callback(*args, **kwargs)
> File "/opt/bench/erpnext/apps/frappe/frappe/commands/utils.py", line 27, in build
> frappe.build.bundle(no_compress, app=app, make_copy=make_copy, restore = restore, verbose=verbose)
> File "/opt/bench/erpnext/apps/frappe/frappe/build.py", line 36, in bundle
> make_asset_dirs(make_copy=make_copy, restore=restore)
> File "/opt/bench/erpnext/apps/frappe/frappe/build.py", line 120, in make_asset_dirs
> os.symlink(source, target)
> OSError: [Errno 17] File exists
> bench@erp:~/erpnext$

also facing same problem

**Comment by ashish-greycube** [comment]
```
Updating customizations for Address
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/apps/frappe/frappe/commands/utils.py", line 27, in build
    frappe.build.bundle(no_compress, app=app, make_copy=make_copy, restore = restore, verbose=verbose)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/apps/frappe/frappe/build.py", line 36, in bundle
    make_asset_dirs(make_copy=make_copy, restore=restore)
  File "/home/ashish/bench-repo/frappe-bench-develop-branch/apps/frappe/frappe/build.py", line 120, in make_asset_dirs
    os.symlink(source, target)
OSError: [Errno 17] File exists

```

**Comment by ashish-greycube** [comment]
![image](https://user-images.githubusercontent.com/29812965/55210637-75bf4580-520e-11e9-840f-8af9e6d8e892.png)
@netchampfaris , it appears some hard-coded values are there
