### ISSUE TITLE
Frappe Version 11.1.15 Installation problem

### ISSUE THREAD

**Issue by saurabh2804** [frappe/erpnext#16989]
I keep getting the following error while trying to install a fresh instance of frappe-bench:

```    
Traceback (most recent call last):
      File "/home/saurabh/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/home/saurabh/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/saurabh/Documents/frappe-bench/apps/frappe/frappe/__init__.py", line 18, in <module>
        from .utils.jinja import (get_jenv, get_template, render_template, get_email_from_template, get_jloader)
      File "/home/saurabh/Documents/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 83
        def validate_email_address(email_str, throw=False):

```

**Workaround:** Getting the older version of frappe solved my problem. Go to apps/frappe

`git checkout 1a25daf6c108a66d37d76c11df09f9c7e973494a`

then go back to frappe-bench

**Comment by saurabh2804** [comment]
This seems similar: https://github.com/frappe/frappe/pull/7110

**Comment by sahil28297** [comment]
Fixed with the latest release.
