### ISSUE TITLE
v11.8 frappe.email.doctype.auto_email_report.auto_email_report.send_daily

### ISSUE THREAD

**Issue by nsrtky** [frappe/erpnext#17108]
{'event': u'daily', 'retry': 0, 'log': <function log at 0x7f28f11cc7d0>, 'site': u'domainerp.com', 'job_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily', 'method_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily', 'method': <function send_daily at 0x7f28df00f230>, 'user': u'Administrator', 'kwargs': {}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 103, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 191, in send_daily
    auto_email_report.send()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 126, in send
    data = self.get_report_content()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 66, in get_report_content
    filters = self.filters, as_dict=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 105, in get_data
    data = frappe.desk.query_report.run(self.name, filters=filters, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 502, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 185, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 66, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/tds_computation_summary/tds_computation_summary.py", line 10, in execute
    validate_filters(filters)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/tds_computation_summary/tds_computation_summary.py", line 24, in validate_filters
    from_year = get_fiscal_year(filters.from_date)[0]
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 20, in get_fiscal_year
    return get_fiscal_years(date, fiscal_year, label, verbose, company, as_dict=as_dict)[0]
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 76, in get_fiscal_years
    raise FiscalYearError(error_msg)
FiscalYearError: Date  not in any active Fiscal Year.

**Comment by Alchez** [comment]
@nsrtky, you're missing a Fiscal Year that covers the date when this error was thrown. Adding one and trying again should fix it.
