### ISSUE TITLE
Bug: Creating a new company

### ISSUE THREAD

**Issue by cjpit** [frappe/erpnext#17143]
Creating a new company on erpnext 11.1.18 breaks if the country is set to USA

It is also breaking on creating a new site, its just that it fails silently and you have no idea.  Things like cost centres etc are not created properly etc.

Please type some additional information that could help us reproduce this issue:
 App Versions
{
	"erpnext": "11.1.18",
	"frappe": "11.1.18",
}
Route
Form/Company/New Company 1

ModuleNotFoundError: No module named 'erpnext.regional.united_states.setup'
```Traceback (most recent call last):
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 905, in run_post_save_methods
    self.run_method("on_update")
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 97, in on_update
    install_country_fixtures(self.name)
  File "/home/cameron/development/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 400, in install_country_fixtures
    .format(frappe.scrub(company_doc.country)))(company_doc, False)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1018, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/__init__.py", line 799, in get_module
    return importlib.import_module(modulename)
  File "/home/cameron/development/frappe-bench/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.regional.united_states.setup'

Traceback (most recent call last):
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1027, in call
    return fn(*args, **newargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 905, in run_post_save_methods
    self.run_method("on_update")
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/cameron/development/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 97, in on_update
    install_country_fixtures(self.name)
  File "/home/cameron/development/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 400, in install_country_fixtures
    .format(frappe.scrub(company_doc.country)))(company_doc, False)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1018, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/cameron/development/frappe-bench/apps/frappe/frappe/__init__.py", line 799, in get_module
    return importlib.import_module(modulename)
  File "/home/cameron/development/frappe-bench/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.regional.united_states.setup'

```

**Comment by cjpit** [comment]
Resolved, was an artifact left over from switching to develop branch. deleted the united_states directory.
