### ISSUE TITLE
Bug (import data): can't import data "get_users_with_role" error

### ISSUE THREAD

**Issue by YasserKarim** [frappe/erpnext#17192]
Dears 
After update Frappe & ERPNext to last Release v11.1.20 

I have got **ImportError: cannot import name get_users_with_role**

While am importing assets data (500 lines), I check my permission to import assets and It's OK, I try as administration to import data of assets, I received the same errors

I receive 2 error, in error log related to this task
### 1st error
`{'event': u'data_import', 'retry': 0, 'log': <function log at 0x7f97e1c4ca28>, 'site': u'teg.88888.guru', 'job_name': u'Import on 09-04-2019 23:13:44', 'method_name': u'upload', 'method': <function upload at 0x7f97e29e1230>, 'user': u'yam@88888.guru', 'kwargs': {'from_data_import': u'Yes', 'data_import_doc': u'Import on 09-04-2019 23:13:44', 'user': u'yam@88888.guru'}, 'is_async': True}
Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 446, in upload
    error_log_doc = frappe.log_error(error_trace)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1482, in log_error
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.run_post_save_methods()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 916, in run_post_save_methods
    self.run_method("on_update")
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1017, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_module
    return rename_doc(*args, **kwargs)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/workflow/doctype/workflow_action/workflow_action.py", line 15, in <module>
    from frappe.utils.user import get_users_with_role
ImportError: cannot import name get_users_with_role`

### and; 2nd error
`Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 403, in upload
    original.save()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 916, in run_post_save_methods
    self.run_method("on_update")
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1017, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_module
    return rename_doc(*args, **kwargs)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/workflow/doctype/workflow_action/workflow_action.py", line 15, in <module>
    from frappe.utils.user import get_users_with_role
ImportError: cannot import name get_users_with_role`

**Comment by YasserKarim** [comment]
issue moved to Frappe "Bug (import data): can't import data "get_users_with_role" error" [7245](url)
