### ISSUE TITLE
Setting web link as item image throws an error

### ISSUE THREAD

**Issue by gaurav-naik** [frappe/erpnext#17298]
![weblink_image_error](https://user-images.githubusercontent.com/17795124/56417248-ec50df80-62b0-11e9-88b7-e4ef7f366d23.gif)

```
Traceback (most recent call last):
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 296, in _save
    self.run_before_save_methods()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/erpnext/erpnext/stock/doctype/item/item.py", line 122, in validate
    self.make_thumbnail()
  File "/home/gaurav/frappe-bench-v11/apps/erpnext/erpnext/stock/doctype/item/item.py", line 269, in make_thumbnail
    file_doc.make_thumbnail()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/core/doctype/file/file.py", line 201, in make_thumbnail
    image, filename, extn = get_web_image(self.file_url)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/core/doctype/file/file.py", line 409, in get_web_image
    image = Image.open(StringIO(r.content))
TypeError: initial_value must be str or None, not bytes

Traceback (most recent call last):
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/__init__.py", line 1030, in call
    return fn(*args, **newargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 296, in _save
    self.run_before_save_methods()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/gaurav/frappe-bench-v11/apps/erpnext/erpnext/stock/doctype/item/item.py", line 122, in validate
    self.make_thumbnail()
  File "/home/gaurav/frappe-bench-v11/apps/erpnext/erpnext/stock/doctype/item/item.py", line 269, in make_thumbnail
    file_doc.make_thumbnail()
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/core/doctype/file/file.py", line 201, in make_thumbnail
    image, filename, extn = get_web_image(self.file_url)
  File "/home/gaurav/frappe-bench-v11/apps/frappe/frappe/core/doctype/file/file.py", line 409, in get_web_image
    image = Image.open(StringIO(r.content))
TypeError: initial_value must be str or None, not bytes
```

**Possible solution**
frappe/frappe/core/doctype/file/file.py, line 405

Change
```
	image = Image.open(StringIO(r.content))
```
to
```
	image = Image.open(StringIO(str(r.content)))
```

**Comment by gaurav-naik** [comment]
This is not an ERPNext issue. Re-posting on frappe. Apologies.
