### ISSUE TITLE
Unable to Submit Work Orders after update to v11.1.22

### ISSUE THREAD

**Issue by EnSeal** [frappe/erpnext#17454]
Hello team 

I did a bench update to v11.1.22 and afterwards i started getting error messages when submitting work orders. everything works fine before bench update. 

Traceback (most recent call last):
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 226, in on_submit
    self.create_job_card()
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 245, in create_job_card
    create_job_card(self, row, auto_create=True)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 694, in create_job_card
    doc.insert()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 14, in validate
    self.validate_time_logs()
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 21, in validate_time_logs
    for d in self.get('time_logs'):
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "/home/ubuntu/xlevel/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/__init__.py", line 1027, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 848, in submit
    self._submit()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 837, in _submit
    self.save()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 313, in _save
    self.run_post_save_methods()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 908, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 226, in on_submit
    self.create_job_card()
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 245, in create_job_card
    create_job_card(self, row, auto_create=True)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 694, in create_job_card
    doc.insert()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/xlevel/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 14, in validate
    self.validate_time_logs()
  File "/home/ubuntu/xlevel/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 21, in validate_time_logs
    for d in self.get('time_logs'):
TypeError: 'NoneType' object is not iterable

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/pull/17760
