### ISSUE TITLE
E-Mail: Syntax error - line too long

### ISSUE THREAD

**Issue by jHetzer** [frappe/erpnext#17565]
Not able to send emails with following error log:
Titel:
```
frappe.email.queue.flush
```
Error:
```
(501, b'Syntax error - line too long')
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 425, in send_one
    smtpserver.sess.sendmail(email.sender, recipient.recipient, encode(message))
  File "/usr/lib64/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (501, b'Syntax error - line too long')
```
System Information:
```
ERPNext: v11.1.28 (master)
Frappe Framework: v11.1.27 (master)
CentOS Linux release 7.6.1810 (Core)
```

**Comment by jHetzer** [comment]
Related Discussion:
https://discuss.erpnext.com/t/smtplib-smtpdataerror-501-bsyntax-error-line-too-long/46570
