### ISSUE TITLE
Payment Entry Save Error Due Date

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#17628]
Please type some additional information that could help us reproduce this issue:
 App Versions
{
	"erpnext": "11.1.20",
	"frappe": "11.1.21"
}
Route
Form/Payment Entry/New Payment Entry 2
Error Report
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 748, in _validate_links
    result = d.get_invalid_links(is_submittable=self.meta.is_submittable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 479, in get_invalid_links
    values_to_fetch, as_dict=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 399, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 443, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 586, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'due_date' in 'field list'")

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 56, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 748, in _validate_links
    result = d.get_invalid_links(is_submittable=self.meta.is_submittable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 479, in get_invalid_links
    values_to_fetch, as_dict=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 399, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 443, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 586, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'due_date' in 'field list'")
Request Data
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Payment Entry\",\"name\":\"New Payment Entry 2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"sg@gmail.com\",\"naming_series\":\"PE-\",\"payment_type\":\"Receive\",\"posting_date\":\"2019-05-16\",\"company\":\"GDMIS\",\"paid_from_account_currency\":\"INR\",\"paid_to_account_currency\":\"INR\",\"mode_of_payment\":\"RAKESH CASH\",\"paid_to\":\"RAKESH CASH - GD\",\"paid_to_account_balance\":-270772,\"base_received_amount\":90240,\"unallocated_amount\":0.10000000000582077,\"difference_amount\":0,\"target_exchange_rate\":1,\"party_type\":\"Customer\",\"party\":\"KAMAL TRADING COMPANY, NAGPUR\",\"paid_from\":\"Debtors - GD\",\"paid_from_account_balance\":0,\"party_balance\":0,\"source_exchange_rate\":1,\"party_name\":\"KAMAL TRADING COMPANY, NAGPUR\",\"references\":[{\"docstatus\":0,\"doctype\":\"Payment Entry Reference\",\"name\":\"New Payment Entry Reference 22\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"sg@gmail.com\",\"parent\":\"New Payment Entry 2\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"idx\":1,\"reference_doctype\":\"Sales Order\",\"reference_name\":\"SO-00031\",\"total_amount\":90239.9,\"outstanding_amount\":90239.9,\"exchange_rate\":1,\"allocated_amount\":90239.9}],\"total_allocated_amount\":90239.9,\"base_total_allocated_amount\":90239.9,\"paid_amount\":90240,\"base_paid_amount\":90240,\"received_amount\":90240,\"allocate_payment_amount\":1,\"reference_no\":\"CASH RECIPT\",\"reference_date\":\"2019-05-16\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery224054500518180487351": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4210,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
Response JSON
{}

**Comment by clarkejj** [comment]
Be sure to post this issue on discuss.erpnext.com to raise notice.

Link to discuss and this issue for folks add comments plus a fix contribution.

**Comment by dj12djdjs** [comment]
I haven't seen this error in latest version of Payment Entry.
