### ISSUE TITLE
InternalError: (1054, u"Unknown column 'lead' in 'field list'")

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#17761]
When Opening CRM >> Prospects Engaged But Not Converted App Versions

```
{
	"erpnext": "11.1.33",
	"frappe": "11.1.30"
}
```
Route
```
query-report/Prospects Engaged But Not Converted
```
Error Report
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1032, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 507, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 201, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 76, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/report/prospects_engaged_but_not_converted/prospects_engaged_but_not_converted.py", line 13, in execute
    data = get_data(filters)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/report/prospects_engaged_but_not_converted/prospects_engaged_but_not_converted.py", line 57, in get_data
    {'lead': lead.name, 'limit': filters.get('no_of_interaction')})
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 199, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'lead' in 'field list'")
```
Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Prospects Engaged But Not Converted",
		"filters": "{\"no_of_interaction\":1,\"lead_age\":60}",
		"cmd": "frappe.desk.query_report.run"
	},
	"url": "/"
}
```
Response JSON
```
{}
```

**Comment by salmanulfarzy** [comment]
Similar issue while fetching Quotation information from Sales Invoice Page.

App Versions
```
{
	"erpnext": "11.1.33",
	"frappe": "11.1.30"
}
```
Route
```
Form/Sales Invoice/New Sales Invoice 1
```
Error Report
```
Traceback (most recent call last):
  File "/home/salman/frappe_bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/salman/frappe_bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/salman/frappe_bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/salman/frappe_bench/apps/frappe/frappe/__init__.py", line 1032, in call
    return fn(*args, **newargs)
  File "/home/salman/frappe_bench/apps/frappe/frappe/desk/search.py", line 155, in search_widget
    as_list=not as_dict)
  File "/home/salman/frappe_bench/apps/frappe/frappe/__init__.py", line 1260, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/salman/frappe_bench/apps/frappe/frappe/model/db_query.py", line 93, in execute
    result = self.build_and_run()
  File "/home/salman/frappe_bench/apps/frappe/frappe/model/db_query.py", line 117, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/salman/frappe_bench/apps/frappe/frappe/database.py", line 214, in sql
    self._cursor.execute(query)
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/salman/frappe_bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tabQuotation.customer' in 'field list'")
```

Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Quotation",
		"txt": "",
		"filters": "{\"docstatus\":1,\"status\":[\"!=\",\"Lost\"],\"company\":\"Foo Solutions\"}",
		"filter_fields": "[\"customer\",\"transaction_date\"]",
		"start": 0,
		"page_length": 21,
		"as_dict": 1,
		"cmd": "frappe.desk.search.search_widget"
	},
	"url": "/"
}
```
Response JSON
```
{}
```
