### ISSUE TITLE
【Bug Report】InternalError: (1054, u"Unknown column 'tabQuotation.customer' in 'field list'") ​

### ISSUE THREAD

**Issue by mojerro** [frappe/erpnext#17886]
I met a error on your online demo when I clicked save on sales order page (I guss it's named this, but I'm not using an English version). 

App Versions
![image](https://user-images.githubusercontent.com/15071824/59167015-9e927e00-8b61-11e9-927b-0df038374e17.png)

error reports

Traceback (most recent call last):
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/__init__.py", line 1032, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/desk/search.py", line 155, in search_widget
    as_list=not as_dict)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/__init__.py", line 1260, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/model/db_query.py", line 93, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/model/db_query.py", line 117, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-11-2019-06-05/apps/frappe/frappe/database.py", line 214, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/benches/bench-11-2019-06-05/env/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tabQuotation.customer' in 'field list'")
​
![image](https://user-images.githubusercontent.com/15071824/59167019-a5b98c00-8b61-11e9-9ff5-82ffa79bef25.png)

**Comment by JoeyGaojingxing** [comment]
![image](https://user-images.githubusercontent.com/15071824/59167207-a7378400-8b62-11e9-8ecd-fd70a9ebdd92.png)
when I point 报价, the price, it shows the error on sales > sales-order page
