### ISSUE TITLE
Cannot complete setup wizard

### ISSUE THREAD

**Issue by RyanSmithHE** [frappe/erpnext#17883]
**Problem:**
On a new install, the Setup Wizard runs through and hangs at the second-to-last step. Refreshing the page causes the Wizard to restart at /1.
This problem only manifests for some Countries, I've used South Africa as an example (this is what I've tested with most).

**Scope:**
All versions - Master, Stage and Develop branches. Confined only to the initial Wizard.

**Reproduce:**
1. Spin up a new instance for ANY branch (even the Demo downloadable VM image).
2. At the Wizard page #1, choose the default "English",
3. At page #2, choose "South Africa" which should also auto-choose Africa-JHB timezone and S.A. Rand (ZAR) currency - which are both correct.
4. Continue the Wizard in the normal way - It will not progress past Page 5.

**Preliminary checks:**
1. The currency and timezone has no effect, picking "South Africa" with other time and currency still manifests the problem. Conversely, picking "Botswana" with the S.A. zone and currency does not cause any problem.
2. I am unsure if picking language "English" matters - I have not tried others.
3. None of the rest of the Wizard matters, any and many different values has the same outcome.
4. In some Dev branch configs I've tried, the Wizard doesn't hang (aka become unresponsive) immediately after step 5, but only after a while of "thinking". This might be unrelated to the problem and because of newer handling methods.

_Just for ref, the latest install I did that produced the error:_
**ERPNext: v11.1.36** (master)
**Frappe Framework: v11.1.33** (master)

**Comment by PMojito** [comment]
This is a bug I have seen many times.  And not just for South Africa, but for other countries (USA).

I would be happy to collaborate with a more-experienced developer than myself, to work on this.

**Comment by dvdl16** [comment]
I've ran into this issue many times (South African here). Would also help with testing if necessary

**Comment by larrydevops** [comment]
Ran into the issue using South Africa, Botswana works as confirmed.

**Comment by barredterra** [comment]
When I cklick on "Next" after step 4, I get this screen:

![image](https://user-images.githubusercontent.com/14891507/77453161-2a2a8200-6df7-11ea-9620-0c2d08b7ce77.png)

And this error in the console:
```
Uncaught TypeError: Cannot read property 'language' of undefined
    at SubClass.set_date_options (date.js:44)
    at SubClass.make_input (date.js:6)
    at SubClass.proto.<computed> [as make_input] (class.js:53)
    at make_input (base_input.js:60)
    at SubClass.refresh_input (base_input.js:87)
    at SubClass.refresh (base_control.js:85)
    at proto.<computed>.attach_doc_and_docfields (layout.js:326)
    at proto.<computed>.refresh (layout.js:224)
    at proto.<computed>.make (field_group.js:23)
    at proto.<computed> [as make] (class.js:53)
```

### Versions

Development setup, production branches (version-12).

erpnext 12.6.0
frappe 12.4.1

Related: #16898

**Comment by barredterra** [comment]
```
frappe-bench> bench run-setup-wizard-ui-test

Running Setup Wizard Test...
http://0.0.0.0:8000/ -
======================================================================
ERROR: test_test_runner (frappe.tests.ui.test_test_runner.TestTestRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/tests/ui/test_test_runner.py", line 9, in test_test_runner
    passed = frappe.get_attr(setup_wizard_test)()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/test_setup_wizard.py", line 53, in run_setup_wizard_test
    driver.set_field("company_tagline", "Just for GST")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/selenium_testdriver.py", line 89, in set_field
    elem.send_keys(text)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=80.0.3987.149)


----------------------------------------------------------------------
Ran 1 test in 55.434s

FAILED (errors=1)
```
