### ISSUE TITLE
Error erpnext.projects.doctype.project.project.project_status_update_reminder 

### ISSUE THREAD

**Issue by mepoohsta** [frappe/erpnext#17891]
```{'event': u'all', 'retry': 0, 'log': <function log at 0x7fcdc0fb69b0>, 'site': u'xxx', 'job_name': u'erpnext.projects.doctype.project.project.project_status_update_reminder', 'method_name': u'erpnext.projects.doctype.project.project.project_status_update_reminder', 'method': <function project_status_update_reminder at 0x7fcdc0f06c80>, 'user': u'Administrator', 'kwargs': {}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 103, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 436, in project_status_update_reminder
    daily_reminder()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 446, in daily_reminder
    send_project_update_email_to_users(project.name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 511, in send_project_update_email_to_users
    reply_to=incoming_email_account
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 468, in sendmail
    inline_images=inline_images, header=header, print_letterhead=print_letterhead)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 77, in send
    text_content = html2text(message)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/html2text/__init__.py", line 867, in html2text
    return h.handle(html)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/html2text/__init__.py", line 134, in handle
    self.feed(data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/html2text/__init__.py", line 130, in feed
    data = data.replace("</' + 'script>", "</ignore>")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by mepoohsta** [comment]
https://discuss.erpnext.com/t/error-erpnext-projects-doctype-project-project-project-status-update-reminder/49682

**Comment by deepeshgarg007** [comment]
@mepoohsta   Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
