### ISSUE TITLE
Is possible to import old database of erpnext v10 into newest erpnext version?

### ISSUE THREAD

**Issue by lncan** [frappe/erpnext#17955]
Hello everyone, I tried to import old database of erpnext v10 into newest erpnext version but no success. I follow 2 commands following to do that:
```
bench --force --site sitename restore /path/to/old/database
bench --force --site sitename migrate
```
Everything was ok when i have completed the first command. But after doing the second, error has ocurred:
```
Migrating erp.abx-ltd.com
Executing frappe.patches.v12_0.remove_deprecated_fields_from_doctype #3 in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.566s
Executing execute:frappe.reload_doc('core', 'doctype', 'comment') in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.172s
Executing execute:frappe.reload_doc('email', 'doctype', 'document_follow') in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.121s
Executing execute:frappe.reload_doc('core', 'doctype', 'communication_link') in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.125s
Executing execute:frappe.reload_doc('core', 'doctype', 'communication') in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.51s
Executing frappe.patches.v11_0.reload_and_rename_view_log #2019-01-03 in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.319s
Executing frappe.patches.v11_0.change_email_signature_fieldtype in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.577s
Executing frappe.patches.v11_0.rename_google_maps_doctype in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 1.565s
Executing frappe.patches.v10_0.modify_smallest_currency_fraction in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.024s
Executing frappe.patches.v10_0.modify_naming_series_table in erp.abx-ltd.com (_831804db5b8606b0)
Success: Done in 0.036s
Executing frappe.patches.v10_0.enhance_security in erp.abx-ltd.com (_831804db5b8606b0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/frappe-erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/frappe-erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/frappe-erpnext/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/commands/site.py", line 229, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/opt/frappe-erpnext/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all()
  File "/opt/frappe-erpnext/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/opt/frappe-erpnext/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/frappe-erpnext/apps/frappe/frappe/patches/v10_0/enhance_security.py", line 34, in execute
    doc.save()
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_before_save_methods()
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 886, in run_before_save_methods
    self.run_method("validate")
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/frappe-erpnext/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/frappe-erpnext/apps/frappe/frappe/core/doctype/system_settings/system_settings.py", line 39, in validate
    if (self.force_user_to_reset_password and
AttributeError: 'SystemSettings' object has no attribute 'force_user_to_reset_password'
```
Please tell me the solution to resolve that. Thank you.

**Comment by flexy2ky** [comment]
here's the correct script:

bench --site sitename --force restore /path/to/old/database
bench --site sitename migrate

I have used this a number of times including a few minutes ago just to reconfirm and i didn't face this issue. so i guess you should try again

**Comment by kennethsequeira** [comment]
Closing the issue as it is being followed up on [discuss](https://discuss.erpnext.com/t/is-possible-to-import-old-database-of-erpnext-v10-into-newest-erpnext-version/49873/9)
