### ISSUE TITLE
[BUG] Shopping cart unable to checkout

### ISSUE THREAD

**Issue by govindsmenokee** [frappe/erpnext#17987]
website.js:161 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1032, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/shopping_cart/cart.py", line 63, in place_order
    if quotation.lead:
AttributeError: 'Quotation' object has no attribute 'lead'

**Comment by mihir-kandoi** [comment]
This issue has been automatically closed as it no longer appears to be valid. If you think this was closed in error, please mention me (@mihir-kandoi) in a comment here and I'll take another look.
