### ISSUE TITLE
Error while creating Bank Account

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18226]
Steps:

1. New "Bank Account"
2. Click on field: Bank > New Bank
3. I was Navigated to Bank form, entered Bank name and saved.
4. On save, Bank master was created and was auto-navigated to "Bank Account" master.

As soon as Bank was auto-updated in the Bank Account master, this error message popped-up.

<img width="1221" alt="Screenshot 2019-07-10 at 3 34 00 PM" src="https://user-images.githubusercontent.com/910238/60961261-5fef0f80-a329-11e9-9286-21c07fee8bda.png">
 
Error message in the console:

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 511, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/desk/notifications.py", line 286, in get_open_count
    filters=filters, limit=100, distinct=True, ignore_ifnull=True))
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1291, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1264, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/model/db_query.py", line 94, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/model/db_query.py", line 124, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'tabPayment Order.bank' in 'where clause'")

**Comment by saurabh6790** [comment]
Not able to replicate on xyz and on local
