### ISSUE TITLE
error in Sales Invoice for Get Items from Quotation 

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#18254]
### Environment 
ERPNext: v11.1.44 (master)
Frappe Framework: v11.1.39 (master)

### Steps to Reproduce
Step 1: Create a Quotation for any Customer
Step 2 : Go to Sales Invoice , Select the customer in step 1, click on Get Items from Quotation 
Step 3: Below error generates

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/desk/search.py", line 155, in search_widget
    as_list=not as_dict)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/__init__.py", line 1264, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/model/db_query.py", line 93, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/model/db_query.py", line 117, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-11-2019-07-04-2/apps/frappe/frappe/database.py", line 214, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/benches/bench-11-2019-07-04-2/env/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tabQuotation.customer' in 'field list'")

```

**Comment by jigneshpshah** [comment]
Fixed by PR #18236
