### ISSUE TITLE
Tax Category error when selection Customer Address

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18422]
<img width="1211" alt="Screenshot 2019-07-19 at 4 52 17 PM" src="https://user-images.githubusercontent.com/910238/61531944-f7e5ab00-aa45-11e9-9115-237343f82d10.png">

Error message:

```
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:352 Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
TypeError: get_address_tax_category() missing 1 required positional argument: 'tax_category'
```

**Comment by ruchamahabal** [comment]
@umairsy I was not able to replicate this issue in version 12 local instance. 
Tried selecting Customer Address everywhere with and without the Tax Category field filled up. Could you please elaborate on steps to replicate this issue?

**Comment by umairsy** [comment]
Seems working in my test instance as well. Perhaps local was broken or was missing configuration.
