### ISSUE TITLE
Error when checking Bank list or Bank master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18459]
<img width="1270" alt="Screenshot 2019-07-24 at 10 43 40 AM" src="https://user-images.githubusercontent.com/910238/61766952-4dcca100-ae00-11e9-84c4-6e595d26ab31.png">

```
jquery.min.js:4 GET https://itemtax.erpnext.xyz/api/method/frappe.desk.notifications.get_open_count?doctype=Bank&name=HDFC+Bank&items=%5B%22Bank+Account%22%2C%22Bank+Guarantee%22%2C%22Payment+Order%22%5D&_=1563945188277 500 (INTERNAL SERVER ERROR)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:218
frappe.call @ request.js:91
set_open_count @ dashboard.js:355
refresh @ dashboard.js:163
refresh_header @ form.js:492
(anonymous) @ form.js:400
Promise.then (async)
(anonymous) @ dom.js:261
frappe.run_serially @ dom.js:259
render_form @ form.js:397
(anonymous) @ form.js:368
Promise.then (async)
initialize_new_doc @ form.js:365
trigger_onload @ form.js:343
refresh @ form.js:292
load @ formview.js:84
(anonymous) @ formview.js:78
callback @ model.js:186
success @ request.js:76
200 @ request.js:113
(anonymous) @ request.js:236
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:218
frappe.call @ request.js:91
(anonymous) @ model.js:178
with_doc @ model.js:172
show_doc @ formview.js:59
(anonymous) @ formview.js:16
with_doctype @ model.js:108
make @ formview.js:12
show @ factory.js:24
frappe.route @ router.js:56
(anonymous) @ router.js:208
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
hashchange (async)
(anonymous) @ list_view.js:906
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
request.js:352 Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 511, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/desk/notifications.py", line 286, in get_open_count
    filters=filters, limit=100, distinct=True, ignore_ifnull=True))
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1291, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/__init__.py", line 1264, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/model/db_query.py", line 94, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/model/db_query.py", line 124, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-2019-04-27/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/benches/bench-2019-04-27/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'tabPayment Order.bank' in 'where clause'")
```

**Comment by ruchamahabal** [comment]
Payment Order removed from bank dashboard in:
https://github.com/frappe/erpnext/pull/18573
