### ISSUE TITLE
Company settings can't be saved anymore / Message: "Same Company is entered more than once"

### ISSUE THREAD

**Issue by borisnq** [frappe/erpnext#18475]
It is impossible to save company settings for an existing company!

If you press the "save" button you get following popup:
"message
Same Company is entered more than once"

Changed values won't be saved.

May be it is an related issue: the cost center tree shows only the main cost center, all childs seem to be vanished.
The database table tabCost Center shows still all cost centers values but the main cost center isn't marked as "is group" anymore

system:
- SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU

- git branch => * master

- Help => About:
Installed Apps

ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)

**Comment by surajshetty3416** [comment]
@borisnq Can you please add more specific steps like when are you getting this issue or maybe steps to replicate(animated GIFs would help)

Currently, on the same version you mentioned, I am able to save Company changes.

**Comment by e8543420** [comment]
I have the same problem. 

It  just happens when I want to update the company informaiton. The change won't be saved.

<img width="1001" alt="微信截图_20190808174758" src="https://user-images.githubusercontent.com/22390428/62693277-c3da2600-ba04-11e9-97ce-88e9fd9f36ef.png">

**Comment by borisnq** [comment]
@surajshetty3416
thanks for taking care!
This installation is running since about a year.
I can not say since when we can't saved the company setup anymore because after installation we don't have to change much in the basic setup.

At least 4 week ago we want to change the default cost center this is when we get the Error Message "Same Company is entered more than once" like **e8543420** too.

It doesn't matter if you change any value or not we have always this behavior.

We have to companies in the settings: One is the company which is installed during the default setup after ERPNext installation . We use this for testing the system.

The  second company is our productive setup.

Both settings can't be saved anymore.

Is it possible that there are some changes happens  about additional fields or changed field formats in the last updates?

**Comment by e8543420** [comment]
I tried to redepoly the system. The problem still there even with brand new installation. So I tried different configration. I find the problem comes when I set county to China(where I a using). There will be no problem when I set to US. I suspect the problem comes from the setting of Chart of Account or Cost Center for certain country.

To update. During the initialization step, I found that the default chart of account will be in the language of your selection, not coming with country. For example, if I set country to China but use language as English, the default chart of account will be in English. And this will not cause the "Same Company is entered more than once" problem. Instead, if I initialize with Chinese language, there will be a chart of account in Chinese, but will cause the problem.

**Comment by marceloabelda** [comment]
I Have de same problem.
![image](https://user-images.githubusercontent.com/635830/62774524-4ef60300-ba7b-11e9-819a-63fc32b28e84.png)

**Comment by biboudidou** [comment]
I have the same problem. Fresh install on ubuntu server 18.04.

**Comment by dasistwas** [comment]
Same here: V12.05

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 324, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 917, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 110, in on_update
    self.set_mode_of_payment_account()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 261, in set_mode_of_payment_account
    mode_of_payment.save(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 886, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/mode_of_payment/mode_of_payment.py", line 13, in validate
    self.validate_repeating_companies()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/mode_of_payment/mode_of_payment.py", line 22, in validate_repeating_companies
    frappe.throw(_("Same Company is entered more than once"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Same Company is entered more than once
```

**Comment by dasistwas** [comment]
The company is also listed in the customer list as customer. But was never created there. Maybe that is related.

**Comment by dasistwas** [comment]
When I do an SQL and check, if there are more than 1 companies:
SELECT COUNT(*) FROM tabCompany;
I get that:
+----------+
| COUNT(*) |
+----------+
|        1 |
+----------+

So there is only one company in the database. I think the check there:
https://github.com/frappe/erpnext/blob/9002a6c1951efaf970e67297963dcb456bebcb0f/erpnext/accounts/doctype/mode_of_payment/mode_of_payment.py#L21

is not a valid check.

And maybe you have the same problem in another file:

https://github.com/frappe/erpnext/blob/9002a6c1951efaf970e67297963dcb456bebcb0f/erpnext/hr/doctype/expense_claim_type/expense_claim_type.py#L14

**Comment by borisnq** [comment]
I cannot confirm the second issue of **dasistwas** 

In my case the company doesn't show up in the customer list.

**Comment by dasistwas** [comment]
@borisnq you are right. We just created a customer with the same name of the company so I thought it might be related, but in fact it is not.

**Comment by borisnq** [comment]
I've updated the system today with `bench update --reset`and I can save company settings without any error messages.

Any changes will be saved correctly now and the issue seems to be solved for me.

Thanks to all for your help!
