### ISSUE TITLE
Website: Error on Item List

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18485]
Error when listing item an website from V12 (test site). GIF of the steps.

https://imgur.com/a/JWhYTsD

Error message:

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 48, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 152, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 168, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 175, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 197, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/benches/bench-2019-05-09/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2019-05-09/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/benches/bench-2019-05-09/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frappe/benches/bench-2019-05-09/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/benches/bench-2019-05-09/apps/erpnext/erpnext/./templates/generators/item/item.html", line 1, in top-level template code
    {% extends "templates/web.html" %}
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code
    {% extends base_template_path %}
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/./templates/base.html", line 68, in top-level template code
    {% block content %}
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/./templates/web.html", line 60, in block "content"
    {{ main_content() }}
  File "/home/frappe/benches/bench-2019-05-09/env/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/./templates/web.html", line 15, in template
    {% block page_container %}
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/./templates/web.html", line 30, in block "page_container"
    {%- block page_content -%}{%- endblock -%}
  File "/home/frappe/benches/bench-2019-05-09/apps/erpnext/erpnext/./templates/generators/item/item.html", line 15, in block "page_content"
    {% include "templates/generators/item/item_details.html" %}
  File "/home/frappe/benches/bench-2019-05-09/apps/erpnext/erpnext/./templates/generators/item/item_details.html", line 12, in top-level template code
    {% if frappe.utils.strip_html(doc.web_long_description) %}
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/utils/data.py", line 607, in strip_html
    return _striptags_re.sub("", text)
TypeError: expected string or bytes-like object
```

Error when trying to access item from Website:

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 48, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 152, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 168, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 175, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/render.py", line 188, in build_page
    context = get_context(path)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/website/context.py", line 87, in build_context
    ret = context.doc.get_context(context)
  File "/home/frappe/benches/bench-2019-05-09/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 73, in get_context
    "products_as_list": cint(frappe.db.get_single_value('Products Settings', 'products_as_list'))
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/database/database.py", line 558, in get_single_value
    frappe.throw(_('Invalid field name: {0}').format(frappe.bold(fieldname)), self.InvalidColumnName)
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2019-05-09/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.database.database.Database.InvalidColumnName: Invalid field name: <b>products_as_list</b>
```

**Comment by scmmishra** [comment]
Hello @umairsy I see two tracebacks in the GiF you provided and I could not establish the relationship between the two, are the two issues related?

**Comment by umairsy** [comment]
First error message, when seeing the item from Item master, by clicking on "View on Website" link.

Second error when trying to see item on the website via it's relevant Item Group, for which we do setting in Website Settings.

**Comment by deepeshgarg007** [comment]
@umairsy  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
