### ISSUE TITLE
bug: several bugs and improvement ideas for education module

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#18599]
after test run the whold education module end to end, the following bugs identified

1.  pymysql.err.InternalError: (1054, "Unknown column 'course_name' in 'field list'") for both student group creation tool and enrolled courses in program enrollment

root cause: missing the fetch from **course_name** field in program course doctype

2. following error when generate student report
 Traceback (most recent call last):
  File "/home/frappe/erpnext12/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/erpnext12/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/erpnext12/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/erpnext12/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/erpnext12/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/erpnext12/apps/erpnext/erpnext/education/doctype/student_report_generation_tool/student_report_generation_tool.py", line 58, in preview_report_card
    "letterhead": letterhead.content,
AttributeError: 'dict' object has no attribute 'content'

root cause, program source code bug,  to be changed as 
"letterhead": letterhead and letterhead.get('content', None),

Improvement Ideas
1. field lable Mandatory to be changed as Mandatory Course, because mandatory is too generic, if translated without context, it will conflict the meaning in other places
2. field label Enrollment to be changed as Course Enrollment, match to the field name, thus make the translation more precise.
3. remove the default setting Indian on Nationality field in Student DocType

**Comment by uebmaster** [comment]
The same error for me
