### ISSUE TITLE
v12 Auto Repeat - TypeError: can’t compare datetime.date to unicode

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18648]
When trying to create an Auto Repeat - the error TypeError: can’t compare datetime.date to unicode keeps popping up.

**Comment by idolaru** [comment]
After several different tries and after countless workarounds - I could not find any solution until now.

I've tried all different frequencies .. the error is the same.

**Comment by clarkejj** [comment]
See this discussion https://discuss.erpnext.com/t/v12-typeerror-cant-compare-datetime-date-to-unicode/51536

**Comment by ruchamahabal** [comment]
fixed: https://github.com/frappe/frappe/pull/8202

**Comment by idolaru** [comment]
After updating to the latest version, Auto Repeat is showing the same error as before:

This is the log from logs/frappe.log

```
[ERROR] 2019-08-20 23:27:14,222 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: SITE RETRACTED
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"docstatus\":0,\"doctype\":\"Auto Repeat\",\"name\":\"New Auto Repeat 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"EMAIL ADDRESS RETRACTED\",\"disabled\":0,\"start_date\":\"2019-08-21\",\"f$
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 221, in insert
    self.run_method("before_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 37, in before_insert
    if start_date <= today_date:
TypeError: can't compare datetime.date to unicode
```

Installed Apps

ERPNext: v12.0.7 (version-12)

Frappe Framework: v12.0.6 (version-12)
