### ISSUE TITLE
bench.utils.CommandFailedError: yarn install

### ISSUE THREAD

**Issue by akawama-zz** [frappe/erpnext#18699]
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

$ bench version
erpnext 12.0.5
frappe 12.0.5

nodejs v10.16.2
mariadb  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Python 3.7.3
yarn 1.17.3

[Original erpnext forum thread](https://discuss.erpnext.com/t/bench-utils-commandfailederror-yarn-install/51683)

Hello guys,
I did a fresh install on my above mentioned system and everything was running fine then I decided to  run `bench-update` and I got the following message
```
➜  frappe-bench sudo bench update            
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up to date.
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python3.7/site-packages (6.1.0)
Backing up sites...

Cannot proceed with update: You have local changes in app "erpnext" that are not committed.

Here are your choices:

1. Merge the erpnext app manually with "git pull" / "git pull --rebase" and fix conflicts.
1. Temporarily remove your changes with "git stash" or discard them completely
	with "bench update --reset" or for individual repositries "git reset --hard"
2. If your changes are helpful for others, send in a pull request via GitHub and
	wait for them to be merged in the core.
```
Then I did `bench update --reset` and it gave me the following error
```
➜  frappe-bench `bench update --reset`
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up to date.
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python3.7/site-packages (6.1.0)
Backing up sites...
INFO:bench.app:pulling frappe
INFO:bench.utils:git fetch --all
Fetching upstream
INFO:bench.utils:git reset --hard upstream/version-12
HEAD is now at b1322ba5e Merge branch 'version-12-hotfix' into version-12
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
INFO:bench.utils:git fetch --all
Fetching upstream
INFO:bench.utils:git reset --hard upstream/version-12
HEAD is now at 9335cdd536 Merge branch 'version-12-hotfix' into version-12
INFO:bench.utils:find . -name "*.pyc" -delete
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python3.7/site-packages (19.2.1)
INFO:bench.utils:./env/bin/pip install -q -r /home/frappe/bench-repo/requirements.txt
INFO:bench.app:installing frappe
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/frappe 
INFO:bench.app:installing erpnext
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext 
Updating node packages...
INFO:bench.utils:yarn install
yarn install v1.17.3
warning ../../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.01s.
INFO:bench.utils:yarn install
yarn install v1.17.3
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "/home/frappe/.cache/yarn/v4/npm-core-js-2.6.1-87416ae817de957a3f249b3b5ca475d4aaed6042/node_modules/core-js/.yarn-metadata.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/home/frappe/frappe-bench/apps/erpnext/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
bench_command()
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 61, in update
_update(pull, patch, build, bench, auto, restart_supervisor, restart_systemd, requirements, no_backup, force=force, reset=reset)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 85, in _update
update_node_packages(bench_path=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 454, in update_node_packages
update_yarn_packages(bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 467, in update_yarn_packages
exec_cmd('yarn install', cwd=app_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 161, in exec_cmd
raise CommandFailedError(cmd)
bench.utils.CommandFailedError: yarn install
```
Here's my [yarn-error.log](https://gist.github.com/yakthungba/d4693b2ddbf8c0c538c111e2c68abb44) just in case.

After running `bench update` initially I got stuck on the front end with a message "Your system is being updated. Please refresh again after a few minutes" so I couldn't proceed with my front end work.

Then I ran `switch-to-branch version-12 frappe erpnext` and `bench update --patch`.  This removed the "system being updated" message from front end. But when I do `bench update` again I get into this same issue.

**Comment by krnkris** [comment]
First of all:
Cannot proceed with update: You have local changes in app "erpnext" that are not committed.
You made some local changes, it may cause problems.

About yarn install:
To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash

BTW:
why you use 
sudo bench update
Please try without sudo:
bench update

**Comment by akawama-zz** [comment]
Like mentioned in error the problem it seems was in /home/frappe/.cache/yarn/v4/npm-core-js-2.6.1-87416ae817de957a3f249b3b5ca475d4aaed6042/node_modules/core-js/.yarn-metadata.json file.

I removed the above file and reinstalled yarn, then everything worked perfectly.
