### ISSUE TITLE
v12 Auto Repeat - TypeError: can only concatenate list (not "unicode") to list

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18836]
After successfully adding an autorepeat with the following e-mail notification set:

```
<h1>Reminder Notification</h1>

<p>Check all bookings of this current month and follow these steps:</p>
<p></p><ol type="1">
  <li>Check the guest calculation for each and every booking</li>
  <li>Update the guest calculation if necessary</li>
  <li>Check all bookings by cross-checking with the daily schedule</li>
  <li>Ask for details from the agent if necessary</li>
<li>Update this task when you finish</li>
<li>Send your report following the report template to Julian</li>
</ol>
<p></p>

<strong>NOTE:</strong> At the end of the month the guest calculation from the daily schedule must <strong>perfectly</strong> match with the guest calculation report from the management system.

<p></p><p>Click to go to the task {{ frappe.utils.get_link_to_form(
	"Task", doc.name) }}</p>
```

The following error appears in the log:

```
{'event': None, 'retry': 0, 'log': <function log at 0x4c87938>, 'site': u'WEBSITE RETRACTED', 'job_name': u'frappe.automation.doctype.auto_repeat.auto_repeat.create_repeated_entries', 'method_name': u'frappe.automation.doctype.auto_repeat.auto_repeat.create_repeated_entries', 'method': <function create_repeated_entries at 0x4e4d140>, 'user': u'Administrator', 'kwargs': {'data': [{u'name': u'Guest calculation reminder'}]}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 304, in create_repeated_entries
    doc.create_documents()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 144, in create_documents
    self.notify_error_to_user(error_log)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 246, in notify_error_to_user
    recipients = get_system_managers(only_name=True) + self.owner
TypeError: can only concatenate list (not "unicode") to list
```

Also, for the Recipients I have set one email address per line and the error is this:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 137, in create_documents
    self.send_notification(new_doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 225, in send_notification
    subject=subject, content=message, attachments=attachments, send_email=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/email.py", line 73, in make
    }).insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 228, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 886, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/communication.py", line 60, in validate
    validate_email(self)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/communication/email.py", line 102, in validate_email
    validate_email_address(email, throw=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 120, in validate_email_address
    email = _check(e.strip())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 113, in _check
    frappe.InvalidEmailAddressError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
InvalidEmailAddressError: EMAIL ADDRESSES RETRACTED is not a valid Email Address
```

**Comment by ruchamahabal** [comment]
fixed and merged: https://github.com/frappe/frappe/pull/8286
Will be deployed soon.
