### ISSUE TITLE
V12 File attachment issues

### ISSUE THREAD

**Issue by erpcloudsystems** [frappe/erpnext#18846]
as we can see below multiple file upload doesn't work 

![fileupload](https://user-images.githubusercontent.com/11355558/63760626-f4083c80-c8bf-11e9-8067-157c8d9be5c9.gif)

and also Arabic file name doesn't upload ??

**Comment by erpcloudsystems** [comment]
console output 

`FileUploader.vue?rollup-plugin-vue=script.js:401 POST https://shop.riadco.com/api/method/upload_file 500 (INTERNAL SERVER ERROR)
(anonymous) @ FileUploader.vue?rollup-plugin-vue=script.js:401
upload_file @ FileUploader.vue?rollup-plugin-vue=script.js:327
(anonymous) @ FileUploader.vue?rollup-plugin-vue=script.js:288
Promise.then (async)
(anonymous) @ dom.js:261
frappe.run_serially @ dom.js:259
upload_files @ FileUploader.vue?rollup-plugin-vue=script.js:285
upload_files @ index.js:50
primary_action @ index.js:66
(anonymous) @ dialog.js:142
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
request.js:352 Traceback (most recent call last):
  File "/home/frappe/cilek-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/cilek-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/cilek-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/handler.py", line 193, in upload_file
    ret.save(ignore_permissions=ignore_permissions)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 294, in _save
    self.insert()
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 252, in insert
    self.run_method("after_insert")
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 1056, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 1039, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/cilek-bench/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/cilek-bench/apps/frappe/frappe/core/doctype/file/file.py", line 81, in after_insert
    "file_url": quote(self.file_url) if self.file_url else self.file_name,
  File "/usr/lib/python2.7/urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u0645'`

**Comment by amutaher** [comment]
same issue with me

**Comment by clarkejj** [comment]
See this https://discuss.erpnext.com/t/v12-file-attachment-issues/52411
