### ISSUE TITLE
pymysql.err.InternalError: (1054, "Unknown column 'is_tree' in 'field list'")

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#18893]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/site.py", line 233, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/opt/bench/erpnext/apps/frappe/frappe/migrate.py", line 40, in migrate
    clear_global_cache()
  File "/opt/bench/erpnext/apps/frappe/frappe/cache_manager.py", line 48, in clear_global_cache
    clear_website_cache()
  File "/opt/bench/erpnext/apps/frappe/frappe/website/render.py", line 295, in clear_cache
    frappe.clear_cache("Guest")
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 561, in clear_cache
    frappe.cache_manager.clear_user_cache(user)
  File "/opt/bench/erpnext/apps/frappe/frappe/cache_manager.py", line 31, in clear_user_cache
    clear_notifications(user)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/notifications.py", line 174, in clear_notifications
    config = get_notification_config()
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/notifications.py", line 237, in get_notification_config
    return frappe.cache().get_value("notification_config", _get)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/notifications.py", line 231, in _get
    nc = frappe.get_attr(notification_config)()
  File "/opt/bench/erpnext/apps/erpnext/erpnext/startup/notifications.py", line 77, in get_notification_config
    fields= ["name"], filters = {"name": ("not in", doctype), 'is_submittable': 1}):
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1293, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1266, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 95, in execute
    result = self.build_and_run()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 109, in build_and_run
    args = self.prepare_args()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.build_conditions()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 323, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 344, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/opt/bench/erpnext/apps/frappe/frappe/model/db_query.py", line 351, in prepare_filter_condition
    f = get_filter(self.doctype, f)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/data.py", line 898, in get_filter
    meta = frappe.get_meta(f.doctype)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 759, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/meta.py", line 84, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 104, in __init__
    self.load_from_db()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/meta.py", line 89, in load_from_db
    super(Meta, self).load_from_db()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 162, in load_from_db
    self.set(df.fieldname, children)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 131, in set
    self.extend(key, value)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 168, in extend
    self.append(key, v)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 145, in append
    value = self._init_child(value, key)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 184, in _init_child
    value = get_controller(value["doctype"])(value)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/base_document.py", line 37, in get_controller
    module_name, custom, is_tree = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), cache=True) \
  File "/opt/bench/erpnext/apps/frappe/frappe/database/database.py", line 400, in get_value
    order_by, cache=cache)
  File "/opt/bench/erpnext/apps/frappe/frappe/database/database.py", line 444, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database/database.py", line 591, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/opt/bench/erpnext/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'is_tree' in 'field list'")

**Comment by racitup** [comment]
I'm also getting this on a fresh instance of the evaluation dev VM. It prompts to do a `bench update` which results in this error. You get the error in all circumstances, e.g. bench doctor, bench migrate, navigate to the webserver on port 8000.
It seems to be the DocType table has lost the is_tree field perhaps?
Verified in the db:
```
show columns from tabDocType LIKE "%tree%";
Empty set (0.00 sec)
```

**Comment by racitup** [comment]
Maybe caused by https://github.com/frappe/frappe/pull/8312 ?

**Comment by racitup** [comment]
Appears to be fixed after a 'bench update'. I now get other errors from the develop branch, but suspect that is normal

**Comment by lbazan** [comment]
Fixed!
