### ISSUE TITLE
V12 Autorepeat sales invoice not working since upgrade from V11 to V12

### ISSUE THREAD

**Issue by muhammadanees83** [frappe/erpnext#18910]
getting this error in logs every night
{'event': u'daily', 'retry': 0, 'log': <function log at 0x7f02f534c8c0>, 'site': u'store.ultimate-solution.com.pk', 'job_name': u'frappe.automation.doctype.auto_repeat.auto_repeat.set_auto_repeat_as_completed', 'method_name': u'frappe.automation.doctype.auto_repeat.auto_repeat.set_auto_repeat_as_completed', 'method': <function set_auto_repeat_as_completed at 0x7f02f49e9cf8>, 'user': u'Administrator', 'kwargs': {}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/automation/doctype/auto_repeat/auto_repeat.py", line 325, in set_auto_repeat_as_completed
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 313, in _save
    self.validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 709, in validate_update_after_submit
    self._validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 616, in _validate_update_after_submit
    frappe.UpdateAfterSubmitError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
UpdateAfterSubmitError: Not allowed to change Status after submission

**Comment by ChipwizBen** [comment]
Possibly related: https://github.com/frappe/erpnext/issues/18888

**Comment by ChipwizBen** [comment]
I also get the same error every night after upgrade, in v12 and now in v12.1.0

**Comment by muhammadanees83** [comment]
no solution yet :(
