### ISSUE TITLE
Black Comment being added on each save 

### ISSUE THREAD

**Issue by ahmadpak** [frappe/erpnext#18933]
Every time I save a document for example Customer a blank comment is added. This happens when editing custom doctypes.

![image](https://user-images.githubusercontent.com/7881486/64339499-a4331f00-cffd-11e9-949c-a9cc2a0de850.png)

> desk.min.js:1 Traceback (most recent call last):
  File "/home/ahmad/erpnext12/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 310, in _save
    self._validate()
  File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 463, in _validate
    self._sanitize_content()
  File "/home/ahmad/erpnext12/apps/frappe/frappe/model/base_document.py", line 661, in _sanitize_content
    sanitized_value = sanitize_html(value, linkify=df.fieldtype=='Text Editor')
AttributeError: 'NoneType' object has no attribute 'fieldtype'

> desk.min.js:1 Traceback (most recent call last):
   File "/home/ahmad/erpnext12/apps/frappe/frappe/app.py", line 60, in application
     response = frappe.api.handle()
   File "/home/ahmad/erpnext12/apps/frappe/frappe/api.py", line 55, in handle
     return frappe.handler.handle()
   File "/home/ahmad/erpnext12/apps/frappe/frappe/handler.py", line 21, in handle
     data = execute_cmd(cmd)
   File "/home/ahmad/erpnext12/apps/frappe/frappe/handler.py", line 56, in execute_cmd
     return frappe.call(method, **frappe.form_dict)
   File "/home/ahmad/erpnext12/apps/frappe/frappe/__init__.py", line 1036, in call
     return fn(*args, **newargs)
   File "/home/ahmad/erpnext12/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
     doc.save()
   File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 271, in save
     return self._save(*args, **kwargs)
   File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 310, in _save
     self._validate()
   File "/home/ahmad/erpnext12/apps/frappe/frappe/model/document.py", line 463, in _validate
     self._sanitize_content()
   File "/home/ahmad/erpnext12/apps/frappe/frappe/model/base_document.py", line 661, in _sanitize_content
     sanitized_value = sanitize_html(value, linkify=df.fieldtype=='Text Editor')
 AttributeError: 'NoneType' object has no attribute 'fieldtype'

**Comment by Don-Leopardo** [comment]
+1. I have the same issue. Tried in Help Article

**Comment by ahmadpak** [comment]
Issue has been fixed in V12.1.1 please update @Don-Leopardo

**Comment by Don-Leopardo** [comment]
@MohammadAhmad1990 In my instance the blank comment is still being added. I'm in the last version of frappe and ERPNext. Can you check if it generates a new comment when you save the customer? Are you self hosted?
