### ISSUE TITLE
Error in Sales register,Gst Sales Register

### ISSUE THREAD

**Issue by remeshkvkumar** [frappe/erpnext#19178]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/__init__.py", line 511, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/desk/query_report.py", line 201, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/frappe/frappe/desk/query_report.py", line 76, in generate_report_result
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/erpnext/erpnext/accounts/report/sales_register/sales_register.py", line 10, in execute
    return _execute(filters)
  File "/home/frappe/benches/bench-version-11-2019-09-24/apps/erpnext/erpnext/accounts/report/sales_register/sales_register.py", line 70, in _execute
    tax_amount_precision = get_field_precision(frappe.get_meta("Sales Taxes and Charges").get_field("tax_amount"), currency=company_currency) or 2
NameError: global name 'get_field_precision' is not defined

**Comment by ruchamahabal** [comment]
fixed in: 
v12: https://github.com/frappe/erpnext/pull/19166
v11: https://github.com/frappe/erpnext/pull/19170
