### ISSUE TITLE
Duplicate Entry for key domain_name while updating to v12.1.6

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#19235]
Its happened in one environment, was successful in others. Wonder if someone else has experienced it. Looking into the probable cause.

![image](https://user-images.githubusercontent.com/1822868/66046492-84c0e080-e52e-11e9-8368-1fd38f6975d5.png)

![image](https://user-images.githubusercontent.com/1822868/66046536-a4f09f80-e52e-11e9-9153-edeab91106a8.png)

**Comment by DonWMason** [comment]
Just happened to me too while updating:

Patching sites...
Migrating erp.fmtsolutions.com
Executing frappe.patches.v12_0.set_default_incoming_email_port in erp.fmtsolutions.com (3de00357df8890bd)


There was an issue while migrating the DocType: Email Domain

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/erpnext-prod/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/commands/site.py", line 233, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/patches/v12_0/set_default_incoming_email_port.py", line 9, in execute
    frappe.reload_doc("email", "doctype", "email_domain", force=True)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/__init__.py", line 799, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/utils.py", line 174, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/import_file.py", line 27, in import_files
    reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/import_file.py", line 32, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/import_file.py", line 66, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/modules/import_file.py", line 141, in import_doc
    doc.insert()
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 258, in insert
    self.run_post_save_methods()
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 917, in run_post_save_methods
    self.run_method("on_update")
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 1056, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 1039, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpnext/erpnext-prod/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 281, in on_update
    raise e
frappe.exceptions.ValidationError: domain_name field cannot be set as unique in tabEmail Domain, as there are non-unique existing values

**Comment by muchai** [comment]
@DonWMason Try this: https://discuss.erpnext.com/t/domain-name-field-cannot-be-set-as-unique-in-tabemail-domain/53445

**Comment by Suraj787** [comment]
@muchai  this is not working  same issue after delete of domain in db
