### ISSUE TITLE
[v12]: Problem with Patch move_item_tax_to_item_tax_template

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#19249]
Refer# 1: https://discuss.erpnext.com/t/v12-possible-bug-in-patch-for-migrating-from-v11-to-v12/51585/4

Refer # 2: https://discuss.erpnext.com/t/migrating-from-v11-to-v12-issues-with-patch/52819

The error I am getting after 2 months of reporting is below, this is happening for my old quotation which is very old in my v11 data and still its failing and on top of it the Quotation is Cancelled as well.
```
Migrating rigplv12
Executing erpnext.patches.v12_0.move_item_tax_to_item_tax_template in rigplv12 (_3bd611f3e1fe10b1)
HR2XSQ009N0 Quotation QTN131400110
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aditya/v12/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/aditya/v12/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aditya/v12/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aditya/v12/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aditya/v12/apps/frappe/frappe/commands/site.py", line 234, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/aditya/v12/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/aditya/v12/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/aditya/v12/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/aditya/v12/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/aditya/v12/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/aditya/v12/apps/erpnext/erpnext/patches/v12_0/move_item_tax_to_item_tax_template.py", line 56, in execute
    item_tax_map, d.item_code, d.parent)
  File "/home/aditya/v12/apps/erpnext/erpnext/patches/v12_0/move_item_tax_to_item_tax_template.py", line 99, in get_item_tax_template
    item_tax_template.save()
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 271, in save
    return self._save(*args, **kwargs)
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 294, in _save
    self.insert()
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 228, in insert
    self.run_before_save_methods()
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 886, in run_before_save_methods
    self.run_method("validate")
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 786, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 1055, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 1038, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aditya/v12/apps/frappe/frappe/model/document.py", line 780, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/aditya/v12/apps/erpnext/erpnext/accounts/doctype/item_tax_template/item_tax_template.py", line 12, in validate
    self.validate_tax_accounts()
  File "/home/aditya/v12/apps/erpnext/erpnext/accounts/doctype/item_tax_template/item_tax_template.py", line 24, in validate_tax_accounts
    d.idx))
  File "/home/aditya/v12/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/aditya/v12/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/aditya/v12/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Item Tax Row 1 must have account of type Tax or Income or Expense or Chargeable
```
Now I checked my database and found I item in my DB to be not having the account type mentioned but even after I changed the account_type to 'Expense Account' I am still getting this error.

**Comment by harshit-30** [comment]
can we close this issue?
