### ISSUE TITLE
frappe.utils.background_jobs.run_doc_method (Error Importing from Tally)

### ISSUE THREAD

**Issue by shreerangamvinay** [frappe/erpnext#19332]
{'event': None, 'retry': 0, 'log': <function log at 0x7faa5d72d050>, 'site': u'testinterio.profezzo.com', 'job_name': u'frappe.utils.background_jobs.run_doc_method', 'method_name': u'frappe.utils.background_jobs.run_doc_method', 'method': <function run_doc_method at 0x7faa5e35f7d0>, 'user': u'interionation@yahoo.com', 'kwargs': {'doc_method': u'_process_master_data', 'name': u'Tally Migration on 16-10-2019 18:01:48', 'doctype': u'Tally Migration'}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 78, in run_doc_method
    getattr(frappe.get_doc(doctype, name), doc_method)(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 214, in _process_master_data
    items, uoms = get_stock_items_uoms(collection)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 194, in get_stock_items_uoms
    "stock_uom": item.BASEUNITS.string,
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by clarkejj** [comment]
Thanks for this report - please post this too on discuss.erpnext.com to inform and enlist help from the community
