### ISSUE TITLE
Session Start Failed! 'items!'

### ISSUE THREAD

**Issue by kumar-gajmer** [frappe/erpnext#19347]
Installed frappe v12.xx. ERPNext app not installed as I want to develop an application on frappe. After 2 days, I am not able to install any new app on my site. It gets installed but desk wouldn't load. Then I got the following error:
![Screen Shot 2019-10-19 at 12 21 19 PM](https://user-images.githubusercontent.com/27823502/67138859-56037380-f26b-11e9-9a06-47c4863442e9.png)

Traceback (most recent call last):
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/www/desk.py", line 21, in get_context
    boot = frappe.sessions.get()
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 132, in get
    bootinfo = get_bootinfo()
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/boot.py", line 44, in get_bootinfo
    load_desktop_icons(bootinfo)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/boot.py", line 104, in load_desktop_icons
    bootinfo.allowed_modules = get_modules_from_all_apps_for_user()
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/config/__init__.py", line 26, in get_modules_from_all_apps_for_user
    module["links"] =  get_onboard_items(module["app"], frappe.scrub(module_name))[:5]
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 268, in get_onboard_items
    sections = get_config(app, module)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 228, in get_config
    for item in section["items"]:
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 48, in update_controller_context
    ret = module.get_context(context)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/www/desk.py", line 24, in get_context
    print(frappe.get_traceback())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 48, in render
    data = render_page_by_language(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 152, in render_page_by_language
    return render_page(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 168, in render_page
    return build(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 175, in build
    return build_page(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 188, in build_page
    context = get_context(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 98, in build_context
    update_controller_context(context, context.controller)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 55, in update_controller_context
    frappe.errprint(frappe.utils.get_traceback())
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in errprint
    print(msg)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 48, in update_controller_context
    ret = module.get_context(context)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/www/error.py", line 11, in get_context
    print(frappe.get_traceback().encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 78, in render
    data = render_page(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 168, in render_page
    return build(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 175, in build
    return build_page(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 188, in build_page
    context = get_context(path)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 98, in build_context
    update_controller_context(context, context.controller)
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 55, in update_controller_context
    frappe.errprint(frappe.utils.get_traceback())
  File "/Users/gajmer/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in errprint
    print(msg)
BrokenPipeError: [Errno 32] Broken pipe

I did most of the things suggested in forums like migrating, updating and all, but no help.

**Comment by clarkejj** [comment]
BrokenPipeError: [Errno 32] Broken pipe

This refers to a network socket error between web browser client and server.

Please post this with details of your environment on discuss for advice

**Comment by kumar-gajmer** [comment]
My Environment:

OSX 10.13.6
Manually installed (redis, Mariadb and other dependencies)
Firefox (with Firebug) for debugging
VSCode with Python Package installed
I have 2 custom apps installed for my company.

**Comment by clarkejj** [comment]
Please post this with details of your environment on discuss for advice?
