### ISSUE TITLE
InternalError: (1054, u"Unknown column 'condition' in 'field list'")

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#19412]
## Description of the issue

The system is  some times showing a error report, the issue looks 

## Context information (for bug reports)

This is happening since the last update via bench update command.

**Output of `bench version`**

erpnext 11.1.46
frappe 11.1.61

## Steps to reproduce the issue

Just login after last update.

![image](https://user-images.githubusercontent.com/3522386/67591374-83906700-f71a-11e9-826a-aedf8ea1b5b1.png)

### Observed result

Some opcion are not displayed properly with the above traceback report

### Expected result

Acces to all options normally

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 88, in logout
    frappe.local.login_manager.logout()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 282, in logout
    delete_session(frappe.session.sid, user=user, reason="User Manually Logged Out")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 83, in delete_session
    logout_feed(user, reason)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/activity_log/feed.py", line 57, in logout_feed
    add_authentication_log(subject, user, operation="Logout")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/activity_log/activity_log.py", line 44, in add_authentication_log
    }).insert(ignore_permissions=True, ignore_links=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 215, in insert
    self.run_method("before_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 775, in run_method
    run_webhooks(self, method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/webhook/__init__.py", line 24, in run_webhooks
    fields=["name", "`condition`", "webhook_docevent", "webhook_doctype"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1293, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1266, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 94, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 122, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 214, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'condition' in 'field list'")
```

## Additional information

Ubuntu 16.04 setup with easy_intall script

**Comment by williamjmorenor** [comment]
there are many traceback reports but the last line is always the same:

InternalError: (1054, u"Unknown column 'condition' in 'field list'")

**Comment by williamjmorenor** [comment]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/chat/doctype/chat_profile/chat_profile.py", line 86, in create
    dprof.save(ignore_permissions = True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 215, in insert
    self.run_method("before_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 775, in run_method
    run_webhooks(self, method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/webhook/__init__.py", line 24, in run_webhooks
    fields=["name", "`condition`", "webhook_docevent", "webhook_doctype"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1293, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1266, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 94, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 122, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 214, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'condition' in 'field list'")
```

**Comment by williamjmorenor** [comment]
This is a vanilla erpnext, with just some added custom columns vie the ERPNext customice form option

**Comment by williamjmorenor** [comment]
For the record run:

`bench --site site1.local execute frappe.model.sync.sync_al`

Thinks to fix this issue. Please close is you think there is nothing more about this traceback

**Comment by clarkejj** [comment]
With any error please post first to discuss.erpnext.com, so all the community are informed to benefit respond and vet issues thanks!  (This list is intended for those that remain unresolved)
