### ISSUE TITLE
release v12.1.7 update error

### ISSUE THREAD

**Issue by santoshbb** [frappe/erpnext#19414]
Is this a bug in 
erpnext 12.1.7
frappe 12.0.17.
after updating to new version i am getting following error for bench update and bench migrate

Migrating test
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 233, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in migrate
    clear_global_cache()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cache_manager.py", line 48, in clear_global_cache
    clear_website_cache()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 295, in clear_cache
    frappe.clear_cache("Guest")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 563, in clear_cache
    frappe.cache_manager.clear_user_cache(user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cache_manager.py", line 31, in clear_user_cache
    clear_notifications(user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 120, in clear_notifications
    config = get_notification_config()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 198, in get_notification_config
    return frappe.cache().hget("notification_config", frappe.session.user, _get)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 172, in hget
    value = super(RedisWrapper, self).hget(_name, key)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/client.py", line 1963, in hget
    return self.execute_command('HGET', name, key)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by tejpochiraju** [comment]
Fixed by following instructions here - https://github.com/frappe/frappe/issues/8677#issuecomment-546182842

**Comment by tejpochiraju** [comment]
This is a Frappe issue and is being [tracked here](https://github.com/frappe/frappe/issues/8677). Would recommend closing this.

**Comment by santoshbb** [comment]
this problem solved in v12.1.8.
I have updated to v12.1.8, i was able to update smoothly without errors and accounting module reappeared.
