### ISSUE TITLE
Allocated amount of advance payment isn't working.

### ISSUE THREAD

**Issue by saidul-islam-tuhin** [frappe/erpnext#19455]
## Description of the issue
I make a purchase order of 200pcs qty whose total amount is 90,000tk. Then i make an advance payment entry for that PO the amount of payment entry has 60,000tk.

I make a Purchase receipt of 100pcs and the amount is  45,000tk. So when i create a Purchase invoice from that PR i click **"Set Advances and Allocate (FIFO)"**. So, in Advance payment child table, **Advance Amount** equal to 60,000tk and i make allocate amount is 45,000tk. That means i want to consume the bill from the advance payment.

But when i click the save button, an error show which said:
**frappe.exceptions.ValidationError: Advance amount cannot be greater than BDT 45,000**

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/munim/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/munim/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/munim/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/munim/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/munim/frappe-bench/apps/frappe/frappe/__init__.py", line 1038, in call
    return fn(*args, **newargs)
  File "/home/munim/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 272, in save
    return self._save(*args, **kwargs)
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in _save
    self.insert()
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 229, in insert
    self.run_before_save_methods()
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 888, in run_before_save_methods
    self.run_method("validate")
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/munim/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 68, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 38, in validate
    super(BuyingController, self).validate()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate
    super(StockController, self).validate()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 104, in validate
    validate_pricing_rules(self)
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 406, in validate_pricing_rules
    doc.calculate_taxes_and_totals()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 165, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 15, in __init__
    self.calculate()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 29, in calculate
    self.calculate_total_advance()
  File "/home/munim/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 463, in calculate_total_advance
    .format(self.doc.party_account_currency, invoice_total))
  File "/home/munim/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/munim/frappe-bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/munim/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Advance amount cannot be greater than BDT 50000.0
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@saidul-islam-tuhin  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
