### ISSUE TITLE
CSV from Report broken

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19827]
## Reproduce by:
- Select Report
- Choose Export in CSV file
## Error Message
```
Traceback (most recent call last):
  File "/home/frappe/bench-repo/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/bench-repo/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench-repo/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench-repo/apps/frappe/frappe/__init__.py", line 1038, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench-repo/apps/frappe/frappe/__init__.py", line 511, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/bench-repo/apps/frappe/frappe/desk/reportview.py", line 177, in export_query
    frappe.response['result'] = text_type(f.read(), 'utf-8')
TypeError: decoding str is not supported
```
## Additional information

ERPNext: v12.1.8 (master)
Frappe Framework: v12.0.17 (master)

**Comment by clarkejj** [comment]
See also https://discuss.erpnext.com/t/typeerror-decoding-str-is-not-supported-in-csv-export/50962/2
