### ISSUE TITLE
Can't create New Clinical Procedure Template and items that depend on it 

### ISSUE THREAD

**Issue by antfobe** [frappe/erpnext#20218]
Hi all, I am using the master branch (healthcare option) and have encountered what seems to be a bug:

![image](https://user-images.githubusercontent.com/13102173/71949750-83e5bd80-31b3-11ea-82ac-956203259783.png)

I already tried [setting the default Stock](https://discuss.erpnext.com/t/how-do-i-change-the-default-unit-of-measure/23955), but the problem persists - Is there anything I am missing?

# Steps to Reproduce:
 * 1: Login as Administrator;
 * 2: Proceed to >Healthcare>Clinical Procedure Template;
 * 3: Fill out the form(s) and attempt to save;
 * 4: Receive the error message: 'Could not find Default Unit of Measure: Unit'

```
(erpnext) git rev-parse --verify master: 926150bccbf1d93bacebcf36dc33a3d116173138
(frappe) git rev-parse --verify master: 880d824b77d2a6392a5d8ae9ea7db22199513c91
```

**Comment by manto89** [comment]
I'm experiencing the same issue: 
The browser console reports:
```
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 243, in insert
    self.run_method("after_insert")
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/bench/apps/erpnext/erpnext/healthcare/doctype/clinical_procedure_template/clinical_procedure_template.py", line 25, in after_insert
    create_item_from_template(self)
  File "/home/frappe/bench/apps/erpnext/erpnext/healthcare/doctype/clinical_procedure_template/clinical_procedure_template.py", line 85, in create_item_from_template
    }).insert(ignore_permissions=True)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 216, in insert
    self._validate_links()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 741, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Default Unit of Measure: Unit
```

I've resolved the issue by creating a Unit of Measure called "Unit" in Stock > Setup > UOM. 
I didn't have that UOM since i've installed ErpNext with a non-english language (Italian in my case)

**Comment by ruchamahabal** [comment]
fixed in: https://github.com/frappe/erpnext/pull/21350
Closing.
