### ISSUE TITLE
[V12 bug] Bank Reconciliation Get Payment Entries - InternalError

### ISSUE THREAD

**Issue by racitup** [frappe/erpnext#20343]
## Description of the issue
Error using `Get Payment Entries` in Bank Reconciliation.
See stacktrace below.
Suspected bug in Plaid integration.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.3.1
Frappe Framework: v12.1.0
```

## Steps to reproduce the issue

1. Configure Plaid and add a Bank Account through Plaid
2. Go to Bank Reconciliation
3. Select the Plaid bank account
4. Hit `Get Payment Entries`

### Observed result
Error:
![Screen Shot 2020-01-20 at 01 34 29](https://user-images.githubusercontent.com/18157195/72692675-1e83bc00-3b25-11ea-9bdb-3f265a4d4fa8.png)

### Expected result
A list of bank transactions

### Stacktrace / full error message
frappe.log:
```
[ERROR] 2020-01-20 00:27:35,754 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 43, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/bank_reconciliation/bank_reconciliation.py", line 42, in get_payment_entries
    """.format(condition, account_cond), (self.bank_account, self.from_date, self.to_date), as_dict=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 't2.bank_account_no' in 'where clause'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 131, in get_snapshot
    if type(value)==str and value.startswith(b"u'"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

## Additional information
install.py onto Ubuntu 18.04
Also broken in develop as of 20/Jan/2020

**Comment by racitup** [comment]
Also when `Include POS Transactions` is set:
```
[ERROR] 2020-01-20 18:23:57,094 | /home/frappe/staging-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
  File "/home/frappe/staging-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/staging-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/staging-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/staging-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/staging-bench/apps/frappe/frappe/__init__.py", line 1059, in call
    return fn(*args, **newargs)
  File "/home/frappe/staging-bench/apps/frappe/frappe/handler.py", line 89, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/staging-bench/apps/frappe/frappe/desk/form/run_method.py", line 43, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/staging-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/staging-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/staging-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/staging-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/staging-bench/apps/erpnext/erpnext/accounts/doctype/bank_reconciliation/bank_reconciliation.py", line 75, in get_payment_entries
    {"account":self.bank_account, "from":self.from_date, "to":self.to_date}, as_dict=1)
  File "/home/frappe/staging-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/staging-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/home/frappe/staging-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
KeyError: 'bank_account_no'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/staging-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/staging-bench/apps/frappe/frappe/utils/error.py", line 131, in get_snapshot
    if type(value)==str and value.startswith(b"u'"):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

**Comment by racitup** [comment]
Also:
Status `Failed`
Scheduled Job `plaid_settings.automatic_synchronization`
Details
Traceback (most recent call last):
  File "/home/frappe/staging-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 73, in execute
    frappe.get_attr(self.method)()
  File "/home/frappe/staging-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.py", line 204, in automatic_synchronization
    plaid_accounts = frappe.get_all("Bank Account", filter={"integration_id": ["!=", ""]}, fields=["name", "bank"])
  File "/home/frappe/staging-bench/apps/frappe/frappe/__init__.py", line 1322, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/staging-bench/apps/frappe/frappe/__init__.py", line 1295, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
TypeError: execute() got an unexpected keyword argument 'filter'
