### ISSUE TITLE
LDAP Search String needs to end with a placeholder

### ISSUE THREAD

**Issue by JoyceBabu** [frappe/erpnext#20427]
## Description of the issue

When I try to enter `(&(objectclass=inetOrgPerson)(|(uid={0})(mail={0})))` as the LDAP Search String, I am getting the error message

> LDAP Search String needs to end with a placeholder, eg sAMAccountName={0}

Please replace the end with placeholder `{0}` check, with contains placeholder `{0}`. The above search string used to work on a previous version of ERPNext.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.3.1
frappe 12.1.0
```

## Steps to reproduce the issue

1. Go to Integrations > LDAP Settings
2. Enter `(&(objectclass=inetOrgPerson)(|(uid={0})(mail={0})))` under LDAP Search String.
3. Click Save

### Observed result

Fails with message

> LDAP Search String needs to end with a placeholder, eg sAMAccountName={0}

### Expected result

Setting saved successfully

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1041, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 272, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 308, in _save
    self.run_before_save_methods()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 888, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/integrations/doctype/ldap_settings/ldap_settings.py", line 20, in validate
    frappe.throw(_("LDAP Search String needs to end with a placeholder, eg sAMAccountName={0}"))
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 363, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 349, in msgprint
    _raise_exception()
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: LDAP Search String needs to end with a placeholder, eg sAMAccountName={0}
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by alexszilagyi** [comment]
Any updates?

**Comment by iAmmar7** [comment]
Any updates?

**Comment by alexszilagyi** [comment]
Not from my side...

**Comment by Mayeu** [comment]
Any update on this? This seems extremely weird that we can't filter on anything but `xxx={0}`. This make it impossible to use the LDAP authentication on FreeIPA for exemple, which use a flat hierarchy, thus relying on the filter to actually filter.

**Comment by JoyceBabu** [comment]
@Mayeu I am not using Erpnext now.

**Comment by Mayeu** [comment]
@JoyceBabu Thank you for your answer :+1:

**Comment by jon-nfc** [comment]
Hi everyone (even op who isn't using ERPNext now)
I've started working on fix for this issue, does #13738 solve your particular issue?

@Mayeu 
Can you provide some info either here or on #13738 on how freeIPA LDAP is implemented. In particular how groups are done? As this will enable me confirm if my proposal fixes your issue as well

**Comment by jon-nfc** [comment]
@ankush,

Can confirm that this issue is validated as during the work I conducted in frappe/frappe#13777. It was by design of the previous developer of the LDAP implementation that the username placeholder was at the end of the search string.

Backporting frappe/frappe#13777 to version 12 should also fix this issue as it did for version 13.

Of note and for confirmation, if a backport to v12 is conducted, confirmation of the python LDAP version will need to be done as the frappe v13 python LDAP module was what was developed against.
