### ISSUE TITLE
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

### ISSUE THREAD

**Issue by radhikagattani183** [frappe/erpnext#20591]
Facing the below issue while starting the setup : 

Traceback (most recent call last):
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
    return super(StaticDataMiddleware, self).__call__(environ, start_response)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/app.py", line 81, in application
    response = handle_exception(e)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/app.py", line 191, in handle_exception
    http_status_code=http_status_code)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/website/render.py", line 33, in render
    raise_if_disabled(path)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/website/render.py", line 345, in raise_if_disabled
    'route': ['like', '%{0}'.format(path)]
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/database.py", line 528, in get_all
    return frappe.get_all(*args, **kwargs)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/__init__.py", line 1321, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/__init__.py", line 1294, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in execute
    result = self.build_and_run()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
    args = self.prepare_args()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
    self.set_optional_columns()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/model/db_query.py", line 298, in set_optional_columns
    columns = get_table_columns(self.doctype)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/database.py", line 863, in get_table_columns
    columns = self.get_db_table_columns('tab' + doctype)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/database.py", line 854, in get_db_table_columns
    where table_name = %s ''', table)]
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/indictrans/radhika_workspace/demoerp_v12/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

**Comment by radhikagattani183** [comment]
The Above issue can be fixed by following the steps- 
1. sudo mysqld --tc-heuristic-recover=ROLLBACK
2. sudo service mysqld restart
