### ISSUE TITLE
bench update failing

### ISSUE THREAD

**Issue by anasanzari** [frappe/erpnext#20899]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/commands/site.py", line 233, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in migrate
    clear_global_cache()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/cache_manager.py", line 48, in clear_global_cache
    clear_website_cache()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 295, in clear_cache
    frappe.clear_cache("Guest")
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/__init__.py", line 576, in clear_cache
    frappe.cache_manager.clear_user_cache(user)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/cache_manager.py", line 31, in clear_user_cache
    clear_notifications(user)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 120, in clear_notifications
    config = get_notification_config()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 200, in get_notification_config
    return frappe.cache().hget("notification_config", user, _get)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 180, in hget
    value = generator()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 180, in _get
    hooks = frappe.get_hooks()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/__init__.py", line 955, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/__init__.py", line 929, in load_app_hooks
    for app in [app_name] if app_name else get_installed_apps(sort=True):
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/__init__.py", line 893, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 702, in get_global
    return self.get_default(key, user)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 706, in get_default
    d = self.get_defaults(key, parent)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 724, in get_defaults
    defaults = frappe.defaults.get_defaults(parent)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/defaults.py", line 77, in get_defaults
    globald = get_defaults_for()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/defaults.py", line 204, in get_defaults_for
    where parent = %s order by creation""", (parent,), as_dict=1)
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/financeadmin/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/financeadmin/frappe-bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4f542e24e6267720'@'localhost' (using password: YES)")

**Comment by clarkejj** [comment]
This is a password or user account issue not a bug for eg. https://discuss.erpnext.com/t/bench-update-build-failed/59081
