### ISSUE TITLE
Cannot open CoA

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#21048]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 770, in get_children
    each["balance"] = flt(get_balance_on(each.get("value"), in_account_currency=False))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 116, in get_balance_on
    year_start_date = get_fiscal_year(date, verbose=0)[1]
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 24, in get_fiscal_year
    return get_fiscal_years(date, fiscal_year, label, verbose, company, as_dict=as_dict)[0]
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 27, in get_fiscal_years
    fiscal_years = frappe.cache().hget("fiscal_years", company) or []
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 178, in hget
    value = super(RedisWrapper, self).hget(_name, key)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/client.py", line 2975, in hget
    return self.execute_command('HGET', name, key)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/client.py", line 877, in execute_command
    conn.send_command(*args)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/connection.py", line 720, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/connection.py", line 771, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/redis/connection.py", line 121, in encode
    "bytes, string, int or float first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```
![image](https://user-images.githubusercontent.com/14891507/77449833-c30ace80-6df2-11ea-9a63-7178fd8e4f1a.png)

### Versions

ERPNext: v12.2.2 (version-12-hotfix)
Frappe Framework: v12.1.0 (version-12-hotfix)

**Comment by happy-cat-coder** [comment]
Same problem here when i want to add a a raw material...

**Comment by happy-cat-coder** [comment]
Hope the answears from [here](https://discuss.erpnext.com/t/creating-new-customer-having-error-of-redis-server-how-to-fix/58453/3) will help you.

**Comment by deepeshgarg007** [comment]
@barredterra Closing this, hope this is resolved by now.
