### ISSUE TITLE
Error while creating demo : Either location or employee must be required

### ISSUE THREAD

**Issue by nomi-gee** [frappe/erpnext#21194]
Error while creating demo :frappe.exceptions.ValidationError: Either location or employee must be required
here is full log 
muhammad@muhammad-ThinkPad-E550:/media/muhammad/erpnext$ bench make-demo --site site1.test --domain Manufacturing --reinstall
MySQL root password: 
Creating Database...
9.52KiB 0:00:00 [34.5MiB/s] [==============================================================================================>] 100%            

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]
Set Administrator password: 
Re-enter Administrator password: 

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Updating customizations for Address
*** Scheduler is enabled ***
Complete Setup...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/muhammad/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/media/muhammad/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/media/muhammad/erpnext/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/commands/__init__.py", line 45, in make_demo
    demo.make(domain, days)
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/demo/demo.py", line 31, in make
    manufacture.setup_data()
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/demo/setup/manufacture.py", line 15, in setup_data
    setup_asset()
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/demo/setup/manufacture.py", line 63, in setup_asset
    asset.submit()
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 866, in submit
    self._submit()
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 855, in _submit
    self.save()
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 929, in run_post_save_methods
    self.run_method("on_submit")
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 1065, in composer
    return composed(self, method, *args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 1048, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 788, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 33, in on_submit
    self.make_asset_movement()
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 156, in make_asset_movement
    'reference_name': reference_docname
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 895, in run_before_save_methods
    self.run_method("validate")
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 1065, in composer
    return composed(self, method, *args, **kwargs)
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 1048, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/media/muhammad/erpnext/apps/frappe/frappe/model/document.py", line 788, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/assets/doctype/asset_movement/asset_movement.py", line 12, in validate
    self.validate_asset()
  File "/media/muhammad/erpnext/apps/erpnext/erpnext/assets/doctype/asset_movement/asset_movement.py", line 26, in validate_asset
    frappe.throw(_("Either location or employee must be required"))
  File "/media/muhammad/erpnext/apps/frappe/frappe/__init__.py", line 374, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/media/muhammad/erpnext/apps/frappe/frappe/__init__.py", line 353, in msgprint
    _raise_exception()
  File "/media/muhammad/erpnext/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Either location or employee must be required

**Comment by capmahesh** [comment]
@nomi-gee  Got solution? I have same error !

**Comment by voarsh2** [comment]
Count me as having the same issue
