### ISSUE TITLE
Error Updating Translations

### ISSUE THREAD

**Issue by codrotech** [frappe/erpnext#21279]
## Description of the issue
After launching bench update-translations I get error ( Untranslated and Translated files are present)
## Context information (for bug reports)
Trying to translate app literals 
**Output of `bench version`**
erpnext 12.6.0
frappe 12.4.1
```

## Steps to reproduce the issue

1. bench get-untranslated it [file]
2. translate untranslated with google
3. bench update-translations it [file untranslated] [file translated]

### Observed result
frappe/frappe/translation/[lang].csv get completely cleaned up
### Expected result
translated file [lang].csv in app/app/translations folder
### Stacktrace / full error message
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/translate.py", line 65, in update_translations
    frappe.translate.update_translations(lang, untranslated_file, translated_file)
  File "/opt/bench/erpnext/apps/frappe/frappe/translate.py", line 660, in update_translations
    write_translations_file(app, lang, full_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/translate.py", line 696, in write_translations_file
    app_messages, full_dict or get_full_dict(lang))
  File "/opt/bench/erpnext/apps/frappe/frappe/translate.py", line 588, in write_csv_file
    w.writerow([p.encode('utf-8') if p else '', m.encode('utf-8'), t.encode('utf-8')])
TypeError: a bytes-like object is required, not 'str'

```
(paste here)
```

## Additional information
If I changes frappe/frappe/translate.py/write_csv_file
with open(path, 'wb') as msgfile:   to  with open(path, 'w') as msgfile:
It creates all files [lang].csv  but in byte format data   b'DocType'

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 18

**Comment by AlvaroMolano** [comment]
It happens the same to me.
Also tried to solve it myself in development env. by interchanging wb & w formats. Either way, I can not force those changes in production env. it needs to be solved here (main repository).
I will be glad to know about a near fix.

**Comment by codrotech** [comment]
> It happens the same to me.
> Also tried to solve it myself in development env. by interchanging wb & w formats. Either way, I can not force those changes in production env. it needs to be solved here (main repository).
> I will be glad to know about a near fix.

Any news on this issue?
