### ISSUE TITLE
AttributeError: 'WebsiteSettings' object has no attribute 'footer_type'

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#21369]
This error is appearing after a recent pull from develop branch.

Traceback (most recent call last):
  File "/opt/erpnext/erpnext/apps/frappe/frappe/middlewares.py", line 16, in __call__
    return super(StaticDataMiddleware, self).__call__(environ, start_response)
  File "/opt/erpnext/erpnext/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/erpnext/erpnext/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/erpnext/erpnext/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/opt/erpnext/erpnext/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/opt/erpnext/erpnext/apps/frappe/frappe/app.py", line 83, in application
    response = handle_exception(e)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/app.py", line 194, in handle_exception
    http_status_code=http_status_code)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/render.py", line 78, in render
    data = render_page(path)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/render.py", line 168, in render_page
    return build(path)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/render.py", line 175, in build
    return build_page(path)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/render.py", line 188, in build_page
    context = get_context(path)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/context.py", line 80, in build_context
    context.update(get_website_settings())
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 152, in get_website_settings
    add_webviews(context, settings)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 165, in add_webviews
    if settings.footer_type=='Web View' and settings.footer_web_view:
AttributeError: 'WebsiteSettings' object has no attribute 'footer_type'

**Comment by kennethsequeira** [comment]
@sjain17 run bench migrate.

Had faced the same issue a couple of days back. There is a patch written for this which will fix the error.

**Comment by kennethsequeira** [comment]
@sjain17 have you tried running `bench migrate` and checked?

**Comment by sjain17** [comment]
yes it is working after bench migrate and bench update. Thanks!
