### ISSUE TITLE
Migration Error: frappe.exceptions.DuplicateEntryError: ('Scheduled Job Type', 'patient_appointment.send_appointment_reminder', IntegrityError(1062, "Duplicate entry 'patient_appointment.send_appointment_reminder' for key 'PRIMARY'"))

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#21434]
## Description of the issue

patch fails on develop branch

## Context information (for bug reports)

```
frappe.exceptions.DuplicateEntryError: ('Scheduled Job Type', 'patient_appointment.send_appointment_reminder', IntegrityError(1062, "Duplicate entry 'patient_appointment.send_appointment_reminder' for key 'PRIMARY'"))
```

**Output of `bench version`**
```
5.0.0
```

## Steps to reproduce the issue

1. move into develop frappe-bench
2. `bench update`

### Observed result

Patch Fails

### Expected result

Migration successful

### Stacktrace / full error message

```sh
craft@cepl-erpnext:~/frappe-bench-edge$ bench update --reset
Backing up sites...
INFO:bench.app:pulling frappe
$ git fetch --all
Fetching upstream
Fetching Thunderbottom
Fetching prafful1234
$ git reset --hard upstream/develop
HEAD is now at 27af065bb Merge pull request #10001 from RJPvT/patch-7
$ find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
$ git fetch --all
Fetching upstream
$ git reset --hard upstream/develop
HEAD is now at 4b2d9b3679 Merge pull request #21386 from nextchamp-saqib/quo-status-fix
$ find . -name "*.pyc" -delete
Updating Python libraries...
$ /home/craft/frappe-bench-edge/env/bin/pip install -q -U pip
INFO:bench.app:installing frappe
$ /home/craft/frappe-bench-edge/env/bin/pip install -q -U -e /home/craft/frappe-bench-edge/apps/frappe 
[sudo] password for craft: 
$ sudo supervisorctl restart frappe-bench-edge-workers: frappe-bench-edge-web:
frappe-bench-edge-workers:frappe-bench-edge-frappe-schedule: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-1: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-0: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-1: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-0: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-0: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-1: stopped
frappe-bench-edge-web:frappe-bench-edge-node-socketio: stopped
frappe-bench-edge-web:frappe-bench-edge-frappe-web: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-schedule: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-0: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-0: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-0: started
frappe-bench-edge-web:frappe-bench-edge-frappe-web: started
frappe-bench-edge-web:frappe-bench-edge-node-socketio: started
INFO:bench.app:installing erpnext
$ /home/craft/frappe-bench-edge/env/bin/pip install -q -U -e /home/craft/frappe-bench-edge/apps/erpnext 
$ sudo supervisorctl restart frappe-bench-edge-workers: frappe-bench-edge-web:
frappe-bench-edge-workers:frappe-bench-edge-frappe-schedule: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-1: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-0: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-0: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-1: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-1: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-0: stopped
frappe-bench-edge-web:frappe-bench-edge-frappe-web: stopped
frappe-bench-edge-web:frappe-bench-edge-node-socketio: stopped
frappe-bench-edge-workers:frappe-bench-edge-frappe-schedule: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-long-worker-0: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-0: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-short-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-1: started
frappe-bench-edge-workers:frappe-bench-edge-frappe-default-worker-0: started
frappe-bench-edge-web:frappe-bench-edge-frappe-web: started
frappe-bench-edge-web:frappe-bench-edge-node-socketio: started
Updating node packages...
$ yarn install
yarn install v1.22.0
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.0
$ snyk protect
Successfully applied Snyk patches

Done in 9.81s.
Done in 11.60s.
$ yarn install
yarn install v1.22.0
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.0
$ snyk protect
Successfully applied Snyk patches

Done in 4.51s.
Done in 5.79s.
Patching sites...
Migrating cepl.mntechnique.com
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/model/base_document.py", line 328, in db_insert
    ), list(d.values()))
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'patient_appointment.send_appointment_reminder' for key 'PRIMARY'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/craft/frappe-bench-edge/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/commands/site.py", line 252, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/migrate.py", line 54, in migrate
    sync_jobs()
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 129, in sync_jobs
    insert_events(all_events, scheduler_events)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 139, in insert_events
    insert_event_list(events, event_type, all_events)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 151, in insert_event_list
    insert_single_event(frequency, event)
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 159, in insert_single_event
    frequency = frequency
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/model/document.py", line 249, in insert
    raise e
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/model/document.py", line 246, in insert
    self.db_insert()
  File "/home/craft/frappe-bench-edge/apps/frappe/frappe/model/base_document.py", line 338, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Scheduled Job Type', 'patient_appointment.send_appointment_reminder', IntegrityError(1062, "Duplicate entry 'patient_appointment.send_appointment_reminder' for key 'PRIMARY'"))
```

## Additional information

- OS version / distribution: Ubuntu 18.04
- `ERPNext` install method: manual install

**Comment by revant** [comment]
https://github.com/frappe/erpnext/pull/21431 fixed it
