### ISSUE TITLE
Latest Version of ERPNext throws error on install

### ISSUE THREAD

**Issue by aure1is** [frappe/erpnext#21472]
## Context information (for bug reports)
Pulled a fresh frappe_docker container and added a new site. To check if the basic frappe new site works did a bench start. Site works.
![image](https://user-images.githubusercontent.com/25451106/80488452-8f3e3e00-8988-11ea-89d1-23ff7c560f2f.png)

Then trying to install the erpnext app by doing following code. During the installation the error occurs.

```
bench get-app erpnext https://github.com/frappe/erpnext.git
bench --site mysite.localhost install-app erpnext
```

## Steps to reproduce the issue

1. get a fresh frappe_docker
2. create a new site
3. fetch and try to install app erpnext
![image](https://user-images.githubusercontent.com/25451106/80489167-a29dd900-8989-11ea-93d0-9f9a4d32c69f.png)

### Observed result
Error report listed above.

### Expected result
Installation successful

### Stacktrace / full error message

**Output of `bench version`**
```
frappe@f78b83dd90f2:/workspace/development/frappe-bench$ bench --site testsite.localhost install-app erpnext

Installing erpnext...
Updating DocTypes for erpnext       : [======================                  ]Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/site.py", line 179, in install_app
    _install_app(app, verbose=context.verbose)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/installer.py", line 83, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 66, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 106, in import_doc
    doc = frappe.get_doc(docdict)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 753, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 71, in get_doc
    return controller(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 115, in __init__
    super(Document, self).__init__(kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in __init__
    self.update(d)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in update
    self.set(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 135, in set
    self.extend(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 172, in extend
    self.append(key, v)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 149, in append
    value = self._init_child(value, key)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 184, in _init_child
    value["doctype"] = self.get_table_field_doctype(key)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 298, in get_table_field_doctype
    return self.meta.get_field(fieldname).options
AttributeError: 'NoneType' object has no attribute 'options'
```

## Additional information
Latest

**Comment by jma4227** [comment]
So, it looks like that you have a field that doesn’t have the correct options... it could be that one of your child tables doctype names was changed. I had an error like that when I deleted a doctype and had a custom field with a doctype that couldn’t be found

**Comment by aure1is** [comment]
> So, it looks like that you have a field that doesn’t have the correct options... it could be that one of your child tables doctype names was changed. I had an error like that when I deleted a doctype and had a custom field with a doctype that couldn’t be found

And where does that field come from? As I said it is a completely fresh site with a fresh install of frappe. Never logged in before. I 100% followed to instructions from https://github.com/frappe/frappe_docker/tree/develop/development and at the step where erpnext is installed it fails with the above error.
