### ISSUE TITLE
v13-Some errors while updating an already existing v13 environment

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21555]
I don't know if someone else has experienced the below errors.
The update succeeds albeit.

remote: Enumerating objects: 613, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 298 (delta 219), reused 262 (delta 185), pack-reused 0
Receiving objects: 100% (298/298), 37.21 KiB | 3.72 MiB/s, done.
Resolving deltas: 100% (219/219), completed with 68 local objects.
From https://github.com/frappe/frappe
   6e68210d6..cf878a2f4  develop                     -> upstream/develop
   f1d69c4ee..df9a6248a  version-12-hotfix           -> upstream/version-12-hotfix
 * [new branch]          version-13-beta             -> upstream/version-13-beta
   d15e8c82e..33ec0e8cc  version-13-beta-pre-release -> upstream/version-13-beta-pre-release
 * [new tag]             v13.0.0-beta.1              -> v13.0.0-beta.1
Backing up sites...
INFO:bench.app:pulling frappe
$ git fetch --all
Fetching upstream
$ git reset --hard upstream/develop
HEAD is now at cf878a2f4 fix: Use text instead of icon to show or hide password (#10200)
$ find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
$ git fetch --all
Fetching upstream
remote: Enumerating objects: 1196, done.
remote: Counting objects: 100% (675/675), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 452 (delta 356), reused 336 (delta 248), pack-reused 0
Receiving objects: 100% (452/452), 73.20 KiB | 9.15 MiB/s, done.
Resolving deltas: 100% (356/356), completed with 103 local objects.
From https://github.com/frappe/erpnext
   f411e754ae..a1ffc44f0c  develop                     -> upstream/develop
   7c5f43d794..119f2f07a5  new-translations            -> upstream/new-translations
 * [new branch]            revert-21420-patch-8        -> upstream/revert-21420-patch-8
   426f0bc168..bf1fc47564  version-12-hotfix           -> upstream/version-12-hotfix
 * [new branch]            version-13-beta             -> upstream/version-13-beta
   ec0103453c..e946699c3e  version-13-beta-pre-release -> upstream/version-13-beta-pre-release
 * [new tag]               v13.0.0-beta.1              -> v13.0.0-beta.1
$ git reset --hard upstream/develop
HEAD is now at a1ffc44f0c fix: removed unwanted comma from json
$ find . -name "*.pyc" -delete
INFO:bench.app:pulling bench_manager
$ git fetch --all
Fetching upstream
$ git reset --hard upstream/develop
HEAD is now at dbe65b5 Merge pull request #58 from gavindsouza/desk-module
$ find . -name "*.pyc" -delete
INFO:bench.app:pulling doubleledger
$ git fetch --all
Fetching upstream
$ git reset --hard upstream/master
HEAD is now at 9fcc69f custom field updated
$ find . -name "*.pyc" -delete
Updating Python libraries...
$ /home/frappe/frappe-bench/env/bin/pip install -q -U pip
INFO:bench.app:installing frappe
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/frappe
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
INFO:bench.app:installing erpnext
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/erpnext
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
INFO:bench.app:installing bench_manager
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/bench_manager
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
INFO:bench.app:installing doubleledger
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/doubleledger
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
Updating node packages...
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error chalk@4.0.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.4
$ snyk protect
Successfully applied Snyk patches

Done in 2.75s.
Done in 3.84s.
Patching sites...
Migrating bench-manager.local
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for bench_manager : [========================================]
Generating Website Theme Files...
Migrating site1.local
Executing erpnext.patches.v12_0.rename_bank_reconciliation in site1.local (_1bd3e0294da19198)
Success: Done in 0.054s
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Updating DocTypes for doubleledger  : [========================================]
Updating customizations for Address
Updating customizations for Contact
Generating Website Theme Files...
Compiling Python Files...
$ bench build
yarn run v1.22.4
$ FRAPPE_ENV=production node rollup/build.js
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js
(node:4006) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tailwindcss'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at get_rollup_options_for_css (/home/frappe/frappe-bench/apps/frappe/rollup/config.js:120:5)
    at get_rollup_options (/home/frappe/frappe-bench/apps/frappe/rollup/config.js:32:10)
    at Object.keys.map.output_file (/home/frappe/frappe-bench/apps/frappe/rollup/config.js:187:5)
    at Array.map (<anonymous>)
    at get_options_for (/home/frappe/frappe-bench/apps/frappe/rollup/config.js:175:4)
    at build_assets (/home/frappe/frappe-bench/apps/frappe/rollup/build.js:52:18)
    at /home/frappe/frappe-bench/apps/frappe/rollup/build.js:43:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:4006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.23s.
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started

**Comment by muchai** [comment]
This could be environment related errors, will look at them. Wondering if someone has experienced it.
