### ISSUE TITLE
View Chart of Accounts in Setup Wizard

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#21627]
In setup wizard

- choose Germany,
- in step "Your Organization", select "SKR04 with numbers" klick on "View Chart of Accounts"
- open root account "Bilanz - Aktiva"

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-13-f1-2/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-13-f1-2/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-13-f1-2/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-13-f1-2/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-13-f1-2/apps/frappe/frappe/__init__.py", line 1074, in call
    return fn(*args, **newargs)
TypeError: get_coa() missing 1 required positional argument: 'is_root'
```

## Versions

ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)

A.K.A. "Version 13" on frappe.cloud.

**Comment by syncbricks** [comment]
Is there any solution to this?

**Comment by deepeshgarg007** [comment]
![image](https://user-images.githubusercontent.com/42651287/200356450-775dfd4f-2c2b-4e8f-a6b8-1a0434c6a497.png)

Not replicable anymore on develop branch with the available options, closing this issue
