### ISSUE TITLE
Stock Balance Report Not Working

### ISSUE THREAD

**Issue by nayanivijay26** [frappe/erpnext#21628]
Generate new report is not working on Stock Balance Report.
Version Details
ERPNext: v12.7.1 (version-12)
Frappe Framework: v12.5.1 (version-12)

**Comment by szufisher** [comment]
on my v13 develop instance the same problem.

**Comment by szufisher** [comment]
Error log
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 240, in get_prepared_report_result
    data = json.loads(uncompressed_content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Solution:
added this line above the error line

`			uncompressed_content = bytes.decode(uncompressed_content) if type(uncompressed_content) == bytes else uncompressed_content`
`			data = json.loads(uncompressed_content)`

**Comment by nayanivijay26** [comment]
Where you added?
