### ISSUE TITLE
Excel export for Query reports broken

### ISSUE THREAD

**Issue by stacq85** [frappe/erpnext#21630]
The Excel export for Query reports seems to be broken. After pressing the download button with the Excel format selected:

```
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 59, in application
    response = frappe.handler.handle()
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1055, in call
    return fn(*args, **newargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/desk/query_report.py", line 286, in export_query
    custom_columns = frappe.parse_json(data["custom_columns"])
KeyError: 'custom_columns'
```
**Versions:**
Frappe Framework: v12.5.1 (version-12)
ERPNext: v12.7.1 (version-12)

**Comment by tedyswaga** [comment]
Having the same issue
