### ISSUE TITLE
Did not cancel

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21681]
![image](https://user-images.githubusercontent.com/1822868/81542972-225e7700-937e-11ea-81b4-912f1bcfa0fa.png)

This happens when a user is trying to cancel a Journal Entry of type Journal Entry, despite having Cancel rights on the document.

Same User can cancel Journal Entry of type Depreciation Entry.

User can cancel Journal Entry of type Journal Entry if they have System manager Role(an issue currently due to auditor queries)

**Comment by kennethsequeira** [comment]
Check the browser's console for any traceback.

**Comment by kennethsequeira** [comment]
Check the browser's console for any traceback.

**Comment by muchai** [comment]
Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
request.js:355 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 42, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 943, in run_post_save_methods
    self.run_method('on_change')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1064, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1049, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_rule/energy_point_rule.py", line 98, in process_energy_points
    return revert_points_for_cancelled_doc(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_rule/energy_point_rule.py", line 113, in revert_points_for_cancelled_doc
    reference_log.revert(_('Reference document has been cancelled'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_log/energy_point_log.py", line 55, in revert
    frappe.only_for('System Manager')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 553, in only_for
    raise PermissionError
frappe.exceptions.PermissionError

request.js:355 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 56, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1055, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 42, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 943, in run_post_save_methods
    self.run_method('on_change')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1064, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1049, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_rule/energy_point_rule.py", line 98, in process_energy_points
    return revert_points_for_cancelled_doc(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_rule/energy_point_rule.py", line 113, in revert_points_for_cancelled_doc
    reference_log.revert(_('Reference document has been cancelled'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/social/doctype/energy_point_log/energy_point_log.py", line 55, in revert
    frappe.only_for('System Manager')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 553, in only_for
    raise PermissionError
frappe.exceptions.PermissionError

**Comment by muchai** [comment]
Commenting the line that checks for system manager on energy_point_log.py fixes the issue. Needs a better solution though.

**Comment by gavindsouza** [comment]
Fixed in https://github.com/frappe/frappe/pull/10234
