### ISSUE TITLE
v12.8.0 Data Import "In Progress" after succesfull import

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#21717]
## Description of the issue
Data Import "In Progress" after succesfull import

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.8.0 (version-12)
Frappe Framework: v12.5.2 (version-12)
```

### Observed result
Status "In Progress" even after succesfull import.
Can be cancelled and eliminated.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 511, in upload
    data_import_doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 315, in _save
    self.validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 717, in validate_update_after_submit
    self._validate_update_after_submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 621, in _validate_update_after_submit
    frappe.UpdateAfterSubmitError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.UpdateAfterSubmitError: No se permite cambiar Import Status si ya está enviado
```
```
DevTools failed to load SourceMap: Could not load content for https://erp.vivebros.com.mx/assets/js/awesomplete.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by marination** [comment]
I'd suggest you use Data Import Beta
