### ISSUE TITLE
ERPNext Cloud index error on hourly backup

### ISSUE THREAD

**Issue by Mikeduncombe** [frappe/erpnext#21713]
## Description of the issue
An issue is created every hour when ERPNext cloud tries to do its backup.

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
![image](https://user-images.githubusercontent.com/23503359/81804826-af860500-9511-11ea-8c29-ab660d902a0d.png)

```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
frappe.limits.update_space_usage
Error
{'retry': 0, 'log': <function log at 0x3e50230>, 'site': u'yorcardlimited.erpnext.com', 'event': u'hourly', 'method_name': u'frappe.limits.update_space_usage', 'method': <function update_space_usage at 0x3d051b8>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.limits.update_space_usage'}
Traceback (most recent call last):
  File "/home/frappe/benches/bench-10-2019-07-15/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/home/frappe/benches/bench-10-2019-07-15/apps/frappe/frappe/limits.py", line 210, in update_space_usage
    backup_size = get_backup_size(frappe.get_site_path("private", "backups"))
  File "/home/frappe/benches/bench-10-2019-07-15/apps/frappe/frappe/limits.py", line 235, in get_backup_size
    total_size += flt(subprocess.check_output(['du', '-ms', backups[idx]]).split()[0], 2)
IndexError: list index out of range
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
@Mikeduncombe raise a support ticket with the ERPNext team for this.
