### ISSUE TITLE
Tally Migration Error

### ISSUE THREAD

**Issue by nrhdasa** [frappe/erpnext#22035]
Data:
"Processing Master Data"
----------------------------------------------------------------------------------------------------

Exception:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 211, in _process_master_data
    collection = self.get_collection(self.master_data)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 55, in get_collection
    master = bs(sanitize(emptify(content)), "xml")
UnboundLocalError: local variable 'content' referenced before assignment

**Comment by xTrikuta** [comment]
> 

have you compress xml into file-name.xml.zip

**Comment by SatinderpalSingh** [comment]
> > 
> 
> have you compress xml into file-name.xml.zip

This is the solution, @xTrikuta Thanks.
