### ISSUE TITLE
Document for field "discount_percentage_on_rate" attached to child table of "New Sales Invoice Item 1" must be a dict or BaseDocument, not class 'int' (40)

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#22074]
### Reproduce

- Create an **Item**
- Create two **Pricing Rules**: one that sets Discount based on Group and one that sets Price and Margin based on quantity. 
- Create a **Sales Invoice**, add that item and increase the quantity,

### Error
```
Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 69, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1086, in call
    return fn(*args, **newargs)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 167, in apply_pricing_rule
    data = get_pricing_rule_for_item(args_copy, item.get('price_list_rate'), doc=doc)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 194, in get_pricing_rule_for_item
    doc = frappe.get_doc(doc)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 772, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 71, in get_doc
    return controller(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 37, in __init__
    super(SalesInvoice, self).__init__(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 28, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 115, in __init__
    super(Document, self).__init__(kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in __init__
    self.update(d)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 92, in update
    self.set(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 139, in set
    self.extend(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 176, in extend
    self.append(key, v)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 153, in append
    value = self._init_child(value, key)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 192, in _init_child
    value = get_controller(value["doctype"])(value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 115, in __init__
    super(Document, self).__init__(kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in __init__
    self.update(d)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 92, in update
    self.set(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 139, in set
    self.extend(key, value)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 176, in extend
    self.append(key, v)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 170, in append
    self.name, str(type(value))[1:-1], value)
ValueError: Document for field "discount_percentage_on_rate" attached to child table of "New Sales Invoice Item 1" must be a dict or BaseDocument, not class 'int' (40)
```

## Versions

ERPNext: v13.0.0-beta.1 (version-13-beta)
Frappe Framework: v13.0.0-beta.1 (version-13-beta)

**Comment by bhavikpatel7023** [comment]
Getting same error in the below version.

ERPNext: v12.14.0 (version-12)
Frappe Framework: v12.12.0 (version-12)
