### ISSUE TITLE
Error: Executing erpnext.patches.v12_0.move_due_advance_amount_to_pending_amount in test.localhost (_fcadc07dbdbc21db)

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#22225]
## Description of the issue

Failure of patch

## Context information (for bug reports)

**Output of `bench version`**
```
5.0.0
```

## Steps to reproduce the issue

1. install v12
2. create new site
3. migrate to develop

https://travis-ci.org/github/frappe/frappe_docker/builds/697718304#L3501

### Observed result

Failure to execute patch

### Expected result

Successful execution of patch

### Stacktrace / full error message

```
Migrating test.localhost
Executing erpnext.patches.v12_0.move_due_advance_amount_to_pending_amount in test.localhost (_fcadc07dbdbc21db)
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/migrate.py", line 55, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 50, in main
    migrate_sites()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 41, in migrate_sites
    migrate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v12_0/move_due_advance_amount_to_pending_amount.py", line 9, in execute
    frappe.db.sql(''' UPDATE `tabEmployee Advance` SET pending_amount=due_advance_amount ''')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 173, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'pending_amount' in 'field list'")
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

frappe_docker

**Comment by revant** [comment]
@abhishekbalam @Anurag810

**Comment by Anurag810** [comment]
https://github.com/frappe/erpnext/pull/22226

**Comment by revant** [comment]
https://travis-ci.org/github/frappe/frappe_docker/jobs/697966332#L541

**Comment by Anurag810** [comment]
Thanks for update
