### ISSUE TITLE
File Upload Fails Silently

### ISSUE THREAD

**Issue by chlarsen** [frappe/erpnext#22359]
## Description of the issue
Files do not upload, upload fails silently.

## Context information (for bug reports)
FreeBSD 12.1, running via bench start for debugging purposes, PostgreSQL as database.

**Output of `bench version`**
```
erpnext 12.9.4
frappe 12.6.2
```

## Steps to reproduce the issue

1. Login in as Administrator
2. Attach a photo (not a link) to the Settings page, e.g. a profile picture
3. Click on the attached file, to view the uploaded photo: file not found error in both public and private mode

### Observed result
bench start gives:
``````
15:14:03 watch.1          | Rebuilding marketplace.min.js
15:14:06 watch.1          | Rebuilding erpnext.min.js
15:14:08 watch.1          | Rebuilding item-dashboard.min.js
15:14:15 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:15] "POST /api/method/frappe.desk.form.utils.remove_attach HTTP/1.0" 200 -
15:14:15 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:15] "POST /api/method/frappe.desk.form.load.get_docinfo HTTP/1.0" 200 -
15:14:44 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:44] "POST /api/method/upload_file HTTP/1.0" 200 -
15:14:45 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:45] "POST /api/method/frappe.desk.form.load.get_docinfo HTTP/1.0" 200 -

``````
### Expected result
The uploaded photo or file should be displayed or be accessible.,

### Stacktrace / full error message

```
15:14:03 watch.1          | Rebuilding marketplace.min.js
15:14:06 watch.1          | Rebuilding erpnext.min.js
15:14:08 watch.1          | Rebuilding item-dashboard.min.js
15:14:15 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:15] "POST /api/method/frappe.desk.form.utils.remove_attach HTTP/1.0" 200 -
15:14:15 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:15] "POST /api/method/frappe.desk.form.load.get_docinfo HTTP/1.0" 200 -
15:14:44 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:44] "POST /api/method/upload_file HTTP/1.0" 200 -
15:14:45 web.1            | 127.0.1.113 - - [20/Jun/2020 15:14:45] "POST /api/method/frappe.desk.form.load.get_docinfo HTTP/1.0" 200 -

```
No error logged when uploading.
```
15:20:39 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:39] "GET /files/curved_red_arrow_0300x0099px.png HTTP/1.0" 500 -
15:20:39 web.1            | Traceback (most recent call last):
15:20:39 web.1            |   File "/usr/local/frappe_prd/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
15:20:39 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
15:20:39 web.1            |   File "/usr/local/frappe_prd/frappe-bench/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 214, in __call__
15:20:39 web.1            |     real_filename, file_loader = loader(path[len(search_path) :])
15:20:39 web.1            |   File "/usr/local/frappe_prd/frappe-bench/apps/frappe/frappe/middlewares.py", line 25, in loader
15:20:39 web.1            |     raise NotFound
15:20:39 web.1            | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
15:20:39 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:39] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.0" 200 -
15:20:39 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:39] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0" 200 -
15:20:39 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:39] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=style.css HTTP/1.0" 200 -
15:20:39 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:39] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.0" 200 -
15:20:41 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:41] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0" 200 -
15:20:41 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:41] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.0" 200 -
15:20:42 web.1            | 127.0.1.113 - - [20/Jun/2020 15:20:42] "GET /files/curved_red_arrow_0300x0099px.png?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0" 200 -
```
Error when trying to view.
## Additional information
The file is indeed missing from the private or public file folder (depending on upload mode). 
Permissions look fine, and the frappe user can  create a file in those folders.
OS version / distribution, `ERPNext` install method, etc.
FreeBSD 12.1, manual install with mods for FreeBSD (deactivation of cypress, npm install of node-sass, which fails with yarn)

I must be missing sth - any thoughts? Thank you so much!
Chris

**Comment by leonardorame** [comment]
Hi @chlarsen, I also would like to install ERPNext on FreeBSD with Postgresql, could you point me to a tutorial or guide to install on that platform and database?.

Leonardo.

**Comment by dalers** [comment]
Be prepared to forge your own path. There have been posts indicating ERPNext is being used with PostgreSQL, and that ERPNext is being run on FreeBSD, but not without considerable effort and expertise (also the current web UI test framework is not supported on FreeBSD).

However, FreeBSD and PostgreSQL are also my preferred environment, so please post your solution if you are able to solve this.

Cheers,
Dale

**Comment by chlarsen** [comment]
Dear All, 
I got it running, well and fast, under FreeBSD, using different jails for the database, the broker (Redis), a reverse SSL proxy for added security and the Python application itself. Alas, the above file upload issue persisted with PostgreSQL, so that I was force to stick to MariaDB. I am presently swamped with work, but will extra a howto from my installation journals asap. Sorry for the sluggish response. 
Chris

**Comment by leonardorame** [comment]
Thanks @chlarsen, my idea was exactly like yours, separated services running on different jails, also the database and app stored on different ZFS datasets with a different snapshot schedule.

**Comment by chlarsen** [comment]
Sounds like the way to go, indeed. End of this month? I am swamped with COVID-19 work still...

**Comment by leonardorame** [comment]
Yea, no rush. For the current install I created a Bhyve VM with Ubuntu 18.04, but it would be very neat to be able to run it on a FreeBSD jail and also with Postgresql.
