### ISSUE TITLE
patches.v13_0.check_is_income_tax_component Failing

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#22363]
hi @Anurag810 

Patch failing for PR #21990 with below error

```
Executing erpnext.patches.v13_0.check_is_income_tax_component in site1.local (_1bd3e0294da19198)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 265, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/check_is_income_tax_component.py", line 12, in execute
    frappe.db.set_value("Salary Component", "Income Tax", "is_income_tax_component", 1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 660, in set_value
    values, debug=debug)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 158, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'is_income_tax_component' in 'field list'")
```

**Comment by iMoshi** [comment]
It's been bugging me as well.

**Comment by centaur78** [comment]
Hi @iMoshi

> It's been bugging me as well.

You could comment out the patch and do bench update temporarily until this issue is resolved.

**Comment by iMoshi** [comment]
> Hi @iMoshi
> 
> > It's been bugging me as well.
> 
> You could comment out the patch and do bench update temporarily until this issue is resolved.

Ahh gotcha. Just gonna comment out everything inside the check_is_income_tax_component.py and I'll check back in the morning :)

**Comment by centaur78** [comment]
> > Hi @iMoshi
> > > It's been bugging me as well.
> > 
> > 
> > You could comment out the patch and do bench update temporarily until this issue is resolved.
> 
> Ahh gotcha. Just gonna comment out everything inside the check_is_income_tax_component.py and I'll check back in the morning :)

Hi @iMoshi 

Commenting the whole py file is not what i meant.

You can just comment the line in the patch.txt file in the erpnext folder . Its the last line

**Comment by iMoshi** [comment]
> > > Hi @iMoshi
> > > > It's been bugging me as well.
> > > 
> > > 
> > > You could comment out the patch and do bench update temporarily until this issue is resolved.
> > 
> > 
> > Ahh gotcha. Just gonna comment out everything inside the check_is_income_tax_component.py and I'll check back in the morning :)
> 
> Hi @iMoshi
> 
> Commenting the whole py file is not what i meant.
> 
> You can just comment the line in the patch.txt file in the erpnext folder . Its the last line

Oh I did. Then I had to stash the changes, and did bench migrate. So far it's been fine :) thanks for the help.

**Comment by Anurag810** [comment]
sorry, for your inconvenience. the fix has been made.
https://github.com/frappe/erpnext/pull/22371

**Comment by iMoshi** [comment]
> sorry, for your inconvenience. the fix has been made.
> #22371

Thank you guys! Awesome work.
