### ISSUE TITLE
Some dependency ends up importing the deprecated "ConfigParser"

### ISSUE THREAD

**Issue by sezanzeb** [frappe/erpnext#22603]
##  Description of the issue

Running pip install on a clone of the develop branch results in importing the deprecated "ConfigParser" package. It has been renamed to "configparser" at least since 2012 and is deprecated in python3 https://stackoverflow.com/a/14087705.

## Steps to reproduce the issue

1. git clone https://github.com/frappe/erpnext
2. cd erpnext
3. pip3.8 install .

### Observed result

cannot import "ConfigParser"

### Expected result

installation finishes

### Stacktrace / full error message

```
(env) ~/Code/frappe-bench❯ ./env/bin/pip3.8 install ./env/src/erpnext 
Processing ./env/src/erpnext
Processing /home/tobias/.cache/pip/wheels/2e/f3/b8/d5c3baae70c32ffff80142c82ab19b3bb5578633426cea79e5/PyGithub-1.44.1-py3-none-any.whl
Collecting Unidecode==1.1.1
  Using cached Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
Processing /home/tobias/.cache/pip/wheels/16/ab/e5/30b85372e87b3f4720065ec08bcd7b38b2afcfdff71adb6da9/WooCommerce-2.1.1-py3-none-any.whl
Collecting braintree==3.57.1
  Using cached braintree-3.57.1-py2.py3-none-any.whl (127 kB)
Collecting frappe
  Using cached frappe-2.1.4.tar.gz (217 kB)
Processing /home/tobias/.cache/pip/wheels/48/63/a3/73540b58a8b9a01609afa9d753f5d1fea5ee646549f8673ab2/gocardless_pro-1.11.0-py3-none-any.whl
Collecting googlemaps==3.1.1
  Using cached googlemaps-3.1.1-py3-none-any.whl (34 kB)
Collecting pandas==0.24.2
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
Processing /home/tobias/.cache/pip/wheels/d9/19/c5/7c161b8b368f7c65355334c1776ab87e4e225a963ab9f28c97/plaid_python-3.4.0-py3-none-any.whl
Collecting pycountry==19.8.18
  Using cached pycountry-19.8.18.tar.gz (10.0 MB)
Collecting python-stdnum==1.12
  Using cached python_stdnum-1.12-py2.py3-none-any.whl (830 kB)
Collecting taxjar==1.9.0
  Using cached taxjar-1.9.0.tar.gz (11 kB)
Collecting tweepy==3.8.0
  Using cached tweepy-3.8.0-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: six in ./env/lib/python3.8/site-packages (from PyGithub==1.44.1->erpnext==13.0.0.dev0) (1.15.0)
Collecting pyjwt
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting deprecated
  Using cached Deprecated-1.2.10-py2.py3-none-any.whl (8.7 kB)
Collecting requests>=2.14.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Processing /home/tobias/.cache/pip/wheels/57/8e/1c/402cdd15c1f9f7ec20fc63b7bb681cb50f7b09189486619f13/ordereddict-1.1-py3-none-any.whl
Collecting Django==1.7.1
  Using cached Django-1.7.1-py2.py3-none-any.whl (7.4 MB)
Collecting MySQL-python==1.2.5
  Using cached MySQL-python-1.2.5.zip (108 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/tobias/Code/frappe-bench/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bolidpi9/MySQL-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bolidpi9/MySQL-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bolidpi9/MySQL-python/pip-egg-info
         cwd: /tmp/pip-install-bolidpi9/MySQL-python/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bolidpi9/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-install-bolidpi9/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
```

## Additional information

Xubuntu 20.04

**Comment by sezanzeb** [comment]
It's probably because "frappe" in my requirements.txt refers to that other frappe package https://pypi.org/project/frappe/, which is also what causes django to get insatlled...

**Comment by gavindsouza** [comment]
> It's probably because "frappe" in my requirements.txt refers to that other frappe package https://pypi.org/project/frappe/, which is also what causes django to get insatlled...

you're right. the project [frappe on PyPI](https://pypi.org/project/frappe) points to the project [Frappe, a Django application "that provides item recommendations for users"](https://github.com/grafos-ml/frappe) whereas ERPNext is an application built over [the Frappe Framework](https://github.com/frappe/frappe) which you won't find on PyPI. You'll have to set up a Frappe environment by setting up [bench](https://github.com/frappe/bench) to install ERPNext as mentioned in the [README](https://github.com/frappe/erpnext#full-install).
