### ISSUE TITLE
Cannot save or Submit Job Offers since develop lates updates

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#22619]
When I try to save a new Job Offer or try to submit an existing I get the blow error -

![image](https://user-images.githubusercontent.com/11851156/86916219-e7d84700-c140-11ea-8e30-71c990a60a64.png)

Error Message - TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by kennethsequeira** [comment]
@asoral 

Open the browser console and paste the traceback.

**Comment by mwalling** [comment]
Not @asoral , but having similar issue with `None` being passed into the database as a literal. Here's what I get creating a new sales invoice:

```Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 701, in make_sales_invoice
    }, target_doc, postprocess, ignore_permissions=ignore_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 116, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 632, in postprocess
    set_missing_values(source, target)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 640, in set_missing_values
    target.run_method("set_missing_values")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1071, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1054, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 340, in set_missing_values
    super(SalesInvoice, self).set_missing_values(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 56, in set_missing_values
    self.set_missing_lead_customer_details()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 85, in set_missing_lead_customer_details
    party_address=self.customer_address, shipping_address=self.shipping_address_name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 60, in _get_party_details
    billing_address=party_address, shipping_address=shipping_address)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 424, in set_taxes
    return get_tax_template(posting_date, args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/tax_rule/tax_rule.py", line 163, in get_tax_template
    where {0}""".format(" and ".join(conditions)), as_dict = True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1525, "Incorrect DATE value: 'None'")
```
