### ISSUE TITLE
Cannot create new ERPNext site on develop branch: UniqueFieldnameError: Purchase Receipt: Fieldname project appears multiple times in rows 97, 102

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#22687]
```
❯ bench new-site test.localhost --install-app erpnext --force --mariadb-root-password=`cat /tmp/password`
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`


Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%
Set Administrator password: 
Re-enter Administrator password: 

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/revant/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands/site.py", line 44, in new_site
    _new_site(db_name, site, mariadb_root_username=mariadb_root_username,
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands/site.py", line 91, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 86, in install_app
    add_to_installed_apps(name)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 111, in add_to_installed_apps
    post_install(rebuild_website)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 190, in post_install
    init_singles()
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 211, in init_singles
    doc.save()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in save
    return self._save(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 303, in _save
    self.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 953, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/erpnext/erpnext/setup/doctype/global_defaults/global_defaults.py", line 48, in on_update
    self.toggle_in_words()
  File "/home/revant/frappe-bench/apps/erpnext/erpnext/setup/doctype/global_defaults/global_defaults.py", line 74, in toggle_in_words
    make_property_setter(doctype, "in_words", "hidden", self.disable_in_words, "Check")
  File "/home/revant/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 90, in make_property_setter
    property_setter.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 953, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 74, in on_update
    validate_fields_for_doctype(self.doc_type)
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 650, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 946, in validate_fields
    check_unique_fieldname(meta.get("name"), d.fieldname)
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 684, in check_unique_fieldname
    frappe.throw(_("{0}: Fieldname {1} appears multiple times in rows {2}").format(docname, fieldname, ", ".join(duplicates)), UniqueFieldnameError)
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 396, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 375, in msgprint
    _raise_exception()
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 326, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.UniqueFieldnameError: Purchase Receipt: Fieldname project appears multiple times in rows 97, 102
```

Found here: https://travis-ci.com/github/frappe/frappe_docker/builds/175582960#L3105

**Comment by sjain17** [comment]
I am also facing the same while bench update
