### ISSUE TITLE
[Bug]: Payment Reconciliation for Credit Notes of Non-Default Company

### ISSUE THREAD

**Issue by manan-ft** [frappe/erpnext#22834]
## Description of the issue
Payment Reconciliation [Accounts>Match Payments with Invoices] for Credit Notes creates a Journal Entry on Successful Reconciliation.
In this Journal Entry, the company is considered as the Default company, therefore if any other company is used in Payment Reconciliation, an Error is thrown "Journal Entry ACC-JV-2020-01200: Account Debtors - D does not belong to Company Default Company" 

**Output of `bench version`**
```
erpnext 12.4.0
frappe 12.2.0
```

## Steps to reproduce the issue

1. Create a Credit Note (Sales invoice with Is Return selected) for a Company that is not set as Default, let us call it Dummy Company and Customer= Customer Name. On submission of this Credit Note, a negative outstanding is created [Debit Balance is Creditors a/c]
2. To knock off this Credit Note Debit Balance against the Credit Balance of the Customer, Open Accounts>Match Payments with Invoices
3. In Payment Reconciliation, select the Company for which Reconciliation is to be done (Dummy Company), Party Type = Customer, Party = Customer Name, Get Unreconciled Entries with the Button
4. This will populate the Credit Note with Amount and Unpaid invoices in the Invoices table, match the Payments [Credit Note in this case] with any Invoice number from the Drop down and Click on `Reconcile`

### Observed result
A validation error is thrown 'Journal Entry ACC-JV-2020-01200: Account Debtors - D does not belong to Company Default Company'

### Expected result
A Journal Entry should be created for Dummy Company which knocks off the Debit Balance of Credit Note with Credit Balance of selected Invoice as it does in case of Credit Notes for Default Company

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 89, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 46, in runserverobj
    r = doc.run_method(method, args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 167, in reconcile
    reconcile_dr_cr_note(dr_or_cr_notes)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 291, in reconcile_dr_cr_note
    jv.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 272, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 922, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 49, in on_submit
    self.make_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 522, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 24, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 128, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 144, in make_entry
    gle.run_method("on_update_with_args", adv_adj, update_outstanding, from_repost)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 40, in on_update_with_args
    self.validate_account_details(adv_adj)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 127, in validate_account_details
    .format(self.voucher_type, self.voucher_no, self.account, self.company))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 364, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 350, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Journal Entry ACC-JV-2020-01200: Account Debtors - D does not belong to Company Default Company
```

## Additional information

Self hosted ERPNext

## Possible Solution
Pass Company parameter in the JV posting function
https://github.com/frappe/erpnext/blob/fd30b8f42285cc673e7b622df6274690008dec6b/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py#L264

**Comment by deepeshgarg007** [comment]
@manan-ft
These fixes are already merged in the latest develop branch. Will be backported shortly in version-12-branches
https://github.com/frappe/erpnext/pull/22601
https://github.com/frappe/erpnext/pull/22738
