### ISSUE TITLE
Urgent - Cannot save purchase invoice

### ISSUE THREAD

**Issue by Nofal-Mami** [frappe/erpnext#22924]
## Description of the issue
Under Buying settings I have enabled "Allow Item to be added multiple times in a transaction" also enabled under selling settings, but when I enter multiple lines in purchase invoice using same item code system throw error Item_code_2 must be unique
## Context information (for bug reports)
item is not stockable, service item, item code is used not naming series.
**Output of `bench version`**
Installed Apps
ERPNext: v12.10.1 (version-12)
Erpnext Custom: v0.0.1 (master)
Frappe Framework: v12.8.1 (version-12)
## Steps to reproduce the issue

1.Create service item and give an item code, do not use naming series.
2.enable buying settings "Allow Item to be added multiple times in a transaction"
3.enter new purchase invoice, add first line with item code for ex:60100000, then add second line and use same item code, save
4.error message displayed

### Observed result
cannot save purchase invoic and error message displayed, item_code_2 must be unique
### Expected result
system should accept multi lines with same item code and save purchase invoice
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 364, in db_update
    ), list(d.values()) + [name])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '60100000' for key 'item_code_2'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in _save
    self.update_children()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 351, in update_children
    self.update_child_table(df.fieldname, df)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 360, in update_child_table
    d.db_update()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 367, in db_update
    self.show_unique_validation_message(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 389, in show_unique_validation_message
    raise frappe.UniqueValidationError(self.doctype, self.name, e)
frappe.exceptions.UniqueValidationError: ('Purchase Invoice Item', '0512bc4ead', IntegrityError(1062, "Duplicate entry '60100000' for key 'item_code_2'"))
request.js:355:14
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 364, in db_update
    ), list(d.values()) + [name])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '60100000' for key 'item_code_2'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in _save
    self.update_children()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 351, in update_children
    self.update_child_table(df.fieldname, df)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 360, in update_child_table
    d.db_update()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 367, in db_update
    self.show_unique_validation_message(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 389, in show_unique_validation_message
    raise frappe.UniqueValidationError(self.doctype, self.name, e)
frappe.exceptions.UniqueValidationError: ('Purchase Invoice Item', '0512bc4ead', IntegrityError(1062, "Duplicate entry '60100000' for key 'item_code_2'"))
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Ubuntu 18.04
install methode manual

Please note this is production instance, I need solution ASAP if you can.

Thx
Nofal

**Comment by bhavesh95863** [comment]
I think **item_code_2**  is your custom field and you set as unique in the property of that field. 

Solution is set unique=0 for that field.

**Comment by Nofal-Mami** [comment]
I did not added item_code_2 custom field, but it shows as constarint in the table.

**Comment by Nofal-Mami** [comment]
resolved
