### ISSUE TITLE
node-sass package not installed on docker image for version-12

### ISSUE THREAD

**Issue by jordanparker-me** [frappe/erpnext#23194]
## Description of the issue
node-sass package not installed on docker image for version-12

## Context information (for bug reports)
Cannot update Theme due to lack of node-sass

**Output of `bench version`**
version-12

## Steps to reproduce the issue

1. Follow set up for local install of single-behch docker
2. Try to change theme

### Observed result
Error msg in UI

### Expected result
Changed theme

### Stacktrace / full error message

```
internal/modules/cjs/loader.js:968
throw err;
^

Error: Cannot find module 'node-sass'
Require stack:
- /home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js'
]
}
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by fdiazdelcastillo** [comment]
Same issu in my installation

**Comment by fdiazdelcastillo** [comment]
same issue in my installation

**Comment by fdiazdelcastillo** [comment]
Any information about this?
