### ISSUE TITLE
Version-13 Payroll Issue 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#23204]
We Can't generate Payroll as well we can't disable cost center as mandatory  field.
![image](https://user-images.githubusercontent.com/12432802/91630578-1b19b280-e9db-11ea-9030-a38654697215.png)

Error Log.

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 270, in make_accrual_jv_entry
    journal_entry.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 897, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 886, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 333, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 963, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 827, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1102, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 821, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 50, in on_submit
    self.make_gl_entries()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 539, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj, update_outstanding=update_outstanding)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 24, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 131, in save_entries
    make_entry(entry, adv_adj, update_outstanding)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 143, in make_entry
    gle.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 926, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 827, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1102, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 821, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 31, in validate
    self.validate_cost_center()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 140, in validate_cost_center
    be used in transactions""").format(self.voucher_type, self.voucher_no, frappe.bold(self.cost_center)))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 396, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 375, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 326, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Journal Entry ACC-JV-2020-00034: Cost Center <b>7072 - Operation Dep. - HT</b> is a group cost center and group cost centers cannot
				be used in transactions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 100, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 527, in submit_salary_slips_for_employees
    payroll_entry.make_accrual_jv_entry()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 274, in make_accrual_jv_entry
    frappe.msgprint(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 370, in msgprint
    message_log.append(json.dumps(out))
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValidationError' is not JSON serializable

![Untitled-Project (1)](https://user-images.githubusercontent.com/12432802/91630618-692eb600-e9db-11ea-8347-0c15005a0f2c.gif)

Please Support very urgent.

**Comment by sammish** [comment]
There is no issue , that was is group cost center issue.   We can't assign the group cost center to employee.

Thanks.
