### ISSUE TITLE
Subscription error: erpnext.accounts.doctype.subscription.subscription.process_all

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#23240]
Please find below errors from the error list:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/subscription/subscription.py", line 463, in process_all
    subscriptions = get_all_subscriptions()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/subscription/subscription.py", line 474, in get_all_subscriptions
    as_dict=1
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'status' in 'where clause'")

**Comment by HaniTetouha** [comment]
facing the same issue on version 13.21

**Comment by Helkyd** [comment]
Hi.
I see this error is still OPEN and until now for V12 not fixed and i see that is still happening on V13.21.

A feedback would be great.
