### ISSUE TITLE
Can't use "Add to Holidays" button in Holiday List

### ISSUE THREAD

**Issue by TrumanCF01512** [frappe/erpnext#23294]
Hello,

"Add to Holidays" button doesn't work
![image](https://user-images.githubusercontent.com/68537754/92449920-f0063e80-f1e4-11ea-8669-55f4780618f5.png)

Thanks,
Best Regards.

**Comment by kennethsequeira** [comment]
Either click on **Report** or open the browser's console and paste the full traceback.

**Comment by buff0k** [comment]
Probably not the same issue, but I get "Not Permitted" error when I try to add weekly off to Holiday List, Console output as follows:

Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
desk.min.js?ver=1617298333.0:1 Traceback (most recent call last):
  File "/home/bench/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/bench/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 73, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1165, in call
    return fn(*args, **newargs)
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 234, in run_doc_method
    is_whitelisted(fn)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 584, in is_whitelisted
    throw(_("Not permitted"), PermissionError)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 423, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 402, in msgprint
    _raise_exception()
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: Not permitted

DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://erpnext.hrcity.co.za/assets/js/socket.io.slim.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://erpnext.hrcity.co.za/assets/js/desk.min.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for https://erpnext.hrcity.co.za/assets/js/form.min.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for https://erpnext.hrcity.co.za/assets/js/control.min.js.map: Load canceled due to load timeout
libs.min.js?ver=1617298333.0:231 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://erpnext.hrcity.co.za/assets/js/libs.min.js?ver=1617298333.0:231:3368)
    at va (https://erpnext.hrcity.co.za/assets/js/libs.min.js?ver=1617298333.0:231:21539)
    at Sa (https://erpnext.hrcity.co.za/assets/js/libs.min.js?ver=1617298333.0:231:22250)
    at c (https://erpnext.hrcity.co.za/assets/js/libs.min.js?ver=1617298333.0:231:935)
    at Function.R [as tz] (https://erpnext.hrcity.co.za/assets/js/libs.min.js?ver=1617298333.0:234:3771)
    at Object.convert_to_user_tz (https://erpnext.hrcity.co.za/assets/js/desk.min.js?ver=1617298333.0:1:278415)
    at prettyDate (https://erpnext.hrcity.co.za/assets/js/desk.min.js?ver=1617298333.0:1:101779)
    at HTMLSpanElement.<anonymous> (https://erpnext.hrcity.co.za/assets/js/desk.min.js?ver=1617298333.0:1:202407)
    at Function.each (https://erpnext.hrcity.co.za/assets/frappe/js/lib/jquery/jquery.min.js:2:2861)
    at n.fn.init.each (https://erpnext.hrcity.co.za/assets/frappe/js/lib/jquery/jquery.min.js:2:845)
w @ libs.min.js?ver=1617298333.0:231
(anonymous) @ libs.min.js?ver=1617298333.0:231
va @ libs.min.js?ver=1617298333.0:231
Sa @ libs.min.js?ver=1617298333.0:231
c @ libs.min.js?ver=1617298333.0:231
R @ libs.min.js?ver=1617298333.0:234
convert_to_user_tz @ desk.min.js?ver=1617298333.0:1
prettyDate @ desk.min.js?ver=1617298333.0:1
(anonymous) @ desk.min.js?ver=1617298333.0:1
each @ jquery.min.js:2
each @ jquery.min.js:2
frappe.datetime.refresh_when @ desk.min.js?ver=1617298333.0:1
(anonymous) @ desk.min.js?ver=1617298333.0:1
jquery.min.js:4 POST https://erpnext.hrcity.co.za/api/method/run_doc_method 403 (FORBIDDEN)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1617298333.0:1
frappe.call @ desk.min.js?ver=1617298333.0:1
run_server_script @ control.min.js?ver=1617298333.0:1
onclick @ control.min.js?ver=1617298333.0:1
(anonymous) @ control.min.js?ver=1617298333.0:1
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
desk.min.js?ver=1617298333.0:1 Traceback (most recent call last):
  File "/home/bench/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/bench/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 73, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1165, in call
    return fn(*args, **newargs)
  File "/home/bench/frappe-bench/apps/frappe/frappe/handler.py", line 234, in run_doc_method
    is_whitelisted(fn)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 584, in is_whitelisted
    throw(_("Not permitted"), PermissionError)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 423, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 402, in msgprint
    _raise_exception()
  File "/home/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: Not permitted

**Comment by ruchamahabal** [comment]
This issue doesn't persist anymore.
