### ISSUE TITLE
Print UOM after quantity error

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#23303]
hi @rohitwaghchaure and @Semiranis 

Just got this error. I am unable to print the invoice after this PR #23263

![image](https://user-images.githubusercontent.com/1904802/92455469-c217fe80-f1d2-11ea-82fa-12b078687e2b.png)

With the below Traceback

```
Failed to load resource: the server responded with a status of 417 (EXPECTATION FAILED)
desk.min.js?ver=1599460231.0:3822 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 69, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1094, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/printview.py", line 188, in get_html_and_style
    html = get_rendered_template(doc, name=name, print_format=print_format, meta=meta,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/printview.py", line 159, in get_rendered_template
    html = template.render(args, filters={"len": len})
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/print_formats/standard.html", line 30, in top-level template code
    <div class="col-xs-{{ (12 / section.columns|len)|int }} column-break">
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/print_formats/standard_macros.html", line 3, in template
    {{ render_table(df, doc) }}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/print_formats/standard_macros.html", line 47, in template
    {% endfor %}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/print_formats/standard_macros.html", line 99, in template
    {%- if df.fieldtype=="Code" %}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./templates/print_formats/includes/item_table_qty.html", line 1, in top-level template code
    {% set qty_first=frappe.db.get_single_value("Print Settings", "print_uom_after_quantity") %}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 572, in get_single_value
    frappe.throw(_('Invalid field name: {0}').format(frappe.bold(fieldname)), self.InvalidColumnName)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 405, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 384, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 332, in _raise_exception
    raise raise_exception(msg)
frappe.database.database.Database.InvalidColumnName: Invalid field name: <b>print_uom_after_quantity</b>
```

_Originally posted by @centaur78 in https://github.com/frappe/erpnext/pull/23263#issuecomment-688726811_

**Comment by Semiranis** [comment]
This field is created automatically after installation of erpnext. You can add it manually in Print Settings to remove this error.

**Comment by centaur78** [comment]
> This field is created automatically after installation of erpnext. You can add it manually in Print Settings to remove this error.

Hi @Semiranis 

Thanks I have done it. It works now.
