### ISSUE TITLE
Datetime field default value "now" in Web Form throws InternalError: Incorrect datetime value: 'Now'

### ISSUE THREAD

**Issue by ceefour** [frappe/erpnext#23413]
## Description of the issue

Datetime field default value "now" in Web Form throws InternalError: Incorrect datetime value: 'Now'

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.3
frappe 13.0.0-beta.3
lovia 0.0.1
```

## Steps to reproduce the issue

1. Create a Doctype with Datetime field, set default value to "now"
2. Confirm that creating a document using Desk UI is working fine
3. Create a Web Form that uses that Doctype and that field
4. Open the Web Form and submit

### Observed result

Error (see stacktrace below)

### Expected result

Submits correctly and field filled as current date and time.

### Stacktrace / full error message

```
jquery.min.js:4 POST http://localhost:8000/ 500 (INTERNAL SERVER ERROR)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
call @ website.js:63
save @ web_form.js:126
(anonymous) @ web_form.js:77
website.js:160 Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 69, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1085, in call
    return fn(*args, **newargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 411, in accept
    doc.insert(ignore_permissions = True, ignore_mandatory = ignore_mandatory)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 246, in insert
    self.db_insert()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 328, in db_insert
    ), list(d.values()))
  File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 158, in sql
    self._cursor.execute(query, values)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1292, "Incorrect datetime value: 'Now' for column `_6235bf2a8f2af0bd`.`tabTalent`.`source_date` at row 1")
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

* Ubuntu 20.04.1
* Docker

**Comment by ankush** [comment]
IIRC this was Fixed a while back. Can't reproduce anymore.

**Comment by LeoKogan** [comment]
Default Value 'Now' is throwing a 'Date Invalid date must be in format: yyyy-mm-dd' message on ERPNEXT 14 cloud based
