### ISSUE TITLE
Uncaught Server Exception

### ISSUE THREAD

**Issue by himanshunandan** [frappe/erpnext#23555]
Hi,

I have installed latest ERNext vrsion on ubuntu 18.04 yesterday. It was working fine yesterday but today it's throwing below error.

Kindly help here
Uncaught Server Exception
Traceback (most recent call last):
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 273, in parse_extends
    node = nodes.Extends(lineno=next(self.stream).lineno)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 739, in tokeniter
    name, filename)
jinja2.exceptions.TemplateSyntaxError: unexpected char '“' at 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/website/render.py", line 218, in build_page
    html = frappe.render_template(context.source, context)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 82, in render_template
    throw(title="Jinja Template Error", msg="<pre>{template}</pre><pre>{tb}</pre>".format(template=template, tb=get_traceback()))
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <pre>{% extends “templates/web.html” %}
{% extends "templates/web.html" %}

{% block style %}
<style>
	{% include "templates/includes/login/login.css" %}
</style>
{% endblock %}

{% block page_content %}

<div style='min-height: 360px'>
	<noscript>
		<div class="text-center my-5">
			<h4>{{ _("Javascript is disabled on your browser") }}</h4>
			<p class="text-muted">{{ _("You need to enable JavaScript for your app to work.") }}<br>{{ _("To enable it follow the instructions in the following link: {0}").format("<a href='https://enable-javascript.com/'>enable-javascript.com</a></p>") }}
		</div>
	</noscript>
<section class='for-login'>
	<div class="login-content page-card" style="margin-top: 30px;">
		<form class="form-signin form-login" role="form">
			<div class="page-card-head">
				<span class="indicator blue" data-text="{{ _('Login') }}"></span>
			</div>

			<input type="text" id="login_email"
				class="form-control"
				placeholder="{% if login_name_placeholder %}{{ login_name_placeholder  }}{% else %}{{ _('Email Address') }}{% endif %}"
				required autofocus>

			<div class="password-field" style="position: relative;">
				<input type="password" id="login_password"
						class="form-control" placeholder="{{ _('Password') }}" required>

				<span toggle="#login_password" class="fa fa-fw fa-eye toggle-password text-muted"></span>
			</div>

			<button class="btn btn-sm btn-primary btn-block btn-login" type="submit">
				{{ _("Login") }}</button>

			{% if ldap_settings and ldap_settings.enabled %}
			<button class="btn btn-sm btn-default btn-block btn-login btn-ldap-login">
				{{ _("Login with LDAP") }}</button>
			{% endif %}
		</form>
	</div>
	<div class='form-footer'>

			<div class='social-logins'>
			{%- if social_login -%}
				<h6>{{ _("Or login with") }}</h6>

				<p class="text-center" style="margin-top: 15px">
				{% for provider in provider_logins %}
					<a href="{{ provider.auth_url }}"
						class="btn btn-default btn-sm btn-social btn-{{ provider.name }}">
							{{ provider.icon }} {{ provider.provider_name }}</a>
				{% endfor %}
				</p>
			{%- endif -%}
			</div>

	{%- if not disable_signup -%}
		<p class="text-center sign-up-message">
			<a href="#signup" style="margin-top: -2px;">{{ _("Don't have an account? Sign up") }}</a>
		</p>
	{%- endif -%}
	<p class="text-center forgot-password-message">
		<a href="#forgot">{{ _("Forgot Password?") }}</a></p>
	</div>
</section>
<section class='for-signup {{ "signup-disabled" if disable_signup else "" }}'>
	<div class="login-content page-card" style="margin-top: 20px;">
	{%- if not disable_signup -%}
		<form class="form-signin form-signup hide" role="form">
			<div class="page-card-head">
				<span class="indicator blue" data-text="{{ _('Sign Up') }}"></span>
			</div>
			<input type="text" id="signup_fullname"
				class="form-control" placeholder="{{ _('Full Name') }}" required autofocus>
			<input type="email" id="signup_email"
				class="form-control" placeholder="{{ _('Email Address') }}" required>
			<button class="btn btn-sm btn-primary btn-block btn-signup" type="submit">{{ _("Sign up") }}</button>
		</form>
	{%- else -%}
		<div class='page-card-head'>
			<span class='indicator darkgrey'>{{_("Signup Disabled")}}</span>
		</div>
		<p>{{_("Signups have been disabled for this website.")}}</p>
		<div><a href='/' class='btn btn-primary btn-sm'>{{ _("Home") }}</a></div>
	{%- endif -%}
	</div>
	<div class='form-footer'>
		<a href="#login" class="blue">{{ _("Have an account? Login") }}</a>
	</div>

</section>

<section class='for-forgot'>
	<div class="login-content page-card" style="margin-top: 20px;">
	<form class="form-signin form-forgot hide" role="form">
		<div class="page-card-head">
			<span class="indicator blue" data-text="{{ _('Forgot Password') }}"></span></div>
		<input type="email" id="forgot_email"
			class="form-control" placeholder="{{ _('Email Address') }}" required autofocus>
		<button class="btn btn-sm btn-primary btn-block btn-forgot" type="submit">{{ _("Reset Password") }}</button>
	</form>
	</div>
	<div class='form-footer'>
		<a href="#login">{{ _("Back to Login") }}</a>
	</div>
</section>
</div>
{% endblock %}

{% block script %}
	<script>{% include "templates/includes/login/login.js" %}</script>
{% endblock %}

{% block sidebar %}{% endblock %}
</pre><pre>Traceback (most recent call last):
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/parser.py", line 273, in parse_extends
    node = nodes.Extends(lineno=next(self.stream).lineno)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/home/erpuser/frappe-bench/env/lib/python3.6/site-packages/jinja2/lexer.py", line 739, in tokeniter
    name, filename)
jinja2.exceptions.TemplateSyntaxError: unexpected char '“' at 11
</pre>
Your email address...
Powered by ERPNext - ERP Software for Education

**Comment by himanshunandan** [comment]
this is resolved. thanks.
