### ISSUE TITLE
migration error v12 to develop: Executing execute:frappe.delete_doc_if_exists("Report", "Loan Repayment")

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#23701]
```
Executing execute:frappe.delete_doc_if_exists("Report", "Loan Repayment") in test.localhost (_fcadc07dbdbc21db)
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 64, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 58, in main
    migrate_sites(maintenance_mode=True)
  File "/home/frappe/frappe-bench/commands/migrate.py", line 35, in migrate_sites
    migrate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 89, in execute_patch
    exec(patchmodule.split("execute:")[1],globals())
  File "<string>", line 1, in <module>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 842, in delete_doc_if_exists
    delete_doc(doctype, name, force=force)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 837, in delete_doc
    ignore_permissions, flags, ignore_on_trash, ignore_missing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 94, in delete_doc
    doc.run_method("on_trash")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1099, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 825, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 53, in on_trash
    frappe.throw(_("You are not allowed to delete Standard Report"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 413, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 392, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 340, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: You are not allowed to delete Standard Report
```

1. Create a fresh v12 erpnext site
2. Migrate to develop branch

found here: https://travis-ci.com/github/frappe/frappe_docker/jobs/403203438#L739

**Comment by iMoshi** [comment]
Not just this, but:

Executing execute:frappe.delete_doc_if_exists('Dashboard', 'Accounts')
Executing execute:frappe.delete_doc("Report", "Department Analytics")
Executing erpnext.patches.v13_0.delete_old_purchase_reports in
Executing erpnext.patches.v13_0.delete_old_sales_reports
Executing erpnext.patches.v13_0.rename_issue_doctype_fields

All of the above are failing to execute.

**Comment by revant** [comment]
This got resolved for docker travis.

@iMoshi
I'll close this issue about the specific patch.
You can create issues for other patches that are failing for you.

**Comment by revant** [comment]
Closing

re-open if needed.
