### ISSUE TITLE
v13-beta5 POS: Mode of Payment invalid for Company

### ISSUE THREAD

**Issue by kevinpthorne** [frappe/erpnext#23872]
## Description of the issue

The POS page complains that the default Mode of Payment set is invalid:
![image](https://user-images.githubusercontent.com/8848627/98611503-46f4c680-22af-11eb-94b7-9b8509636a34.png)
even though the Mode of Payment config looks correct:
![image](https://user-images.githubusercontent.com/8848627/98611608-73a8de00-22af-11eb-8a65-f544a422a4d5.png)

## Context information (for bug reports)

My config has more than 1 company setup. The POS Profile company matches the one in the Mode of Payment page.

**Output of `bench version`**
```
erpnext 13.0.0-beta.5
frappe 13.0.0-beta.6
```

## Steps to reproduce the issue

1. Create Mode of Payment configuration for Company X (e.g. set Credit Card account for Company X to "CC - Company X")
2. Create POS Profile under Company X with Credit Card as default Mode of Payment
3. Open POS with POS Profile previously created

### Observed result
Error that disabled the entire desk interface that requires a page refresh.
### Expected result
Usable POS
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1107, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 101, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 46, in runserverobj
    r = doc.run_method(method, args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1099, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 825, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 319, in set_missing_values
    profile = self.set_pos_fields(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 267, in set_pos_fields
    update_multi_mode_option(self, profile)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1635, in update_multi_mode_option
    frappe.throw(msg.format(", ".join(invalid_modes)), title=_("Missing Account"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 409, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 388, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 342, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please set default Cash or Bank account in Mode of Payments <a href="https://example.org/desk#Form/Mode%20of%20Payment/Credit%20Card">Credit Card</a>
```

## Additional information

Running the query from `sales_invoice.get_mode_of_payment_info()` manually produces the results expected:
![image](https://user-images.githubusercontent.com/8848627/98612166-cd5dd800-22b0-11eb-94f2-3e7865465125.png)

I cannot seem to get the `pos_profile` variable nor the `pos_payment_method` printed anymore for viewing.

**Comment by nextchamp-saqib** [comment]
Can you try printing `doc.company` just before `payment_mode = get_mode_of_payment_info(pos_payment_method.mode_of_payment, doc.company)` gets executed?

Also which company is set as default company in Global Defaults?

**Comment by kevinpthorne** [comment]
I am having a really hard time trying to get `doc.company` or anything printed out... keep in mind this only is affecting my production installation as well.

[This workaround was successful.](https://discuss.erpnext.com/t/feature-erpnext-v13-new-point-of-sale-beta-testing/61093/140?u=kevinpthorne)
