### ISSUE TITLE
[version-13] AttributeError: 'NoneType' object has no attribute 'fieldtype'

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#23893]
## Description of the issue
Submitting a new Quotation or Invoice, with tax applied, cannot save it. Saving without tax applied, it works.
`AttributeError: 'NoneType' object has no attribute 'fieldtype'`

**Output of `bench version`**
```
erpnext 13.0.0-beta.5
frappe 13.0.0-beta.6
```
## Additional information
Ubuntu 20.04 server
ERPNext manual installation

**Comment by ghost** [comment]
```
Traceback (most recent call last):
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/__init__.py", line 1107, in call
    return fn(*args, **newargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 320, in _save
    self.run_before_save_methods()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 930, in run_before_save_methods
    self.run_method("validate")
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 1099, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 825, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 26, in validate
    super(Quotation, self).validate()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 40, in validate
    super(SellingController, self).validate()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate
    super(StockController, self).validate()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 78, in validate
    self.calculate_taxes_and_totals()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 181, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 17, in __init__
    self.calculate()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 34, in calculate
    self.set_item_wise_tax_breakup()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 633, in set_item_wise_tax_breakup
    self.doc.other_charges_calculation = get_itemised_tax_breakup_html(self.doc)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 673, in get_itemised_tax_breakup_html
    update_itemised_tax_data(doc)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/regional/italy/utils.py", line 25, in update_itemised_tax_data
    row.tax_rate = flt(tax_rate, row.precision("tax_rate"))
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/base_document.py", line 786, in precision
    if df.fieldtype in ("Currency", "Float", "Percent"):
AttributeError: 'NoneType' object has no attribute 'fieldtype'
```

**Comment by ghost** [comment]
I tried changing company country from Italy to another country (France) and is now possible to apply tax on quotation, invoice, sale order.
Changing again the company country back to Italy, I get the following error:
>A field with the name 'company_tax_id' already exists in doctype Sales Invoice.
>Failed to setup defaults for country Italy. Please contact support@erpnext.com


The following error log also display on clean new installation, choosing Italy as company country during setup wizard.
```
Traceback (most recent call last):
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 443, in install_country_fixtures
    frappe.get_attr(module_name)(company_doc, False)
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/regional/italy/setup.py", line 14, in setup
    make_custom_fields()
  File "/home/cyberd3vil/frappe-bench/apps/erpnext/erpnext/regional/italy/setup.py", line 188, in make_custom_fields
    create_custom_fields(custom_fields, ignore_validate = frappe.flags.in_patch, update=update)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 151, in create_custom_fields
    create_custom_field(doctype, df, ignore_validate=ignore_validate)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 135, in create_custom_field
    custom_field.insert()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in insert
    self.run_method("before_insert")
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 1099, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/model/document.py", line 825, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 40, in before_insert
    frappe.throw(_("A field with the name '{}' already exists in doctype {}.").format(self.fieldname, self.dt))
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/__init__.py", line 409, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/__init__.py", line 388, in msgprint
    _raise_exception()
  File "/home/cyberd3vil/frappe-bench/apps/frappe/frappe/__init__.py", line 342, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'company_tax_id' already exists in doctype Sales Invoice.
```

**Comment by shahedsherkat** [comment]
In my case:
Company name was on UAE. Changing it to India solved the issue!

Is any fix expected for this?

**Comment by shahedsherkat** [comment]
Hello Frappe team, 

many resolution for this?
Changing the country to India solved this issue temporarily but now I encounter below error when try to post a purchase invoice

https://discuss.erpnext.com/t/v12-pymysql-err-internalerror-1054-unknown-column-gst-category-in-field-list/58146

Please let me know how to overcome this issue.

Thank you for your support in advance.

Bests, 
Shahed

**Comment by arudra123** [comment]
'NoneType' object has no attribute 'payment_terms'" - i get this error while creating a sales invoice via API
