### ISSUE TITLE
Payroll Entry - ValueError - too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#24047]
Hi @Anurag810 

I am unable to submit the Salary slip after updating to this PR #23173 .

![salary_slip error](https://user-images.githubusercontent.com/1904802/100969187-20dbe280-354c-11eb-93ea-e64de0a4ac10.jpg)

Below is the traceback

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1112, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 918, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 907, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 984, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1133, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 842, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 25, in on_submit
    self.create_salary_slips()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 147, in create_salary_slips
    create_salary_slips_for_employees(emp_list, args, publish_progress=False)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 536, in create_salary_slips_for_employees
    ss.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 947, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 848, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1133, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 842, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 47, in validate
    self.get_emp_and_working_day_details()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 143, in get_emp_and_working_day_details
    payroll_based_on, consider_unmarked_attendance_as = frappe.db.get_value("Payroll Settings", None, ["payroll_based_on","consider_unmarked_attendance_as"])
ValueError: too many values to unpack (expected 2)
```

**Comment by Anurag810** [comment]
@centaur78 thanks for reporting we will push fixes on priority.

**Comment by Anurag810** [comment]
@centaur78 I tried to replicate the issue locally but it is working fine for me.

**Comment by centaur78** [comment]
> @centaur78 I tried to replicate the issue locally but it is working fine for me.

Hi @Anurag810 

I am on the develop branch.

I just did
bench update --reset
bench clear-cache
bench restart

Still the same issue as soon as I click "Get Salary Slip"

![salary_slip error 2](https://user-images.githubusercontent.com/1904802/100974742-3fdf7200-3556-11eb-934f-860612907b95.jpg)

Prior to the PR #23173, it was working without this issue. Not sure if any other connected PR is causing this ??

**Comment by centaur78** [comment]
Hi @Anurag810 

Now going through the changed code of the PR... It looks like there is something called Payroll Settings which needs to be set.

Strange couldn't find it anywhere in the settings menu or other places. Had to do a search to find.

Finally after setting the details below. I am able to submit the salary slip. 

![payroll_settings](https://user-images.githubusercontent.com/1904802/101337680-64f51d00-3895-11eb-9e61-84ed574e06b4.jpg)

It would really nice if you guys can mentioned in the Documentation /Manual regarding this

Closing issue.
