### ISSUE TITLE
LMS feature broken in beta13

### ISSUE THREAD

**Issue by deantheiceman** [frappe/erpnext#24144]
## Description of the issue

LMS programs return code server 500, error log below:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 62, in top-level template code
    <span class="indicator blue">{{_('Start')}}</span>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 66, in top-level template code
    {{ banner_html or "" }}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 77, in block "content"
    {{ card(course) }}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 55, in template
    {% if has_access and progress[course.name] %}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'progress' is undefined
```

## Context information (for bug reports)

**Output of `bench version`**
```
v13beta6
```

## Steps to reproduce the issue

1. Go to erpnext/lms
2. Click on program

### Stacktrace / full error message

See above

## Additional information

Kubernetes release

**Comment by deantheiceman** [comment]
This happens when logging in with a user

**Comment by fderyckel** [comment]
Yes, it works for me as administrator and as a student.  What type of user?  I am on V13
ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.x.x-develop () (develop)

Could you give more details on how to reproduce the error as I am not managing to get it.

**Comment by alibeep** [comment]
Hey there! I get the same problem when selecting the program in which the student is enrolled after logging in using a student account.
@fderyckel 
![problem 1](https://user-images.githubusercontent.com/77193800/104090030-604ccb80-527c-11eb-89e7-67274c3c6d7e.JPG)

Kindly note that I am on a free trial plan with ERPNext

**Comment by federicocalvo** [comment]
Hi, to this day it remains the same.

This happend when login a user and enrollment in the course.

ERPNext: v13.0.0-dev (rebrand-ui)
Frappe Framework: v13.0.0-dev (rebrand-ui)
Frappe Framework: v0.0.1 (master)

```
Traceback (most recent call last):
  File "/home/erp/erpnext/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/erp/erpnext/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/erp/erpnext/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/erp/erpnext/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/erp/erpnext/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/erp/erpnext/apps/erpnext/erpnext/./www/lms/program.html", line 62, in top-level template code
    <span class="indicator blue">{{_('Start')}}</span>
  File "/home/erp/erpnext/apps/frappe/frappe/./templates/base.html", line 66, in top-level template code
    {{ banner_html or "" }}
  File "/home/erp/erpnext/apps/erpnext/erpnext/./www/lms/program.html", line 77, in block "content"
    {{ card(course) }}
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/erp/erpnext/apps/erpnext/erpnext/./www/lms/program.html", line 55, in template
    {% if has_access and progress[course.name] %}
  File "/home/erp/erpnext/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'progress' is undefined
```

**Comment by federicocalvo** [comment]
Update as of today. LMS still does not working.

ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.x.x-develop () (develop)

`Traceback (most recent call last):
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/diamo/Frappe/apps/erpnext/erpnext/./www/lms/index.html", line 4, in top-level template code
    {% from "www/lms/macros/card.html" import null_card %}
  File "/home/diamo/Frappe/apps/frappe/frappe/./templates/base.html", line 81, in top-level template code
    {% block content %}
  File "/home/diamo/Frappe/apps/erpnext/erpnext/./www/lms/index.html", line 54, in block "content"
    {% for program in featured_programs %}
TypeError: 'NoneType' object is not iterable`

**Comment by chipohameja** [comment]
Is there a fix for this because I'm also getting the same error here:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 62, in top-level template code
    <span class="indicator blue">{{_('Start')}}</span>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 66, in top-level template code
    {{ banner_html or "" }}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 77, in block "content"
    {{ card(course) }}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/program.html", line 55, in template
    {% if has_access and progress[course.name] %}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'progress' is undefined

**Comment by amecreate** [comment]
https://github.com/frappe/erpnext/pull/24828 didn’t fix the jinja2.exceptions.UndefinedError: 'progress' is undefined 
Administrator or system manager can view LMS 
Regular user get the Uncaught Server Exception with roles Education Manager, Instructor, LMS User, Student and Website Manager
