### ISSUE TITLE
Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by avaiskhatri** [frappe/erpnext#24195]
@nabinhait 

erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs

{'retry': 0, 'kwargs': {}, 'is_async': True, 'method_name': 'erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs', 'job_name': 'erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs', 'user': 'Administrator', 'method': <function rename_gle_sle_docs at 0x7f7eb1437730>, 'log': <function log at 0x7f7eb1d7ed90>, 'site': 'erp.duraprints.pk', 'event': 'hourly'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 287, in rename_gle_sle_docs
    rename_temporarily_named_docs(doctype)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 296, in rename_temporarily_named_docs
    frappe.db.sql("""UPDATE `tab{}` SET name = %s, to_rename = 0 where name = %s""".format(doctype), (newname, oldname))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

**Comment by Himanshu-Gurjar** [comment]
Any update on this ?

**Comment by codefazt** [comment]
someone find a solution for this error ?
