### ISSUE TITLE
Offsite backup fails

### ISSUE THREAD

**Issue by deantheiceman** [frappe/erpnext#24219]
<!--
Welcome to ERPNext issue tracker! Before creating an issue, please heed the following:

1. This tracker should only be used to report bugs and request features / enhancements to ERPNext
## Description of the issue

Backup fails to offsite location such as Google drive

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/rq/worker.py", line 975, in perform_job
    rv = job.perform()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/rq/job.py", line 696, in perform
    self._result = self._execute()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/rq/job.py", line 719, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 100, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/google_drive/google_drive.py", line 187, in upload_system_backup_to_google_drive
    validate_file_size()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/offsite_backup_utils.py", line 88, in validate_file_size
    file_size = get_file_size(latest_file, unit="GB")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/offsite_backup_utils.py", line 74, in get_file_size
    file_size = os.path.getsize(file_path)
  File "/opt/bitnami/python/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Seems to be the same as this issue https://discuss.erpnext.com/t/backup-error-typeerror-stat-path-should-be-string-bytes-os-pathlike-or-integer-not-nonetype/66473

I'm using v13-beta6, however the backup was always working daily until a few days ago

**Comment by carstenblt** [comment]
Same here. Started after there was a DNS error recently with my S3 storage and backups failed a couple of days. It believe it can't find the "most recent backup".

**Comment by deantheiceman** [comment]
I've tried deleting the old backup, and deleting the backup settings still no luck.

Shouldn't this trigger a failed notifcation too? seems like a serious issue since backups are failing silently now

**Comment by ankiteciitkgp** [comment]
I am also facing a similar issue. I have setup ERPNext using docker on ec2 and have configured backups using s3. 

Initially, I was receiving the same error message specified but for the last 2 days, I am receiving emails stating that backup is successful but I don't see any object in my bucket.

![Screenshot from 2021-01-03 19-06-12](https://user-images.githubusercontent.com/5340524/103479917-e5f0f700-4df6-11eb-8a36-82f6c9116e32.png)

![Screenshot from 2021-01-03 19-05-49](https://user-images.githubusercontent.com/5340524/103479923-eee1c880-4df6-11eb-8c4f-6f6afdbdac4d.png)

**Comment by deantheiceman** [comment]
@nabinhait @karthikeyan5 @Vigneshsekar
Please consider this issue.

**Comment by carstenblt** [comment]
I got notifications about failed backups at least.

I am not sure what I did to solve it. I changed the number of backups in the system settings and then manually downloaded a backup. After that the S3 backup started working again...

**Comment by deantheiceman** [comment]
what did you change the number of backups to?

**Comment by deantheiceman** [comment]
@carstenblt where did you change these settings?

**Comment by deantheiceman** [comment]
bump anyone?

**Comment by carstenblt** [comment]
@deantheiceman It's really just called "System Settings", there you can set the number of backups. Then there is "backups", from which you can trigger a manual backup. It will send you an email with a download link when it's finished. I guess that's most likely the step that might have fixed it.

Nonetheless, this really is a bug and should be addressed.

**Comment by Nikhil13x** [comment]
> @deantheiceman It's really just called "System Settings", there you can set the number of backups. Then there is "backups", from which you can trigger a manual backup. It will send you an email with a download link when it's finished. I guess that's most likely the step that might have fixed it.
> 
> Nonetheless, this really is a bug and should be addressed.

Yes .. this workaround fixed my issue.. thank you @carstenblt

**Comment by hackedunit** [comment]
It seems to have magically started working after I took a **first** **manual** backup using the following commands:

```
docker run --rm -e "SITES=example.com" -e "WITH_FILES=1" -v example_sites-vol:/home/frappe/frappe-bench/sites --network frappe-network frappe/erpnext-worker:v12.18.0 backup
```

```
docker run --rm -e "BUCKET_NAME=example" -e "REGION=eu-west-3" -e "ACCESS_KEY_ID=key" -e "SECRET_ACCESS_KEY=key" -e "ENDPOINT_URL=https://example/" -e "BUCKET_DIR=frappe-backups" -v example_sites-vol:/home/frappe/frappe-bench/sites --network frappe-network frappe/erpnext-worker:v12.18.0 push-backup
```

Now both Google Drive and S3 Automatic backups are working (from the UI). I'm running erpnext v12.18.0 on docker with swarm.

**Comment by revant** [comment]
Whoever is using docker refer this: https://github.com/frappe/frappe_docker/wiki/Backup-and-Push-to-cloud-Swarm-Cron-job

**Comment by joshuarestivo** [comment]
What about those using docker in the context of kubernetes? Is there a ready answer for this issue?

**Comment by revant** [comment]
> What about those using docker in the context of kubernetes? Is there a ready answer for this issue?

setup a Kubernetes `CronJob`, refer this https://helm.erpnext.com/kubernetes-resources/create-backup-and-push-to-cloud-cronjob
