### ISSUE TITLE
AttributeError: 'DocTypeLink' object has no attribute 'hidden' when creating new Import.

### ISSUE THREAD

**Issue by martinhbramwell** [frappe/erpnext#24235]
## Description of the issue

When attempting to create a new importation, two drop down list fields are shown: "Document Type" and "Import Type".
A moment or two after the "Document Type" drop down opens the following alert is thrown ... 

```AttributeError: 'DocTypeLink' object has no attribute 'hidden'```

... and the list disappears.

It is possible to quickly paste a correct DocType name to stop the error occurring, however incorrect names do not stop the error and are immediately erased.

## Context information (for bug reports)

**Output of `bench version`**
```
erpdev@loso:~/frappe-bench-DLS$ bench version
erpnext 13.0.0-beta.7
frappe 13.0.0-beta.9
erpdev@loso:~/frappe-bench-DLS$ 
```

## Steps to reproduce the issue

1. Attempt to start a data importation
2.
3.

### Observed result

Not possible to select from drop down list.  It appears for a moment with a few items but then disappears.

### Expected result

Can choose a DocType from a drop down list.

### Stacktrace / full error message

Trace from: ```~/frappe-bench-DLS/logs/frappe.log```

```
2020-12-29 09:11:49,331 ERROR frappe New Exception collected with id: 2020-12-29 09:11:49.206693-67.193.35.107-5ed
Site: dev.erpnext.host
Form Dict: {'doctype': 'DocType', 'with_parent': '1', 'cached_timestamp': '', 'cmd': 'frappe.desk.form.load.getdoctype'}

```

Trace from: ```~/frappe-bench-DLS/logs/web.log```

```
Traceback (most recent call last):
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/__init__.py", line 1113, in call
    return fn(*args, **newargs)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/meta.py", line 54, in load_assets
    self.load_dashboard()
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/desk/form/meta.py", line 199, in load_dashboard
    self.set('__dashboard', self.get_dashboard_data())
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/model/meta.py", line 469, in get_dashboard_data
    self.add_doctype_links(data)
  File "/home/erpdev/frappe-bench-DLS/apps/frappe/frappe/model/meta.py", line 491, in add_doctype_links
    if link.hidden:
AttributeError: 'DocTypeLink' object has no attribute 'hidden'
```

## Additional information

```
erpdev@loso:~/frappe-bench-DLS$ bench version
erpnext 13.0.0-beta.7
frappe 13.0.0-beta.9
erpdev@loso:~/frappe-bench-DLS$
```

**Comment by martinhbramwell** [comment]
I have been unable to repeat this issue, so I suspect I did internal damage myself.
