### ISSUE TITLE
AttributeError: 'StockEntry' object has no attribute 'set_incoming_rate'

### ISSUE THREAD

**Issue by martinhbramwell** [frappe/erpnext#24277]
## Description of the issue

Cannot create Stock Entry from Pick List

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.7
frappe 13.0.0-beta.9
```

## Steps to reproduce the issue

1.  Attempt to create a Work Order from as Pick List
2.
3.

### Observed result

Error thrown

### Expected result

A draft Stock Entry

### Stacktrace / full error message

```
17:58:04 web.1            | Traceback (most recent call last):
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/frappe/frappe/app.py", line 64, in application
17:58:04 web.1            |     response = frappe.api.handle()
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/frappe/frappe/api.py", line 58, in handle
17:58:04 web.1            |     return frappe.handler.handle()
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/frappe/frappe/handler.py", line 30, in handle
17:58:04 web.1            |     data = execute_cmd(cmd)
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/frappe/frappe/handler.py", line 70, in execute_cmd
17:58:04 web.1            |     return frappe.call(method, **frappe.form_dict)
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/frappe/frappe/__init__.py", line 1113, in call
17:58:04 web.1            |     return fn(*args, **newargs)
17:58:04 web.1            |   File "/home/erpdev/frappe-bench-DENH/apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 381, in create_stock_entry
17:58:04 web.1            |     stock_entry.set_incoming_rate()
17:58:04 web.1            | AttributeError: 'StockEntry' object has no attribute 'set_incoming_rate'
```

**Output of `grep -RC 3 set_incoming_rate`**
```shell
erpnext/controllers/selling_controller.py-		self.set_customer_address()
erpnext/controllers/selling_controller.py-		self.validate_for_duplicate_items()
erpnext/controllers/selling_controller.py-		self.validate_target_warehouse()
erpnext/controllers/selling_controller.py:		self.set_incoming_rate()
erpnext/controllers/selling_controller.py-
erpnext/controllers/selling_controller.py-	def set_missing_values(self, for_validate=False):
erpnext/controllers/selling_controller.py-
--
erpnext/controllers/selling_controller.py-
erpnext/controllers/selling_controller.py-				sales_order.update_reserved_qty(so_item_rows)
erpnext/controllers/selling_controller.py-
erpnext/controllers/selling_controller.py:	def set_incoming_rate(self):
erpnext/controllers/selling_controller.py-		if self.doctype not in ("Delivery Note", "Sales Invoice"):
erpnext/controllers/selling_controller.py-			return
erpnext/controllers/selling_controller.py-
--
erpnext/stock/doctype/pick_list/pick_list.py-	else:
erpnext/stock/doctype/pick_list/pick_list.py-		stock_entry = update_stock_entry_items_with_no_reference(pick_list, stock_entry)
erpnext/stock/doctype/pick_list/pick_list.py-
erpnext/stock/doctype/pick_list/pick_list.py:	stock_entry.set_incoming_rate()
erpnext/stock/doctype/pick_list/pick_list.py-	stock_entry.set_actual_qty()
erpnext/stock/doctype/pick_list/pick_list.py-	stock_entry.calculate_rate_and_amount(update_finished_item_rate=False)
erpnext/stock/doctype/pick_list/pick_list.py-
```

**Stock Entry has no such method as set_incoming_rate()**

## Additional information

OS version / distribution, `ERPNext` install method, etc.
**Output of `lsb_release -a`**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by asoral** [comment]
I am also getting the same error
