### ISSUE TITLE
TypeError: assign_salary_structure() got an unexpected keyword argument 'company'

### ISSUE THREAD

**Issue by kingraphaii** [frappe/erpnext#24428]
## Description
When assigning a salary structure to employees from the Salary Structure Page, after selecting filters (company, grade, department etc), the following error pops up:

```python
TypeError: assign_salary_structure() got an unexpected keyword argument 'company'
```

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.x.x-develop () (develop)
```

## Steps to reproduce the issue

1. Create salary structure (add components etc)
2. Goto Salary Structure detail page
3. Click on "Assign to Employees"
4. On the modal that pops up, select grade for example
5. Set dates and base, variable
6. Click on "Assign" when done

### Observed result
A Server Error alert pops up with the message: `assign_salary_structure() got an unexpected keyword argument 'company'`

### Expected result
Expecting a successfull salary structure assignment to employees that match the selected filters (grade, department etc).

### Stacktrace / full error message

```
Traceback (most recent call last):
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/app.py", line 67, in application
12:44:55 web.1            |     response = frappe.api.handle()
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/api.py", line 58, in handle
12:44:55 web.1            |     return frappe.handler.handle()
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 30, in handle
12:44:55 web.1            |     data = execute_cmd(cmd)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 70, in execute_cmd
12:44:55 web.1            |     return frappe.call(method, **frappe.form_dict)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 1133, in call
12:44:55 web.1            |     return fn(*args, **newargs)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/handler.py", line 101, in runserverobj
12:44:55 web.1            |     frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/desk/form/run_method.py", line 49, in runserverobj
12:44:55 web.1            |     r = doc.run_method(method, **args)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 848, in run_method
12:44:55 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1135, in composer
12:44:55 web.1            |     return composed(self, method, *args, **kwargs)
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 1118, in runner
12:44:55 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
12:44:55 web.1            |   File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 842, in <lambda>
12:44:55 web.1            |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
12:44:55 web.1            | TypeError: assign_salary_structure() got an unexpected keyword argument 'company'
```

## Additional information
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by pateljannat** [comment]
https://github.com/frappe/erpnext/pull/24798 will resolve this issue

**Comment by kingraphaii** [comment]
Tested the change on my instance. Error does go away, but there is another issue. I've added a comment to your PR.
