### ISSUE TITLE
Unable to send support email

### ISSUE THREAD

**Issue by Davincible** [frappe/erpnext#24677]
## Description of the issue
When an error occurs, and I click report, the email doesn't send with a nonetype error

## Context information (for bug reports)

**Output of `bench version`**
```
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

erpnext 13.x.x-develop
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/utils/background_jobs.py", line 100, in execute_job
    method(**kwargs)
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/core/doctype/communication/email.py", line 457, in sendmail
    communication._notify(print_html=print_html, print_format=print_format, attachments=attachments,
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/core/doctype/communication/communication.py", line 211, in _notify
    _notify(self, print_html, print_format, attachments, recipients, cc, bcc)
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/core/doctype/communication/email.py", line 147, in _notify
    prepare_to_notify(doc, print_html, print_format, attachments)
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/core/doctype/communication/email.py", line 229, in prepare_to_notify
    set_incoming_outgoing_accounts(doc)
  File "/webapps/next.doroart.nl/frappe-bench-latest/apps/frappe/frappe/core/doctype/communication/email.py", line 289, in set_incoming_outgoing_accounts
    doc.db_set("email_account", doc.outgoing_email_account.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by cptnpopcorn** [comment]
I have exactly the same error, having set up everything related to mail (domain, email account, linked email account to user).
tracked in [this issue](https://github.com/frappe/frappe/issues/13365#issue-904810629)

@Davincible Have you solved this? Since you closed the issue after 4 days?

**Comment by Davincible** [comment]
@cptnpopcorn I suppose I did, but can't remember to be honest. I'm sorry
