### ISSUE TITLE
Unable to cancel Payment Entry - after allocating invoices but deleting before submissions

### ISSUE THREAD

**Issue by shreyanshj** [frappe/erpnext#24958]
## Environment:
frappe.cloud
Installed Apps
ERPNext: v12.18.0 (HEAD)
Frappe Framework: v12.15.0 (HEAD)

## Description of the issue
On creating a Payment Entry, unable to cancel. UI reports following error:

"Did not cancel"
Because of another error beneath:
"TypeError: object of type 'NoneType' has no len()"

## Steps to reproduce the issue

1. Create a Payment Entry
2. Pull invoices to allocate to - such that complete payment amount is allocated. None of the invoices has tax information/applicable.
3. Save
4. Before submitting, remove all entries of allocated invoices.
5. Submit

### Observed result
UI Reports two error overlapping each other:
First being "Did not cancel"
Second, hidden behind first "TypeError: object of type 'NoneType' has no len()"

### Expected result
Payment entry should have been cancelled

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 872, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 862, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 903, in run_before_save_methods
    self.run_method("before_cancel")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 118, in before_cancel
    validate_einvoice_fields(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/india/e_invoice/utils.py", line 26, in validate_einvoice_fields
    no_taxes_applied = len(doc.get('taxes', [])) == 0
TypeError: object of type 'NoneType' has no len()
```

**Comment by pateljannat** [comment]
Fixed https://github.com/frappe/erpnext/pull/24616
