### ISSUE TITLE
Error when opening the report for DATEV, user needs access rights for the DocType DocType

### ISSUE THREAD

**Issue by Mutantpenguin** [frappe/erpnext#24959]
## Description of the issue
Users can not open the DATEV report. Would need rights to access the DocType DocType (no typo here, I really mean DocType).

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.18.0
frappe 12.15.0
```

## Steps to reproduce the issue

1. Create a user with the role Accounts Manager or Accounts User and log in
2. open the DATEV report
3. select a date range where you are sure to see anything (test this with a user with the role System Manager first)

### Observed result
Error message:
![image](https://user-images.githubusercontent.com/9027507/111799179-119a5e00-88cb-11eb-93e2-e1da4a52cbfd.png)

I checked in the code that this is not a typo by it really means the DocType DocType.

### Expected result
A working DATEV report.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 536, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 205, in run
    result = generate_report_result(report, filters, user, custom_columns)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    result = get_filtered_data(report.ref_doctype, columns, result, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 474, in get_filtered_data
    match_filters_per_doctype = get_user_match_filters(linked_doctypes, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 635, in get_user_match_filters
    filter_list = frappe.desk.reportview.build_match_conditions(dt, user, False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 375, in build_match_conditions
    match_conditions =  DatabaseQuery(doctype, user=user).build_match_conditions(as_condition=as_condition)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 556, in build_match_conditions
    frappe.throw(_("No permission to read {0}").format(self.doctype), frappe.PermissionError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: No permission to read DocType
```

## Additional information

OS version / distribution: Ubuntu 18.04
`ERPNext` install method: easy installer

**Comment by Mutantpenguin** [comment]
Still the same problem with version 13:
```
erpnext 13.7.0
frappe 13.7.0
```
