### ISSUE TITLE
Error Using Easy Install Sript

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#24962]
Hi ,

I started encountering the error below again while trying to use the Easy Install script

```
Traceback (most recent call last):
  File "install.py", line 498, in <module>
    install_bench(args)
  File "install.py", line 279, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 414, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.
```

This was fixed with a PR a while ago but seems to be back now! Pls help fix urgently

OS: Ubuntu 18.04

Thanks

**Comment by Olawale1** [comment]
https://discuss.erpnext.com/t/error-using-easy-install-script/72836

**Comment by Olawale1** [comment]
Going through the logs, it seems the installation fails at the point below:

```
TASK [mariadb : include_tasks] *************************************************
task path: /tmp/.bench/bench/playbooks/roles/mariadb/tasks/main.yml:69
fatal: [localhost]: FAILED! => {
    "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to be in '/tmp/.bench/bench/playbooks/roles/mariadb/tasks/mysql_secure_installation.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set root Password\n  ^ here\n"
}
```
