### ISSUE TITLE
Issue when upgrading from ERPNext v12.2.0 to v12.17.0

### ISSUE THREAD

**Issue by neelbhanushali** [frappe/erpnext#24968]
## Description of the issue
Upgrading from frappe [v12.0.19](https://github.com/frappe/frappe/releases/tag/v12.0.19) to [v12.14.0](https://github.com/frappe/frappe/releases/tag/v12.14.0) [This does not matter]
Upgrading from erpnext [v12.2.0](https://github.com/frappe/erpnext/releases/tag/v12.2.0) to [v12.17.0](https://github.com/frappe/erpnext/releases/tag/v12.17.0)
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.2.0
frappe 12.0.19
```

## Steps to reproduce the issue

1. Checkout commit of the version you want to upgrade to in frappe/erpnext repositories
2. bench migrate

### Observed result
Patch `erpnext.patches.v11_0.add_permissions_in_gst_settings #2020-04-04` fails

### Expected result
All patches should execute

### Stacktrace / full error message

```
Executing erpnext.patches.v11_0.add_permissions_in_gst_settings #2020-04-04 in site1.local (_DBNAME)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 286, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v11_0/add_permissions_in_gst_settings.py", line 11, in execute
    add_permissions()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 81, in add_permissions
    add_permission(doctype, 'All', 0)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 494, in add_permission
    validate_permissions_for_doctype(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 992, in validate_permissions_for_doctype
    doctype = frappe.get_doc("DocType", doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 762, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 71, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType E Invoice Settings not found
```

OS version / distribution, `ERPNext` install method, etc.
`easy install`

**Comment by neelbhanushali** [comment]
`add_permissions` from the patch file was failing

>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v11_0/add_permissions_in_gst_settings.py", line 11, in execute
>     add_permissions()
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 81, in add_permissions
>     add_permission(doctype, 'All', 0)

I performed following steps to make it work
* Removed `E Invoice Settings` from `add_permissions` method `doctype` tuple variable [[ref]](https://github.com/frappe/erpnext/blob/version-12/erpnext/regional/india/setup.py#L80)
* run `bench migrate` command which executed successfully 
* removed the changes made to [apps/erpnext/erpnext/regional/india/setup.py](https://github.com/frappe/erpnext/blob/version-12/erpnext/regional/india/setup.py#L80)
* To make sure permissions for Doctype `E Invoice Settings` were updated properly, executed following in `bench console`
```python
from frappe.permissions import add_permission, update_permission_property
doctype = 'E Invoice Settings'
add_permission(doctype, 'All', 0)
for role in ('Accounts Manager', 'Accounts User', 'System Manager'):
	add_permission(doctype, role, 0)
	update_permission_property(doctype, role, 0, 'write', 1)
	update_permission_property(doctype, role, 0, 'create', 1)
frappe.db.commit()
```

To check whether this worked properly, I checked permissions for `E Invoice Settings` in `Role Permissions Manager` and I could see 4 entries which correspond to statements executed in `bench console` 
![screencapture-erp-atriina-desk-2021-03-22-12_26_20](https://user-images.githubusercontent.com/29022906/111951767-19941100-8b0a-11eb-891c-597d73c4f037.png)

Queries:
1. Is this the correct way to do this until this is fixed?
2. When can this be fixed?

**Comment by neelbhanushali** [comment]
@rmehta @nabinhait 

two issues similar to this one
