### ISSUE TITLE
Administrator cannot submit Salary Slip

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#25197]
Hi all

Just did a bench update .. I am unable to submit the Salary slip with a message "Not permitted.".. Even when logged in as the Administrator, getting the below error and traceback

![salary_slip_error](https://user-images.githubusercontent.com/1904802/113545794-e23e5d80-95fb-11eb-84d0-65018cc9c02f.jpg)

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1165, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 229, in run_doc_method
    is_whitelisted(fn)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 584, in is_whitelisted
    throw(_("Not permitted"), PermissionError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 423, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 402, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: Not permitted
```

Looks like the api 'run_doc_method' is also Forbidden as shown.

![image](https://user-images.githubusercontent.com/1904802/113546206-9e982380-95fc-11eb-98a2-e7362bdf138a.png)

**Comment by centaur78** [comment]
Hi @sagarvora 

Could this run_doc_method 403 be caused [from this frappe PR 12720](https://github.com/frappe/frappe/pull/12720).

Even the Administrator cannot submit the doc ?

**Comment by sagarvora** [comment]
Is this a custom method you wrote? Any method accessible from the frontend needs to be whitelisted.

**Comment by centaur78** [comment]
Nope.. I am running the develop branch as is... no customization, no custom methods.. 

I just created a Payroll Entry and when I am trying to submit the Salary Slip ... I am getting the Permission error along with the 403 for the run_doc_method... when i running this as the Administrator.

**Comment by sagarvora** [comment]
I have found the issue. Will be fixed soon. Thanks for reporting!
