### ISSUE TITLE
frappe.exceptions.LinkValidationError on upgrade from v12 to v13

### ISSUE THREAD

**Issue by ZhakCoding** [frappe/erpnext#25211]
Output of bench --site site migrate: (Ubuntu 20.04)

```
Migrating 51.178.39.164
Executing erpnext.patches.v13_0.setup_patient_history_settings_for_standard_doctypes in 51.178.39.164 (_6ed5bfe12a184b93)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/sergio/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sergio/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/commands/site.py", line 297, in migrate
    migrate(
  File "/home/sergio/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/sergio/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/sergio/frappe-bench/apps/erpnext/erpnext/patches/v13_0/setup_patient_history_settings_for_standard_doctypes.py", line 13, in execute
    setup_patient_history_settings()
  File "/home/sergio/frappe-bench/apps/erpnext/erpnext/healthcare/setup.py", line 229, in setup_patient_history_settings
    settings.save()
  File "/home/sergio/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/model/document.py", line 318, in _save
    self._validate_links()
  File "/home/sergio/frappe-bench/apps/frappe/frappe/model/document.py", line 815, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg),
  File "/home/sergio/frappe-bench/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/sergio/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/sergio/frappe-bench/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #4: Document Type: Therapy Session, Row #6: Document Type: Inpatient Medication Order

```

### Things tried ###

bench --site site console
frappe.reload_doc('accounts', 'doctype','therapy_session')
`/frappe-bench/apps/erpnext/erpnext/accounts/doctype/therapy_session/therapy_session.json missing`
frappe.reload_doc('accounts', 'doctype','impatient_medication_order')
`/frappe-bench/apps/erpnext/erpnext/accounts/doctype/impatient_medication_order/impatient_medication_order.json missing
`

**Comment by ammarfrahm** [comment]
Fixed by running the following function in the bench site console:
```
frappe.reload_doc('healthcare', 'doctype','therapy_session')
frappe.reload_doc('healthcare', 'doctype','inpatient_medication_order')
```
