### ISSUE TITLE
Upgrade to v13(India) is broken during patches step - setup_fields_for_80g_certificate_and_donation

### ISSUE THREAD

**Issue by Nikhil13x** [frappe/erpnext#25214]
Executing erpnext.patches.v13_0.setup_fields_for_80g_certificate_and_donation in erp.4csolutions.in (4cs)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 300, in migrate
    skip_search_index=skip_search_index
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/erpnext/erpnext/patches/v13_0/setup_fields_for_80g_certificate_and_donation.py", line 9, in execute
    make_custom_fields()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 617, in make_custom_fields
    create_custom_fields(custom_fields, update=update)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 158, in create_custom_fields
    custom_field.save()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 336, in _save
    self.run_post_save_methods()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 982, in run_post_save_methods
    self.run_method("on_update")
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 69, in on_update
    validate_fields_for_doctype(self.dt)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 686, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 990, in validate_fields
    check_illegal_default(d)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 784, in check_illegal_default
    frappe.throw(_("Default value for {0} must be in the list of options.").format(frappe.bold(d.fieldname)))
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/mujeerhashmi/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Default value for <b>naming_series</b> must be in the list of options.

**Comment by gsarunk** [comment]
I do face this error. I run a multisite. Couple of sites went through. Couple stuck with this error.

**Comment by mujeerhashmi** [comment]
@nabinhait @saurabh6790 This issue is also faced by few people and wanted your much-deserved attention to it.

**Comment by mujeerhashmi** [comment]
Any updates here??

**Comment by nrhdasa** [comment]
You can please do the following to resolve this issue.
Open **Naming Series** in your current ERPNext v12:
1. Select Doctype Purchase Invoice.
2. In the series section replace 'PINV-YYYY-.' with 'PINV-YY-.' and keep it on top or default.
3. Similarly in Sales Invoice replace 'SINV-YYYY-.' with 'SINV-YY-.' and keep it on top or default.

Then you may upgrade, it should work.

**Comment by mujeerhashmi** [comment]
> Open **Naming Series** in your current ERPNext v12:

My v12 is not accessible anymore. Is there a possibility of changing this from backend?

**Comment by mujeerhashmi** [comment]
Ok. I could finally manage to get through it.
```
bench mariadb
update `tabProperty Setter` set value='SINV-.YY.-' where name="Sales Invoice-naming_series-default";
update `tabProperty Setter` set value='PINV-.YY.-' where name="Purchase Invoice-naming_series-default";
```

**Comment by sagarvora** [comment]
This seems to be fixed here: https://github.com/frappe/erpnext/pull/25220
Please close the issue if solved.
