### ISSUE TITLE
[V13] startup problem

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#25253]
v13
ubuntu 18
easy install script
upgrade to v13:
![image](https://user-images.githubusercontent.com/18129232/114092055-b0b0e500-98ce-11eb-8c14-aa85e723eab1.png)

all was succesful.

bench start
problem!?

![image](https://user-images.githubusercontent.com/18129232/114092647-611ee900-98cf-11eb-842a-acd815cdb2ea.png)

complete error txt:

AttributeError
AttributeError: 'WebsiteSettings' object has no attribute 'hide_login'

Traceback (most recent call last)
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
init_request(request)
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 130, in init_request
raise frappe.SessionStopped('Session Stopped')
During handling of the above exception, another exception occurred:
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
data = render_page_by_language(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
return render_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
return build(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
return build_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
context = get_context(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
context = build_context(context)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 81, in build_context
context.update(get_website_settings(context))
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 159, in get_website_settings
context["hide_login"] = settings.hide_login
During handling of the above exception, another exception occurred:
File "/home/parsa/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
return super(StaticDataMiddleware, self).__call__(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
resp = f(*args[:-2] + (request,))
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 85, in application
response = frappe.utils.response.handle_session_stopped()
File "/home/parsa/frappe-bench/apps/frappe/frappe/utils/response.py", line 223, in handle_session_stopped
return frappe.website.render.render("message", http_status_code=503)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 79, in render
data = render_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
return build(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
return build_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
context = get_context(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
context = build_context(context)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 81, in build_context
context.update(get_website_settings(context))
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 159, in get_website_settings
context["hide_login"] = settings.hide_login
AttributeError: 'WebsiteSettings' object has no attribute 'hide_login'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by j209** [comment]
COMPLETE ERROR TXT:

AttributeError
AttributeError: 'WebsiteSettings' object has no attribute 'hide_login'

Traceback (most recent call last)
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
init_request(request)
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 130, in init_request
raise frappe.SessionStopped('Session Stopped')
During handling of the above exception, another exception occurred:
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
data = render_page_by_language(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
return render_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
return build(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
return build_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
context = get_context(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
context = build_context(context)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 81, in build_context
context.update(get_website_settings(context))
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 159, in get_website_settings
context["hide_login"] = settings.hide_login
During handling of the above exception, another exception occurred:
File "/home/parsa/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
return super(StaticDataMiddleware, self).__call__(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/local.py", line 231, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/home/parsa/frappe-bench/env/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
resp = f(*args[:-2] + (request,))
File "/home/parsa/frappe-bench/apps/frappe/frappe/app.py", line 85, in application
response = frappe.utils.response.handle_session_stopped()
File "/home/parsa/frappe-bench/apps/frappe/frappe/utils/response.py", line 223, in handle_session_stopped
return frappe.website.render.render("message", http_status_code=503)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 79, in render
data = render_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
return build(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
return build_page(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
context = get_context(path)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
context = build_context(context)
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/context.py", line 81, in build_context
context.update(get_website_settings(context))
File "/home/parsa/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 159, in get_website_settings
context["hide_login"] = settings.hide_login
AttributeError: 'WebsiteSettings' object has no attribute 'hide_login'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by j209** [comment]
Solved!

**Comment by jeewan2015** [comment]
@j209 
how ?
