### ISSUE TITLE
ERPNext v12 -> v13 Migration: Unable to delete or cancel report because it is linked

### ISSUE THREAD

**Issue by shreyanshj** [frappe/erpnext#25319]
## Description of the issue
- Attempting to update from v12 (erpnext.com copy) to v13 using the following commands:
```
bench switch-to-branch version-13 frappe erpnext --upgrade
bench update --patch
```
But it reports error when attempting to patch:
`erpnext.patches.v13_0.delete_old_purchase_reports`

Stating:
```
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Report <a href="/app/Form/Report/Purchase Order Items To Be Received or Billed">Purchase Order Items To Be Received or Billed</a> is linked with Prepared Report <a href="/app/Form/Prepared Report/REP00666">REP00666</a>
```
## Context information (for bug reports)
Attempting to migrate an existing v12 (updated, erpnext.com version of DB) to v13 (released branch)

**Output of `bench version`**
```
frappe@agf-erpnext001:~/frappe-bench$ bench version
erpnext 13.0.1
frappe 13.0.2
frappe@agf-erpnext001:~/frappe-bench$
```

## Steps to reproduce the issue
I am not sure if it would have some recurrence (because others have apparently been able to successfully upgrade). But, this is what I did
1. Download backup from erpnext.com onto Ubuntu 18.04.3 LTS
2. `bench update`
3. `bench switch-to-branch version-13 frappe erpnext --upgrade`
4. `bench update --patch`

### Stacktrace / full error message
```
~/frappe-bench$ bench switch-to-branch version-13 frappe erpnext --upgrade
...
...
~/frappe-bench$ bench update --patch
Backing up sites...
...
...
Executing erpnext.patches.v13_0.delete_old_purchase_reports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 300, in migrate
    skip_search_index=skip_search_index
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/delete_old_purchase_reports.py", line 17, in execute
    frappe.delete_doc("Report", report)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 871, in delete_doc
    ignore_permissions, flags, ignore_on_trash, ignore_missing, delete_permanently)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 105, in delete_doc
    check_if_doc_is_linked(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 253, in check_if_doc_is_linked
    raise_link_exists_exception(doc, linked_doctype, reference_docname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 308, in raise_link_exists_exception
    .format(doc.doctype, doc_link, reference_doctype, reference_link, row), frappe.LinkExistsError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Report <a href="/app/Form/Report/Purchase Order Items To Be Received or Billed">Purchase Order Items To Be Received or Billed</a> is linked with Prepared Report <a href="/app/Form/Prepared Report/REP00666">REP00666</a>
```

## Additional information
- Also, no report has 'Reference Report" set to this report.
- My attempt to delete this report using `bench console` resulted in error as this is standard report
- Attempt to delete using `developer_mode` also failed with this error:
```
InternalError: (1054, "Unknown column 'tabAssignment Rule.due_date_based_on' in 'where clause'")
```

**Comment by shreyanshj** [comment]
Ok - So, I managed to bypass this by directly deleting the 'Prepared Report' linked to this report from DB.
But, I am not sure if this still constitutes a bug or not. Maybe before migration/patching, should all the Prepared Report be deleted? Especially when any activity in migration is actually attempting to remove a report which has links to Prepared Reports.
