### ISSUE TITLE
Stock Reconciliation - "sr" referenced before assignment

### ISSUE THREAD

**Issue by sowmyarajshree** [frappe/erpnext#25390]
## Description of the issue
While cancelling the submitted Stock Reconciliation facing the error as **"UnboundLocalError: local variable 'sr' referenced before assignment"** .Can't able to cancel the submitted Stock reconciliation entry.

## Context information (for bug reports)
![Screenshot from 2021-04-19 15-25-25](https://user-images.githubusercontent.com/75108667/115217853-89a2b080-a123-11eb-92c2-96425ed1d914.png)

1.Can't able to Cancel the submited Stock Reconciliation.
2.While cancelling the submitted stock Reconciliation "UnboundLocalError: local variable 'sr' referenced before assignment" error is throwing.

In ERPNEXT Version-13.

**Comment by ankush** [comment]
After you get this error, can you go to the browser console and share the traceback. 

How to:
Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
Chrome: https://developer.chrome.com/docs/devtools/console/

**Comment by sowmyarajshree** [comment]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 39, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 922, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 912, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 336, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 987, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 50, in on_cancel
    self.make_sle_on_cancel()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 392, in make_sle_on_cancel
    self.make_sl_entries(sl_entries, allow_negative_stock=allow_negative_stock)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 305, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 44, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 78, in make_entry
    sle.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 917, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 906, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 336, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 985, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 49, in on_submit
    process_serial_no(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 219, in process_serial_no
    update_serial_nos(sle, item_det)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 398, in update_serial_nos
    auto_make_serial_nos(sle)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 420, in auto_make_serial_nos
    sr = update_args_for_serial_no(sr, serial_no, args, is_new=is_new)
UnboundLocalError: local variable 'sr' referenced before assignment

request.js:387 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1145, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 39, in cancel
    doc.cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 922, in cancel
    self._cancel()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 912, in _cancel
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 336, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 987, in run_post_save_methods
    self.run_method("on_cancel")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 50, in on_cancel
    self.make_sle_on_cancel()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 392, in make_sle_on_cancel
    self.make_sl_entries(sl_entries, allow_negative_stock=allow_negative_stock)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 305, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 44, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 78, in make_entry
    sle.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 917, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 906, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 336, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 985, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 49, in on_submit
    process_serial_no(self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 219, in process_serial_no
    update_serial_nos(sle, item_det)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 398, in update_serial_nos
    auto_make_serial_nos(sle)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 420, in auto_make_serial_nos
    sr = update_args_for_serial_no(sr, serial_no, args, is_new=is_new)
UnboundLocalError: local variable 'sr' referenced before assignment

**Comment by aakvatech** [comment]
Facing same problem

**Comment by ankush** [comment]
Based on this code:

https://github.com/frappe/erpnext/blob/a6e3d24882ac06b4ae7ce70e19b7d59a63e0bfad/erpnext/stock/doctype/serial_no/serial_no.py#L422-L428


This can only happen when you're trying to consume a serial no that doesn't exist. Need to handle the error message correctly though. 

Can reproduce now:

1. Create a new serialized item
2. Create a stock reco that will create a new serial no
3. Cancel stock reco. 

Temporary Work around: instead of canceling create a new stock reconciliation that undoes the changes.
