### ISSUE TITLE
It's not possible to create Item Variants

### ISSUE THREAD

**Issue by scdanieli** [frappe/erpnext#25423]
## Description of the issue

It's not possible to create Item Variants.

## Context information (for bug reports)

ERPNext: v13.1.0 (version-13)
Frappe Framework: v13.1.0 (version-13)

Same issue also under ...

ERPNext: v13.0.2 (version-13)
Frappe Framework: v13.0.3 (version-13)

## Steps to reproduce the issue

1. Create an **Item Template** (Check *Has Variants*, add at least one *Attributes* row)
2. Open the newly created **Item Template** and try to create Single/Multiple Variant/s via the Create Button.

#### Single Variant

```
Traceback (most recent call last):
  File "/home/frappe/bench-landa/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/bench-landa/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench-landa/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench-landa/apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 1166, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench-landa/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 306, in _save
    self.insert()
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 237, in insert
    self.run_before_save_methods()
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 960, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 858, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 1147, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 1130, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 852, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/bench-landa/apps/erpnext/erpnext/stock/doctype/item/item.py", line 118, in validate
    self.validate_variant_attributes()
  File "/home/frappe/bench-landa/apps/erpnext/erpnext/stock/doctype/item/item.py", line 950, in validate_variant_attributes
    variant = get_variant(self.variant_of, args, self.name)
  File "/home/frappe/bench-landa/apps/erpnext/erpnext/controllers/item_variant.py", line 35, in get_variant
    frappe.throw(_("Please specify at least one attribute in the Attributes table"))
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please specify at least one attribute in the Attributes table
```

#### Multiple Variants

```
Traceback (most recent call last):
  File "/home/frappe/bench-landa/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/bench-landa/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench-landa/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench-landa/apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 1166, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench-landa/apps/erpnext/erpnext/controllers/item_variant.py", line 189, in enqueue_multiple_variant_creation
    return create_multiple_variants(item, args)
  File "/home/frappe/bench-landa/apps/erpnext/erpnext/controllers/item_variant.py", line 205, in create_multiple_variants
    variant.save()
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 306, in _save
    self.insert()
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 232, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/document.py", line 422, in set_new_name
    set_new_name(self)
  File "/home/frappe/bench-landa/apps/frappe/frappe/model/naming.py", line 55, in set_new_name
    frappe.throw(_("{0} is required").format(doc.meta.get_label(fieldname)))
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/frappe/bench-landa/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Item Code is required
```

**Comment by scdanieli** [comment]
Problem/Solution: https://github.com/frappe/erpnext/issues/25037#issuecomment-819280902

**Comment by ankush** [comment]
Closing as it's a duplicate issue. Sending PR for fix.
