### ISSUE TITLE
TypeError: expected string or bytes-like object  process_response when submitting web form

### ISSUE THREAD

**Issue by zefanja** [frappe/erpnext#25544]
## Description of the issue

When I want to submit a web form (e.g. new domain/issues?new=1) I get an error (TypeError: expected string or bytes-like object  process_response). Because of this (I think) it does not redirect/route to the next page (that is specified under Actions in the web form settings)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.0
frappe 13.2.0
```

## Steps to reproduce the issue

1. Open web form (e.g. mydomain.com/issues?new=1)
2. Submit web form

### Observed result

* no redirection / routing to new page
* error in web console

### Expected result

* after submitting it you redirect to the route specified in the web form settings

### Stacktrace / full error message

```
jquery.min.js:4 POST https://domain/ 500 (INTERNAL SERVER ERROR)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
call @ website.js:63
callback @ web_form.js:145
200 @ website.js:78
i @ jquery.min.js:2
add @ jquery.min.js:2
always @ jquery.min.js:2
statusCode @ jquery.min.js:4
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
call @ website.js:63
save @ web_form.js:127
(anonymous) @ web_form.js:77
website.js:160 Traceback (most recent call last):
  File "/home/erp/frappe-bench/apps/frappe/frappe/app.py", line 65, in application
    response = frappe.handler.handle()
  File "/home/erp/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/erp/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1175, in call
    return fn(*args, **newargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/handler.py", line 182, in upload_file
    ret.save(ignore_permissions=ignore_permissions)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 306, in _save
    self.insert()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 237, in insert
    self.run_before_save_methods()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 960, in run_before_save_methods
    self.run_method("validate")
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 1147, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 1130, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 852, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 94, in validate
    self.set_file_name()
  File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 252, in set_file_name
    self.file_name = re.sub(r'/', '', self.file_name)
  File "/home/erp/frappe-bench/env/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 20.04, upgraded from ERP v12

**Comment by zefanja** [comment]
Any other information I can provide? This issue is a show stopper for us right now, because web form redirects doesn't work anymore :(

**Comment by begearon** [comment]
Hello, same issue here. Any update on this?
Thanks!

**Comment by Kinisiemobility-Auroville** [comment]
I am also having some issue .
Thanks

**Comment by av-dev2** [comment]
any update on this issue..??, I am facing the same case here....

**Comment by hbhawsar777** [comment]
Any Update on this issue.??
I'm using  
ERPNext : v13.11.0
Frappe Framework: v13.11.0

**Comment by gamusinhunter** [comment]
Facing this same issue on Frappe v14.0.2 
Did anyone find out the cause or how to solve it?
