### ISSUE TITLE
[V13.2] Password Reset is throwing error

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#25596]
Hi ,

After updating to V13.2 we keep encountering the error below when trying to reset a user password:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1175, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/rate_limiter.py", line 121, in wrapper
    frappe.throw(_("You hit the rate limit because of too many requests. Please try after sometime."))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 433, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 412, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 366, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: You hit the rate limit because of too many requests. Please try after sometime.
```

Please help fix asap!

Thanks

**Comment by abdulmalikGaruba** [comment]
any luck?

**Comment by Olawale1** [comment]
Hi @abdulmalikGaruba 

I think it was fixed in an update. Pls confirm your current version

**Comment by abdulmalikGaruba** [comment]
frappe 13.6.0

**Comment by abdulmalikGaruba** [comment]
Hello @Olawale1 
i used version 13.6.0 for frappe
