### ISSUE TITLE
v13 upgrade: unknown column 'email_id' in 'field list'

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#25726]
## Description of the issue

When upgrading from v12 to v13 we aways get an error unknown column 'email_id' in 'field list'. 
Also other users are affected see https://discuss.erpnext.com/t/erpnext-v12-to-v13-migration-issue/72321/3

## Context information (for bug reports)

```
bench version
erpnext 13.2.1
frappe 13.2.2

node -v
v10.24.0
```

## Steps to reproduce the issue

bench update
bench switch-to-branch version-13 frappe erpnext --upgrade
bench migrate-env /usr/bin/python3
bench setup requirements
bench build
bench update --patch

### Stacktrace / full error message

```
Executing erpnext.patches.v13_0.update_member_email_address in erp.site.tld (_da1deed950194793)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 301, in migrate
    skip_search_index=skip_search_index
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/patches/v13_0/update_member_email_address.py", line 15, in execute
    if not frappe.db.get_value("Member", member, "email_id"):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 406, in get_value
    order_by, cache=cache, for_update=for_update)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 450, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update, for_update=for_update)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 605, in _get_values_from_table
    values, as_dict=as_dict, debug=debug, update=update)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/erpnext/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'email_id' in 'field list'")
```
## workaround

commented out 2 lines in

   /frappe-bench/apps/erpnext/erpnext/patches/v13_0$  nano update_member_email_address.py

          #                       if not frappe.db.get_value("Member", member, "email_id"):
          #                               frappe.db.set_value("Member", member, "email_id", email)

**Comment by fadilsiddique** [comment]
https://discuss.erpnext.com/t/erpnext-v12-to-v13-migration-issue/72321 it's solved here.
