### ISSUE TITLE
make_purchase_order_for_default_supplier() missing 1 required positional argument: 'source_name'

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#25865]
Hi

While creating a purchase order from sales order, the below error pops up.

![image](https://user-images.githubusercontent.com/1904802/119935359-6ed02100-bf98-11eb-99c9-e7cc4d875650.png)

However as you can see both those values are same !!

![image](https://user-images.githubusercontent.com/1904802/119935892-4b59a600-bf99-11eb-9b39-225440ad64e3.png)

![image](https://user-images.githubusercontent.com/1904802/119935920-5f9da300-bf99-11eb-9c84-14c34acf13e7.png)

Below is the stack trace and the 417 exception error

![image](https://user-images.githubusercontent.com/1904802/119936178-c9b64800-bf99-11eb-9d56-d0e42fb879b8.png)

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1173, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 876, in make_purchase_order_for_default_supplier
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 961, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1148, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 853, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 43, in validate
    super(PurchaseOrder, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 31, in validate
    super(BuyingController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 22, in validate
    super(StockController, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 108, in validate
    self.validate_all_documents_schedule()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 175, in validate_all_documents_schedule
    self.validate_non_invoice_documents_schedule()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 169, in validate_non_invoice_documents_schedule
    self.validate_payment_schedule_amount()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 1011, in validate_payment_schedule_amount
    frappe.throw(_("Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 431, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 410, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 364, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total
```
and clicking on the 417 error brings the below stack trace

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1173, in call
    return fn(*args, **newargs)
TypeError: make_purchase_order_for_default_supplier() missing 1 required positional argument: 'source_name'
```

**Comment by centaur78** [comment]
The same issue is also showing up in version 13 as well

**Comment by dj12djdjs** [comment]
@centaur78 I wasn't able to replicate this on develop or version-13 can you tell me the exact steps you followed leading to this?

**Comment by centaur78** [comment]
Hi @dj12djdjs 

Just to make sure , I just did bench update and both frappe and erpnext are at

![image](https://user-images.githubusercontent.com/1904802/120583572-89464680-c43f-11eb-9f97-9a565fa7a797.png)

Try creating a quotation for a customer with the following details
1. Set the currency and price list as below
![image](https://user-images.githubusercontent.com/1904802/120583639-b135aa00-c43f-11eb-8041-eeb68a8dc85b.png)

2. Set three items with the following rates which would give the total prices as shown
![image](https://user-images.githubusercontent.com/1904802/120584026-46d13980-c440-11eb-89aa-0eeea934ffa7.png)

3. Set the payment terms as shown below 
![image](https://user-images.githubusercontent.com/1904802/120584185-89931180-c440-11eb-8a74-c3277dcd071d.png)

4. Save and Submit. No problems here
5. Now create a Sales order from this Quotation maintaining the same currency and price list as above. 
6. One additional step here is since its a drop ship, you would also need to select "Supplier delivers to customer" against each items
7. Now save and submit.
8. Now try to create a Purchase order from this Sales order while selecting "Against Default Supplier". You will get the error
**Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total**

**Comment by centaur78** [comment]
Hi @dj12djdjs 

Also bench updated develop as well. Same error by following the above process.

**Comment by dj12djdjs** [comment]
@centaur78 I'm still not able to replicate it. I suspect it has something to do with the conversion between EUR and OMR. What if you play with the exchange rate so R.O 118.479 rounds to R.O 118.48 ?

**Comment by centaur78** [comment]
@dj12djdjs 

OMR is the base currency, with precision set to 3 digit in Settings. However.. I never had this problem before, except after a bench update that was done in May. 

So if this was the problem with exchange rates it should affect all other previous order as well.

**Comment by dj12djdjs** [comment]
I just tried on my end with 3 digit precision and it worked fine. It should be something else.

**Comment by centaur78** [comment]
hmm

This is weird.

I just cancelled the sales order and amended it by changing the exchange rate from 0.467  to 0.47 but maintaining the same precision for others 

What do you know... it went through .... Still don't understand why this is .

Closing this.. as issue resolved.
