### ISSUE TITLE
UnboundLocalError: local variable 'leave_allocation' referenced before assignment

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26304]
On Bulk Leave Policy Assignment.

![image](https://user-images.githubusercontent.com/1822868/124281135-17ead800-db52-11eb-87b9-5130cbac6510.png)

**Comment by ankush** [comment]
I am guessing this is where it's happening:

https://github.com/frappe/erpnext/blob/fd84847f2b263d0611a80387e90329e29c93c6d8/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py#L54-L60

**Comment by dinkuraja** [comment]
Any update on this?? I am also getting same error when assigning the leave policy

**Comment by lokeshwrn** [comment]
Any update on this?
I am getting the same error, during individual leave policy assignment, bulk leave policy assignment, and during its import too. 

I am unable to assign a leave policy to the employees in all possible ways. Any possible workaround for this?

```Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 126, in import_data
    doc = self.process_doc(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 194, in process_doc
    return self.insert_record(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 215, in insert_record
    new_doc.submit()
  File "apps/frappe/frappe/model/document.py", line 938, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 926, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 340, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1006, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 867, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1160, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1143, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 861, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 22, in on_submit
    self.grant_leave_alloc_for_employee()
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 61, in grant_leave_alloc_for_employee
    leave_allocations[leave_policy_detail.leave_type] = {"name": leave_allocation, "leaves": new_leaves_allocated}
UnboundLocalError: local variable 'leave_allocation' referenced before assignment```

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/29086
