### ISSUE TITLE
frappe.exceptions.LinkValidationError: Could not find DocType: packing_slip

### ISSUE THREAD

**Issue by jeffsampaul** [frappe/erpnext#26346]
Getting the following error during bench migrate

<frappe.core.doctype.version.version.Version object at 0x7f18955d7040>
{'name': None, 'owner': 'Administrator', 'creation': None, 'modified': None, 'modified_by': None, 'parent': None, 'parentfield': None, 'parenttype': None, 'idx': 0, 'docstatus': 0, 'ref_doctype': None, 'docname': None, 'data': None, 'doctype': 'Version', '__islocal': 1}
<frappe.custom.doctype.custom_script.custom_script.CustomScript object at 0x7f189527d370>
{'name': None, 'owner': 'Administrator', 'creation': None, 'modified': None, 'modified_by': None, 'parent': None, 'parentfield': None, 'parenttype': None, 'idx': 0, 'docstatus': 0, 'dt': None, 'script': None, 'doctype': 'Custom Script', '__islocal': 1}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jefferson/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/commands/site.py", line 286, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/migrate.py", line 52, in migrate
    sync_fixtures()
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 26, in sync_fixtures
    import_custom_scripts(app)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 46, in import_custom_scripts
    frappe.get_doc({
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/model/document.py", line 224, in insert
    self._validate_links()
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg),
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/jefferson/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find DocType: packing_slip

**Comment by jeffsampaul** [comment]
Had to rename packing_slip.js to Packing Slip.js 
Fixed the issue myself
