### ISSUE TITLE
Custom field error in ERPNext 5

### ISSUE THREAD

**Issue by chafor** [frappe/erpnext#2636]
Hi,

We begin using ERP Next 5, because it's absolutely necessary to use a chart of account with more than 4 root chart.

But when I look at the custom field option ERP Next return me this :

Traceback (innermost last):
File "/home/apt/frappe-bench/apps/frappe/frappe/app.py", line 49, in application
response = frappe.handler.handle()
File "/home/apt/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
execute_cmd(cmd)
File "/home/apt/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
ret = frappe.call(method, **frappe.form_dict)
File "/home/apt/frappe-bench/apps/frappe/frappe/__init__.py", line 682, in call
return fn(*args, **newargs)
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 59, in getdoctype
docs = get_meta_bundle(doctype)
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 69, in get_meta_bundle
bundle = [frappe.desk.form.meta.get_meta(doctype)]
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 19, in get_meta
meta = frappe.cache().get_value("form_meta:" + doctype, lambda: FormMeta(doctype))
File "/home/apt/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 38, in get_value
val = generator()
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 19, in 
meta = frappe.cache().get_value("form_meta:" + doctype, lambda: FormMeta(doctype))
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 31, in init
self.load_assets()
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 41, in load_assets
self.load_templates()
File "/home/apt/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 169, in load_templates
module = load_doctype_module(self.name)
File "/home/apt/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 60, in load_doctype_module
doctype_python_modules[key] = frappe.get_module(get_module_name(doctype, module, prefix))
File "/home/apt/frappe-bench/apps/frappe/frappe/__init__.py", line 482, in get_module
return importlib.import_module(modulename)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
import(name)
ImportError: No module named custom_field.custom_field

Is it because you have not finish this part yet?

**Comment by rmehta** [comment]
Did you run `bench frappe --latest` ?

This issue should not come.

**Comment by chafor** [comment]
Hello here the console error :
apt@sverpnext5:~$ bench update
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 13 (delta 4), reused 1 (delta 0)
Unpacking objects: 100% (13/13), done.
From https://github.com/frappe/bench
   5fc81d0..36b6ffe  master     -> origin/master
 * [new branch]      pdvyas-patch-1 -> origin/pdvyas-patch-1
Updating 5fc81d0..36b6ffe
Fast-forward
 bench/cli.py              | 18 +++++++++++++-----
 bench/production_setup.py |  4 ++--
 bench/utils.py            |  9 ++++++++-
 3 files changed, 23 insertions(+), 8 deletions(-)
remote: Counting objects: 133, done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 133 (delta 53), reused 12 (delta 7)
Receiving objects: 100% (133/133), 80.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), done.
From https://github.com/frappe/erpnext
 * branch            v5.0       -> FETCH_HEAD
   538253e..d2b762d  v5.0       -> upstream/v5.0
Updating 538253e..d2b762d
error: Your local changes to the following files would be overwritten by merge:
        erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
Please, commit your changes or stash them before you can merge.
Aborting
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/apt/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/apt/bench-repo/bench/cli.py", line 166, in update
    pull_all_apps()
  File "/home/apt/bench-repo/bench/app.py", line 74, in pull_all_apps
    exec_cmd("git pull {rebase} upstream {branch}".format(rebase=rebase, branch=get_current_branch(app_dir)), cwd=app_dir)
  File "/home/apt/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git pull  upstream v5.0
' returned non-zero exit status 1
apt@sverpnext5:~$
