### ISSUE TITLE
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte

### ISSUE THREAD

**Issue by arahimfahim40** [frappe/erpnext#26413]
## Description of the issue
When trying to integrate and embed a metabase dashboard in ERPNext, following error is outputted in trying to open the page afterwards "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte".
## Context information (for bug reports)
I was following this [link](https://discuss.erpnext.com/t/tutorial-creating-an-embedded-metabase-internal-page/44942)
**Output of `bench version`**
```
erpnext 13.6.0
erpnext_helper 0.0.1
erpnext_shipping 0.0.1
frappe 13.6.0
metabase_integration 0.0.1
shippmentservice 0.0.1

```

## Steps to reproduce the issue

1. Follow the tutorial to set up metabase integration in a ERPNext page
2. Open the page afterwards
3. The error will occur

### Observed result
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte
### Expected result
Dashboard embedded
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 32, in getpage
    doc = get(page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 15, in get
    page.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/page/page.py", line 113, in load_assets
    self.script = render_include(f.read())
  File "/home/frappe/frappe-bench/env/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 187: invalid start byte

/socket.io/?EIO=3&transport=polling&t=NgDWDmv:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
If this is part custom metabase_integration then the issue should be opened in the relevant repo. 
If it's related to core request handling then frappe/frappe. 

In any case, this issue doesn't belong in erpnext repo.

**Comment by arahimfahim40** [comment]
Since this works completely fine in V12 but not in V13 I think there is some problem in Frappe so I have opened an Issue in [frappe](https://github.com/frappe/frappe/issues/13695)
