### ISSUE TITLE
Tally migration tool error

### ISSUE THREAD

**Issue by hemkantSplat** [frappe/erpnext#26446]
When I process xml from tally i get following error

Data:
"Processing Master Data"
----------------------------------------------------------------------------------------------------

Exception:
Traceback (most recent call last):
  File "/home/splaterp/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 250, in _process_master_data
    company = get_company_name(collection)
  File "/home/splaterp/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 98, in get_company_name
    return collection.find_all("REMOTECMPINFO.LIST")[0].REMOTECMPNAME.string.strip()
IndexError: list index out of range

**Comment by moizsami** [comment]
I am receiving the same error, I exported from Tally ERP 9..is there any solution for it ?

**Comment by mihir-kandoi** [comment]
This issue has been automatically closed as it no longer appears to be valid. If you think this was closed in error, please mention me (@mihir-kandoi) in a comment here and I'll take another look.
