### ISSUE TITLE
v13.7.0 'Student' object has no attribute 'student_category'

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#26745]
## Description of the issue
"Student Applicant" can't be enrolled. AttributeError: 'Student' object has no attribute 'student_category'.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.7.0 (version-13)
Frappe Framework: v13.7.0 (version-13)
```

## Steps to reproduce the issue

1. Validate Student Applicant.
2. Actions > Approve. Update.
3. Clic on "Enroll"
4. AttributeError: 'Student' object has no attribute 'student_category'.

### Observed result
![Error_student_category](https://user-images.githubusercontent.com/25084259/127694785-99b104fe-0f70-426f-af28-2d11b1361bdb.png)

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/education/api.py", line 39, in enroll_student
    program_enrollment.student_category = student.student_category
AttributeError: 'Student' object has no attribute 'student_category'
```

**Comment by HarshAulakh** [comment]
@ankush Is this issue still open? Would love to have a look at it as part of hacktoberfest.

**Comment by ankush** [comment]
This is already fixed, just not linked to PR. 

https://github.com/frappe/erpnext/pull/26716
