### ISSUE TITLE
V13.8 Importing Payment Entry with multi currency 

### ISSUE THREAD

**Issue by zenicolas** [frappe/erpnext#26974]
## Description of the issue

Unable to submit payment entry (receive) with multi-currency.
Unallocated amount cancels the allocated amount. 
Difference amount calculates the paid amount in company currency minus the foreign currency amount.

## Context information (for bug reports)

Imported Payment Entries from google sheet as drafts. 

**Output of `bench version`**
ERPNext: v13.8.0 (version-13)
Frappe Framework: v13.8.1 (version-13)

```

## Steps to reproduce the issue

1. Imported Payment Entry as draft from Google Sheet
2. Reconciling payments from the payment entry module
3. Submitting document once all information is complete

### Observed result

Allocated amount is displayed correctly. 
Calculation issue with the difference amount, displays the paid amount minus the foreign currency amount. 
Disregards the allocated amounts. (since allocated and unallocated amounts equals zero)

### Expected result

Unallocated amount should display allocated less paid amount in company currency.
Difference amount should be zero. 
[Men-Invest Commodities Ltd - ACC-PAY-21-08-00256.pdf](https://github.com/frappe/erpnext/files/6997476/Men-Invest.Commodities.Ltd.-.ACC-PAY-21-08-00256.pdf)

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/core/doctype/data_import/importer.py", line 126, in import_data
    doc = self.process_doc(doc)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/core/doctype/data_import/importer.py", line 194, in process_doc
    return self.insert_record(doc)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/core/doctype/data_import/importer.py", line 215, in insert_record
    new_doc.submit()
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 929, in submit
    self._submit()
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 918, in _submit
    self.save()
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 337, in _save
    self.run_post_save_methods()
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 997, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 859, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 1148, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 1131, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/model/document.py", line 853, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/admin_aplvanille_com/myfrappe/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 73, in on_submit
    frappe.throw(_("Difference Amount must be zero"))
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/__init__.py", line 432, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/home/admin_aplvanille_com/myfrappe/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Difference Amount must be zero
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Google Cloud, ubuntu-minimal-2004
[ERPNext-v13.8-data_import-payment_entry-difference_amout-issue.xlsx](https://github.com/frappe/erpnext/files/6997447/ERPNext-v13.8-data_import-payment_entry-difference_amout-issue.xlsx)

**Comment by deepeshgarg007** [comment]
@zenicolas You are getting a validation, the difference amount should be zero in all cases, this might be a data issue or some unhandled edge case, please share some data as to what values you had added in the template and reopen this issue
