### ISSUE TITLE
Error on selecting the employees while creating the time logs for the Job card

### ISSUE THREAD

**Issue by JamesCharlesDoe** [frappe/erpnext#27064]
## Description of the issue
Error on selecting the employees while creating the time logs for the Jog

This issue is a duplicate of the issue (https://github.com/frappe/erpnext/issues/26540). 

We have  checked this issue with the latest ERPNext 13.9 version and also with the develop branch and we are getting the same issue. I think the issue can be replicated on the new frappe sites and create the job cards from the work order.

Kindly let us know how to resolve this issue.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.9.2
frappe 13.9.0

```

## Steps to reproduce the issue

1. Create a Job Card using the work order
2. Select an employee within the "Time Logs" table
3. Try to 'Save' the Job Card

### Observed result
![image](https://user-images.githubusercontent.com/89257569/130237911-c43afc05-e32e-4e63-8b39-82481ddd13dd.png)

### Expected result
Job card should be saved

### Stacktrace / full error message

```
18:49:54 web.1            | 127.0.0.1 - - [20/Aug/2021 18:49:54] "POST /api/method/frappe.desk.search.search_link HTTP/1.1" 200 -
18:49:54 web.1            | 127.0.0.1 - - [20/Aug/2021 18:49:54] "GET /api/method/frappe.desk.form.utils.validate_link?value=HR-EMP-00001&options=Employee&fetch=&_=1629465559085 HTTP/1.1" 200 -
18:49:55 web.1            | 127.0.0.1 - - [20/Aug/2021 18:49:55] "GET /api/method/frappe.desk.form.utils.validate_link?value=HR-EMP-00001&options=Employee&fetch=&_=1629465559086 HTTP/1.1" 200 -
18:49:56 web.1            | 127.0.0.1 - - [20/Aug/2021 18:49:56] "POST /api/method/frappe.desk.search.search_link HTTP/1.1" 200 -
18:49:57 web.1            | 127.0.0.1 - - [20/Aug/2021 18:49:57] "POST /api/method/erpnext.manufacturing.doctype.job_card.job_card.make_time_log HTTP/1.1" 500 -


```

**Comment by ankush** [comment]
Hello, 
When this error occurs,  can you please get error traceback from the browser console? It will tell us exactly where this issue is coming from.

ref: https://balsamiq.com/support/faqs/browserconsole/

**Comment by JamesCharlesDoe** [comment]
Hi, 
I have got the below error in my browser console.

jquery.js:10099 POST http://localhost:8000/api/method/erpnext.manufacturing.doctype.job_card.job_card.make_time_log 500 (INTERNAL SERVER ERROR)
send @ jquery.js:10099
ajax @ jquery.js:9682
frappe.request.call @ request.js:229
frappe.call @ request.js:98
make_time_log @ job_card__js:237
_handler @ script_manager.js:30
start_job @ job_card__js:221
_handler @ script_manager.js:30
eval @ job_card__js:174
(anonymous) @ messages.js:99
(anonymous) @ dialog.js:150
dispatch @ jquery.js:5429
elemData.handle @ jquery.js:5233
request.js:387 Traceback (most recent call last):
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in call
    return fn(*args, **newargs)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 540, in make_time_log
    doc.add_time_log(args)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 214, in add_time_log
    self.save()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 282, in save
    return self._save(*args, **kwargs)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 317, in _save
    self.run_before_save_methods()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 966, in run_before_save_methods
    self.run_method("validate")
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 1156, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 1139, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 25, in validate
    self.validate_time_logs()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 50, in validate_time_logs
    data = self.get_overlap_for(d)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 84, in get_overlap_for
    existing = frappe.db.sql("""select jc.name as name, jctl.to_time from
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/apps/frappe/frappe/database/database.py", line 138, in sql
    self._cursor.execute(query, values)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ewall/Documents/ERPNext_dev/frappe-bench/env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'jc.employee' in 'where clause'"

**Comment by timschneider** [comment]
I think this bug is caused by this line: 

https://github.com/frappe/erpnext/blob/69973a65aa96d5b1bb9c05961c1815e4ce1f880c/erpnext/manufacturing/doctype/job_card/job_card.py#L78

it should be

`validate_overlap_for = " and jctl.employee = %(employee)s "`

![grafik](https://user-images.githubusercontent.com/2517553/130487197-3b002380-caab-4edd-ac8e-8fbe57bc56dc.png)

I'm not able to test this because i've no dev version at hand and only my kubernetes prod environment, maybe @yadavyk or @ankush you can help?


ERPNext: v13.9.2 (version-13)
Frappe Framework: v13.9.1 (version-13)
