### ISSUE TITLE
frappe.exceptions.ValidationError: Fieldtype cannot be changed from Data to Currency

### ISSUE THREAD

**Issue by techseria** [frappe/erpnext#27075]
At the time of erpnext version 12 to 13 we are getting this error. 
Executing erpnext.patches.v13_0.check_is_income_tax_component #22-06-2020 in dev-erp.techseria.com (_ea829b60f0500595)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/opt/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/erp/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/commands/site.py", line 309, in migrate
    skip_search_index=skip_search_index
  File "/opt/erp/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/opt/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/erp/frappe-bench/apps/erpnext/erpnext/patches/v13_0/check_is_income_tax_component.py", line 31, in execute
    setup(patch=True)
  File "/opt/erp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 17, in setup
    setup_company_independent_fixtures(patch=patch)
  File "/opt/erp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 24, in setup_company_independent_fixtures
    make_custom_fields()
  File "/opt/erp/frappe-bench/apps/erpnext/erpnext/regional/india/setup.py", line 685, in make_custom_fields
    create_custom_fields(custom_fields, update=update)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 169, in create_custom_fields
    custom_field.save()
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 320, in _save
    self.run_before_save_methods()
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 963, in run_before_save_methods
    self.run_method("validate")
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 861, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 1153, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 855, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 58, in validate
    frappe.throw(_("Fieldtype cannot be changed from {0} to {1}").format(old_fieldtype, self.fieldtype))
  File "/opt/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 432, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/opt/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/opt/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fieldtype cannot be changed from Data to Currency

**Comment by mymi14s** [comment]
This is not a bug, the field may contain data set that is not a floating point / integer.

Locate the table and fileld, change all non number records to number maybe 0.0. The retry the migration.

**Comment by techseria** [comment]
Can you please share in which table or filed I need to check?

**Comment by techseria** [comment]
Here is the thread https://discuss.erpnext.com/t/frappe-exceptions-validationerror-fieldtype-cannot-be-changed-from-data-to-currency/76868

Other people are also facing the same problem. If you can provide some more help or guide then it will be really helpful.

**Comment by elan-k** [comment]
We are also facing this issue and are unable to find the location(table & field) of the issue as well. 

We have hosted with frappecloud.com, where we are not getting any support from them. Also no access to the Database as well. 

By looking at the error, I'm able to see it's related to custom fields... but no sure about it.  

![12to13_Error](https://user-images.githubusercontent.com/78781781/131095412-91b94118-b97a-4b37-ab16-6fe8d0bdce3f.JPG)

@mymi14s : Can you help us with the same?

**Comment by mymi14s** [comment]
Take download the database locally and fix

**Comment by elan-k** [comment]
@mymi14s :

Ok.. sure, Let me try that out.

Can you suggest any specific area that I can look at since the error has the following informations, 

1. erpnext.patches.v13_0.check_is_income_tax_component
2. File /opt/erp/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py, line 58, in validate
frappe.throw(("Fieldtype cannot be changed from {0} to {1}").format(old_fieldtype, self.fieldtype))
3. frappe.exceptions.ValidationError: Fieldtype cannot be changed from Data to Currency

**Comment by techseria** [comment]
If anyone can guide table name or query then I can also check.
I tried to print MySQL query log and also checked the binary log to identify actual query which is causing the issue but did not found anything.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/27195
