### ISSUE TITLE
Payment Schedule Calculation Multiplies the Total for the Payment Schedule by the Number of Payments When Validating

### ISSUE THREAD

**Issue by skjbulcher** [frappe/erpnext#27208]
## Description of the issue

After a fresh v13 install, attempting to create a Sales Order with an arbitrary Payment Schedule results in

![image](https://user-images.githubusercontent.com/16672299/131177325-1a490756-5901-4df6-b74e-da63e6fd0543.png)

The Grand total is the same as the total of the Payment Amount column in the Payment Schedule.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.9.2
frappe 13.9.1
```

## Steps to reproduce the issue

1. Create a Sales Order, add items to create a total
2. Set up a Payment Schedule:
    - Payment Term = ""
    - Description = "DP", "+1", "+2"
    - Due Date (as appropriate)
    - Invoice Portion = "0%"
    - Payment Amount = values totaling the amount of the invoice. E.g. for a $2100 Sales Order, you can use the values $100, $1000, $1000
3. Save

### Observed result

Sale Order does not save and sends the message:
![image](https://user-images.githubusercontent.com/16672299/131177796-992a318c-95fe-45cd-9ee9-2501a8239d62.png)

### Expected result

The Sales Order should save

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 963, in run_before_save_methods
    self.run_method("validate")
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 861, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1153, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 855, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 35, in validate
    super(SalesOrder, self).validate()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 31, in validate
    super(SellingController, self).validate()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 26, in validate
    super(StockController, self).validate()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 108, in validate
    self.validate_all_documents_schedule()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 179, in validate_all_documents_schedule
    self.validate_non_invoice_documents_schedule()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 173, in validate_non_invoice_documents_schedule
    self.validate_payment_schedule_amount()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 1334, in validate_payment_schedule_amount
    frappe.throw(_("Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total"))
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 432, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/home/jbulcher/workspace/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total
```

## Additional information

I noticed a few things about the `accounts_controller.py` file while investigating this issue:

```
def validate_payment_schedule_amount(self):
    ...
        if self.get("payment_schedule
            total = 0
            base_total = 0
            for d in self.get("payment_schedule"):
                total += flt(d.payment_amount)
                base_total += flt(d.base_payment_amount)
                print(f'{d.base_payment_amount=}, {total=}, {base_total=}')
```

In the above code block, `flt(d.payment_amount)` equals the value entered under the 'Payment Amount' column of the Payment Schedule child table, so that `total` equals the total of all Payment Amounts in the Payment Schedule. `flt(d.base_payment_amount)`, however, equals the total from the start, causing the base_total to be the total value multiplied by the number of rows in the Payment Schedule. You can see this in the output of the print statement:

```
12:21:58 web.1            | d.base_payment_amount=2100.0, total=100.0, base_total=2100.0
12:21:58 web.1            | d.base_payment_amount=2100.0, total=1100.0, base_total=4200.0
12:21:58 web.1            | d.base_payment_amount=2100.0, total=2100.0, base_total=6300.0
```

Later on when the validation condition runs, it's using that base_total in the comparison:

```
if total != flt(grand_total, self.precision("grand_total")) or \
    base_total != flt(base_grand_total, self.precision("base_grand_total")):
    frappe.throw(_("Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total"))
````

At this point I'm out of my depth since I don't know what `base_total` is supposed to be - if it's related to the Payment Schedule or the Sales Order total.

**Comment by skjbulcher** [comment]
I think I might have found the problem in this commit from 18 days ago: https://github.com/frappe/erpnext/commit/cd980f5e6b1853b4cf2af02d5592cb5da7ae1f8a?branch=cd980f5e6b1853b4cf2af02d5592cb5da7ae1f8a&diff=split

```
		for d in self.get("payment_schedule"):
			if d.invoice_portion:
				d.payment_amount = flt(grand_total * flt(d.invoice_portion / 100), d.precision('payment_amount'))
				d.base_payment_amount = flt(base_grand_total * flt(d.invoice_portion / 100), d.precision('base_payment_amount'))
				d.outstanding = d.payment_amount
			elif not d.invoice_portion:
				d.base_payment_amount = flt(base_grand_total * self.get("conversion_rate"), d.precision('base_payment_amount'))
```

The commit appears to handle the base_payment_amount incorrectly.

When invoice portions (%) is present, it does something like this so that each line is a portion of the grand total:

```
base_payment_amount for each line = Sales Order grand total * %
```

However, f there is no invoice portion, it looks like this:

```
base_payment_amount for each line = Sales Order grand total
```

If I'm not reading that wrong, then the base_payment_amount is calculated incorrectly
