### ISSUE TITLE
[Version 5] Bench migrate-to-v5 exception

### ISSUE THREAD

**Issue by sinaisix** [frappe/erpnext#2730]
Running bench migrate-to-v5 fails with following exception
Executing frappe.patches.v5_0.update_shared in site1.local (site1.local)
Traceback (most recent call last):
File "/home/ubuntu/frappe-bench/env/bin/frappe", line 9, in 
load_entry_point('frappe==4.9.2', 'console_scripts', 'frappe')()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 39, in main
ret = run(fn, args)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
out = globals().get(fn)(*args)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
return fn(args, *new_kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/cli.py", line 442, in latest
frappe.modules.patch_handler.run_all()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
if not run_single(patchmodule = patch):
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
return execute_patch(patchmodule, method, methodargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
frappe.get_attr(patchmodule.split()[0] + ".execute")()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/patches/v5_0/update_shared.py", line 13, in execute
frappe.share.add("User", user.name, user.name, write=1)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/share.py", line 37, in add
doc.save(ignore_permissions=True)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in save
self.insert()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 165, in insert
self.run_before_save_methods()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 495, in run_before_save_methods
self.run_method("validate")
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 461, in run_method
return Document.hook(fn)(self, *args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 572, in composer
return composed(self, method, args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 555, in runner
add_to_return_value(self, fn(self, args, *kwargs))
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in 
fn = lambda self, args, *kwargs: getattr(self, method)(args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/docshare/docshare.py", line 16, in validate
self.get_doc().run_method("validate_share", self)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 461, in run_method
return Document.hook(fn)(self, args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 572, in composer
return composed(self, method, args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 555, in runner
add_to_return_value(self, fn(self, args, *kwargs))
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 455, in 
fn = lambda self, args, *kwargs: getattr(self, method)(args, *kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 95, in validate_share
frappe.throw(("Sorry! User should have complete access to their own record."))
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init_.py", line 234, in throw
msgprint(msg, raise_exception=exc)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/init.py", line 227, in msgprint
raise_exception()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init_.py", line 211, in raise_exception
raise raise_exception, msg
frappe.exceptions.ValidationError: Sorry! User should have complete access to their own record.
Error: None
Traceback (most recent call last):
File "/usr/local/bin/bench", line 9, in 
load_entry_point('bench==0.1', 'console_scripts', 'bench')()
File "/home/ubuntu/bench-repo/bench/cli.py", line 38, in cli
return bench()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call_
return self.main(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
return callback(args, **kwargs)
File "/home/ubuntu/bench-repo/bench/cli.py", line 172, in update
patch_sites()
File "/home/ubuntu/bench-repo/bench/utils.py", line 93, in patch_sites
exec_cmd("{frappe} --latest all".format(frappe=get_frappe(bench=bench)), cwd=os.path.join(bench, 'sites'))
File "/home/ubuntu/bench-repo/bench/utils.py", line 61, in exec_cmd
subprocess.check_call(cmd, cwd=cwd, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ubuntu/frappe-bench/env/bin/frappe --latest all' returned non-zero exit status 1
Error: None
Traceback (most recent call last):
File "/usr/local/bin/bench", line 9, in 
load_entry_point('bench==0.1', 'console_scripts', 'bench')()
File "/home/ubuntu/bench-repo/bench/cli.py", line 38, in cli
return bench()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call_
return self.main(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
return callback(args, **kwargs)
File "/home/ubuntu/bench-repo/bench/cli.py", line 210, in _migrate_to_v5
migrate_to_v5(bench=bench)
File "/home/ubuntu/bench-repo/bench/migrate_to_v5.py", line 16, in migrate_to_v5
exec_cmd("{bench} update".format(bench=sys.argv[0]))
File "/home/ubuntu/bench-repo/bench/utils.py", line 61, in exec_cmd
subprocess.check_call(cmd, cwd=cwd, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/bench update' returned non-zero exit status 1

**Comment by gentle-** [comment]
I have the same issue. I am on Ubuntu 14.04.1 and did the "bench migrate-to-v5" when I ran into this error.

**Comment by sinaisix** [comment]
yeah. Tried it in my Amazon web services server, 14.04.1. Same error

**Comment by pdvyas** [comment]
This issue is from a new "share" feature which would work like google docs.
If you want a clean v5 install, maybe `bench frappe --reinstall` would help
(this would drop database and start afresh)

**Comment by gentle-** [comment]
Yes, that does work, although it also resets the administrator password, which is not stored in the file. Anyway, I can't access ERPNext now.
This might be irrelevant for the bug. I'm happy to do a fresh install after you fix the original issue. If it's a minor thing (the admin pwd), please let me know.

**Comment by sinaisix** [comment]
In my case, running bench frappe --reinstall asked me for a new admin
password. Reinstall went fine. But it installed v4.16. Now I do bench
update to v4.21.4. Then I do bench migrate-to-v5 and still same error. Like
@gentle- stated above, I'll hold on till this bug is fixed. Quite a show
stopper if you ask me

Luqman
+233-244-493985

**Comment by pdvyas** [comment]
If you run `bench frappe --reinstall` in a v5 bench, that shouldn't change
the version to 4.

**Comment by gentle-** [comment]
Scratch my remarks on the admin password.
The username is administrator, not Administrator. That's what went wrong. Password is generated as @sinaisix described.

I'm on V5 after reinstall. Workaround is working for me.

**Comment by sinaisix** [comment]
Ok @gentle- can you run me through your steps, one after the other?

**Comment by gentle-** [comment]
Sure.

Fresh Virtualbox VM: ubuntu server 14.04.1 installed as guest OS.

wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh
sudo bash setup_frappe.sh --setup-production
bench migrate-to-v5

At this point I get an error

bench frappe --reinstall
(script indeed asks for admin password, which I gave and which afterwards works)

Now I'm still on V5, but the setup wizard now gives me some trouble (opened a new issue for that)

**Comment by sinaisix** [comment]
Ok thanks. I'll try that on my aws server and get back

**Comment by sinaisix** [comment]
Ok thanks. Got it up and running on aws Now

**Comment by sinaisix** [comment]
Not sure where to file this

![v5](https://cloud.githubusercontent.com/assets/3254773/6166605/5da1cf76-b2a9-11e4-9098-0d71fe349ed9.png)

**Comment by rmehta** [comment]
fixed
