### ISSUE TITLE
Migrate version-13 to develop fails do to taxjar patch.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#27307]
## Description of the issue
Migration from version-13 to develop branch fails during erpnext.patches.v13_0.custom_fields_for_taxjar_integration

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 13.x.x-develop
```
### Stacktrace / full error message

```
Executing erpnext.patches.v13_0.custom_fields_for_taxjar_integration in migrate-site (_8b1d265d961c7476)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-13-develop/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/commands/site.py", line 309, in migrate
    skip_search_index=skip_search_index
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/migrate.py", line 65, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
    run_patch(patch)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/bench-13-develop/apps/erpnext/erpnext/patches/v13_0/custom_fields_for_taxjar_integration.py", line 27, in execute
    create_custom_fields(custom_fields, update=True)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 159, in create_custom_fields
    create_custom_field(doctype, df, ignore_validate=ignore_validate)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 139, in create_custom_field
    custom_field.insert()
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 265, in insert
    self.run_post_save_methods()
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 998, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 859, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 1155, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 1138, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/model/document.py", line 853, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 75, in on_update
    validate_fields_for_doctype(self.dt)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 741, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1069, in validate_fields
    check_website_search_field(meta)
  File "/home/frappe/bench-13-develop/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 941, in check_website_search_field
    if not meta.website_search_field:
AttributeError: 'Meta' object has no attribute 'website_search_field'

```

**Comment by ankush** [comment]
Duplicate
https://github.com/frappe/frappe/issues/14245
