### ISSUE TITLE
frappe school - HR Module

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#27407]
## Description of the issue
When clicking on employee life cycle video, Error Code: 500 
## Context information (for bug reports)
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    response = renderer_instance.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 61, in render
    html = self.get_html()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 443, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in get_html
    html = self.render_template()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 212, in render_template
    html = frappe.render_template(self.source, self.context, safe_render=safe_render)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 108, in top-level template code
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "<template>", line 26, in block 'content'
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 50, in template
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/community/community/lms/doctype/lesson/lesson.py", line 47, in render_html
    return markdown_to_html(self.body)
  File "/home/frappe/frappe-bench/apps/community/community/lms/md.py", line 28, in markdown_to_html
    return markdown.markdown(text, extensions=['fenced_code', MacroExtension()])
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markdown/core.py", line 248, in convert
    if not source.strip():
AttributeError: 'NoneType' object has no attribute 'strip'

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by nidhipurohit11** [comment]
Please report issues by sending an email to school@frappe.io
