### ISSUE TITLE
Error while generating a pdf

### ISSUE THREAD

**Issue by wildman-web** [frappe/erpnext#27645]
Traceback (most recent call last):
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/utils/print_format.py", line 92, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "/home/frappe/vivitra-bench/apps/frappe/frappe/utils/pdf.py", line 40, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/vivitra-bench/env/lib/python3.6/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/vivitra-bench/env/lib/python3.6/site-packages/pdfkit/pdfkit.py", line 159, in to_pdf
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr))
OSError: wkhtmltopdf exited with non-zero code 1. error:
The switch --print-media-type, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-frappe'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

**Comment by eclipsed-ninja** [comment]
No expert by any means, but looks like an issue not related to erpnext but your server setup. I believe you're not running any display on that server. I had this issue with wkhtmltopdf and the solution was to install and setup xvfb.
https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

This should possibly fix the issue as erpnext might be using wkhtmltopdf or something similar which is dependent on x server.

**Comment by ankush** [comment]
@eclipsed-ninja has correctly identified the root cause. Not related to  ERPNext / Frappe.
