### ISSUE TITLE
Server Error => KeyError: ‘shopping_cart’ v13.11

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#27760]
## Description of the issue
Can't access to "Shopping Cart Settings"
## Context information (for bug reports)
**Output of `bench version`**
```
ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)

```

## Steps to reproduce the issue

1. Type on Search bar "Shopping Cart Settings"
2. Pop up Server Error

### Observed result
![Server Error](https://user-images.githubusercontent.com/25084259/135761512-a677bd5b-4730-46d3-876c-a5fbf24c54f8.png)
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1198, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 71, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 49, in load_assets
    self.add_code()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 81, in add_code
    path = os.path.join(get_module_path(self.module), 'doctype', scrub(self.name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 167, in get_module_path
    return frappe.get_module_path(module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 981, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
KeyError: 'shopping_cart'
```

**Comment by ankush** [comment]
Use "E commerce settings". This will get fixed in next release: https://github.com/frappe/erpnext/pull/27700

**Comment by jewelc** [comment]
Version 13.12.0 Released but this fix #27700 is not there..

**Comment by ankush** [comment]
@jewelc Thanks for pointing it out. We will be making another release shortly. 


https://github.com/frappe/erpnext/pull/27831

**Comment by bryanjcp** [comment]
Hello guys have a fix about this issue?? it happens the same to me.. 

![image](https://user-images.githubusercontent.com/98916252/152230054-f091b8ad-6b6b-4ff0-bf7e-cd6c6c3f69ab.png)
