### ISSUE TITLE
could not generate the salary slip when the salary structure is assigned from the middle of the month

### ISSUE THREAD

**Issue by onlinebizsoft** [frappe/erpnext#27774]
## Description of the issue

I have an employee who join the company in the middle of the month so we have applied a salary structure for him from the middle of the month but then the salary slip can't be generated because it requires the salary structure assigned from the first date of the month

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 100, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/payroll_entry/payroll_entry.py", line 583, in create_salary_slips_for_employees
    ss.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 961, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1148, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 853, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 51, in validate
    self.get_emp_and_working_day_details()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 189, in get_emp_and_working_day_details
    self.pull_sal_struct()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 242, in pull_sal_struct
    make_salary_slip(self._salary_structure_doc.name, self)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_structure/salary_structure.py", line 190, in make_salary_slip
    }, target_doc, postprocess, ignore_child_tables=True, ignore_permissions=ignore_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 127, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_structure/salary_structure.py", line 179, in postprocess
    target.run_method('process_salary_structure', for_preview=for_preview)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1148, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1131, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 853, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 1175, in process_salary_structure
    self.calculate_net_pay()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 470, in calculate_net_pay
    self.calculate_component_amounts("earnings")
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 498, in calculate_component_amounts
    self.add_structure_components(component_type)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 506, in add_structure_components
    data = self.get_data_for_eval()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/payroll/doctype/salary_slip/salary_slip.py", line 542, in get_data_for_eval
    frappe.bold(formatdate(date_to_validate)),
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 432, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please assign a Salary Structure for Employee <b>xxxxxxxxx</b> applicable from or before <b>01/09/2021</b> first
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by onlinebizsoft** [comment]
Actually the bug also happened when we have a salary structure applied in the middle of the month (and another structure applied from previous month)

**Comment by onlinebizsoft** [comment]
Please re=open @ankush
