### ISSUE TITLE
Session Start Failed - Notification Settings

### ISSUE THREAD

**Issue by manuthu** [frappe/erpnext#28001]
## Description of the issue
Dear team,

we recently upgraded ErpNext from v12 to the latest v13. 

The upgrade process went well but now some users are unable to login. Below is a description of the error Im getting from the logs.

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/app.py", line 23, in get_context
    boot = frappe.sessions.get()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 132, in get
    bootinfo = get_bootinfo()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/boot.py", line 65, in get_bootinfo
    bootinfo.notification_settings = get_notification_settings()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/boot.py", line 331, in get_notification_settings
    return frappe.get_cached_doc('Notification Settings', frappe.session.user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 834, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 877, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 75, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 113, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 156, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 438, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 417, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 371, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Notification Settings <email> not found
```

**Output of `bench version`**

```
(env) ~/frappe-bench$ bench --version
5.0.0-dev
```

## Additional information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by kunhimohamed** [comment]
Execute the patch `frappe.patches.v12_0.create_notification_settings_for_user`
