### ISSUE TITLE
Error in Consolidated Financial Statement

### ISSUE THREAD

**Issue by vincentnjara** [frappe/erpnext#28063]
Hi 
I updated to the versionv13.13.0 (version-13) but I am getting the server error "unsupported operand type(s) for +=: 'int' and 'NoneType'" at consolidated financial statement report. Please help to resolve it

Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:387 Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 1199, in call
    return fn(*args, **newargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 615, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 236, in run
    result = generate_report_result(report, filters, user, custom_columns)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 78, in generate_report_result
    res = report.execute_script_report(filters)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 125, in execute_script_report
    res = self.execute_module(filters)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 50, in execute
    data, message, chart, report_summary = get_balance_sheet_data(fiscal_year, companies, columns, filters)
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 78, in get_balance_sheet_data
    message, opening_balance = prepare_companywise_opening_balance(asset, liability, equity, companies)
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 118, in prepare_companywise_opening_balance
    opening_value += get_opening_balance(account_name, data, company)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by ankush** [comment]
fixed here: https://github.com/frappe/erpnext/pull/28035
