### ISSUE TITLE
Redis Cluster MOVED error

### ISSUE THREAD

**Issue by utkudarilmaz** [frappe/erpnext#28129]
## Description of the issue

I installed the ERPNext with Helm and also I installed bitnami/redis-cluster chart for redis-queue and redis-socketio on my K8S cluster. ERPNext worker nodes throwing an error after the connected to Redis Cluster. 

Is ERPNext not supporting Redis Cluster?

## Context Information

```
erpnext 13.13.0
frappe 13.13.0
redis-cluster 6.2.6
bitnami/redis-cluster helm version 7.0.8
frappe/erpnext helm version 3.2.31
```

### Expected result

All ERPNext pods running without throw exception.

### Stacktrace / full error message

```
Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache-master:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/worker.py", line 12, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/worker.py", line 7, in main
    start_worker(queue, False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 155, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level = logging_level)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/rq/worker.py", line 550, in work
    self.register_birth()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/rq/worker.py", line 286, in register_birth
    if self.connection.exists(self.key) and \
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/client.py", line 1581, in exists
    return self.execute_command('EXISTS', *names)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MOVED 10476 10.23.2.124:6379
```

**Comment by ankush** [comment]
This belongs in https://discuss.erpnext.com/

also checkout https://helm.erpnext.com/faq.html

**Comment by utkudarilmaz** [comment]
You can find topic on https://discuss.erpnext.com/t/redis-cluster-moved-error/81859
