### ISSUE TITLE
SocketIO Connects to Port 9000 : Error socket.io Failed to load resource (server not found) --> http://localhost:9000/socket.io/... 

### ISSUE THREAD

**Issue by ATHRIBIS** [frappe/erpnext#28167]
## _About socket.io pages_
[https://discuss.erpnext.com/t/use-https-socket-io-in-development-environment/48505](https://discuss.erpnext.com/t/use-https-socket-io-in-development-environment/48505) (Use HTTPS / Socket.io in development environment, socket.io doesnt work with https)
[https://discuss.erpnext.com/t/frappe-v8-0-20-later-socketio-error/22973/2](https://discuss.erpnext.com/t/frappe-v8-0-20-later-socketio-error/22973/2) (try to resolve http:6787/socket.io/?EIO=3&transport=polling&t=1493040997461-38 Failed to load resource: net::ERR_NAME_NOT_RESOLVED)
https://stackoverflow.com/questions/40950423/how-to-install-erpnext-using-apache
https://about.lovia.life/docs/infrastructure/erpnext/install-erpnext-on-ubuntu-vm/#troubleshooting-4-socketio-connects-to-port-9000 (Troubleshooting 4: SocketIO Connects to Port 9000)

## Exact error
**On Safari**
<img width="1141" alt="Capture d’écran 2021-10-30 à 20 02 53" src="https://user-images.githubusercontent.com/54010689/139553776-717f79d6-f3c2-4a35-a793-29a40d0e1667.png">

**On Firefox**
`Blocking of a multi-origin request (Cross-Origin Request): the "Same Origin" policy does not allow to consult the remote resource located on http://localhost:9000/socket.io/?EIO=3&transport=polling&t=NpItWmb. Reason: failure of the CORS request.`

By the way i did some research about CORS : https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
Maybe the error comes from the fact that the connection is in http and not https ?
Whether the mode is in developer or in production, the error is always there, I tried both.
Edit :
from [https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed](https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed)
> The HTTP request using CORS failed due to the HTTP connection which failed either at the network level or at the protocol level. The error is not directly related to CORS, but is some basic network error.

## Description of the issue

Hello everyone, I have a problem with socket.io
I am in dev mode, local usage.
I first noticed that the email function (send a mail) was not working.
I opened the logs and the console, and everything was filled with an error. It is not directly related to the mail function, it appears every few seconds when I open the desktop (The error appears in the browser console and in the bench console)
I tried to see on the internet where it came from, I didn't understand everything. I tried some tricks, but I'm not very good in linux.

I noticed that nginx was not even installed (seems like web server run under python), I thought it might be related so I installed it. I looked for how to put ERPNext on Nginx, I did the nginx bench setup with the ln command ... for the configuration. 
But nginx did not start anymore because : 
`nginx: [emerg] duplicate upstream "frappe-bench-frappe" in /etc/nginx/conf.d/nginx.conf:1`

In addition, I saw a solution to modify Procfile :
web: bench serve --port 8000
change to :
web: sudo bench serve --port 8000

This results in my error : 
`Failed to load resource: Could not connect to server.  -->    localhost:9000/socket.io/...`
Becomes :
`Error 404,    -->    localhost:8000/socket.io/...`
So I don't understand anything

I think the problem is that ERPNext is not on nginx. Because when I connect to localhost:80 (nginx port), there is the default page Welcome to nginx.
How to solve the error in console log ? (see the image)

--------
[https://stackoverflow.com/a/43861906](https://stackoverflow.com/a/43861906) 

> Socket.io was the main problem, finally I found a way to make it work (transport=polling requests to /socket.io must be http, all other requests to /socket.io must be websocket).

This solution proposes to change the configuration of apache. However, if I understood correctly, it is not apache that takes care of the web server.
```
$ netstat -nplt
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      2213/python         
tcp        0      0 127.0.0.1:11000         0.0.0.0:*               LISTEN      2202/redis-server 1 
tcp        0      0 127.0.0.1:12000         0.0.0.0:*               LISTEN      2196/redis-server 1 
tcp        0      0 127.0.0.1:13000         0.0.0.0:*               LISTEN      2189/redis-server 1 
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      578/redis-server 12 
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      891/mysqld          
tcp6       0      0 :::9000                 :::*                    LISTEN      2216/node           
...
```
Why tcp6 for node (port 9000 who is causing trouble) ?

https://stackoverflow.com/questions/47797322/node-js-server-only-listening-on-ipv6

> You need to specify an IPV4 address when you call the listen(), I had the same issue with the http module. If I use this:

I found this by a research of "server.listen" https://github.com/frappe/frappe/blob/fbe4bdaa9ece56f79f5a96702d44ba8c4ea3f5da/socketio.js
So i change this file on my server. Exemple :
`server.listen(13882, function() { });`
comes
`server.listen(13882, "0.0.0.0", function() { });`
The ipv4 is specified !
```
$ netstat -nplt
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      4198/node
```
But iit doesnt solve the probleme, the error persist.

-----------
I found this : https://about.lovia.life/docs/infrastructure/erpnext/install-erpnext-on-ubuntu-vm/#troubleshooting-4-socketio-connects-to-port-9000

We can check the config `bench –site [mysite] show-config`
If I understood correctly, the config is linked to javascript (executed on the client side): 
desk.js -> socketio_client.js -> frappe.socketio.init () -> frappe.socketio.get_host ()
And in socketio_client.js  the input port default is 3000.

> In implementation of “frappe.socketio.get_host(port)” changes the actual host, due to window.dev_server==true and frappe.boot.socketio_port==9000:

```
	get_host: function(port = 3000) {
		var host = window.location.origin;
		if(window.dev_server) {
			var parts = host.split(":");
			port = frappe.boot.socketio_port || port.toString() || '3000';
			if(parts.length > 2) {
				host = parts[0] + ":" + parts[1];
			}
			host = host + ":" + port;
		}
		return host;
	},
```
And now, i don't understand (load balancer what is that) :

> Although you can run bench start –no-dev but this will result in Error 404 as the bench server does not reverse proxy to socketio server. So the least annoying workaround is:
> 
> 1. open port 9000, and
> 
> 2. Configure load balancer for that too. Don’t forget to set ALB’s security group including “socketio-9000-server”.
> 
> 3. Meaning you can’t use CDN for ERPNext development/staging environment.
> 
> If it goes well you’ll get 101 Switching Protocols response on your browser:

So, i went to https://github.com/frappe/frappe/blob/c78be3d28d7a86795aae249d0bfc71b53ea479b6/frappe/public/js/frappe/socketio_client.js to find the path of the crappy file, and i change in it all 3000 by 9000. It doesnt work.

I change 9000 to 3000 in the common config file, in site folder. Doesnt solve probleme, the error was just http://localhost:3000/socket.io/... 

----
I tried to find a redis or socketio configuration, I found redis_socketio.conf 
/home/frappe/.bench/bench/config/templates/redis_socketio.conf
/home/frappe/frappe-bench/config/redis_socketio.conf
/usr/local/lib/python3.6/dist-packages/bench/config/templates/redis_socketio.conf

## Context information (for bug reports)

**ERPNext version**
I download the .OVA file (for virtual box) with ERPNext v12, and I manually upgraded to v13.
When I type `bench update`
--> `Cannot proceed with update: You have local changes in app "frappe" that are not committed.`
Maybe my frappe is "corrupt" or something is wrong in ?
**Output of `bench version`**
I think I have the last version of bench ? I did a bench update yesterday
So I just noticed while doing the bug report that it displayed this :

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 774, in get_version
    app_info.version = getattr(app_hooks, f"{app_info.branch}_version", None) or module.__version__
AttributeError: module 'paypal_integration' has no attribute '__version__
```

### Steps to reproduce the issue

1. Start bench normally (bench start)
2. Connect to the office (http://localhost:8000/app)
--> ERPNext announces that it cannot connect to localhost:9000/socket.io/...

### What i did and change nothing

```
sudo supervisorctl start all
sudo supervisorctl stop all
```
```
bench clear-cache
bench clear-website-cache
```
```
bench setup socketio
```
```
cd ~/frappe-bench
sudo npm install -g yarn
bench setup requirements --node
bench update --requirements
bench setup socketio
bench build
bench update
bench --site [sitename] set-maintenance-mode off
```
When i do `bench update` :

```
error /home/frappe/frappe-bench/apps/frappe/node_modules/node-sass: Command failed.

```
then are detail all gcc things about node-sass
```
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/usr/local/bin/node" "/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/frappe/frappe-bench/apps/frappe/node_modules/node-sass
gyp ERR! node -v v16.13.0
gyp ERR! node-gyp -v v3.8.0
```
now when i bench start i get
```
Error in: /home/frappe/frappe-bench/apps/frappe/frappe/public/scss/website.scss
23:44:03 watch.1          | Error: You need to install either node-sass or sass in order to process Sass files
23:44:03 watch.1          |     at /home/frappe/frappe-bench/apps/frappe/node_modules/rollup-plugin-postcss/dist/index.js:349:15
23:44:03 watch.1          |     at new Promise (<anonymous>)
23:44:03 watch.1          |     at Object.process (/home/frappe/frappe-bench/apps/frappe/node_modules/rollup-plugin-postcss/dist/index.js:345:12)
23:44:03 watch.1          |     at /home/frappe/frappe-bench/apps/frappe/node_modules/rollup-plugin-postcss/dist/index.js:618:33
23:44:03 watch.1          |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
so i did
```
yarn add node-sass in apps/frappe dir
```
i just wasted my time

_**My problem of email not sending is always here**_
### Logs
./logs/node-socketio.error.log
./logs/redis-socketio.log
./logs/node-socketio.log
./logs/redis-socketio.error.log
I don't have any of these log files
My logs folder contains nothing about the error 

### Stacktrace / full error message

This is what I get when I [bench start](url)
```
18:02:04 system           | redis_cache.1 started (pid=4032)
18:02:04 system           | redis_queue.1 started (pid=4036)
18:02:04 system           | web.1 started (pid=4045)
18:02:04 system           | socketio.1 started (pid=4047)
18:02:04 system           | watch.1 started (pid=4049)
18:02:04 system           | worker_default.1 started (pid=4052)
18:02:04 system           | worker_short.1 started (pid=4063)
18:02:04 system           | schedule.1 started (pid=4061)
18:02:04 system           | redis_socketio.1 started (pid=4046)
18:02:04 system           | worker_long.1 started (pid=4048)
18:02:04 redis_socketio.1 | 4059:C 30 Oct 18:02:04.248 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
18:02:04 redis_socketio.1 | 4059:C 30 Oct 18:02:04.248 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=4059, just started
18:02:04 redis_socketio.1 | 4059:C 30 Oct 18:02:04.248 # Configuration loaded
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.249 * Increased maximum number of open files to 10032 (it was originally set to 1024).
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.250 * Running mode=standalone, port=12000.
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.251 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.251 # Server initialized
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.251 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:02:04 redis_socketio.1 | 4059:M 30 Oct 18:02:04.251 * Ready to accept connections
18:02:04 redis_queue.1    | 4041:C 30 Oct 18:02:04.259 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
18:02:04 redis_queue.1    | 4041:C 30 Oct 18:02:04.259 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=4041, just started
18:02:04 redis_queue.1    | 4041:C 30 Oct 18:02:04.259 # Configuration loaded
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.259 * Increased maximum number of open files to 10032 (it was originally set to 1024).
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.260 * Running mode=standalone, port=11000.
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.260 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.260 # Server initialized
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.260 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:02:04 redis_queue.1    | 4041:M 30 Oct 18:02:04.260 * Ready to accept connections
18:02:04 redis_cache.1    | 4038:C 30 Oct 18:02:04.259 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
18:02:04 redis_cache.1    | 4038:C 30 Oct 18:02:04.259 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=4038, just started
18:02:04 redis_cache.1    | 4038:C 30 Oct 18:02:04.259 # Configuration loaded
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 * Increased maximum number of open files to 10032 (it was originally set to 1024).
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 * Running mode=standalone, port=13000.
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 # Server initialized
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:02:04 redis_cache.1    | 4038:M 30 Oct 18:02:04.260 * Ready to accept connections
18:02:05 web.1            | /home/frappe/frappe-bench/env/lib/python3.6/site-packages/bleach_whitelist/bleach_whitelist.py:7: DeprecationWarning: bleach-allowlist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-whitelist
18:02:05 web.1            |   DeprecationWarning
18:02:05 schedule.1       | /home/frappe/frappe-bench/env/lib/python3.6/site-packages/bleach_whitelist/bleach_whitelist.py:7: DeprecationWarning: bleach-allowlist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-whitelist
18:02:05 schedule.1       |   DeprecationWarning
18:02:05 socketio.1       | listening on *: 9000
18:02:05 watch.1          | /home/frappe/frappe-bench/env/lib/python3.6/site-packages/bleach_whitelist/bleach_whitelist.py:7: DeprecationWarning: bleach-allowlist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-whitelist
18:02:05 watch.1          |   DeprecationWarning
18:02:05 web.1            |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
18:02:05 web.1            |  * Restarting with inotify reloader
18:02:05 web.1            | /home/frappe/frappe-bench/env/lib/python3.6/site-packages/bleach_whitelist/bleach_whitelist.py:7: DeprecationWarning: bleach-allowlist has been renamed bleach-allowlist. It will not receive further updates under the old name. See https://pypi.org/project/bleach-whitelist
18:02:05 web.1            |   DeprecationWarning
18:02:05 watch.1          | yarn run v1.22.10
18:02:06 watch.1          | warning ../../../package.json: No license field
18:02:06 watch.1          | $ node rollup/watch.js
18:02:06 web.1            |  * Debugger is active!
18:02:06 web.1            |  * Debugger PIN: 295-785-035
18:02:11 watch.1          | 
18:02:11 watch.1          | Rollup Watcher Started
18:02:11 watch.1          | 
18:02:11 watch.1          | Watching...
18:02:13 watch.1          | Browserslist: caniuse-lite is outdated. Please run:
18:02:13 watch.1          | npx browserslist@latest --update-db
18:02:13 watch.1          | Rebuilding frappe-web-b4.css
18:02:14 watch.1          | Rebuilding frappe-chat-web.css
18:02:14 watch.1          | Rebuilding chat.js
18:02:15 watch.1          | Rebuilding frappe-recorder.min.js
18:02:17 watch.1          | Rebuilding checkout.min.js
18:02:17 watch.1          | Rebuilding frappe-web.min.js
18:02:19 watch.1          | Rebuilding bootstrap-4-web.min.js
18:02:20 watch.1          | Rebuilding control.min.js
18:02:24 watch.1          | Rebuilding dialog.min.js
18:02:26 watch.1          | Rebuilding desk.min.css
18:02:27 watch.1          | Rebuilding printview.css
18:02:27 watch.1          | Rebuilding desk.min.js
18:02:29 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:29] "GET /index HTTP/1.1" 200 -
18:02:29 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:29] "POST / HTTP/1.1" 200 -
18:02:34 watch.1          | Rebuilding form.min.js
18:02:37 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:37] "GET /app HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "POST /api/method/frappe.core.doctype.user_permission.user_permission.get_user_permissions HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/email.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/chat-notification.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/click.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/erpnext/sounds/call-disconnect.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/cancel.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/delete.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/chat-message.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/error.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "POST /api/method/frappe.desk.doctype.event.event.get_events HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/alert.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/submit.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/erpnext/sounds/incoming-call.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/email.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/click.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/chat-notification.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "POST /api/method/frappe.desk.doctype.tag.tag.get_tags_list_for_awesomebar HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /api/method/frappe.desk.reportview.get_list?fields=%5B%22*%22%5D&limit=20&order_by=creation+desc&doctype=Notification+Log&_=1635616957781 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/erpnext/sounds/call-disconnect.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/cancel.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/delete.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/chat-message.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/error.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/alert.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/frappe/sounds/submit.mp3 HTTP/1.1" 200 -
18:02:38 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:38] "GET /assets/erpnext/sounds/incoming-call.mp3 HTTP/1.1" 200 -
18:02:39 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:39] "POST /api/method/frappe.utils.change_log.show_update_popup HTTP/1.1" 200 -
18:02:40 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:40] "POST /api/method/frappe.desk.desktop.get_desktop_page HTTP/1.1" 200 -
18:02:40 web.1            | 10.0.2.2 - - [30/Oct/2021 18:02:40] "GET /api/method/frappe.desk.reportview.get_list?filters=%7B%22name%22%3A%22[mysitename]%40gmx.com%22%7D&fields=%5B%22*%22%5D&doctype=Dashboard+Settings&limit=20&_=1635616957782 HTTP/1.1" 200 -
18:02:43 watch.1          | Rebuilding list.min.js
18:02:45 watch.1          | Rebuilding report.min.css
18:02:45 watch.1          | Rebuilding report.min.js
18:02:47 watch.1          | Rebuilding web_form.min.js
18:02:47 watch.1          | Rebuilding web_form.css
18:02:47 watch.1          | Rebuilding email.css
18:02:47 watch.1          | Rebuilding barcode_scanner.min.js
18:02:48 watch.1          | Rebuilding user_profile_controller.min.js
18:02:48 watch.1          | Rebuilding login.css
18:02:48 watch.1          | Rebuilding data_import_tools.min.js
18:02:51 watch.1          | Rebuilding frappe-web-b4.css
18:02:52 watch.1          | Rebuilding frappe-chat-web.css
18:02:53 watch.1          | Rebuilding desk.min.css
18:02:53 watch.1          | Rebuilding printview.css
18:02:53 watch.1          | Rebuilding report.min.css
18:02:53 watch.1          | Rebuilding web_form.css
18:02:53 watch.1          | Rebuilding email.css
18:02:53 watch.1          | Rebuilding login.css
18:02:53 watch.1          | Rebuilding erpnext.css
18:02:53 watch.1          | Rebuilding marketplace.css
18:02:53 watch.1          | Rebuilding erpnext-web.min.js
18:02:53 watch.1          | Rebuilding erpnext-web.css
18:02:53 watch.1          | Rebuilding marketplace.min.js
18:02:57 watch.1          | Rebuilding erpnext.min.js
18:02:58 watch.1          | Rebuilding item-dashboard.min.js
18:02:58 watch.1          | Rebuilding point-of-sale.min.js
18:03:00 watch.1          | Rebuilding bank-reconciliation-tool.min.js
18:03:01 watch.1          | Rebuilding e-commerce.min.js
18:03:01 watch.1          | Rebuilding hierarchy-chart.min.js
18:03:05 watch.1          | Rebuilding erpnext.css
18:03:05 watch.1          | Rebuilding marketplace.css
18:03:05 watch.1          | Rebuilding erpnext-web.css
18:03:28 web.1            | 127.0.0.1 - - [30/Oct/2021 18:03:28] "GET /assets/css/printview.css HTTP/1.1" 200 -
18:03:30 web.1            | 127.0.0.1 - - [30/Oct/2021 18:03:30] "GET /assets/css/printview.css HTTP/1.1" 200 -
18:04:14 web.1            | 127.0.0.1 - - [30/Oct/2021 18:04:14] "GET /assets/css/printview.css HTTP/1.1" 200 -
18:04:17 web.1            | 127.0.0.1 - - [30/Oct/2021 18:04:17] "GET /assets/css/printview.css HTTP/1.1" 200 -

```
## Additional information

As you can see I really don't understand anything about how frappe works ahah
I use VirtualBox, with the .ova available on the website of frappe ERPNext.
Ports redirection : 80 to 80, 8000 to 8000 and 3022 to 22 (just for ssh)
I'm not English so I'm sorry if I'm not very clear

**Comment by ATHRIBIS** [comment]
**On Safari**
<img width="1141" alt="Capture d’écran 2021-10-30 à 20 02 53" src="https://user-images.githubusercontent.com/54010689/139553776-717f79d6-f3c2-4a35-a793-29a40d0e1667.png">

**On Firefox**
`Blocking of a multi-origin request (Cross-Origin Request): the "Same Origin" policy does not allow to consult the remote resource located on http://localhost:9000/socket.io/?EIO=3&transport=polling&t=NpItWmb. Reason: failure of the CORS request.`


Edit: i deleted everything and start again from v13.13.0
