### ISSUE TITLE
Update Patches References a Query Builder attribute from the Frappe Module Causing Update Script to Fail

### ISSUE THREAD

**Issue by Nathaniel401** [frappe/erpnext#28322]
## Description of the issue
Running the traditional 'bench update' command fails when upgrading to 13.13.0 or 13.14.0, due to referencing the newly announced query builder attribute (qb) against the Frappe module.

## Context information (for bug reports)
From what I can read, the query builder is supposed to be on the Frappe 14 stack (https://discuss.erpnext.com/t/announcement-introducing-frappe-query-builder/79092), where ERPNext 13.13.0 and 13.14.0 are running in tandem with Frappe 13. 

**Output of `bench version`**
```
erpnext 13.14.0 (Note: upgrading from 13.12.1, upgrade failed but due to error noted below but it's reporting 13.14.0 right now)
frappe 13.2.1
```

## Steps to reproduce the issue

1. Upgrade ERPNext using 'bench update' command
2.
3.

### Observed result
Upgrade failure

### Expected result
Upgrade success

### Stacktrace / full error message

```
Migrating erp.internalopscovers.com
Executing erpnext.patches.v13_0.fetch_thumbnail_in_website_items in erp.internalopscovers.com (_9a6ff083146bae9f)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erpadmin/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/commands/site.py", line 301, in migrate
    skip_search_index=skip_search_index
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/patches/v13_0/fetch_thumbnail_in_website_items.py", line 6, in execute
    website_item = frappe.qb.DocType("Website Item").as_("wi")
AttributeError: module 'frappe' has no attribute 'qb'
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
> frappe 13.2.1


This is the issue. Upgrade frappe version to latest too.

**Comment by Nathaniel401** [comment]
Hey @ankush, how do I upgrade Frappe first? Why doesn't "bench update" do that?

Also why is it referencing a Beta release of Frappe when 13.14.0 is being paired with ERPNext 13.14.0?

**Comment by ankush** [comment]
`bench update` is supposed to do that too, unless you've some local change that's causing update to fail for frappe. Try `bench update --reset` (this will wipe local changes in code)

**Comment by Nathaniel401** [comment]
Will try that right now @ankush thank you! Will report back momentarily.

**Comment by Nathaniel401** [comment]
Hi @ankush that worked perfectly! Many thanks!
