### ISSUE TITLE
pymysql.err.OperationalError: (4078, "Illegal parameter data types varchar and row for operation '='")

### ISSUE THREAD

**Issue by edwinorlando83** [frappe/erpnext#28344]
The error is when choosing 2 forms of payment in POS configuration

![image](https://user-images.githubusercontent.com/11822274/141277626-b22df012-ebc8-4896-993c-93dfe3792d8c.png)

![image](https://user-images.githubusercontent.com/11822274/141278010-ba7ca8ef-5ea0-4805-8e33-656bf4440a8b.png)

**Comment by ankush** [comment]
can you press F12 and go to "console" and copy paste the full error log?

**Comment by edwinorlando83** [comment]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1207, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 240, in run_doc_method
    response = doc.run_method(method, args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 388, in set_missing_values
    profile = self.set_pos_fields(for_validate)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 330, in set_pos_fields
    update_multi_mode_option(self, profile)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2036, in update_multi_mode_option
    mode_of_payments_info = get_mode_of_payments_info(mode_of_payments, doc.company)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 2075, in get_mode_of_payments_info
    """, (company, mode_of_payments), as_dict=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 148, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (4078, "Illegal parameter data types varchar and row for operation '='")

**Comment by ankush** [comment]
This was fixed recently https://github.com/frappe/erpnext/pull/28321 

@nextchamp-saqib

**Comment by edwinorlando83** [comment]
thanks, I will update the ERpNext

**Comment by ankush** [comment]
It's probably not released yet. But if you have access to code you can try cherry-picking the commit if you want to fix it immediately.

**Comment by edwinorlando83** [comment]
Ok, I will change the code for the moment

**Comment by ankush** [comment]
closing this as it's a fixed issue. reopen / comment if required.
