### ISSUE TITLE
Error on submitting Asset Value Adjustment - ERPNext: v13.14.1 (version-13)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#28395]
Error: **AttributeError: 'Asset' object has no attribute 'get_depreciation_amount'**

![image](https://user-images.githubusercontent.com/1822868/141784403-26310dda-4006-4e08-bc48-4741128a6541.png)

**Comment by ankush** [comment]
Share full traceback please so it's easier to find root cause. 

Most likely coming from here: https://github.com/frappe/erpnext/blob/952fc87c99f8b3a084d132cde52124f975ef6f95/erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py#L114-L115

**Comment by muchai** [comment]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 936, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 919, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1004, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py", line 26, in on_submit
    self.reschedule_depreciations(self.new_asset_value)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py", line 116, in reschedule_depreciations
    depreciation_amount = asset.get_depreciation_amount(value_after_depreciation,
AttributeError: 'Asset' object has no attribute 'get_depreciation_amount'

request.js:418 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1207, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 936, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 919, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1004, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py", line 26, in on_submit
    self.reschedule_depreciations(self.new_asset_value)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py", line 116, in reschedule_depreciations
    depreciation_amount = asset.get_depreciation_amount(value_after_depreciation,
AttributeError: 'Asset' object has no attribute 'get_depreciation_amount'
