### ISSUE TITLE
Migrating sites after patch in V13

### ISSUE THREAD

**Issue by MOM01990** [frappe/erpnext#28568]
I keep getting the below error after bench update or bench update --patch; right after migrating site

frappe-bench$ bench update --patch
Backing up sites...
Backup Summary for [SITE] at 2021-11-25 23:56:07.597506
Config : ./[SITE]/private/backups/20211125_235604-[SITE]-site_config_backup.json 315.0B
Database: ./[SITE]/private/backups/20211125_235604-[SITE]-database.sql.gz    5.6MiB
Backup for Site [SITE] has been successfully completed
Patching sites...
Migrating [SITE]
Executing erpnext.patches.v13_0.create_leave_policy_assignment_based_on_employee_current_leave_policy in [SITE] (_1bd3e0294da19198)
Traceback (most recent call last):
 File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
  "__main__", mod_spec)
 File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
  exec(code, run_globals)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
  main()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
  click.Group(commands=commands)(prog_name='bench')
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
  return self.main(*args, **kwargs)
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
  rv = self.invoke(ctx)
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
  return callback(*args, **kwargs)
 File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
  ret = f(frappe._dict(ctx.obj), *args, **kwargs)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 309, in migrate
  skip_search_index=skip_search_index
 File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
  frappe.modules.patch_handler.run_all(skip_failing)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
  run_patch(patch)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
  if not run_single(patchmodule = patch):
 File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
  return execute_patch(patchmodule, method, methodargs)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
  frappe.get_attr(patchmodule.split()[0] + ".execute")()
 File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_leave_policy_assignment_based_on_employee_current_leave_policy.py", line 21, in execute
  create_assignment(employee.name, employee.leave_policy)
 File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_leave_policy_assignment_based_on_employee_current_leave_policy.py", line 69, in create_assignment
  lpa.save()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
  return self._save(*args, **kwargs)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
  self.insert()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 232, in insert
  self._validate_links()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 834, in _validate_links
  frappe.CancelledLinkError)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 439, in throw
  msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
 File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
  _raise_exception()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in _raise_exception
  raise raise_exception(msg)
frappe.exceptions.CancelledLinkError: Cannot link cancelled document: Leave Policy: HR-LPOL-2020-00001

**Comment by Olawale1** [comment]
This issue is still not fixed. Kindly re-open!

**Comment by Olawale1** [comment]
In the meantime, is there any suggestion on how to get around this pls ?

**Comment by Olawale1** [comment]
Hi @ruchamahabal 

Trust you're doing well. I'm not sure if this is related to your patch but now there is a new error when updating

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 47, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 105, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_leave_policy_assignment_based_on_employee_current_leave_policy.py", line 59, in execute
    create_assignment(
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_leave_policy_assignment_based_on_employee_current_leave_policy.py", line 88, in create_assignment
    lpa.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 22, in on_submit
    self.grant_leave_alloc_for_employee()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 72, in grant_leave_alloc_for_employee
    frappe.throw(_("Leave already have been assigned for this Leave Policy Assignment"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Leave already have been assigned for this Leave Policy Assignment
```
This happens even in sites that do not have any Leave Policy Assignment record! Kindly confirm if I should open a new thread for this

Thanks

**Comment by ruchamahabal** [comment]
@Olawale1 This patch has been removed completely now https://github.com/frappe/erpnext/pull/31097 since it was unnecessary. Not sure why was it added in the first place.

**Comment by Olawale1** [comment]
Fantastic! I agree completely.  Hope this 'un-patch' will be released in production soon

Thanks a lot
