### ISSUE TITLE
Validations for Custom field option value for Data type fields

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#28637]
After upgrading from v12 to v13 the below error comes while `bench --site test.site migrate --skip-failing`.

Migrating test.site
Executing erpnext.patches.v12_0.add_eway_bill_in_delivery_note in test.site (_1234567890)
Failed to execute patch
Executing erpnext.patches.v13_0.check_is_income_tax_component #22-06-2020 in test.site (_1234567890)
Failed to execute patch
Executing erpnext.patches.v13_0.setup_fields_for_80g_certificate_and_donation in test.site (_1234567890)
Failed to execute patch
Executing erpnext.patches.v12_0.add_gst_category_in_delivery_note in test.site (_1234567890)
Failed to execute patch

**Comment by ankush** [comment]
Can't do much without tracebacks for patch failure. can you share full tracebacks?

**Comment by mohsinalimat** [comment]
log of Executing erpnext.patches.v12_0.add_eway_bill_in_delivery_note

Migrating site1.local
Executing erpnext.patches.v12_0.add_eway_bill_in_delivery_note in site1.local (_1234567890)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 306, in migrate
    migrate(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v12_0/add_eway_bill_in_delivery_note.py", line 11, in execute
    create_custom_field('Delivery Note', {
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 142, in create_custom_field
    custom_field.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 268, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1001, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 76, in on_update
    validate_fields_for_doctype(self.dt)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 751, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1062, in validate_fields
    validate_data_field_type(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1016, in validate_data_field_type
    frappe.msgprint(text_str + df_options_str, title="Invalid Data Field", raise_exception=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 374, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: <b>Issued By</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Name</li><li>Phone</li><li>URL</li><li>Barcode</ul>

**Comment by ankush** [comment]
You've added "Issued By" in the option of some custom field or maybe it was added before this validation was put in place. 

Removing that from "Option" should fix it.

**Comment by mohsinalimat** [comment]
Old version 

ERPNext: v12.16.2 (version-12)

Frappe Framework: v12.13.0 (version-12)

and migrate to v13 latest above error comes.

**Comment by mohsinalimat** [comment]
> Old version
> 
> ERPNext: v12.16.2 (version-12)
> 
> Frappe Framework: v12.13.0 (version-12)
> 
> and migrate to v13 latest above error comes.

@ankush please see this message.

**Comment by ankush** [comment]
I saw, check my previous message. You'll most likely have to find which fields have "Issued By" set as option (can be found using filters). Then remove that option.

**Comment by ankush** [comment]
There was a patch added to fix this exact same thing.

https://github.com/frappe/erpnext/pull/27200

Maybe that's already executed on your site or maybe it needs to be reordered.

**Comment by mohsinalimat** [comment]
> You've added "Issued By" in the option of some custom field or maybe it was added before this validation was put in place. 
> 
> 
> 
> Removing that from "Option" should fix it.

I don't know how to solve this.

Can you please guide me in video or screenshots or other way?

**Comment by ankush** [comment]
Potential solution:

https://github.com/frappe/erpnext/pull/27200 

The patch for custom field option correction seems to be executing in an incorrect order. This patch should be higher up execution order (near start of v13 patches)

Mostly just reordering the patch execution and re-executing it should work.

**Comment by ankush** [comment]
>       I don't know how to solve this.

>  Can you please guide me in video or screenshots or another way?

go to Custom Field list and find which `Data` field has `Option` equal to `Issued By`. You can find them with filters. 

Alternatively if you can execute the patch manually, then execute the patch I linked above.

**Comment by mohsinalimat** [comment]
> > ```
> >   I don't know how to solve this.
> > ```
> 
> 
> > Can you please guide me in video or screenshots or another way?
> 
> 
> go to Custom Field list and find which `Data` field has `Option` equal to `Issued By`. You can find them with filters.
> 
> 
> Alternatively if you can execute the patch manually, then execute the patch I linked above.

![Screenshot 2021-12-10 at 2 25 38 PM](https://user-images.githubusercontent.com/973676/145545962-1e96b18e-39a1-48d5-b0b3-bfc915b31341.png)

**Comment by ankush** [comment]
Go to delivery note > customize form and erase the "Option" value. Link fields can have options, data fields can't.

**Comment by mohsinalimat** [comment]
> Go to delivery note > customize form and erase the "Option" value. Link fields can have options, data fields can't.

Now working perfectly.

Thanks @ankush 
You are a genius.
