### ISSUE TITLE
ImportError: Salary Slip

### ISSUE THREAD

**Issue by D347HG0D** [frappe/erpnext#28683]
Traceback (most recent call last):
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/__init__.py", line 877, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    return _get_controller()
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in _get_controller
    raise ImportError(doctype)
ImportError: Salary Slip
request.js:387:14
Traceback (most recent call last):
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/__init__.py", line 1199, in call
    return fn(*args, **newargs)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/__init__.py", line 877, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/document.py", line 73, in get_doc
    controller = get_controller(doctype)
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    return _get_controller()
  File "/home/sysadmin/erpnext1/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in _get_controller
    raise ImportError(doctype)
ImportError: Salary Slip

This error was showing after i upgraded my erpnext from 12 to 13.

**Comment by sharmanakul** [comment]
hey @D347HG0D, were you able to find a solution?

**Comment by Shantanu-mishra** [comment]
@sharmanakul There was problem during upgrade before i didn't knew much about ERPNext so i made few errors in upgrading. Previously i used to customize directly on core which is wrong. which cause some problems in upgrading.
