### ISSUE TITLE
Potential infinite loop in WO->JC creation

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#28793]
There's a loop here that seems to become infinite loop in tests

https://github.com/frappe/erpnext/blob/5977c4da755304e13d8ac717e1628d979837a014/erpnext/manufacturing/doctype/job_card/job_card.py#L125-L134

Example test timeout:

https://github.com/frappe/erpnext/runs/4452846549?check_suite_focus=true

```
 ERROR  test_job_card_scrap_item (erpnext.manufacturing.doctype.work_order.test_work_order.TestWorkOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/tests/utils.py", line 153, in wrapper
    result = func(*args, **kwargs)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/test_work_order.py", line 798, in test_job_card_scrap_item
    wo_order = make_wo_order_test_record(item=item, company=company, planned_start_date=now(), qty=20, skip_transfer=1)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/test_work_order.py", line 921, in make_wo_order_test_record
    wo_order.submit()
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 282, in save
    return self._save(*args, **kwargs)
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in _save
    self.run_post_save_methods()
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 1163, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 1146, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/runner/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 291, in on_submit
    self.create_job_card()
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 384, in create_job_card
    plan_days, enable_capacity_planning)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 399, in prepare_data_for_job_card
    enable_capacity_planning=enable_capacity_planning)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1100, in create_job_card
    doc.schedule_time_logs(row)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 134, in schedule_time_logs
    self.check_workstation_time(row)
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 168, in check_workstation_time
    workstation_end_time = datetime.datetime.combine(start_date, get_time(time_slot.end_time))
  File "/home/runner/frappe-bench/apps/frappe/frappe/utils/data.py", line 300, in get_time
    return parser.parse(time_str).time()
  File "/home/runner/frappe-bench/env/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/runner/frappe-bench/env/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/runner/frappe-bench/env/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 740, in _parse
    i = self._parse_numeric_token(l, i, info, ymd, res, fuzzy)
  File "/home/runner/frappe-bench/env/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 929, in _parse_numeric_token
    elif self._find_hms_idx(idx, tokens, info, allow_jump=True) is not None:
  File "/home/runner/frappe-bench/env/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1009, in _find_hms_idx
    if idx+1 < len_l and info.hms(tokens[idx+1]) is not None:
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/tests/utils.py", line 147, in _handle_timeout
    raise Exception(error_message)
Exception: Test timed out.
```

**Comment by ankush** [comment]
This was resolved long time back
