### ISSUE TITLE
Pull from email account

### ISSUE THREAD

**Issue by shubhankarsri1234** [frappe/erpnext#28903]
### Information about bug

Error in incoming mails . I have set email integration but not able to receive mails , instead an error showed
( pull_from_email_account )

### Version

v13

### Module

accounts

### Version

ERPNext : v13.2.0
Frappe : v13.1.2 

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error
Traceback (most recent call last):
  File "/usr/lib/python3.7/imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.7/imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.7/imaplib.py", line 1047, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.7/imaplib.py", line 1149, in _get_line
    line = self.readline()
  File "/usr/lib/python3.7/imaplib.py", line 312, in readline
    raise self.error("got more than %d bytes" % _MAXLINE)
imaplib.IMAP4.error: got more than 20480 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/email/receive.py", line 120, in get_messages
    uid_list = email_list = self.get_new_mails()
  File "apps/frappe/frappe/email/receive.py", line 185, in get_new_mails
    response, message = self.imap.uid('search', None, self.settings.email_sync_rule)
  File "/usr/lib/python3.7/imaplib.py", line 879, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1023, in _command_complete
    raise self.error('command: %s => %s' % (name, val))
imaplib.IMAP4.error: command: UID => got more than 20480 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 104, in execute_job
    method(**kwargs)
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 840, in pull_from_email_account
    email_account.receive()
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 315, in receive
    emails = email_server.get_messages()
  File "apps/frappe/frappe/email/receive.py", line 153, in get_messages
    if self.has_login_limit_exceeded(e):
  File "apps/frappe/frappe/email/receive.py", line 297, in has_login_limit_exceeded
    return "-ERR Exceeded the login limit" in strip(cstr(e.message))
AttributeError: 'error' object has no attribute 'message'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imagen20048** [comment]
Hi how are you, i got the same problem, any solution to recommend us

**Comment by pnwilly** [comment]
Same issue here. I wonder whether anyone got a solution out there.
