### ISSUE TITLE
add_default_exit_questionnaire_notification_template patch failing on develop

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#28986]
### Information about bug

<img width="1439" alt="Screenshot 2021-12-21 at 4 44 16 PM" src="https://user-images.githubusercontent.com/9079960/146921054-99b5a85c-3ada-4dec-ada0-51b428941bb9.png">

### Version

develop

### Module

HR

### Version

develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
λ bench --site develop migrate --skip-search-index
Migrating develop
Executing frappe.patches.v14_0.save_ratings_in_fraction in develop (_541daae9e38f203a)
Success: Done in 0.079s
Executing erpnext.patches.v13_0.disable_ksa_print_format_for_others # 16-12-2021 in develop (_541daae9e38f203a)
Success: Done in 0.065s
Executing erpnext.patches.v14_0.add_default_exit_questionnaire_notification_template in develop (_541daae9e38f203a)

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/Users/ankush/benches/develop/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ankush/benches/develop/env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/commands/site.py", line 457, in migrate
    migrate(
  File "/Users/ankush/benches/develop/apps/frappe/frappe/migrate.py", line 68, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
    run_patch(patch)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
    if not run_single(patchmodule = patch):
  File "/Users/ankush/benches/develop/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/Users/ankush/benches/develop/apps/erpnext/erpnext/patches/v14_0/add_default_exit_questionnaire_notification_template.py", line 27, in execute
    hr_settings.save()
  File "/Users/ankush/benches/develop/apps/frappe/frappe/model/document.py", line 282, in save
    return self._save(*args, **kwargs)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/model/document.py", line 318, in _save
    self._validate_links()
  File "/Users/ankush/benches/develop/apps/frappe/frappe/model/document.py", line 833, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg),
  File "/Users/ankush/benches/develop/apps/frappe/frappe/__init__.py", line 443, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/Users/ankush/benches/develop/apps/frappe/frappe/__init__.py", line 422, in msgprint
    _raise_exception()
  File "/Users/ankush/benches/develop/apps/frappe/frappe/__init__.py", line 376, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Leave Approval Notification Template: Leave Approval Notification, Leave Status Notification Template: Leave Status Notification, Interview Reminder Notification Template: Interview Reminder, Feedback Reminder Notification Template: Interview Feedback Reminder
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ruchamahabal** [comment]
This can only happen if the Templates are deleted from the backend 🤔. If a user is deleting any default Email / Notification Template, they will get a linking error so they have to remove the link from HR Settings and only then delete it. This patch is just setting a new template and link validation is failing for old ones.

Anyway, we can add `doc.flags.ignore_links = True` while saving.
