### ISSUE TITLE
[V5] bench update fails

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2900]
Error: subprocess.CalledProcessError: Command 'git pull upstream v5.0' returned non-zero exit status 1

This is a new V5 installation

**Comment by gentle-** [comment]
Have the same issue. I have a working V5, but the update after the weekend failed...

**Comment by PKPandurangan** [comment]
Here is the full output..

remote: Counting objects: 2826, done.
remote: Compressing objects: 100% (993/993), done.
remote: Total 2826 (delta 1390), reused 851 (delta 851), pack-reused 982
Receiving objects: 100% (2826/2826), 4.12 MiB | 6.28 MiB/s, done.
Resolving deltas: 100% (2003/2003), done.
From https://github.com/frappe/erpnext
   eda4265..7e98eb3  master     -> upstream/master
   ce7b238..7e98eb3  develop    -> upstream/develop
   ceb0472..43ba7e1  v5.0       -> upstream/v5.0
 * [new tag]         v4.22.0    -> v4.22.0
 * [new tag]         v4.22.1    -> v4.22.1
 * [new tag]         v4.22.2    -> v4.22.2
 * [new tag]         v4.23.0    -> v4.23.0
error: Your local changes to the following files would be overwritten by checkout:
        erpnext/hr/doctype/salary_slip/salary_slip.json
Please, commit your changes or stash them before you can switch branches.
Aborting
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 210, in _migrate_to_v5
    migrate_to_v5(bench=bench)
  File "/home/frappe/bench-repo/bench/migrate_to_v5.py", line 14, in migrate_to_v5
    checkout_v5(repo, bench=bench)
  File "/home/frappe/bench-repo/bench/migrate_to_v5.py", line 47, in checkout_v5
    exec_cmd("git checkout v5.0", cwd=cwd)
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git checkout v5.0' returned non-zero exit status 1

**Comment by PKPandurangan** [comment]
Here is the git diff response.


diff --git a/erpnext/hr/doctype/salary_slip/salary_slip.json b/erpnext/hr/doctype/salary_slip/salary_slip.json
index 44607dc..0c35e42 100644
--- a/erpnext/hr/doctype/salary_slip/salary_slip.json
+++ b/erpnext/hr/doctype/salary_slip/salary_slip.json
@@ -1,4 +1,5 @@
 {
+ "allow_rename": 1, 
  "creation": "2013-01-10 16:34:15", 
  "docstatus": 0, 
  "doctype": "DocType", 
@@ -337,7 +338,7 @@
  "icon": "icon-file-text", 
  "idx": 1, 
  "is_submittable": 1, 
- "modified": "2014-09-09 05:35:33.807228", 
+ "modified": "2015-02-27 20:33:01.325421", 
  "modified_by": "Administrator", 
  "module": "HR", 
  "name": "Salary Slip", 
@@ -360,15 +361,18 @@
   }, 
   {
    "amend": 1, 
+   "apply_user_permissions": 1, 
    "cancel": 1, 
    "create": 1, 
    "delete": 1, 
    "email": 1, 
+   "export": 1, 
    "permlevel": 0, 
    "print": 1, 
    "read": 1, 
    "report": 1, 
    "role": "HR Manager", 
+   "set_user_permissions": 1, 
    "submit": 1, 
    "write": 1
   },

**Comment by gentle-** [comment]
My issue is gone, I had some translation files adjusted, which the bench correctly identified as being changed.

**Comment by nabinhait** [comment]
@PKPandurangan You should either discard you local changes or commit them to run `bench update`.

**Comment by Steggur** [comment]
How do you commit them to run Bench update?
Sorry for the newbie question.

**Comment by PKPandurangan** [comment]
after discarding the changes, it throws me a new error 

root@debian7:/home/frappe/frappe-bench# bench migrate-to-v5
This will migrate all sites in the bench to version 5. Version 5 is still work in progress and NOT STABLE.
This is irreversible. Do you want to continue? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 210, in _migrate_to_v5
    migrate_to_v5(bench=bench)
  File "/home/frappe/bench-repo/bench/migrate_to_v5.py", line 12, in migrate_to_v5
    validate_v4(bench=bench)
  File "/home/frappe/bench-repo/bench/migrate_to_v5.py", line 41, in validate_v4
    raise Exception("{} is not on v4.x.x".format(repo))
Exception: frappe is not on v4.x.x

**Comment by pdvyas** [comment]
Run `bench update` not migrate-to-v5

**Comment by PKPandurangan** [comment]
Thats awesome. Thank you very much Guys..

**Comment by PKPandurangan** [comment]
@pdvyas @nabinhait Sorry to bother you guys again. Got something else for your preview..


Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 39, in main
    ret = run(fn, args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
    out = globals().get(fn)(**args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 448, in latest
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v5_0/style_settings_to_website_theme.py", line 10, in execute
    migrate_style_settings()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v5_0/style_settings_to_website_theme.py", line 28, in migrate_style_settings
    website_theme.use_theme()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 55, in use_theme
    use_theme(self.name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 61, in use_theme
    website_settings.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 500, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 466, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 577, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 560, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 460, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 17, in validate
    self.validate_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 22, in validate_home_page
    if self.home_page and not resolve_route(self.home_page):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in resolve_route
    route = get_page_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 51, in get_page_route
    found = filter(lambda p: p.page_name==path, get_pages())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 129, in get_pages
    route.page_title = frappe.get_attr(controller + "." + "page_title")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 715, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/shopping_cart/shopping_cart/templates/pages/address.py", line 9, in <module>
    from frappe.widgets.form.meta import get_meta
ImportError: No module named widgets.form.meta
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 172, in update
    patch_sites()
  File "/home/frappe/bench-repo/bench/utils.py", line 93, in patch_sites
    exec_cmd("{frappe} --latest all".format(frappe=get_frappe(bench=bench)), cwd=os.path.join(bench, 'sites'))
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/frappe --latest all' returned non-zero exit status 1

**Comment by pdvyas** [comment]
Are you sure that shopping_cart doesn't exist in `apps/shopping_cart`. If it does, then I guess `migrate-to-v5` would have failed midway. We're merging v5.0 to develop tomorrow anyway. there will be a new bench command to this. Will update this thread with further instructions with updated bench.

**Comment by PKPandurangan** [comment]
yes. Shopping cart doesn't exist. can you please tell me what should i do next to get the data back from the previous version?

**Comment by pdvyas** [comment]
Try,

bench frappe --clear_cache
bench update

and post the output

**Comment by PKPandurangan** [comment]
Please find the output for  bench frappe --clear_cache

````
root@debian7:/home/frappe/frappe-bench# bench frappe --clear_cache
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 53, in main
    return run(fn, parsed_args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
    out = globals().get(fn)(**args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 580, in clear_cache
    frappe.clear_cache()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 362, in clear_cache
    for fn in frappe.get_hooks("clear_cache"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 654, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 44, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 625, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named shopping_cart.hooks
````
