### ISSUE TITLE
Error in pull_from_email_account

### ISSUE THREAD

**Issue by hbhawsar777** [frappe/erpnext#29016]
### Information about bug

![Screenshot from 2021-12-24 08-59-09](https://user-images.githubusercontent.com/54030707/147313033-f787b625-a36a-4cc8-81f3-6e4d2d9901de.png)

### Module

support

### Version

Frappe - 13.12.1
ERPNext - 13.12.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/ec2-user/frappeWorkbench/frappe-bench/apps/frappe/frappe/email/receive.py", line 120, in get_messages
    uid_list = email_list = self.get_new_mails()
  File "/home/ec2-user/frappeWorkbench/frappe-bench/apps/frappe/frappe/email/receive.py", line 185, in get_new_mails
    response, message = self.imap.uid('search', None, self.settings.email_sync_rule)
  File "/usr/lib64/python3.6/imaplib.py", line 879, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib64/python3.6/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python3.6/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'Could not parse command']
```

**Comment by ankush** [comment]
This was fixed a while back. Update Frappe.
