### ISSUE TITLE
Twitter Integration not usable without elevated access to Twitter API

### ISSUE THREAD

**Issue by Katzen48** [frappe/erpnext#29084]
### Information about bug

I tried to set up the Twitter integration.
I created a developer account, a project and an app in the developer portal.
After entering the consumer key and secret into the "Twitter Settings" of ERPNext and authorizing the access, I got an error, that I need elevated access, to use the requested endpoint.

By having a look at the code and after a bit of research, I found out, that ERPNext uses the V1.1 Twitter API, which is deprecated and only allowed for developers with elevated access.

This is kind of a problem, as elevated access requires applying and getting put on a waitlist, which could take a while.
Additionally, getting elevated access doesn't get you many perks aside from a higher API limit, which is unnecessary for most use cases.
Last, using a deprecated API, which may be discontinued anytime is something to avoid.

### Module

integrations

### Version

Frappe version: 13.15.0
ERPNext version: 13.15.0

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/twitter_settings/twitter_settings.py", line 43, in get_access_token
    user = api.me()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/tweepy/api.py", line 407, in me
    return self.get_user(screen_name=self.auth.get_username())
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/tweepy/auth.py", line 140, in get_username
    user = api.verify_credentials()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/tweepy/api.py", line 672, in verify_credentials
    return bind_api(
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/tweepy/binder.py", line 253, in _call
    return method.execute()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/twitter_settings/twitter_settings.py", line 125, in callback
    twitter_settings.get_access_token(oauth_token,oauth_verifier)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/twitter_settings/twitter_settings.py", line 58, in get_access_token
    frappe.throw(_('Invalid Consumer Key or Consumer Secret Key'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Invalid Consumer Key or Consumer Secret Key
```

**Comment by Katzen48** [comment]
Is that a thing, that will be fixed?

**Comment by Katzen48** [comment]
Any updates?

**Comment by Katzen48** [comment]
@deepeshgarg007 why was this issue closed without a comment?
