### ISSUE TITLE
Issues in Process Statement of Accounts 

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29108]
### Information about bug

Issue : On hitting Send Email button on the Process Statement of Accounts form, an error pops up. Also unable to download PDF on hitting download button 

Site: campbell.erpnext.com 
Screenshot :
![image](https://user-images.githubusercontent.com/46772424/147920731-7fc21fac-db21-4f5c-9c5b-935847b6ef51.png)

![image](https://user-images.githubusercontent.com/46772424/147920739-449ced30-f457-44f9-8439-9e52a2ffebe9.png)

### Module

accounts

### Version

13

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py", line 262, in send_emails
    report = get_report_pdf(doc, consolidated=False)
  File "apps/erpnext/erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py", line 88, in get_report_pdf
    col, res = get_soa(filters)
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 40, in execute
    validate_filters(filters, account_details)
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 71, in validate_filters
    filters.account = frappe.parse_json(filters.get('account'))
  File "apps/frappe/frappe/__init__.py", line 1845, in parse_json
    return parse_json(val)
  File "apps/frappe/frappe/utils/__init__.py", line 689, in parse_json
    val = json.loads(val)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kkulloters** [comment]
Facing the same issue on our end with ERPNext: v13.18.0 (version-13) and Frappe Framework: v13.18.0 (version-13)

**Comment by NuttCorp** [comment]
Facing the same issue ERPNext/FF v13.18.0

**Comment by vcavel** [comment]
Same here with the same versions

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/29928
