### ISSUE TITLE
V5 Bench Update Fails

### ISSUE THREAD

**Issue by PKPandurangan** [frappe/erpnext#2914]
Tried Migrating to V5 and had an sub process error mentioned in #2900 . After fixing and giving the bench update , I am getting this error.

Traceback (most recent call last):
File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in 
load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 39, in main
ret = run(fn, args)
File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
out = globals().get(fn)(*args)
File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
return fn(args, *new_kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 448, in latest
frappe.modules.patch_handler.run_all()
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
if not run_single(patchmodule = patch):
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
return execute_patch(patchmodule, method, methodargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
frappe.get_attr(patchmodule.split()[0] + ".execute")()
File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v5_0/style_settings_to_website_theme.py", line 10, in execute
migrate_style_settings()
File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v5_0/style_settings_to_website_theme.py", line 28, in migrate_style_settings
website_theme.use_theme()
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 55, in use_theme
use_theme(self.name)
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 61, in use_theme
website_settings.save()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in save
self.run_before_save_methods()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 500, in run_before_save_methods
self.run_method("validate")
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 466, in run_method
return Document.hook(fn)(self, *args, *kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 577, in composer
return composed(self, method, args, *kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 560, in runner
add_to_return_value(self, fn(self, args, *kwargs))
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 460, in 
fn = lambda self, args, *kwargs: getattr(self, method)(args, *kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 17, in validate
self.validate_home_page()
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 22, in validate_home_page
if self.home_page and not resolve_route(self.home_page):
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in resolve_route
route = get_page_route(path)
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 51, in get_page_route
found = filter(lambda p: p.page_name==path, get_pages())
File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 129, in get_pages
route.page_title = frappe.get_attr(controller + "." + "page_title")
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 715, in get_attr
return getattr(get_module(modulename), methodname)
File "/home/frappe/frappe-bench/apps/frappe/frappe/init.py", line 520, in get_module
return importlib.import_module(modulename)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/home/frappe/frappe-bench/apps/shopping_cart/shopping_cart/templates/pages/address.py", line 9, in 
from frappe.widgets.form.meta import get_meta
ImportError: No module named widgets.form.meta
Error: None
Traceback (most recent call last):
File "/usr/local/bin/bench", line 9, in 
load_entry_point('bench==0.1', 'console_scripts', 'bench')()
File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
return bench()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in call
return self.main(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
return callback(args, **kwargs)
File "/home/frappe/bench-repo/bench/cli.py", line 172, in update
patch_sites()
File "/home/frappe/bench-repo/bench/utils.py", line 93, in patch_sites
exec_cmd("{frappe} --latest all".format(frappe=get_frappe(bench=bench)), cwd=os.path.join(bench, 'sites'))
File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
subprocess.check_call(cmd, cwd=cwd, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/frappe --latest all' returned non-zero exit status 1

**Comment by pdvyas** [comment]
@rmehta

**Comment by rmehta** [comment]
shopping cart must be uninstalled when migrating... (if installed)

**Comment by PKPandurangan** [comment]
Thanks @rmehta . It would be great if you could let me know how to uninstall the shopping cart completely from the bench.

**Comment by PKPandurangan** [comment]
I have read one of the old pages to uninstall the shopping cart and here is what i got.

````
root@debian7:/home/frappe/frappe-bench/env/bin# ./pip uninstall shopping_cart
Cannot uninstall requirement shopping-cart, not installed
````

&

````
root@debian7:/home/frappe/frappe-bench# bench update
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/frappe
 * branch            v5.0       -> FETCH_HEAD
Already up-to-date.
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 49, in main
    frappe.init(site, sites_path=sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 115, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 674, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 561, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named shopping_cart
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 171, in update
    backup_all_sites()
  File "/home/frappe/bench-repo/bench/utils.py", line 283, in backup_all_sites
    backup_site(site, bench=bench)
  File "/home/frappe/bench-repo/bench/utils.py", line 279, in backup_site
    cwd=os.path.join(bench, 'sites'))
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/frappe --backup site1.local' returned non-zero exit status 1
````

**Comment by PKPandurangan** [comment]
I have updated the shopping cart, just to make sure i am uninstalling it properly. I have followed this link to uninstall the shopping cart and it was successful.

https://discuss.frappe.io/t/how-to-install-v5-version/3732/2

Then during the bench update, I am getting this error.

````
root@debian7:/home/frappe/frappe-bench/apps# bench update
Already up-to-date.
remote: Counting objects: 1118, done.
remote: Compressing objects: 100% (714/714), done.
remote: Total 1118 (delta 259), reused 211 (delta 211), pack-reused 193
Receiving objects: 100% (1118/1118), 770.40 KiB, done.
Resolving deltas: 100% (306/306), done.
From https://github.com/frappe/erpnext
 * branch            v5.0       -> FETCH_HEAD
Updating 43ba7e1..25bd84d
error: unable to unlink old 'erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/account/chart_of_accounts/import_from_openerp.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/account/chart_of_accounts/verified/standard_chart_of_accounts.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/fiscal_year_company/fiscal_year_company.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/journal_entry/journal_entry.js' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/journal_entry/journal_entry.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/journal_entry/test_journal_entry.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/journal_entry_account/journal_entry_account.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/mode_of_payment_account/mode_of_payment_account.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/monthly_distribution/monthly_distribution.js' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/monthly_distribution/monthly_distribution.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/monthly_distribution/test_monthly_distribution.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/monthly_distribution_percentage/monthly_distribution_percentage.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/doctype/party_account/party_account.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/report/accounts_payable_summary/accounts_payable_summary.js' (Permission denied)
error: unable to unlink old 'erpnext/accounts/report/accounts_payable_summary/accounts_payable_summary.py' (Permission denied)
error: unable to unlink old 'erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.js' (Permission denied)
error: unable to unlink old 'erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.py' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/lead/lead.js' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/lead/lead.py' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/lead/test_lead.py' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/opportunity/opportunity.js' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/opportunity/opportunity.py' (Permission denied)
error: unable to unlink old 'erpnext/crm/doctype/opportunity/test_opportunity.py' (Permission denied)
error: unable to unlink old 'erpnext/hub_node/__init__.py' (Permission denied)
error: unable to unlink old 'erpnext/hub_node/doctype/hub_settings/hub_settings.py' (Permission denied)
error: unable to unlink old 'erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.py' (Permission denied)
error: unable to unlink old 'erpnext/manufacturing/doctype/operation/operation.py' (Permission denied)
error: unable to unlink old 'erpnext/manufacturing/doctype/operation/test_operation.py' (Permission denied)
error: unable to unlink old 'erpnext/manufacturing/doctype/production_order_operation/production_order_operation.py' (Permission denied)
error: unable to unlink old 'erpnext/manufacturing/doctype/workstation_working_hour/workstation_working_hour.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/capacity_planning.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/manufacturing_activity_type.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/new_crm_module.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/recalculate_total_amount_in_jv.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/remove_shopping_cart_app.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/rename_table_fieldnames.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/rename_total_fields.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/replace_renamed_fields_in_custom_scripts_and_print_formats.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/set_appraisal_remarks.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/set_default_company_in_bom.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/taxes_and_totals_in_party_currency.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_account_types.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_companywise_payment_account.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_dn_against_doc_fields.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_from_bom.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_frozen_accounts_permission_role.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_item_description_and_image.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_item_name_in_bom.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_journal_entry_title.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_sms_sender.py' (Permission denied)
error: unable to unlink old 'erpnext/patches/v5_0/update_time_log_title.py' (Permission denied)
error: unable to unlink old 'erpnext/projects/doctype/project_task/project_task.py' (Permission denied)
error: unable to unlink old 'erpnext/public/js/pos/pos.js' (Permission denied)
error: unable to unlink old 'erpnext/selling/report/customer_credit_balance/customer_credit_balance.js' (Permission denied)
error: unable to unlink old 'erpnext/selling/report/customer_credit_balance/customer_credit_balance.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/__init__.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/cart.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_price_list/shopping_cart_price_list.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_settings/shopping_cart_settings.js' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_settings/shopping_cart_settings.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_settings/test_shopping_cart_settings.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_shipping_rule/shopping_cart_shipping_rule.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/doctype/shopping_cart_taxes_and_charges_master/shopping_cart_taxes_and_charges_master.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/product.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/test_shopping_cart.py' (Permission denied)
error: unable to unlink old 'erpnext/shopping_cart/utils.py' (Permission denied)
error: unable to unlink old 'erpnext/stock/doctype/item_attribute/item_attribute.py' (Permission denied)
error: unable to unlink old 'erpnext/stock/doctype/item_attribute/test_item_attribute.py' (Permission denied)
error: unable to unlink old 'erpnext/stock/doctype/item_attribute_value/item_attribute_value.py' (Permission denied)
error: unable to unlink old 'erpnext/stock/doctype/item_variant/item_variant.py' (Permission denied)
error: unable to unlink old 'erpnext/stock/doctype/stock_reconciliation_item/stock_reconciliation_item.py' (Permission denied)
error: unable to unlink old 'erpnext/support/doctype/issue/issue.py' (Permission denied)
error: unable to unlink old 'erpnext/support/doctype/issue/test_issue.py' (Permission denied)
error: unable to unlink old 'erpnext/support/doctype/warranty_claim/test_warranty_claim.py' (Permission denied)
error: unable to unlink old 'erpnext/support/doctype/warranty_claim/warranty_claim.js' (Permission denied)
error: unable to unlink old 'erpnext/support/doctype/warranty_claim/warranty_claim.py' (Permission denied)
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 166, in update
    pull_all_apps()
  File "/home/frappe/bench-repo/bench/app.py", line 75, in pull_all_apps
    exec_cmd("git pull {rebase} upstream {branch}".format(rebase=rebase, branch=get_current_branch(app_dir)), cwd=app_dir)
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git pull  upstream v5.0
' returned non-zero exit status 1
````

**Comment by pdvyas** [comment]
Try `bench frappe --clear_cache && bench frappe --latest`

**Comment by PKPandurangan** [comment]
This issue is shorter than all the others i have seen. :+1: 

````
root@debian7:/home/frappe/frappe-bench# bench frappe --clear_cache
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 49, in main
    frappe.init(site, sites_path=sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 115, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 674, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 561, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named shopping_cart
````

**Comment by PKPandurangan** [comment]
@rmehta Not sure what is the issue. here is the list of commands that i tried and their result.


Trying to update the bench and i am getting the following error
````
root@debian7:/home/frappe/frappe-bench# bench update
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            v5.0       -> FETCH_HEAD
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident  <frappe@debian7.c.bustling-brand-849.internal> not allowed
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 166, in update
    pull_all_apps()
  File "/home/frappe/bench-repo/bench/app.py", line 75, in pull_all_apps
    exec_cmd("git pull {rebase} upstream {branch}".format(rebase=rebase, branch=get_current_branch(app_dir)), cwd=app_dir)
  File "/home/frappe/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git pull  upstream v5.0
' returned non-zero exit status 128
````

Tried to check the configuration and it has values.

````
root@debian7:/home/frappe/frappe-bench# git config --global -l
user.email=******@******.com
user.name=******
````

Tried to clear the cache as well.

````
root@debian7:/home/frappe/frappe-bench# bench frappe --clear_cache
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.11.4', 'console_scripts', 'frappe')()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 53, in main
    return run(fn, parsed_args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
    out = globals().get(fn)(**args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/cli.py", line 580, in clear_cache
    frappe.clear_cache()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 362, in clear_cache
    for fn in frappe.get_hooks("clear_cache"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 654, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 44, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 625, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named shopping_cart.hooks
````

Checked if the shopping_cart folder is present and its not

````
root@debian7:/home/frappe/frappe-bench# cd apps
root@debian7:/home/frappe/frappe-bench/apps# ls
erpnext  frappe
````

Checked if the shopping_cart text is present in the apps.txt and its nor present there as well.

````
root@debian7:/home/frappe/frappe-bench# cd sites
root@debian7:/home/frappe/frappe-bench/sites# ls
apps.txt  assets  celerybeat.pid  currentsite.txt  languages.txt  site1.local  test.schedule
root@debian7:/home/frappe/frappe-bench/sites# cat apps.txt
frappe
erpnext
````

Please help me fix this.
