### ISSUE TITLE
Failed to migrate quickbooks

### ISSUE THREAD

**Issue by hadeeld7** [frappe/erpnext#29161]
### Information about bug

So I have setup up my migrator successfully but when i started to fetch data i get failed status and found some error in my error log. the custom fields for migration has been added successfully and some accounts have been added to the charts of accounts, other than that it has failed. note that my quickbooks have only journal entry that i want to migrate.

### Module

integrations

### Version

ERPNext: v13.16.1 (version-13)
Frappe Framework: v13.16.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Data
"{\"warnings\":null,\"intuitObject\":null,\"fault\":{\"error\":[{\"message\":\"message=ApplicationAuthorizationFailed; errorCode=003100; statusCode=403\",\"detail\":null,\"code\":\"3100\",\"element\":null}],\"type\":\"SERVICE\"},\"report\":null,\"queryResponse\":null,\"batchItemResponse\":[],\"attachableResponse\":[],\"syncErrorResponse\":null,\"requestId\":null,\"time\":1640612353707,\"status\":null,\"cdcresponse\":[]}"
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 206, in _migrate_entries
    entry_count = response.json()["QueryResponse"]["totalCount"]
KeyError: 'QueryResponse'
```
```
Data
""
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 102, in _migrate
    self._migrate_entries_from_gl(entity)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 285, in _migrate_entries_from_gl
    if entity in self.general_ledger:
AttributeError: 'QuickBooksMigrator' object has no attribute 'general_ledger'
```

```
Data
"{\"warnings\":null,\"intuitObject\":null,\"fault\":{\"error\":[{\"message\":\"message=ApplicationAuthorizationFailed; errorCode=003100; statusCode=403\",\"detail\":null,\"code\":\"3100\",\"element\":null}],\"type\":\"SERVICE\"},\"report\":null,\"queryResponse\":null,\"batchItemResponse\":[],\"attachableResponse\":[],\"syncErrorResponse\":null,\"requestId\":null,\"time\":1640612375173,\"status\":null,\"cdcresponse\":[]}"
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 206, in _migrate_entries
    entry_count = response.json()["QueryResponse"]["totalCount"]
KeyError: 'QueryResponse'
```

```
Data
"{\"warnings\":null,\"intuitObject\":null,\"fault\":{\"error\":[{\"message\":\"message=ApplicationAuthorizationFailed; errorCode=003100; statusCode=403\",\"detail\":null,\"code\":\"3100\",\"element\":null}],\"type\":\"SERVICE\"},\"report\":null,\"queryResponse\":null,\"batchItemResponse\":[],\"attachableResponse\":[],\"syncErrorResponse\":null,\"requestId\":null,\"time\":1640612373987,\"status\":null,\"cdcresponse\":[]}"
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 206, in _migrate_entries
    entry_count = response.json()["QueryResponse"]["totalCount"]
KeyError: 'QueryResponse'
```

```
Data
"{\"warnings\":null,\"intuitObject\":null,\"fault\":{\"error\":[{\"message\":\"message=ApplicationAuthorizationFailed; errorCode=003100; statusCode=403\",\"detail\":null,\"code\":\"3100\",\"element\":null}],\"type\":\"SERVICE\"},\"report\":null,\"queryResponse\":null,\"batchItemResponse\":[],\"attachableResponse\":[],\"syncErrorResponse\":null,\"requestId\":null,\"time\":1640612372898,\"status\":null,\"cdcresponse\":[]}"
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 206, in _migrate_entries
    entry_count = response.json()["QueryResponse"]["totalCount"]
KeyError: 'QueryResponse'
```

```
Data
""
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 261, in _create_fiscal_years
    smallest_ledger_entry_date = getdate(min(entry["date"] for entry in chain(*self.gl_entries.values()) if entry["date"]))
ValueError: min() arg is an empty sequence
```

```
Data
"{\"warnings\":null,\"intuitObject\":null,\"fault\":{\"error\":[{\"message\":\"message=ApplicationAuthorizationFailed; errorCode=003100; statusCode=403\",\"detail\":null,\"code\":\"3100\",\"element\":null}],\"type\":\"SERVICE\"},\"report\":null,\"queryResponse\":null,\"batchItemResponse\":[],\"attachableResponse\":[],\"syncErrorResponse\":null,\"requestId\":null,\"time\":1640612357266,\"status\":null,\"cdcresponse\":[]}"
Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 236, in _fetch_general_ledger
    for section in response.json()["Rows"]["Row"]:
KeyError: '
```

**Comment by hadeeld7** [comment]
this is not solved yet

**Comment by viveking** [comment]
Seems your Quickbook connection not working. 
Check the API Endpoint if its **https://quickbooks.api.intuit.com/v3**
Use Client Id and Secret from Production & Not fron the Sandbox/Development.
