### ISSUE TITLE
payment reconciliation sql error

### ISSUE THREAD

**Issue by reubenromandy** [frappe/erpnext#29203]
### Information about bug

Upon opening the payment reconciliation page and entering the following information:
party type - customer
party - one of my customers
receivable account - my receivable account
and an amount in the minimum or maximum invoice amount
And pressing the Get Unreconciled Entries button, I intermittently receive a sql error.
The error and the full stack trace are pasted in the details below.

The min and max payment filters don't seem to be working at all, but not throwing an error.
The other filters work as expected.

### Module

accounts

### Version

erpnext 13.16.1
frappe 13.16.0

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error Message: pymysql.err.OperationalError: (1054, "Unknown column 'gl.debit_in_account_currency' in 'where clause'")

Stack Trace:
Traceback (most recent call last):
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/handler.py", line 237, in run_doc_method
    response = doc.run_method(method)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 18, in get_unreconciled_entries
    self.get_nonreconciled_payment_entries()
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 28, in get_nonreconciled_payment_entries
    dr_or_cr_notes = self.get_dr_or_cr_notes()
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 130, in get_dr_or_cr_notes
    }, as_dict=1)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 148, in sql
    self._cursor.execute(query, values)
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/erpadmin/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'gl.debit_in_account_currency' in 'where clause'")
```

**Comment by ankush** [comment]
This field should exist

https://github.com/frappe/erpnext/blob/a651a0ffc8fd95a35c6325a2a6ab84d66027d376/erpnext/accounts/doctype/gl_entry/gl_entry.json#L18 

something wrong with your site probably. 

Can you confirm if this is there in GL entry doctype?

**Comment by reubenromandy** [comment]
Yep, it's there in the gl_entry.json. 
Pasted the beginning of the file below.
{
 "actions": [],
 "autoname": "ACC-GLE-.YYYY.-.#####",
 "creation": "2013-01-10 16:34:06",
 "doctype": "DocType",
 "document_type": "Document",
 "engine": "InnoDB",
 "field_order": [
  "posting_date",
  "transaction_date",
  "account",
  "party_type",
  "party",
  "cost_center",
  "debit",
  "credit",
  "account_currency",
  **"debit_in_account_currency",**
  "credit_in_account_currency",

**Comment by ankush** [comment]
Is it there in the database?

```sql
select debit_in_account_currency from `tabGL Entry` limit 1;
```

Also are you still able to reproduce this error after recent updates?

**Comment by reubenromandy** [comment]
It is in the database. 
I haven't run any recent updates. Still in the process of breaking ERPNext in and so busy troubleshooting things I don't have time to update and test versions for a while. But when things calm down I will run updates and check. Thanks for following up with me.
