### ISSUE TITLE
Key Error: 'Special' in Maintenance Schedule

### ISSUE THREAD

**Issue by majubewi** [frappe/erpnext#29343]
### Information about bug

Nothing the Error Message can be hidden or removed since we did not expect an error message or have to have an error for this setting.

### Module

support

### Version

Frappe version: Current stable
ERPNext version: 13.x.x ( Current stable ) 

Error is located here:
https://github.com/frappe/erpnext/blob/ef53eb7fcda8a58c62a11aef3c8a7dc16f5e3f0b/erpnext/maintenance/doctype/maintenance_schedule/maintenance_schedule.py#L57

![image](https://user-images.githubusercontent.com/11473213/149946251-e7cf9f69-d411-4eae-94a2-d06e929d7b8e.png)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 237, in run_doc_method
    response = doc.run_method(method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/maintenance/doctype/maintenance_schedule/maintenance_schedule.py", line 57, in validate_end_date_visits
    no_of_visits = cint(diff / days_in_period[item.periodicity])
KeyError: 'Special'
```

**Comment by ankush** [comment]
There's no such option for periodicity: https://github.com/frappe/erpnext/blob/fcf12c4054e39822e0e08a2239f97f8ed1bf587e/erpnext/maintenance/doctype/maintenance_schedule_item/maintenance_schedule_item.json#L94

Fix is to the list dynamically using meta or default dict.
