### ISSUE TITLE
Serial No not in stock Message

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#29371]
### Information about bug

ERPNext give a pop-up message that the serial number **** is not in stock even though the status of the serial number is active.

How or what are the ways to check where is this serial number?

I am trying to submit a delivery note but this message keeps on appearing.

The status of the serial number is active and it is available on the stock ledger balance serial number column

![image](https://user-images.githubusercontent.com/60758795/150281628-31e618b4-9350-4d1b-8fa2-bd164a729d4d.png)

Is this a bug?

### Module

stock

### Version

Frappe Framework: v13.18.0 (HEAD)
ERPNext: v13.18.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 217, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 447, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 329, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 57, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 159, in make_entry
    sle.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 307, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 268, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 51, in on_submit
    process_serial_no(self)
  File "apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 225, in process_serial_no
    validate_serial_no(sle, item_det)
  File "apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 276, in validate_serial_no
    frappe.throw(_("Serial No {0} not in stock").format(serial_no), SerialNoNotExistsError)
  File "apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
erpnext.stock.doctype.serial_no.serial_no.SerialNoNotExistsError: Serial No 0201200V000DH0200211 not in stock

request.js:418 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 217, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 447, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 329, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 57, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 159, in make_entry
    sle.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 307, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 268, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 51, in on_submit
    process_serial_no(self)
  File "apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 225, in process_serial_no
    validate_serial_no(sle, item_det)
  File "apps/erpnext/erpnext/stock/doctype/serial_no/serial_no.py", line 276, in validate_serial_no
    frappe.throw(_("Serial No {0} not in stock").format(serial_no), SerialNoNotExistsError)
  File "apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
erpnext.stock.doctype.serial_no.serial_no.SerialNoNotExistsError: Serial No 0201200V000DH0200211 not in stock
```

**Comment by ankush** [comment]
The error is thrown when serial no record doesn't have purchase/mfg info

https://github.com/frappe/erpnext/blob/a163dbe78c0a701ee80ba280f9a39f321e8fc777/erpnext/stock/doctype/serial_no/serial_no.py#L256-L257

Can you open the document and confirm?

Also check stock ledger entry of the original document where this serial no was bought/manufactured. What is the value of "serial no" in that stock ledger entry.

**Comment by Ponyooooo** [comment]
Hi @ankush this is related to https://discuss.erpnext.com/t/serial-no-not-in-stock/85050/5. This serial number has an incoming stock ledger under a Material Receipt (Stock Entry) transaction. However, after cancelling a Delivery Note that was linked to it, the record of the document it was purchased on the serial number was removed. This is currently occurring everytime a Delivery Note is cancelled.

The serial number status is on an active status.

**Comment by Ponyooooo** [comment]
Hi @ankush do you think if the FIFO feature is another factor of this po-up message? Currently, the valuation on the stock settings is in a FIFO but it is not defined on the item record.

Then when we select a serial number, we just randomly select the serial number based on the physical items and not from the ERPNExt. We do not use or follow the auto fetch button of the delivery note. However, I am not sure why on the first submission of the delivery note, it was saved and submitted using the random SN.

Still cannot figure out the cause of this pop up error. 

We also noticed that the Creation Document No value was removed when I multiple times cancelled the DN where the SN was linked.

**Comment by Ponyooooo** [comment]
ohh looks like this was a bug on Version 13.13 when we first deploy the system. However, was not resolved when the updates of version were deployed. Just letting everyone know :)
