### ISSUE TITLE
Uname to rename some accounts, templates, etc.

### ISSUE THREAD

**Issue by realkinetix** [frappe/erpnext#29413]
### Information about bug

ERPNext is throwing an error when trying to rename accounts or tax templates most of the time. Sometimes it works, others it does as per the details below.

I posted on the forum but received no response.

https://discuss.erpnext.com/t/server-exception-valueerror-unsupported-format-character-p-0x50-when-trying-to-edit-template-name/85046

Also, when using the erpnext demo system at erpnext.com, trying to report the issue is broken as well.  The "Raise a Ticket" window appears with the details, but when I go to submit, an "Invalid Date" pop-up appears, stating "None is not a valid date string." - but there's no place to adjust a date that I can see.

### Module

accounts

### Version

	"erpnext": "13.18.0",
	"frappe": "13.18.0"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Route

Form/Item Tax Template/Canada PST 7% - PB

Traceback

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/account/account.py", line 348, in update_account_number
    frappe.rename_doc("Account", name, new_name, force=1)
  File "apps/frappe/frappe/__init__.py", line 971, in rename_doc
    return rename_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 90, in rename_doc
    rename_eps_records(doctype, old, new)
  File "apps/frappe/frappe/model/rename_doc.py", line 194, in rename_eps_records
    (frappe.qb.update(epl)
  File "apps/frappe/frappe/query_builder/utils.py", line 56, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs) # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 148, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.9/site-packages/pymysql/cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "env/lib/python3.9/site-packages/pymysql/cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
ValueError: unsupported format character 'P' (0x50) at index 60

Request Data

{
	"type": "POST",
	"args": {
		"account_name": "GST 5%",
		"name": "GST - PB"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.account.account.update_account_number"
}

ResponseData

{
	"exception": "ValueError: unsupported format character 'P' (0x50) at index 60"
}
```

**Comment by deepeshgarg007** [comment]
@realkinetix Was unable to replicate. Can you please specify what was original name and what did you try to rename it to with exact steps and reopen
