### ISSUE TITLE
UnboundLocalError: local variable 'leave_allocation' referenced before assignment

### ISSUE THREAD

**Issue by vidovide** [frappe/erpnext#29420]
### Information about bug

Leave Policy Assignment not working due to an error (local variable 'leave_allocation' referenced before assignment).

Tested on several sites.

### Module

HR

### Version

erpnext": "13.18.0
frappe": "13.18.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.18.0",
	"frappe": "13.18.0"
}
```
### Route
```
Form/Leave Policy Assignment/CYS1LS-000001
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 22, in on_submit
    self.grant_leave_alloc_for_employee()
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 61, in grant_leave_alloc_for_employee
    leave_allocations[leave_policy_detail.leave_type] = {"name": leave_allocation, "leaves": new_leaves_allocated}
UnboundLocalError: local variable 'leave_allocation' referenced before assignment

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 937, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 925, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1005, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 866, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1159, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1142, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 860, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 22, in on_submit
    self.grant_leave_alloc_for_employee()
  File "apps/erpnext/erpnext/hr/doctype/leave_policy_assignment/leave_policy_assignment.py", line 61, in grant_leave_alloc_for_employee
    leave_allocations[leave_policy_detail.leave_type] = {"name": leave_allocation, "leaves": new_leaves_allocated}
UnboundLocalError: local variable 'leave_allocation' referenced before assignment
```

**Comment by vidovide** [comment]
Seems to be solved in 13.19.0. Thx!
