### ISSUE TITLE
v4 bench update givs error (returned non-zero exit status 1)

### ISSUE THREAD

**Issue by chandutalluri** [frappe/erpnext#2954]
please help me to resolve update error 
chandu@myerp:~/eipl/frappe-bench$ bench update
Already up-to-date.
From https://github.com/frappe/shopping-cart
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
database backup taken - ./envirosyz.com/private/backups/20150312_4403087_database.sql.gz - on 2015-03-12 23:33:30.209510
database backup taken - ./eenergy.in/private/backups/20150312_94473133_database.sql.gz - on 2015-03-12 23:33:31.456389
Traceback (most recent call last):
  File "/home/chandu/eipl/frappe-bench/env/bin/frappe", line 9, in <module>
    load_entry_point('frappe==4.1.0', 'console_scripts', 'frappe')()
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/cli.py", line 53, in main
    return run(fn, parsed_args)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/cli.py", line 83, in run
    out = globals().get(fn)(**args)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/cli.py", line 67, in new_fn
    return fn(*args, **new_kwargs)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/cli.py", line 495, in backup
    odb = scheduled_backup(ignore_files=not with_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/utils/backups.py", line 142, in scheduled_backup
    odb = new_backup(older_than, ignore_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/utils/backups.py", line 146, in new_backup
    delete_temp_backups(older_than=168)
  File "/home/chandu/eipl/frappe-bench/apps/frappe/frappe/utils/backups.py", line 157, in delete_temp_backups
    file_list = os.listdir(get_backup_path())
OSError: [Errno 2] No such file or directory: './test/private/backups'
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/chandu/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/chandu/bench-repo/bench/cli.py", line 171, in update
    backup_all_sites()
  File "/home/chandu/bench-repo/bench/utils.py", line 283, in backup_all_sites
    backup_site(site, bench=bench)
  File "/home/chandu/bench-repo/bench/utils.py", line 279, in backup_site
    cwd=os.path.join(bench, 'sites'))
  File "/home/chandu/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/chandu/eipl/frappe-bench/env/bin/frappe --backup test' returned non-zero exit status 1

**Comment by pdvyas** [comment]
remove the test directory from sites and try again

**Comment by chandutalluri** [comment]
pdvyas Thanks 
it's worked for me and solved my issue 
Again thanks for sped reply
