### ISSUE TITLE
You do not have Read or Select Permissions for Academic Term v13.19.0

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#29558]
### Information about bug

When Instructors try to use Student Attendance Tool by link `.../app/student-attendance-tool`
They have the error:
`You do not have Read or Select Permissions for Academic Term`
On v13.18.0 was 
![QIP Shot - Screen 148](https://user-images.githubusercontent.com/3992823/151932293-ef61fa6e-f994-48a6-b1dc-3466bd8e5f80.png)
no problem with it. Maybe something changed?

### Module

education

### Version

ERPNext: v13.19.0 (version-13)
Frappe Framework: v13.19.0 (version-13)

**Comment by GoldenScrew** [comment]
Also you should to know, that In our portal we do not use Academic Term.

**Comment by GoldenScrew** [comment]
Sometimes I have the error
`### App Versions
```
{
	"erpnext": "13.19.0",
	"frappe": "13.19.0",
	"wiki": "0.0.1"
}
```
### Route
```
Form/Student Attendance Tool/Student Attendance Tool
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
TypeError: validate_link() missing 1 required positional argument: 'docname'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Student Group",
		"fields": "[\"academic_year\",\"academic_term\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link"
}
```
### Response Data
```
{
	"exception": "TypeError: validate_link() missing 1 required positional argument: 'docname'"
}
````
