### ISSUE TITLE
Timesheet: server error on new Timesheet

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29568]
### Information about bug

Click on new timesheet.
![image](https://user-images.githubusercontent.com/88872881/151963011-df4ebfdc-dc6a-4767-9416-60cee693c858.png)

### App Versions
```
{
	"erpnext": "13.19.0",
	"frappe": "13.19.0"
}
```
### Route
```
Form/Timesheet/new-timesheet-3
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
TypeError: validate_link() missing 1 required positional argument: 'docname'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Company",
		"fields": "[]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.validate_link"
}
```
### Response Data
```
{
	"exception": "TypeError: validate_link() missing 1 required positional argument: 'docname'"
}
```

### Module

HR

### Version

v13

**Comment by ankush** [comment]
can be fixed by https://github.com/frappe/frappe/pull/15776 

(still some more thought is required on that PR though 🙈

**Comment by surajshetty3416** [comment]
Should be fixed with https://github.com/frappe/frappe/pull/15776
