### ISSUE TITLE
Sales Invoice save problem if there are customer po numbers

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#29562]
### Information about bug

If there are many customer's po numbers for a single invoice, "Value too big" error shown.

![image](https://user-images.githubusercontent.com/710051/151945436-458a5cee-f646-406e-9cdd-8308ddd83745.png)

We made it's length 255 but sometimes it is more than that.

We will try "Small Text" also.

For resolution, 
- Do we need that field? It should be in the lines I think. How system use that field in such way?
- Can we use different field type for that? Other than data?

Regards,
Turker TUNALI

### Module

accounts

### Version

ERPNext: v13.17.0 (version-13)
Frappe Framework: v13.17.1 (version-13)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "apps/frappe/frappe/model/document.py", line 239, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 500, in _validate
    self._validate_length()
  File "apps/frappe/frappe/model/base_document.py", line 727, in _validate_length
    self.throw_length_exceeded_error(df, max_length, value)
  File "apps/frappe/frappe/model/base_document.py", line 754, in throw_length_exceeded_error
    frappe.throw(_("{0}: '{1}' ({3}) will get truncated, as max characters allowed is {2}")\
  File "apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CharacterLengthExceededError: Sales Invoice SF-22-02-0001: 'Customer's Purchase Order' (218559-188-2, 218559-242-1, 218559-289-1, 218559-240-1, 218559-237-2, 218559-246-2, 218559-239-1, 218559-239-2, 218559-243-2, 218559-17-3, 218559-238-1, 218559-125-3, 218559-245-2, 218559-244-2, 218559-212-1, 218559-240-2, 218559-242-2, 218559-216-1, 218559-245-1, 218559-238-2, 218559-243-1, 218559-244-1, 218559-237-1, 218559-246-1, 218559-289-2) will get truncated, as max characters allowed is 255
request.js:418:14
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "apps/frappe/frappe/model/document.py", line 239, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 500, in _validate
    self._validate_length()
  File "apps/frappe/frappe/model/base_document.py", line 727, in _validate_length
    self.throw_length_exceeded_error(df, max_length, value)
  File "apps/frappe/frappe/model/base_document.py", line 754, in throw_length_exceeded_error
    frappe.throw(_("{0}: '{1}' ({3}) will get truncated, as max characters allowed is {2}")\
  File "apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CharacterLengthExceededError: Sales Invoice SF-22-02-0001: 'Customer's Purchase Order' (218559-188-2, 218559-242-1, 218559-289-1, 218559-240-1, 218559-237-2, 218559-246-2, 218559-239-1, 218559-239-2, 218559-243-2, 218559-17-3, 218559-238-1, 218559-125-3, 218559-245-2, 218559-244-2, 218559-212-1, 218559-240-2, 218559-242-2, 218559-216-1, 218559-245-1, 218559-238-2, 218559-243-1, 218559-244-1, 218559-237-1, 218559-246-1, 218559-289-2) will get truncated, as max characters allowed is 255
```

**Comment by ankush** [comment]
Hey @TurkerTunali 

This field is only used for storing references, so changing it to the small text type should be fine. Text fields have very high limit, only drawback is they can't be indexed properly so they shouldn't be used for any field which needs to be filtered upon often (e.g. Customer).

Also the field was supposed to be used for single PO number only (as per current design)

**Comment by TurkerTunali** [comment]
Thank you for clarification.

**Comment by TurkerTunali** [comment]
Thank you for clarification.
