### ISSUE TITLE
uncaught server exception

### ISSUE THREAD

**Issue by leafkage** [frappe/erpnext#29586]
### Information about bug

![Uploading image.png…]()

without user enrollment into the course, the user is able to access the course under the program.

### Module

education

### Version

ERPNext: v13.0.0-beta.14 (version-13-beta)

Frappe Framework: v13.0.0-beta.12 (version-13-beta)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
jinja2.exceptions.UndefinedError: 'progress' is undefined
```

**Comment by ankush** [comment]
> ERPNext: v13.0.0-beta.14 (version-13-beta)



update the version, this is more than a year old and beta version 😅 


Also image isn't visible in issue description, reupload?

**Comment by leafkage** [comment]
we are facing the following error in some courses in the LMS.


Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 79, in top-level template code
    <span class="indicator blue">{{_('Start')}}</span>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 66, in top-level template code
    {{ banner_html or "" }}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 96, in block "content"
    {{ card(topic) }}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 74, in template
    {% if progress[topic.name].completed %}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'progress' is undefined

**Comment by leafkage** [comment]
Hi Ankush ,
We are facing a error in some courses in LMS .

Thanks & Regards
Sanket Bhendarkar

**Comment by ankush** [comment]
please don't create duplicates. https://github.com/frappe/erpnext/issues/29590

**Comment by leafkage** [comment]
can updating the version could solve this issue? if yes then which version should I install?
