### ISSUE TITLE
Cannot merge an account [ValueError: unsupported format character]

### ISSUE THREAD

**Issue by kurogeek** [frappe/erpnext#29583]
### Information about bug

I tried to merge an account named "VAT - RCL" into "1501 - Buying VAT 7% - RCL" and I got an error `ValueError: unsupported format character 'R' (0x52) at index 74`.

![image](https://user-images.githubusercontent.com/7752934/152082166-e38b6316-b365-460e-a252-8a5db7150a78.png)

![image](https://user-images.githubusercontent.com/7752934/152082218-407061fd-3def-408e-a6d8-6687c9ec5c64.png)

### Module

accounts

### Version

Frappe Version - v13.19.0 (version-13)
ERPNext Version - v13.19.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/account/account.py", line 367, in merge_account
    frappe.rename_doc("Account", old, new, merge=1, force=1)
  File "apps/frappe/frappe/__init__.py", line 971, in rename_doc
    return rename_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 90, in rename_doc
    rename_eps_records(doctype, old, new)
  File "apps/frappe/frappe/model/rename_doc.py", line 194, in rename_eps_records
    (frappe.qb.update(epl)
  File "apps/frappe/frappe/query_builder/utils.py", line 56, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs) # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 148, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
ValueError: unsupported format character 'R' (0x52) at index 74
```

**Comment by ankush** [comment]
the problem is because of `%` in name.
