### ISSUE TITLE
Uncaught Server Exception occurs for some courses in LMS 

### ISSUE THREAD

**Issue by leafkage** [frappe/erpnext#29590]
### Information about bug

The user was enrolled in the program. I think it creates the course enrollment automatically for all the courses under the program at that point in time. If a new course is added to the program, it shows this error. 
Given this info, see what is the best way to handle this. I am OK if it gives the proper message that the Course enrolment needs to be done. The cryptic error is not ok.

Traceback: 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 223, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 79, in top-level template code
    <span class="indicator blue">{{_('Start')}}</span>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 66, in top-level template code
    {{ banner_html or "" }}
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 96, in block "content"
    {{ card(topic) }}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./www/lms/course.html", line 74, in template
    {% if progress[topic.name].completed %}
  File "/home/frappe/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'progress' is undefined

### Module

education

### Version

ERPNext: v13.0.0-beta.14 (version-13-beta)

Frappe Framework: v13.0.0-beta.12 (version-13-beta)

### Installation method

FrappeCloud

**Comment by leafkage** [comment]
can updating the version could solve this issue? if yes then which version should I install?
