### ISSUE TITLE
TypeError on opening Sales Invoice

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#29591]
### Information about bug

https://user-images.githubusercontent.com/52111700/152133636-94274826-f55d-43ba-a85d-f6c28e129ab7.mp4

### Module

accounts

### Version

ERPNext: v13.19.0 (HEAD)
Frappe Framework: v13.19.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
TypeError: validate_link() missing 1 required positional argument: 'docname'
```

**Comment by rtdany10** [comment]
Similar issue https://github.com/frappe/erpnext/issues/29568

I hope https://github.com/frappe/frappe/pull/15776 fixes this too.
@surajshetty3416

**Comment by ankush** [comment]
This was fixed couple of releases ago.
