### ISSUE TITLE
Getting server error module 'erpnext' has no attribute get_company_currency

### ISSUE THREAD

**Issue by Subramani830** [frappe/erpnext#29619]
### Information about bug

Unable to create the Purchase Order, Purchase Invoice and Purchase receipt.
Facing error module 'erpnext' has no attribute get_company_currency.

![image](https://user-images.githubusercontent.com/75359186/152320296-2ef78103-ab7c-4a22-a3b3-87841a5f4af3.png)

### Module

buying

### Version

ERPNext: v13.19.0
Frappe : v13.19.0

**Comment by kennethsequeira** [comment]
@Subramani830 this issue is still persisting?

Please paste the entire error log from the browser console or by clicking on Report/Copy Error.

The traceback will be helpful in detecting the root cause

**Comment by Craftint** [comment]
Getting same error on many sites. Is it related to network speed

**Comment by mhbu50** [comment]
I am also facing the same issue with many sites in frappe cloud:

### App Versions
```
{
	"erpnext": "13.36.5",
	"frappe": "13.39.1",
	"lubeoil": "0.0.1"
}
```
### Route
```
Form/Payment Entry/ACC-PAY-2022-05040
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1243, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 94, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 812, in make_gl_entries
    gl_entries = process_gl_map(gl_entries)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 99, in process_gl_map
    gl_map = merge_similar_entries(gl_map, precision)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 169, in merge_similar_entries
    company_currency = erpnext.get_company_currency(company)
AttributeError: module 'erpnext' has no attribute 'get_company_currency'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-PAY-2022-05040\",\"owner\":\"nasiruddin@saudilubeoil.com\",\"creation\":\"2022-09-01 11:30:30.831659\",\"modified\":\"2022-09-01 11:30:31.106335\",\"modified_by\":\"nasiruddin@saudilubeoil.com\",\"idx\":0,\"docstatus\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Receive\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2022-08-22\",\"company\":\"Saudi Technology Lube Oil Plant\",\"party_type\":\"Customer\",\"party\":\"CUST-00271\",\"party_name\":\"Mahattat Asmaa Ali Al Zahrani\",\"party_balance\":10524.05,\"paid_from\":\"11110000000 - Debtors - STLOP\",\"paid_from_account_type\":\"Receivable\",\"paid_from_account_currency\":\"SAR\",\"paid_from_account_balance\":10524.05,\"paid_to\":\"11490000000 - Sales Rep. Yaqoub Abdulraheem Fund - STLOP\",\"paid_to_account_type\":\"Cash\",\"paid_to_account_currency\":\"SAR\",\"paid_to_account_balance\":33792.95,\"paid_amount\":3750,\"paid_amount_after_tax\":3750,\"source_exchange_rate\":1,\"base_paid_amount\":3750,\"base_paid_amount_after_tax\":3750,\"received_amount\":3750,\"received_amount_after_tax\":3750,\"target_exchange_rate\":1,\"base_received_amount\":3750,\"base_received_amount_after_tax\":3750,\"total_allocated_amount\":3750,\"base_total_allocated_amount\":3750,\"unallocated_amount\":0,\"difference_amount\":0,\"apply_tax_withholding_amount\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_no\":\"5758\",\"status\":\"Draft\",\"custom_remarks\":0,\"remarks\":\"Amount SAR 3750 received from CUST-00271\\nTransaction reference no 5758 dated None\\nAmount SAR 1571.55 against Sales Invoice ACC-SINV-2022-01436\\nAmount SAR 1725 against Sales Invoice ACC-SINV-2022-01630\\nAmount SAR 453.4499999999998 against Sales Invoice ACC-SINV-2022-02142\",\"letter_head\":\"Stander Header\",\"title\":\"CUST-00271\",\"doctype\":\"Payment Entry\",\"references\":[{\"name\":\"f7ead2768d\",\"owner\":\"nasiruddin@saudilubeoil.com\",\"creation\":\"2022-09-01 11:30:30.831659\",\"modified\":\"2022-09-01 11:30:30.944743\",\"modified_by\":\"nasiruddin@saudilubeoil.com\",\"parent\":\"ACC-PAY-2022-05040\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"idx\":1,\"docstatus\":0,\"reference_doctype\":\"Sales Invoice\",\"reference_name\":\"ACC-SINV-2022-01436\",\"due_date\":\"2022-03-05\",\"total_amount\":2571.5,\"outstanding_amount\":1571.55,\"allocated_amount\":1571.55,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"doctype\":\"Payment Entry Reference\"},{\"name\":\"32a690cae6\",\"owner\":\"nasiruddin@saudilubeoil.com\",\"creation\":\"2022-09-01 11:30:30.831659\",\"modified\":\"2022-09-01 11:30:30.964500\",\"modified_by\":\"nasiruddin@saudilubeoil.com\",\"parent\":\"ACC-PAY-2022-05040\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"idx\":2,\"docstatus\":0,\"reference_doctype\":\"Sales Invoice\",\"reference_name\":\"ACC-SINV-2022-01630\",\"due_date\":\"2022-03-26\",\"total_amount\":1725,\"outstanding_amount\":1725,\"allocated_amount\":1725,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"doctype\":\"Payment Entry Reference\"},{\"name\":\"d3741d6998\",\"owner\":\"nasiruddin@saudilubeoil.com\",\"creation\":\"2022-09-01 11:30:30.831659\",\"modified\":\"2022-09-01 11:30:30.988673\",\"modified_by\":\"nasiruddin@saudilubeoil.com\",\"parent\":\"ACC-PAY-2022-05040\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"idx\":3,\"docstatus\":0,\"reference_doctype\":\"Sales Invoice\",\"reference_name\":\"ACC-SINV-2022-02142\",\"due_date\":\"2022-04-21\",\"total_amount\":3484.5,\"outstanding_amount\":3484.5,\"allocated_amount\":453.45,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"doctype\":\"Payment Entry Reference\"}],\"taxes\":[],\"deductions\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2022-09-01T09:22:44.868Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery224028854317071246771": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1251,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: module 'erpnext' has no attribute 'get_company_currency'"
}
```

**Comment by Craftint** [comment]
Getting the same issue on multiple instances hosted on frappe cloud. Either on opening report or customer or invoices. It is getting temporarily fixed by restart only. 
Need an urgent solution.

![image](https://user-images.githubusercontent.com/67686213/207531232-593488c5-e33d-4b2d-b9af-dea1bc6a882e.png)
