### ISSUE TITLE
Error when having a slideshow for item with variants in eCommerce

### ISSUE THREAD

**Issue by roquegv** [frappe/erpnext#29713]
### Information about bug

Hi there.
When accessing a Item's details in website, the system throws the following error:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 216, in build_page
    context = get_context(path)
  File "apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "apps/frappe/frappe/website/context.py", line 97, in build_context
    ret = context.doc.get_context(context)
  File "apps/erpnext/erpnext/e_commerce/doctype/website_item/website_item.py", line 213, in get_context
    self.set_variant_context(context)
  File "apps/erpnext/erpnext/e_commerce/doctype/website_item/website_item.py", line 274, in set_variant_context
    if self.slideshow and context.variant and context.variant.slideshow:
AttributeError: 'Item' object has no attribute 'slideshow'
```
To reproduce the error, follow:

0. Make sure the "Hide variants" checkbox in E Commerce Setting is checked
1. Create a template Item ("has variants" checked)
2. Create some variants
3. Create a Website Slideshow
4. Create Website Items for template and variants items created previously (Item > Actions > Publish in Website)
5. Enter the template's Website Item and set the slideshow
6. Access the template website item in website

Here is the post on the forum: [https://discuss.erpnext.com/t/error-when-having-a-slideshow-for-item-with-variants-in-ecommerce/84816](https://discuss.erpnext.com/t/error-when-having-a-slideshow-for-item-with-variants-in-ecommerce/84816)

Thanks

### Module

ecommerce

### Version

Frappe version: 13.17.1
ERPNext version: 13.17.0

### Installation method

easy-install

**Comment by ankush** [comment]
update to latest version: https://github.com/frappe/erpnext/pull/29219
