### ISSUE TITLE
cannot upgrade to V5

### ISSUE THREAD

**Issue by collinssolutions** [frappe/erpnext#2973]
I am seeing some different post about if V5 is available. I setup my server with the script and i am running 

Installed Apps

ERPNext: v4.24.1
Open Source Enterprise Resource Planning for Small and Midsized Organizations

Frappe Framework: v4.13.2
Full Stack Web Application Framework in Python

Shopping Cart: v0.7.0
Online Shopping Cart integrated with ERPNext

When i run bench migrate-to-v5
Usage: bench [OPTIONS] COMMAND [ARGS]...

Error: No such command "migrate-to-v5".

Is V5 not available? If it is how do i upgrade to it.

**Comment by pdvyas** [comment]
V5 is available in develop branch (ie. for testing, not for production).
Run,
```
bench update
bench switch-to-develop
bench retry-upgrade
```

**Comment by pandeybk** [comment]
I received following error message when I followed above steps,

```
database backup taken - ./site1.local/private/backups/20150330_38158354_database.sql.gz - on 2015-03-31 08:44:21.095029
Migrating site1.local
Executing erpnext.patches.v4_4.make_email_accounts in site1.local (1bd3e0294d)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 202, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v4_4/make_email_accounts.py", line 4, in execute
    frappe.reload_doc("email", "doctype", "email_account")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 520, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 37, in reload_doc
    return import_files(module, dt, dn, force=force)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 17, in import_files
    return import_file(module, dt, dn, force=force)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 22, in import_file
    ret = import_file_by_path(path, force)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 120, in import_doc
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 553, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 501, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 614, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 597, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 495, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 113, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 122, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 62, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(get_module_name(doctype, module, prefix))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 529, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 10, in <module>
    from frappe.email.receive import POP3Server, Email
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 11, in <module>
    from email_reply_parser import EmailReplyParser
ImportError: No module named email_reply_parser
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 55, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 244, in update
    patch_sites()
  File "/home/frappe/bench-repo/bench/utils.py", line 117, in patch_sites
    run_frappe_cmd('--site', 'all', 'migrate', bench=bench)
  File "/home/frappe/bench-repo/bench/utils.py", line 422, in run_frappe_cmd
    subprocess.check_call((f, '-m', 'frappe.utils.bench_helper', 'frappe') + args, cwd=sites_dir)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/home/frappe/frappe-bench/env/bin/python', '-m', 'frappe.utils.bench_helper', 'frappe', '--site', 'all', 'migrate')' returned non-zero exit status 1
```

**Comment by pdvyas** [comment]
```
bench update --requirements
bench retry-upgrade
```

**Comment by pandeybk** [comment]
Now following logs when ``` bench update --requirements```

```
Exception:
  Traceback (most recent call last):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 782, in unpack_url
      session,
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 667, in unpack_http_url
      from_path, content_type = _download_http_url(link, session, temp_dir)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 843, in _download_http_url
      _download_url(resp, link, content_file)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 615, in _download_url
      for chunk in progress_indicator(resp_read(4096), 4096):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 580, in resp_read
      decode_content=False):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 256, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 186, in read
      data = self._fp.read(amt)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
      self.__callback(self.__buf.getvalue())
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 205, in cache_response
      self.serializer.dumps(request, response, body=body),
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
      ).encode("utf8"),
  MemoryError

Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 55, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 236, in update
    update_requirements()
  File "/home/frappe/bench-repo/bench/utils.py", line 308, in update_requirements
    exec_cmd("{pip} install -q -r {req_file}".format(pip=pip, req_file=req_file))
  File "/home/frappe/bench-repo/bench/utils.py", line 72, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './env/bin/pip install -q -r ./apps/frappe/requirements.txt' returned non-zero exit status 2
```

**Comment by pandeybk** [comment]
I tried ``` ./env/bin/pip install -q -r ./apps/frappe/requirements.txt``` manually and realized that there are some permission issue which I fixed them. Then I tried ```bench retry-upgrade``` same error message mention in first thread.

**Comment by pandeybk** [comment]
looks like system pip is different then bench using when I tried ```./env/bin/pip install -q -r ./apps/frappe/requirements.txt``` following error message is display

```
  Exception:
  Traceback (most recent call last):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 782, in unpack_url
      session,
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 667, in unpack_http_url
      from_path, content_type = _download_http_url(link, session, temp_dir)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 843, in _download_http_url
      _download_url(resp, link, content_file)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 615, in _download_url
      for chunk in progress_indicator(resp_read(4096), 4096):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/download.py", line 580, in resp_read
      decode_content=False):
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 256, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 186, in read
      data = self._fp.read(amt)
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
      self.__callback(self.__buf.getvalue())
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 205, in cache_response
      self.serializer.dumps(request, response, body=body),
    File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
      ).encode("utf8"),
  MemoryError
```

**Comment by rmehta** [comment]
seems like you are out of memory, you might want to increase your VM size?

**Comment by pandeybk** [comment]
Thank you rmehta for pointing to right direction. I have added some swap memory and it works.

Others digital ocean user may find helpful, following solution works:

https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps
