### ISSUE TITLE
Datev Report: Download zip file fails, if company has special chars in it. Results in JSONDecodeError

### ISSUE THREAD

**Issue by itsdaveit** [frappe/erpnext#29731]
### Information about bug

Because of the window.open with filters in
https://github.com/frappe/erpnext/blob/9dec4a2454e2eb1dcee0015c9d319c05c69bf90b/erpnext/regional/report/datev/datev.js#L44
the filters dict gets truncated before its used in
https://github.com/frappe/erpnext/blob/9dec4a2454e2eb1dcee0015c9d319c05c69bf90b/erpnext/regional/report/datev/datev.py#L549
when company name contains "&" (or maybe other chars, which don`t get decoded from the URL correctly)

Workaround: Rename your Company from "Hans & Franz" to "Hans und Franz"

### Module

regional

### Version

ERPNext: v13.17.0 (version-13)
Frappe Framework: v13.17.1 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/regional/report/datev/datev.py", line 549, in download_datev_csv
    filters = json.loads(filters)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 12 (char 11)
```

**Comment by itsdaveit** [comment]
@barredterra Thanks again for your great Work!

**Comment by barredterra** [comment]
Thanks for reporting!
