### ISSUE TITLE
Failing patches while migrating to V13

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#29808]
### Information about bug

Hi ,

There are a couple of patches failing while migrating from V12 to V13. Please see below:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench2/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/commands/site.py", line 309, in migrate
    skip_search_index=skip_search_index
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/migrate.py", line 69, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench2/apps/erpnext/erpnext/patches/v13_0/update_old_loans.py", line 90, in execute
    loan_type_doc.submit()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 327, in _save
    self._validate()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 497, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-bench2/apps/frappe/frappe/model/document.py", line 822, in _validate_mandatory
    name=self.name))
frappe.exceptions.MandatoryError: [Loan Type, DEMO LOAN]: disbursement_account
```
The other one is already reported here:

https://github.com/frappe/erpnext/issues/28568

Thanks

### Module

other

### Version

Frappe: v12.25.0 (version-12)

ERPNext: v12.28.0 (version-12)

**Comment by deepeshgarg007** [comment]
This should be resolved, closing
