### ISSUE TITLE
Unable to open salary slip list page

### ISSUE THREAD

**Issue by iamejaaz** [frappe/erpnext#29882]
### Information about bug

Hey there,
Upon opening the Salary slip list page, I got the following error and blank page, below is the screenshot.
![image](https://user-images.githubusercontent.com/67804911/154796973-efe14f68-952f-43d2-a212-0237cbd8653b.png)
![image](https://user-images.githubusercontent.com/67804911/154797035-2a80cffd-ed5c-45dd-9352-47e2d0301500.png)

### Module

HR

### Version

"erpnext": "14.0.0-dev",
"frappe": "14.0.0-dev"

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev"
}
```
### Route
```
List/Salary Slip/List
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 20, in get_meta
    meta = FormMeta(meta)
  File "apps/frappe/frappe/desk/form/meta.py", line 34, in __init__
    super(FormMeta, self).__init__(doctype)
  File "apps/frappe/frappe/model/meta.py", line 90, in __init__
    super(Meta, self).__init__(doctype)
  File "apps/frappe/frappe/model/document.py", line 123, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 81, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 167, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 214, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 191, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 231, in _init_child
    raise AttributeError(key)
AttributeError: __print_formats

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Salary Slip",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
### Response Data
```
{
	"exception": "AttributeError: __print_formats"
}
```
```

**Comment by naquiuddin** [comment]
Here is some information, somebody else is also getting the error.

https://discuss.erpnext.com/t/attributeerror-print-format/86362/3

**Comment by iamejaaz** [comment]
Solved https://github.com/frappe/frappe/pull/16069

**Comment by naquiuddin** [comment]
Great Thanks
