### ISSUE TITLE
Not able to navigate to POS profile

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29930]
Created a new POS profile and then opened it. But then getting the following error

### App Versions
```
{
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev"
}
```
### Route
```
point-of-sale
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 20, in get_meta
    meta = FormMeta(meta)
  File "apps/frappe/frappe/desk/form/meta.py", line 34, in __init__
    super(FormMeta, self).__init__(doctype)
  File "apps/frappe/frappe/model/meta.py", line 90, in __init__
    super(Meta, self).__init__(doctype)
  File "apps/frappe/frappe/model/document.py", line 123, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 81, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 167, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 214, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 191, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 231, in _init_child
    raise AttributeError(key)
AttributeError: __print_formats

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "POS Invoice",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
### Response Data
```
{
	"exception": "AttributeError: __print_formats"
}
```

### Module

accounts

### Version

v14

**Comment by sharmanakul** [comment]
it is observed on the other pages as well.

**Comment by yadavyk** [comment]
Also unable to navigate to Sales Invoice doctype. The list view for a lot of doctypes is broken and shows similar error @surajshetty3416 . 

![Sales Inoice](https://user-images.githubusercontent.com/32797974/155067414-de890457-0faa-4e4c-8faa-462f1fed6453.png)
