### ISSUE TITLE
Can not rename  item and check merge option if merged item has stock (tabBin record exists) anymore

### ISSUE THREAD

**Issue by kanedai** [frappe/erpnext#30048]
### Information about bug

When I  need to merge 2 items, I use the rename button and click the "Merge with existing (This cannot be undone)" box.
And it will report an error: " pymysql.err.IntegrityError: (1062, "Duplicate entry '542432-WAREHOUSE' for key 'unique_item_warehouse'")"

### Module

stock

### Version

Frappe:13.21.0
Erpnext 13.21.0

### Relevant log output / Stack trace / Full Error Message.

```shell
pymysql.err.IntegrityError: (1062, "Duplicate entry '542432-WAREHOUSE'' for key 'unique_item_warehouse'")
```

**Comment by szufisher** [comment]
browser console log:

```
request.js:425 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 976, in rename_doc
    return rename_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 76, in rename_doc
    update_link_field_values(link_fields, old, new, doctype)
  File "apps/frappe/frappe/model/rename_doc.py", line 294, in update_link_field_values
    frappe.db.set_value(parent, {docfield: old}, docfield, new, update_modified=False)
  File "apps/frappe/frappe/database/database.py", line 705, in set_value
    query.run(debug=debug)
  File "apps/frappe/frappe/query_builder/utils.py", line 59, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs) # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'N55208280-直运仓库 - GUBT' for key 'unique_item_warehouse'")
```

exception triggered by this SQL statement

```
SELECT `name`
FROM `tabBin`
WHERE `item_code` = 'N55208271'
ORDER BY modified DESC
FOR
UPDATE
```

seems caused by the changed item_code,warehouse index on tabBin from non-unique to unique.

![{DF8C89B6-8E1E-70C2-A17F-8B7C867A7AC3}](https://user-images.githubusercontent.com/12823863/156568059-a6101735-b63c-42ad-a591-f162eadfef02.jpg)
Fig1: screen shot from recorder screen



![image](https://user-images.githubusercontent.com/12823863/156567534-382529f0-a4e8-4722-95da-0f64f4babf59.png)
Fig 2: index version 13.21


![image](https://user-images.githubusercontent.com/12823863/156567874-2492b49f-2da1-4781-a700-7950f2b473c6.png)
Fig 3: index version before 13.21

**Comment by ankush** [comment]
probably broken after https://github.com/frappe/erpnext/pull/29519
