### ISSUE TITLE
Database error in Virtual Field while marking Attendance

### ISSUE THREAD

**Issue by ejaazkhan** [frappe/erpnext#30124]
### Information about bug

- I have added Custom Virtual Field as `less_minutes` in Attendance Doctype
![image](https://user-images.githubusercontent.com/67804911/157376786-97b098d9-658e-4859-8c58-5bea7e78af6d.png)

- The Employee check-ins are here.
![image](https://user-images.githubusercontent.com/67804911/157377192-d010d364-b26a-4e60-8bae-0cf80d343c9d.png)

- When I Click Mark attendance button in Shift I got below error
![image](https://user-images.githubusercontent.com/67804911/157377362-938f1774-0a8c-4754-b792-85e86d73a1ca.png)

### Module

HR

### Version

"erpnext": "14.0.0-beta.2",
"frappe": "14.0.0-beta.2",

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.0.0-beta.2",
	"frappe": "14.0.0-beta.2",
}
```
### Route
```
Form/Shift Type/Morning Shift
```
### Trackeback
```python
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 263, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1170, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1153, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 867, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/hr/doctype/shift_type/shift_type.py", line 40, in process_auto_attendance
    mark_attendance_and_link_log(single_shift_logs, attendance_status, key[1].date(), working_hours, late_entry, early_exit, in_time, out_time, self.name)
  File "apps/erpnext/erpnext/hr/doctype/employee_checkin/employee_checkin.py", line 112, in mark_attendance_and_link_log
    attendance.submit()
  File "apps/frappe/frappe/model/document.py", line 944, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 932, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    self.db_update()
  File "apps/frappe/frappe/model/base_document.py", line 480, in db_update
    frappe.db.sql("""UPDATE `tab{doctype}`
  File "apps/frappe/frappe/database/database.py", line 152, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'less_minutes' in 'field list'")

```
### Request Data
```json
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"Morning Shift\",\"owner\":\"Administrator\",\"creation\":\"2022-03-07 12:47:14.564593\",\"modified\":\"2022-03-08 16:16:36.897199\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"start_time\":\"10:00:00\",\"end_time\":\"13:00:00\",\"holiday_list\":\"Weekly Holiday\",\"enable_auto_attendance\":1,\"determine_check_in_and_check_out\":\"Strictly based on Log Type in Employee Checkin\",\"working_hours_calculation_based_on\":\"First Check-in and Last Check-out\",\"begin_check_in_before_shift_start_time\":60,\"allow_check_out_after_shift_end_time\":60,\"working_hours_threshold_for_half_day\":0,\"working_hours_threshold_for_absent\":0,\"process_attendance_after\":\"2022-03-01\",\"last_sync_of_checkin\":\"2022-03-08 15:06:33\",\"enable_entry_grace_period\":1,\"late_entry_grace_period\":5,\"enable_exit_grace_period\":0,\"early_exit_grace_period\":0,\"doctype\":\"Shift Type\",\"__last_sync_on\":\"2022-03-09T05:03:02.235Z\"}",
		"method": "process_auto_attendance"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method"
}
```
### Response Data
```json
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'less_minutes' in 'field list'\")"
}
```
```

**Comment by ankush** [comment]
No such field in ERPNext. probably customization or custom app. 

https://github.com/frappe/erpnext/search?q=less_minutes

**Comment by ejaazkhan** [comment]
> No such field in ERPNext. Probably issue customization or custom app.
> 
> https://github.com/frappe/erpnext/search?q=less_minutes

I know no such field in ERPNext, but I have added Virtual Field, Then why it is trying to store virtual field value in Database?

**Comment by ankush** [comment]
@gavindsouza 🥲
