### ISSUE TITLE
Can't set quantity in purchase invoice (AttributeError: 'NoneType' object has no attribute 'options')

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#30129]
### Information about bug

When creating a new purchase invoice, the following error pops up, as soon as you enter an item and try to set its quantity.

### Module

buying

### Version

{
	"erpnext": "13.22.0",
	"frappe": "13.22.0"
}

### Relevant log output / Stack trace / Full Error Message.

```shell
Route
Form/Purchase Invoice/new-purchase-invoice-1


Error Report
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 209, in apply_pricing_rule
    data = get_pricing_rule_for_item(args_copy, item.get('price_list_rate'), doc=doc)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 241, in get_pricing_rule_for_item
    doc = frappe.get_doc(doc)
  File "apps/frappe/frappe/__init__.py", line 891, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 75, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 49, in __init__
    super(PurchaseInvoice, self).__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 67, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 122, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 85, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 234, in _init_child
    value = get_controller(value["doctype"])(value)
  File "apps/frappe/frappe/model/document.py", line 122, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 85, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 230, in _init_child
    value["doctype"] = self.get_table_field_doctype(key)
  File "apps/frappe/frappe/model/base_document.py", line 350, in get_table_field_doctype
    return self.meta.get_field(fieldname).options
AttributeError: 'NoneType' object has no attribute 'options'
```

**Comment by ankush** [comment]
@carstenblt  can you update to the latest release and confirm if this is resolved? https://github.com/frappe/erpnext/releases/tag/v13.22.1

**Comment by carstenblt** [comment]
@ankush Fixed! Thank you!
