### ISSUE TITLE
Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'

### ISSUE THREAD

**Issue by Fehndruid** [frappe/erpnext#30204]
### Information about bug

Moin,
1. create article, only to purchase, no stock article
2. create purchase invoice, with this article and book
3. got this error: pymysql.err.OperationalError: (1054, \"Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'\")

So I couldn't book purchase invoices. I tried it two times, with new created invoices, the error is reproducible. What's wrong? What could help?

Regards

### Module

stock, buying

### Version

- "erpnext": "13.22.1",
- "frappe": "13.22.1"

- ERPNext-12 Ubuntu Image, 
- upgraded to ERP13, 
- upgraded OS Updates (no System upgrade until now), 
- upgraded to python 3.8 and created new environment with frappe and erpnext.

### Relevant log output / Stack trace / Full Error Message.

```shell
### Route

Form/Purchase Invoice/ACC-PINV-2022-00007
``` 
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 341, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1007, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 866, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 431, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 444, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 474, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 549, in make_item_gl_entries
    provisional_accounting_for_non_stock_items = cint(frappe.db.get_value('Company', self.company,
  File "apps/frappe/frappe/database/database.py", line 413, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "apps/frappe/frappe/database/database.py", line 458, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update, for_update=for_update)
  File "apps/frappe/frappe/database/database.py", line 617, in _get_values_from_table
    r = self.sql("select {fields} from `tab{doctype}` {where} {conditions} {order_by} {for_update}"
  File "apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'")

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 341, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1007, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 866, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 431, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 444, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 474, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 549, in make_item_gl_entries
    provisional_accounting_for_non_stock_items = cint(frappe.db.get_value('Company', self.company,
  File "apps/frappe/frappe/database/database.py", line 413, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "apps/frappe/frappe/database/database.py", line 458, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update, for_update=for_update)
  File "apps/frappe/frappe/database/database.py", line 617, in _get_values_from_table
    r = self.sql("select {fields} from `tab{doctype}` {where} {conditions} {order_by} {for_update}"
  File "apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
                "doc": "{\"name\":\"ACC-PINV-...\",...}",
		"action": "Submit"
	},
	"btn": {
		"jQuery2240435407192211073161": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4397,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'\")"
}
```
```

**Comment by ankush** [comment]
Your system isn't correctly migrated. Run `bench migrate` or check for existence of this column. 

https://github.com/frappe/erpnext/blob/468964a3f7f7a0e1c9c4c2b458c44072a8a2ef49/erpnext/setup/doctype/company/company.json#L730-L735

**Comment by Fehndruid** [comment]
I complete that, a similar error occurred by all other booking actions.
That entry is set in that file. But <code>bench migrate</code> solved my problem. Many Thanks @ankush
