### ISSUE TITLE
'HTML2Text' object has no attribute 'unescape' in Itemwise Purchase Register

### ISSUE THREAD

**Issue by akshay83** [frappe/erpnext#30374]
### Information about bug

Unable to open Itemwise purchase register.

### Module

accounts

### Version

ERPNext: v13.21.0 (version-13)
Frappe Framework: v13.21.0 (version-13)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 629, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 244, in run
    result = generate_report_result(report, filters, user, custom_columns)
  File "apps/frappe/frappe/__init__.py", line 629, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 86, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 133, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 150, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py", line 22, in execute
    return _execute(filters)
  File "apps/erpnext/erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py", line 33, in _execute
    itemised_tax, tax_columns = get_tax_accounts(item_list, columns, company_currency,
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 468, in get_tax_accounts
    description = handle_html(description)
  File "apps/frappe/frappe/utils/xlsxutils.py", line 66, in handle_html
    h = h.unescape(data or "")
AttributeError: 'HTML2Text' object has no attribute 'unescape'
```

**Comment by ankush** [comment]
update to latest version https://github.com/frappe/frappe/issues/15779
