### ISSUE TITLE
TypeError on Tax Withholding Category Creation

### ISSUE THREAD

**Issue by Muhsina-V-P** [frappe/erpnext#30379]
### Information about bug

Getting type error while creating new Tax Withholding Category.

TypeError: '<' not supported between instances of 'int' and 'NoneType'

![Screenshot from 2022-03-23 15-28-06](https://user-images.githubusercontent.com/75487959/159674099-6c915be2-c1be-4ebb-b210-dfcd08aeafc3.png)

Frappe version - v13.23.0 (version-13)
ERPNext version - v13.23.0 [(version-13)

### Module

accounts

### Version

Frappe version - v13.23.0 (version-13)
ERPNext version - v13.23.0 (version-13)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 240, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 971, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 863, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 14, in validate
    self.validate_thresholds()
  File "apps/erpnext/erpnext/accounts/doctype/tax_withholding_category/tax_withholding_category.py", line 28, in validate_thresholds
    if d.cumulative_threshold and d.cumulative_threshold < d.single_threshold:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by SherinKR** [comment]
#30382 Check this
