### ISSUE TITLE
"NameError: name 'CONSOLE' is not defined"

### ISSUE THREAD

**Issue by rafiqueromeo** [frappe/erpnext#30421]
### Information about bug

When i try to submit Purchase Invoice. It gives me error
(Server Error
"NameError: name 'CONSOLE' is not defined")

### Module

accounts, buying

### Version

Bench Version: 5.0.0
ERPNext: v12.28.0 (version-12)

Frappe Framework: v12.25.0 (version-12)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:387 Traceback (most recent call last):
  File "/home/wardah/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    else:
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in submit
    return self._submit()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in _submit
    return self.save()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 910, in run_before_save_methods
    self.run_method("before_submit")
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 810, in run_method
    run_server_script_for_doc_event(self, method)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 43, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script.py", line 32, in execute_doc
    safe_exec(self.script, None, dict(doc = doc))
  File "/home/wardah/frappe-bench/apps/frappe/frappe/utils/safe_exec.py", line 31, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 1, in <module>
NameError: name 'CONSOLE' is not defined

request.js:387 Traceback (most recent call last):
  File "/home/wardah/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    else:
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in submit
    return self._submit()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in _submit
    return self.save()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 910, in run_before_save_methods
    self.run_method("before_submit")
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 810, in run_method
    run_server_script_for_doc_event(self, method)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 43, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script.py", line 32, in execute_doc
    safe_exec(self.script, None, dict(doc = doc))
  File "/home/wardah/frappe-bench/apps/frappe/frappe/utils/safe_exec.py", line 31, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 1, in <module>
NameError: name 'CONSOLE' is not defined

api/method/frappe.desk.form.save.savedocs:1          Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:387 Traceback (most recent call last):
  File "/home/wardah/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    else:
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in submit
    return self._submit()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in _submit
    return self.save()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 910, in run_before_save_methods
    self.run_method("before_submit")
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 810, in run_method
    run_server_script_for_doc_event(self, method)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 43, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script.py", line 32, in execute_doc
    safe_exec(self.script, None, dict(doc = doc))
  File "/home/wardah/frappe-bench/apps/frappe/frappe/utils/safe_exec.py", line 31, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 1, in <module>
NameError: name 'CONSOLE' is not defined

request.js:387 Traceback (most recent call last):
  File "/home/wardah/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    else:
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in submit
    return self._submit()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in _submit
    return self.save()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 910, in run_before_save_methods
    self.run_method("before_submit")
  File "/home/wardah/frappe-bench/apps/frappe/frappe/model/document.py", line 810, in run_method
    run_server_script_for_doc_event(self, method)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 43, in run_server_script_for_doc_event
    frappe.get_doc('Server Script', script_name).execute_doc(doc)
  File "/home/wardah/frappe-bench/apps/frappe/frappe/core/doctype/server_script/server_script.py", line 32, in execute_doc
    safe_exec(self.script, None, dict(doc = doc))
  File "/home/wardah/frappe-bench/apps/frappe/frappe/utils/safe_exec.py", line 31, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals) # pylint: disable=exec-used
  File "<unknown>", line 1, in <module>
NameError: name 'CONSOLE' is not defined
```

**Comment by ankush** [comment]
This is an error in your server script.

**Comment by rafiqueromeo** [comment]
Thank you so much dear sir,
Actually i use form Script , but for experiment purpose, I created a Server
script a week ago and forgot to disable or delete that script. Sorry
