### ISSUE TITLE
Stock Entry submission Error: UnboundLocalError: local variable 'sle_doc' referenced before assignment

### ISSUE THREAD

**Issue by beingeek** [frappe/erpnext#30483]
### Information about bug

While Submitting Stock Entry, an error is occurring 

https://user-images.githubusercontent.com/25414115/160644499-b18cdb90-97a4-4a81-951a-b824e180e59d.mp4

 

### Module

stock

### Version

ERPNext: v13.21.1 (version-13)

Frappe Framework: v13.21.0 (version-13)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.21.1",
	"frappe": "13.21.0"
}
```
### Route
```
Form/Stock Entry/STOCK-ENTRY-03291
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 341, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1007, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 863, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 124, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 814, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 293, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 59, in make_sl_entries
    args = sle_doc.as_dict()
UnboundLocalError: local variable 'sle_doc' referenced before assignment

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 341, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1007, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 863, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 124, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 814, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 293, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 59, in make_sl_entries
    args = sle_doc.as_dict()
UnboundLocalError: local variable 'sle_doc' referenced before assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"STOCK-ENTRY-03291\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"idx\":0,\"docstatus\":0,\"naming_series\":\"STOCK-ENTRY-\",\"stock_entry_type\":\"Manufacture\",\"purpose\":\"Manufacture\",\"add_to_transit\":0,\"work_order\":\"MFG-WO-2022-00051-1\",\"company\":\"Abnaa Al Arabiya Company-شركة أبناء العربية\",\"posting_date\":\"2021-02-01\",\"posting_time\":\"21:43:48\",\"set_posting_time\":1,\"inspection_required\":0,\"from_bom\":1,\"apply_putaway_rule\":0,\"bom_no\":\"BOM-6287016760157-007\",\"fg_completed_qty\":42968,\"use_multi_level_bom\":0,\"from_warehouse\":\"4- Work in Progress  - ABNA\",\"to_warehouse\":\"Finished Goods-Central Warehouse - ABNA\",\"total_incoming_value\":173148.58,\"total_outgoing_value\":116443.42,\"value_difference\":56705.16,\"total_additional_costs\":57034.72,\"letter_head\":\"HR\",\"is_opening\":\"No\",\"per_transferred\":0,\"total_amount\":0,\"is_return\":0,\"doctype\":\"Stock Entry\",\"items\":[{\"name\":\"40ad51d3c6\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":1,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"212000001\",\"item_name\":\"Hitachi Black Ink 1067k 500ML\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"Hitachi Black Ink 1067k 500ML\",\"item_group\":\"212 - Ink\",\"qty\":0.85936,\"transfer_qty\":0,\"retain_sample\":0,\"uom\":\"ML\",\"stock_uom\":\"Btl1\",\"conversion_factor\":0.002,\"sample_quantity\":0,\"basic_rate\":225,\"additional_cost\":0,\"valuation_rate\":225,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":193.5,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"65d4c179a7\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":2,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"204000001\",\"item_name\":\"Preform (200ML)  A 29/25  8.43 Gram\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Preform (200ML) 8.43 Gram Blue Color A 29/25 </div><div>بريفورم عنق 29/25 حجم 200 مل وزن 8.43 </div><div><br></div>\",\"item_group\":\"204 - Preforms\",\"qty\":1035847,\"transfer_qty\":1035847,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0.042129005,\"additional_cost\":0,\"valuation_rate\":0.042129005,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":43639.2,\"amount\":43639.2,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":1035847,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"bf8304760d\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":3,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"212000002\",\"item_name\":\"Hitachi Make Up S 100A 800ML\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"Hitachi Make Up S 100A 800ML\",\"item_group\":\"212 - Ink\",\"qty\":1.0742,\"transfer_qty\":0,\"retain_sample\":0,\"uom\":\"ML\",\"stock_uom\":\"Btl\",\"conversion_factor\":0.00125,\"sample_quantity\":0,\"basic_rate\":112,\"additional_cost\":0,\"valuation_rate\":112,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":119.84,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"dbdf4920e9\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":4,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"201000001\",\"item_name\":\"Cap (cr) 29/25 MM Pet  Bottle Closure - Silver Color\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Cap (cr) 29/25 MM Pet  Bottle Closure-Silver Color</div><div>غطاء </div>\",\"item_group\":\"201 - Caps\",\"qty\":1032152,\"transfer_qty\":1032152,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0.012740627,\"additional_cost\":0,\"valuation_rate\":0.012740627,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":13150.26,\"amount\":13150.26,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":1807366,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"ee4081fa86\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":5,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"206000002\",\"item_name\":\"Stretch Film 20mic\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Stretch Film 20mic X 20 Kg</div>\",\"item_group\":\"206 - Stretch-Film\",\"qty\":0.257808,\"transfer_qty\":0.26,\"retain_sample\":0,\"uom\":\"Roll\",\"stock_uom\":\"Roll\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":105.358592849,\"additional_cost\":0,\"valuation_rate\":105.358592849,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":27.39,\"amount\":27.39,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":0.26,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"f3f28dfd2e\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":6,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"202000001\",\"item_name\":\"Glue Carton  Advantra Bold 9430\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Glue Carton  Advantra Bold 9430</div>\",\"item_group\":\"202 - Glue\",\"qty\":180.4656,\"transfer_qty\":180.47,\"retain_sample\":0,\"uom\":\"Kg\",\"stock_uom\":\"Kg\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":19.37766,\"additional_cost\":0,\"valuation_rate\":19.37766,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":3497.09,\"amount\":3497.09,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":180.47,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"e99a623c78\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":7,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"104000001\",\"item_name\":\"Treated Water \",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"Treated Water \",\"item_group\":\"104 - Treated Water\",\"qty\":226871.04,\"transfer_qty\":226871.04,\"retain_sample\":0,\"uom\":\"Litre\",\"stock_uom\":\"Litre\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0.089581362,\"additional_cost\":0,\"valuation_rate\":0.089581362,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":20323.42,\"amount\":20323.42,\"expense_account\":\"533108 - Semi Finished Material Consumption -استهلاك المنتج شبة التام - ABNA\",\"cost_center\":\"20101020201 - RYD FAC R/O 1 UNITS TREATED - ABNA\",\"actual_qty\":226871.04,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"d05be301e2\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":8,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"208000004\",\"item_name\":\"CARTON 200 ML Fridge \",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Carton 200 ML Fridge 32.6 X 21.8 X 12.9 CM</div>\",\"item_group\":\"208 - Packaging Carton\",\"qty\":43190,\"transfer_qty\":43190,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0.656913247,\"additional_cost\":0,\"valuation_rate\":0.656913247,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":28372.08,\"amount\":28372.08,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":43190,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"6d2fbc4d7a\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":9,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"202000002\",\"item_name\":\"Glue Label Carity 4150 ZP\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Glue Label Carity 4150 ZP</div>\",\"item_group\":\"202 - Glue\",\"qty\":6.4452,\"transfer_qty\":6.45,\"retain_sample\":0,\"uom\":\"Kg\",\"stock_uom\":\"Kg\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":16.223143774,\"additional_cost\":0,\"valuation_rate\":16.223143774,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":104.64,\"amount\":104.64,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":6.45,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"4ecc6e025b\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":10,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"203000002\",\"item_name\":\"Printed Bopp 40Mic Label 200 ML (ANOUD) 197 mm X30 mm \",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div><p>Labels 200 ML Ava Water</p><p>ملصق 200 مل</p><p>Printed Bopp 40Mic Label 200 ML (ANOUD) 197 mm X30 mm </p></div>\",\"item_group\":\"203 - Label\",\"qty\":1032841,\"transfer_qty\":1032841,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0.003119,\"additional_cost\":0,\"valuation_rate\":0.003119,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":3221.43,\"amount\":3221.43,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":1032841,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"c4383830d8\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":11,\"docstatus\":0,\"s_warehouse\":\"4- Work in Progress  - ABNA\",\"item_code\":\"207000001\",\"item_name\":\"Wooden Pallet\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"<div>Wooden Pallet 1200 X 1000 MM</div>\",\"item_group\":\"207 - Pallet\",\"qty\":275,\"transfer_qty\":275,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":13.798449249,\"additional_cost\":0,\"valuation_rate\":13.798449249,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":3794.57,\"amount\":3794.57,\"expense_account\":\"533102 - Packaging Material Consumption -استهلاك مواد التغليف - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":275,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"0a62f56dce\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":12,\"docstatus\":0,\"t_warehouse\":\"Finished Goods-Central Warehouse - ABNA\",\"item_code\":\"6287016760157\",\"item_name\":\"AVA Water 200ml Fridge Pack 24 Pcs\",\"is_finished_item\":1,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"Small size pack 4.8 Ltr./Kg. Designed with side easy to open and ideal to keep in the fridge and use at office, home and on the go.\",\"item_group\":\"Fridge Pack\",\"qty\":42962,\"transfer_qty\":42962,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":2.702710855,\"additional_cost\":57034.72,\"valuation_rate\":4.030272887,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":116113.86,\"amount\":173148.58,\"expense_account\":\"535163 - Factory Output -اقفال المصروفات التشغيلية في المنتج النهائي - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":0,\"transferred_qty\":0,\"bom_no\":\"BOM-6287016760157-007\",\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"},{\"name\":\"2d43d70a63\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":13,\"docstatus\":0,\"t_warehouse\":\"Quality Control Damage Central Warehouse  - ABNA\",\"item_code\":\"6287016760157\",\"item_name\":\"AVA Water 200ml Fridge Pack 24 Pcs\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":1,\"description\":\"Small size pack 4.8 Ltr./Kg. Designed with side easy to open and ideal to keep in the fridge and use at office, home and on the go.\",\"item_group\":\"Fridge Pack\",\"qty\":6,\"transfer_qty\":6,\"retain_sample\":0,\"uom\":\"Pcs\",\"stock_uom\":\"Pcs\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0,\"additional_cost\":0,\"valuation_rate\":0,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":0,\"expense_account\":\"535163 - Factory Output -اقفال المصروفات التشغيلية في المنتج النهائي - ABNA\",\"cost_center\":\"20101020101 - LINE PET KR1 - ABNA\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"}],\"additional_costs\":[{\"name\":\"5ec6f6e12b\",\"owner\":\"Administrator\",\"creation\":\"2022-03-29 17:44:22.659265\",\"modified\":\"2022-03-29 18:40:52.476644\",\"modified_by\":\"Administrator\",\"parent\":\"STOCK-ENTRY-03291\",\"parentfield\":\"additional_costs\",\"parenttype\":\"Stock Entry\",\"idx\":1,\"docstatus\":0,\"expense_account\":\"535163 - Factory Output -اقفال المصروفات التشغيلية في المنتج النهائي - ABNA\",\"account_currency\":\"SAR\",\"exchange_rate\":1,\"description\":\"Operating Cost as per Work Order / BOM\",\"amount\":57034.72,\"base_amount\":57034.72,\"doctype\":\"Landed Cost Taxes and Charges\"}],\"__last_sync_on\":\"2022-03-29T15:52:03.685Z\",\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
		"action": "Submit"
	},
	"btn": {
		"jQuery2240135390675280318671": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 281,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "UnboundLocalError: local variable 'sle_doc' referenced before assignment"
}
```
```

**Comment by ankush** [comment]
Check qty in stock UOM, it's 0.

https://github.com/frappe/erpnext/pull/30476
