### ISSUE TITLE
frappe.exceptions.DoesNotExistError: DocType Member not found

### ISSUE THREAD

**Issue by iamejaaz** [frappe/erpnext#30656]
### Information about bug

I switched to the `develop` branch from `version-14-beta` recently, and now when I run `bench migrate`, it throws an error saying "Doctype Member Not Found"

### Module

non-profit

### Version

erpnext 13.x.x-develop
frappe 14.x.x-develop

### Relevant log output / Stack trace / Full Error Message.

```shell
Migrating erpnext.test
Updating DocTypes for frappe        : [========================================] 100%
Updating DocTypes for erpnext       : [========================================] 100%

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ejaaz/frappe-bench/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/commands/site.py", line 457, in migrate
    SiteMigration(
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/migrate.py", line 173, in run
    self.post_schema_updates()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in wrapper
    ret = method(*args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/migrate.py", line 130, in post_schema_updates
    sync_fixtures()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 24, in sync_fixtures
    import_doc(frappe.get_app_path(app, "fixtures", fname))
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 216, in import_doc
    import_file_by_path(
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 132, in import_file_by_path
    import_doc(
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 237, in import_doc
    doc.insert()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in insert
    self.run_before_save_methods()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 973, in run_before_save_methods
    self.run_method("validate")
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 870, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 1166, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 1149, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 867, in fn
    return method_object(*args, **kwargs)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 45, in validate
    meta = frappe.get_meta(self.dt, cached=False)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/__init__.py", line 969, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/meta.py", line 53, in get_meta
    return load_meta(doctype)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/meta.py", line 56, in load_meta
    return Meta(doctype)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/meta.py", line 97, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/meta.py", line 102, in load_from_db
    super(Meta, self).load_from_db()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/model/document.py", line 147, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/__init__.py", line 448, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/__init__.py", line 427, in msgprint
    _raise_exception()
  File "/home/ejaaz/frappe-bench/apps/frappe/frappe/__init__.py", line 382, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType Member not found
```

**Comment by iamejaaz** [comment]
This issue occurs because of custom fields in the Non-profit Module(I haven't added any 🤔, E.G. `Member-pan_number`, `Donor-pan_number`).
I have exported the custom fields of my Custom app(`bench export-fixtures --app custom_app`) and with them, all the other fields are exported as well.
Although I have installed the non_profit app as well, the error still occurs 🤒 

What should I do now? Is there any solution? Should I remove all the custom fields of the non-profit module from fixture or is this a bug?

**Comment by iashaik** [comment]
How did you resolve this? I'm in the same boat and I am blocked

**Comment by iamejaaz** [comment]
> How did you resolve this? I'm in the same boat and I am blocked

I exported only my custom app fields
![image](https://user-images.githubusercontent.com/67804911/218086403-b219e910-d557-4964-88f1-b5bab156b74b.png)

**Comment by iashaik** [comment]
Thanks, I was doing that already, I don't know what the issue was I created a new Doc and then the error went away. Not really sure what the issue is. 

My issue is happening in Printing - Jinja 2 template, guess I just need to figure out try...catch with Jinja
