### ISSUE TITLE
Patches Error while bench migrating 

### ISSUE THREAD

**Issue by RajatBizMap** [frappe/erpnext#30738]
### Information about bug

 bench migrate
Migrating mfi.com
Exporting Custom DocPerm app mfi_customization filters [['parent', 'not in', ['DocType']]]
Executing frappe.patches.v13_0.jinja_hook in mfi.com (_f88a349f0640e440)
Success: Done in 0.432s
Executing frappe.patches.v13_0.update_notification_channel_if_empty in mfi.com (_f88a349f0640e440)
Success: Done in 5.293s
Executing frappe.patches.v14_0.drop_data_import_legacy in mfi.com (_f88a349f0640e440)
`Data Import Legacy` has been deprecated. The DocType is deleted, but the data still exists on the database. If this data is worth recovering, you may export it using

	bench --site mfi.com backup -i 'Data Import Legacy'

After this, the table will continue to persist in the database, until you choose to remove it yourself. If you want to drop the table, you may run

	bench --site mfi.com execute frappe.db.sql --args "('DROP TABLE IF EXISTS `tabData Import Legacy`', )"

Success: Done in 0.218s
Executing frappe.patches.v14_0.rename_cancelled_documents in mfi.com (_f88a349f0640e440)
Renaming cancelled records of Purchase Receipt doctype
Renaming cancelled records of Purchase Invoice doctype
Renaming cancelled records of Delivery Note doctype
Renaming cancelled records of Sales Order doctype
Renaming cancelled records of Sales Invoice doctype
Renaming cancelled records of Asset Delivery Note doctype
Renaming cancelled records of Stock Entry doctype
Renaming cancelled records of Material Request doctype
Renaming cancelled records of Payment Entry doctype
Renaming cancelled records of Asset doctype
Renaming cancelled records of Asset Movement doctype
Renaming cancelled records of Quality Inspection doctype
Renaming cancelled records of Packing Slip doctype
Success: Done in 47.478s
Executing frappe.patches.v14_0.update_workspace2 # 25.08.2021 in mfi.com (_f88a349f0640e440)
Success: Done in 13.046s
Executing erpnext.patches.v13_0.add_doctype_to_sla #14-06-2021 in mfi.com (_f88a349f0640e440)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rajat/demo_frappe_bench/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/commands/site.py", line 306, in migrate
    migrate(
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/migrate.py", line 65, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
    run_patch(patch)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/rajat/demo_frappe_bench/apps/erpnext/erpnext/patches/v13_0/add_doctype_to_sla.py", line 22, in execute
    agreement.save()
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/model/document.py", line 282, in save
    return self._save(*args, **kwargs)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/model/document.py", line 320, in _save
    self._validate()
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/model/document.py", line 518, in _validate
    self.validate_set_only_once()
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/model/document.py", line 563, in validate_set_only_once
    frappe.throw(_("Value cannot be changed for {0}").format(self.meta.get_label(field.fieldname)),
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/__init__.py", line 440, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/__init__.py", line 419, in msgprint
    _raise_exception()
  File "/home/rajat/demo_frappe_bench/apps/frappe/frappe/__init__.py", line 373, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CannotChangeConstantError: Value cannot be changed for Document Type

### Module

selling

### Version

Frappe version 13
Erpnext Version 13

**Comment by YamanQD** [comment]
Same issue when upgrading to v14

**Comment by ankush** [comment]
duplicate https://github.com/frappe/erpnext/issues/30790
