### ISSUE TITLE
Error while selecting group by Item Groups in Sales Analytics

### ISSUE THREAD

**Issue by ahmederp** [frappe/erpnext#30788]
### Information about bug

Out of nowhere I started getting this error: **TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'**
whenever I select Item Groups in the Group By filter in Sales Analytics. What could have gone wrong?!

Module
selling

Version
ErpNext: 13.27.0
Frappe: 13.26.1

Installation method
easy-install

Relevant log output / Stack trace / Full Error Message.
### App Versions
{
"erpnext": "13.27.0",
"frappe": "13.26.1"
}

### Route
query-report/Sales Analytics

### Trackeback
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 69, in application
response = frappe.api.handle()
File "apps/frappe/frappe/api.py", line 55, in handle
return frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 37, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/init.py", line 1447, in call
return fn(*args, **newargs)
File "apps/frappe/frappe/init.py", line 766, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File "apps/frappe/frappe/desk/query_report.py", line 254, in run
result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
File "apps/frappe/frappe/init.py", line 766, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File "apps/frappe/frappe/desk/query_report.py", line 88, in generate_report_result
res = get_report_result(report, filters) or []
File "apps/frappe/frappe/desk/query_report.py", line 69, in get_report_result
res = report.execute_script_report(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 146, in execute_script_report
res = self.execute_module(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_module
return frappe.get_attr(method_name)(frappe._dict(filters))
File "apps/erpnext/erpnext/selling/report/sales_analytics/sales_analytics.py", line 14, in execute
return Analytics(filters).run()
File "apps/erpnext/erpnext/selling/report/sales_analytics/sales_analytics.py", line 43, in run
self.get_data()
File "apps/erpnext/erpnext/selling/report/sales_analytics/sales_analytics.py", line 109, in get_data
self.get_sales_transactions_based_on_item_group()
File "apps/erpnext/erpnext/selling/report/sales_analytics/sales_analytics.py", line 237, in get_sales_transactions_based_on_item_group
self.get_groups()
File "apps/erpnext/erpnext/selling/report/sales_analytics/sales_analytics.py", line 381, in get_groups
self.depth_map.setdefault(d.name, self.depth_map.get(d.parent) + 1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### Request Data
{
"type": "GET",
"args": {
"report_name": "Sales Analytics",
"filters": "{"tree_type":"Item Group","doc_type":"Sales Invoice","value_quantity":"Value","from_date":"2022-01-01","to_date":"2022-12-31","company":"ASSET For Industrial & Energy Solutions LLC","range":"Monthly"}"
},
"headers": {},
"error_handlers": {},
"url": "/api/method/frappe.desk.query_report.run"
}

### Response Data
{
"exception": "TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'"
}

**Comment by deepeshgarg007** [comment]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/42651287/198511524-46e4629c-d2da-4a14-b17b-f476387a0a9f.png">

Just checked and it worked fine for me without any errors, please reopen if this still persists
