### ISSUE TITLE
Error In installing ERPNext stack in Ubuntu 20.04 : ansible-playbook error

### ISSUE THREAD

**Issue by IHackmer19** [frappe/erpnext#30792]
### Information about bug

I have a fresh VPS installation of Ubuntu 20.04 on [Contabo](contabo.com). Tried Installing Erpnext on Ubuntu more than 3 times and got the same error 👇
![image](https://user-images.githubusercontent.com/96727779/164910369-82b8278d-f4b4-4829-8d10-9771c3e5bc1c.png)

The Log file shows the error of not being able to connect to the database 👇 
![image](https://user-images.githubusercontent.com/96727779/164910441-e27ef013-7711-4384-a026-e51721672ae0.png)

Both types of installation - with and without the verbose tag - gives an error. 
Also tried to add root password to the `\etc\mysql\.my.cnf` file, but still gave an error...

Added the following lines to .my.cnf 👇 
` user=root
password=######
`

### Module

other

### Version

Frappe-13
Erpnext-13

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Traceback (most recent call last):
  File "install.py", line 497, in <module>
    install_bench(args)
  File "install.py", line 278, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 413, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.
```

**Comment by IHackmer19** [comment]
Solved using this guide 👇
https://discuss.erpnext.com/t/tutorial-how-to-manually-install-erpnext-v13-11-production-on-debian-10-w-ssl-cert/81017
