### ISSUE TITLE
Upgrade Failure: sla patch fails (v13.26 -> v14-beta.3) #16728

### ISSUE THREAD

**Issue by this-gavagai** [frappe/erpnext#30790]
### Information about bug

Update fails on patch: v13_0/add_doctype_to_sla.py

From the stack trace below, it seems that there is a write protection of some sort on the Apply On field.

### Module

other

### Version

v14-beta.3 (upgrading from 13.26)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/data/frappe-bench/apps/frappe/frappe/migrate.py", line 171, in run
    self.run_schema_updates()
  File "/data/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in wrapper
    ret = method(*args, **kwargs)
  File "/data/frappe-bench/apps/frappe/frappe/migrate.py", line 112, in run_schema_updates
    frappe.modules.patch_handler.run_all(skip_failing=self.skip_failing, patch_type=PatchType.pre_model_sync)
  File "/data/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 76, in run_all
    run_patch(patch)
  File "/data/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_patch
    if not run_single(patchmodule = patch):
  File "/data/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 145, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/data/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 177, in execute_patch
    _patch()
  File "/data/frappe-bench/apps/erpnext/erpnext/patches/v13_0/add_doctype_to_sla.py", line 21, in execute
    agreement.save()
  File "/data/frappe-bench/apps/frappe/frappe/model/document.py", line 277, in save
    return self._save(*args, **kwargs)
  File "/data/frappe-bench/apps/frappe/frappe/model/document.py", line 314, in _save
    self._validate()
  File "/data/frappe-bench/apps/frappe/frappe/model/document.py", line 516, in _validate
    self.validate_set_only_once()
  File "/data/frappe-bench/apps/frappe/frappe/model/document.py", line 561, in validate_set_only_once
    frappe.throw(
  File "/data/frappe-bench/apps/frappe/frappe/__init__.py", line 448, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/data/frappe-bench/apps/frappe/frappe/__init__.py", line 427, in msgprint
    _raise_exception()
  File "/data/frappe-bench/apps/frappe/frappe/__init__.py", line 382, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CannotChangeConstantError: Value cannot be changed for <strong>Apply On</strong>
```

**Comment by YamanQD** [comment]
Same issue when upgrading to v14

**Comment by aakvatech** [comment]
Same issue with v14
