### ISSUE TITLE
Migration Error: Executing erpnext.patches.v4_4.make_email_accounts

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#3094]
```
revant@revant-laptop:~/frappe-bench$ bench update --upgrade
Already up-to-date.
From https://github.com/frappe/shopping-cart
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
Migrating castlecraft.in
Executing frappe.patches.v5_0.convert_to_barracuda_and_utf8mb4 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'docfield', force=True) #2015-01-01 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.reload_doc('email', 'doctype', 'email_alert') #2014-07-15 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.reload_doc('desk', 'doctype', 'todo') #2014-12-31-1 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.reload_doc('custom', 'doctype', 'property_setter') #2014-12-31-1 in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.v4_to_v5 in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.remove_shopping_cart_app in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.permissions.reset_perms("Module Def") in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.permissions.reset_perms("User") #2015-03-24 in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.rename_table_fieldnames in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.communication_parent in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.clear_website_group_and_notifications in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.db.sql("""update tabComment set comment = substr(comment, 6, locate(":", comment)-6) where comment_type in ("Assigned", "Assignment Completed")""") in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.fix_feed in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.update_shared in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.bookmarks_to_stars in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.style_settings_to_website_theme in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.rename_ref_type_fieldnames in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.fix_email_alert in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.fix_null_date_datetime in castlecraft.in (cpes-frappe)
Success
Executing frappe.patches.v5_0.force_sync_website in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.permissions.reset_perms("GL Entry") #2014-06-09 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.permissions.reset_perms("Stock Ledger Entry") #2014-06-09 in castlecraft.in (cpes-frappe)
Success
Executing execute:frappe.rename_doc("DocType", "Support Ticket", "Issue", force=True) in castlecraft.in (cpes-frappe)
Success
Executing erpnext.patches.v4_4.make_email_accounts in castlecraft.in (cpes-frappe)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands.py", line 202, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/revant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/revant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/revant/frappe-bench/apps/erpnext/erpnext/patches/v4_4/make_email_accounts.py", line 58, in execute
    existing_account.save()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 214, in save
    self.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 186, in insert
    self.db_insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/base_document.py", line 254, in db_insert
    ), d.values())
  File "/home/revant/frappe-bench/apps/frappe/frappe/database.py", line 132, in sql
    self._cursor.execute(query, values)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
frappe.exceptions.NameError: ('Email Account', u'Cs', IntegrityError(1062, "Duplicate entry 'Cs' for key 'PRIMARY'"))
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/revant/bench-repo/bench/cli.py", line 55, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/revant/bench-repo/bench/cli.py", line 247, in update
    patch_sites()
  File "/home/revant/bench-repo/bench/utils.py", line 118, in patch_sites
    run_frappe_cmd('--site', 'all', 'migrate', bench=bench)
  File "/home/revant/bench-repo/bench/utils.py", line 427, in run_frappe_cmd
    subprocess.check_call((f, '-m', 'frappe.utils.bench_helper', 'frappe') + args, cwd=sites_dir)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/home/revant/frappe-bench/env/bin/python', '-m', 'frappe.utils.bench_helper', 'frappe', '--site', 'all', 'migrate')' returned non-zero exit status 1
```
It works when all the email pulling and outgoing settings are deleted and site is migrated.

**Comment by rmehta** [comment]
Fixed via commit 39539f1
