### ISSUE TITLE
Custom field in the GL Entry Doc related to Activity Type giving pymysql.err.OperationalError: 1054

### ISSUE THREAD

**Issue by hameedacpa** [frappe/erpnext#31044]
### App Versions
```
{
	"erpnext": "13.29.2",
	"frappe": "13.29.0"
}
```
### Route
```
Form/Journal Entry/ACC-JV-2022-00129
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 85, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 839, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj, update_outstanding=update_outstanding)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 34, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 201, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 214, in make_entry
    validate_expense_against_budget(args)
  File "apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 157, in validate_expense_against_budget
    budget_records = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'b.activity_type' in 'field list'")

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 37, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 85, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 839, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj, update_outstanding=update_outstanding)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 34, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 201, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 214, in make_entry
    validate_expense_against_budget(args)
  File "apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 157, in validate_expense_against_budget
    budget_records = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'b.activity_type' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-JV-2022-00129\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"idx\":0,\"docstatus\":0,\"title\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"voucher_type\":\"Journal Entry\",\"naming_series\":\"ACC-JV-.YYYY.-\",\"company\":\"Fantasy Flow Technical Works\",\"posting_date\":\"2022-05-14\",\"apply_tds\":0,\"total_debit\":8400,\"total_credit\":8400,\"difference\":0,\"multi_currency\":0,\"total_amount_currency\":\"AED\",\"total_amount\":8400,\"total_amount_in_words\":\"AED Eight Thousand, Four Hundred only.\",\"write_off_based_on\":\"Accounts Receivable\",\"write_off_amount\":0,\"pay_to_recd_from\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"is_opening\":\"No\",\"doctype\":\"Journal Entry\",\"accounts\":[{\"name\":\"39838112d0\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":1,\"docstatus\":0,\"account\":\"21301 - VAT 5% - ST001\",\"account_type\":\"Tax\",\"balance\":-12994.45,\"party_type\":\"\",\"party\":\"\",\"party_balance\":0,\"cost_center\":\"Main - ST001\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":400,\"debit\":400,\"credit_in_account_currency\":0,\"credit\":0,\"is_advance\":\"No\",\"against_account\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"doctype\":\"Journal Entry Account\"},{\"name\":\"31b04ef3db\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":2,\"docstatus\":0,\"account\":\"211101 - Trade Payable - ST001\",\"account_type\":\"Payable\",\"balance\":93125.76,\"party_type\":\"Supplier\",\"party\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"party_balance\":120469.16,\"cost_center\":\"Main - ST001\",\"project\":\"PROJ-0001\",\"activity_type\":\"Painting\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":0,\"debit\":0,\"credit_in_account_currency\":8400,\"credit\":8400,\"is_advance\":\"No\",\"against_account\":\"21301 - VAT 5% - ST001, 51105 - Cost of Short Term Projects - ST001\",\"doctype\":\"Journal Entry Account\"},{\"name\":\"4b2eeef9fd\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":3,\"docstatus\":0,\"account\":\"51105 - Cost of Short Term Projects - ST001\",\"account_type\":\"\",\"balance\":0,\"party_type\":\"\",\"party\":\"\",\"party_balance\":0,\"cost_center\":\"Main - ST001\",\"project\":\"PROJ-0001\",\"activity_type\":\"Painting\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":8000,\"debit\":8000,\"credit_in_account_currency\":0,\"credit\":0,\"is_advance\":\"No\",\"against_account\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"doctype\":\"Journal Entry Account\"}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2022-05-17T04:10:07.157Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery224041891487734527811": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 196,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'b.activity_type' in 'field list'\")"

### Module

accounts

### Version

### App Versions
```
{
	"erpnext": "13.29.2",
	"frappe": "13.29.0"
}
```

### Installation method

_No response_

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.29.2",
	"frappe": "13.29.0"
}
```
### Route
```
Form/Journal Entry/ACC-JV-2022-00129
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 85, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 839, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj, update_outstanding=update_outstanding)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 34, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 201, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 214, in make_entry
    validate_expense_against_budget(args)
  File "apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 157, in validate_expense_against_budget
    budget_records = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'b.activity_type' in 'field list'")

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 37, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1242, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 85, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 839, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj, update_outstanding=update_outstanding)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 34, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 201, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 214, in make_entry
    validate_expense_against_budget(args)
  File "apps/erpnext/erpnext/accounts/doctype/budget/budget.py", line 157, in validate_expense_against_budget
    budget_records = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'b.activity_type' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-JV-2022-00129\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"idx\":0,\"docstatus\":0,\"title\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"voucher_type\":\"Journal Entry\",\"naming_series\":\"ACC-JV-.YYYY.-\",\"company\":\"Fantasy Flow Technical Works\",\"posting_date\":\"2022-05-14\",\"apply_tds\":0,\"total_debit\":8400,\"total_credit\":8400,\"difference\":0,\"multi_currency\":0,\"total_amount_currency\":\"AED\",\"total_amount\":8400,\"total_amount_in_words\":\"AED Eight Thousand, Four Hundred only.\",\"write_off_based_on\":\"Accounts Receivable\",\"write_off_amount\":0,\"pay_to_recd_from\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"is_opening\":\"No\",\"doctype\":\"Journal Entry\",\"accounts\":[{\"name\":\"39838112d0\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":1,\"docstatus\":0,\"account\":\"21301 - VAT 5% - ST001\",\"account_type\":\"Tax\",\"balance\":-12994.45,\"party_type\":\"\",\"party\":\"\",\"party_balance\":0,\"cost_center\":\"Main - ST001\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":400,\"debit\":400,\"credit_in_account_currency\":0,\"credit\":0,\"is_advance\":\"No\",\"against_account\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"doctype\":\"Journal Entry Account\"},{\"name\":\"31b04ef3db\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":2,\"docstatus\":0,\"account\":\"211101 - Trade Payable - ST001\",\"account_type\":\"Payable\",\"balance\":93125.76,\"party_type\":\"Supplier\",\"party\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"party_balance\":120469.16,\"cost_center\":\"Main - ST001\",\"project\":\"PROJ-0001\",\"activity_type\":\"Painting\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":0,\"debit\":0,\"credit_in_account_currency\":8400,\"credit\":8400,\"is_advance\":\"No\",\"against_account\":\"21301 - VAT 5% - ST001, 51105 - Cost of Short Term Projects - ST001\",\"doctype\":\"Journal Entry Account\"},{\"name\":\"4b2eeef9fd\",\"owner\":\"Administrator\",\"creation\":\"2022-05-14 16:06:23.821349\",\"modified\":\"2022-05-14 16:06:23.821349\",\"modified_by\":\"Administrator\",\"parent\":\"ACC-JV-2022-00129\",\"parentfield\":\"accounts\",\"parenttype\":\"Journal Entry\",\"idx\":3,\"docstatus\":0,\"account\":\"51105 - Cost of Short Term Projects - ST001\",\"account_type\":\"\",\"balance\":0,\"party_type\":\"\",\"party\":\"\",\"party_balance\":0,\"cost_center\":\"Main - ST001\",\"project\":\"PROJ-0001\",\"activity_type\":\"Painting\",\"account_currency\":\"AED\",\"exchange_rate\":1,\"debit_in_account_currency\":8000,\"debit\":8000,\"credit_in_account_currency\":0,\"credit\":0,\"is_advance\":\"No\",\"against_account\":\"Ahmed Ibrahim Mohd. Technical Service LLC\",\"doctype\":\"Journal Entry Account\"}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2022-05-17T04:10:07.157Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery224041891487734527811": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 196,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'b.activity_type' in 'field list'\")"
```

**Comment by hameedacpa** [comment]
I'm testing the behavior of this error, Mostly but not confirmed 100% the error coming when selecting any account which is related to PL (Expense or Revenue) core types and assign activity type in the Journal Entry it can not handle the submit action

**Comment by hameedacpa** [comment]
Any update for this issue

**Comment by hameedacpa** [comment]
Please pay attention to this error
