### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#31151]
### Information about bug

On opening address or contact, which extends to opening a customer or supplier

Could be a data issue, other sites working well, despite being on same app versions.

Not sure if it's related to this pr: https://github.com/frappe/frappe/pull/16863

### Module

accounts, buying, selling, CRM

### Version

"erpnext": "13.30.0",
"frappe": "13.29.2"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"csf_ke": "2.1.4",
	"erpnext": "13.30.0",
	"frappe": "13.29.2"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2022-XXXX
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 37, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/email/__init__.py", line 23, in get_contact_list
    match_conditions = build_match_conditions("Contact")
  File "apps/frappe/frappe/desk/reportview.py", line 664, in build_match_conditions
    as_condition=as_condition
  File "apps/frappe/frappe/model/db_query.py", line 711, in build_match_conditions
    doctype_conditions = self.get_permission_query_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 801, in get_permission_query_conditions
    c = frappe.call(frappe.get_attr(method), self.user)
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/contacts/address_and_contact.py", line 100, in get_permission_query_conditions_for_contact
    return get_permission_query_conditions("Contact")
  File "apps/frappe/frappe/contacts/address_and_contact.py", line 108, in get_permission_query_conditions
    links = get_permitted_and_not_permitted_links(doctype)
  File "apps/frappe/frappe/contacts/address_and_contact.py", line 143, in get_permitted_and_not_permitted_links
    allowed_doctypes = frappe.permissions.get_doctypes_with_read()
  File "apps/frappe/frappe/permissions.py", line 366, in get_doctypes_with_read
    set([p.parent if type(p.parent) == str else p.parent.encode("UTF8") for p in get_valid_perms()])
  File "apps/frappe/frappe/permissions.py", line 366, in <listcomp>
    set([p.parent if type(p.parent) == str else p.parent.encode("UTF8") for p in get_valid_perms()])
AttributeError: 'NoneType' object has no attribute 'encode'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": ""
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.email.get_contact_list"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'encode'"
}
```
```

**Comment by sameer-mahendru** [comment]
Any update on this issue?

I am presently unable to open Customer masters due to this error.

**Comment by muchai** [comment]
Interesting. I somewhat know it's somewhat a data issue, since other sites are Ok. But with this similar issue, I wonder if it's a erpnext issue too.

**Comment by sameer-mahendru** [comment]
I recently upgraded from V12 to V13 and was receiving this error but was still able to proceed with opening the doctype. Now I updated to the latest frappe and ERPNext versions and I am unable able to open a customer master. Do you have any workarounds? Do you know how we can escalate this issue, as work is stuck at the moment?

**Comment by muchai** [comment]
It's related to the pr mentioned: https://github.com/frappe/frappe/pull/16863, which is from the latest release.

As for why it's affecting some sites, and not others, not sure yet.

**Comment by sameer-mahendru** [comment]
UPDATE

On my site, a user with limited role and user permissions is able to open an individual customer master, while my user account with full role and user permissions encounters this error.

Not sure of how to make sense of this.

**Comment by muchai** [comment]
@hrwX seems to be related to this pr: https://github.com/frappe/frappe/pull/16863

**Comment by muchai** [comment]
Hi frappe, mind reversing this, in one site, creation, or opening of customers and suppliers is not possible at all.

**Comment by this-gavagai** [comment]
This is likely a frappe issue, so I've replied over there:
https://github.com/frappe/frappe/issues/17030
