### ISSUE TITLE
Unknown column 'enable_provisional_accounting_for_non_stock_items' when upgrade v12 to v13

### ISSUE THREAD

**Issue by nguyenrom** [frappe/erpnext#31192]
### Information about bug

- I'm upgrade ERPNext from v12 to v13 
- I tried to run bench migrate but it not working.

### Module

other

### Version

ERPNext v12 latest

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 47, in run_all
    run_patch(patch)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 105, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/mycompany/frappe-bench/apps/erpnext/erpnext/patches/v13_0/item_reposting_for_incorrect_sl_and_gl.py", line 80, in execute
    update_gl_entries_after(posting_date, posting_time, company=row.name)
  File "/home/mycompany/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 1121, in update_gl_entries_after
    repost_gle_for_stock_vouchers(stock_vouchers, posting_date, company, warehouse_account)
  File "/home/mycompany/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 1148, in repost_gle_for_stock_vouchers
    expected_gle = voucher_obj.get_gl_entries(warehouse_account)
  File "/home/mycompany/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 292, in get_gl_entries
    self.make_item_gl_entries(gl_entries, warehouse_account=warehouse_account)
  File "/home/mycompany/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 308, in make_item_gl_entries
    "Company", self.company, "enable_provisional_accounting_for_non_stock_items"
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/database/database.py", line 469, in get_value
    limit=1,
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/database/database.py", line 540, in get_values
    limit=limit,
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/database/database.py", line 739, in _get_values_from_table
    update=update,
  File "/home/mycompany/frappe-bench/apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mycompany/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'enable_provisional_accounting_for_non_stock_items' in 'field list'")
```

**Comment by nguyenrom** [comment]
I have found solution, login to site database:

```
ALTER TABLE tabCompany
ADD enable_provisional_accounting_for_non_stock_items int(1);
```
