### ISSUE TITLE
Data import not working on develop branch

### ISSUE THREAD

**Issue by nbhatti** [frappe/erpnext#31254]
### Information about bug

When click on Start Import the button disappears and worker.error.log troughs errors 

```04:08:53 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 144, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 109, in start_import
    data_import = frappe.get_doc("Data Import", data_import)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in get_controller
    return _get_controller()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 46, in _get_controller
    from frappe.utils.nestedset import NestedSet
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 20, in <module>
    from frappe.query_builder.terms import SubQuery
ImportError: cannot import name 'SubQuery' from 'frappe.query_builder.terms' (/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/terms.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/worker.py", line 1013, in perform_job
    rv = job.perform()
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/job.py", line 709, in perform
    self._result = self._execute()
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/job.py", line 732, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 168, in execute_job
    frappe.log_error(title=method_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2102, in log_error
    max_size=max_size,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in get_controller
    return _get_controller()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 46, in _get_controller
    from frappe.utils.nestedset import NestedSet
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 20, in <module>
    from frappe.query_builder.terms import SubQuery
ImportError: cannot import name 'SubQuery' from 'frappe.query_builder.terms' (/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/terms.py)
```

### Module

accounts

### Version

erpnext 14.x.x-develop
frappe 14.x.x-develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
04:08:53 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 144, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 109, in start_import
    data_import = frappe.get_doc("Data Import", data_import)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in get_controller
    return _get_controller()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 46, in _get_controller
    from frappe.utils.nestedset import NestedSet
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 20, in <module>
    from frappe.query_builder.terms import SubQuery
ImportError: cannot import name 'SubQuery' from 'frappe.query_builder.terms' (/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/terms.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/worker.py", line 1013, in perform_job
    rv = job.perform()
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/job.py", line 709, in perform
    self._result = self._execute()
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/rq/job.py", line 732, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 168, in execute_job
    frappe.log_error(title=method_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2102, in log_error
    max_size=max_size,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in get_controller
    return _get_controller()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 46, in _get_controller
    from frappe.utils.nestedset import NestedSet
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 20, in <module>
    from frappe.query_builder.terms import SubQuery
ImportError: cannot import name 'SubQuery' from 'frappe.query_builder.terms' (/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/terms.py)
```

**Comment by dj12djdjs** [comment]
I just tested with `Brand` doctype data import. Worked perfectly.

I think it may have been fixed with this: https://github.com/frappe/frappe/pull/17075

@nbhatti Could you pull latest update. It should be working.

**Comment by dj12djdjs** [comment]
I've tested data import with and without child items. I'm not able to replicate this. It seems fixed.. @nbhatti Please advise if you still have this issue after updating. Thanks
