### ISSUE TITLE
Data too long for column 'remarks' at row 1" when importing journ entries

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#31333]
### Information about bug

Eve if the template do not have a remark there is a traceback because the database do not accept the data for the column remark.

[11. Plantilla deducciones 11 2022.xlsx](https://github.com/frappe/erpnext/files/8886217/11.Plantilla.deducciones.11.2022.xlsx)

### Module

accounts

### Version

Installed Apps
ERPNext: v12.30.1 (version-12)

Frappe Framework: v12.27.0 (version-12)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 126, in import_data
    doc = self.process_doc(doc)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 194, in process_doc
    return self.insert_record(doc)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 215, in insert_record
    new_doc.submit()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in submit
    return self._submit()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in _submit
    return self.save()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 939, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 806, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 1085, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 1068, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/document.py", line 803, in fn
    return method_object(*args, **kwargs)
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 53, in on_submit
    self.make_gl_entries()
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 528, in make_gl_entries
    make_gl_entries(gl_map, cancel=cancel, adv_adj=adv_adj)
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 24, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 128, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "/home/erpadmin/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 144, in make_entry
    gle.db_insert()
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/model/base_document.py", line 341, in db_insert
    frappe.db.sql("""INSERT INTO `tab{doctype}` ({columns})
  File "/home/erpadmin/frappe-bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/erpadmin/frappe-bench/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'remarks' at row 1")
```

**Comment by williamjmorenor** [comment]
I really can not find where does the "remark" data come from.

Even BLOB can not handle de data, where I can just set the remark to "None" to get the template up?

**Comment by dj12djdjs** [comment]
@williamjmorenor I believe the `remarks` field is automatically generated when inserting the row.

If you specify a custom remark, it should by-pass this.

**Comment by szufisher** [comment]
per the code from journal_entry.py

	def create_remarks(self):
		r = []

		if self.user_remark:
			r.append(_("Note: {0}").format(self.user_remark))

		if self.cheque_no:
			if self.cheque_date:
				r.append(_("Reference #{0} dated {1}").format(self.cheque_no, formatdate(self.cheque_date)))
			else:
				msgprint(_("Please enter Reference date"), raise_exception=frappe.MandatoryError)

		for d in self.get("accounts"):
			if d.reference_type == "Sales Invoice" and d.credit:
				r.append(
					_("{0} against Sales Invoice {1}").format(
						fmt_money(flt(d.credit), currency=self.company_currency), d.reference_name
					)
				)

			if d.reference_type == "Sales Order" and d.credit:
				r.append(
					_("{0} against Sales Order {1}").format(
						fmt_money(flt(d.credit), currency=self.company_currency), d.reference_name
					)
				)

			if d.reference_type == "Purchase Invoice" and d.debit:
				bill_no = frappe.db.sql(
					"""select bill_no, bill_date
					from `tabPurchase Invoice` where name=%s""",
					d.reference_name,
				)
				if (
					bill_no
					and bill_no[0][0]
					and bill_no[0][0].lower().strip() not in ["na", "not applicable", "none"]
				):
					r.append(
						_("{0} against Bill {1} dated {2}").format(
							fmt_money(flt(d.debit), currency=self.company_currency),
							bill_no[0][0],
							bill_no[0][1] and formatdate(bill_no[0][1].strftime("%Y-%m-%d")),
						)
					)

			if d.reference_type == "Purchase Order" and d.debit:
				r.append(
					_("{0} against Purchase Order {1}").format(
						fmt_money(flt(d.credit), currency=self.company_currency), d.reference_name
					)
				)

		if r:
			self.remark = ("\n").join(r)  # User Remarks is not mandatory

system auto concatenated each sales invoice item in the journal entry detail,  import so many invoice item lines in one journal entry is not possible.

the following 2 possible solutions

1. import the data via open invoice tool instead of the journal entry.
2. create one simple server script on doctype Journal Entry, before save event to override the doc.remark field.
