### ISSUE TITLE
Sendgrid smtp not working

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#31339]
### Information about bug

I’ve set all smtp settings for sendgrid but it doesn’t work. It is showing error "Invalid outgoing mail server or port", so that system is not saving this account.
But when I’m checking “Awaiting password” this checkbox, It is saving account detail. but account is saving as inactive.
But when I’m checking “Enable Incoming” it is saving as active but I am unable to select in from list.

### Module

CRM, integrations

### Version

Installed Apps
ERPNext: v13.28.0
Frappe Framework: v13.28.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
pull_from_email_account

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 134, in execute_job
    method(**kwargs)
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 959, in pull_from_email_account
    email_account.receive()
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 347, in receive
    emails = email_server.get_messages()
  File "apps/frappe/frappe/email/receive.py", line 138, in get_messages
    if not self.connect():
  File "apps/frappe/frappe/email/receive.py", line 75, in connect
    return self.connect_pop()
  File "apps/frappe/frappe/email/receive.py", line 110, in connect_pop
    self.pop.pass_(self.settings.password)
  File "/usr/lib/python3.8/poplib.py", line 216, in pass_
    return self._shortcmd('PASS %s' % pswd)
  File "/usr/lib/python3.8/poplib.py", line 179, in _shortcmd
    return self._getresp()
  File "/usr/lib/python3.8/poplib.py", line 155, in _getresp
    raise error_proto(resp)
poplib.error_proto: b'-ERR [AUTH] Username and password not accepted.'
```

**Comment by dj12djdjs** [comment]
This looks related to: https://discuss.erpnext.com/t/sendgrid-smtp-not-working/90898

**Comment by megha0071994** [comment]
But this also have no solution..

**Comment by nihantra** [comment]
Kindly information purpose, which email server do you use?

**Comment by megha0071994** [comment]
sendgrid service.
