### ISSUE TITLE
Feedback for KB articles is broken

### ISSUE THREAD

**Issue by ZhenWang-Avant** [frappe/erpnext#31338]
### Information about bug

Clicking `Was this article helpful?` on KB articles does not work and shows error in console

### Module

other

### Version

ERPNext: v13.33.0 (version-13)
Frappe Framework: v13.32.1 (version-13)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
website.js:174 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1448, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/website/doctype/help_article/help_article.py", line 120, in add_feedback
    value = cint(frappe.db.get_value("Help Article", article, field))
  File "apps/frappe/frappe/database/database.py", line 459, in get_value
    ret = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 531, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 726, in _get_values_from_table
    r = self.sql(
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'helpful' in 'field list'")
```
```

**Comment by dj12djdjs** [comment]
This is valid, the whitelisted method references columns that don't exist in `help_article.json`: `helpful`, and `not_helpful`
https://github.com/frappe/frappe/blob/6dfbf7b19ea735d45a61c3e3a3e70be540827b60/frappe/website/doctype/help_article/help_article.py#L112-L119

https://github.com/frappe/frappe/blob/develop/frappe/website/doctype/help_article/help_article.json

**Comment by marination** [comment]
Don't know why but the helpful fields were removed via https://github.com/frappe/frappe/pull/10723/commits/02ddaa5ee7c101fb2ca40d6c0ac5982bcc88a982
