### ISSUE TITLE
Error after upgrading to latest version ailed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#31386]
### Information about bug

I upgraded the system normally and when I'm trying to log in to the backend I see this error 

```
Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'
```

The request in inspector shows 

```json
{
  "exc_type": "ValidationError",
  "exception": "frappe.exceptions.ValidationError: Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'",
  "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 72, in execute_cmd\\n    method = get_attr(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 256, in get_attr\\n    method = frappe.get_attr(cmd)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1541, in get_attr\\n    return getattr(get_module(modulename), methodname)\\nAttributeError: module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 69, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 54, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 45, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 74, in execute_cmd\\n    frappe.throw(_(\\\"Failed to get method for command {0} with {1}\\\").format(cmd, e))\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 512, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 487, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 439, in _raise_exception\\n    raise raise_exception(msg)\\nfrappe.exceptions.ValidationError: Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\n\"]",
  "_server_messages": "[\"{\\\"message\\\": \\\"Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1}\"]"
}
```

I would expect everything to work normally. 

### Module

other

### Version

bench --version
`5.11.0`

bench version
```
bench_manager 0.0.1
erpnext 14.x.x-develop
frappe 14.x.x-develop
```

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
{
  "exc_type": "ValidationError",
  "exception": "frappe.exceptions.ValidationError: Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'",
  "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 72, in execute_cmd\\n    method = get_attr(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 256, in get_attr\\n    method = frappe.get_attr(cmd)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1541, in get_attr\\n    return getattr(get_module(modulename), methodname)\\nAttributeError: module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 69, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 54, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 45, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 74, in execute_cmd\\n    frappe.throw(_(\\\"Failed to get method for command {0} with {1}\\\").format(cmd, e))\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 512, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 487, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 439, in _raise_exception\\n    raise raise_exception(msg)\\nfrappe.exceptions.ValidationError: Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\n\"]",
  "_server_messages": "[\"{\\\"message\\\": \\\"Failed to get method for command frappe.desk.desktop.get_wspace_sidebar_items with module 'frappe.desk.desktop' has no attribute 'get_wspace_sidebar_items'\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1}\"]"
}
```

**Comment by ioweb-gr** [comment]
I'd love to provide it but I noticed that today when my user logged out for inactivity I'm getting an internal server error on login page. So I can no longer log in to get the previous error. 

I updated from 13.x-develop

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 17, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 497, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/login.py", line 44, in get_context
    context["logo"] = frappe.get_website_settings("app_logo") or frappe.get_hooks("app_logo_url")[-1]
  File "apps/frappe/frappe/__init__.py", line 2234, in get_website_settings
    return local.website_settings[key]
KeyError: 'app_logo'
```

**Comment by dj12djdjs** [comment]
It seems to me the migration didn't perform successfully. Did you receive any errors during the `bench migrate` process?

**Comment by ioweb-gr** [comment]
That is the confusing part. During bench migrate all patches executed successfully

**Comment by ioweb-gr** [comment]
I've managed to get past the login error by using this patch 

```
Index: apps/frappe/frappe/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/frappe/frappe/__init__.py b/apps/frappe/frappe/__init__.py
--- a/apps/frappe/frappe/__init__.py	
+++ b/apps/frappe/frappe/__init__.py	(date 1655545050427)
@@ -2230,7 +2230,7 @@
 def get_website_settings(key):
 	if not hasattr(local, "website_settings"):
 		local.website_settings = db.get_singles_dict("Website Settings", cast=True)
-	if key in local.website_settings
+	if key in local.website_settings:
 	    return local.website_settings[key]
 
 ```

**Comment by ioweb-gr** [comment]
Could someone point me out where this "app_logo" key is stored in the database so I can update it in the database as well for future updates?
