### ISSUE TITLE
Error: Value missing for Version: DocType

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#31383]
### Information about bug

Hi ,

After the last update, we are encountering this error when trying to Save or Submit any record

```
Error: Value missing for Version: DocType
Error: Value missing for Version: Document Name
```

Please help resolve urgently as this almost completely hinders use of the system

Thanks

### Module

other

### Version

ERPNext: v13.34.0 (version-13)
Frappe Framework: v13.31.0 (version-13)

### Relevant log output / Stack trace / Full Error Message.

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1448, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/query_report.py", line 169, in background_enqueue_run
    track_instance.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1100, in run_post_save_methods
    self.save_version()
  File "apps/frappe/frappe/model/document.py", line 1217, in save_version
    version.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 538, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 891, in _validate_mandatory
    fields=", ".join((each[0] for each in missing)), doctype=self.doctype, name=self.name
frappe.exceptions.MandatoryError: [Version, ded6153b7d]: ref_doctype, docname
```

**Comment by Olawale1** [comment]
This was fixed after a system reboot

Thanks
