### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by Epdecking** [frappe/erpnext#31505]
### Information about bug

Error message when trying to save purchase invoice, it just started this week, never happened in the past.

### Module

buying

### Version

ERPNext: v13.34.2 (HEAD)

Frappe Framework: v13.34.0 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.34.2",
	"frappe": "13.34.0"
}
```
### Route
```
Form/Purchase Invoice/new-purchase-invoice-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 25, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 83, in validate
    super(PurchaseInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 38, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 155, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 302, in set_incoming_rate
    rate = flt(outgoing_rate * d.conversion_factor, d.precision("rate"))
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 25, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 83, in validate
    super(PurchaseInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 38, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 155, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 302, in set_incoming_rate
    rate = flt(outgoing_rate * d.conversion_factor, d.precision("rate"))
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Invoice\",\"name\":\"new-purchase-invoice-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"ep@epdecking.com\",\"naming_series\":\"PINV-22-\",\"company\":\"EP Decking Inc 2021\",\"posting_date\":\"2022-06-30\",\"set_posting_time\":1,\"is_paid\":0,\"is_return\":0,\"apply_tds\":0,\"currency\":\"USD\",\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"USD\",\"ignore_pricing_rule\":0,\"is_subcontracted\":\"No\",\"update_stock\":0,\"apply_discount_on\":\"Grand Total\",\"disable_rounded_total\":0,\"allocate_advances_automatically\":0,\"ignore_default_payment_terms_template\":0,\"letter_head\":\"EP Decking\",\"group_same_items\":0,\"on_hold\":0,\"status\":\"Paid\",\"represents_company\":\"EP Decking Inc 2021\",\"is_internal_supplier\":0,\"party_account_currency\":\"USD\",\"is_opening\":\"No\",\"__run_link_triggers\":false,\"supplier\":\"Central Transport\",\"supplier_name\":\"Central Transport\",\"due_date\":\"2022-06-30\",\"bill_no\":\"150-139223\",\"conversion_rate\":1,\"plc_conversion_rate\":1,\"total_qty\":1,\"base_total\":330,\"base_net_total\":330,\"total_net_weight\":0,\"total\":330,\"net_total\":330,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_grand_total\":330,\"base_in_words\":\"\",\"grand_total\":330,\"in_words\":\"\",\"language\":\"en\",\"credit_to\":\"Creditors - EP\",\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Invoice Item\",\"name\":\"new-purchase-invoice-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"ep@epdecking.com\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"include_exploded_items\":0,\"cost_center\":\"Main - EP\",\"page_break\":0,\"parent\":\"new-purchase-invoice-1\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"idx\":1,\"item_code\":\"\",\"item_name\":\"Trucking Freight Out Charge\",\"description\":\"<div class=\\\"ql-editor read-mode\\\"><p>SINV-22-00605 Factory Flooring.com</p></div>\",\"item_group\":\"\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"uom\":\"Unit\",\"conversion_factor\":0,\"stock_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":330,\"amount\":330,\"base_rate\":330,\"base_amount\":330,\"net_rate\":330,\"net_amount\":330,\"base_net_rate\":330,\"base_net_amount\":330,\"expense_account\":\"5140 - Trucking Freight Out - EP\",\"asset_category\":\"\",\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":\"\",\"creation\":\"\",\"modified_by\":\"ep@epdecking.com\",\"modified\":\"\",\"lft\":null,\"rgt\":null,\"stock_uom_rate\":null,\"valuation_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0}],\"creation\":\"\",\"modified_by\":\"ep@epdecking.com\",\"modified\":\"\",\"lft\":null,\"rgt\":null,\"idx\":null,\"posting_time\":\"09:10:27\",\"supplier_address\":null,\"address_display\":null,\"contact_person\":null,\"rounding_adjustment\":0,\"base_rounding_adjustment\":0,\"rounded_total\":330,\"base_rounded_total\":330,\"total_advance\":0,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"payment_terms_template\":null,\"tax_withholding_category\":null}",
		"action": "Save"
	},
	"btn": {
		"jQuery224031175312470838471": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 2433,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'"
}
```
```

**Comment by ChipwizBen** [comment]
Happening to me too. Here's my output (some entries replaced with "nope" for privacy:

`### App Versions
```
{
	"erpnext": "13.35.0",
	"frappe": "13.35.0"
}
```
### Route
```
Form/Purchase Invoice/PINV-00824
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1007, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 347, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 83, in validate
    super(PurchaseInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 38, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 155, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 302, in set_incoming_rate
    rate = flt(outgoing_rate * d.conversion_factor, d.precision("rate"))
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"PINV-00824\",\"owner\":\"ben@nope.co.nz\",\"creation\":\"2022-06-29 18:07:25.637328\",\"modified\":\"2022-06-29 18:07:25.637328\",\"modified_by\":\"ben@nope.co.nz\",\"idx\":0,\"docstatus\":0,\"title\":\"Caltex\",\"naming_series\":\"PINV-\",\"supplier\":\"Caltex\",\"supplier_name\":\"Caltex\",\"tax_id\":\"73-472-776\",\"due_date\":\"2022-07-29\",\"company\":\"nope Ltd\",\"posting_date\":\"2022-06-29\",\"posting_time\":\"18:07:02\",\"set_posting_time\":1,\"is_paid\":1,\"is_return\":0,\"apply_tds\":0,\"currency\":\"NZD\",\"conversion_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"NZD\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"is_subcontracted\":\"No\",\"update_stock\":0,\"scan_barcode\":\"\",\"total_qty\":1,\"base_total\":205.93,\"base_net_total\":179.07,\"total_net_weight\":0,\"total\":205.93,\"net_total\":179.07,\"tax_category\":\"\",\"taxes_and_charges\":\"New Zealand GST - NOL\",\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">Item</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">GST @ 15.0</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>Fuel</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 179.07\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(15.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 26.86\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"base_taxes_and_charges_added\":26.86,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":26.86,\"taxes_and_charges_added\":26.86,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":26.86,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_grand_total\":205.93,\"base_rounding_adjustment\":0,\"base_rounded_total\":0,\"base_in_words\":\"\",\"grand_total\":205.93,\"rounding_adjustment\":0,\"rounded_total\":0,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":0,\"disable_rounded_total\":1,\"mode_of_payment\":\"Bank Transfer\",\"cash_bank_account\":\"38-nope - Kiwibank - nope - NOL\",\"paid_amount\":205.93,\"base_paid_amount\":205.93,\"write_off_amount\":0,\"base_write_off_amount\":0,\"allocate_advances_automatically\":0,\"payment_terms_template\":\"30 Days\",\"ignore_default_payment_terms_template\":0,\"terms\":\"\",\"letter_head\":\"nope Letter Header and Footer\",\"group_same_items\":0,\"language\":\"en\",\"on_hold\":0,\"status\":\"Paid\",\"is_internal_supplier\":0,\"credit_to\":\"Creditors - NOL\",\"party_account_currency\":\"NZD\",\"is_opening\":\"No\",\"against_expense_account\":\"Travel Expenses - NOL\",\"remarks\":\"No Remarks\",\"per_received\":0,\"doctype\":\"Purchase Invoice\",\"items\":[{\"name\":\"d917ea18d8\",\"owner\":\"ben@nope.co.nz\",\"creation\":\"2022-06-29 18:07:25.637328\",\"modified\":\"2022-06-29 18:07:25.637328\",\"modified_by\":\"ben@nope.co.nz\",\"parent\":\"PINV-00824\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"idx\":1,\"docstatus\":0,\"item_code\":\"\",\"item_name\":\"Fuel\",\"description\":\"\",\"item_group\":\"\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"uom\":\"Unit\",\"conversion_factor\":0,\"stock_uom\":\"Nos\",\"stock_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":205.93,\"amount\":205.93,\"base_rate\":205.93,\"base_amount\":205.93,\"stock_uom_rate\":205.93,\"is_free_item\":0,\"net_rate\":179.07,\"net_amount\":179.06956521739133,\"base_net_rate\":179.07,\"base_net_amount\":179.07,\"valuation_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"expense_account\":\"Travel Expenses - NOL\",\"is_fixed_asset\":0,\"asset_category\":\"\",\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":\"\",\"cost_center\":\"Main - NOL\",\"page_break\":0,\"doctype\":\"Purchase Invoice Item\"}],\"pricing_rules\":[],\"supplied_items\":[],\"taxes\":[{\"name\":\"9fcd8d06e6\",\"owner\":\"ben@nope.co.nz\",\"creation\":\"2022-06-29 18:07:25.637328\",\"modified\":\"2022-06-29 18:07:25.637328\",\"modified_by\":\"ben@nope.co.nz\",\"parent\":\"PINV-00824\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Invoice\",\"idx\":1,\"docstatus\":0,\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":1,\"included_in_paid_amount\":0,\"account_head\":\"GST - NOL\",\"description\":\"GST @ 15.0\",\"rate\":15,\"cost_center\":\"Main - NOL\",\"account_currency\":\"NZD\",\"tax_amount\":26.86,\"tax_amount_after_discount_amount\":26.86,\"total\":205.93,\"base_tax_amount\":26.86,\"base_total\":205.93,\"base_tax_amount_after_discount_amount\":26.86,\"item_wise_tax_detail\":\"{\\\"Fuel\\\":[15,26.86]}\",\"doctype\":\"Purchase Taxes and Charges\"}],\"advances\":[],\"advance_tax\":[],\"payment_schedule\":[{\"name\":\"f0ac70f3ab\",\"owner\":\"ben@nope.co.nz\",\"creation\":\"2022-06-29 18:07:25.637328\",\"modified\":\"2022-06-29 18:07:25.637328\",\"modified_by\":\"ben@nope.co.nz\",\"parent\":\"PINV-00824\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Invoice\",\"idx\":1,\"docstatus\":0,\"payment_term\":\"30 Days\",\"description\":\"Payment must be paid in full by the Due Date. Outstanding balances will be charged an additional 18% per annum, calculated daily.\",\"due_date\":\"2022-07-29\",\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount_date\":\"2022-06-29\",\"discount\":0,\"payment_amount\":205.93,\"outstanding\":205.93,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":205.93,\"doctype\":\"Payment Schedule\"}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\",\"supplier_tds\":null},\"__last_sync_on\":\"2022-07-07T03:39:47.178Z\",\"change_amount\":0,\"base_change_amount\":0}",
		"action": "Submit"
	},
	"btn": {
		"jQuery224095661031963037091": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 244,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'"
}
````

**Comment by ChipwizBen** [comment]
To clarify, no purchase invoices can be saved. It's quite a problematic issue.

**Comment by heterocyclics** [comment]
I have the same issue too. Unable to create Purchase invoices at all. Just to add, I am creating a line item with the Item name and description only, not an existing item.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/31529

**Comment by marination** [comment]
A workaround now is to make sure the UOM is the same as the Stock UOM. Wont matter since it is a non-item purchase.

This is if you cannot update your instance immediately
@Epdecking @ChipwizBen @heterocyclics

**Comment by Epdecking** [comment]
> A workaround now is to make sure the UOM is the same as the Stock UOM. Wont matter since it is a non-item purchase.
> 
> This is if you cannot update your instance immediately @Epdecking @ChipwizBen @heterocyclics

In fact, my UOM is the same as Stock UOM and I have been doing the same thing. All of sudden have error.
