### ISSUE TITLE
frappe.exceptions.ValidationError: A field with the name 'customer_group' already exists in doctype Sales Order.

### ISSUE THREAD

**Issue by Rakeshsivaji65** [frappe/erpnext#31540]
### Information about bug

frappe.exceptions.ValidationError: A field with the name 'customer_group' already exists in doctype Sales Order.  

when i try to restore the db from v12 to v13 and give bench migrate, this issue occurs.

### Module

selling

### Version

v13
v13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Migrating mamba01_v13_dev03
Executing erpnext.patches.v13_0.create_accounting_dimensions_in_orders in mamba01_v13_dev03 (_63c0cd6bf0b2e87f)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 47, in run_all
    run_patch(patch)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 105, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/halosis/mamba/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_accounting_dimensions_in_orders.py", line 36, in execute
    create_custom_field(doctype, df, ignore_validate=True)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 176, in create_custom_field
    custom_field.insert()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 254, in insert
    self.run_method("before_insert")
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 45, in before_insert
    _("A field with the name '{}' already exists in doctype {}.").format(self.fieldname, self.dt)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'territory' already exists in doctype Sales Order.

**Comment by dj12djdjs** [comment]
Can you provide the stack trace?

**Comment by Rakeshsivaji65** [comment]
[https://www.yogile.com/3gu7bdtaehl#21t](url)

@dj12djdjs

**Comment by Rakeshsivaji65** [comment]
@dj12djdjs  any solution?

**Comment by Rakeshsivaji65** [comment]
This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Migrating mamba01_v13_dev03
Executing erpnext.patches.v13_0.create_accounting_dimensions_in_orders in mamba01_v13_dev03 (_63c0cd6bf0b2e87f)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 47, in run_all
    run_patch(patch)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 81, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 105, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/halosis/mamba/frappe-bench/apps/erpnext/erpnext/patches/v13_0/create_accounting_dimensions_in_orders.py", line 36, in execute
    create_custom_field(doctype, df, ignore_validate=True)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 176, in create_custom_field
    custom_field.insert()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 254, in insert
    self.run_method("before_insert")
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 45, in before_insert
    _("A field with the name '{}' already exists in doctype {}.").format(self.fieldname, self.dt)
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/halosis/mamba/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'territory' already exists in doctype Sales Order.

**Comment by dj12djdjs** [comment]
The problem might be related to custom fields. Do you have any custom fields setup for Sales Order?

**Comment by deepeshgarg007** [comment]
@Rakeshsivaji65 This issue should be resolved now, closing this
