### ISSUE TITLE
Change Value Maintain Stock Error

### ISSUE THREAD

**Issue by sengho777** [frappe/erpnext#31557]
### Information about bug

on Edit item then change value Maintain stock
<img width="923" alt="image" src="https://user-images.githubusercontent.com/65536015/177962936-4135874f-7abe-4337-b230-72a1dcaadf8e.png">

### Module

stock

### Version

Version 13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell

### App Versions
```
{
	"email_delivery_service": "0.0.1",
	"erpnext": "14.0.0-dev",
	"erpnext_smb": "0.0.1",
	"frappe": "14.0.0-dev"
}
```
### Route
```
Form/Item/010101
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 288, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 322, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1250, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1232, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 116, in validate
    self.cant_change()
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 907, in cant_change
    if linked_doc := self._get_linked_submitted_documents(changed_fields):
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 961, in _get_linked_submitted_documents
    elif linked_doc := frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 431, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 529, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 771, in _get_values_from_table
    r = self.sql(query, as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/database/database.py", line 191, in sql
    self._cursor.execute(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'parent' in 'field list'")

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1551, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 288, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 322, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1250, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1232, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 116, in validate
    self.cant_change()
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 907, in cant_change
    if linked_doc := self._get_linked_submitted_documents(changed_fields):
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 961, in _get_linked_submitted_documents
    elif linked_doc := frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 431, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 529, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 771, in _get_values_from_table
    r = self.sql(query, as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/database/database.py", line 191, in sql
    self._cursor.execute(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'parent' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"010101\",\"owner\":\"sengho715@gmail.com\",\"creation\":\"2022-07-08 16:24:17.281672\",\"modified\":\"2022-07-08 16:24:17.281672\",\"modified_by\":\"sengho715@gmail.com\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"STO-ITEM-.YYYY.-\",\"item_code\":\"010101\",\"item_name\":\"010101\",\"item_group\":\"Products\",\"stock_uom\":\"Nos\",\"disabled\":0,\"allow_alternative_item\":0,\"is_stock_item\":1,\"has_variants\":0,\"include_item_in_manufacturing\":1,\"opening_stock\":10,\"valuation_rate\":0,\"standard_rate\":1,\"is_fixed_asset\":0,\"auto_create_assets\":0,\"is_grouped_asset\":0,\"over_delivery_receipt_allowance\":0,\"over_billing_allowance\":0,\"description\":\"010101\",\"shelf_life_in_days\":0,\"end_of_life\":\"2099-12-31\",\"default_material_request_type\":\"Purchase\",\"valuation_method\":\"\",\"weight_per_unit\":0,\"allow_negative_stock\":0,\"has_batch_no\":0,\"create_new_batch\":0,\"has_expiry_date\":0,\"retain_sample\":0,\"sample_quantity\":0,\"has_serial_no\":0,\"variant_based_on\":\"Item Attribute\",\"min_order_qty\":0,\"safety_stock\":0,\"is_purchase_item\":1,\"lead_time_days\":0,\"last_purchase_rate\":0,\"is_customer_provided_item\":0,\"delivered_by_supplier\":0,\"enable_deferred_expense\":0,\"no_of_months_exp\":0,\"country_of_origin\":\"Cambodia\",\"grant_commission\":1,\"is_sales_item\":1,\"max_discount\":0,\"enable_deferred_revenue\":0,\"no_of_months\":0,\"inspection_required_before_purchase\":0,\"inspection_required_before_delivery\":0,\"is_sub_contracted_item\":0,\"customer_code\":\"\",\"published_in_website\":0,\"total_projected_qty\":0,\"doctype\":\"Item\",\"taxes\":[],\"customer_items\":[],\"item_defaults\":[{\"name\":\"b68324a6a0\",\"owner\":\"sengho715@gmail.com\",\"creation\":\"2022-07-08 16:24:17.281672\",\"modified\":\"2022-07-08 16:24:17.281672\",\"modified_by\":\"sengho715@gmail.com\",\"docstatus\":0,\"idx\":1,\"company\":\"mysite\",\"default_warehouse\":\"Stores - M\",\"parent\":\"010101\",\"parentfield\":\"item_defaults\",\"parenttype\":\"Item\",\"doctype\":\"Item Default\"}],\"supplier_items\":[],\"reorder_levels\":[],\"attributes\":[],\"barcodes\":[{\"name\":\"4d6b7522c6\",\"owner\":\"sengho715@gmail.com\",\"creation\":\"2022-07-08 16:24:17.281672\",\"modified\":\"2022-07-08 16:24:17.281672\",\"modified_by\":\"sengho715@gmail.com\",\"docstatus\":0,\"idx\":1,\"barcode_type\":\"\",\"uom\":\"Box\",\"parent\":\"010101\",\"parentfield\":\"barcodes\",\"parenttype\":\"Item\",\"doctype\":\"Item Barcode\"}],\"uoms\":[{\"name\":\"2b701bb17a\",\"owner\":\"sengho715@gmail.com\",\"creation\":\"2022-07-08 16:24:17.281672\",\"modified\":\"2022-07-08 16:24:17.281672\",\"modified_by\":\"sengho715@gmail.com\",\"docstatus\":0,\"idx\":1,\"uom\":\"Nos\",\"conversion_factor\":1,\"parent\":\"010101\",\"parentfield\":\"uoms\",\"parenttype\":\"Item\",\"doctype\":\"UOM Conversion Detail\"}],\"__onload\":{\"stock_exists\":0,\"asset_naming_series\":\"ACC-ASS-.YYYY.-\"},\"__last_sync_on\":\"2022-07-08T09:29:51.011Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600351420512143177161": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1075,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'parent' in 'field list'\")"
}
```

```

**Comment by nihantra** [comment]
Hi @sengho777,

As per your requirement, the PR has been raised.
Please check this reference #31560 

Thank You!
