### ISSUE TITLE
Server Error pymysql.err.DataError: (1406, "Data too long for column 'name' at row 1")

### ISSUE THREAD

**Issue by zenicolas** [frappe/erpnext#31592]
### Information about bug

Trying to create a purchase receipt without any link to a purchase order. 

Receive the error in subject. Still investigation but no luck yet. 

Found the below discussion regarding this issue without being able to fix it myself. 

Discussion from Feb seems to have found a resolution although, I wasn't able to replicate the fix. 

from Feb 2020 : https://discuss.erpnext.com/t/bench-update-error-pymysql-err-dataerror-1406-u-data-too-long-for-column-content-at-row-1/58217
from Oct 2020 : https://discuss.erpnext.com/t/cant-import-some-data-via-csv-which-i-can-create-manuall-data-too-long-for-column-name-at-row-1/66970/2
from Jan 2021 : https://discuss.erpnext.com/t/creating-budget-with-long-name-throws-error/70101

### Module

stock

### Version

Installed Apps
Frappe Chat: v0.0.1 (HEAD)
ERPNext: v13.35.2 (HEAD)
Frappe Framework: v13.35.1 (HEAD)
POS Awesome: v3.3.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"erpnext": "13.35.2",
	"frappe": "13.35.1",
	"posawesome": "3.3.0"
}
```
### Route
```
Form/Purchase Receipt/new-purchase-receipt-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 24, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 256, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 464, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 49, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 79, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 115, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 149, in make_autoname
    n = parse_naming_series(parts, doctype, doc)
  File "apps/frappe/frappe/model/naming.py", line 164, in parse_naming_series
    part = getseries(n, digits)
  File "apps/frappe/frappe/model/naming.py", line 217, in getseries
    frappe.db.sql("INSERT INTO `tabSeries` (`name`, `current`) VALUES (%s, 1)", (key,))
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'name' at row 1")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Purchase Receipt\",\"name\":\"new-purchase-receipt-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"nicolas@aplvanille.com\",\"naming_series\":\"PR-.YY..MM.-\",\"company\":\"Aromaz & Flavors\",\"posting_date\":\"2022-07-14\",\"set_posting_time\":0,\"apply_putaway_rule\":0,\"is_return\":0,\"currency\":\"MGA\",\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"USD\",\"ignore_pricing_rule\":0,\"is_subcontracted\":\"No\",\"apply_discount_on\":\"Grand Total\",\"disable_rounded_total\":0,\"status\":\"Draft\",\"is_internal_supplier\":0,\"letter_head\":\"AZF\",\"group_same_items\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Purchase Receipt Item\",\"name\":\"new-purchase-receipt-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"nicolas@aplvanille.com\",\"item_group\":\"Cinnamon\",\"received_qty\":0,\"stock_uom\":\"Kg\",\"retain_sample\":0,\"margin_type\":\"\",\"is_free_item\":0,\"is_fixed_asset\":0,\"allow_zero_valuation_rate\":0,\"include_exploded_items\":0,\"cost_center\":\"Main - AZF\",\"page_break\":0,\"parent\":\"new-purchase-receipt-1\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Receipt\",\"idx\":1,\"qty\":1,\"rejected_qty\":0,\"conversion_factor\":1,\"received_stock_qty\":0,\"stock_qty\":1,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":0,\"amount\":0,\"base_rate\":0,\"base_amount\":0,\"stock_uom_rate\":0,\"net_rate\":0,\"net_amount\":0,\"base_net_rate\":0,\"base_net_amount\":0,\"valuation_rate\":0,\"item_tax_amount\":0,\"rm_supp_cost\":0,\"landed_cost_voucher_amount\":0,\"billed_amt\":0,\"weight_per_unit\":1,\"total_weight\":1,\"brand\":null,\"sample_quantity\":0,\"asset_category\":null,\"item_code\":\"CIN-HNNG-BARK\",\"weight_uom\":\"Kg\",\"item_name\":\"Cinnamon HNNG\",\"description\":\"Cinnamon Bark | Class: Large Pieces | Moist: &lt;12% \\nCinnamomum Verum\\nHS Code : 09.06.20.00 || Origin : Madagascar \\nLot: CIN010 | MG-TMM02 | 0220-11\",\"image\":\"\",\"warehouse\":null,\"income_account\":\"4110 - Sales - AZF\",\"expense_account\":\"5111 - Cost of Goods Sold - AZF\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Kg\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"supplier\":null,\"update_stock\":0,\"delivered_by_supplier\":0,\"last_purchase_rate\":2100,\"transaction_date\":\"2022-07-14\",\"against_blanket_order\":null,\"bom_no\":null,\"grant_commission\":1,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"supplier_part_no\":null,\"has_margin\":false,\"free_item_data\":\"\",\"child_docname\":\"new-purchase-receipt-item-1\"}],\"posting_time\":\"09:57:11\",\"conversion_rate\":1,\"plc_conversion_rate\":4107.655321,\"billing_address\":\"Aromaz & Flavors-Office\",\"shipping_address\":\"APLV-Warehouse\",\"shipping_address_display\":\"Antanandava, RN2<br>Toamasina<br>\\n50100<br>Madagascar<br>\\n\",\"billing_address_display\":\"Lot 494 ME Mandrosoa Ivato<br>Antananarivo<br>\\nMadagascar<br>\\n\",\"base_net_total\":0,\"net_total\":0,\"base_total\":0,\"total\":0,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":0,\"taxes_and_charges_deducted\":0,\"taxes_and_charges_added\":0,\"base_grand_total\":0,\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":0,\"base_rounded_total\":0,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"supplier_name\":\"Sylvana\",\"represents_company\":null,\"supplier\":\"Sylvana\",\"supplier_address\":null,\"address_display\":null,\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"tax_category\":\"\",\"set_warehouse\":\"\",\"total_net_weight\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery224064102367787706631": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1865,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.DataError: (1406, \"Data too long for column 'name' at row 1\")"
}
```
```

**Comment by zenicolas** [comment]
Same issue with Purchase invoice and Purchase receipt

**Comment by zenicolas** [comment]
Same issue with Sales invoice and Purchase order

**Comment by yadavyk** [comment]
Fixed with [17508](https://github.com/frappe/frappe/pull/17508). @zenicolas Can you update and confirm ?

**Comment by zenicolas** [comment]
Thanks you very much guys, works like a charm.
