### ISSUE TITLE
PDF cannot be created (wkhtmltopdf reported an error)

### ISSUE THREAD

**Issue by Altizo** [frappe/erpnext#31611]
### Information about bug

Expected:
After you click the button, a new tab with the pdf file will open

Result:
After clicking the button, a new empty tab opens and nothing happens.

Details:
ERP is served by a third-party proxy server (Nginx Proxy Manager).
I was able to get the log from frappe.log inside the docker container.

### Module

other

### Version

ERPNext: v13.35.0
Frappe Framework: v13.35.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 39, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 132, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
2022-07-17 12:37:30,935 ERROR frappe Could not take error snapshot: characters_written
Site: erp.domain.ru
Form Dict: {'doctype': 'Sales Invoice', 'name': 'ACC-SINV-2022-00546', 'format': 'Standard', 'no_letterhead': '0', 'letterhead': 'Бланк NAME', 'settings': '{}', '_lang': 'ru', 'cmd': 'frappe.utils.print_format.download_pdf', 'style': None, 'doc': <SalesInvoice: ACC-SINV-2022-00546>}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/print_format.py", line 134, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 41, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: TimeoutError
```

**Comment by Perkapz404** [comment]
Run the below command on your terminal.
sudo apt-get install xvfb libfontconfig wkhtmltopdf
Then try to generate PDF.

**Comment by Altizo** [comment]
I tried to do it.
After installing these packages into the container, the dependencies will stretch by about 500 MB.
After installation, the server returns error 500 instead of 502

#### Error 500:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1588, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 129, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.10/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
The switch --print-media-type, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-frappe'
Exit with code 1 due to network error: TimeoutError
	```

**Comment by Altizo** [comment]
Thanks, it solved the problem.
Together with these packages, 500 MB dependencies are installed

**Comment by Altizo** [comment]
Thanks, it solved the problem.
Together with these packages, 500 MB dependencies are installed
