### ISSUE TITLE
Can not confirm appointment

### ISSUE THREAD

**Issue by iMoshi** [frappe/erpnext#31675]
### Information about bug

When a customer creates an appointment booking through the portal and tries to verify his/her email (from the email sent by ERPNext) portal breaks with the following traceback:

### Module

CRM

### Version

Frappe version: v14 Beta 5
ERPNext version: v14 Beta 6

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 17, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 496, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/erpnext/erpnext/www/book_appointment/verify/index.py", line 16, in get_context
    appointment.set_verified(email)
  File "apps/erpnext/erpnext/crm/doctype/appointment/appointment.py", line 94, in set_verified
    self.create_lead_and_link()
  File "apps/erpnext/erpnext/crm/doctype/appointment/appointment.py", line 107, in create_lead_and_link
    lead = frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1165, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 73, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 80, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 114, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 109, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 156, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 208, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 249, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 234, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 262, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment
```

**Comment by sagarvora** [comment]
Similar to https://github.com/frappe/erpnext/issues/31800
