### ISSUE TITLE
Error while loading Patient Appointment doctype 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#31682]
### Information about bug

The following error appears while loading Patient Appointment doctype 

![erro while loading patient appointment doctype](https://user-images.githubusercontent.com/32797974/180442373-1249310e-c395-4627-8c0e-77fcd0304ab0.png)

### Module

other

### Version

V14 Beta2

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev",
	"healthcare": "0.0.1",
	"hrms": "0.0.1"
}
```
### Route
```
List/Patient Appointment/List
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1317, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/healthcare/healthcare/healthcare/doctype/patient_appointment/patient_appointment.py", line 26, in <module>
    from erpnext.hr.doctype.employee.employee import is_holiday
ModuleNotFoundError: No module named 'erpnext.hr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1579, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 73, in getdoctype
    docs = get_meta_bundle(doctype)
  File "apps/frappe/frappe/desk/form/load.py", line 84, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 42, in get_meta
    meta = FormMeta(doctype)
  File "apps/frappe/frappe/desk/form/meta.py", line 56, in __init__
    self.load_assets()
  File "apps/frappe/frappe/desk/form/meta.py", line 70, in load_assets
    self.load_templates()
  File "apps/frappe/frappe/desk/form/meta.py", line 227, in load_templates
    module = load_doctype_module(self.name)
  File "apps/frappe/frappe/modules/utils.py", line 244, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Patient Appointment, the DocType you're trying to open might be deleted.<br> Error: No module named 'erpnext.hr'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Patient Appointment",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
### Response Data
```
{
	"exception": "ImportError: Module import failed for Patient Appointment, the DocType you're trying to open might be deleted.<br> Error: No module named 'erpnext.hr'"
}
```
```

**Comment by ruchamahabal** [comment]
https://github.com/frappe/health/pull/115
