### ISSUE TITLE
Bank Statement Import - Unable to import, throws an error 

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#31688]
### Information about bug

Bank Statement Import - When downloaded the template, edited it, saved it in the correct format, and tried to import then it's throwing an error - "Value for Import Log cannot be a list"

![Screenshot 2022-07-22 at 8 24 59 PM](https://user-images.githubusercontent.com/82337328/180468242-5c2d136d-f54b-4533-a410-218d099af768.png)

### Module

accounts

### Version

ERPNext: v14.0.0-dev (HEAD)
Frappe Framework: v14.0.0-dev (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:438 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1579, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 298, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 335, in _save
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 525, in _validate
    self._validate_length()
  File "apps/frappe/frappe/model/base_document.py", line 884, in _validate_length
    for fieldname, value in self.get_valid_dict(ignore_virtual=True).items():
  File "apps/frappe/frappe/model/base_document.py", line 328, in get_valid_dict
    frappe.throw(_("Value for {0} cannot be a list").format(_(df.label)))
  File "apps/frappe/frappe/__init__.py", line 521, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 489, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 441, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Value for Import Log cannot be a list
```

**Comment by ruthra-kumar** [comment]
fixed on https://github.com/frappe/erpnext/pull/32110.
