### ISSUE TITLE
Invalid or unexpected token prevent accessing ERPNext Desk 

### ISSUE THREAD

**Issue by JingerTea** [frappe/erpnext#31785]
### Information about bug

After upgrading to Frappe-bench V14, ERPNext Desk is stocking at LOGO in production mode. I have looked up others who were also experiencing same issue when they were using Frappe-bench V13 before.

Reference link: https://discuss.erpnext.com/t/erpnext-desk-stuck-at-logo-in-production/81143

```
Uncaught SyntaxError: Invalid or unexpected token
listing.html:2 Uncaught TypeError: Cannot set properties of undefined (setting 'listing')
    at listing.html:2:19
    at kanban_card.html:2:36
address_list.html:2 Uncaught TypeError: Cannot set properties of undefined (setting 'address_list')
    at address_list.html:2:19
    at index.js:107:1
capture.js:14 Uncaught TypeError: Cannot set properties of undefined (setting 'get_data_uri')
    at capture.js:14:10
    at control.js:53:1
report_factory.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'Factory')
    at report_factory.js:4:71
    at report_utils.js:155:1
```
<img width="1175" alt="Screen Shot 2022-08-06 at 3 37 25 AM" src="https://user-images.githubusercontent.com/72108315/183240653-4c89cde4-0eb9-4b80-bb3f-b156cbd106f0.png">

As you can see, the desk doesn’t work when accessed through the set domain https://erp.mydomain.com/ but works fine through http://serverip:8000/app. The previous solution for this is to use stable version of Frappe-bench V13. Since now ERPNext V14 requires Frappe-bench V14, I am limited to V14.0.0 and V14.0.2. I have tried both, they all result the same issue.

### Module

other

### Version

V14.0.2

**Comment by dgehriger** [comment]
I'm experiencing the exact same issue.

**Comment by ankush** [comment]
@JingerTea can you rebuild assets? Can you click on the first error message to see from where the error message is originating?

**Comment by shinzuco** [comment]
@ankush https://a.tmp.ninja/wEGASpBM.js
the file attached is desk.bundle.js

**Comment by ankush** [comment]
@shinzuco 

Some incorrect syntax in built asset files 🤔 

<img width="714" alt="Screenshot 2022-08-09 at 4 16 57 PM" src="https://user-images.githubusercontent.com/9079960/183630317-0d450aea-f01b-492d-90ea-616d2637d423.png">



Can you share node version and esbuild versions? @shinzuco 

`node -v`


Also your exact commit of frappe and yarn.lock will help. Cause at present I am unable to reproduce the problem you're seeing 😅

**Comment by shinzuco** [comment]
> @shinzuco
> 
> Some incorrect syntax in built asset files thinking
> 
> <img alt="Screenshot 2022-08-09 at 4 16 57 PM" width="714" src="https://user-images.githubusercontent.com/9079960/183630317-0d450aea-f01b-492d-90ea-616d2637d423.png">
> 
> Can you share node version and esbuild versions? @shinzuco
> 
> `node -v`
> 
> Also your exact commit of frappe and yarn.lock will help. Cause at present I am unable to reproduce the problem you're seeing sweat_smile

node : v14.19.0
 "esbuild": "^0.14.29",
 
@ankush 

I tried copying the package json from the latest dev and version 14 builds and rebuilding node_modules after deleting it. Did not help.
 
 Tried bumping the editorjs version to 2.24.0(from 2.20.0) did not help
 
 Here are the files you requested. https://a.tmp.ninja/WuMnGJUQ.json
 https://a.tmp.ninja/lyOGwJfi.lock

**Comment by shinzuco** [comment]
@ankush Sometimes when i run bench build with or without force, it works. But as soon as i clear cache(ctrl+shift+r) the same exact error returns.

**Comment by dgehriger** [comment]
Again, very same issue here. Node version is 16.16.0.

**Comment by dgehriger** [comment]
I've managed to work around the issue for now by hand editing _apps/frappe/node_modules/@editorjs/editorjs/dist/editor.js_, and replacing `s=1..toFixed,c=Math.floor` by `s=1..toFixed()`, and then rebuilding bench.

**Comment by shinzuco** [comment]
@dgehriger rebuilding via bench/yarn seems to temporarily load the desk, but using ctrl+shift+r presents the same error

I am using cloudflare, disabled caching and all js optimisations, and now the issue is gone (both this and editing editor.js had to be done)

**Comment by dgehriger** [comment]
@shinzuco : I'm also using Cloudflare. Let me disable it for this site to see if it helps.
