### ISSUE TITLE
DROPbox Integration : Access Token Error 

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#31829]
### Information about bug

When setting up dropbox backup integration in ERPNExt , all steps are followed , however a "access token is required". I can generate one in dropbox its self , however in erpnext there is no field on the front end to popluate the access token:

> Backup Upload Failed!
> 
> Oops, your automated backup to Dropbox failed.
> 
> Error message: No Access Token exists! Please generate the access token for Dropbox. Traceback (most recent call last): File "apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 78, in take_backup_to_dropbox raise Exception Exception
> 

Looking at the doctype "dropbox settings" I can see three extra fields which are hidden , one of them is the access token , is there reason why these are hidden and if the app or integration requires an access token then why have it hidden.

### Module

integrations

### Version

ERPNext: v13.36.1 (version-13)

Frappe Framework: v13.36.3 (version-13)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
@tjomtek The only reason those fields would be hidden is if they are already set in the site_config.json

If they exist in the site_config.json, you can ether modify the keys there. Or remove them from site_config.json and set them in the dropbox settings form.

For example:
```json
{
"dropbox_access_key": "ACCESSKEY",
"dropbox_secret_key": "SECRECTKEY"
}
```

**Comment by tjomtek** [comment]
Thanks dj12djdjs
After trying a couple of methods i get the follow error on trace back :

Traceback (most recent call last):
  File "/home/erpnxtadmin/frappe-bench/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/erpnxtadmin/frappe-bench/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/erpnxtadmin/frappe-bench/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/erpnxtadmin/frappe-bench/env/lib/python3.7/site-packages/urllib3/connection.py", line 464, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/home/erpnxtadmin/frappe-bench/env/lib/python3.7/site-packages/urllib3/connection.py", line 512, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.7/ssl.py", line 338, in match_hostname
    % (hostname, dnsnames[0]))
ssl.SSLCertVerificationError: ("hostname 'dropbox.erpnext.com' doesn't match 'bi.frappe.io'",)

Bearing in mind this is a self-host...
The system does create the folders(apps/{myappname}in dropbox which is a good sign , however fails to deliver the file to dropbox.

**Comment by dj12djdjs** [comment]
@tjomtek During what process does this error occur? I don't see any reference to frappe dropbox integration in this traceback.

**Comment by tjomtek** [comment]
@dj12djdjs , when I click on "take back now" under the Dropbox Setting.
