### ISSUE TITLE
Discount Accounting unable to submit multi-currency invoice

### ISSUE THREAD

**Issue by lvr26** [frappe/erpnext#31844]
### Information about bug

I am unable to submit multi-currency invoices that has Additional discount on Grand Total. Company currency is in IDR, while my supplier currency is in USD.
I had set up:
- Supplier currency: USD
- Payable account currency: USD
- Discount account: USD

All I did, I create purchase order with discount. then I received the order. Then I create purchase invoice which only at this phase, discount account is required to be filled. After that I can't submit it. It always says "Debit and Credit is not equal...".
If I allocate the discount to each of the items, the invoice can be submitted. Yet I needed it to be able to be submitted with discount on the total invoice. If it is in the company currency, the system have no issue with it and the invoice can be submitted. Seems like the issue only happens when the "update stock" is checked or when the invoice is in other currency (not the same as company's currency). Is there any workaround for this issue or maybe I did something wrong. Please assist. Thank you.

![image](https://user-images.githubusercontent.com/89437369/184494129-a60777dc-246a-4bf3-8f7e-991e45ad50b0.png)

### Module

buying

### Version

Frappe version - 13.34.0
ERPNext version - 13.34.2

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1214, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 939, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 928, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 341, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1007, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 863, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 431, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 450, in make_gl_entries
    make_gl_entries(gl_entries, update_outstanding=update_outstanding, merge_entries=False, from_repost=from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 25, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 152, in save_entries
    round_off_debit_credit(gl_map)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 206, in round_off_debit_credit
    .format(gl_map[0].voucher_type, gl_map[0].voucher_no, debit_credit_diff))
  File "apps/frappe/frappe/__init__.py", line 445, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 424, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 378, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Debit and Credit not equal for Purchase Invoice #ACC-PINV-2022-00017. Difference is 224985.0.
```

**Comment by deepeshgarg007** [comment]
@lvr26 We have removed discount accounting from Purchase Cycle in the latest version-13 release so this issue is not valid anymore. Closing this issue

**Comment by lvr26** [comment]
Maybe you can help enlighten me as to how then to apply discount in purchase invoice?

**Comment by lvr26** [comment]
thanks all. issue solved
