### ISSUE TITLE
Whatsapp Notification Error

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#31872]
### Information about bug

I have integrated twilio for using whatsapp notification and I'm getting this error. What I'm doing wrong. Please help me.
Thank you..

### Module

integrations, other

### Version

ERPNext: v13.28.0

Frappe Framework: v13.28.0

Twilio Integration: v0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/email/doctype/notification/notification.py", line 147, in send
    self.create_system_notification(doc, context)
  File "apps/frappe/frappe/email/doctype/notification/notification.py", line 178, in create_system_notification
    if "{" in subject:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by megha0071994** [comment]
Now I'm getting this error.

HTTP 400 error: Unable to create record: The 'From' number whatsapp:+12056064440 is not a valid phone number, shortcode, or alphanumeric sender ID.
