### ISSUE TITLE
installing v13 manual

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#31885]
### Information about bug

**Installing v13 , with python 3.8.10**

bench get-app branch version-13 erpnext https://github.com/frappe/erpnext
Getting erpnext
$ git clone https://github.com/frappe/erpnext  --depth 1 --origin upstream
Cloning into 'erpnext'...
remote: Enumerating objects: 4867, done.
remote: Counting objects: 100% (4867/4867), done.
remote: Compressing objects: 100% (4121/4121), done.
remote: Total 4867 (delta 969), reused 2277 (delta 516), pack-reused 0
Receiving objects: 100% (4867/4867), 17.13 MiB | 7.44 MiB/s, done.
Resolving deltas: 100% (969/969), done.
Ignoring dependencies of https://github.com/frappe/erpnext. To install dependencies use --resolve-deps
Installing erpnext
$ /home/bench/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/bench/frappe-bench/apps/erpnext 
ERROR: Package 'erpnext' requires a different Python: 3.8.10 not in '>=3.10'
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 432, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 230, in install
    install_app(
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 561, in install_app
    bench.run(
  File "/usr/local/lib/python3.8/dist-packages/bench/bench.py", line 47, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/__init__.py", line 155, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
erpnxtadmin@vps-366ed503:/home/bench/frappe-bench$ python3 --version
Python 3.8.10

### Module

other

### Version

v13

### Installation method

manual install

**Comment by Solufyin** [comment]
Hi @tjomtek,

```
git clone https://github.com/frappe/bench bench-repo
sudo pip3 install -e bench-repo
sudo pip3 install frappe-bench
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
sudo apt install python3.10
sudo apt install python3.10-dev
bench init frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13
```

Please apply one by one command and check it.
Maybe it helps you.

Thank You!

**Comment by tjomtek** [comment]
Thanks Solufyin , this helped, appreciated :)
