### ISSUE TITLE
Migration Error: erpnext.accounts.doctype.cost_center_allocation.cost_center_allocation.WrongPercentageAllocation: Total percentage against cost centers should be 100

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#32029]
### Information about bug

Error during migration of a site used to create demo companies and records. Error happens during migration

### Module

accounts

### Version

```json
{
  "frappe": {
    "title": "Frappe Framework",
    "description": "Full stack web framework with Python, Javascript, MariaDB, Redis, Node",
    "branch": "",
    "version": "14.4.3"
  },
  "erpnext": {
    "title": "ERPNext",
    "description": "ERP made simple",
    "branch": "",
    "version": "14.0.2"
  },
  "india_compliance": {
    "title": "India Compliance",
    "description": "ERPNext app to simplify compliance with Indian Rules and Regulations",
    "branch": "",
    "version": "0.0.1"
  },
  "payments": {
    "title": "Payments",
    "description": "Payments app for frappe",
    "branch": "",
    "version": "0.0.1"
  }
}
```

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
frappe@erpnext-v14-gunicorn-576d8889d5-tg2r9:~/frappe-bench/sites$ bench --site site.localhost migrate
Migrating site.localhost
/home/frappe/frappe-bench/apps/frappe/frappe/database/query.py:197: UserWarning: The 'filters_config' hook used to add custom operators is not yet implemented in frappe.db.query engine. Use db_query (frappe.get_list) instead.
  warn(
Updating DocTypes for frappe        : [========================================] 100%
Updating DocTypes for erpnext       : [========================================] 100%
Updating DocTypes for payments      : [========================================] 100%
Updating DocTypes for india_compliance: [========================================] 100%
Executing erpnext.patches.v14_0.migrate_cost_center_allocations in site.localhost (_61cea756fa86cccf)
Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for payments
Updating Dashboard for india_compliance
Updating customizations for Address
Updating customizations for Contact
Building search index for site.localhost
Retrieving Routes                   : [========================================] 100%
Building Index                      : [========================================] 100%
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 523, in migrate
    SiteMigration(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 172, in run
    self.run_schema_updates()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in wrapper
    ret = method(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 113, in run_schema_updates
    frappe.modules.patch_handler.run_all(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 75, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 62, in run_patch
    if not run_single(patchmodule=patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 150, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 185, in execute_patch
    _patch()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v14_0/migrate_cost_center_allocations.py", line 11, in execute
    create_new_cost_center_allocation_records(cc_allocations)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v14_0/migrate_cost_center_allocations.py", line 24, in create_new_cost_center_allocation_records
    cca.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 301, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 323, in _save
    return self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 255, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 928, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1268, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1250, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 925, in fn
    return method_object(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/cost_center_allocation/cost_center_allocation.py", line 32, in validate
    self.validate_total_allocation_percentage()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/cost_center_allocation/cost_center_allocation.py", line 42, in validate_total_allocation_percentage
    frappe.throw(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 524, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 492, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 444, in _raise_exception
    raise raise_exception(msg)
erpnext.accounts.doctype.cost_center_allocation.cost_center_allocation.WrongPercentageAllocation: Total percentage against cost centers should be 100
```

**Comment by dj12djdjs** [comment]
@revant I wasn't able to replicate this from a blank installation of version-13 -> version-14.

Could you supply the cost center data prior to version-14 migration?
