### ISSUE TITLE
Subcontracting Receipt "set_missing_values_in_additional_costs"

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#32039]
### Information about bug

Subcontrating Receipt can't not be saved

![Captura de Pantalla 2022-08-31 a la(s) 9 26 18](https://user-images.githubusercontent.com/25084259/187703212-4cea2d09-9358-49b6-be85-1c526a1ec9e5.png)
![Captura de Pantalla 2022-08-31 a la(s) 9 26 39](https://user-images.githubusercontent.com/25084259/187703219-28822c12-e612-4a5b-8fe8-c94b45d0eb7f.png)

### Module

buying, manufacturing

### Version

ERPNext: v14.0.0 (version-14)
Frappe Framework: v14.0.2 (version-14)
Payments: v0.0.1 (develop)

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.0.0",
	"frappe": "14.0.2",
	"payments": "0.0.1"
}
```
### Route
```
Form/Subcontracting Receipt/new-subcontracting-receipt-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1588, in call
    methodname = method_string.split(".")[-1]
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 300, in save
    """Wrapper for _save"""
  File "apps/frappe/frappe/model/document.py", line 322, in _save
    if self.get("__islocal") or not self.get("name"):
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.flags.in_insert = True
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    if self._action == "save":
  File "apps/frappe/frappe/model/document.py", line 927, in run_method
    fn.__name__ = str(method)
  File "apps/frappe/frappe/model/document.py", line 1267, in composer
    composed = compose(f, *hooks)
  File "apps/frappe/frappe/model/document.py", line 1249, in runner
    def runner(self, method, *args, **kwargs):
  File "apps/frappe/frappe/model/document.py", line 924, in fn
    if method in self.__dict__ or callable(method_object):
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 63, in validate
    self.set_missing_values()
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 106, in set_missing_values
    self.set_missing_values_in_additional_costs()
AttributeError: 'SubcontractingReceipt' object has no attribute 'set_missing_values_in_additional_costs'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"xxxxxxxxxxxx\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-SCR-.YYYY.-\",\"supplier\":\"Proveedor B\",\"supplier_name\":\"Proveedor B\",\"company\":\"XXXXXX\",\"posting_date\":\"2022-08-31\",\"posting_time\":\"09:16:36.678547\",\"set_posting_time\":0,\"is_return\":0,\"supplier_address\":\"Proveedor B-Facturación\",\"contact_person\":\"SEÑOR APELLIDO-Proveedor B\",\"address_display\":\"CALLE, COLONIA, EDO. DE MÉXICO, México\",\"contact_display\":\"SEÑOR APELLIDO\",\"shipping_address\":\"XXXXX\",\"shipping_address_display\":\"XXXXXXXXXXX\",\"set_warehouse\":\"Almacén General - CA\",\"supplier_warehouse\":\"Maquila - CA\",\"total_qty\":1,\"total\":35,\"distribute_additional_costs_based_on\":\"\",\"total_additional_costs\":0,\"status\":\"Draft\",\"per_returned\":0,\"letter_head\":\"XXXXXXX\",\"doctype\":\"Subcontracting Receipt\",\"additional_costs\":[],\"items\":[{\"owner\":\"xxxxxxxxxx\",\"docstatus\":0,\"idx\":1,\"item_code\":\"XMCLG22PPMRAF-LG\",\"item_name\":\"CAMISA MANGA LARGA OGGI, POPELINA MIL RAYAS AZUL FUERTE-BLANCO, T-LG\",\"description\":\"CAMISA MANGA LARGA OGGI, POPELINA MIL RAYAS AZUL FUERTE-BLANCO, T <div>Talla Caballero Alfa: LG</div>\",\"brand\":\"OGGI\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"returned_qty\":0,\"stock_uom\":\"Pza\",\"conversion_factor\":1,\"rate\":35,\"amount\":35,\"recalculate_rate\":1,\"rm_cost_per_qty\":0,\"service_cost_per_qty\":35,\"additional_cost_per_qty\":0,\"rm_supp_cost\":0,\"warehouse\":\"Almacén General - CA\",\"subcontracting_order\":\"SC-ORD-2022-00002\",\"schedule_date\":\"2022-08-30\",\"subcontracting_order_item\":\"c5c96b5394\",\"bom\":\"BOM-XMCLG22PPMRAF-LG-001\",\"cost_center\":\"Principal - CA\",\"page_break\":0,\"parentfield\":\"items\",\"parenttype\":\"Subcontracting Receipt\",\"doctype\":\"Subcontracting Receipt Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-subcontracting-receipt-1\",\"name\":\"new-subcontracting-receipt-item-1\"}],\"supplied_items\":[],\"__islocal\":1,\"__onload\":{\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-subcontracting-receipt-1\",\"__last_sync_on\":\"2022-08-31T14:16:36.795Z\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360036116125446598591": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 723,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'SubcontractingReceipt' object has no attribute 'set_missing_values_in_additional_costs'"
}
```
```

**Comment by s-aga-r** [comment]
@franciscobuendiao are you still getting this error? Closing this for now reopen it if it's not resolved after the update.
