### ISSUE TITLE
No permission to read DocType

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#32034]
### Information about bug

a pop up message of No permission to read DocType is constantly appearing. We just wanted to give the accounts manager role an access to view and navigate the Bank Clearance Summary.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/60758795/187585664-f26bd39f-a515-4830-b84c-4b38cdc5a7f4.png">
 

### Module

accounts

### Version

ERPNext: v13.36.5 (HEAD)
Frappe Framework: v13.39.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 256, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 117, in generate_report_result
    result = get_filtered_data(report.ref_doctype, columns, result, user)
  File "apps/frappe/frappe/desk/query_report.py", line 583, in get_filtered_data
    match_filters_per_doctype = get_user_match_filters(linked_doctypes, user=user)
  File "apps/frappe/frappe/desk/query_report.py", line 766, in get_user_match_filters
    filter_list = frappe.desk.reportview.build_match_conditions(dt, user, False)
  File "apps/frappe/frappe/desk/reportview.py", line 664, in build_match_conditions
    as_condition=as_condition
  File "apps/frappe/frappe/model/db_query.py", line 692, in build_match_conditions
    frappe.throw(_("No permission to read {0}").format(_(self.doctype)), frappe.PermissionError)
  File "apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: No permission to read Doctype
```

**Comment by dj12djdjs** [comment]
This should be "DocType"

https://github.com/frappe/erpnext/blob/11b04acf8ba522e330ce06d964cbf4a71757b453/erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py#L26
