### ISSUE TITLE
TypeError: 'str' object does not support item assignment opening old leads and opportunities

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32051]
### Information about bug

Pops up when 

### Module

CRM

### Version

ERPNext: v14.0.0-dev (HEAD)
Frappe Framework: v14.0.0-dev (HEAD)
HRMS: v0.0.1 (HEAD)
Frappe Insights: v0.1.0-beta (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
GET https://site.site/api/method/frappe.desk.form.load.getdoc?doctype=Lead&name=CRM-LEAD-2019-00060&_=1662054937283 500
send @ jquery.js:10109
ajax @ jquery.js:9690
frappe.request.call @ request.js:273
frappe.call @ request.js:105
(anonymous) @ model.js:248
with_doc @ model.js:238
fetch_and_render @ formview.js:90
show_doc @ formview.js:85
make @ formview.js:18
show @ factory.js:25
render_page @ router.js:242
render @ router.js:221
route @ router.js:131
push_state @ router.js:397
Promise.finally.frappe.route_flags @ router.js:290
set_route @ router.js:284
frappe.set_route @ router.js:468
t @ router.js:37
(anonymous) @ router.js:73
dispatch @ jquery.js:5430
c1.handle @ jquery.js:5234
request.js:462 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1597, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 37, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "apps/frappe/frappe/__init__.py", line 1188, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 73, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 80, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 105, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 151, in load_from_db
    super().__init__(d)
  File "apps/frappe/frappe/model/base_document.py", line 109, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 156, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 208, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 249, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 234, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 262, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment
```

**Comment by sagarvora** [comment]
@muchai This issue is happening because you have a column for one of the child tables in the parent doctype ( **Lead / Opportunity** )

Since https://github.com/frappe/frappe/pull/16540, `doc.extend` accepts all iterable values, not just `list`. I think in your case, the column in the parent doctype has a string value, hence the issue.
