### ISSUE TITLE
AttributeError: 'ReceivablePayableReport' object has no attribute 'customer'

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32160]
### Information about bug

This happens when one selects the territory filter on the report.
Also, the territory column on the report, shows territory as per the data in the customer doctype not as captured on the sales invoice.

### Module

accounts

### Version

ERPNext: v14.1.0 (HEAD)
Frappe Framework: v14.6.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:462 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1599, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 783, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 253, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 783, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 40, in execute
    return ReceivablePayableReport(filters).run(args)
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 62, in run
    self.get_data()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 85, in get_data
    self.get_ple_entries()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 669, in get_ple_entries
    self.prepare_conditions()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 741, in prepare_conditions
    self.add_customer_filters()
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 793, in add_customer_filters
    self.get_hierarchical_filters("Territory", "territory")
  File "apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 838, in get_hierarchical_filters
    customer = self.customer
AttributeError: 'ReceivablePayableReport' object has no attribute 'customer'
```

**Comment by ruthra-kumar** [comment]
Fixed on #32175
