### ISSUE TITLE
Pos Closing Not Working

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#32182]
### Information about bug

While doing a POS closing entry. Found the below mentioned error.

### App Versions
```
{
"erpnext": "14.0.3",
"frappe": "14.5.0",
"payments": "0.0.1"
}
```
### Route
```
Form/POS Closing Entry/new-pos-closing-entry-1
```
### Trackeback
```
Syntax error in query:
SELECT SUM(`stock_value_difference`) `batch_value`,SUM(`actual_qty`) `batch_qty` FROM `tabStock Ledger Entry` WHERE `item_code`=%(param1)s AND `warehouse`=%(param2)s AND `batch_no`=%(param3)s AND `is_cancelled`=0 AND TIMESTAMP(`posting_date`,`posting_time`)<TIMESTAMP('2022-09-05',16:21:01) {'param1': 'AM0001', 'param2': 'Kullanchavadi - A', 'param3': 'AM-TLT-####'}
Traceback (most recent call last):
 File "apps/frappe/frappe/app.py", line 69, in application
  response = frappe.api.handle()
 File "apps/frappe/frappe/api.py", line 54, in handle
  return frappe.handler.handle()
 File "apps/frappe/frappe/handler.py", line 45, in handle
  data = execute_cmd(cmd)
 File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
  return frappe.call(method, **frappe.form_dict)
 File "apps/frappe/frappe/__init__.py", line 1599, in call
  return fn(*args, **newargs)
 File "apps/frappe/frappe/desk/form/save.py", line 20, in savedocs
  doc.submit()
 File "apps/frappe/frappe/model/document.py", line 1015, in submit
  return self._submit()
 File "apps/frappe/frappe/model/document.py", line 994, in _submit
  return self.save()
 File "apps/frappe/frappe/model/document.py", line 301, in save
  return self._save(*args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 352, in _save
  self.run_post_save_methods()
 File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
  self.run_method("on_submit")
 File "apps/frappe/frappe/model/document.py", line 928, in run_method
  out = Document.hook(fn)(self, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1268, in composer
  return composed(self, method, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1250, in runner
  add_to_return_value(self, fn(self, *args, **kwargs))
 File "apps/frappe/frappe/model/document.py", line 925, in fn
  return method_object(*args, **kwargs)
 File "apps/erpnext/erpnext/accounts/doctype/pos_closing_entry/pos_closing_entry.py", line 77, in on_submit
  consolidate_pos_invoices(closing_entry=self)
 File "apps/erpnext/erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py", line 330, in consolidate_pos_invoices
  create_merge_logs(invoice_by_customer, closing_entry)
 File "apps/erpnext/erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py", line 415, in create_merge_logs
  merge_log.submit()
 File "apps/frappe/frappe/model/document.py", line 1015, in submit
  return self._submit()
 File "apps/frappe/frappe/model/document.py", line 994, in _submit
  return self.save()
 File "apps/frappe/frappe/model/document.py", line 301, in save
  return self._save(*args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 352, in _save
  self.run_post_save_methods()
 File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
  self.run_method("on_submit")
 File "apps/frappe/frappe/model/document.py", line 928, in run_method
  out = Document.hook(fn)(self, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1268, in composer
  return composed(self, method, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1250, in runner
  add_to_return_value(self, fn(self, *args, **kwargs))
 File "apps/frappe/frappe/model/document.py", line 925, in fn
  return method_object(*args, **kwargs)
 File "apps/erpnext/erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py", line 80, in on_submit
  sales_invoice = self.process_merging_into_sales_invoice(sales)
 File "apps/erpnext/erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py", line 103, in process_merging_into_sales_invoice
  sales_invoice.save()
 File "apps/frappe/frappe/model/document.py", line 301, in save
  return self._save(*args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 323, in _save
  return self.insert()
 File "apps/frappe/frappe/model/document.py", line 255, in insert
  self.run_before_save_methods()
 File "apps/frappe/frappe/model/document.py", line 1056, in run_before_save_methods
  self.run_method("validate")
 File "apps/frappe/frappe/model/document.py", line 928, in run_method
  out = Document.hook(fn)(self, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1268, in composer
  return composed(self, method, *args, **kwargs)
 File "apps/frappe/frappe/model/document.py", line 1250, in runner
  add_to_return_value(self, fn(self, *args, **kwargs))
 File "apps/frappe/frappe/model/document.py", line 925, in fn
  return method_object(*args, **kwargs)
 File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 94, in validate
  super(SalesInvoice, self).validate()
 File "apps/erpnext/erpnext/controllers/selling_controller.py", line 32, in validate
  super(SellingController, self).validate()
 File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
  super(StockController, self).validate()
 File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 154, in validate
  self.set_incoming_rate()
 File "apps/erpnext/erpnext/controllers/selling_controller.py", line 423, in set_incoming_rate
  d.incoming_rate = get_incoming_rate(
 File "apps/erpnext/erpnext/stock/utils.py", line 278, in get_incoming_rate
  in_rate = get_batch_incoming_rate(
 File "apps/erpnext/erpnext/stock/stock_ledger.py", line 1182, in get_batch_incoming_rate
  batch_details = (
 File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
  return frappe.db.sql(query, params, *args, **kwargs) # nosemgrep
 File "apps/frappe/frappe/database/database.py", line 209, in sql
  self._cursor.execute(query, values)
 File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
  result = self._query(query)
 File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
  conn.query(q)
 File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
  self._affected_rows = self._read_query_result(unbuffered=unbuffered)
 File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
  result.read()
 File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
  first_packet = self.connection._read_packet()
 File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
  packet.raise_for_error()
 File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
  err.raise_mysql_exception(self._data)
 File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
  raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':21:01)' at line 1")

```
### Request Data
```
{
"type": "POST",
"args": {
 "doc": "{\"name\":\"POS-CLO-2022-00001\",\"owner\":\"Administrator\",\"creation\":\"2022-09-05 16:21:30.234709\",\"modified\":\"2022-09-05 16:21:30.234709\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"period_start_date\":\"2022-09-05 14:20:27.492531\",\"period_end_date\":\"2022-09-05 16:20:54\",\"posting_date\":\"2022-09-05\",\"posting_time\":\"16:21:01\",\"pos_opening_entry\":\"POS-OPE-2022-00001\",\"status\":\"Draft\",\"company\":\"Agrifi\",\"pos_profile\":\"Kullanchavadi\",\"user\":\"Administrator\",\"grand_total\":410,\"net_total\":410,\"total_quantity\":2,\"error_message\":null,\"amended_from\":null,\"doctype\":\"POS Closing Entry\",\"payment_reconciliation\":[{\"name\":\"1932382d88\",\"owner\":\"Administrator\",\"creation\":\"2022-09-05 16:21:30.234709\",\"modified\":\"2022-09-05 16:21:30.234709\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"mode_of_payment\":\"Cash\",\"opening_amount\":0,\"expected_amount\":410,\"closing_amount\":0,\"difference\":-410,\"parent\":\"POS-CLO-2022-00001\",\"parentfield\":\"payment_reconciliation\",\"parenttype\":\"POS Closing Entry\",\"doctype\":\"POS Closing Entry Detail\",\"__unsaved\":1},{\"name\":\"d7212ab1ce\",\"owner\":\"Administrator\",\"creation\":\"2022-09-05 16:21:30.234709\",\"modified\":\"2022-09-05 16:21:30.234709\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"mode_of_payment\":\"Credit Card\",\"opening_amount\":0,\"expected_amount\":0,\"closing_amount\":0,\"difference\":0,\"parent\":\"POS-CLO-2022-00001\",\"parentfield\":\"payment_reconciliation\",\"parenttype\":\"POS Closing Entry\",\"doctype\":\"POS Closing Entry Detail\",\"__unsaved\":1}],\"pos_transactions\":[{\"name\":\"fb210cf4cb\",\"owner\":\"Administrator\",\"creation\":\"2022-09-05 16:21:30.234709\",\"modified\":\"2022-09-05 16:21:30.234709\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"pos_invoice\":\"ACC-PSINV-2022-00001\",\"posting_date\":\"2022-09-05\",\"customer\":\"Dummy Customer POS\",\"grand_total\":205,\"is_return\":0,\"return_against\":null,\"parent\":\"POS-CLO-2022-00001\",\"parentfield\":\"pos_transactions\",\"parenttype\":\"POS Closing Entry\",\"doctype\":\"POS Invoice Reference\",\"__unsaved\":1},{\"name\":\"dd78c853a1\",\"owner\":\"Administrator\",\"creation\":\"2022-09-05 16:21:30.234709\",\"modified\":\"2022-09-05 16:21:30.234709\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"pos_invoice\":\"ACC-PSINV-2022-00002\",\"posting_date\":\"2022-09-05\",\"customer\":\"Dummy Customer POS\",\"grand_total\":205,\"is_return\":0,\"return_against\":null,\"parent\":\"POS-CLO-2022-00001\",\"parentfield\":\"pos_transactions\",\"parenttype\":\"POS Closing Entry\",\"doctype\":\"POS Invoice Reference\",\"__unsaved\":1}],\"taxes\":[],\"__last_sync_on\":\"2022-09-05T10:51:30.569Z\",\"__unsaved\":1}",
 "action": "Submit"
},
"btn": {
 "jQuery360014505141363144871": {
 "events": {
  "click": [
  {
   "type": "click",
   "origType": "click",
   "guid": 24002,
   "namespace": ""
  }
  ]
 }
 }
},
"freeze": true,
"headers": {},
"error_handlers": {},
"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
"exception": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':21:01)' at line 1\")"
}
```

### Module

stock

### Version

Frappe-version=14.1.0
Erpnext-version=14.6.0

### Installation method

manual install

**Comment by asoral** [comment]
Solution :
In TIMESTAMP('2022-09-05',16:21:01) Time Written in int It should be Str
