### ISSUE TITLE
wkhtmltopdf not support using unpatched qt

### ISSUE THREAD

**Issue by hameedacpa** [frappe/erpnext#32343]
### Information about bug

Sales invoices not generated by pressing PDF button 

### Module

accounts, selling

### Version

ERPNext: v14.2.0 (version-14)
Frappe Framework: v14.8.0 (version-14)
wkhtmltopdf 0.12.6

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Error
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1598, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 129, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.10/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
The switch --print-media-type, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-erpnext'
Exit with code 1 due to network error: TimeoutError
```

**Comment by dj12djdjs** [comment]
As per: https://frappeframework.com/docs/v14/user/en/installation#pre-requisites

wkhtmltopdf with patched qt is required

**Comment by chetentshering** [comment]
I got the same issue

**Comment by rasos** [comment]
For generating PDFs, we have to use a version with a patched Qt. The latest that also supports SSLv3 is 0.12.5,  whereas 0.12.6 (that comes with Debian bullseye) does not produce logos in PDFs. 

Downgrading fixed it for me: 

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
apt install ./wkhtmltox_0.12.5-1.stretch_amd64.deb
```

**Comment by lasalesi** [comment]
In Debian 12 or ubuntu 22.04 LTS (which are required due to V14 Python dependency), this will not work due to libssl1.1 dependency:

    The following packages have unmet dependencies:
     wkhtmltox : Depends: libssl1.1 but it is not installable
    E: Unable to correct problems, you have held broken packages.
