### ISSUE TITLE
Developer mode not working

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#32342]
### Information about bug

I enabled developer mode by modifying site_config.json. I created a new app ( say test_app ) and installed in the site. Next, one of these two things happen:
1. Internal server error appears on next refresh.
2. While creating a new doctype (under developer mode), the module def error occurs: Module test_app not found. This error appears repeatedly and eventually turns in to an Internal Server Error.
 
I tried this with latest versions.

### Module

other

### Version

Frappe version 14.8.0
Erpnext version 14.2.0

Same error with Erpnext v 14.0.1 (may be an issue with Frappe, didn't check)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.0.1",
	"frappe": "14.8.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Module Def/new-module-def-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1598, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 301, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 323, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 281, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1087, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 928, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1268, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1250, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 925, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/module_def/module_def.py", line 15, in on_update
    frappe.clear_cache()
  File "apps/frappe/frappe/__init__.py", line 877, in clear_cache
    frappe.cache_manager.clear_user_cache()
  File "apps/frappe/frappe/cache_manager.py", line 89, in clear_user_cache
    clear_global_cache()
  File "apps/frappe/frappe/cache_manager.py", line 105, in clear_global_cache
    frappe.setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1529, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1387, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1336, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'vat_register'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Module Def\",\"name\":\"new-module-def-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"anup@ajiragroup.com\",\"custom\":0,\"app_name\":\"frappe\",\"module_name\":\"VAT Register\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360077612364792493291": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 196,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'vat_register'"
}
```
```

**Comment by dj12djdjs** [comment]
Steps:
1. `bench init frappe-bench`
2. `cd frappe-bench
`3. `bench get-app  --resolve-deps erpnext`
4. `bench new-app myapp`
5. Fill out bench prompts
6. ` bench new-site --mariadb-root-username {DB_ROOT_USER} localhost`
7. `bench --site localhost set-config developer_mode 1`
8. `bench --site localhost install-app erpnext`
9. `bench --site localhost install-app myapp`

With these steps it worked.

Please provide all the steps you used to create and install your app, and any error messages during the creation and installation of the app.

**Comment by ajiragroup** [comment]
We followed the steps as described in the link below. 
Only change in the steps in the link is we selected to install ERPNext v14.0.1 instead of the latest. We let the bench download the latest Frappe.

 Installation worked perfectly, without any errors.

We will check the corrections as you suggested and update you soon. Thanks!

https://discuss.erpnext.com/t/guide-how-to-install-erpnext-v14-on-linux-ubuntu-step-by-step-instructions/92960


One more thing, as per your suggestion, we first create a new app then new site, then install erpnext and then install new app.

But according to our flow:
we first installed created new site, installed erpnext in that site, then created a new app and then tried to install new app in that site. Then the error occured.
