### ISSUE TITLE
ImportError: cannot import name 'add_data_to_monitor' from 'frappe.monitor' (apps/frappe/frappe/monitor.py)

### ISSUE THREAD

**Issue by erpwala** [frappe/erpnext#32422]
### Information about bug

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1598, in call
    # if function has any **kwargs parameter that capture arbitrary keyword arguments
  File "apps/frappe/frappe/__init__.py", line 782, in wrapper_fn
    finally:
  File "apps/frappe/frappe/desk/reportview.py", line 29, in get
    data = compress(execute(**args), args=args)
  File "apps/frappe/frappe/desk/reportview.py", line 258, in compress
    from frappe.desk.query_report import add_total_row
  File "apps/frappe/frappe/desk/query_report.py", line 15, in <module>
    from frappe.monitor import add_data_to_monitor
ImportError: cannot import name 'add_data_to_monitor' from 'frappe.monitor' (apps/frappe/frappe/monitor.py)

### Module

other

### Version

ERPNext: v14.2.1 (version-14)

Frappe Framework: v14.8.0 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1598, in call
    # if function has any **kwargs parameter that capture arbitrary keyword arguments
  File "apps/frappe/frappe/__init__.py", line 782, in wrapper_fn
    finally:
  File "apps/frappe/frappe/desk/reportview.py", line 29, in get
    data = compress(execute(**args), args=args)
  File "apps/frappe/frappe/desk/reportview.py", line 258, in compress
    from frappe.desk.query_report import add_total_row
  File "apps/frappe/frappe/desk/query_report.py", line 15, in <module>
    from frappe.monitor import add_data_to_monitor
ImportError: cannot import name 'add_data_to_monitor' from 'frappe.monitor' (apps/frappe/frappe/monitor.py)
```

**Comment by mohsinalimat** [comment]
Same issue facing. https://github.com/frappe/frappe/issues/18258

**Comment by mohsinalimat** [comment]
@erpwala Please update the latest version-14.

**Comment by ankush** [comment]
You need to restart bench properly after updating.
