### ISSUE TITLE
Payment entry ledger is linked to cancelled invoice. Unable to delete Sales invoice

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32450]
### Information about bug

When an invoice is cancelled with payment entry the payment entry gets unlinked but unable to delete the cancelled sales invoice. it throws following error

![image](https://user-images.githubusercontent.com/112148467/193396102-00dc7d39-b5b7-460b-92e0-5ffa11cebb3f.png)

the payment entry is unlinked but the payment entry ledger is still linked to sales invoice
Invoice cancellation checks are all active in the accounts settings

![image](https://user-images.githubusercontent.com/112148467/193396140-a0c484c9-0247-4593-9e94-d165cd6cfeb1.png)

### Module

accounts, selling

### Version

ERPNext: v14.2.1 (HEAD)
Frappe Framework: v14.9.0 (HEAD)
Frappe HR: v1.0.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 273, in delete
    frappe.delete_doc(doctype, name, ignore_missing=False)
  File "apps/frappe/frappe/__init__.py", line 1239, in delete_doc
    return frappe.model.delete_doc.delete_doc(
  File "apps/frappe/frappe/model/delete_doc.py", line 130, in delete_doc
    check_if_doc_is_dynamically_linked(doc)
  File "apps/frappe/frappe/model/delete_doc.py", line 346, in check_if_doc_is_dynamically_linked
    raise_link_exists_exception(doc, reference_doctype, reference_docname, at_position)
  File "apps/frappe/frappe/model/delete_doc.py", line 359, in raise_link_exists_exception
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Sales Invoice <a href="/app/Form/Sales Invoice/ACC-SINV-2022-00010">ACC-SINV-2022-00010</a> is linked with Payment Ledger Entry <a href="/app/Form/Payment Ledger Entry/6b012c8867">6b012c8867</a> 
request.js:462:14
```

**Comment by InfiWits** [comment]
Still not working

**Comment by felixlu07** [comment]
Still not working for me as well.
