### ISSUE TITLE
Gross Profit Report

### ISSUE THREAD

**Issue by innovast-technology** [frappe/erpnext#32638]
### Information about bug

Gross Profit report gave an error message 
(1052, "Column 'company' in where clause is ambiguous")
It can be solved by changing  line 674 of gross_profit.py to
`conditions += " and tabSales Invoice.company = %(company)s"`

### Module

accounts

### Version

erpnext 14.3.0
frappe 14.11.1
hrms 1.0.0
payments 0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 781, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 254, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 781, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 88, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 69, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 19, in execute
    gross_profit_data = GrossProfitGenerator(filters)
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 400, in init
    self.load_invoice_items()
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 718, in load_invoice_items
    self.si_list = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1052, "Column 'company' in where clause is ambiguous")
```

**Comment by ruthra-kumar** [comment]
Not replicable.
@innovast-technology Does this error occur on every run or when a specific filter is applied?

**Comment by innovast-technology** [comment]
No it occurs for all filters
I am not sure if this is specific to my version of mysql server (mysql  Ver 15.1 Distrib 10.5.16-MariaDB) or not
