### ISSUE TITLE
Error in Web Form: Conflict of Wiki App with Web Forms in V14

### ISSUE THREAD

**Issue by taha-azzan** [frappe/erpnext#32719]
### Information about bug

Hi Frappe Family,

I hope you are doing well,

I had v13 of ERPNext, as well as Wiki, and everything was working normally.

I updated to v14 a while ago, but I encountered a problem after updating, which is that when I open any Web Form, the following message appears:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/wiki/wiki/www/new.py", line 10, in get_context
    context.doc = frappe.get_doc("Wiki Page", frappe.form_dict.wiki_page)
  File "apps/frappe/frappe/__init__.py", line 1180, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/website/website_generator.py", line 16, in __init__
    super().__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Wiki Page job_application not found
```

When I uninstall Wiki app all Web Forms work again!

Thank you in advance.

### Module

other

### Version

Frappe version:  v14.10.0 (version-14)
ERPNext version:  v14.2.3 (version-14)

**Comment by phot0n** [comment]
Hey, can you also try updating wiki app? - this problem was recently fixed: https://github.com/frappe/wiki/pull/93 & https://github.com/frappe/wiki/pull/94
