### ISSUE TITLE
Education module not working

### ISSUE THREAD

**Issue by Daniel-OS01** [frappe/erpnext#32767]
### Information about bug

Hello,

All the education module not for me. 

I get same message when i try to press any of the buttons in the module:

Not found
Page education-settings not found
The resource you are looking for is not available

![image](https://user-images.githubusercontent.com/31541221/198880337-e185218d-0aac-480b-8e57-5b1f28c2a7c3.png)
 

Another thing i noticed, in the user profile when i press on "Fees" i get an error:
![image](https://user-images.githubusercontent.com/31541221/198880181-7c8231aa-2ccc-43a0-bd71-202c2685e98d.png)

All the other modules working fine.

### Module

education

### Version

Frappe Framework: v14.13.0 (version-14)

ERPNext: v14.4.0 (version-14)

Education: v0.0.1 (develop)

Healthcare: v0.0.1 (develop)

Frappe HR: v1.0.0 (develop)

Frappe LMS: v0.0.1 (main)

Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
When i press Fees in the account profile:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/list_page.py", line 12, in render
    return super().render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/list.py", line 22, in get_context
    context.update(get_list_context(context, doctype) or {})
  File "apps/frappe/frappe/www/list.py", line 183, in get_list_context
    module = load_doctype_module(doctype)
  File "apps/frappe/frappe/modules/utils.py", line 230, in load_doctype_module
    module = get_doctype_module(doctype)
  File "apps/frappe/frappe/modules/utils.py", line 221, in get_doctype_module
    frappe.throw(_("DocType {} not found").format(doctype), exc=frappe.DoesNotExistError)
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)

frappe.exceptions.DoesNotExistError: DocType fees not found
```

**Comment by Solufyin** [comment]
Hi @dragon3252,

I think, if not enabled then please go to the domain setting and enable the education module.

Thank You!

**Comment by Daniel-OS01** [comment]
Hi @Solufyin 

Thank you.

Solution:

/app/domain-settings

Enable Education module:

![image](https://user-images.githubusercontent.com/31541221/199498775-e9e11810-e79f-47a3-830b-52ffcb7169a6.png)

**Comment by mcjill** [comment]
Education module not showing in domain settings
