### ISSUE TITLE
Unable to import chart of Accounts with Account Numbers

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32815]
### Information about bug

Unable to import chart of account with account numbers in ERPNext using chart of accounts importer tool. 
can anyone help me out in this please’?

![image](https://user-images.githubusercontent.com/112148467/199401703-d56e8e71-d214-42ae-a917-c639c5dbc65e.png)

it shows following error

![image](https://user-images.githubusercontent.com/112148467/199402302-681e825c-c8ff-4346-8b92-fcf799ab82da.png)

### Module

accounts

### Version

Frappe Chat: v0.0.1 (HEAD)
ERPNext: v13.40.3 (HEAD)
Frappe Framework: v13.42.0 (HEAD)

ERPNext: v14.4.0 (HEAD)
Frappe Framework: v14.13.0 (HEAD)
Frappe HR: v1.0.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

Frappe Server

### Relevant log output / Stack trace / Full Error Message.

```shell
XHRPOSThttps://craft-trading.frappe.cloud/api/method/erpnext.accounts.doctype.chart_of_accounts_importer.chart_of_accounts_importer.get_coa
[HTTP/2 417 Expectation Failed 145ms]

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 164, in get_coa
    forest = build_forest(data)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 256, in build_forest
    path = return_parent(data, account_name)[::-1]
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 215, in return_parent
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: The parent account <strong>Application of Funds (Assets)</strong> does not exists in the uploaded template
request.js:462:14
```

**Comment by pra17shant** [comment]
**You Can Build Your Template Like Wise and Try to Again**
![Template](https://user-images.githubusercontent.com/99401472/199899478-9456801b-793d-48ad-8169-44fbe272c05a.png)

**After Upload Template Image look like**

![Screenshot from 2022-11-04 11-19-27](https://user-images.githubusercontent.com/99401472/199899778-81283e0d-24f0-4bb6-8849-10b73225104a.png)

**Comment by maveezmh** [comment]
@pra17shant Thank you  Prashant. it works
