### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32901]
### Information about bug

Happens when a parent warehouse is set for All Warehouses, and then one switches view to Tree view for warehouses.
Well, there shouldn't be a parent warehouse for all warehouses, but the system allows this to be set.

![image](https://user-images.githubusercontent.com/1822868/200628943-1d8f1287-0537-4aaf-9f5d-161100c01470.png)

### Module

stock

### Version

ERPNext: v14.5.1 (HEAD)
Frappe Framework: v14.14.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
/api/method/erpnext.stock.doctype.warehouse.warehouse.get_children:1          Failed to load resource: the server responded with a status of 500 ()
request.js:462 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 175, in get_children
    warehouse_wise_value = get_warehouse_wise_stock_value(company)
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 205, in get_warehouse_wise_stock_value
    update_value_in_parent_warehouse(
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 220, in update_value_in_parent_warehouse
    update_value_in_parent_warehouse(
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 220, in update_value_in_parent_warehouse
    update_value_in_parent_warehouse(
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 220, in update_value_in_parent_warehouse
    update_value_in_parent_warehouse(
  [Previous line repeated 972 more times]
  File "apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 219, in update_value_in_parent_warehouse
    warehouse_wise_stock_value[parent_warehouse] += flt(stock_value)
  File "apps/frappe/frappe/utils/data.py", line 921, in flt
    if isinstance(s, str):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by s-aga-r** [comment]
@muchai unable to replicate:

![image](https://user-images.githubusercontent.com/63660334/204456045-0d8049bf-f185-4fdc-aae5-37841326b73a.png)

**Comment by muchai** [comment]
Seems there's a validation now, "Item cannot be added to its own descend**e**nts (this should be descend**a**nts")

As long as that validation is there, issue cannot recur.

Will close this issue.
