### ISSUE TITLE
Repost Item Valuation altering older GL entries

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#33002]
### Information about bug

Repost Item Valuation is making changes in older GL entries, including the fiscals years which are already closed.

https://user-images.githubusercontent.com/52111700/202373550-93a4d327-b66b-42c3-b9c5-28b442ac597c.mp4

This is a serious issue as companies often file their closing balance and there would be mismatch if repost is run.

### Module

accounts, stock

### Version

ERPNext: v13.41.0 (HEAD)
Frappe Framework: v13.43.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 139, in repost
    repost_gl_entries(doc)
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 199, in repost_gl_entries
    repost_doc=doc,
  File "apps/erpnext/erpnext/accounts/utils.py", line 1195, in repost_gle_for_stock_vouchers
    voucher_obj.make_gl_entries(gl_entries=expected_gle, from_repost=True)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 73, in make_gl_entries
    make_gl_entries(gl_entries, from_repost=from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 35, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 220, in save_entries
    check_freezing_date(gl_map[0]["posting_date"], adv_adj)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 441, in check_freezing_date
    formatdate(acc_frozen_upto)
  File "apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: You are not authorized to add or update entries before 31-03-2021
```

**Comment by rtdany10** [comment]
I believe [get_future_stock_vouchers](https://github.com/frappe/erpnext/blob/v13.41.0/erpnext/accounts/utils.py#L1240) is the culprit. When posting_date/posting_time passed to that function doesn't get parsed correctly, the timestamp becomes `datetime.datetime(1900, 1, 1, 0, 1)` causing all older entries to be altered.

**Comment by rtdany10** [comment]
This issue seems to arise when there are pending repost item valuations before the date of account freezing.
I believe the system tries to run pending one before executing the new ones(ordered on the basis of posting date and time) and the pending ones threw these errors.

I cancelled the older entries and the issue got resolved.
