### ISSUE TITLE
Server Error: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#33049]
### Information about bug

I opened Customer Doctype, and opened one customer -> Clicked in View->Accounting Ledger.

Then this error appeared. This error occured on other customers as well.

![image](https://user-images.githubusercontent.com/108009061/202897854-86436303-31aa-43d5-a989-08021c7a231a.png)

### Module

accounts

### Version

"erpnext": "14.7.0",
	"frappe": "14.15.0",
	"hrms": "1.0.0",
	"payments": "0.0.1"

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.7.0",
	"frappe": "14.15.0",
	"hrms": "1.0.0",
	"payments": "0.0.1"
}
```
### Route
```
query-report/General Ledger
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1581, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 781, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 249, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 781, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 43, in execute
    filters = set_account_currency(filters)
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 137, in set_account_currency
    else frappe.db.get_value(filters.party_type, filters.party[0], "default_currency")
  File "apps/frappe/frappe/database/database.py", line 495, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 592, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 809, in _get_values_from_table
    query = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 317, in dict_query
    conditions = self.get_condition(table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 213, in get_condition
    table_object = self.get_table(table)
  File "apps/frappe/frappe/database/query.py", line 223, in get_table
    table_name = table_name.strip('"').strip("'")
AttributeError: 'NoneType' object has no attribute 'strip'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "General Ledger",
		"filters": "{\"company\":\"Ajira Builders\",\"from_date\":\"2022-10-20\",\"to_date\":\"2022-11-20\",\"account\":[],\"party\":[\"Amrit Poudel\"],\"group_by\":\"Group by Voucher (Consolidated)\",\"cost_center\":[],\"project\":[],\"branch\":[],\"include_dimensions\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'strip'"
}
```
```

**Comment by ajiragroup** [comment]
Great!
