### ISSUE TITLE
Error while entering rate in Material Request

### ISSUE THREAD

**Issue by ahmadpak** [frappe/erpnext#33054]
### Information about bug

The Error pops up if I try to add the rate of the items which are initially zero

![Kapture 2022-11-21 at 05 43 11](https://user-images.githubusercontent.com/7881486/202936441-c3ea201b-9e11-4d95-ad5b-5cb5398b73aa.gif)

### App Versions

```
{
	"erpnext": "13.42.0",
	"frappe": "13.44.0",
	"havenir_tools": "0.0.1",
	"irc_erp": "0.0.1"
}
```
### Route
```
Form/Material Request/MR-ISS-2022-00054
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 91, in get_item_details
    out.update(get_price_list_rate(args, item))
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 792, in get_price_list_rate
    insert_item_price(args)
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 816, in insert_item_price
    (args.rate + args.discount_amount) / args.get("conversion_factor")
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"item_code\":\"SS-05-04-LC-00168\",\"warehouse\":\"Mech. & Elect. Store - IDP\",\"doctype\":\"Material Request\",\"buying_price_list\":\"Standard Buying\",\"currency\":\"PKR\",\"name\":\"MR-ISS-2022-00054\",\"qty\":1,\"stock_qty\":1,\"company\":\"IRC Dairy Products Pvt. Ltd.\",\"conversion_rate\":1,\"material_request_type\":\"Material Issue\",\"plc_conversion_rate\":1,\"rate\":100,\"uom\":\"Nos\",\"conversion_factor\":1}",
		"overwrite_warehouse": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.get_item_details.get_item_details"
}
```
### Response Data
```
{
	"exception": "TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'"
}
```

### Module

stock

### Version

Frappe Version 13.44.0
ERPNext Version 13.44.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 91, in get_item_details
    out.update(get_price_list_rate(args, item))
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 792, in get_price_list_rate
    insert_item_price(args)
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 816, in insert_item_price
    (args.rate + args.discount_amount) / args.get("conversion_factor")
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by ruthra-kumar** [comment]
Doesn't happen on latest-V13.42.7 @ahmadpak Does it persist?
