### ISSUE TITLE
AttributeError: module ‘erpnext’ has no attribute ‘get_company_currency’

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#33330]
### Information about bug

On saving sales invoice, getting this error.

![image](https://user-images.githubusercontent.com/67686213/207531722-fc8cba35-82ba-40a6-8337-41a27bad9a1b.png)

### Module

accounts, selling

### Version

ERPNext: v13.33.0 (HEAD)
Frappe Framework: v13.33.1 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
The issue is happening to multiple instances hosted on frappe cloud. Restart is temporarily fixing the issue. But we need permanent solution for this as customers are getting annoyed by these daily
```

**Comment by dj12djdjs** [comment]
@Craftint Can you please paste the traceback into the github issue? I cannot read it at all from the screen shot.

**Comment by Craftint** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 24, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 96, in validate
    super(SalesInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 32, in validate
    super(SellingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 42, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 156, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 436, in set_incoming_rate
    raise_error_if_no_rate=False,
  File "apps/erpnext/erpnext/stock/utils.py", line 300, in get_incoming_rate
    currency=erpnext.get_company_currency(args.get("company")),
AttributeError: module 'erpnext' has no attribute 'get_company_currency'
request.js:430:14




It is on submitting sales invoice

**Comment by Craftint** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 62, in get_count
    data = execute(**args)[0].get("total_count")
  File "apps/frappe/frappe/desk/reportview.py", line 68, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 479, in build_conditions
    match_conditions = self.build_match_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 695, in build_match_conditions
    self.shared = frappe.share.get_shared(self.doctype, self.user)
  File "apps/frappe/frappe/share.py", line 142, in get_shared
    "DocShare", fields=["share_name"], filters=filters, or_filters=or_filters
  File "apps/frappe/frappe/database/database.py", line 646, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1741, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1713, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 474, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "apps/frappe/frappe/model/db_query.py", line 495, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "apps/frappe/frappe/model/db_query.py", line 504, in prepare_filter_condition
    additional_filters_config = get_additional_filters_from_hooks()
  File "apps/frappe/frappe/boot.py", line 372, in get_additional_filters_from_hooks
    filter_config.update(frappe.get_attr(hook)())
  File "apps/frappe/frappe/__init__.py", line 1447, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/erpnext/erpnext/__init__.py", line 5, in <module>
    from erpnext.hooks import regional_overrides
  File "apps/erpnext/erpnext/hooks.py", line 115, in <module>
    "defaults": {"doctype": "Sales Order", "parents": [{"label": _("Orders"), "route": "orders"}]},
  File "apps/frappe/frappe/__init__.py", line 115, in _
    translated_string = get_full_dict(lang).get(msg)
  File "apps/frappe/frappe/translate.py", line 287, in get_full_dict
    frappe.local.lang_full_dict = load_lang(lang)
  File "apps/frappe/frappe/translate.py", line 311, in load_lang
    path = os.path.join(frappe.get_pymodule_path(app), "translations", lang + ".csv")
  File "apps/frappe/frappe/__init__.py", line 1244, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "apps/paci_app/paci_app/__init__.py", line 19, in <module>
    from erpnext.accounts.doctype.invoice_discounting.invoice_discounting import (
  File "apps/erpnext/erpnext/accounts/doctype/invoice_discounting/invoice_discounting.py", line 16, in <module>
    from erpnext.controllers.accounts_controller import AccountsController
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 30, in <module>
    from erpnext.accounts.doctype.pricing_rule.utils import (
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 16, in <module>
    from erpnext.stock.get_item_details import get_conversion_factor
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 13, in <module>
    from erpnext import get_company_currency
ImportError: cannot import name 'get_company_currency' from 'erpnext' (apps/erpnext/erpnext/__init__.py)

It is on saving purchsae invoice on other site

**Comment by rohitwaghchaure** [comment]
@Craftint Update your ERPNext and Frappe apps to latest version of v13 which is v13.42.2 and v13.46.0

**Comment by Craftint** [comment]
The second log i posted is from latest version

**Comment by deepeshgarg007** [comment]
@Craftint Is this still happening, please help us with the steps to replicate and then reopen the issue

**Comment by Craftint** [comment]
Hi,
The same error is happening for another site which has frappe version : 13.46 and erpnext version 13.42.4 and hosted in frappecloud,

The error log : 

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/doctype/tag/tag.py", line 208, in get_tags_list_for_awesomebar
    return [t.name for t in frappe.get_list("Tag")]
  File "apps/frappe/frappe/__init__.py", line 1713, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 479, in build_conditions
    match_conditions = self.build_match_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 695, in build_match_conditions
    self.shared = frappe.share.get_shared(self.doctype, self.user)
  File "apps/frappe/frappe/share.py", line 142, in get_shared
    "DocShare", fields=["share_name"], filters=filters, or_filters=or_filters
  File "apps/frappe/frappe/database/database.py", line 646, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1741, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1713, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 474, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "apps/frappe/frappe/model/db_query.py", line 495, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "apps/frappe/frappe/model/db_query.py", line 504, in prepare_filter_condition
    additional_filters_config = get_additional_filters_from_hooks()
  File "apps/frappe/frappe/boot.py", line 372, in get_additional_filters_from_hooks
    filter_config.update(frappe.get_attr(hook)())
  File "apps/frappe/frappe/__init__.py", line 1447, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/erpnext/erpnext/__init__.py", line 5, in <module>
    from erpnext.hooks import regional_overrides
  File "apps/erpnext/erpnext/hooks.py", line 115, in <module>
    "defaults": {"doctype": "Sales Order", "parents": [{"label": _("Orders"), "route": "orders"}]},
  File "apps/frappe/frappe/__init__.py", line 115, in _
    translated_string = get_full_dict(lang).get(msg)
  File "apps/frappe/frappe/translate.py", line 287, in get_full_dict
    frappe.local.lang_full_dict = load_lang(lang)
  File "apps/frappe/frappe/translate.py", line 311, in load_lang
    path = os.path.join(frappe.get_pymodule_path(app), "translations", lang + ".csv")
  File "apps/frappe/frappe/__init__.py", line 1244, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "apps/paci_app/paci_app/__init__.py", line 19, in <module>
    from erpnext.accounts.doctype.invoice_discounting.invoice_discounting import (
  File "apps/erpnext/erpnext/accounts/doctype/invoice_discounting/invoice_discounting.py", line 16, in <module>
    from erpnext.controllers.accounts_controller import AccountsController
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 30, in <module>
    from erpnext.accounts.doctype.pricing_rule.utils import (
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 16, in <module>
    from erpnext.stock.get_item_details import get_conversion_factor
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 13, in <module>
    from erpnext import get_company_currency
ImportError: cannot import name 'get_company_currency' from 'erpnext' (apps/erpnext/erpnext/__init__.py)
[request.js:430:14](https://dubaicharity.frappe.cloud/apps/frappe/frappe/public/js/frappe/request.js)
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. [utils.js:764:9](https://dubaicharity.frappe.cloud/apps/frappe/frappe/public/js/frappe/utils/utils.js)
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 46, in get_list
    data = execute(**args)
  File "apps/frappe/frappe/desk/reportview.py", line 68, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 474, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "apps/frappe/frappe/model/db_query.py", line 495, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "apps/frappe/frappe/model/db_query.py", line 504, in prepare_filter_condition
    additional_filters_config = get_additional_filters_from_hooks()
  File "apps/frappe/frappe/boot.py", line 372, in get_additional_filters_from_hooks
    filter_config.update(frappe.get_attr(hook)())
  File "apps/frappe/frappe/__init__.py", line 1447, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/erpnext/erpnext/__init__.py", line 5, in <module>
    from erpnext.hooks import regional_overrides
  File "apps/erpnext/erpnext/hooks.py", line 115, in <module>
    "defaults": {"doctype": "Sales Order", "parents": [{"label": _("Orders"), "route": "orders"}]},
  File "apps/frappe/frappe/__init__.py", line 115, in _
    translated_string = get_full_dict(lang).get(msg)
  File "apps/frappe/frappe/translate.py", line 287, in get_full_dict
    frappe.local.lang_full_dict = load_lang(lang)
  File "apps/frappe/frappe/translate.py", line 311, in load_lang
    path = os.path.join(frappe.get_pymodule_path(app), "translations", lang + ".csv")
  File "apps/frappe/frappe/__init__.py", line 1244, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "apps/paci_app/paci_app/__init__.py", line 19, in <module>
    from erpnext.accounts.doctype.invoice_discounting.invoice_discounting import (
  File "apps/erpnext/erpnext/accounts/doctype/invoice_discounting/invoice_discounting.py", line 16, in <module>
    from erpnext.controllers.accounts_controller import AccountsController
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 30, in <module>
    from erpnext.accounts.doctype.pricing_rule.utils import (
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 16, in <module>
    from erpnext.stock.get_item_details import get_conversion_factor
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 13, in <module>
    from erpnext import get_company_currency
ImportError: cannot import name 'get_company_currency' from 'erpnext' (apps/erpnext/erpnext/__init__.py)

**Comment by Craftint** [comment]
![image](https://user-images.githubusercontent.com/67686213/208589514-3fb61bf2-3d95-4aab-bb5f-ce81ea286eb8.png)

**Comment by Craftint** [comment]
@deepeshgarg007 Please check

**Comment by dj12djdjs** [comment]
I think this may be a frappe cloud problem. Maybe the env isn't setup properly. I would recommend opening a support ticket on frappe cloud. @Craftint

**Comment by Craftint** [comment]
We had raised support and contacted frappe cloud team. They are discarding us saying its application related.
It is still happening. We require a combined support
