### ISSUE TITLE
Cannot Submit Purchase Order that has been Created from Sales Order when Supplier is Internal Supplier

### ISSUE THREAD

**Issue by sameer-mahendru** [frappe/erpnext#33349]
### Information about bug

In my implementation I have two separate companies - one is a Distribution company and the other is a Manufacturing company.  The manufacturing company has been set up as an internal supplier for the Distribution company (i.e. a Supplier has been created and has been set to represent the Manufacturing Company and has been allowed to transact with the Distribution company.

The Distribution company creates Sales Orders and then proceeds to create a Purchase Order, from said Sales Order, to the internal supplier, the Manufacturing Company. The manufacturing Company then proceeds to make an Inter Company Sales Order from the Purchase Order of the Distribution company.

This flow was working fine in version 12.  However, since migrating to version 13 and continuing into version 14, this process flow is broken when creating a Purchase Order from Sales Order in the distribution company.  The error raised is detailed in the error message section.

My limited understanding of the code based has led me to identify the function "set_incoming_rate" and line number 313 in the buying_controller.py file as follows:

> field = "incoming_rate" if self.get("is_internal_supplier") else "rate"

as the culprit. I am unable to find the field "incoming_rate" anywhere in the Purchase Order and Purchase Order Item Doctypes.

Would appreciate a speedy resolution to this issue as it it is currently hampering our workflow. I can be contacted on sam.mahendru@gmail.com should there be any further queries.

### Module

buying

### Installed Apps
ERPNext: v14.10.1 (HEAD)

Frappe Framework: v14.19.1 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.10.1",
	"frappe": "14.19.1",
	"hrms": "1.0.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Purchase Order/new-purchase-order-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 325, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 257, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1038, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 907, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 904, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 54, in validate
    super(PurchaseOrder, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 52, in validate
    super(SubcontractingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 155, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 319, in set_incoming_rate
    frappe.db.get_value(ref_doctype, d.get(frappe.scrub(ref_doctype)), field)
  File "apps/frappe/frappe/database/database.py", line 495, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 592, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 822, in _get_values_from_table
    return self.sql(query, as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'incoming_rate' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"sam.mahendru@gmail.com\",\"docstatus\":0,\"idx\":0,\"title\":\"{supplier_name}\",\"naming_series\":\"PO-.YY.-.abbr.-.####\",\"supplier\":\"Automotive Ancillaries Limited (S) - AED\",\"transaction_date\":\"2022-12-15\",\"company\":\"Tradeways LLC\",\"abbr\":\"TWL\",\"apply_tds\":0,\"is_subcontracted\":0,\"cost_center\":\"AAL Industrial - TWL\",\"currency\":\"AED\",\"conversion_rate\":1,\"price_list_currency\":\"AED\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"total_qty\":100,\"total_net_weight\":1713,\"base_total\":5600,\"base_net_total\":5600,\"total\":5600,\"net_total\":5600,\"tax_withholding_net_total\":0,\"base_tax_withholding_net_total\":0,\"tax_category\":\"UAE VAT RCM - Industrial\",\"shipping_rule\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":5600,\"base_rounding_adjustment\":0,\"base_in_words\":\"\",\"base_rounded_total\":0,\"grand_total\":5600,\"rounding_adjustment\":0,\"rounded_total\":0,\"disable_rounded_total\":1,\"in_words\":\"\",\"advance_paid\":0,\"apply_discount_on\":\"\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"company_trn\":\"100328046600003\",\"customer\":\"\",\"customer_name\":\"\",\"contact_print_hide\":0,\"shipping_address_print_hide\":0,\"payment_terms_template\":null,\"status\":\"Draft\",\"per_billed\":0,\"per_received\":0,\"letter_head\":\"Tradeways LLC\",\"group_same_items\":0,\"recoverable_standard_rated_expenses\":0,\"reverse_charge\":\"N\",\"recoverable_reverse_charge\":100,\"reverse_charge_applicable\":\"N\",\"select_print_heading\":\"PURCHASE ORDER\",\"language\":\"en\",\"total_base_weight\":1645.5864,\"is_internal_supplier\":1,\"inter_company_order_reference\":\"\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Order\",\"pricing_rules\":[],\"items\":[{\"owner\":\"sam.mahendru@gmail.com\",\"docstatus\":0,\"idx\":1,\"item_code\":\"AAL137500\",\"item_name\":\"AAL.1375.00\",\"fg_item_qty\":1,\"schedule_date\":\"2022-12-15\",\"item_group\":\"Leaf Springs-Conventional(A)\",\"description\":\"<div>Spring Leaf</div>\",\"tax_rate\":5,\"tax_amount\":525,\"total_amount\":11025,\"image\":\"\",\"qty\":100,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":100,\"price_list_rate\":56,\"last_purchase_rate\":56,\"base_price_list_rate\":56,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":56,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":56,\"rate\":56,\"amount\":5600,\"base_rate\":56,\"base_amount\":5600,\"stock_uom_rate\":56,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":56,\"net_amount\":5600,\"base_net_rate\":56,\"base_net_amount\":5600,\"warehouse\":\"Stores - TWL\",\"actual_qty\":0,\"company_total_stock\":0,\"sales_order\":\"SO-22-TWL-2663\",\"sales_order_item\":\"d614e7ff4d\",\"delivered_by_supplier\":0,\"against_blanket_order\":0,\"blanket_order_rate\":0,\"received_qty\":0,\"returned_qty\":0,\"billed_amt\":0,\"expense_account\":\"51110 - Cost of Goods Sold - TWL\",\"include_exploded_items\":0,\"weight_per_unit\":17.13,\"total_weight\":1713,\"weight_uom\":\"Kg\",\"cost_center\":\"AAL Industrial - TWL\",\"is_fixed_asset\":0,\"item_tax_rate\":\"{}\",\"page_break\":0,\"item_detail\":\"FB 060X08X4505-SUP09\",\"base_weight_per_unit\":16.455864,\"sub_total_base_weight\":1645.5864,\"parentfield\":\"items\",\"parenttype\":\"Purchase Order\",\"doctype\":\"Purchase Order Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-purchase-order-1\",\"name\":\"new-purchase-order-item-1\",\"has_margin\":false,\"child_docname\":\"new-purchase-order-item-1\"}],\"taxes\":[{\"docstatus\":0,\"doctype\":\"Purchase Taxes and Charges\",\"name\":\"new-purchase-taxes-and-charges-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"sam.mahendru@gmail.com\",\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"account_currency\":null,\"parent\":\"new-purchase-order-1\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Order\",\"idx\":1,\"row_id\":null,\"account_head\":\"221431 - VAT RCM (Input) - TWL\",\"description\":\"VAT RCM (Input)\",\"rate\":5,\"cost_center\":\"AAL Industrial - TWL\",\"tax_amount\":280,\"tax_amount_after_discount_amount\":280,\"total\":5880,\"base_tax_amount\":280,\"base_total\":5880,\"base_tax_amount_after_discount_amount\":280,\"item_wise_tax_detail\":\"{\\\"AAL137500\\\":[5,280]}\"},{\"docstatus\":0,\"doctype\":\"Purchase Taxes and Charges\",\"name\":\"new-purchase-taxes-and-charges-2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"sam.mahendru@gmail.com\",\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"account_currency\":null,\"parent\":\"new-purchase-order-1\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Order\",\"idx\":2,\"row_id\":null,\"account_head\":\"221432 - VAT RCM (Output) - TWL\",\"description\":\"VAT RCM (Output)\",\"rate\":-5,\"cost_center\":\"AAL Industrial - TWL\",\"tax_amount\":-280,\"tax_amount_after_discount_amount\":-280,\"total\":5600,\"base_tax_amount\":-280,\"base_total\":5600,\"base_tax_amount_after_discount_amount\":-280,\"item_wise_tax_detail\":\"{\\\"AAL137500\\\":[-5,-280]}\"}],\"payment_schedule\":[],\"supplied_items\":[],\"__islocal\":1,\"__onload\":{\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-purchase-order-1\",\"__last_sync_on\":\"2022-12-15T07:20:27.755Z\",\"supplier_name\":\"Automotive Ancillaries Limited\",\"supplier_name_in_arabic\":null,\"supplier_trn\":\"100261032500003\",\"supplier_group_2\":\"Local - AAL Other\",\"represents_company\":\"Automotive Ancillaries Limited\",\"supplier_address\":\"Automotive Ancillaries Limited (S)-Billing\",\"address_display\":\"PO Box 16755<br>EWTA-52, Jebel Ali Free Zone<br>Dubai<br>\\nUnited Arab Emirates<br>\\nPhone: +97148816645<br>Fax: +97148816110<br>\",\"billing_address\":\"Tradeways LLC-Billing\",\"billing_address_display\":\"PO Box 5155<br>Dubai<br>\\nUnited Arab Emirates<br>\\nPhone: +97142236565<br>Fax: +97142210045<br>\",\"shipping_address\":\"Tradeways LLC-Billing\",\"shipping_address_display\":\"PO Box 5155<br>Dubai<br>\\nUnited Arab Emirates<br>\\nPhone: +97142236565<br>Fax: +97142210045<br>\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"buying_price_list\":\"Internal-AAL-TWL-AED\",\"taxes_and_charges\":\"UAE VAT RCM - Industrial - TWL\",\"schedule_date\":\"2022-12-15\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery36000046066993343207851": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 6558,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'incoming_rate' in 'field list'\")"
}
```
```

**Comment by rohitwaghchaure** [comment]
@sameer-mahendru 
Have you tried creating the Purchase Order first and then Sales Order?
https://github.com/frappe/erpnext/pull/32113

**Comment by sameer-mahendru** [comment]
@rohitwaghchaure 
Thank you for taking the time to respond!

When I create the Purchase Order in Company A first then I am only able to create and Inter Company Sales Order in Company B.  However, in this case, the Sales Order in Company A is still pending?

The flow that I need is Sales Order (Company A) --> Purchase Order (Company A) --> Inter Company Sales Order (Company B) --> Delivery Note (Company B) --> Sales Invoice (Company B) --> Inter Company Purchase Invoice (Company A). This entire flow is needed not just to update stock and accounts, but also to generate the necessary documentation (Invoices, Packing Lists, Delivery Notes) for Customs and Taxation purposes.

I am able to do Sales Order (Company A) --> Purchase Order (Company A) as long as the Supplier selected in the Purchase Order is not of type "internal supplier".  However, then I am not able to proceed with this Purchase Order (Company A) to make an Inter Company Sales Order (Company B).

The entire flow I mentioned above was working just fine in version 12. Since upgrading to Version 13 and now 14 this flow is broken. The best I can figure, with my limited understanding, that this is due to line number 313 in the buying_controller.py selecting a field "incoming_rate" which does not exist when submitting a Purchase Order.

Appreciate any further help that you can provide or guidance as to how to get this elevated in priority with Erpnext team.  We have living with this since version 13, but it is starting to hamper our work.

**Comment by zenicolas** [comment]
Hi @sameer-mahendru 

We're having the same issue, have you been able to find a solution or what is your workaround ? Are you creating the purchase order on a "non-internal" supplier ? 

Thanks in advance

**Comment by nabinhait** [comment]
The issue has been fixed in v14, closing the issue.
