### ISSUE TITLE
Error: Column company in where clause is ambiguos

### ISSUE THREAD

**Issue by fkalpana** [frappe/erpnext#33364]
### Information about bug

In the gross profit report, there is an ambiguous column on left join.
Please change the following in the code.

app/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py

` def load_invoice_items(self):
                conditions = ""
                if self.filters.company:
                        conditions += " and `tabSales Invoice`.company = %(company)s"   #Correction must be done here. add table name before column
                if self.filters.from_date:
                        conditions += " and posting_date >= %(from_date)s"
                if self.filters.to_date:
                        conditions += " and posting_date <= %(to_date)s"

`

### Module

accounts

### Version

"erpnext": "14.10.1",
"frappe": "14.19.1"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.10.1",
	"frappe": "14.19.1",
	"payments": "0.0.1"
}
```
### Route
```
query-report/Gross Profit
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 784, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 784, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 20, in execute
    gross_profit_data = GrossProfitGenerator(filters)
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 401, in __init__
    self.load_invoice_items()
  File "apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.py", line 738, in load_invoice_items
    self.si_list = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1052, "Column 'company' in where clause is ambiguous")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Gross Profit",
		"filters": "{\"company\":\"DOV\",\"from_date\":\"2022-01-01\",\"to_date\":\"2022-12-31\",\"group_by\":\"Invoice\"}",
		"is_tree": true,
		"parent_field": "parent_invoice"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}

### Response Data1
```
{
	"exception": "pymysql.err.OperationalError: (1052, \"Column 'company' in where clause is ambiguous\")"
}
```
```

**Comment by deepeshgarg007** [comment]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/42651287/211148751-bfaaa3f8-1feb-4ddd-ae99-02f1c57dc774.png">

@fkalpana I am unable to replicate, please give us more info to replicate and then reopen the issue
