### ISSUE TITLE
Bug in general ledger report - Accounting Dimension

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#33443]
### Information about bug

We have created a Business Division new doctype and added that into accounting Dimension

When tries to fetch in general ledger it shows mysql error

Server Error
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''IRSAA Internal Audit'\n\t\t\n\t\torder by posting_date, creation' at line 9")

![image](https://user-images.githubusercontent.com/21578167/209514317-6eb2930e-0c70-41ea-936a-1ae03bad1509.png)

### Module

accounts

### Version

ERPNext: v13.42.5 (version-13)
Frappe Framework: v13.46.1 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Syntax error in query: request.js:430:14
select
			name as gl_entry, posting_date, account, party_type, party,
			voucher_type, voucher_no, business_division,
			cost_center, project,
			against_voucher_type, against_voucher, account_currency,
			remarks, against, is_opening, creation , debit, credit, debit_in_account_currency,
		credit_in_account_currency 
		from `tabGL Entry`
		where company=%(company)s and (posting_date >=%(from_date)s or is_opening = 'Yes') and (posting_date <=%(to_date)s) and is_cancelled = 0 and business_division in %(business_division)s
		
		order by posting_date, creation request.js:430:14
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 89, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 165, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 50, in execute
    res = get_result(filters, account_details)
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 153, in get_result
    gl_entries = get_gl_entries(filters, accounting_dimensions)
  File "apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 226, in get_gl_entries
    gl_entries = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 187, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''IRSAA Internal Audit'\n\t\t\n\t\torder by posting_date, creation' at line 9")
```

**Comment by ghost** [comment]
@dineshpanchal93  What version of MariaDB are you running? [Clerkie](https://bit.ly/clerkie_ai)
