### ISSUE TITLE
Sales invoice submit error

### ISSUE THREAD

**Issue by yesmathew** [frappe/erpnext#33486]
### Information about bug

Recently migrated to ver 14
On submission of sales invoices, every time it throws an error. But once the cache is cleared it works as expected.

![image](https://user-images.githubusercontent.com/8710780/210037162-1f10415f-2963-4a77-a5a4-d4d8ff04041e.png)

### Module

accounts, selling

### Version

"bank_api_integration": "0.0.1",
"erpnext": "14.11.1",
"frappe": "14.21.0"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"bank_api_integration": "0.0.1",
	"erpnext": "14.11.1",
	"frappe": "14.21.0"
}
```
### Route
```
Form/Sales Invoice/KOSI-22-00311
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 284, in run_doc_method
    doc = frappe.get_doc(docs)
  File "apps/frappe/frappe/__init__.py", line 1179, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 64, in get_doc
    raise ValueError("First non keyword argument must be a string or dict")
ValueError: First non keyword argument must be a string or dict

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "apply_shipping_rule"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method"
}
```
### Response Data
```
{
	"exception": "ValueError: First non keyword argument must be a string or dict"
}
```

**Comment by deepeshgarg007** [comment]
@yesmathew This might be your site-specific issue or must have been resolved by now. This is not replicable, closing this issue
