### ISSUE TITLE
Cannot select customer primary contact

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#33484]
### Information about bug

The system throws a sql error on trying to select the primary contact for a customer.

![customer_primary_contact_select](https://user-images.githubusercontent.com/12420747/209963538-75123d0a-5b11-47ee-90e0-36bc320eb19c.png)

### Module

buying, selling

### Version

erpnext 14.11.1
frappe 14.21.0

### Installation method

None

**Comment by dj12djdjs** [comment]
@mujeerhashmi Can you provide the traceback?

**Comment by mujeerhashmi** [comment]
```
### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.11.1",
	"frappe": "14.21.0",
	"hrms": "1.0.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 35, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 98, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 83, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 299, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 745, in get_customer_primary_contact
    .run()
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabContact.full_name' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Contact",
		"ignore_user_permissions": 0,
		"reference_doctype": "Customer",
		"query": "erpnext.selling.doctype.customer.customer.get_customer_primary_contact",
		"filters": "{\"customer\":\"new-customer-1\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabContact.full_name' in 'field list'\")"
}
```

**Comment by dj12djdjs** [comment]
This has been fixed with this PR: https://github.com/frappe/erpnext/pull/33440

It is just waiting to be released. You can use this patch to fix your issue.
