### ISSUE TITLE
paid_amount in POS invoice_doc gets modified during validation, in cases of fractional Grand_Total amounts

### ISSUE THREAD

**Issue by karanwilson** [frappe/erpnext#33494]
### Information about bug

In the case of fractional amounts in grand_total:- (with or without rounding disabled)

When the POS Invoice is saved using invoice_doc.save()  (before submitting the invoice) :-
In case of 'Rounding enabled':
under run_before_save_methods()  a validate method is executed tracing to sales_invoice.py then to its super class selling_controller.py - when this SellingController super class executes its validate method, then the invoice_doc.paid_amount is getting changed from grand_total to the fractional part of the grand_total in case of rounding (as per stack trace below);
In case of 'Rounding disabled':
the invoice_doc.paid_amount is getting changed from grand_total to 0.01 - only in cases of grand_total having fractional amount 0.35 or less, does the validation pass without modification to the invoice_doc.paid_amount.

This changed invoice_doc.paid_amount value then creates an exception in the validate_pos(self) method in sales_invoice.py

### Module

selling

### Version

ERPNext: v13.42.2 (version-13)
Frappe Framework: v13.45.1 (version-13)
POS Awesome: v3.5.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 400, in update_invoice
    invoice_doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 133, in validate
    self.validate_pos()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 798, in validate_pos
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: 'If' matched: Paid amount 0.39 + Write Off Amount 0.0 can not be greater than Grand Total -66.38; invoice_total -66.0, self.rounded_total -66.0, self.precision('grand total') 2
```

**Comment by karanwilson** [comment]
Traced the rabbit hole to really deep waters... understood the true meaning of spaghetti code :-)
I had to finally set the 'Currency Precision' to 3, and the problem is solved.

**Comment by karanwilson** [comment]
While the problem was solved by setting the 'Currency Precision' to 3 - I now understand that the problem was actually sourcing from POS Awesome - as they are not using the Banker's rounding algorithm that Frappe is using..
