### ISSUE TITLE
Retail POS email send error

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#33578]
### Information about bug

After "email receipt" in the retail module the system shows an error in the error logs.

### Module

selling, other

### Version

ERPNext: v13.39.5 (version-13)

Frappe Framework: v13.41.4 (version-13)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
sendmail
Error
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 144, in execute_job
    method(**kwargs)
  File "apps/frappe/frappe/core/doctype/communication/email.py", line 649, in sendmail
    communication._notify(
  File "apps/frappe/frappe/core/doctype/communication/communication.py", line 290, in _notify
    _notify(self, print_html, print_format, attachments, recipients, cc, bcc)
  File "apps/frappe/frappe/core/doctype/communication/email.py", line 271, in _notify
    prepare_to_notify(doc, print_html, print_format, attachments)
  File "apps/frappe/frappe/core/doctype/communication/email.py", line 356, in prepare_to_notify
    doc.content += get_attach_link(doc, print_format)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by bynicolas** [comment]
I experience the same thing

```
Installed Apps
ERPNext: v14.12.1 (HEAD)

Frappe Framework: v14.22.0 (HEAD)

Payments: v0.0.1 (develop)
```
