### ISSUE TITLE
service "configurator" didn't completed successfully: exit 1

### ISSUE THREAD

**Issue by AJM-LSC** [frappe/erpnext#33620]
### Information about bug

Getting the below issue when starting up images with compose. I've had everything running fine for months, but I rebuilt images with the new version and now the configurator is failing to start. I've done this every update since October without any issues.

### Module

other

### Version

 Frappe v14.22.0
ERPNext v14.12.1

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/usr/local/bin/configure.py", line 56, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/configure.py", line 44, in main
    update_config(
  File "/usr/local/bin/configure.py", line 16, in update_config
    config: dict[str, Any] = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by AJM-LSC** [comment]
deleting the volume fixed the issue.
