### ISSUE TITLE
Issue when scrapping asset

### ISSUE THREAD

**Issue by cambraventures** [frappe/erpnext#33729]
### Information about bug

When I try to scrap an asset or do an asset movement I get the following error:

Special Characters except "-", "#", ".", "/", "{" and "}" not allowed in naming series

I've named and renamed all of the assets of the company and it's still giving me the issue. Please help !

### Module

other

### Version

Frappe Version: v14.14.1 (version-14)
ERPNext Version:  v14.5.1 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
N/A
```

**Comment by anandbaburajan** [comment]
Hello @cambraventures, can you share the full traceback of the error?

**Comment by cambraventures** [comment]
![41D018BC-B026-4CDA-90BD-3CFC43D23174](https://user-images.githubusercontent.com/117315619/213442702-503468be-8ba2-42be-8dd0-2b477e957d65.png)

All I get is this where would I find the trace back within the program. I host on my own server

**Comment by anandbaburajan** [comment]
@cambraventures can you please share the steps to reproduce the issue? You might be using some other special character in some document related to the asset. Also, I'll see how this error message can be improved.

**Comment by cambraventures** [comment]
I go to assets, I click on the asset and once in the page I select Manage > Scrap Asset and then it asks me if I want to do this I click OK and then the message comes up. 
![C989DEA3-5237-45C8-A894-4FF8737E1E04](https://user-images.githubusercontent.com/117315619/213466497-b6f35849-04a4-4eb5-b3d2-565a4757a231.jpeg)
![1EDD1B12-29D3-4E61-949D-DEF8C85FE480](https://user-images.githubusercontent.com/117315619/213466653-f8d634c3-7b35-4261-8a00-08422e2ca5b6.jpeg)
![1F1245D3-54CB-4DB9-B9A1-FCE997D557A8](https://user-images.githubusercontent.com/117315619/213466766-e2f8bfc5-e488-41fc-8a09-45b4a3d58c7d.jpeg)
![08FA9F64-EDC5-447E-8205-7CA5D7D1D881](https://user-images.githubusercontent.com/117315619/213466881-4e6b21be-8fc3-4a4b-8f49-f9f4518a10d9.jpeg)

**Comment by anandbaburajan** [comment]
@cambraventures I understand that. By "steps to reproduce the issue", I meant the step by step approach you took (from creating an asset to scrapping the asset), using an example. Also, you can find the traceback through the console section of your browser's developer tools. Open the console, click scrap and it should show something like this:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/2698932/213490318-6ca2c70e-2b8c-468c-b991-0469897f035e.png">

**Comment by cambraventures** [comment]
My apologies for not understanding what you meant. I will give you step by step here and I will see if I can locate the trace back in Developer

**Comment by cambraventures** [comment]
Here is the trace back for the error:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 202, in scrap_asset
    depreciate_asset(asset, date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 252, in depreciate_asset
    make_depreciation_entry(asset.name, date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 115, in make_depreciation_entry
    je.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 325, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 252, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 448, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 222, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 258, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 283, in make_autoname
    return series.generate_next_name(doc)
  File "apps/frappe/frappe/model/naming.py", line 68, in generate_next_name
    self.validate()
  File "apps/frappe/frappe/model/naming.py", line 60, in validate
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.model.naming.InvalidNamingSeriesError: Special Characters except "-", "#", ".", "/", "{" and "}" not allowed in naming series

**Comment by cambraventures** [comment]
I'm tied up at the moment with work I will do a step by step once I have some free time.

Thanks

**Comment by anandbaburajan** [comment]
@cambraventures seems like there's an issue with naming in journal entries. Have you set a custom "Series for Asset Depreciation Entry (Journal Entry)"? Can you share what other depreciation journal entries look like (are they something like ACC-JV-2023-00022 or different)?

**Comment by cambraventures** [comment]
We haven't had any depreciation this year because we moved over from Quickbooks and all the depreciation had accumulated on that system we just entered in the previous depreciation in the box asked so we haven't done any journal entries for depreciation yet. I can tell you that when the system was set up it was out of the box and we didn't set up any custom naming series in a script or in the code.

**Comment by cambraventures** [comment]
I can also tell you when I entered in the older pre depreciated assets we did an import with an excel file if that helps. Any new assets we entered this year was through ERPNext and it used the naming series ACC-ASS-.YYYY. But we changed all of the asset names to the names of the items to match them up

**Comment by anandbaburajan** [comment]
@cambraventures thanks, but the info is not enough unfortunately. Can you share the exact steps to reproduce? Or, I'm pushing a fix to improve the error message, so you could wait for a few days, update your site when the latest release is available, and then you can see in the error which naming series is causing the problem.

**Comment by cambraventures** [comment]
Here are the steps I'm going thru to get this error:

Step one I go to "Asset" and click "Add Asset"
![image](https://user-images.githubusercontent.com/117315619/213878151-d4fa454c-a949-41ea-8858-a401afcfee74.jpeg)

Then I fill in the required items. The asset is tied to an Item already entered into the system as a "fixed asset".
![image](https://user-images.githubusercontent.com/117315619/213878217-2868dc8f-9bcd-4fd0-988b-b56e1c6998ae.jpeg)

![image](https://user-images.githubusercontent.com/117315619/213878240-e15d96d0-4769-4179-8341-0973ce4f318e.jpeg)

Then I save and Submit and the asset is now being tracked:
![image](https://user-images.githubusercontent.com/117315619/213878268-4a52613d-5b1a-4b73-94f9-6b37f490ef06.jpeg)

Then I click back into the asset. On the top of the page is a pull down that says Manage. When I do it has the option of scrap asset which I select. It asks me am I sure and I say ok then the error appears:

![image](https://user-images.githubusercontent.com/117315619/213878337-fd31b7c2-3b7c-49f1-838e-ac949fb8749f.jpeg)

![image](https://user-images.githubusercontent.com/117315619/213878367-981cbe29-99b9-4d04-9b19-19dd45b3b040.jpeg)

![image](https://user-images.githubusercontent.com/117315619/213878388-713b6157-0935-4e51-949c-99f53a3db27f.jpeg)

![image](https://user-images.githubusercontent.com/117315619/213878422-9b5a85be-165d-4527-83fb-d55ceeaf9286.jpeg)

**Comment by anandbaburajan** [comment]
@cambraventures can you upgrade to the latest release, try scrapping and see which is the fauly naming series?

**Comment by cambraventures** [comment]
Yes definitely. I did the upgrade to the latest last night and I'll make an attempt this morning and report 

Thank you

**Comment by cambraventures** [comment]
I did the upgrade and tried to scrap the asset it still gave the same error message. Here is the tracebacks:

request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1595, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py", line 21, in execute
    prepare_chart_data(data, filters)
  File "apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py", line 163, in prepare_chart_data
    labels_values_map[belongs_to_month].asset_value += d.get("asset_value")
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

(anonymous) @ request.js:457
socketio_client.js:137 throttled
/api/method/erpnext.assets.doctype.asset.depreciation.scrap_asset:1          Failed to load resource: the server responded with a status of 417 (EXPECTATION FAILED)
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1595, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 254, in scrap_asset
    depreciate_asset(asset, date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 304, in depreciate_asset
    make_depreciation_entry(asset.name, date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 129, in make_depreciation_entry
    je.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 450, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 222, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 258, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 283, in make_autoname
    return series.generate_next_name(doc)
  File "apps/frappe/frappe/model/naming.py", line 68, in generate_next_name
    self.validate()
  File "apps/frappe/frappe/model/naming.py", line 60, in validate
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.model.naming.InvalidNamingSeriesError: Special Characters except "-", "#", ".", "/", "{" and "}" not allowed in naming series

**Comment by anandbaburajan** [comment]
@cambraventures can you share versions of frappe and erpnext?

**Comment by cambraventures** [comment]
ERPNext version: 14.13.0
Frappe: 14.23.0

**Comment by anandbaburajan** [comment]
@cambraventures we released newer versions on Wednesday.

**Comment by cambraventures** [comment]
Ok got it let me try that and see if it corrects the issue thank you

**Comment by cambraventures** [comment]
The update says 13.44 is that correct I have 14.24 already

**Comment by anandbaburajan** [comment]
@cambraventures since you're on v14, the latest versions you need are ERPNext v14.14.0 and Frappe v14.24.0.

**Comment by cambraventures** [comment]
I am up to date on this. Right now I'm running ERPNext 14.14.0 and Frappe 14.24.0 and I'm still running into the same issue

**Comment by anandbaburajan** [comment]
@cambraventures what's the error message now? Should be showing which naming series.

**Comment by cambraventures** [comment]
This is the message I'm receiving when attempting to scrap asset:

![image](https://user-images.githubusercontent.com/117315619/215533176-b3fb3b02-6380-4c8b-bf4d-dd33b683e49b.jpeg)

This is the trace back:
![image](https://user-images.githubusercontent.com/117315619/215533894-04383181-01d3-4673-bd50-fe167bb13af9.jpeg)

**Comment by anandbaburajan** [comment]
@cambraventures single quotes shouldn't be present around the YYYY, as the message suggests.

**Comment by cambraventures** [comment]
None of the assets have names like that the names of the assets I created are the same as the item they're attached to. For example hypertough shelf is the name of the asset, nothing remotely close to the naming series shown in the error message

**Comment by anandbaburajan** [comment]
@cambraventures like I mentioned before, the naming series in the error is of the depreciation entry made (while you tried to scrap the asset). So you need to fix the naming series for depreciation entries.

**Comment by cambraventures** [comment]
I see you've closed this but my question is where in the program do I do this and change the naming series ?

**Comment by cambraventures** [comment]
Never mind I figured it out and adjusted the naming series and it worked thank you for your help on this long ticket
