### ISSUE TITLE
Unable to create payment entry for employee advance

### ISSUE THREAD

**Issue by hadeeld7** [frappe/erpnext#33878]
### Information about bug

Unable to create payment entry for employee advance. 

Documentation reference: https://docs.erpnext.com/docs/v14/user/manual/en/human-resources/employee-advance#employee-advance-via-payment-entry

### Module

accounts

### Version

Frappe - v14.24.0
Erpnext -  v14.4.0 

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1609, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 909, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 906, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 68, in validate
    self.validate_reference_documents()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 309, in validate_reference_documents
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Reference Doctype must be one of Journal Entry
```

**Comment by Nihantra-Patel** [comment]
Hi @hadeeld7,

Everything is working fine. No problems were encountered in the latest versions 14 and 15. Kindly upgrade to version 14 or 15, then refresh and check again.

https://github.com/frappe/erpnext/assets/141945075/96497c0d-5b00-4193-a16d-d9577e4271b2

Thank You!
