### ISSUE TITLE
Fixed Asset Register Crashing

### ISSUE THREAD

**Issue by johnneijzen** [frappe/erpnext#33870]
### Information about bug

I updated ERPnext from v13.28.0 to V13.44.0 no errors show up during migration and i testing all workspace all seem to expect for workspace for assets for some reason Fixed Asset Register is broken i do notice that line is crashing on was added quite recently https://github.com/frappe/erpnext/commit/42fe63da2ce778ee0cd3831ba2f94c34747e1e06. i did tried to manually debugging so far it crashing on this line
![image](https://user-images.githubusercontent.com/1343960/215415858-713c651e-587a-490f-8f97-365f9a0bad55.png)
![image](https://user-images.githubusercontent.com/1343960/215416053-4afb0981-f6ce-4e78-8f3a-9d6f77ec4acc.png)

it also be that finance books is needed in first place but if that is case that i think finance book should mark mandatory so that user cant make that error
![image](https://user-images.githubusercontent.com/1343960/215417034-1a875c86-f15b-4efe-9872-9be578cbe5e7.png)
![image](https://user-images.githubusercontent.com/1343960/215417379-cb1af5e5-01d2-46eb-92db-8f3575f39193.png)

### Module

assets

### Version

Frappe Version: v13.48.0
ERPnext Version: v13.44.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.44.0",
	"frappe": "13.48.0",
	"trinity_erp": "0.0.1"
}
```
### Route
```

```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1462, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 772, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 772, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 89, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 165, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py", line 19, in execute
    data = get_data(filters)
  File "apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py", line 102, in get_data
    asset_value = get_asset_value(asset, filters.finance_book)
  File "apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py", line 133, in get_asset_value
    return frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 472, in get_value
    ret = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 532, in get_values
    out = self._get_value_for_many_names(doctype, filters, fieldname, debug=debug, limit=limit)
  File "apps/frappe/frappe/database/database.py", line 761, in _get_value_for_many_names
    return self.get_all(
  File "apps/frappe/frappe/database/database.py", line 646, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1746, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1718, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 170, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 187, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 223, in prepare_args
    self.build_conditions()
  File "apps/frappe/frappe/model/db_query.py", line 474, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "apps/frappe/frappe/model/db_query.py", line 495, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "apps/frappe/frappe/model/db_query.py", line 580, in prepare_filter_condition
    value = [frappe.db.escape((v or "").strip(), percent=False) for v in values]
  File "apps/frappe/frappe/model/db_query.py", line 580, in <listcomp>
    value = [frappe.db.escape((v or "").strip(), percent=False) for v in values]
AttributeError: 'list' object has no attribute 'strip'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Fixed Asset Register",
		"filters": "{\"status\":\"In Location\",\"filter_based_on\":\"Fiscal Year\",\"date_based_on\":\"Purchase Date\",\"group_by\":\"--Select a group--\",\"is_existing_asset\":0,\"company\":\"TRINITY INSURANCE AND REINSURANCE BROKERS, INC.\",\"from_fiscal_year\":\"2022\",\"to_fiscal_year\":\"2022\",\"from_date\":\"2022-01-30\",\"to_date\":\"2023-01-30\"}",
		"ignore_prepared_report": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'list' object has no attribute 'strip'"
}
```
```

**Comment by johnneijzen** [comment]
https://github.com/frappe/erpnext/pull/33888 okay i see that is getting fixed i will close this once that is merge into version-13

**Comment by johnneijzen** [comment]
Fixed in https://github.com/frappe/erpnext/pull/33890 so closing this issue
