### ISSUE TITLE
Purchase Receipt for Asset with Charges included in Valuation and Total

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#33969]
### Information about bug

1. Create an Asset Category
    2.  Leave _Enable Capital Work in Progress Accounting_ disabled
1. Create an **Item**
    3. Enable _Is Fixed Asset_
5. Create a **Shipping Rule** for $ 10.00 fixed shipping costs
    ```json
    {
      "shipping_rule_type": "Buying",
      "account": "5205 - Freight and Forwarding Charges - COMP",
      "calculate_based_on": "Fixed",
      "shipping_amount": 10.00,
      "conditions": [],
      "countries": []
    }
    ```
6. Create a **Purchase Order**
    1. Add one unit of our item at a rate of $ 100.00
    2. Select the Shipping Rule, which should apply the fixed charge as follows:
        ```json
        {
           "category": "Valuation and Total",
           "add_deduct_tax": "Add",
           "charge_type": "Actual",
           "tax_amount": 10.00,
           "total": 110.00
        }
        ```
8. Create and submit a **Purchase Receipt**

The controller will create only one GL Entry for the freight charges and complain that there is no counter entry. The **Purchase Receipt** cannot be submitted.

Similar issue in **Purchase Invoice**: https://github.com/frappe/erpnext/pull/33092

### Module

stock

### Version

ERPNext: v13.45.0
Frappe Framework: v13.49.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1020, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1009, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 366, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 236, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 71, in make_gl_entries
    make_gl_entries(gl_entries, from_repost=from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 38, in make_gl_entries
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Incorrect number of General Ledger Entries found. You might have selected a wrong Account in the transaction.
```

**Comment by deepeshgarg007** [comment]
@barredterra This was fixed a while back If I am not wrong. Please reopen this if the issue still persists

**Comment by PatrickDEissler** [comment]
This is still an issue on ERPNext: v13.49.14 / Frappe Framework: v13.56.0

**Comment by PatrickDEissler** [comment]
We now updated our customer to V14: 
ERPNext: v14.24.0 (HEAD)
Frappe Framework: v14.36.0 (HEAD)

And the issue still persists.

**Comment by nabinhait** [comment]
I think the issue has been fixed in the latest version 14, closing the issue, please reopen if it still there in v14/v15.
