### ISSUE TITLE
V13.45.1 docker installation with PostgreSQL error for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by skygunner** [frappe/erpnext#33976]
### Information about bug

Installation v13.45.1 using the pwd.yml with 

frappe/erpnext:v13.45.1
PostgreSQL 9.5

Updating DocTypes for erpnext       : [========================================] 100%
create-site exited with code 1

### Module

other

### Version

frappe/erpnext:v13.45.1
PostgreSQL 9.5

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
db              | ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list at character 316
db              | STATEMENT:  select distinct module as module
db              |                               from "tabDocType"
db              |                               where "tabDocType"."name" in ('Salary Slip', 'Employee', 'Expense Claim', 'Leave Application', 'Attendance Request', 'Compensatory Leave Request', 'Employee Tax Exemption Declaration', 'Employee Tax Exemption Proof Submission', 'Timesheet')
db              |
db              |                                order by "tabDocType"."modified" DESC
db              | WARNING:  there is no transaction in progress
create-site     | Traceback (most recent call last):
create-site     |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
create-site     |     return _run_code(code, main_globals, None,
create-site     |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
create-site     |     exec(code, run_globals)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
create-site     |     main()
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
create-site     |     click.Group(commands=commands)(prog_name="bench")
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
create-site     |     return self.main(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 782, in main
create-site     |     rv = self.invoke(ctx)
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
create-site     |     return _process_result(sub_ctx.command.invoke(sub_ctx))
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
create-site     |     return _process_result(sub_ctx.command.invoke(sub_ctx))
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
create-site     |     return ctx.invoke(self.callback, **ctx.params)
create-site     |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
create-site     |     return callback(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 74, in new_site
create-site     |     _new_site(
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 82, in _new_site
create-site     |     install_app(app, verbose=verbose, set_as_patched=not source_sql)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 196, in install_app
create-site     |     frappe.get_attr(after_install)()
create-site     |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 35, in after_install
create-site     |     add_non_standard_user_types()
create-site     |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 209, in add_non_standard_user_types
create-site     |     create_user_type(user_type, data)
create-site     |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 256, in create_user_type
create-site     |     doc.save(ignore_permissions=True)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 312, in save
create-site     |     return self._save(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 334, in _save
create-site     |     return self.insert()
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 263, in insert
create-site     |     self.run_before_save_methods()
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1054, in run_before_save_methods
create-site     |     self.run_method("validate")
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 943, in run_method
create-site     |     out = Document.hook(fn)(self, *args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1264, in composer
create-site     |     return composed(self, method, *args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1246, in runner
create-site     |     add_to_return_value(self, fn(self, *args, **kwargs))
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 940, in fn
create-site     |     return method_object(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user_type/user_type.py", line 19, in validate
create-site     |     self.set_modules()
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user_type/user_type.py", line 48, in set_modules
create-site     |     modules = frappe.get_all(
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1757, in get_all
create-site     |     return get_list(doctype, *args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1729, in get_list
create-site     |     return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 170, in execute
create-site     |     result = self.build_and_run()
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 210, in build_and_run
create-site     |     return frappe.db.sql(
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 120, in sql
create-site     |     return super(PostgresDatabase, self).sql(*args, **kwargs)
create-site     |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 193, in sql
create-site     |     self._cursor.execute(query)
create-site     | psycopg2.errors.InvalidColumnReference: for SELECT DISTINCT, ORDER BY expressions must appear in select list
create-site     | LINE 5:     order by "tabDocType"."modified" DESC
create-site     |                      ^
create-site     |
Updating DocTypes for erpnext       : [========================================] 100%
create-site exited with code 1
```

**Comment by skygunner** [comment]
13.45+mariadb 10.3 does not have this problem.
