### ISSUE TITLE
Work order consumed material: 500, Uncaught Server Exception There was an error building this page

### ISSUE THREAD

**Issue by skygunner** [frappe/erpnext#33974]
### Information about bug

Fresh install. Open Work Order Consumed Materials page, refresh page will give 
500, Uncaught Server Exception There was an error building this page

### Module

manufacturing

### Version

Ecommerce Integrations: v1.14.1 (main)
ERPNext: v14.15.1 (version-14)
Frappe Framework: v14.25.1 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "apps/frappe/frappe/website/path_resolver.py", line 40, in resolve
    endpoint = resolve_path(self.path)
  File "apps/frappe/frappe/website/path_resolver.py", line 145, in resolve_path
    path = resolve_from_map(path)
  File "apps/frappe/frappe/website/path_resolver.py", line 157, in resolve_from_map
    return evaluate_dynamic_routes(rules, path) or path
  File "apps/frappe/frappe/website/router.py", line 71, in evaluate_dynamic_routes
    endpoint, args = urls.match("/" + path)
  File "env/lib/python3.10/site-packages/werkzeug/routing/map.py", line 601, in match
    raise RequestRedirect(
werkzeug.routing.exceptions.RequestRedirect: 308 Permanent Redirect: https://erp.domainame.com/app/report/Work%20Order%20Consumed%20Materials
```

**Comment by skygunner** [comment]
is this a valid bug?

**Comment by thekingchild** [comment]
I am also facing the issue. there is no explanation on how to resolve this issue. Anyone that got it resolve should please help.
