### ISSUE TITLE
PostgreSQL db install reports 'need to add explicit type casts', function if(boolean, numeric, unknown) does not exist

### ISSUE THREAD

**Issue by skygunner** [frappe/erpnext#33972]
### Information about bug

Hi,

I tried to install using the **pwd.yml docker file** with **PostgreSQL** 13.9 or 14.6
However after installation and login, I got this error while clicking some modules in the nav bar like **CRM, stock, buying**.

### Module

stock, buying, CRM

### Version

	"erpnext": "14.15.1",
	"frappe": "14.25.1"

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
{
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}

Error in query:
function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by skygunner** [comment]
### App Versions
```
{
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}
```
### Route
```
Workspaces/Stock
```
### Trackeback
```
Error in query:
function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/buying/report/purchase_order_trends/purchase_order_trends.py", line 15, in execute
    data = get_data(filters, conditions)
  File "apps/erpnext/erpnext/controllers/trends.py", line 192, in get_data
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Purchase Order Trends",
		"filters": "{\"period\":\"Monthly\",\"period_based_on\":\"posting_date\",\"based_on\":\"Item\",\"company\":\"test company\",\"fiscal_year\":\"2022-2023\"}",
		"ignore_prepared_report": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": ""
}
```

**Comment by skygunner** [comment]
with Report TDS Computation Summary

`### App Versions
```
{
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}
```
### Route
```
query-report/TDS Computation Summary
```
### Trackeback
```
Error in query:
function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/buying/report/purchase_order_trends/purchase_order_trends.py", line 15, in execute
    data = get_data(filters, conditions)
  File "apps/erpnext/erpnext/controllers/trends.py", line 192, in get_data
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Purchase Order Trends",
		"filters": "{\"period\":\"Monthly\",\"period_based_on\":\"posting_date\",\"based_on\":\"Item\",\"company\":\"test company\",\"fiscal_year\":\"2022-2023\"}",
		"ignore_prepared_report": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": ""
}
````

**Comment by skygunner** [comment]
`### App Versions
```
{
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}
```
### Route
```
query-report/TDS Payable Monthly
```
### Trackeback
```
Error in query:
function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/buying/report/purchase_order_trends/purchase_order_trends.py", line 15, in execute
    data = get_data(filters, conditions)
  File "apps/erpnext/erpnext/controllers/trends.py", line 192, in get_data
    data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function if(boolean, numeric, unknown) does not exist
LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Purchase Order Trends",
		"filters": "{\"period\":\"Monthly\",\"period_based_on\":\"posting_date\",\"based_on\":\"Item\",\"company\":\"test company\",\"fiscal_year\":\"2022-2023\"}",
		"ignore_prepared_report": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": ""
}
````
