### ISSUE TITLE
TDS Payable Monthly and TDS Computation Summary give pymysql.err.OperationalError: (1054, "Unknown column 'pan' in 'field list'")

### ISSUE THREAD

**Issue by skygunner** [frappe/erpnext#33970]
### Information about bug

Fresh install. 
Open those two reports from the search bar , or refresh after open, will trigger error.  
with or without ecommerce_integrations.
mariadb 10.3/10.6.11/10.9/10.10 / PostgreSQL 13.5/13.9
Both docker install and manual native install have this problem. 

### Module

accounts

### Version

	"ecommerce_integrations": "1.14.1",
	"erpnext": "14.15.1",
	"frappe": "14.25.1"

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"ecommerce_integrations": "1.14.1",
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}
```
### Route
```
query-report/TDS Payable Monthly
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 22, in execute
    res = get_result(
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 37, in get_result
    supplier_map = get_supplier_pan_map()
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 106, in get_supplier_pan_map
    suppliers = frappe.db.get_all(
  File "apps/frappe/frappe/database/database.py", line 723, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1924, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1896, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 172, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 212, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'pan' in 'field list'")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "TDS Payable Monthly",
		"filters": "{\"company\":\"TEST Company\",\"from_date\":\"2023-01-07\",\"to_date\":\"2023-02-07\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'pan' in 'field list'\")"
}
```
```

**Comment by skygunner** [comment]
`
### App Versions
```
{
	"ecommerce_integrations": "1.14.1",
	"erpnext": "14.15.1",
	"frappe": "14.25.1"
}
```
### Route
```
query-report/TDS Computation Summary
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 87, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 68, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/tds_computation_summary/tds_computation_summary.py", line 25, in execute
    res = get_result(
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 37, in get_result
    supplier_map = get_supplier_pan_map()
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 106, in get_supplier_pan_map
    suppliers = frappe.db.get_all(
  File "apps/frappe/frappe/database/database.py", line 723, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1924, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1896, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 172, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 212, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'pan' in 'field list'")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "TDS Computation Summary",
		"filters": "{\"company\":\"TEST Company\",\"from_date\":\"2023-01-07\",\"to_date\":\"2023-02-07\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'pan' in 'field list'\")"
}
```
`

**Comment by skygunner** [comment]
This problem does not happen in V13.45

**Comment by deepeshgarg007** [comment]
@skygunner ERPNext is not fully PostgreSQL supported yet

**Comment by fr8in** [comment]
This is issue is happening in mariadb installation.

**Comment by nvisionitmu** [comment]
Issue happens on Frappe Cloud in v14 as well - even with mariadb
