### ISSUE TITLE
Error when running bench update

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3405]
I get this error when I tried to run bench update

Executing erpnext.patches.v5_0.portal_fixes in erp.agtech.com.sg (f7dccb995c)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 205, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/patches/v5_0/portal_fixes.py", line 3, in execute
    erpnext.setup.install.add_web_forms()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 60, in add_web_forms
    data_import=True)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 120, in import_doc
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 179, in insert
    self._validate()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 300, in _validate
    self._validate_mandatory()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 462, in _validate_mandatory
    raise frappe.MandatoryError(", ".join((each[0] for each in missing)))
frappe.exceptions.MandatoryError: label

**Comment by kodybaker** [comment]
We have this exact same issue.

**Comment by anandpdoshi** [comment]
Can you update and check if this error still exists?

**Comment by kodybaker** [comment]
Just ran bench update

Executing erpnext.patches.v5_0.portal_fixes in site1.local (1bd3e0294d)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 205, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/patches/v5_0/portal_fixes.py", line 3, in execute
    erpnext.setup.install.add_web_forms()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/setup/install.py", line 60, in add_web_forms
    data_import=True)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 120, in import_doc
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 179, in insert
    self._validate()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 300, in _validate
    self._validate_mandatory()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 462, in _validate_mandatory
    raise frappe.MandatoryError(", ".join((each[0] for each in missing)))
frappe.exceptions.MandatoryError: label

**Comment by anandpdoshi** [comment]
Hey @kodybaker. I am not able to reproduce the issue. Have you made any changes in your Frappe repository?

**Comment by justinlusg** [comment]
I have not made any changes to the Frappe repository.. upgrading from 5.0.10

**Comment by anandpdoshi** [comment]
Try this and then run bench update
`bench --force --reload-doc website doctype web_form_field`

**Comment by justinlusg** [comment]
Error: no such option: --reload-doc

**Comment by anandpdoshi** [comment]
oops. Try this:
`bench --force reload-doc website doctype web_form_field`

**Comment by kodybaker** [comment]
This worked for me. 
bench update now works and the site is back up and running.
Thanks!

**Comment by justinlusg** [comment]
ubuntu@ip-172-31-27-142:~$ bench --force reload-doc website doctype web_form_field
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 249, in reload_doc
    frappe.reload_doc(module, doctype, docname, force=context.force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 547, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 37, in reload_doc
    return import_files(module, dt, dn, force=force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 17, in import_files
    return import_file(module, dt, dn, force=force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 22, in import_file
    ret = import_file_by_path(path, force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 93, in import_doc
    doc = frappe.get_doc(docdict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 491, in get_doc
    return frappe.model.document.get_doc(arg1, arg2)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 43, in get_doc
    controller = get_controller(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py", line 22, in get_controller
    module_name, custom = frappe.db.get_value("DocType", doctype, ["module", "custom"]) \
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 396, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug, cache=cache)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 437, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 533, in _get_values_from_table
    conditions, order_by), values, as_dict=as_dict, debug=debug, update=update)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 105, in sql
    self.connect()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 51, in connect
    use_unicode=True, charset='utf8')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 2 must be string, not None

**Comment by nabinhait** [comment]
you need to pass `--site your_site_name`

**Comment by justinlusg** [comment]
Thank you, i managed to update now.. but I have to reload all the 25 customers I'm hosting on my server one by one before i can successfully update..
