### ISSUE TITLE
India Compliance

### ISSUE THREAD

**Issue by momscode** [frappe/erpnext#34100]
### Information about bug

Hello there

We are facing an issue while installing the app "India-Compliance".
it shows the error related to 'supervisorctrl' while restarting the bench.

Any suggestion to fix this

### Module

other

### Version

Frappe Version : v14.23.0
ERPNext Version : v14.13.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
frappe@momssrv4:~/frappe-bench$ bench restart
$ supervisorctl restart frappe:
error: <class 'PermissionError'>, [Errno 13] Permission denied: file: /usr/lib/python3/dist-packages/supervisor/xmlrpc.py line: 560
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/utils.py", line 41, in restart
    Bench(".").reload(web, supervisor, systemd)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 151, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/bench.py", line 315, in restart_supervisor_processes
    failure = bench.run(f"{sudo}supervisorctl restart {group}", _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
```

**Comment by HUMENTH** [comment]
Try Step 19 of this [Installation Guide](https://github.com/HUMENTH/Guide-to-Install-Frappe-ERPNext-in-Ubuntu-22.04-LTS#step-19-if-getting-error-13-on-bench-restart-optional).

**Comment by momscode** [comment]
Thank you 
Will try and update here

**Comment by deepeshgarg007** [comment]
@momscode Please raise this issue on https://github.com/resilient-tech/india-compliance/issues
