### ISSUE TITLE
Communication: Cannot reply Communication. Cannot receive two Communications from the same person.

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#34135]
### Information about bug

Bug 1 - Cannot reply to Communication

When trying to reply to a Communication, the error is prompted: From Full Name is required

Bug 2 - Cannot receive two Communications from the same person

Receiving the first Communication is successful. The same person from the same e-mail sends a second Communication with different subject, the Error log registers pull_from_email_account (1062, \"Duplicate entry 'Name appears here' for key 'sender_full_name'\")

### Module

CRM

### Version

ERPNext: v13.46.1 (version-13)

Frappe Framework: v13.49.2 (version-13)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 144, in execute_job
    method(**kwargs)
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 971, in pull_from_email_account
    email_account.receive()
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 404, in receive
    raise Exception(frappe.as_json(exceptions))
Exception: [
 "Traceback (most recent call last):\n  File \"apps/frappe/frappe/model/base_document.py\", line 411, in db_insert\n    frappe.db.sql(\n  File \"apps/frappe/frappe/database/database.py\", line 187, in sql\n    self._cursor.execute(query, values)\n  File \"env/lib/python3.8/site-packages/pymysql/cursors.py\", line 148, in execute\n    result = self._query(query)\n  File \"env/lib/python3.8/site-packages/pymysql/cursors.py\", line 310, in _query\n    conn.query(q)\n  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 775, in _read_query_result\n    result.read()\n  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File \"env/lib/python3.8/site-packages/pymysql/connections.py\", line 725, in _read_packet\n    packet.raise_for_error()\n  File \"env/lib/python3.8/site-packages/pymysql/protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"env/lib/python3.8/site-packages/pymysql/err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.IntegrityError: (1062, \"Duplicate entry 'Mina Bregman' for key 'sender_full_name'\")\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 371, in receive\n    communication = self.insert_communication(msg, args=args)\n  File \"apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 511, in insert_communication\n    communication.insert(ignore_permissions=True)\n  File \"apps/frappe/frappe/model/document.py\", line 275, in insert\n    self.db_insert()\n  File \"apps/frappe/frappe/model/base_document.py\", line 440, in db_insert\n    self.show_unique_validation_message(e)\n  File \"apps/frappe/frappe/model/base_document.py\", line 500, in show_unique_validation_message\n    raise frappe.UniqueValidationError(self.doctype, self.name, e)\nfrappe.exceptions.UniqueValidationError: ('Communication', 'Mina Bregman', IntegrityError(1062, \"Duplicate entry 'Mina Bregman' for key 'sender_full_name'\"))\n"
]
```

**Comment by Nihantra-Patel** [comment]
Hi @idolaru,

Everything is working fine. No problems were encountered in versions 14 and 15.

Kindly upgrade to version 14 or 15, then refresh and check again.
We no longer provide support for version 13 or older. 

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
