### ISSUE TITLE
pymysql.err.ProgrammingError because of single quote in bank reference (auto reconciliation of a bank transaction)

### ISSUE THREAD

**Issue by vcavel** [frappe/erpnext#34162]
### Information about bug

Hi, I've got the following bug while auto-reconciling bank transactions in the bank reconciliation module :

> pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TIGE FACT 140223'\n\t\torder by posting_date' at line 23")

The reference number of the record is 

> CB VERT'TIGE       FACT 140223

I think that the single quote is the reason for the bug.

### Module

accounts

### Version

"ecommerce_integrations": "1.15.2",
"erpnext": "14.16.1",
"frappe": "14.25.4",
"hiboutik": "1.2.2",
"payments": "0.0.1"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"ecommerce_integrations": "1.15.2",
	"erpnext": "14.16.1",
	"frappe": "14.25.4",
	"hiboutik": "1.2.2",
	"payments": "0.0.1",
	"ubrewery": "0.0.1"
}
```
### Route
```
Form/Bank Reconciliation Tool/Bank Reconciliation Tool
```
### Trackeback
```
Syntax error in query:
SELECT
			(CASE WHEN reference_no=%(reference_no)s THEN 1 ELSE 0 END
			+ CASE WHEN (party_type = %(party_type)s AND party = %(party)s ) THEN 1 ELSE 0  END
			+ 1 ) AS rank,
			'Payment Entry' as doctype,
			name,
			paid_amount,
			reference_no,
			reference_date,
			party,
			party_type,
			posting_date,
			paid_from_account_currency as currency
		FROM
			`tabPayment Entry`
		WHERE
			paid_amount <= %(amount)s
			AND docstatus = 1
			AND payment_type IN (%(payment_type)s, 'Internal Transfer')
			AND coalesce(clearance_date, '') = ""
			AND paid_from = %(bank_account)s
			AND posting_date between '2021-01-01' and '2023-02-20'
			AND reference_no = 'CB VERT'TIGE       FACT 140223'
		order by posting_date {'amount': 24.5, 'payment_type': 'Pay', 'reference_no': "CB VERT'TIGE       FACT 140223", 'party_type': None, 'party': None, 'bank_account': '512002 - Crédit Coopératif - Compte courant - LSS'}
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 279, in auto_reconcile_vouchers
    linked_payments = get_linked_payments(
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 416, in get_linked_payments
    matching = check_matching(
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 468, in check_matching
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TIGE       FACT 140223'\n\t\torder by posting_date' at line 23")
```

**Comment by Nihantra-Patel** [comment]
Hi @vcavel,

The error you're encountering seems to be related to the SQL syntax. Specifically, the issue is with the `reference_no` value in the WHERE clause which contains an apostrophe (`'`) that's not properly escaped.

Here's the problematic part of your query:

```sql
AND reference_no = 'CB VERT'TIGE       FACT 140223'
```

As you can see, the value `'CB VERT'TIGE       FACT 140223'` contains an apostrophe (`'`) within it, which is causing the syntax error.

To fix this issue, you need to properly escape the apostrophe within the `reference_no` value. One common method is by doubling the apostrophe, like this:

```sql
AND reference_no = 'CB VERT''TIGE       FACT 140223'
```


It's not a bug, issue is in the reference_no

Thank You!
