### ISSUE TITLE
IndexError: list index out of range on restoring a scrapped asset

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34234]
### Information about bug

Scrap Asset
Then try to Restore the Asset

### Module

assets

### Version

ERPNext: v14.17.1 (HEAD)
Frappe Framework: v14.26.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 286, in restore_asset
    reverse_depreciation_entry_made_after_disposal(asset, asset.disposal_date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 331, in reverse_depreciation_entry_made_after_disposal
    finance_book = asset.get("schedules")[0].get("finance_book")
IndexError: list index out of range
```

**Comment by anandbaburajan** [comment]
@muchai can you share the asset's details in JSON?

**Comment by muchai** [comment]
Please let me close this one. Tested with another case, and it worked.
