### ISSUE TITLE
error while enter items "urllib.error.URLError:"

### ISSUE THREAD

**Issue by waseemaj98** [frappe/erpnext#34297]
### Information about bug

![image_2023-03-04_105243397](https://user-images.githubusercontent.com/46657846/222886556-f1aaadd6-8c8d-466a-ab4a-1cff0d3a1c1b.png)

### Module

stock, buying, selling, ecommerce

### App Versions
```
{
	"ecommerce_integrations": "1.13.1",
	"erpnext": "14.10.0",
	"frappe": "14.18.1",
	"hrms": "1.0.0",
	"payments": "0.0.1"
}
```

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### Route

Form/Item/new-item-1
```
### Trackeback
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1587, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 195, in insert
    return insert_doc(doc).as_dict()
  File "apps/frappe/frappe/client.py", line 459, in insert_doc
    return frappe.get_doc(doc).insert()
  File "apps/frappe/frappe/model/document.py", line 274, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 907, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1256, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1577, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1319, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 7, in <module>
    from shopify.resources import Product, Variant
  File "env/lib/python3.10/site-packages/shopify/__init__.py", line 2, in <module>
    from shopify.session import Session, ValidationException
  File "env/lib/python3.10/site-packages/shopify/session.py", line 12, in <module>
    from shopify.api_version import ApiVersion, Release, Unstable
  File "env/lib/python3.10/site-packages/shopify/api_version.py", line 86, in <module>
    ApiVersion.define_known_versions()
  File "env/lib/python3.10/site-packages/shopify/api_version.py", line 28, in define_known_versions
    req = request.urlopen("https://app.shopify.com/services/apis.json")
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Item\",\"name\":\"new-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"STO-ITEM-.YYYY.-\",\"stock_uom\":\"Nos\",\"disabled\":0,\"allow_alternative_item\":0,\"is_stock_item\":1,\"has_variants\":0,\"include_item_in_manufacturing\":1,\"is_fixed_asset\":0,\"auto_create_assets\":0,\"is_grouped_asset\":0,\"end_of_life\":\"2099-12-31\",\"default_material_request_type\":\"Purchase\",\"valuation_method\":\"\",\"allow_negative_stock\":0,\"has_batch_no\":0,\"create_new_batch\":0,\"has_expiry_date\":0,\"retain_sample\":0,\"has_serial_no\":0,\"variant_based_on\":\"Item Attribute\",\"min_order_qty\":0,\"is_purchase_item\":1,\"is_customer_provided_item\":0,\"delivered_by_supplier\":0,\"enable_deferred_expense\":0,\"country_of_origin\":\"Libya\",\"grant_commission\":1,\"is_sales_item\":1,\"enable_deferred_revenue\":0,\"inspection_required_before_purchase\":0,\"inspection_required_before_delivery\":0,\"is_sub_contracted_item\":0,\"published_in_website\":0,\"__run_link_triggers\":1,\"item_template\":\"\",\"item_code\":\"1233\",\"item_name\":\"test\",\"item_group\":\"Consumable\",\"create_variant\":0,\"opening_stock\":0,\"standard_rate\":0}"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.insert"
}
```
### Response Data
```
{
	"exception": "urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>"
}
```
```

**Comment by deepeshgarg007** [comment]
The error seems to be related to the e-commerce app, please raise your issue on https://github.com/frappe/ecommerce_integrations/issues

**Comment by sohailamar** [comment]
Hi @deepeshgarg007 
Any update on this issue? As I am unable to create assets on my system
