### ISSUE TITLE
Purchase Invoice: setting negative qty in items table using custom script

### ISSUE THREAD

**Issue by KishanPanchal25** [frappe/erpnext#34601]
### Information about bug

In purchase invoice, When setting negative qty in items table by creating new raw using custom script 
getting this error 

"For an item, quantity must be negative number item name"

Is return is set to 1,
Naming series is set to RET---
I have checked the manual entry which works the same.
I have matched the json of both entries manual and custom script they are not different 

When debugging the issue it turns out even when the value is set to -10 or any value < 0 
the status updater -> validate_qty receives qty = 1 only

when the qty is changed to +10 or any value >0 it sets that positive value to qty.

here is the code which is creating the row and setting those values

`frappe.call({
                            "method": "frappe.client.get",
                            "args": {
                                "doctype": "Item",
                                "filters": {
                                    "item_code": d.item_code
                                }
                            },
                            "callback": function(response) {
                                var item = response.message;
                                var item_row = cur_frm.add_child("items");
                                // item_row.item_code = item.item_code;
                                // item_row.qty = -10;
                                item_row.item_code = item_row.item_code;
                                // cur_frm.script_manager.trigger("items", "validate");
                                item_row.item_name = item_row.item_name;
                                item_row.qty = parseInt(d.count) ;
                                item_row.received_qty = parseInt(d.count) ;
                                item_row.uom = item.purchase_uom;
                                item_row.conversion_factor = item_row.uoms[1].conversion_factor;
                                item_row.stock_qty = item_row.uoms[1].conversion_factor * d.count * -1;
                                item_row.stock_uom = item_row.stock_uom;
                                // item_row.rate = 0;
                                // item_row.amount = 0;
                                // item_row.base_rate = 0; 
                                // item_row.base_amount = 0;
                                cur_frm.refresh_field("items");
                            }
                        });`
                        
                        Here d is actually a row from another table from which we are copying the values

### Module

accounts

### Version

ERPNext: v14.19.0 (version-14)

Frappe Framework: v14.29.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:457 
        
       Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 91, in validate
    super(PurchaseInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 52, in validate
    super(SubcontractingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 184, in validate
    self.validate_qty()
  File "apps/erpnext/erpnext/controllers/status_updater.py", line 234, in validate_qty
    frappe.throw(_(f"For an item, quantity must be negative number  :::   {d.item_code}  :::   which is :::  {d.qty}  :::"))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: For an item, quantity must be negative number
```

**Comment by deepeshgarg007** [comment]
@KishanPanchal25 You are calling validate method specifically here, just try and save the doc, the validation is getting called before the `qty` is updated. Doesn't look like a product bug
