### ISSUE TITLE
Adding student is causing sql error

### ISSUE THREAD

**Issue by komelb** [frappe/erpnext#34668]
### Information about bug

Ubuntu 22.04
ERPNext 14
Bench 5.0.0

In the education module, I was simply trying to add new student and I got this

### Module

education

### Version

education 0.0.1
erpnext 14.x.x-develop
frappe 15.x.x-develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"education": "0.0.1",
	"erpnext": "14.0.0-dev",
	"frappe": "15.0.0-dev"
}
```
### Route
```
Form/Student/new-student-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 53, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1591, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 34, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 316, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 338, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 269, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1061, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1280, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1262, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/education/education/education/doctype/student/student.py", line 19, in validate
    self.validate_user()
  File "apps/education/education/education/doctype/student/student.py", line 68, in validate_user
    student_user.add_roles("Student")
  File "apps/frappe/frappe/core/doctype/user/user.py", line 497, in add_roles
    self.save()
  File "apps/frappe/frappe/model/document.py", line 316, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 338, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 264, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 462, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1280, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1262, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 49, in autoname
    self.email = self.email.strip().lower()
AttributeError: 'NoneType' object has no attribute 'strip'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Student\",\"name\":\"new-student-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enabled\":1,\"naming_series\":\"EDU-STU-.YYYY.-\",\"joining_date\":\"2023-03-30\",\"blood_group\":\"\",\"country\":\"Iran\",\"first_name\":\"Mir Jaweed\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360050120392564650711": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 795,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'strip'"
}
```
```

**Comment by rehanrehman389** [comment]
#https://github.com/frappe/education/pull/117

**Comment by Nihantra-Patel** [comment]
lots of functionality has been changed so please test the new https://github.com/frappe/education.

And if there is any error then raise the issue on https://github.com/frappe/education/issues
