### ISSUE TITLE
Dead Code in Ecommerce Shopping Cart causes Error [v14.20.0]

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#34673]
### Information about bug

Please check file erpnext/e_commerce/shopping_cart/cart.py line 632:
rule_label_map = frappe.db.get_values("Shipping Rule", shipping_rules, "label")

The variable "rule_label_map" is never used in method "get_applicable_shipping_rules" and hence is dead code that should be removed.

Actually the db request even causes an error in my code (see stack trace below).
 
Everything works just fine if I comment out line 632.

### Module

ecommerce

### Version

Frappe Version: v14.30.0
ERPNext v14.20.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 225, in run_pymodule_method
    return method(self.context)
  File "apps/erpnext/erpnext/templates/pages/cart.py", line 11, in get_context
    context.update(get_cart_quotation())
  File "apps/erpnext/erpnext/e_commerce/shopping_cart/cart.py", line 51, in get_cart_quotation
    "shipping_rules": get_applicable_shipping_rules(party),
  File "apps/erpnext/erpnext/e_commerce/shopping_cart/cart.py", line 632, in get_applicable_shipping_rules
    rule_label_map = frappe.db.get_values("Shipping Rule", shipping_rules, "label")
  File "apps/frappe/frappe/database/database.py", line 570, in get_values
    out = self._get_value_for_many_names(
  File "apps/frappe/frappe/database/database.py", line 840, in _get_value_for_many_names
    return self.get_all(
  File "apps/frappe/frappe/database/database.py", line 724, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1924, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1896, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 202, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 217, in build_and_run
    args = self.prepare_args()
  File "apps/frappe/frappe/model/db_query.py", line 252, in prepare_args
    self.parse_args()
  File "apps/frappe/frappe/model/db_query.py", line 374, in parse_args
    filters = json.loads(filters)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ophl55** [comment]
Can someone please have a look?
The dead code still persists in ERPNext v14.38.0.

It is just one line.

File: erpnext/e_commerce/shopping_cart/cart.py
Line: 637 (rule_label_map = frappe.db.get_values("Shipping Rule", shipping_rules, "label"))


```
def get_applicable_shipping_rules(party=None, quotation=None):
	shipping_rules = get_shipping_rules(quotation)

	if shipping_rules:
		rule_label_map = frappe.db.get_values("Shipping Rule", shipping_rules, "label")     # DEAD CODE: SHOULD BE REMOVED
		# we need this in sorted order as per the position of the rule in the settings page
		return [[rule, rule] for rule in shipping_rules]
```

**Comment by ophl55** [comment]
@git-avc @viralkansodiya @rohitwaghchaure @ankush @trustedcomputer @s-aga-r 

Can someone of you guys maybe have a quick look and evaluate the issue? It is just a tiny change and should be fixed in no time.

Many thanks in advance. Let me know if I can support in any way.

**Comment by ophl55** [comment]
@viralkansodiya Thank you for having a look and your pull request! :)

**Comment by ophl55** [comment]
Closed by https://github.com/frappe/erpnext/pull/37001
