### ISSUE TITLE
Sure, here's a sample GitHub issue that you can use to report the error:  Issue: UnboundLocalError when clicking "Get Outstanding Invoice" button in Payment Entry

### ISSUE THREAD

**Issue by osama1998H** [frappe/erpnext#34767]
### Description
When I click on the "Get Outstanding Invoice" button in the Payment Entry form, I get an UnboundLocalError with the following message:

`UnboundLocalError: local variable 'voucher_type' referenced before assignment`

This error prevents me from retrieving outstanding invoices for payment.

### **Steps to reproduce**

1. Log in to the ERPNext instance.
2. Go to the Payment Entry form.
3. Click on the "Get Outstanding Invoice" button.

### **Expected behavior**
I expect the outstanding invoices to be displayed so that I can select the ones to pay.

### **Actual behavior**
I get an UnboundLocalError with the message "local variable 'voucher_type' referenced before assignment".

### **Reproducibility**
Always

### **Additional information**
I've checked the code, and it seems that the voucher_type variable is not properly assigned before it is referenced. This causes the UnboundLocalError. Can you please investigate this issue and provide a fix? Thank you!

### Module

education

### **Environment**

- Frappe Chat: v0.0.1 (HEAD)
- Education: v0.0.1 (HEAD)
- ERPNext: v14.17.0 (HEAD)
- Erpnext Telegram Integration: v1.2.0 (HEAD)
- Frappe Framework: v14.26.0 (HEAD)
- Frappe HR: v14.0.3 (HEAD)
- Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"education": "0.0.1",
	"erpnext": "14.17.0",
	"erpnext_telegram_integration": "1.2.0",
	"frappe": "14.26.0",
	"hrms": "14.0.3",
	"payments": "0.0.1"
}
```
### Route
```
Form/Payment Entry/new-payment-entry-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1271, in get_outstanding_reference_documents
    orders_to_be_billed = get_orders_to_be_billed(
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1381, in get_orders_to_be_billed
    if voucher_type:
UnboundLocalError: local variable 'voucher_type' referenced before assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"posting_date\":\"2022-12-18\",\"company\":\"RTC Mansour College\",\"party_type\":\"Student\",\"payment_type\":\"Receive\",\"party\":\"EDU-STU-2023-00067\",\"party_account\":\"1614 - مدينون قطاع خاص - RMC\",\"from_posting_date\":\"2023-03-07\",\"to_posting_date\":\"2023-04-06\",\"outstanding_amt_greater_than\":0,\"outstanding_amt_less_than\":0,\"allocate_payment_amount\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_outstanding_reference_documents"
}
```
### Response Data
```
{
	"exception": "UnboundLocalError: local variable 'voucher_type' referenced before assignment"
}
```
```

**Comment by ankush** [comment]
what is party type on document? is it student?

**Comment by osama1998H** [comment]
@ankush yes it's student
