### ISSUE TITLE
Can not find any doctype connections

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#34826]
### Information about bug

![err01](https://user-images.githubusercontent.com/93484850/231335575-a91b5792-f760-4e22-907d-21774f73e52b.png)

### Module

accounts, stock, buying, selling

### Version

Frappe : 13.53
Erpnext : 13.49.12

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
grid.js:983 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'label')
    at Grid.update_docfield_property (grid.js:983:69)
    at String.<anonymous> (form.js:1310:37)
    at Function.each (jquery.min.js:2:2911)
    at frappe.ui.form.Form.set_currency_labels (form.js:1308:5)
    at init.update_item_grid_labels (transaction.js:1400:12)
    at init.change_grid_labels (transaction.js:1359:8)
    at init.set_dynamic_labels [as _super] (transaction.js:1303:8)
    at init.set_dynamic_labels (sales_order__js:655:8)
    at init.set_dynamic_labels (class.js:53:18)
    at init.refresh (transaction.js:341:8)
```

**Comment by maveezmh** [comment]
same issue here... unable to create any connecting documents. 

no option to create sales order from quotation
no option to create sales invoice from sales order 
so on

**Comment by maveezmh** [comment]
@deepeshgarg007
