### ISSUE TITLE
Cannot set properties of undefined (setting 'label') - missing create button on sales order

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34829]
### Information about bug

Affects users trying to create a delivery note from the sales order create button.

The create button is not visible.
![image](https://user-images.githubusercontent.com/1822868/231372906-b0cd1ab8-a15c-4268-aa46-154f7debebcf.png)

### Module

stock

### Version

ERPNext: v14.21.0 (HEAD)
Frappe Framework: v14.31.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Cannot set properties of undefined (setting 'label')
    at Ft.update_docfield_property (grid.js:1192:69)
    at String.<anonymous> (form.js:1462:37)
    at Function.each (jquery.js:391:19)
    at frappe.ui.form.Form.set_currency_labels (form.js:1460:5)
    at frappe.ui.form.Controller.update_item_grid_labels (transaction.js:1295:12)
    at frappe.ui.form.Controller.change_grid_labels (transaction.js:1254:8)
    at frappe.ui.form.Controller.set_dynamic_labels (transaction.js:1198:8)
    at frappe.ui.form.Controller.set_dynamic_labels (sales_order__js:646:9)
    at frappe.ui.form.Controller.refresh (transaction.js:341:8)
    at frappe.ui.form.Controller.refresh (sales_order__js:401:9)
```

**Comment by dineshpanchal93** [comment]
I face the same issue, Kindly update again your ERP will resolve the issue.

Some js file may not migrated

**Comment by muchai** [comment]
Fixed here. https://github.com/frappe/frappe/pull/20658
