### ISSUE TITLE
‘>’ not supported between instances of ‘datetime.datetime’ and ‘str’

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#34859]
### Information about bug

Goal:
To extend my existing workflow for Material Request.
I wanted to enable a another  state, if an existing state is active for more than 5 days

What I did:
Build a standard workflow : Draft > Pending Approval by Stock Manager. This works fine.
Then I wanted to add the example code that is visible in the row of the Transition Table in Workflow.

This code is:

> doc.creation > frappe.utils.add_to_date(frappe.utils.now_datetime(), days=-5, as_string=True, as_datetime=True)

Then I get the error:

> "TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'"

I had a look at the field description of "creation" in `tabMaterial Request`; it is of type datetime,
Clearly there is a mismatch between doc.creation and the return result of add_to_date

Desired outcome:
No error.

request .
If the example code could please be updated. Often, people that don't have strong experience in python , rely on
example code to get them going.

I can contribute the following.
Someone in the community has tried to assist me. I have also done some research and found this URL.

> https://github.com/frappe/frappe/blob/develop/frappe/utils/data.py

And on line 196 I found this ....

> @typing.overload
def add_to_date(
	date,
	years=0,
	months=0,
	weeks=0,
	days=0,
	hours=0,
	minutes=0,
	seconds=0,
	as_string: Literal[False] = False,
	as_datetime: Literal[True] = True,
) -> datetime.datetime:

This seem to imply that , if I set as_string=False , the add_to_date should return a type "datetime"

So I replaced the conditional code with

> doc.creation > frappe.utils.add_to_date(frappe.utils.now_datetime(), days=-5, as_string=False, as_datetime=True)

But I still get the same error.

### Module

other

### Version

	"erpnext": "13.48.1",
	"frappe": "13.49.3"
}

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### Trackeback

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/workflow.py", line 73, in get_transitions
    if not is_transition_condition_satisfied(transition, doc):
  File "apps/frappe/frappe/model/workflow.py", line 100, in is_transition_condition_satisfied
    return frappe.safe_eval(
  File "apps/frappe/frappe/__init__.py", line 2119, in safe_eval
    return eval(code, eval_globals, eval_locals)
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
```

**Comment by willspenc** [comment]
I have found a solution that will get me going,but my request remains. If the example code could be updated please.

Here is my code..

> frappe.utils.add_to_date(doc.creation, days=0, as_string=True, as_datetime=True) < frappe.utils.add_to_date(frappe.utils.now_datetime(), days=-5, as_string=True, as_datetime=True)

**Comment by phot0n** [comment]
probably creation needs to be casted before evaluation

**Comment by willspenc** [comment]
How can I do that in the python-entry box for workflow?
