### ISSUE TITLE
Error while fetching Emails (EmailAccount.receive and pull_from_email_account)

### ISSUE THREAD

**Issue by ROBJkE** [frappe/erpnext#34861]
### Information about bug

Some Emails can not be fetched by ERPNext and the errors `EmailAccount.receive` and `pull_from_email_account` show up in the protocol.
In general the Mail fetching works but somehow some Mails can not be fetched.

### Module

accounts

### Version

Frappe Version: v14.14.3
ERPNext Version: v14.6.0

### Installation method

docker

#### EmailAccount.receive

```shell
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 468, in receive
    communication = mail.process()
      self = <EmailAccount: Support>
      exceptions = []
      inbound_mails = [<frappe.email.receive.InboundMail object at 0x7f0a13db0910>, <frappe.email.receive.InboundMail object at 0x7f0a13db0b80>]
      mail = <frappe.email.receive.InboundMail object at 0x7f0a13db0910>
  File "apps/frappe/frappe/email/receive.py", line 697, in process
    return self._build_communication_doc()
      self = <frappe.email.receive.InboundMail object at 0x7f0a13db0910>
      communication = None
  File "apps/frappe/frappe/email/receive.py", line 728, in _build_communication_doc
    communication.insert(ignore_permissions=True)
      self = <frappe.email.receive.InboundMail object at 0x7f0a13db0910>
      data = {'subject': 'Re: Problem mit Elysium Slider nach Umzug', 'content': '\n\n\n\nHallo Robert,\n<div><br>\n</div>\n<div>Folgende Fehlermeldung erhalten wir, wenn wir den Prozess manuell anstoßen:</div>\n<div>request.ERROR: Uncaught PHP\xa0Exception\xa0Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\Exception\\UnmappedFieldException:\xa0"Field "id" in entity "media" was not found."\xa0at /html/shopware/vendor/shopware/core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php\n line\xa0220\xa0{"exception":"[object] (Shopware\\\\Core\\\\Framework\\\\DataAbstractionLayer\\\\Dbal\\\\Exception\\\\UnmappedFieldException(code: 0): Field \\"id\\" in entity \\"media\\" was not found. at /html/shopware/vendor/shopware/core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php:220)"}\n []</div>\n<div><br>\n</div>\n<div>Da der Fehler nur im Produktivsystem auftritt, würde ich ungern das Plugin einfach deaktivieren. Wenn du sagst, es ist unerlässlich, muss ich mir was...
      append_to = 'Communication'
      communication = <Communication: 37989b3a61>
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self.run_post_save_methods()
      self = <Communication: 37989b3a61>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 1076, in run_post_save_methods
    self.run_method("on_update")
      self = <Communication: 37989b3a61>
  File "apps/frappe/frappe/model/document.py", line 908, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <Communication: 37989b3a61>
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f0a12d8b760>
      method = 'on_update'
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
      self = <Communication: 37989b3a61>
      args = ()
      kwargs = {}
      hooks = [<function on_communication_update at 0x7f0a12fad7e0>, <function set_first_response_time at 0x7f0a1303e0e0>, <function clear_doctype_notifications at 0x7f0a16a67880>, <function update_feed at 0x7f0a12faff40>, <function process_workflow_actions at 0x7f0a12e00ca0>, <function apply at 0x7f0a1340f490>, <function attach_files_to_document at 0x7f0a13499630>, <function notify_consumers at 0x7f0a12faf130>, <function update_due_date at 0x7f0a1340f520>, <function apply_permissions_for_non_standard_user_type at 0x7f0a12e297e0>]
      method = 'on_update'
      doc_events = {'*': {'after_insert': ['frappe.event_streaming.doctype.event_update_log.event_update_log.notify_consumers'], 'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.core.doctype.activity_log.feed.update_feed', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.event_streaming.doctype.event_update_log.event_update_log.notify_consumers', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.event_streaming.doctype.event_update_log.event_update_log.notify_co...
      handler = 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f0a12fae0e0>
      compose = <function Document.hook.<locals>.compose at 0x7f0a12fae200>
      f = <function Document.run_method.<locals>.fn at 0x7f0a12d8b760>
  File "apps/frappe/frappe/model/document.py", line 1244, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
      self = <Communication: 37989b3a61>
      method = 'on_update'
      args = ()
      kwargs = {}
      f = <function on_communication_update at 0x7f0a12fad7e0>
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f0a12fae170>
      fn = <function Document.run_method.<locals>.fn at 0x7f0a12d8b760>
      hooks = (<function on_communication_update at 0x7f0a12fad7e0>, <function set_first_response_time at 0x7f0a1303e0e0>, <function clear_doctype_notifications at 0x7f0a16a67880>, <function update_feed at 0x7f0a12faff40>, <function process_workflow_actions at 0x7f0a12e00ca0>, <function apply at 0x7f0a1340f490>, <function attach_files_to_document at 0x7f0a13499630>, <function notify_consumers at 0x7f0a12faf130>, <function update_due_date at 0x7f0a1340f520>, <function apply_permissions_for_non_standard_user_type at 0x7f0a12e297e0>)
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 813, in on_communication_update
    update_response_and_resolution_metrics(parent, for_resolution)
      doc = <Communication: 37989b3a61>
      status = 'on_update'
      parent = <Issue: ISS-2023-00003>
      for_resolution = None
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 592, in update_response_and_resolution_metrics
    priority = get_response_and_resolution_duration(doc)
      doc = <Issue: ISS-2023-00003>
      apply_sla_for_resolution = None
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 729, in get_response_and_resolution_duration
    sla = frappe.get_doc("Service Level Agreement", doc.service_level_agreement)
      doc = <Issue: ISS-2023-00003>
  File "apps/frappe/frappe/__init__.py", line 1176, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ('Service Level Agreement', None)
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
      args = ('Service Level Agreement', None)
      kwargs = {}
      doctype = 'Service Level Agreement'
      controller = <class 'erpnext.support.doctype.service_level_agreement.service_level_agreement.ServiceLevelAgreement'>
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
      self = <ServiceLevelAgreement: unsaved>
      args = ('Service Level Agreement', None)
      kwargs = {}
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
      self = <ServiceLevelAgreement: unsaved>
      d = None
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
      msg = 'Service Level Agreement None not found'
      exc = <class 'frappe.exceptions.DoesNotExistError'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      sys = <module 'sys' (built-in)>
      out = {'message': 'Service Level Agreement None not found', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1}
      _strip_html_tags = <functools._lru_cache_wrapper object at 0x7f0a12c541a0>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7f0a12e29a20>
      inspect = <module 'inspect' from '/usr/local/lib/python3.10/inspect.py'>
      msg = 'Service Level Agreement None not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
      strip_html_tags = <function strip_html_tags at 0x7f0a173b6320>
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
      inspect = <module 'inspect' from '/usr/local/lib/python3.10/inspect.py'>
      msg = 'Service Level Agreement None not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
frappe.exceptions.DoesNotExistError: Service Level Agreement None not found
```

#### pull_from_email_account

```shell
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 159, in execute_job
    method(**kwargs)
      site = 'erp.blurcreative.de'
      method = <function pull_from_email_account at 0x7f0a134c25f0>
      event = 'all'
      job_name = 'pull_from_email_account|Support'
      kwargs = {'email_account': 'Support'}
      user = 'Administrator'
      is_async = True
      retry = 0
      method_name = 'pull_from_email_account'
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 825, in pull_from_email_account
    email_account.receive()
      email_account = <EmailAccount: Support>
  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 496, in receive
    raise Exception(frappe.as_json(exceptions))
      self = <EmailAccount: Support>
      exceptions = ['Traceback (most recent call last):\n  File "apps/frappe/frappe/email/doctype/email_account/email_account.py", line 468, in receive\n    communication = mail.process()\n  File "apps/frappe/frappe/email/receive.py", line 697, in process\n    return self._build_communication_doc()\n  File "apps/frappe/frappe/email/receive.py", line 728, in _build_communication_doc\n    communication.insert(ignore_permissions=True)\n  File "apps/frappe/frappe/model/document.py", line 283, in insert\n    self.run_post_save_methods()\n  File "apps/frappe/frappe/model/document.py", line 1076, in run_post_save_methods\n    self.run_method("on_update")\n  File "apps/frappe/frappe/model/document.py", line 908, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File "apps/frappe/frappe/model/document.py", line 1260, in composer\n    return composed(self, method, *args, **kwargs)\n  File "apps/frappe/frappe/model/document.py", line 1244, in runner\n    add_to_return_value(self, f(self, method, ...
      inbound_mails = [<frappe.email.receive.InboundMail object at 0x7f0a13db0910>, <frappe.email.receive.InboundMail object at 0x7f0a13db0b80>]
      mail = <frappe.email.receive.InboundMail object at 0x7f0a13db0b80>
      communication = <Communication: 2890e76dbb>
builtins.Exception: [
 "Traceback (most recent call last):\n  File \"apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 468, in receive\n    communication = mail.process()\n  File \"apps/frappe/frappe/email/receive.py\", line 697, in process\n    return self._build_communication_doc()\n  File \"apps/frappe/frappe/email/receive.py\", line 728, in _build_communication_doc\n    communication.insert(ignore_permissions=True)\n  File \"apps/frappe/frappe/model/document.py\", line 283, in insert\n    self.run_post_save_methods()\n  File \"apps/frappe/frappe/model/document.py\", line 1076, in run_post_save_methods\n    self.run_method(\"on_update\")\n  File \"apps/frappe/frappe/model/document.py\", line 908, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"apps/frappe/frappe/model/document.py\", line 1260, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"apps/frappe/frappe/model/document.py\", line 1244, in runner\n    add_to_return_value(self, f(self, method, *args, **kwargs))\n  File \"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\", line 813, in on_communication_update\n    update_response_and_resolution_metrics(parent, for_resolution)\n  File \"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\", line 592, in update_response_and_resolution_metrics\n    priority = get_response_and_resolution_duration(doc)\n  File \"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\", line 729, in get_response_and_resolution_duration\n    sla = frappe.get_doc(\"Service Level Agreement\", doc.service_level_agreement)\n  File \"apps/frappe/frappe/__init__.py\", line 1176, in get_doc\n    doc = frappe.model.document.get_doc(*args, **kwargs)\n  File \"apps/frappe/frappe/model/document.py\", line 74, in get_doc\n    return controller(*args, **kwargs)\n  File \"apps/frappe/frappe/model/document.py\", line 106, in __init__\n    self.load_from_db()\n  File \"apps/frappe/frappe/model/document.py\", line 149, in load_from_db\n    frappe.throw(\n  File \"apps/frappe/frappe/__init__.py\", line 522, in throw\n    msgprint(\n  File \"apps/frappe/frappe/__init__.py\", line 490, in msgprint\n    _raise_exception()\n  File \"apps/frappe/frappe/__init__.py\", line 442, in _raise_exception\n    raise raise_exception(msg)\nfrappe.exceptions.DoesNotExistError: Service Level Agreement None not found\n"
]
```

**Comment by ROBJkE** [comment]
Found the Problem.
I created a Support case from Email A but if the Customer replies the Email B creates the Error.
This is because the Email Account (Email-Konto in Screenshot) was not set. After setting the right Email-Account and fetching Email B again it works and the Email automaticly assigned to the Support case.

![image](https://user-images.githubusercontent.com/26817419/232057179-7b03b618-a356-48e6-9971-d65570f681ea.png)
