### ISSUE TITLE
Not able to rename the company. this is a second error. Property management is not installed but still getting error

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#34913]
### Information about bug

![image](https://user-images.githubusercontent.com/28171912/232846272-d5546f66-dace-4851-b144-d129161b4991.png)

### Module

accounts

### Version

ERPNext: v13.49.12 (HEAD)
Frappe Framework: v13.53.2 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.49.12",
	"frappe": "13.53.2"
}
```
### Route
```
Form/Company/UNIDOW Advisory Services LLP
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 36, in update_document_title
    docname = rename_doc(doctype=doctype, old=docname, new=new_name, merge=merge)
  File "apps/frappe/frappe/model/rename_doc.py", line 93, in rename_doc
    update_link_field_values(link_fields, old, new, doctype)
  File "apps/frappe/frappe/model/rename_doc.py", line 328, in update_link_field_values
    single_doc = frappe.get_doc(field["parent"])
  File "apps/frappe/frappe/__init__.py", line 1079, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 77, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 82, in get_controller
    site_controllers[doctype] = _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 64, in _get_controller
    module = load_doctype_module(doctype, module_name)
  File "apps/frappe/frappe/modules/utils.py", line 235, in load_doctype_module
    app = get_module_app(module)
  File "apps/frappe/frappe/modules/utils.py", line 263, in get_module_app
    return frappe.local.module_app[scrub(module)]
KeyError: 'property_management_solution'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Company",
		"docname": "UNIDOW Advisory Services LLP",
		"new_name": "UNIDOW India Services LLP",
		"title_field": "",
		"merge": 0,
		"freeze": true,
		"freeze_message": "Updating related fields..."
	},
	"freeze": true,
	"freeze_message": "Updating related fields...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.rename_doc.update_document_title"
}
```
### Response Data
```
{
	"exception": "KeyError: 'property_management_solution'"
}
```
```

**Comment by deepeshgarg007** [comment]
@unidow Looks like you have force removed some module and that is causing this issue. Doesn't look like a core bug. Closing this issue

**Comment by unidow** [comment]
@deepeshgarg007  could you confirm how we are able to force remove the module or app? Can I have an explanation? Why don't you provide a fix or solution which we can understand???

**Comment by unidow** [comment]
We can simply click on a button to install or remove the app. there is no option given to "FORCE REMOVE"
