### ISSUE TITLE
Erpnext Help page error Traceback

### ISSUE THREAD

**Issue by boubafof** [frappe/erpnext#35005]
### Information about bug

My erpnext help page show error, and i have no way to get it back. no update has been done, and nothing 

### Module

portal, other

### Version

frappe version 13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/context.py", line 61, in update_controller_context
    ret = module.get_context(context)
  File "apps/erpnext/erpnext/templates/pages/help.py", line 13, in get_context
    sections = json.loads(s.get_started_sections)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/render.py", line 60, in render
    data = render_page_by_language(path)
  File "apps/frappe/frappe/website/render.py", line 210, in render_page_by_language
    return render_page(path)
  File "apps/frappe/frappe/website/render.py", line 227, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 235, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 251, in build_page
    context = get_context(path)
  File "apps/frappe/frappe/website/context.py", line 32, in get_context
    context = build_context(context)
  File "apps/frappe/frappe/website/context.py", line 113, in build_context
    update_controller_context(context, context.controller)
  File "apps/frappe/frappe/website/context.py", line 70, in update_controller_context
    frappe.errprint(frappe.utils.get_traceback())
  File "apps/frappe/frappe/__init__.py", line 377, in errprint
    print(msg)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/context.py", line 61, in update_controller_context
    ret = module.get_context(context)
  File "apps/frappe/frappe/www/error.py", line 15, in get_context
    print(frappe.get_traceback())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 75, in application
    response = frappe.website.render.render()
  File "apps/frappe/frappe/website/render.py", line 91, in render
    data = render_page(path)
  File "apps/frappe/frappe/website/render.py", line 227, in render_page
    return build(path)
  File "apps/frappe/frappe/website/render.py", line 235, in build
    return build_page(path)
  File "apps/frappe/frappe/website/render.py", line 251, in build_page
    context = get_context(path)
  File "apps/frappe/frappe/website/context.py", line 32, in get_context
    context = build_context(context)
  File "apps/frappe/frappe/website/context.py", line 113, in build_context
    update_controller_context(context, context.controller)
  File "apps/frappe/frappe/website/context.py", line 70, in update_controller_context
    frappe.errprint(frappe.utils.get_traceback())
  File "apps/frappe/frappe/__init__.py", line 377, in errprint
    print(msg)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Nihantra-Patel** [comment]
Hi @boubafof,

Kindly upgrade to version 14 or 15, then refresh and check again.
We no longer provide support for version 13 or older. 

Everything is working fine. No problems were encountered in versions 14 and 15.

Reference: https://www.youtube.com/watch?v=S_NqBmg6es0

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
