### ISSUE TITLE
Unable to submit delivery notes

### ISSUE THREAD

**Issue by JeffYYW** [frappe/erpnext#35069]
### Information about bug

Error when trying to submit a delivery note.

Steps to reproduce:
1. Create Delivery note from Sales Order
2. Save delivery note
3. Submit delivery note
4. See error below:

{
	"exception": "TypeError: update_reserved_qty() takes 1 positional argument but 2 were given"
}

### Module

stock

### Version

Frappe version - 13.56.0
ERPnext version - 13.49.14

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1020, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1009, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 366, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 246, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 474, in update_stock_ledger
    self.update_reserved_qty()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 410, in update_reserved_qty
    sales_order.update_reserved_qty(so_item_rows)
TypeError: update_reserved_qty() takes 1 positional argument but 2 were given
```

**Comment by iMoshi** [comment]
I've been getting the same error, hope y'all fix this asap :) 

ERPNext v14.20.3
Frappe v14.31

**Comment by rohitwaghchaure** [comment]
Tested and working fine on the latest version of v14
