### ISSUE TITLE
Subcontracting Receipt Quantity Issue

### ISSUE THREAD

**Issue by Donferarri92** [frappe/erpnext#35083]
### Information about bug

In Subcontracting Order, we do the material transfer to the subcontracting vendor. 

Scenario: We are sending 10 meters of cloth for dying purpose. Once dying is done, the cloth elongates by 0.5 meters. (Not fixed. this can go beyond also and can also shrink)

While doing the subcontracting receipt we are inwarding 10.5 Meters. Following error comes.

**"Row 1: Consumed Qty 10.5 must be less than or equal to Available Qty For Consumption 10.0 in Consumed Items Table."**

![image](https://user-images.githubusercontent.com/90032072/234859661-82303f99-d517-4b23-8629-7acb0bb66963.png)

Suggested Solution: Same as Delivery/Receipt Allowance and Over Billing Allowance, we can also create Subcontracting Receipt Allowance for better control.

### Module

manufacturing

### Version

ERPNext: v14.22.2 (HEAD)
Frappe Framework: v14.33.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 87, in on_submit
    self.validate_available_qty_for_consumption()
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 204, in validate_available_qty_for_consumption
    frappe.throw(_(msg))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row 1: Consumed Qty 10.5
					must be less than or equal to Available Qty For Consumption
					10.0
					in Consumed Items Table.
```

**Comment by s-aga-r** [comment]
@Donferarri92 

If you have configured `Over Delivery/Receipt Allowance (%)` in Stock Settings then you can receive more than the Subcontracting Order Item(s) Qty. Make sure the `Backflush Raw Materials of Subcontract Based On` is set to `Material Transferred for Subcontract` in Buying Settings so that you can change the Consumed Qty manually as the receipt qty is not fixed in your case. 

Ref:

Stock Settings
![image](https://github.com/frappe/erpnext/assets/63660334/3da917ff-04e3-46c8-8de0-916688779ce5)

Buying Settings
![image](https://github.com/frappe/erpnext/assets/63660334/fc0f932a-26cc-4e0d-b0dd-1440e29a93e5)

BOM (1:1)
![image](https://github.com/frappe/erpnext/assets/63660334/03cc2123-7347-4f9f-8f6d-7369a907711b)

Subcontracting Order (10 Qty)
![image](https://github.com/frappe/erpnext/assets/63660334/36ecd5ce-5b7e-42a4-aece-a03502a9a938)

Stock Entry [Send to Subcontractor] (10 Qty)
![image](https://github.com/frappe/erpnext/assets/63660334/99b0c613-9e88-4ced-b5af-5701190ab0f5)

Subcontracting Receipt (11 Qty)

[Screencast from 2023-05-15 16-23-25.webm](https://github.com/frappe/erpnext/assets/63660334/536dbc18-80e8-4736-9027-9ff910c6ba43)

Stock Ledger
![image](https://github.com/frappe/erpnext/assets/63660334/b93f2619-3820-47fb-a227-86bfa0182629)
