### ISSUE TITLE
SQL syntax error when viewing company accounts [v14, postgres]

### ISSUE THREAD

**Issue by rafalkrupinski** [frappe/erpnext#35181]
### Information about bug

On Postgres, this line
[	filters.append(['ifnull(`{0}`,"")'.format(parent_fieldname), "=", "" if is_root else parent])](https://github.com/frappe/erpnext/blob/7fb1e5bdcdb4db704f66dbca8675855e55323a94/erpnext/accounts/utils.py#LL964C36-L964C36)
turns to `coalesce("parent_cost_center","")`
`""` is an empty column name and is causes the syntax error.

If the intention was to turn NULL to "" (empty string), then using `\'\'` works, but I'm not sure if the problem is with the double quotes or it's a with translating them in the DB layer.

### Module

accounts

### Version

ERPNext: v14.23.1 (version-14)

Frappe Framework: v14.35.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
18:18:02 web.1            | 127.0.0.1 - - [05/May/2023 18:18:02] "POST /api/method/erpnext.accounts.utils.get_children HTTP/1.1" 500 -
18:18:05 web.1            | Syntax error in query:
18:18:05 web.1            | select "name" as value, "is_group" as expandable
18:18:05 web.1            |                     from "tabCost Center"
18:18:05 web.1            |                     where coalesce("tabCost Center"."docstatus", 0) < '2' and coalesce("parent_cost_center","") = '' and "tabCost Center"."company" = 'öKlo'
18:18:05 web.1            | 
18:18:05 web.1            |                      order by "tabCost Center"."modified" ASC 
18:18:05 web.1            | Traceback (most recent call last):
18:18:05 web.1            |   File "apps/frappe/frappe/app.py", line 66, in application
18:18:05 web.1            |     response = frappe.api.handle()
18:18:05 web.1            |   File "apps/frappe/frappe/api.py", line 54, in handle
18:18:05 web.1            |     return frappe.handler.handle()
18:18:05 web.1            |   File "apps/frappe/frappe/handler.py", line 45, in handle
18:18:05 web.1            |     data = execute_cmd(cmd)
18:18:05 web.1            |   File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
18:18:05 web.1            |     return frappe.call(method, **frappe.form_dict)
18:18:05 web.1            |   File "apps/frappe/frappe/__init__.py", line 1607, in call
18:18:05 web.1            |     return fn(*args, **newargs)
18:18:05 web.1            |   File "apps/erpnext/erpnext/accounts/utils.py", line 963, in get_children
18:18:05 web.1            |     acc = frappe.get_list(doctype, fields=fields, filters=filters)
18:18:05 web.1            |   File "apps/frappe/frappe/__init__.py", line 1896, in get_list
18:18:05 web.1            |     return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
18:18:05 web.1            |   File "apps/frappe/frappe/model/db_query.py", line 202, in execute
18:18:05 web.1            |     result = self.build_and_run()
18:18:05 web.1            |   File "apps/frappe/frappe/model/db_query.py", line 242, in build_and_run
18:18:05 web.1            |     return frappe.db.sql(
18:18:05 web.1            |   File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
18:18:05 web.1            |     return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
18:18:05 web.1            |   File "apps/frappe/frappe/database/database.py", line 219, in sql
18:18:05 web.1            |     self._cursor.execute(query, values)
18:18:05 web.1            | psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
18:18:05 web.1            | LINE 3: ...atus", 0) < '2' and coalesce("parent_cost_center","") = '' a...
```

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/issues/24389

Postgres isn't supported yet
