### ISSUE TITLE
No function matches the given name and argument types.

### ISSUE THREAD

**Issue by rafalkrupinski** [frappe/erpnext#35180]
### Information about bug

On a fresh install of frappe with erpnext and on Postgres 14, when opening Desk I get this error message:
> Server Error
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.

After closing the message i can see that `Sales Order Trends` panel is empty, with only the message: "loading..."

### Module

selling

### Version

ERPNext: v14.23.1 (version-14)
Frappe Framework: v14.35.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
16:20:16 web.1            | Traceback (most recent call last):
16:20:16 web.1            |   File "apps/frappe/frappe/app.py", line 66, in application
16:20:16 web.1            |     response = frappe.api.handle()
16:20:16 web.1            |   File "apps/frappe/frappe/api.py", line 54, in handle
16:20:16 web.1            |     return frappe.handler.handle()
16:20:16 web.1            |   File "apps/frappe/frappe/handler.py", line 45, in handle
16:20:16 web.1            |     data = execute_cmd(cmd)
16:20:16 web.1            |   File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
16:20:16 web.1            |     return frappe.call(method, **frappe.form_dict)
16:20:16 web.1            |   File "apps/frappe/frappe/__init__.py", line 1607, in call
16:20:16 web.1            |     return fn(*args, **newargs)
16:20:16 web.1            |   File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
16:20:16 web.1            |     retval = fn(*args, **get_newargs(fn, kwargs))
16:20:16 web.1            |   File "apps/frappe/frappe/desk/query_report.py", line 258, in run
16:20:16 web.1            |     result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
16:20:16 web.1            |   File "apps/frappe/frappe/__init__.py", line 789, in wrapper_fn
16:20:16 web.1            |     retval = fn(*args, **get_newargs(fn, kwargs))
16:20:16 web.1            |   File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
16:20:16 web.1            |     res = get_report_result(report, filters) or []
16:20:16 web.1            |   File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
16:20:16 web.1            |     res = report.execute_script_report(filters)
16:20:16 web.1            |   File "apps/frappe/frappe/core/doctype/report/report.py", line 142, in execute_script_report
16:20:16 web.1            |     res = self.execute_module(filters)
16:20:16 web.1            |   File "apps/frappe/frappe/core/doctype/report/report.py", line 159, in execute_module
16:20:16 web.1            |     return frappe.get_attr(method_name)(frappe._dict(filters))
16:20:16 web.1            |   File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 15, in execute
16:20:16 web.1            |     data = get_data(filters, conditions)
16:20:16 web.1            |   File "apps/erpnext/erpnext/controllers/trends.py", line 192, in get_data
16:20:16 web.1            |     data = frappe.db.sql(
16:20:16 web.1            |   File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
16:20:16 web.1            |     return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
16:20:16 web.1            |   File "apps/frappe/frappe/database/database.py", line 219, in sql
16:20:16 web.1            |     self._cursor.execute(query, values)
16:20:16 web.1            | psycopg2.errors.UndefinedFunction: function if(boolean, numeric, unknown) does not exist
16:20:16 web.1            | LINE 1: select t2.item_code, t2.item_name,SUM(IF(t1.transaction_date...
16:20:16 web.1            |                                               ^
16:20:16 web.1            | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/issues/24389

Postgres isn't supported yet
