### ISSUE TITLE
General ledger report pdf download in custom app in frappe.whitelist api 

### ISSUE THREAD

**Issue by rakesh1230** [frappe/erpnext#35218]
### Information about bug

hii
When i tried to render my same html code in general_ledger.html ledger in my custom app html file it gave me an error tag name was expected why it should not work in api function through frappe.render_template. if anyone know about this please help me. 

### Module

accounts

### Version

Frappe Version:14
Erpnet Version:14

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/employee_self_service/employee_self_service/mobile/ess.py", line 2096, in get_transactions
    html = frappe.render_template(
  File "apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().get_template(template).render(context)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "env/lib/python3.10/site-packages/jinja2/loaders.py", line 572, in load
    return loader.load(environment, name, globals)
  File "env/lib/python3.10/site-packages/jinja2/loaders.py", line 522, in load
    return loader.load(environment, local_name, globals)
  File "env/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "apps/employee_self_service/employee_self_service/templates/employee_statement.html", line 19, in template
    <h2 class="text-center">{%= __("Statement Of Account") %}</h2>
jinja2.exceptions.TemplateSyntaxError: tag name expected
```

**Comment by rakesh1230** [comment]
can i use the same html code in my custom app and pass in the render template for download pdf file of general ledger report

**Comment by Nihantra-Patel** [comment]
Check the reference:

https://github.com/search?q=repo%3Afrappe%2Ferpnext%20frappe.render_template&type=code

https://discuss.frappe.io/t/where-to-place-template-files-for-frappe-render-template/81821

https://frappeframework.com/docs/user/en/api/jinja#frappe-render-template
