### ISSUE TITLE
Event Sync Log Error ( Event Producer )

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#35211]
### Information about bug

Hello Team ,

Whenever we try to stream an event, we get an error

![image](https://user-images.githubusercontent.com/12432802/236808755-d192a4bb-3ebc-4f05-a043-e3c7c7e05978.png)

![image](https://user-images.githubusercontent.com/12432802/236808888-1b338ca7-9e33-44bf-a0ea-bd2689f19316.png)

Error-1

Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 313, in set_insert
    doc.insert(set_name=update.docname, set_child_names=False)
  File "apps/frappe/frappe/model/document.py", line 251, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 882, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #1: Party: Namokar Sales Private Limited

error-2

Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 310, in set_insert
    sync_dependencies(doc, producer_site)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 492, in sync_dependencies
    dependency.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 450, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/contacts/doctype/contact/contact.py", line 24, in autoname
    self.name = self.name + "-" + link.link_name.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

Error-3

Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 310, in set_insert
    sync_dependencies(doc, producer_site)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 492, in sync_dependencies
    dependency.insert()
  File "apps/frappe/frappe/model/document.py", line 260, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 528, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 863, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [Address, Namokar Sales Private Limited-Billing]: link_name

error-4

Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 310, in set_insert
    sync_dependencies(doc, producer_site)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 492, in sync_dependencies
    dependency.insert()
  File "apps/frappe/frappe/model/document.py", line 250, in insert
    self.check_if_latest()
  File "apps/frappe/frappe/model/document.py", line 763, in check_if_latest
    self.check_docstatus_transition(0)
  File "apps/frappe/frappe/model/document.py", line 797, in check_docstatus_transition
    raise frappe.DocstatusTransitionError(
frappe.exceptions.DocstatusTransitionError: Cannot change docstatus from 0 (Draft) to 2 (Cancelled)

error-5

Traceback (most recent call last):
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 277, in sync
    set_insert(update, producer_site, event_producer.name)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 313, in set_insert
    doc.insert(set_name=update.docname, set_child_names=False)
  File "apps/frappe/frappe/model/document.py", line 251, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 882, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #2: Party: VARGHESS-22S088

### Module

integrations

### Version

ERPNext: v14.23.4 (version-14)

Frappe Framework: v14.35.0 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@sammish seems like the issue is related to your customization. The DocType(s) link fields are not set correctly i.e. None or Invalid.
