### ISSUE TITLE
Error while reposting item valuation

### ISSUE THREAD

**Issue by ketan-striff** [frappe/erpnext#35288]
### Information about bug

Facing issue when interwarehouse transfer with negative stock.

### Module

stock, buying, selling

### Version

erpnext 14.24.0
frappe 14.36.0
hrms 14.3.1
india_compliance 14.6.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
{"message": "Debit and Credit not equal for Purchase Invoice #PI-23-00001. Difference is -28600.0.", "title": "Message", "indicator": "red", "raise_exception": 1}
Traceback:
Traceback (most recent call last): File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 201, in repost repost_gl_entries(doc) File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 262, in repost_gl_entries repost_gle_for_stock_vouchers( File "apps/erpnext/erpnext/accounts/utils.py", line 1168, in repost_gle_for_stock_vouchers voucher_obj.make_gl_entries(gl_entries=expected_gle, from_repost=True) File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 540, in make_gl_entries make_gl_entries( File "apps/erpnext/erpnext/accounts/general_ledger.py", line 45, in make_gl_entries save_entries(gl_map, adv_adj, update_outstanding, from_repost) File "apps/erpnext/erpnext/accounts/general_ledger.py", line 299, in save_entries process_debit_credit_difference(gl_map) File "apps/erpnext/erpnext/accounts/general_ledger.py", line 367, in process_debit_credit_difference raise_debit_credit_not_equal_error(debit_credit_diff, voucher_type, voucher_no) File "apps/erpnext/erpnext/accounts/general_ledger.py", line 404, in raise_debit_credit_not_equal_error frappe.throw( File "apps/frappe/frappe/__init__.py", line 525, in throw msgprint( File "apps/frappe/frappe/__init__.py", line 493, in msgprint _raise_exception() File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception raise raise_exception(msg) frappe.exceptions.ValidationError: Debit and Credit not equal for Purchase Invoice #PI-23-00001. Difference is -28600.0.
```

**Comment by rohitwaghchaure** [comment]
@ketan-striff This issue is related to data and difficult to replicate. If your site is hosted on frappecloud kindly create a support ticket for this issue.

**Comment by ketan-striff** [comment]
Site is not hosted on frappecloud but I can provide access to our server.
