### ISSUE TITLE
`NoneType object is not iterable ` error when creating a sales order from a quotation

### ISSUE THREAD

**Issue by IMS94** [frappe/erpnext#35322]
### Information about bug

When creating a sales order from a quotation, the following error is prompted. Tried adding a sales team to the customer too, but didn't work.

```
TypeError: 'NoneType' object is not iterable
```

### Module

selling

### Version

ERPNext 14.24.0
Frappe 14.36.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 263, in make_sales_order
    return _make_sales_order(source_name, target_doc)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 333, in _make_sales_order
    doclist = get_mapped_doc(
  File "apps/frappe/frappe/model/mapper.py", line 144, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 291, in set_missing_values
    for d in customer.get("sales_team"):
TypeError: 'NoneType' object is not iterable
```

**Comment by Solufyin** [comment]
Hi @IMS94,

Please upgrade your version because the issue has been solved in PR: #35153

Thank You!

**Comment by IMS94** [comment]
@Solufyin thanks for the update.

@ruthra-kumar thanks for the fixes. Can I know when are you planning to release the changes made in #35355 into v14?

**Comment by ruthra-kumar** [comment]
@IMS94 Fix is released in ERPNext v14.25.0

**Comment by IMS94** [comment]
@ruthra-kumar Thanks for the update!

**Comment by bhaveshmahavar** [comment]
I have ERPNEXT latest version still i got this error.
How can i solve this error?
@IMS94 @ruthra-kumar [Solufyin](https://github.com/Solufyin)

Error: TypeError: 'NoneType' object is not iterable
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 291, in set_missing_values
    for d in customer.get("sales_team"):
TypeError: 'NoneType' object is not iterable
