### ISSUE TITLE
Internal Transfer Return break because of latest change

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#35385]
### Information about bug

PR: https://github.com/frappe/erpnext/pull/34980

We Create Delivery Note then Purchase Receipt in Internal Transfer.
SO transaction happen this way Source Warehouse to in-Transit Warehouse. And in-transit Warehouse to target warehouse by Purchase Receipt.

But the problem in Return Workflow this https://github.com/frappe/erpnext/pull/34980 pr create bug. 
First we need to create Purchase Return so that it rollback from Target Warehouse to In transit by Return Purchase Receipt. then In-transit to Source by Return Delivery Note. 

So problem while creating Purhcase Return in Internal case it ask for Delivery note item which is inappropriate. All return operation stuck because of this.

### Module

accounts

### Version

ERPNext: v14.23.0 (version-14)

Frappe Framework: v14.33.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 119, in validate
    super(PurchaseReceipt, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 52, in validate
    super(SubcontractingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 151, in validate
    self.validate_inter_company_reference()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 415, in validate_inter_company_reference
    frappe.throw(_(msg), title=_("Internal Transfer Reference Missing"))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: At Row 1: The field <strong>Delivery Note Item</strong> is mandatory for internal transfer

(anonymous) @ request.js:457
```

**Comment by Nihantra-Patel** [comment]
You're correct, but it's designed from the perspective of the user or client.

However, you can change this feature in a custom app if you prefer. Otherwise, you can delete the added code, but we recommend overriding it in your custom app for the user or client.
