### ISSUE TITLE
Issue: error when splitting a batch with repack purpose

### ISSUE THREAD

**Issue by Madcheese101** [frappe/erpnext#35441]
### Information about bug

Hello,

When trying to split a batch, it errors like this:

`Purpose cannot be "Repack". It should be one of "Send to Warehouse", "Receive at Warehouse", "Material Transfer"`

### Module

stock

### Version

ERPNext: v13.49.5 (version-13)
Frappe Framework: v13.51.2 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/stock/doctype/batch/batch.py", line 250, in split_batch
    stock_entry.insert()
  File "apps/frappe/frappe/model/document.py", line 264, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 542, in _validate
    self._validate_selects()
  File "apps/frappe/frappe/model/base_document.py", line 721, in _validate_selects
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError:  Purpose cannot be "Repack". It should be one of "Send to Warehouse", "Receive at Warehouse", "Material Transfer"
```

**Comment by rohitwaghchaure** [comment]
@Madcheese101 It seems that you have deleted the Stock Entry Type as Repack, kindly create the Stock Entry Type as Repack (Set Purpose as Repack) and check.

<img width="873" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/f9271b73-b84b-4b82-b8f2-c4fb920377a6">

**Comment by Madcheese101** [comment]
@rohitwaghchaure the Repack stock type is there, nothing was deleted.

<img width="590" alt="image" src="https://github.com/frappe/erpnext/assets/40042269/ec78eec3-073b-48aa-b9c7-03ec81dc13bc">

I even just recreated it again, and still the same error.
