### ISSUE TITLE
pymysql.err.DataError: (1264, "Out of range value for column 'valuation_rate' at row 1")

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#35469]
### Information about bug

desk.bundle.V3ATWB56.js:445 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/workflow.py", line 135, in apply_workflow
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1005, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 984, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 244, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 518, in update_stock_ledger
    self.make_sl_entries(
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 470, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 85, in make_sl_entries
    repost_current_voucher(args, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 101, in repost_current_voucher
    update_entries_after(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 386, in __init__
    self.build()
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 434, in build
    self.process_sle_against_current_timestamp()
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 458, in process_sle_against_current_timestamp
    self.process_sle(sle)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 611, in process_sle
    frappe.get_doc(sle).db_update()
  File "apps/frappe/frappe/model/base_document.py", line 558, in db_update
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 219, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'valuation_rate' at row 1")

### Module

stock

### Version

ERPNext: v14.23.0 (version-14)

Frappe Framework: v14.34.0 (version-14)

### Installation method

None

**Comment by vishdha** [comment]
cur_frm.doc.items[0].valuation_rate
= 486.490063193

**Comment by vishdha** [comment]
Cause by https://github.com/frappe/erpnext/pull/32272/files
