### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by c0fe** [frappe/erpnext#35464]
The suggestion is simple, improve your documentation, the manual installation just links to Frappe Bench, beyond that it doesn't really specify how to actually run the installation of ERPNext. For example, I figured the installation through Bench is:

`bench init frappe-bench --frappe-branch version-14`

but that errors out:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/usr/local/lib/python3.10/dist-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/usr/local/lib/python3.10/dist-packages/git/cmd.py", line 287, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 5, in <module>
    from bench.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 13, in <module>
    from bench.bench import Bench
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 36, in <module>
    from bench.utils.app import get_current_version
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/app.py", line 12, in <module>
    from bench.app import get_repo_dir
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 18, in <module>
    from git import Repo
  File "/usr/local/lib/python3.10/dist-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

So having documentation that would be more expanded and actually gives instructions on how to manually install.

**Comment by ankush** [comment]
Installation guide does mention git as dependency.


I'd recommend using docker instead, manual install is quite long process.


https://github.com/frappe/frappe_docker

**Comment by c0fe** [comment]
@ankush why would you close this? documentation is messy and is missing steps. i gave you an example. the error message is just an example of incomplete documentation in which you have to make a guess as to how to install. machine being installed has git installed so this is a second issue but the documentation rewrite is valid.

the installation instructions is to simply link another project, that's it. that is not proper documentation.
