### ISSUE TITLE
Tally Migration

### ISSUE THREAD

**Issue by riddhisolanki001** [frappe/erpnext#35472]
### Information about bug

Data:
"Processing Master Data"

Exception:
Traceback (most recent call last):
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 276, in _process_master_data
    chart_of_accounts, customers, suppliers = get_coa_customers_suppliers(collection)
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 131, in get_coa_customers_suppliers
    for account in coa:
UnboundLocalError: local variable 'coa' referenced before assignment

### Module

accounts

### Version

ERPNext: v14.25.1 (version-14)

Frappe Framework: v14.36.3 (version-14)

### Installation method

None

**Comment by Sunitsarode** [comment]
How to resolve this issue, I have got this issue still in latest version of Frappe and ERPNext
