### ISSUE TITLE
Error in tally Migration 

### ISSUE THREAD

**Issue by riddhisolanki001** [frappe/erpnext#35471]
### Information about bug

Data:
"Error occured while parsing Chart of Accounts: Please make sure that no two accounts have the same name"
----------------------------------------------------------------------------------------------------

Exception:
Traceback (most recent call last):
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 123, in get_coa_customers_suppliers
    coa = traverse({}, children, roots, roots, group_set)
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 189, in traverse
    tree[account] = traverse({}, children, children[account], roots, group_set)
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 189, in traverse
    tree[account] = traverse({}, children, children[account], roots, group_set)
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 189, in traverse
    tree[account] = traverse({}, children, children[account], roots, group_set)
  [Previous line repeated 971 more times]
  File "/home/riddhi-solanki/migoo_backup/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 187, in traverse
    if account in group_set or account in roots:
RecursionError: maximum recursion depth exceeded in comparison

### Module

accounts

### Version

ERPNext: v14.25.1 (version-14)

Frappe Framework: v14.36.3 (version-14)

### Installation method

None

**Comment by MDALAMIN2526** [comment]
I'm also having same problem in V13. anyone have any solution?
