### ISSUE TITLE
Sidebar broken on latest release

### ISSUE THREAD

**Issue by ChipwizBen** [frappe/erpnext#35535]
### Information about bug

On the latest release of v14, the menu sidebar is broken. Other menu sidebars work fine:
![image](https://github.com/frappe/erpnext/assets/7927875/86d9b07a-8b53-4c6b-896a-88a6cadeaf80)
![image](https://github.com/frappe/erpnext/assets/7927875/4fe4a23e-4a7b-4e85-a477-864be240bb5c)

It's broken in both Firefox and Chrome.

### Module

accounts, HR, integrations

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
Frappe HR: v15.0.0-dev (develop)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Possibly related:
![image](https://github.com/frappe/erpnext/assets/7927875/697ce470-60b3-4ad8-a03f-42e5ccc5dc8d)
```

**Comment by ChipwizBen** [comment]
Has anybody else experienced this? Is this a configuration issue?

**Comment by mastewalm** [comment]
does it work for other user accounts for you?

**Comment by ChipwizBen** [comment]
> does it work for other user accounts for you?

Yes, it appears to be fine with other accounts.

**Comment by mastewalm** [comment]
Then we are facing the same problem. I hope someone will help us.

**Comment by ChipwizBen** [comment]
Likely related error:

Title
_test/problematic_page failed

Error

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
      path = '_test/problematic_page'
      http_status_code = 200
      response = None
      endpoint = '_test/problematic_page'
      path_resolver = <frappe.website.path_resolver.PathResolver object at 0x7fa3016225f0>
      renderer_instance = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fa301581fd0>
      e = ValidationError('<pre>{% raise %}\n</pre><pre>Traceback (most recent call last):\n  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template\n    return get_jenv().from_string(template).render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string\n    return cls.from_code(self, self.compile(source), gs, None)\n                               ^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile\n    self.handle_exception(source=source_hint)\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "<unknown>", line 1, in template\njinja2.exceptions.TemplateSyntaxError: Encountered unknown tag \'raise\'.\n</pre>')
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fa301581fd0>
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
      args = (<frappe.website.page_renderers.template_page.TemplatePage object at 0x7fa301581fd0>,)
      kwargs = {}
      func = <function TemplatePage.get_html at 0x7fa303369f80>
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 101, in get_html
    html = self.render_template()
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fa301581fd0>
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 238, in render_template
    html = frappe.render_template(self.source, self.context, safe_render=safe_render)
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fa301581fd0>
      safe_render = True
  File "apps/frappe/frappe/utils/jinja.py", line 87, in render_template
    throw(
      template = '{% raise %}\n'
      context = {'top_bar_items': [], 'footer_items': [], 'post_login': [{'label': 'My Account', 'url': '/me'}, {'label': 'Log out', 'url': '/?cmd=web_logout'}], 'disable_signup': 1, 'navbar_template': 'Standard Navbar', 'footer_template': 'Standard Footer', 'facebook_share': 0, 'google_plus_one': 0, 'twitter_share': 0, 'linked_in_share': 0, 'url': 'http://localhost', 'encoded_title': '', 'web_include_js': ['website_script.js', 'erpnext-web.bundle.js'], 'web_include_css': ['erpnext-web.bundle.css'], 'favicon': '/assets/erpnext/images/erpnext-favicon.svg', 'splash_image': '/assets/erpnext/images/erpnext-logo.svg', 'theme': <WebsiteTheme: Standard>, 'hide_login': 0, 'read_only_mode': False, 'boot': {'sysdefaults': {'float_precision': 2, 'date_format': 'dd-mm-yyyy', 'time_format': 'HH:mm:ss'}, 'time_zone': {'system': 'Pacific/Auckland', 'user': 'Pacific/Auckland'}}, 'base_template': None, 'basepath': 'apps/frappe/frappe/www/_test', 'basename': 'apps/frappe/fr...
      is_path = None
      safe_render = True
      TemplateError = <class 'jinja2.exceptions.TemplateError'>
      _ = <function _ at 0x7fa30b741a80>
      get_traceback = <function get_traceback at 0x7fa30a47e520>
      throw = <function throw at 0x7fa30a47ea20>
  File "apps/frappe/frappe/__init__.py", line 526, in throw
    msgprint(
      msg = '<pre>{% raise %}\n</pre><pre>Traceback (most recent call last):\n  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template\n    return get_jenv().from_string(template).render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string\n    return cls.from_code(self, self.compile(source), gs, None)\n                               ^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile\n    self.handle_exception(source=source_hint)\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "<unknown>", line 1, in template\njinja2.exceptions.TemplateSyntaxError: Encountered unknown tag \'raise\'.\n</pre>'
      exc = <class 'frappe.exceptions.ValidationError'>
      title = 'Jinja Template Error'
      is_minimizable = False
      wide = False
      as_list = False
  File "apps/frappe/frappe/__init__.py", line 494, in msgprint
    _raise_exception()
      msg = '<pre>{% raise %}\n</pre><pre>Traceback (most recent call last):\n  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template\n    return get_jenv().from_string(template).render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string\n    return cls.from_code(self, self.compile(source), gs, None)\n                               ^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile\n    self.handle_exception(source=source_hint)\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "<unknown>", line 1, in template\njinja2.exceptions.TemplateSyntaxError: Encountered unknown tag \'raise\'.\n</pre>'
      title = 'Jinja Template Error'
      raise_exception = <class 'frappe.exceptions.ValidationError'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      sys = <module 'sys' (built-in)>
      out = {'message': '<pre>{% raise %}\n</pre><pre>Traceback (most recent call last):\n  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template\n    return get_jenv().from_string(template).render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string\n    return cls.from_code(self, self.compile(source), gs, None)\n                               ^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile\n    self.handle_exception(source=source_hint)\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "<unknown>", line 1, in template\njinja2.exceptions.TemplateSyntaxError: Encountered unknown tag \'raise\'.\n</pre>', 'title': 'Jinja Template Error', 'indicator': 'red', 'raise_exception': 1}
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7fa3017f4680>
      _strip_html_tags = <functools._lru_cache_wrapper object at 0x7fa301d950c0>
      inspect = <module 'inspect' from '/usr/lib64/python3.11/inspect.py'>
      strip_html_tags = <function strip_html_tags at 0x7fa30a469120>
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
      inspect = <module 'inspect' from '/usr/lib64/python3.11/inspect.py'>
      msg = '<pre>{% raise %}\n</pre><pre>Traceback (most recent call last):\n  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template\n    return get_jenv().from_string(template).render(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string\n    return cls.from_code(self, self.compile(source), gs, None)\n                               ^^^^^^^^^^^^^^^^^^^^\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile\n    self.handle_exception(source=source_hint)\n  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "<unknown>", line 1, in template\njinja2.exceptions.TemplateSyntaxError: Encountered unknown tag \'raise\'.\n</pre>'
      raise_exception = <class 'frappe.exceptions.ValidationError'>
frappe.exceptions.ValidationError: <pre>{% raise %}
</pre><pre>Traceback (most recent call last):
  File "apps/frappe/frappe/utils/jinja.py", line 85, in render_template
    return get_jenv().from_string(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'raise'.
</pre>
