### ISSUE TITLE
Unable to submit closing stock balance

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35616]
### Information about bug

There is a document in ERPNext called Closing Stock balance. seems like it has no documentation on how it works or further details. when given fields are filled and updated getting following error

### Module

stock

### Version

V14

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"cheque_management": "0.0.1",
	"erpnext": "14.26.0",
	"frappe": "14.37.1",
	"hrms": "14.4.0",
	"payments": "0.0.1",
	"posawesome": "3.4.0",
	"vector": "0.0.1"
}
```
### Route
```
Form/Closing Stock Balance/new-closing-stock-balance-2
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.py", line 33, in validate
    self.validate_duplicate()
  File "apps/erpnext/erpnext/stock/doctype/closing_stock_balance/closing_stock_balance.py", line 54, in validate_duplicate
    query = query.where(table.get(fieldname) == self.get(fieldname))
TypeError: 'Field' object is not callable

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Closing Stock Balance\",\"name\":\"new-closing-stock-balance-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CBAL-.#####\",\"company\":\"Craft Interactive\",\"status\":\"Draft\",\"item_group\":\"All Item Groups\",\"from_date\":\"2023-01-01\",\"to_date\":\"2023-06-08\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360072405486013498181": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 16322,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: 'Field' object is not callable"
}
```
```

**Comment by s-aga-r** [comment]
fixed in ERPNext v14.27.2 

ref: https://github.com/frappe/erpnext/pull/35617
