### ISSUE TITLE
bench get-untranslated not working

### ISSUE THREAD

**Issue by YiNingCN** [frappe/erpnext#35637]
### Information about bug

bench get-untranslated stopped working after recent update (which was working a few weeks ago)
output is : NameError: name 'entries' is not defined
Command : bench get-untranslated zh 1.csv

### Module

other

### Version

14.27.1
updated with bench update 2023/6/12

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
yining@erp-test:/home/frappe/frappe-bench$ bench get-untranslated zh 1.csv
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/translate.py", line 64, in get_untranslated
    frappe.translate.get_untranslated(lang, untranslated_file, get_all=all, app=app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 1042, in get_untranslated
    messages.extend(get_messages_for_app(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 414, in get_messages_for_app
    messages.extend(get_messages_from_report(name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 601, in get_messages_from_report
    messages = _get_messages_from_page_or_report(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 633, in _get_messages_from_page_or_report
    messages = get_messages_from_file(os.path.join(doc_path, frappe.scrub(name) + ".py"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 725, in get_messages_from_file
    messages += extract_messages_from_python_code(file_contents)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 745, in extract_messages_from_python_code
    for message in extract_python(
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/babel/messages/extract.py", line 487, in extract_python
    value = eval(code, {'__builtins__': {}}, {})
  File "<string>", line 2, in <module>
NameError: name 'entries' is not defined
```

**Comment by YiNingCN** [comment]
upgrade babel solved the problem
pip install babel --upgrade

**Comment by sinhpn92** [comment]
@YiNingCN 
I have the same issue. 
I installed and update babel, But It still not working.
<img width="447" alt="Screenshot 2023-08-22 at 16 51 11" src="https://github.com/frappe/erpnext/assets/9253441/5a17673c-e64c-4fd0-914e-4741e0e352e6">
