### ISSUE TITLE
Stock Aging Report Bug in Dashboard Chart

### ISSUE THREAD

**Issue by ihesamyou** [frappe/erpnext#35669]
### Information about bug

In Dashboard Chart form when chart_type, report is selected and report stock aging is selected, we get this error in both V13 and V14:

![stock_aging](https://github.com/frappe/erpnext/assets/86075967/6070dfa9-004f-4220-a067-110baab35fc6)

### Module

stock

### Version

ERPNext Version 13 and 14

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"drive": "0.0.1",
	"erpnext": "13.39.0",
	"frappe": "13.41.1",
	"frappedesk": "0.4.7"
}
```
### Route
```
Form/Dashboard Chart/new-dashboard-chart-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 257, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 91, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 72, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 165, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/stock/report/stock_ageing/stock_ageing.py", line 22, in execute
    data = format_report_data(filters, item_details, to_date)
  File "apps/erpnext/erpnext/stock/report/stock_ageing/stock_ageing.py", line 48, in format_report_data
    range1, range2, range3, above_range3 = get_range_age(filters, fifo_queue, to_date, item_dict)
  File "apps/erpnext/erpnext/stock/report/stock_ageing/stock_ageing.py", line 99, in get_range_age
    if age <= filters.range1:
TypeError: '<=' not supported between instances of 'int' and 'str'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Stock Ageing",
		"filters": "{\"company\":\"سرووهیدرولیک پویا\",\"to_date\":\"2023-06-13\",\"range1\":\"30\",\"range2\":\"60\",\"range3\":\"90\",\"show_warehouse_wise_stock\":0}",
		"ignore_prepared_report": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "TypeError: '<=' not supported between instances of 'int' and 'str'"
}
```
```

**Comment by ihesamyou** [comment]
Fixed.
