### ISSUE TITLE
Consolidated Financial Statement Error

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#35765]
### App Versions
```
{
	"erpnext": "14.27.6",
	"frappe": "14.39.0",
	"india_compliance": "14.10.1"
}
```
### Route
```
query-report/Consolidated Financial Statement
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 790, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 790, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 53, in execute
    data, message, chart, report_summary = get_balance_sheet_data(
  File "apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 72, in get_balance_sheet_data
    asset = get_data(companies, "Asset", "Debit", fiscal_year, filters=filters)
  File "apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 371, in get_data
    accumulate_values_into_parents(accounts, accounts_by_name, companies)
  File "apps/erpnext/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py", line 448, in accumulate_values_into_parents
    accounts_by_name[account][company] = accounts_by_name[account].get(company, 0.0) + d.get(
KeyError: 'Duties and Taxes'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Consolidated Financial Statement",
		"filters": "{\"company\":\"iThinker LLP\",\"filter_based_on\":\"Fiscal Year\",\"period_start_date\":\"2023-04-01\",\"period_end_date\":\"2024-03-31\",\"from_fiscal_year\":\"2023-2024\",\"to_fiscal_year\":\"2023-2024\",\"report\":\"Balance Sheet\",\"presentation_currency\":\"INR\",\"include_default_book_entries\":1}",
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "KeyError: 'Duties and Taxes'"
}
```

### Module

accounts

### Version

ERPNext: v14.27.6 (HEAD)

Frappe Framework: v14.39.0 (HEAD)

India Compliance: v14.10.1 (HEAD)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@nakul80 The error is not replicable, looks more like a data issue. Please add more info for investigation

**Comment by nakul80** [comment]
It says its a KeyError: 'Duties and Taxes'.. It is not data dependent i feel as 'Duties and Taxes' probably is a backend definition.
