### ISSUE TITLE
TypeError: On validating Payment Entry with no references

### ISSUE THREAD

**Issue by meaziz** [frappe/erpnext#35877]
### Information about bug

When saving Payment entry for parties other that customers or suppliers. and with no references in the references table
TypeError occurs since the loop is not scoped.

### Module

accounts

### Version

ERPNext: v14.27.7 (HEAD)
Frappe Framework: v14.39.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.27.7",
	"frappe": "14.39.0",
	"non_profit": "0.0.1"
}
```
### Route
```
Form/Payment Entry/new-payment-entry-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 81, in validate
    self.validate_allocated_amount()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 167, in validate_allocated_amount
    for d in latest_references:
TypeError: 'NoneType' object is not iterable

### Response Data
```
{
	"exception": "TypeError: 'NoneType' object is not iterable"
}
```
```

**Comment by meaziz** [comment]
https://github.com/frappe/erpnext/blob/c7186ff95c6fca7b149c3c0d9acf1af99aca53a9/erpnext/accounts/doctype/payment_entry/payment_entry.py#L158

**Comment by meaziz** [comment]
https://github.com/frappe/erpnext/blob/d9008779de78252f481585958ec88dda674430cf/erpnext/accounts/doctype/payment_entry/payment_entry.py#L182C14-L182C14
