### ISSUE TITLE
Non System Manager Cannot Stop the Work Order

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#35878]
### Information about bug

A user already has the role of manufacturing manager and manufacturing user however, the user cannot manually change the status of a work order using the status button with the stop and close option.
![image](https://github.com/frappe/erpnext/assets/60758795/8c9e50a7-4051-435a-bf55-923da6e8e8ce)

Why is a non system manager cannot use the status button? Any solution on this?
to

### Module

manufacturing

### Version

ERPNext: v13.51.6 (HEAD)
Frappe Framework: v13.57.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1229, in stop_unstop
    frappe.throw(_("Not permitted"), frappe.PermissionError)
  File "apps/frappe/frappe/__init__.py", line 512, in throw
    as_list=as_list,
  File "apps/frappe/frappe/__init__.py", line 480, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 435, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: Not permitted
```

**Comment by Solufyin** [comment]
Hi @Ponyooooo,

Because if no write permission in the work order then faced issues.

Please check it.

https://github.com/frappe/erpnext/blob/60a170d1a45b6e12497500282818e0805a39a6ef/erpnext/manufacturing/doctype/work_order/work_order.py#L1228-L1229

Thank You!

**Comment by Ponyooooo** [comment]
@Solufyin we gave both the manufacturing manager and manufacturing user a "write" permission using the role permissions manager tool. Actually we have tick all the checkmark on the work order just to make it work. However, the message still pop ups.

**Comment by nabinhait** [comment]
Can't replicate the issue. Maybe some customisation is creating the issue.
