### ISSUE TITLE
HSN/SAC code error while creating multiple variants

### ISSUE THREAD

**Issue by Donferarri92** [frappe/erpnext#35948]
### Information about bug

I created a template item and made the has variant checkbox as true. I added 2 Item attributes. When I go to creat and select multiple variants, the following error comes.

"HSN/SAC code is required. Please enter a valid HSN/SAC code."

Expected: Multiple variants should be created with same HSN code as template item.

![image](https://github.com/frappe/erpnext/assets/90032072/c26dbd25-d105-4945-addc-d137c854d2d9)

### Module

stock

### Version

Frappe Version: v14.40.1 (HEAD)
ERPNext Version: v14.28.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/controllers/item_variant.py", line 226, in enqueue_multiple_variant_creation
    return create_multiple_variants(item, args)
  File "apps/erpnext/erpnext/controllers/item_variant.py", line 247, in create_multiple_variants
    variant.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 6, in validate
    validate_hsn_code(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/item.py", line 25, in validate_hsn_code
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 526, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 494, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.MandatoryError: HSN/SAC Code is required. Please enter a valid HSN/SAC code.
```

**Comment by Nihantra-Patel** [comment]
Hi @Donferarri92,

Please check it.

https://github.com/resilient-tech/india-compliance/issues/1640#issuecomment-1914059277

Thank You!
