### ISSUE TITLE
Error when saving ToDo

### ISSUE THREAD

**Issue by mrPauwHaan** [frappe/erpnext#35982]
### Information about bug

When trying to save a ToDo after updating it, I am getting random errors sometimes. It is not because of what I am entering, because of trying different combinations and pressing "save" multiple times after the error, it does work.

### Module

other

### Version

	"chat": "0.0.1",
	"ecommerce_integrations": "1.17.1",
	"erpnext": "14.27.9",
	"frappe": "14.40.0",
	"hrms": "15.0.0-dev",
	"non_profit": "0.0.1",
	"payments": "0.0.1",
	"wiki": "2.0.0"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"ecommerce_integrations": "1.17.1",
	"erpnext": "14.27.9",
	"frappe": "14.40.0",
	"hrms": "15.0.0-dev",
	"non_profit": "0.0.1",
	"payments": "0.0.1",
	"wiki": "2.0.0"
}
```
### Route
```
Form/ToDo/5aa48982ae
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 17, in savedocs
    capture_doc(doc, action)
TypeError: capture_doc() takes 1 positional argument but 2 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"5aa48982ae\",\"owner\":\"jordy.pouwels@shadowzone.nl\",\"creation\":\"2023-07-03 20:36:14.305591\",\"modified\":\"2023-07-03 20:36:14.305591\",\"modified_by\":\"jordy.pouwels@shadowzone.nl\",\"docstatus\":0,\"idx\":0,\"status\":\"Open\",\"status_bestuur_todo\":\"Bespreken vergadering\",\"priority\":\"Medium\",\"description\":\"<div class=\\\"ql-editor read-mode\\\"><p>Jubileumjaar</p><ol><li data-list=\\\"bullet\\\"><span class=\\\"ql-ui\\\" contenteditable=\\\"false\\\"></span>Online jubileumboek 2023? (Heyzine?)</li></ol></div>\",\"doctype\":\"ToDo\",\"__last_sync_on\":\"2023-07-03T18:36:15.666Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery360051069204385615221": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1169,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: capture_doc() takes 1 positional argument but 2 were given"
}
```
```

**Comment by ankush** [comment]
Not reproducible. Code does allow two arguments. 


Check if latest code is present in frappe folder and isn't modified. https://github.com/frappe/frappe/blob/85e169e5fe7975bf6f4695f4e2fff67e3d0c86b5/frappe/utils/telemetry.py#L61
