### ISSUE TITLE
The declaration is missing for the today variable in the Bank Reconciliation Tool (ReferenceError: today is not defined) 

### ISSUE THREAD

**Issue by navinbalaji** [frappe/erpnext#36021]
### Information about bug

The declaration is missing for the variable today in the Bank Reconciliation Tool. Leads to the javascript error

### Steps to Reproduce:
1. Open Bank Reconciliation Tool
2. Open browser developer options and open the console

### Attachment
<img width="1219" alt="Screenshot 2023-07-07 at 11 21 19 AM" src="https://github.com/frappe/erpnext/assets/54995833/d00c8784-4141-4ee2-8d0d-0b2e7ebc1e8d">

### Module

accounts

### Version

Frappe Version - v14.40.1
ERPNext Version - v14.29.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
`Uncaught (in promise) ReferenceError: today is not defined
    at onload (bank_reconciliation_tool__js:26:9)
    at d (script_manager.js:30:12)
    at n (script_manager.js:109:16)
    at script_manager.js:127:22
 `
```

**Comment by navinbalaji** [comment]
Issue Resolved in  #36022
