### ISSUE TITLE
Unable to generate the balance sheet report

### ISSUE THREAD

**Issue by aravindsprint** [frappe/erpnext#36023]
### Information about bug

Hi,

When we try to generate the balance sheet report, we are getting an error like below but there is no ledger like that
"Input Tax IGST RCM - MAC."
<img width="1392" alt="image" src="https://github.com/frappe/erpnext/assets/15940614/89a3fa87-a4d0-4be1-9db0-713858154583">

<img width="1433" alt="image" src="https://github.com/frappe/erpnext/assets/15940614/0136f251-3718-4688-9883-650608f55bdf">

Kindly fix this issue.

### Module

accounts

### Version

Installed Apps
ERPNext: v14.28.0 (HEAD)

Frappe Framework: v14.40.1 (HEAD)

Frappe HR: v14.4.5 (HEAD)

India Compliance: v14.10.2 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by aravindsprint** [comment]
Hi,

Here is the error log,

request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/balance_sheet/balance_sheet.py", line 34, in execute
    asset = get_data(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 193, in get_data
    calculate_values(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 228, in calculate_values
    frappe.msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 447, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: Could not retrieve information for Input Tax IGST RCM - MAC.

Kindly do the needful.

**Comment by Nihantra-Patel** [comment]
Hi @aravindsprint,

We looked at the newest version 14 and tested it, but we didn't find the problem. So, I believe the problem has been fixed. If the problem happens again, please reopen it in either version 14 or 15, and if you can, include a video explanation.

Thank You!
