### ISSUE TITLE
Unambiguous Column error in GST Item Wise Sales Register Report

### ISSUE THREAD

**Issue by MhmdSinanKT** [frappe/erpnext#36059]
### Information about bug

When loading up the report, unambiguous column error is coming up, I have checked the code and it is due to the method taking data from Sales Invoice and Sales Invoice Item tables but in the additional columns being added in the query, the table name isn't mentioned for the columns.

### Module

regional

### Version

ERPNext - 13.51.7
Frappe - 13.57.4

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions
{
    "erpnext": "13.51.7",
    "frappe": "13.57.4",
    "vinays_v13": "0.0.1"
}
### Route
query-report/GST Itemised Sales Register
### Trackeback
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/kf_city_2/kf_city_2/kf_city_2/customization/kf_app.py", line 104, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 773, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 259, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 773, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 93, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 74, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 165, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/regional/report/gst_itemised_sales_register/gst_itemised_sales_register.py", line 51, in execute
    additional_conditions=additional_conditions,
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 33, in _execute
    item_list = get_items(filters, additional_query_columns, additional_conditions)
  File "apps/erpnext/erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py", line 430, in get_items
    as_dict=1,
  File "apps/frappe/frappe/database/database.py", line 187, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1052, "Column 'gst_hsn_code' in field list is ambiguous")
### Request Data
{
    "type": "GET",
    "args": {
        "report_name": "GST Itemised Sales Register",
        "filters": "{\"from_date\":\"2023-06-10\",\"to_date\":\"2023-07-10\",\"company\":\"Vinyas Innovative Technologies Pvt Ltd\"}",
        "are_default_filters": false
    },
    "headers": {},
    "error_handlers": {},
    "url": "/api/method/frappe.desk.query_report.run"
}
### Response Data
{
    "exception": "pymysql.err.OperationalError: (1052, \"Column 'gst_hsn_code' in field list is ambiguous\")"
}
```

**Comment by Nihantra-Patel** [comment]
Hi @MhmdSinanKT,

Fixed by https://github.com/frappe/erpnext/pull/36000 or https://github.com/resilient-tech/india-compliance/pull/818

Kindly upgrade to version 14 or 15, then refresh and check again.
We no longer provide support for version 13 or older. 

Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Comment by MhmdSinanKT** [comment]
I'll check in v15, thanks
