### ISSUE TITLE
Balance Sheet Report - Couldnt retrieve info

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#36110]
### Information about bug

error running balance sheet report.. similar error while opening chart of accounts.

Input CGST RCM is a valid chart of account in the Current Liabilities group.
![image](https://github.com/frappe/erpnext/assets/64956588/bcdcc0bf-728c-4df1-bbc8-528cfd990e1a)

### Module

accounts

### Version

ERPNext: v14.29.1 (HEAD)
Frappe Framework: v14.40.2 (HEAD)
India Compliance: v14.10.4 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught (in promise) Filter missing
/api/method/frappe.desk.query_report.run?report_name=Balance%20Sheet&filters=%7B%22company%22%3A%22iThinker%20LLP%22%2C%22filter_based_on%22%3A%22Fiscal%20Year%22%2C%22period_start_date%22%3A%222023-04-01%22%2C%22period_end_date%22%3A%222024-03-31%22%2C%22from_fiscal_year%22%3A%222023-2024%22%2C%22to_fiscal_year%22%3A%222023-2024%22%2C%22periodicity%22%3A%22Yearly%22%2C%22cost_center%22%3A%5B%5D%2C%22accumulated_values%22%3A1%2C%22include_default_book_entries%22%3A1%7D&is_tree=true&parent_field=parent_account&are_default_filters=false&_=1689221438005:1 
        
        
        Failed to load resource: the server responded with a status of 417 ()
request.js:457  Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/balance_sheet/balance_sheet.py", line 32, in execute
    asset = get_data(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 193, in get_data
    calculate_values(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 228, in calculate_values
    frappe.msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 447, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: Could not retrieve information for Input CGST RCM - ITK.
```

**Comment by Nihantra-Patel** [comment]
Hi @nakul80,

We looked at the newest version 14 and tested it, but we didn't find the problem. So, I believe the problem has been fixed. If the problem happens again, please reopen it in either version 14 or 15, and if you can, include a video explanation.

Thank You!
