### ISSUE TITLE
Requirements.txt is missing in version-14 branch

### ISSUE THREAD

**Issue by chromonav** [frappe/erpnext#36146]
### Information about bug

requirements.txt file is missing in version-14 branch.

### Module

other

### Version

ERPNEXT VERSION = = "14.30.6"

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
(env) frappe@f29f185fa893:~/frappe-bench/apps/frappe$ bench install-app erpnext

Installing erpnext...
Updating DocTypes for erpnext       : [====================================    ] 90%An error occurred while installing erpnext: Module import failed for TaxJar Settings, the DocType you're trying to open might be deleted.<br> Error: No module named 'taxjar'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1330, in get_module
    return importlib.import_module(modulename)
  File "/home/frappe/.pyenv/versions/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/taxjar_settings/taxjar_settings.py", line 13, in <module>
    from erpnext.erpnext_integrations.taxjar_integration import get_client
  File "apps/erpnext/erpnext/erpnext_integrations/taxjar_integration.py", line 4, in <module>
    import taxjar
ModuleNotFoundError: No module named 'taxjar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 294, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 409, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 494, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for TaxJar Settings, the DocType you're trying to open might be deleted.<br> Error: No module named 'taxjar'
```

**Comment by mohsinalimat** [comment]
You miss the `site_name` on install-app step.

**Comment by ankush** [comment]
Use latest bench version. We don't use requirements.txt anymore, instead pyproject.toml is being used which is the new python packaging standard.

**Comment by siasty** [comment]
But when we create applications bench builds in the old architecture  we dont have pyproject.toml
