### ISSUE TITLE
Delivery Note Cancelling Issue

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#36161]
### Information about bug

Hello,

We are facing issue while cancelling delievery note.
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/4a4dee43-7fc4-4a95-9f4b-999ea9bc3b19">

Issue Description:
### App Versions
```
{
	"erpnext": "14.30.6",
	"frappe": "14.40.3",
	"gateguard": "0.0.1",
	"hrms": "14.6.0",
	"india_compliance": "14.11.0",
	"payments": "0.0.1",
	"precihole": "0.0.1"
}
```
### Route
```
Form/Delivery Note/DN-JW2324-0098
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 47, in cancel
    doc.cancel()
  File "apps/frappe/frappe/model/document.py", line 1010, in cancel
    return self._cancel()
  File "apps/frappe/frappe/model/document.py", line 990, in _cancel
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1087, in run_post_save_methods
    self.run_method("on_cancel")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 272, in on_cancel
    self.repost_future_sle_and_gle()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 789, in repost_future_sle_and_gle
    create_repost_item_valuation_entry(args)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 1019, in create_repost_item_valuation_entry
    repost_entry.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1101, in run_post_save_methods
    self.run_method("on_change")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/frappe/frappe/automation/doctype/milestone_tracker/milestone_tracker.py", line 45, in evaluate_milestone
    frappe.get_doc("Milestone Tracker", d.get("name")).apply(doc)
AttributeError: 'str' object has no attribute 'get'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Delivery Note",
		"name": "DN-JW2324-0098"
	},
	"btn": {
		"jQuery360076048621588352881": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4042,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.cancel"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'str' object has no attribute 'get'"
}
```

### Module

stock

### Version

ERPNext: v14.30.6 (version-14)
Frappe Framework: v14.40.3 (version-14)

### Installation method

FrappeCloud

**Comment by precihole** [comment]
Resolved by bench migrate & restarting bench again
