### ISSUE TITLE
Error in version 14:Company GSTIN is a mandatory field for accounting of GST Accounts.

### ISSUE THREAD

**Issue by techomniflo** [frappe/erpnext#36187]
### Information about bug

I am just try to submit sales invoice in erpnext it show this error.

![image](https://github.com/frappe/erpnext/assets/86599018/6d8c5653-1124-411d-88ec-a1e2fde874da)

### Module

accounts

### Version

ERPNext: v14.25.1 (version-14)

Frappe Framework: v14.40.3 (version-14)

India Compliance: v14.12.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 269, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1037, in make_gl_entries
    make_gl_entries(
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 45, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 305, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 316, in make_entry
    gle.submit()
  File "apps/frappe/frappe/model/document.py", line 1005, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 984, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1048, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/gl_entry.py", line 18, in validate
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Company GSTIN is a mandatory field for accounting of GST Accounts.
```

**Comment by SvbZ3r0** [comment]
Add GST number for your customer and for your company. You can't submit a GST invoice without the GST numbers of all involved parties.

**Comment by techomniflo** [comment]
@SvbZ3r0  Already set for that and its also in reflected in sales invoice "contact and address" section

![image](https://github.com/frappe/erpnext/assets/86599018/22542929-6af4-4d30-98cd-0db73e6ff42a)

**Comment by SvbZ3r0** [comment]
That's weird. Probably a bug then.
You should ask here: https://github.com/resilient-tech/india-compliance since all India exclusive stuff is maintained in their repo.

**Comment by Anurangenie** [comment]
Having the same issue, did you end up figuring it out?
