### ISSUE TITLE
Creating a customer throws customer object has no attribute 'portal_users'

### ISSUE THREAD

**Issue by anandanatarajan** [frappe/erpnext#36216]
### Information about bug

my os is ubuntu 22.04.2 LTS when i tried to create a customer from erpnext the title error popped up. The details are
### App Versions
```
{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"hrms": "15.0.0-dev"
}
```
### Route
```
List/Customer/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 82, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1651, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 227, in save
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 316, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 338, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 269, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1061, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1289, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1271, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 86, in validate
    self.add_role_for_user()
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 176, in add_role_for_user
    for portal_user in self.portal_users:
AttributeError: 'Customer' object has no attribute 'portal_users'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"is_internal_customer\":0,\"language\":\"en\",\"so_required\":0,\"dn_required\":0,\"is_frozen\":0,\"disabled\":0,\"__run_link_triggers\":1,\"customer_name\":\"M/s. Base Control Tech\",\"customer_group\":\"Commercial\",\"territory\":\"Rest Of The World\",\"email_id\":\"jagannath@batpl.com\",\"email_address\":\"jagannath@batpl.com\"}"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.save"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'Customer' object has no attribute 'portal_users'"
}
```

### Module

selling

### Version

"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"hrms": "15.0.0-dev"

### Installation method

manual install

**Comment by GursheenK** [comment]
This field was added recently. The latest JSON code might not have been migrated yet. 

You can try `bench --site <your-site-name> migrate` so that the ERPNext Doctypes are updated. 

Please let us know if the error still persists by re-opening the issue.
