### ISSUE TITLE
can't create envent producer

### ISSUE THREAD

**Issue by aguspetti** [frappe/erpnext#36239]
### Information about bug

hello guy im have an issue when creating a event producer in my intance installed on frappe cloud, when I hit the save button it says:

frappe.exceptions.PermissionError: You are not permitted to access this resource.Function 

frappe.event_streaming.doctype.event_consumer.event_consumer.register_consumer is not whitelisted.

I belive this s a bug but maybe i miss configure something

![image](https://github.com/frappe/erpnext/assets/140256719/85abd5fb-24b8-489f-8d25-cedffab2f380)

### Module

other

### Version

"erpnext": "14.31.3",
"frappe": "14.41.0"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.31.3",
	"frappe": "14.41.0"
}
```
### Route
```
Form/Event Producer/new-event-producer-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 253, in insert
    self.run_method("before_insert")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1267, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1249, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 24, in before_insert
    self.create_event_consumer()
  File "apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 79, in create_event_consumer
    response = producer_site.post_api(
  File "apps/frappe/frappe/frappeclient.py", line 344, in post_api
    return self.post_process(res)
  File "apps/frappe/frappe/frappeclient.py", line 382, in post_process
    raise FrappeException(exc)
frappe.frappeclient.FrappeException: FrappeClient Request Failed

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 82, in execute_cmd
    is_whitelisted(method)
  File "apps/frappe/frappe/__init__.py", line 775, in is_whitelisted
    throw(msg, PermissionError, title="Method Not Allowed")
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: <details><summary>You are not permitted to access this resource.</summary>Function <strong>frappe.event_streaming.doctype.event_consumer.event_consumer.register_consumer</strong> is not whitelisted.</details>


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Event Producer\",\"name\":\"new-event-producer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"mantenimiento@spreadelectricsa.com.ar\",\"incoming_change\":0,\"producer_doctypes\":[{\"docstatus\":0,\"doctype\":\"Event Producer Document Type\",\"name\":\"new-event-producer-document-type-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"mantenimiento@spreadelectricsa.com.ar\",\"status\":\"Pending\",\"use_same_name\":0,\"unsubscribe\":0,\"has_mapping\":0,\"parent\":\"new-event-producer-1\",\"parentfield\":\"producer_doctypes\",\"parenttype\":\"Event Producer\",\"idx\":1,\"ref_doctype\":\"Issue\"}],\"producer_url\":\"http://spreadelectric.ddns.net:8001\",\"api_key\":\"##########\",\"user\":\"mantenimiento@spreadelectricsa.com.ar\",\"api_secret\":\"######\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360014310429120845681": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 670,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": ""
}
```
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14, then refresh and check again.

Everything is working fine. No problems were encountered in the latest version 14.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!

**Comment by htakawira** [comment]
Hello guys i am having repeated errors with event producer.

After setting up everything and trying approve the doctypes i get this error message.

Hello Henry I am trying the set the Event Streaming and am getting this error ### App Versions
{
  "erpnext": "14.65.3",
  "frappe": "14.67.1"
}
### Route
Form/Event Consumer/http://10.10.21.225
### Traceback
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 357, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1267, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1249, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/event_streaming/doctype/event_consumer/event_consumer.py", line 31, in on_update
    self.update_consumer_status()
  File "apps/frappe/frappe/event_streaming/doctype/event_consumer/event_consumer.py", line 50, in update_consumer_status
    event_producer = frappe._dict(event_producer)
TypeError: 'NoneType' object is not iterable

### Request Data
{
  "type": "POST",
  "args": {
    "doc": "{\"name\":\"http://10.10.21.225\",\"owner\":\"jmukwena@hwangecolliery.co.zw\",\"creation\":\"2024-03-20 19:47:27.372788\",\"modified\":\"2024-03-20 19:47:27.413111\",\"modified_by\":\"jmukwena@hwangecolliery.co.zw\",\"docstatus\":0,\"idx\":0,\"callback_url\":\"http://10.10.21.225\",\"api_key\":\"d60039b43980e28\",\"api_secret\":\"***************\",\"user\":\"jmukwena@hwangecolliery.co.zw\",\"incoming_change\":0,\"doctype\":\"Event Consumer\",\"consumer_doctypes\":[{\"name\":\"c867d4bbe9\",\"owner\":\"jmukwena@hwangecolliery.co.zw\",\"creation\":\"2024-03-20 19:47:27.372788\",\"modified\":\"2024-03-20 19:47:27.372788\",\"modified_by\":\"jmukwena@hwangecolliery.co.zw\",\"docstatus\":0,\"idx\":1,\"ref_doctype\":\"POS Invoice\",\"status\":\"Approved\",\"unsubscribed\":0,\"parent\":\"http://10.10.21.225\",\"parentfield\":\"consumer_doctypes\",\"parenttype\":\"Event Consumer\",\"doctype\":\"Event Consumer Document Type\"},{\"name\":\"f958c0ed1d\",\"owner\":\"jmukwena@hwangecolliery.co.zw\",\"creation\":\"2024-03-20 19:47:27.372788\",\"modified\":\"2024-03-20 19:47:27.372788\",\"modified_by\":\"jmukwena@hwangecolliery.co.zw\",\"docstatus\":0,\"idx\":2,\"ref_doctype\":\"Sales Invoice\",\"status\":\"Pending\",\"unsubscribed\":0,\"parent\":\"http://10.10.21.225\",\"parentfield\":\"consumer_doctypes\",\"parenttype\":\"Event Consumer\",\"doctype\":\"Event Consumer Document Type\"}],\"__last_sync_on\":\"2024-03-20T17:51:01.704Z\",\"__unsaved\":1}",
    "action": "Save"
  },
  "btn": {
    "jQuery36000414492771365093661": {
      "events": {
        "click": [
          {
            "type": "click",
            "origType": "click",
            "guid": 465,
            "namespace": ""
          }
        ]
      }
    }
  },
  "freeze": true,
  "headers": {},
  "error_handlers": {},
  "url": "/api/method/frappe.desk.form.save.savedocs"
}
### Response Data
{
  "exception": "TypeError: 'NoneType' object is not iterable"
}

**Comment by htakawira** [comment]
Could the above error be a bug in version 14 as well.
