### ISSUE TITLE
Server Error-Not able to Cancel Loan Repayment Entry

### ISSUE THREAD

**Issue by KBP-Civil** [frappe/erpnext#36446]
### Information about bug

Traceback (most recent call last):

File "apps/frappe/frappe/[app.py](http://app.py/)", line 66, in application

response = frappe.api.handle()

File "apps/frappe/frappe/[api.py](http://api.py/)", line 55, in handle

return frappe.handler.handle()

File "apps/frappe/frappe/[handler.py](http://handler.py/)", line 38, in handle

data = execute_cmd(cmd)

File "apps/frappe/frappe/[handler.py](http://handler.py/)", line 76, in execute_cmd

return [frappe.call](http://frappe.call/)(method, **frappe.form_dict)

File "apps/frappe/frappe/__init__.py", line 1474, in call

return fn(*args, **newargs)

File "apps/frappe/frappe/model/[workflow.py](http://workflow.py/)", line 143, in apply_workflow

doc.cancel()

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 1025, in cancel

return self._cancel()

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 1015, in _cancel

return [self.save](http://self.save/)()

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 312, in save

return self._save(*args, **kwargs)

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 366, in _save

[self.run](http://self.run/)_post_save_methods()

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 1090, in run_post_save_methods

[self.run](http://self.run/)_method("on_cancel")

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 943, in run_method

out = Document.hook(fn)(self, args, *kwargs)

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 1262, in composer

return composed(self, method, args, *kwargs)

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 1244, in runner

add_to_return_value(self, fn(self, args, *kwargs))

File "apps/frappe/frappe/model/[document.py](http://document.py/)", line 940, in fn

return method_object(*args, **kwargs)

File "apps/erpnext/erpnext/loan_management/doctype/loan_repayment/loan_[repayment.py](http://repayment.py/)", line 43, in on_cancel

self.update_repayment_schedule(cancel=1)

File "apps/erpnext/erpnext/loan_management/doctype/loan_repayment/loan_[repayment.py](http://repayment.py/)", line 268, in update_repayment_schedule

regenerate_repayment_schedule(self.against_loan, cancel)

File "apps/erpnext/erpnext/loan_management/doctype/loan_repayment/loan_[repayment.py](http://repayment.py/)", line 614, in regenerate_repayment_schedule

while balance_amount > 0:

TypeError: '>' not supported between instances of 'NoneType' and 'int'

### Module

other

### Version

ERPNext: v13.52.7 (HEAD)
Frappe Framework: v13.58.3 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @KBP-Civil,

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
Everything is working fine. No problems were encountered in the latest versions 14 and 15.

**For version 15**, the Loan Management module is located within the [Lending](https://github.com/frappe/lending) app. This is because the loan management module is separated from ERPNext and is referred to as [lending](https://github.com/frappe/lending).

If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
