### ISSUE TITLE
Cant add Zero Amount Free Items on a Validate Selling Price for Item Against Purchase Rate or Valuation Rate

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#36445]
### Information about bug

How do you give free items to clients if Validate Selling Price for Item Against Purchase Rate or Valuation Rate is enabled on the selling settings?

We cannot provide free items with zero amounts on invoices.

Creating a pricing rule is also not working, eventhough you put a checkmark on the free item.

### Module

selling

### Version

ERPNext: v13.52.7 (HEAD)
Frappe Framework: v13.58.3 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 25, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 334, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 263, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1054, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1262, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1244, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 88, in validate
    super(SalesInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 35, in validate
    self.validate_selling_price()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 285, in validate_selling_price
    throw_message(item.idx, item.item_name, last_valuation_rate_in_sales_uom, "valuation rate")
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 219, in throw_message
    title=_("Invalid Selling Price"),
  File "apps/frappe/frappe/__init__.py", line 512, in throw
    as_list=as_list,
  File "apps/frappe/frappe/__init__.py", line 480, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 435, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #1: Selling rate for item <b>Chicken Joy2</b> is lower than its <b>valuation rate</b>.
					Selling <b>net rate</b> should be atleast <b>10.12345679</b>.<br><br>Alternatively,
					you can disable selling price validation in <a href="https://erp./app/selling-settings/Selling%20Settings">Selling Settings</a> to bypass
					this validation.
```

**Comment by Nihantra-Patel** [comment]
Hi @Ponyooooo,

It's designed according to the user/client perceptive.

We no longer provide support for version 13 or older.
Kindly upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
