### ISSUE TITLE
/payment-success?redirect_to=%2Forders has error

### ISSUE THREAD

**Issue by Spixmaster** [frappe/erpnext#36474]
### Information about bug

I have set up a web store. After a purchase, the redirect throws an error. The redirect happens the the route `/payment-success?redirect_to=%2Forders`.

### Module

ecommerce

### Version

ERPNext: v14.32.1 (HEAD)
Frappe Framework: v14.42.0 (HEAD)
Hospitality: v0.0.1 (develop)
Frappe HR: v14.8.0 (HEAD)
Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 162, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 224, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/payments/payments/templates/pages/payment_success.py", line 11, in get_context
    doc = frappe.get_doc(frappe.local.form_dict.doctype, frappe.local.form_dict.docname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1196, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 64, in get_doc
    raise ValueError("First non keyword argument must be a string or dict")
ValueError: First non keyword argument must be a string or dict
```
```

**Comment by Nihantra-Patel** [comment]
Hi @Spixmaster,

Kindly upgrade to version 14 or 15, then refresh and check again.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!
