### ISSUE TITLE
TDS Computation Summary Error

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#36613]
### Information about bug

<img width="1440" alt="Screenshot 2023-08-12 at 7 07 09 PM" src="https://github.com/frappe/erpnext/assets/11851156/807efaa0-40d5-4524-ad5a-f6102dd7ae76">

### Module

accounts

### Version

Frappe Version-v14.44.0 (version-14)
Erpnext Version-v14.34.3 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
```
### Route
```
query-report/TDS Computation Summary
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 802, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 802, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/tds_computation_summary/tds_computation_summary.py", line 23, in execute
    ) = get_tds_docs(filters)
  File "apps/erpnext/erpnext/accounts/report/tds_payable_monthly/tds_payable_monthly.py", line 235, in get_tds_docs
    party = frappe.get_all(filters.get("party_type"), pluck="name")
  File "apps/frappe/frappe/__init__.py", line 1937, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1909, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 190, in execute
    self.columns = self.get_table_columns()
  File "apps/frappe/frappe/model/db_query.py", line 533, in get_table_columns
    return get_table_columns(self.doctype)
  File "apps/frappe/frappe/model/meta.py", line 75, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "apps/frappe/frappe/database/database.py", line 1176, in get_table_columns
    columns = self.get_db_table_columns("tab" + doctype)
TypeError: can only concatenate str (not "NoneType") to str

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "TDS Computation Summary",
		"filters": "{\"company\":\"Bastar Dairy Farm Pvt Ltd\",\"from_date\":\"2023-07-12\",\"to_date\":\"2023-08-12\"}",
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "TypeError: can only concatenate str (not \"NoneType\") to str"
}
```
```

**Comment by GursheenK** [comment]
Fixed via https://github.com/frappe/erpnext/pull/36568
