### ISSUE TITLE
On submitting Sales Invoices raising Error ''Debit and Credit not equal for Sales Invoice ...''

### ISSUE THREAD

**Issue by Sendipad** [frappe/erpnext#36698]
### Information about bug

could not submit a sales invoice as it said 
Debit and Credit not equal for Sales Invoice #{number of Sales Invoice}. Difference is **-88.0** :
however the grand total of sales invoice is 44.00 it is double the grand amount negatively: 

### Module

accounts

### Version

v14.45.0 (version-14)
v14.35.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 269, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1043, in make_gl_entries
    make_gl_entries(
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 42, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 297, in save_entries
    process_debit_credit_difference(gl_map)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 368, in process_debit_credit_difference
    raise_debit_credit_not_equal_error(debit_credit_diff, voucher_type, voucher_no)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 405, in raise_debit_credit_not_equal_error
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Debit and Credit not equal for Sales Invoice #S-1-23-0109. Difference is -88.0.
```

**Comment by Sendipad** [comment]
Sorry guys , I have solved it , the problem was with a server script that i have been using to validate the exchange rate of foreign currency before submitting Sales Invoice.
However That Script was working just fine But after the last update This problems appears!!!
