### ISSUE TITLE
Home Page Not Found after Login

### ISSUE THREAD

**Issue by trackomatic** [frappe/erpnext#36722]
### Information about bug

After updating my Local Setup to ERPNEXT 14.35.2, The Workspace for a user doesn't appear after login.

There are my setup details:

![image](https://github.com/frappe/erpnext/assets/140053831/31458a02-5764-4a08-919e-9ddc989aa219)

Here after login, nothing appears for user:

![image](https://github.com/frappe/erpnext/assets/140053831/714ebcf4-b115-4d98-831b-e8c7b97934c4)

Moreover, if you want to view the website after login, the home page is not found (404) and if you logout the user, then the website works fine..

![image](https://github.com/frappe/erpnext/assets/140053831/de5de7ae-89b2-488a-87e7-954b146dbef1)

![image](https://github.com/frappe/erpnext/assets/140053831/39b717e2-2651-46b4-9535-cccb64b217e0)

### Module

accounts, integrations

### Version

Frappe Version: 14.45.0
ERPNext Version: 14.35.2

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No Outcome from Issue. No Error Appearing on screen.
```

**Comment by Olawale1** [comment]
Also encountering this issue. The error below appears in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at frappe.views.Workspace.show_page (workspace.js:366:46)
    at frappe.views.Workspace.show (workspace.js:259:8)
    at workspace.js:243:26
```

As I mentioned in the forum https://discuss.frappe.io/t/workspace-not-loading-properly-in-recent-v14-versions/108935 I suspect this has to do with the Workspace Cache

Kindly help resolve 

Thanks

**Comment by PersistentDabbler** [comment]
I am also experiencing this error. It started after upgrading from V13 to V14.

**Comment by jiangangwu** [comment]
Seems to clear all cookie can solve the problem. 

This problem often comes after applying upgrade or migrate.
