### ISSUE TITLE
DB Dead Lock Error on Stock Ledger

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36835]
### Information about bug

dead lock error at stock ledger

### Module

stock

### Version

frappe 14.46.0
erpnext 14.36.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1163, in read
    self._read_result_packet(first_packet)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1236, in _read_result_packet
    self._read_rowdata_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1270, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 138, in repost
    repost_sl_entries(doc)
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 163, in repost_sl_entries
    repost_future_sle(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 224, in repost_future_sle
    obj = update_entries_after(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 375, in __init__
    self.initialize_previous_data(self.args)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 406, in initialize_previous_data
    previous_sle = get_previous_sle_of_current_voucher(args)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 1038, in get_previous_sle_of_current_voucher
    sle = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 199, in sql
    raise frappe.QueryDeadlockError(e)
frappe.exceptions.QueryDeadlockError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by rohitwaghchaure** [comment]
@thida-bcn Are you trying to repost multiple Repost Item Valuation entries at a same time?

**Comment by thida-bcn** [comment]
> @thida-bcn Are you trying to repost multiple Repost Item Valuation entries at a same time?

hello, system posted automatically due to back date stock transactions
