### ISSUE TITLE
Create new company error exception: "AttributeError: 'function' object has no attribute 'delete_value'"

### ISSUE THREAD

**Issue by khmergeo** [frappe/erpnext#36858]
### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.36.0",
	"frappe": "14.46.0",
	"frappe_helper": "0.3.3",
	"frappe_telegram": "0.0.1",
	"healthcare": "15.0.0-dev",
	"hrms": "15.0.0-dev",
	"lms": "1.0.0",
	"meeting": "0.0.1",
	"payments": "0.0.1",
	"restaurant_management": "1.3.7"
}
```
### Route
```
Form/Company/new-company-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/hrms/hrms/overrides/company.py", line 17, in make_company_fixtures
    make_salary_components(doc.country)
  File "apps/hrms/hrms/overrides/company.py", line 76, in make_salary_components
    doc.insert(ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1098, in run_post_save_methods
    self.clear_cache()
  File "apps/hrms/hrms/payroll/doctype/salary_component/salary_component.py", line 19, in clear_cache
    frappe.cache.delete_value(SALARY_COMPONENT_VALUES)
AttributeError: 'function' object has no attribute 'delete_value'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Company\",\"name\":\"new-company-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"country\":\"Cambodia\",\"is_group\":0,\"default_letter_head\":\"Sophy\",\"create_chart_of_accounts_based_on\":\"\",\"allow_account_creation_against_child_company\":0,\"enable_perpetual_inventory\":1,\"enable_provisional_accounting_for_non_stock_items\":0,\"auto_exchange_rate_revaluation\":0,\"auto_err_frequency\":\"Daily\",\"submit_err_jv\":0,\"idx\":0,\"monthly_sales_target\":0,\"total_monthly_sales\":0,\"credit_limit\":0,\"lft\":0,\"rgt\":0,\"company_name\":\"AppleTree\",\"abbr\":\"AT\",\"default_currency\":\"USD\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360093520280667466961": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1138,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'function' object has no attribute 'delete_value'"
}
```

### Module

accounts

### Version

erpnex: "14.36.0"
frappe: "14.46.0"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
{
	"exception": "AttributeError: 'function' object has no attribute 'delete_value'"
}
```

**Comment by nguyenth1810** [comment]
I got the same error while saving a new holiday list.

### App Versions
```
{
	"erpnext": "14.36.0",
	"frappe": "14.46.0",
	"hrms": "15.0.0-dev"
}
```
### Route
```
Form/Holiday List/new-holiday-list-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/hrms/hrms/utils/holiday_list.py", line 17, in invalidate_cache
    frappe.cache.delete_value(HOLIDAYS_BETWEEN_DATES)
AttributeError: 'function' object has no attribute 'delete_value'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Holiday List\",\"name\":\"new-holiday-list-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"nguyenth@unicloud.com.vn\",\"weekly_off\":\"\",\"idx\":0,\"total_holidays\":0,\"holidays\":[{\"docstatus\":0,\"idx\":1,\"holiday_date\":\"2023-09-02\",\"weekly_off\":0,\"description\":\"Independence Day\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-1\"},{\"docstatus\":0,\"idx\":2,\"holiday_date\":\"2023-09-04\",\"weekly_off\":0,\"description\":\"Independence Day (Observed)\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-2\"},{\"docstatus\":0,\"idx\":3,\"holiday_date\":\"2024-01-01\",\"weekly_off\":0,\"description\":\"International New Year's Day\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-3\"},{\"docstatus\":0,\"idx\":4,\"holiday_date\":\"2024-02-09\",\"weekly_off\":0,\"description\":\"Vietnamese New Year's Eve\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-4\"},{\"docstatus\":0,\"idx\":5,\"holiday_date\":\"2024-02-10\",\"weekly_off\":0,\"description\":\"Vietnamese New Year\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-5\"},{\"docstatus\":0,\"idx\":6,\"holiday_date\":\"2024-02-11\",\"weekly_off\":0,\"description\":\"The second day of Tet Holiday\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-6\"},{\"docstatus\":0,\"idx\":7,\"holiday_date\":\"2024-02-12\",\"weekly_off\":0,\"description\":\"The third day of Tet Holiday\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-7\"},{\"docstatus\":0,\"idx\":8,\"holiday_date\":\"2024-02-13\",\"weekly_off\":0,\"description\":\"The forth day of Tet Holiday\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-8\"},{\"docstatus\":0,\"idx\":9,\"holiday_date\":\"2024-02-14\",\"weekly_off\":0,\"description\":\"The fifth day of Tet Holiday\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-9\"},{\"docstatus\":0,\"idx\":10,\"holiday_date\":\"2024-04-18\",\"weekly_off\":0,\"description\":\"Hung Kings Commemoration Day\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-10\"},{\"docstatus\":0,\"idx\":11,\"holiday_date\":\"2024-04-30\",\"weekly_off\":0,\"description\":\"Liberation Day/Reunification Day\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-11\"},{\"docstatus\":0,\"idx\":12,\"holiday_date\":\"2024-05-01\",\"weekly_off\":0,\"description\":\"International Labor Day\",\"parent\":\"new-holiday-list-1\",\"parentfield\":\"holidays\",\"parenttype\":\"Holiday List\",\"doctype\":\"Holiday\",\"__islocal\":1,\"name\":\"new-holiday-12\"}],\"holiday_list_name\":\"123\",\"from_date\":\"2023-08-01\",\"to_date\":\"2024-07-31\",\"country\":\"VN\",\"subdivision\":\"\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360099481049124041961": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 476,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'function' object has no attribute 'delete_value'"
}
```
