### ISSUE TITLE
Depreciation Schedule Posting : Decimal Issue

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36905]
### Information about bug

for Depreciation, 
Schedule Posting is not working 
When we try to post manual from Asset, it's working well

### Module

accounts, assets

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/4e12d312-c04d-4e83-8924-e59bb87dd62e)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
error from schedule job log list
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 85, in execute
    frappe.get_attr(self.method)()
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 24, in post_depreciation_entries
    make_depreciation_entry(asset, date)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 113, in make_depreciation_entry
    je.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1052, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 58, in validate
    self.validate_debit_credit_amount()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 619, in validate_debit_credit_amount
    frappe.throw(_("Row {0}: Both Debit and Credit values cannot be zero").format(d.idx))
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row 1: Both Debit and Credit values cannot be zero
```

**Comment by anandbaburajan** [comment]
@thida-bcn we'll need more asset details like depreciation details, etc. You can just share the asset details in JSON (from the developer tools console using "cur_frm.doc").

**Comment by thida-bcn** [comment]
> @thida-bcn we'll need more asset details like depreciation details, etc. You can just share the asset details in JSON (from the developer tools console using "cur_frm.doc").

hello
[fa json.txt](https://github.com/frappe/erpnext/files/12582212/fa.json.txt)

**Comment by thida-bcn** [comment]
> @thida-bcn we'll need more asset details like depreciation details, etc. You can just share the asset details in JSON (from the developer tools console using "cur_frm.doc").

hello, I had send json file
any progress?

**Comment by khushi8112** [comment]
Hi @thida-bcn 
Just checking in – does this issue still persist? I’ve tried to replicate it on my instance but couldn’t reproduce the issue. If you’re still facing it, please feel free to reopen the issue, and we’ll be happy to take it forward from there.
