### ISSUE TITLE
Dead Lock Error On Repost Item Valuation

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36906]
### Information about bug

there was error on Repost Item Valuation

### Module

accounts, stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/8fdd3a26-9801-420d-8fb4-e0c38c9a268e)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/database/database.py", line 174, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1163, in read
    self._read_result_packet(first_packet)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1236, in _read_result_packet
    self._read_rowdata_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1270, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 139, in repost
    repost_gl_entries(doc)
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 193, in repost_gl_entries
    directly_dependent_transactions = _get_directly_dependent_vouchers(doc)
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 225, in _get_directly_dependent_vouchers
    affected_vouchers = get_future_stock_vouchers(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1258, in get_future_stock_vouchers
    future_stock_vouchers = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 199, in sql
    raise frappe.QueryDeadlockError(e)
frappe.exceptions.QueryDeadlockError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by rohitwaghchaure** [comment]
@thida-bcn kindly update your site to v14 and check
