### ISSUE TITLE
Cannot save production plan from material request

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#36977]
### App Versions
```
{
	"erpnext": "14.36.0",
	"frappe": "14.46.0",
	"helpdesk": "0.10.0",
	"hrms": "14.10.3",
	"india_compliance": "14.16.0"
}
```
### Route
```
Form/Production Plan/new-production-plan-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1051, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 42, in validate
    self.validate_sales_orders()
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 57, in validate_sales_orders
    msg = _("No items are available in the sales order {0} for production").format(sales_orders[0])
IndexError: list index out of range

```
### Response Data
```
{
	"exception": "IndexError: list index out of range"
}
```

### Module

manufacturing

### Version

"erpnext": "14.36.0",
"frappe": "14.46.0",
"helpdesk": "0.10.0",
"hrms": "14.10.3",
"india_compliance": "14.16.0"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1051, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 42, in validate
    self.validate_sales_orders()
  File "apps/erpnext/erpnext/manufacturing/doctype/production_plan/production_plan.py", line 57, in validate_sales_orders
    msg = _("No items are available in the sales order {0} for production").format(sales_orders[0])
IndexError: list index out of range
request.js:457:14
```

**Comment by viralkansodiya** [comment]
#36807 please update your version this error has been resolve
