### ISSUE TITLE
Error creating a sales order from quotation 

### ISSUE THREAD

**Issue by osamaerksosi** [frappe/erpnext#36990]
### Information about bug

when try to create sales order from quotation with lead and this lead has converted to customer I get this error 

File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 291, in set_missing_values
    for d in customer.get("sales_team"):
TypeError: 'NoneType' object is not iterable

**quotation.py** at def **_make_customer** when there customer linked to the lead it return only _customer name_ not the _full object_

### Module

selling

### Version

Frappe Version - 14.48.1
Erpnext Version - 14.38.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 263, in make_sales_order
    return _make_sales_order(source_name, target_doc)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 333, in _make_sales_order
    doclist = get_mapped_doc(
  File "apps/frappe/frappe/model/mapper.py", line 144, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 291, in set_missing_values
    for d in customer.get("sales_team"):
TypeError: 'NoneType' object is not iterable
```

**Comment by osamaerksosi** [comment]
@nabinhait

**Comment by viralkansodiya** [comment]
https://github.com/frappe/erpnext/blob/develop/erpnext/selling/doctype/quotation/quotation.py

please check 291 no line now code is 
for d in customer.get("sales_team") or  []:

check your code if still this error is coming please coming

**Comment by osamaerksosi** [comment]
problem in _make_customer function in case founding the linked customer with the lead the function return only the name of the customer.
in my opinion it should return the full object 
you maybe should edit this line
[https://github.com/frappe/erpnext/blob/develop/erpnext/selling/doctype/quotation/quotation.py#L478](url)

**Comment by s-aga-r** [comment]
@osamaerksosi Please update your instance to the latest version in order to get the issue resolved.

ref: 
- https://github.com/frappe/erpnext/issues/35322
- https://github.com/frappe/erpnext/pull/35355
