### ISSUE TITLE
Broken Payment Request dependency

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37004]
### Information about bug

After several payment module were moved into their own app, ERPNext initially was dependent on the Payments app. Now that this hard dependency has been removed, a few leftovers are causing errors and breaking unittests.

I think, the Payment Gateway Account should move to Payments as well. Without any Payment Gateways it is of no use.

![IMG_1398](https://github.com/frappe/erpnext/assets/46800703/9aaa1aa5-5581-4673-a279-69156bbf8eb7)
![IMG_1397](https://github.com/frappe/erpnext/assets/46800703/03e0c291-3497-4cb3-a068-9b0cf8de3a58)

### Module

other

### Version

ERPNext dev on Frappe dev

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```
bench --site ap15 run-tests
ERROR   PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('HASH', '#0000001a', 1, 3198)
ERROR   PropertyValue: Unknown syntax or no value: 0 3px 6px #0000001a
ERROR   CSSStyleDeclaration: Syntax Error in Property: box-shadow:0 3px 6px #0000001a
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/erpnext15/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/erpnext15/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/erpnext15/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/erpnext15/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/erpnext15/apps/frappe/frappe/commands/utils.py", line 783, in run_tests
    ret = frappe.test_runner.main(
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 111, in main
    ret = run_all_tests(app, verbose, profile, failfast=failfast, junit_xml_output=junit_xml_output)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 173, in run_all_tests
    _add_test(app, path, filename, verbose, test_suite)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 339, in _add_test
    make_test_records(doctype, verbose, commit=True)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 357, in make_test_records
    make_test_records(options, verbose, force, commit=commit)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 357, in make_test_records
    make_test_records(options, verbose, force, commit=commit)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 357, in make_test_records
    make_test_records(options, verbose, force, commit=commit)
  [Previous line repeated 5 more times]
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 351, in make_test_records
    for options in get_dependencies(doctype):
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 374, in get_dependencies
    module, test_module = get_modules(doctype)
  File "/home/frappe/erpnext15/apps/frappe/frappe/test_runner.py", line 364, in get_modules
    test_module = load_doctype_module(doctype, module, "test_")
  File "/home/frappe/erpnext15/apps/frappe/frappe/modules/utils.py", line 234, in load_doctype_module
    module = module or get_doctype_module(doctype)
  File "/home/frappe/erpnext15/apps/frappe/frappe/modules/utils.py", line 225, in get_doctype_module
    frappe.throw(_("DocType {} not found").format(doctype), exc=frappe.DoesNotExistError)
  File "/home/frappe/erpnext15/apps/frappe/frappe/__init__.py", line 570, in throw
    msgprint(
  File "/home/frappe/erpnext15/apps/frappe/frappe/__init__.py", line 542, in msgprint
    _raise_exception()
  File "/home/frappe/erpnext15/apps/frappe/frappe/__init__.py", line 491, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType Payment Gateway not found
```

**Comment by bosue** [comment]
This exception occurs every single time I‘m trying to run unit tests. I wonder how it doesn’t make unit testing fail here…

**Comment by s-aga-r** [comment]
> This exception occurs every single time I‘m trying to run unit tests. I wonder how it doesn’t make unit testing fail here…

https://github.com/s-aga-r/erpnext/blob/38aebf65e2c9a93e3fc0d999668040f471c55b51/.github/helper/site_config_mariadb.json#L14

**Comment by bosue** [comment]
I see. From what I can tell, the soft dependency however doesn’t throw any notice, so users may not even know. Either way the problem‘s going to be gone soon. Thanks @s-aga-r!

**Comment by s-aga-r** [comment]
@bosue `Payments` app is a soft dependency in production but is required in a testing environment.

ref: https://github.com/frappe/erpnext/pull/33245

**Comment by bosue** [comment]
> @bosue Payments app is a soft dependency in production but is required in a testing environment.
> 
> ref: https://github.com/frappe/erpnext/pull/33245

I know, I know. Seen this and am personally fine, thanks. 🙏
