### ISSUE TITLE
Print button does not work when viewing a tree

### ISSUE THREAD

**Issue by messam10** [frappe/erpnext#37088]
### Information about bug

When I display as a tree in any Doctype, I cannot print it as shown in the video below.

![print error](https://github.com/frappe/erpnext/assets/49818381/537d0fd4-0d16-4347-949e-41f2a2619017)

And also does not appear to me if there is Error!

### Module

accounts, stock, any tree view

#### Installed Apps

**ERPNext:** v13.52.15 (version-13)

**Frappe Framework:** v13.58.11 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
microtemplate.js:141 Uncaught TypeError: frappe.assets.bundled_asset is not a function
    at frappe.render_tree (microtemplate.js:141:45)
    at treeview.js:380:11
    at print_utils.js:73:4
    at frappe.ui.Dialog.<anonymous> (messages.js:99:3)
    at HTMLButtonElement.<anonymous> (dialog.js:155:20)
    at HTMLButtonElement.dispatch (jquery.min.js:3:7537)
    at r.handle (jquery.min.js:3:5620)
frappe.render_tree @ microtemplate.js:141
(anonymous) @ treeview.js:380
(anonymous) @ print_utils.js:73
(anonymous) @ messages.js:99
(anonymous) @ dialog.js:155
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```

**Comment by messam10** [comment]
I discovered that the error is in Frappe and not from ERPNext
And I created a issue in Frappe Project
[Link](https://github.com/frappe/frappe/issues/22406)
