### ISSUE TITLE
[BUG] : check permission error in Portal check_parent_permission

### ISSUE THREAD

**Issue by aliarslan61** [frappe/erpnext#37080]
### Information about bug

when customer or desk user is logging in to the portal over view Website, im getting this permission error check_parent_permission
index.js
if (contacts && contacts.message && contacts.message.length > 0) {
            const contact_name = contacts.message[0].name;

            const links = await frappe.call({
                method: "frappe.client.get_list",
                args: {
                    doctype: "Dynamic Link",
                    filters: {
                        "parenttype": "Contact",
                        "parent": contact_name,
                        "link_doctype": "Customer"
                    },
                    fields: ["link_name"],
                    limit_page_length: 1
                }
            });

### Module

portal

### Version

ERPNext: v14.39.0 (version-14)
Frappe Framework: v14.48.1 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
website.js:177 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 91, in application
    response = frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 47, in get_list
    check_parent_permission(parent, doctype)
  File "apps/frappe/frappe/model/db_query.py", line 1166, in check_parent_permission
    raise frappe.PermissionError
frappe.exceptions.PermissionError
```

**Comment by aliarslan61** [comment]
as a workaround i changed below method in client.py -> comment lines 46 and 47 add line 61 and 62 (line nos are from client.py)

``` @frappe.whitelist()
def get_list(
	doctype,
	fields=None,
	filters=None,
	order_by=None,
	limit_start=None,
	limit_page_length=20,
	parent=None,
	debug=False,
	as_dict=True,
	or_filters=None,
):
	"""Returns a list of records by filters, fields, ordering and limit

	:param doctype: DocType of the data to be queried
	:param fields: fields to be returned. Default is `name`
	:param filters: filter list by this dict
	:param order_by: Order by this fieldname
	:param limit_start: Start at this index
	:param limit_page_length: Number of records to be returned (default 20)"""
	# if frappe.is_table(doctype):
	# 	check_parent_permission(parent, doctype)

	args = frappe._dict(
		doctype=doctype,
		parent_doctype=parent,
		fields=fields,
		filters=filters,
		or_filters=or_filters,
		order_by=order_by,
		limit_start=limit_start,
		limit_page_length=limit_page_length,
		debug=debug,
		as_list=not as_dict,
	)
	if frappe.is_table(doctype):
		args.ignore_permissions = True
      
	validate_args(args)
	return frappe.get_list(**args)

```

**Comment by aliarslan61** [comment]
@frappe.whitelist()
def get_list(
	doctype,
	fields=None,
	filters=None,
	order_by=None,
	limit_start=None,
	limit_page_length=20,
	parent=None,
	debug=False,
	as_dict=True,
	or_filters=None,
):
	"""Returns a list of records by filters, fields, ordering and limit

	:param doctype: DocType of the data to be queried
	:param fields: fields to be returned. Default is `name`
	:param filters: filter list by this dict
	:param order_by: Order by this fieldname
	:param limit_start: Start at this index
	:param limit_page_length: Number of records to be returned (default 20)"""
	# if frappe.is_table(doctype):
	# 	check_parent_permission(parent, doctype)

	args = frappe._dict(
		doctype=doctype,
		parent_doctype=parent,
		fields=fields,
		filters=filters,
		or_filters=or_filters,
		order_by=order_by,
		limit_start=limit_start,
		limit_page_length=limit_page_length,
		debug=debug,
		as_list=not as_dict,
	)
	if frappe.is_table(doctype):
		args.ignore_permissions = True
      
	validate_args(args)
	return frappe.get_list(**args)

**Comment by DipenFrappe** [comment]
Replicate the issue in the latest version, and if it replicates, help with steps and screenshots/GIFs
