### ISSUE TITLE
Deadlock on stock entry submit

### ISSUE THREAD

**Issue by niyazrazak** [frappe/erpnext#37179]
----------------------------------------------
ERPNext: v14.37.1 (version-14)
Frappe Framework: v14.47.2 (version-14)
-------------------------------------------------

`Traceback (most recent call last):
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1164, in read
    self._read_result_packet(first_packet)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1240, in _read_result_packet
    self._read_rowdata_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1274, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/reapit/reapit/tasks.py", line 94, in material_issue
    doc.submit()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 176, in submit
    self._submit()
  File "apps/frappe/frappe/model/document.py", line 987, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 307, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 358, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1093, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 203, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1190, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 513, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 86, in make_sl_entries
    repost_current_voucher(args, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 102, in repost_current_voucher
    update_entries_after(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 395, in __init__
    self.build()
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 443, in build
    self.process_sle_against_current_timestamp()
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 464, in process_sle_against_current_timestamp
    sl_entries = self.get_sle_against_current_voucher()
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 471, in get_sle_against_current_voucher
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 226, in sql
    raise frappe.QueryDeadlockError(e) from e
frappe.exceptions.QueryDeadlockError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')`

**Comment by ankush** [comment]
If you have access to db server run `SHOW ENGINE INNODB STATUS` after deadlock occurs. 

It's really hard to fix deadlock without that information.
