### ISSUE TITLE
Not able to access a doctype 

### ISSUE THREAD

**Issue by buddhiraz** [frappe/erpnext#37271]
### Information about bug

I am getting this error in my app which fetch order data from Unicommerce and store each orders in Unicommerce Orders Doctype.

### Module

other

### Version

ERPNext: v14.13.0 (version-14)

Frappe Framework: v14.23.0 (version-14)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.13.0",
	"frappe": "14.23.0",
	"hrms": "1.0.0",
	"khanal_tech_integrations": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Unicommerce Orders/P60LG1DVY9L0
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1595, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 37, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "apps/frappe/frappe/__init__.py", line 1184, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 165, in load_from_db
    frappe.db.get_values(
  File "apps/frappe/frappe/database/database.py", line 592, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 822, in _get_values_from_table
    return self.sql(query, as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/database/database.py", line 218, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'parent' in 'where clause'")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Unicommerce Orders",
		"name": "LD194N8V5N6D"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoc"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'parent' in 'where clause'\")"
}
```
```

**Comment by buddhiraz** [comment]
In console I am getting this :

OperationalError: (1054, "Unknown column 'parent' in 'where clause'")


Full error is hereby : 

In [1]: order_doc = frappe.get_doc('Unicommerce Orders','SLP4074307627')
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File <ipython-input-1-fc91286f0adf>:1, in <cell line: 1>()
----> 1 order_doc = frappe.get_doc('Unicommerce Orders','SLP4074307627')

File ~/frappe-bench/apps/frappe/frappe/__init__.py:1184, in get_doc(*args, **kwargs)
   1167 """Return a `frappe.model.document.Document` object of the given type and name.
   1168 
   1169 :param arg1: DocType name as string **or** document JSON.
   (...)
   1180 
   1181 """
   1182 import frappe.model.document
-> 1184 doc = frappe.model.document.get_doc(*args, **kwargs)
   1186 # Replace cache if stale one exists
   1187 if (key := can_cache_doc(args)) and cache().hexists("document_cache", key):

File ~/frappe-bench/apps/frappe/frappe/model/document.py:74, in get_doc(*args, **kwargs)
     72 controller = get_controller(doctype)
     73 if controller:
---> 74 	return controller(*args, **kwargs)
     76 raise ImportError(doctype)

File ~/frappe-bench/apps/frappe/frappe/model/document.py:106, in Document.__init__(self, *args, **kwargs)
    103 	# for_update is set in flags to avoid changing load_from_db signature
    104 	# since it is used in virtual doctypes and inherited in child classes
    105 	self.flags.for_update = kwargs.get("for_update")
--> 106 	self.load_from_db()
    107 	return
    109 if isinstance(args[0], dict):
    110 	# first argument is a dict

File ~/frappe-bench/apps/frappe/frappe/model/document.py:165, in Document.load_from_db(self)
    161 		self.set(df.fieldname, [])
    162 		continue
    164 	children = (
--> 165 		frappe.db.get_values(
    166 			df.options,
    167 			{"parent": self.name, "parenttype": self.doctype, "parentfield": df.fieldname},
    168 			"*",
    169 			as_dict=True,
    170 			order_by="idx asc",
    171 			for_update=self.flags.for_update,
    172 		)
    173 		or []
    174 	)
    176 	self.set(df.fieldname, children)
    178 # sometimes __setup__ can depend on child values, hence calling again at the end

File ~/frappe-bench/apps/frappe/frappe/database/database.py:592, in Database.get_values(self, doctype, filters, fieldname, ignore, as_dict, debug, order_by, update, cache, for_update, run, pluck, distinct, limit)
    590 	if order_by:
    591 		order_by = "modified" if order_by == "KEEP_DEFAULT_ORDERING" else order_by
--> 592 	out = self._get_values_from_table(
    593 		fields=fields,
    594 		filters=filters,
    595 		doctype=doctype,
    596 		as_dict=as_dict,
    597 		debug=debug,
    598 		order_by=order_by,
    599 		update=update,
    600 		for_update=for_update,
    601 		run=run,
    602 		pluck=pluck,
    603 		distinct=distinct,
    604 		limit=limit,
    605 	)
    606 except Exception as e:
    607 	if ignore and (frappe.db.is_missing_column(e) or frappe.db.is_table_missing(e)):
    608 		# table or column not found, return None

File ~/frappe-bench/apps/frappe/frappe/database/database.py:822, in Database._get_values_from_table(self, fields, filters, doctype, as_dict, debug, order_by, update, for_update, run, pluck, distinct, limit)
    819 if fields == "*" and not isinstance(fields, (list, tuple)) and not isinstance(fields, Criterion):
    820 	as_dict = True
--> 822 return self.sql(query, as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)

File ~/frappe-bench/apps/frappe/frappe/database/database.py:218, in Database.sql(self, query, values, as_dict, as_list, formatted, debug, ignore_ddl, as_utf8, auto_commit, update, explain, run, pluck)
    215 query, values = self._transform_query(query, values)
    217 try:
--> 218 	self._cursor.execute(query, values)
    219 except Exception as e:
    220 	if self.is_syntax_error(e):

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py:148, in Cursor.execute(self, query, args)
    144     pass
    146 query = self.mogrify(query, args)
--> 148 result = self._query(query)
    149 self._executed = query
    150 return result

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py:310, in Cursor._query(self, q)
    308 self._last_executed = q
    309 self._clear_result()
--> 310 conn.query(q)
    311 self._do_get_result()
    312 return self.rowcount

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py:548, in Connection.query(self, sql, unbuffered)
    546     sql = sql.encode(self.encoding, "surrogateescape")
    547 self._execute_command(COMMAND.COM_QUERY, sql)
--> 548 self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    549 return self._affected_rows

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py:775, in Connection._read_query_result(self, unbuffered)
    773 else:
    774     result = MySQLResult(self)
--> 775     result.read()
    776 self._result = result
    777 if result.server_status is not None:

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py:1156, in MySQLResult.read(self)
   1154 def read(self):
   1155     try:
-> 1156         first_packet = self.connection._read_packet()
   1158         if first_packet.is_ok_packet():
   1159             self._read_ok_packet(first_packet)

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py:725, in Connection._read_packet(self, packet_type)
    723     if self._result is not None and self._result.unbuffered_active is True:
    724         self._result.unbuffered_active = False
--> 725     packet.raise_for_error()
    726 return packet

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py:221, in MysqlPacket.raise_for_error(self)
    219 if DEBUG:
    220     print("errno =", errno)
--> 221 err.raise_mysql_exception(self._data)

File ~/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py:143, in raise_mysql_exception(data)
    141 if errorclass is None:
    142     errorclass = InternalError if errno < 1000 else OperationalError
--> 143 raise errorclass(errno, errval)

OperationalError: (1054, "Unknown column 'parent' in 'where clause'")
