### ISSUE TITLE
Bug: "Work Order Operation" Missing Permissions

### ISSUE THREAD

**Issue by 0FiRE0** [frappe/erpnext#37305]
### Information about bug

When the user opens the "Manufacturing Dashboard", a missing permission error shows up as follows: (Noting that all permissions are granted, and this error is showing even for the Admin user)
Highlighting that there is a missing permission to access the "Work Order Operation" doctype.

![image](https://github.com/frappe/erpnext/assets/19993814/1029983c-2fc3-483f-ae59-3ca48f53a9a2)

And when I checked the "Role Permissions Manager", no roles were given permission to access it:

![image](https://github.com/frappe/erpnext/assets/19993814/12345858-f99d-4ac4-9af5-2711f5431ce1)

And when I try to grant access permission to the "Manufacturing Manager", the doctype field is disabled and not able to select the "Work Order Operation" at all.
![image](https://github.com/frappe/erpnext/assets/19993814/ee8122d2-939e-475a-a97b-594429e5a77b)

### Module

manufacturing

### Version

Frappe: v14.51.0
ERPNext: v14.41.1

### Installation method

docker

**Comment by niraj2477** [comment]
@0FiRE0 
`Work Order Operation` is Child DOCTYPE.
Can you please share steps you followed?

**Comment by 0FiRE0** [comment]
@niraj2477 Regarding the steps, I have just opened the "Manufacturing" dashboard.
Even with a fresh installation, the issue shows up.
And the user which was used is the "Administrator" and tried with other users who have full access as well.

**Comment by OmelMedina** [comment]
Hey,

I'm having the same issue with ERPnext v15. Although unlike @0FiRE0, I do get an error code with the administrator account logged in. Hopefully this will help with solving the problem


### App Versions
```
{
	"erpnext": "15.0.0",
	"frappe": "15.0.1"
}
```
### Route
```
dashboard-view/Manufacturing
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/utils/dashboard.py", line 26, in wrapper
    results = generate_and_cache_results(kwargs, function, cache_key, chart)
  File "apps/frappe/frappe/utils/dashboard.py", line 41, in generate_and_cache_results
    results = function(
  File "apps/frappe/frappe/desk/doctype/dashboard_chart/dashboard_chart.py", line 144, in get
    chart_config = get_chart_config(chart, filters, timespan, timegrain, from_date, to_date)
  File "apps/frappe/frappe/desk/doctype/dashboard_chart/dashboard_chart.py", line 210, in get_chart_config
    data = frappe.db.get_list(
  File "apps/frappe/frappe/database/database.py", line 698, in get_list
    return frappe.get_list(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1948, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 201, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 241, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column '_unit' in 'order clause'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"chart_name": "Completed Operation",
		"filters": "[[\"Work Order Operation\",\"docstatus\",\"=\",1,false]]",
		"refresh": 1,
		"time_interval": null,
		"timespan": null,
		"from_date": null,
		"to_date": null,
		"heatmap_year": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.doctype.dashboard_chart.dashboard_chart.get",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column '_unit' in 'order clause'\")",
	"exc_type": "OperationalError"
}
```

**Comment by PITPL-Akshay-Prajapati** [comment]
Facing same issue.Is there any solution?
![image](https://github.com/frappe/erpnext/assets/95674015/06ba31a6-7400-4a52-8d74-e87d662d0c0f)
![image](https://github.com/frappe/erpnext/assets/95674015/dca15af4-02b9-48c4-bf9a-d4b3bd2d40ea)
