### ISSUE TITLE
Facing weird error in payroll creating.. KeyError: 'salary_slip_based_on_timesheet'

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#37348]
### Information about bug

I was running a payroll entry and selected Frequency as monthly as usual and on selecting the employee, it throws that error.
I was expecting that I would select the employee and continue to create payroll entry.

Kindly help I can continue

### Module

HR

### Version

Frappe Chat: v0.0.1 (main)
ERPNext: v14.41.2 (version-14)
Frappe Framework: v14.51.0 (version-14)
Frappe HR: v14.12.1 (version-14)
Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"erpnext": "14.41.2",
	"frappe": "14.51.0",
	"hrms": "14.12.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Payroll Entry/HR-PRUN-2023-00007
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 37, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 108, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 85, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 2417, in wrapper
    return fn(**kwargs)
  File "apps/hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py", line 1370, in employee_query
    filters.pop("salary_slip_based_on_timesheet")
KeyError: 'salary_slip_based_on_timesheet'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Employee",
		"ignore_user_permissions": 0,
		"reference_doctype": "Payroll Employee Detail",
		"query": "hrms.payroll.doctype.payroll_entry.payroll_entry.employee_query",
		"filters": "{\"company\":\"SITEFIX PAINTS & HARDWARE\",\"start_date\":\"2023-10-01\",\"end_date\":\"2023-10-31\",\"payroll_frequency\":\"Monthly\",\"payroll_payable_account\":\"2120 - Payroll Payable - SP&H\",\"currency\":\"KES\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link"
}
```
### Response Data
```
{
	"exception": "KeyError: 'salary_slip_based_on_timesheet'"
}
```
```

**Comment by viralkansodiya** [comment]
@jaqobk https://github.com/frappe/erpnext/issues/37348
in next update it will resolve
