### ISSUE TITLE
Payment Reco Issue

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#37406]
### Information about bug

We have made Journal Entry as opening balance of Import Supplier

And this year we have made paymennt using payment entries

https://github.com/frappe/erpnext/assets/21578167/2a250917-73db-46ac-b9ca-07974d4d27f7

### Module

accounts

### Version

ERPNext: v14.41.2 (version-14)

Frappe Framework: v14.51.0 (version-14)

Frappe HR: v14.12.1 (version-14)

India Compli

Uploading Screen Recording 2023-10-09 at 12.58.17 PM.mov…

ance: v14.16.2 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 306, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 399, in reconcile
    self.reconcile_allocations()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 373, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe)
  File "apps/erpnext/erpnext/accounts/utils.py", line 468, in reconcile_against_document
    update_reference_in_payment_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 660, in update_reference_in_payment_entry
    payment_entry.make_exchange_gain_loss_journal()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1127, in make_exchange_gain_loss_journal
    je = create_gain_loss_journal(
  File "apps/erpnext/erpnext/accounts/utils.py", line 1939, in create_gain_loss_journal
    journal_entry.save()
  File "apps/frappe/frappe/model/document.py", line 307, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 329, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1053, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 61, in validate
    self.validate_against_jv()
  File "apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 499, in validate_against_jv
    dr_or_cr = "debit" if d.credit > 0 else "credit"
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by aakvatech** [comment]
Faced this on FC as well

The fix is to change 
```dr_or_cr = "debit" if d.credit > 0 else "credit"```

to

```dr_or_cr = "debit" if (d.credit or 0) > 0 else "credit"```

**Comment by dineshpanchal93** [comment]
@aakvatech Thank you

But i think frappe team should update this in their v14 repo.

**Comment by yrestom** [comment]
I am facing the same issue

**Comment by ruthra-kumar** [comment]
@dineshpanchal93 
Is the issue fixed post this change https://github.com/frappe/erpnext/pull/38321 ?

**Comment by Nandhinidevi123** [comment]
@ruthra-kumar 
Yes fixed. - https://github.com/frappe/erpnext/pull/38321
