### ISSUE TITLE
Manufacture Stock Entry error if manufactured uom is different

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#37413]
### Information about bug

Stock Entry calculates needed qty when saving if stock entry type is manufacture.
But stock entry doesn't take into account the stock conversions.

So, when we are creating 288 Kg of goods with 288 Kg (But 600 meters) of raw materials it throws an exception.
<img width="1710" alt="image" src="https://github.com/frappe/erpnext/assets/710051/92a01db4-5de2-4444-801c-6adb950d09f8">

We can resolve it by changing stock entry validation from this
```	def validate_fg_completed_qty(self):
		item_wise_qty = {}
		if self.purpose == "Manufacture" and self.work_order:
			for d in self.items:
				if d.is_finished_item:
					item_wise_qty.setdefault(d.item_code, []).append(d.qty)
```

to this:
```	def validate_fg_completed_qty(self):
		item_wise_qty = {}
		if self.purpose == "Manufacture" and self.work_order:
			for d in self.items:
				if d.is_finished_item:
					#item_wise_qty.setdefault(d.item_code, []).append(d.qty)
					item_wise_qty.setdefault(d.item_code, []).append(d.transfer_qty if d.transfer_qty else d.qty)
```

### Module

stock, manufacturing

### Version

Frappe Framework: v14.36.1 (version-14)
ERPNext: v14.24.3 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 140, in validate
    self.validate_fg_completed_qty()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 472, in validate_fg_completed_qty
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: The finished product <strong>Onur</strong> quantity <strong>600.0</strong> and For Quantity <strong>288</strong> cannot be different
```

**Comment by mihir-kandoi** [comment]
Can you give us the exact reproduction steps?

**Comment by TurkerTunali** [comment]
I can confirm this issue still exists in v15 and v16-develop, but it has evolved and is now harder to reproduce due to frontend behavior masking the backend bug.

### Current Behavior: Frontend Auto-Update (Main Issue)

Steps to reproduce:

    Create Item "TEST FG" with Stock UOM: Kg, add alternate UOM: Meter (conversion factor: 2)

    Create BOM with 1 Kg TEST FG output

    Create Work Order for 4 Kg

    Create Stock Entry (Manufacture):

        Purpose: Manufacture

        For Quantity: 4 Kg

        Get items from Work Order

        In Items table, change finished goods row:

            UOM: Meter

            Qty: 2 (equals 4 Kg in stock UOM)

What happens: The system automatically changes For Quantity (fg_completed_qty) from 4 Kg to 2 Kg as soon as you modify the qty in items table.

Problem: You intended to manufacture 4 Kg (2 Meter), but the system now records only 2 Kg manufactured, making multi-UOM manufacturing impossible and it sets the manufactured qty as 2 in Work Order although we've produced 4.

Root Cause: stock_entry.js lines 1052-1057 and 1009-1020 auto-recalculate fg_completed_qty on every qty change without respecting UOM conversions.

### Backend Validation Still Has UOM Mismatch Bug

In v15 (if you could bypass frontend), the error was:
"The finished product TEST FG quantity 2.0 and For Quantity 4 cannot be different"

In v16-develop, the validation logic changed but the same UOM comparison bug exists - it still compares d.qty (UOM) against fg_completed_qty (stock UOM).

This would cause incorrect process loss calculations if the frontend didn't prevent reaching this code.

**Comment by DipenFrappe** [comment]
Multiple UOMs are not supported in the manufacturing flow
