### ISSUE TITLE
UnboundLocalError: local variable 'grand_total' referenced before assignment

### ISSUE THREAD

**Issue by zaengit** [frappe/erpnext#37461]
### Information about bug

![Screenshot_20231011_195719](https://github.com/frappe/erpnext/assets/31380073/a8972f3f-ca54-457b-93f7-115396b4c607)

after click pay 
error UnboundLocalError: local variable 'grand_total' referenced before assignment

### Module

accounts

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v15.x.x-develop () (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1671, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 408, in make_payment_request
    grand_total = get_amount(ref_doc, gateway_account.get("payment_account"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 518, in get_amount
    if grand_total > 0:
UnboundLocalError: local variable 'grand_total' referenced before assignment
```

**Comment by IMS94** [comment]
We encounter the same issue in erpnext when creating a payment request for a sales invoice.
```python
File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 408, in make_payment_request
    grand_total = get_amount(ref_doc, gateway_account.get("payment_account"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 518, in get_amount
    if grand_total > 0:
UnboundLocalError: local variable 'grand_total' referenced before assignment
```

**Comment by deepeshgarg007** [comment]
@zaendev This issue should be resolved now, please update your sites and then try again.
