### ISSUE TITLE
Accounts Receivable Report Loading Issue

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#37561]
### Information about bug

if Invoice count is more than 100000

request.js:352 TypeError: Cannot read properties of undefined (reading 'responseText')
    at 200 (request.js:128:61)
    at Object.<anonymous> (request.js:345:6)
    at V (jquery.js:3500:31)
    at Object.fireWith [as rejectWith] (jquery.js:3630:7)
    at S0 (jquery.js:9798:14)
    at XMLHttpRequest.<anonymous> (jquery.js:10057:9)

### Module

accounts

### Version

ERPNext: v14.37.1 (version-14)

Frappe Framework: v14.47.1 (version-14)

### Installation method

None

![image](https://github.com/frappe/erpnext/assets/6947417/b38b00fa-ad60-4564-8d9f-b1b54079ae08)

**Comment by deepeshgarg007** [comment]
@vishdha This is not replicable on any site right now, closing this. Reopen if the issue still persists.
