### ISSUE TITLE
Encountering the following error on Sales Order conversion to a Delivery Note in version 15

### ISSUE THREAD

**Issue by PashieCharuma** [frappe/erpnext#37566]
### Information about bug

Encountering the following error on Sales Order conversion to a Delivery Note in version 15
![Sales Order to Delivery Note Conversion Error](https://github.com/frappe/erpnext/assets/148335341/fbeaf145-33a0-4f5a-9bf7-1c984216e2ed)

### Module

selling

### Version

ERPNext: v15.0.0-dev (HEAD)

Frappe Framework: v15.0.0-dev (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Not permitted
Please specify a valid parent DocType for Delivery Note Item
Insufficient Permission for Delivery Note Item (create)
```

**Comment by s-aga-r** [comment]
@PashieCharuma Could you provide us with the browser console log?

**Comment by PashieCharuma** [comment]
@s-aga-r Browser Console Log

Deprecation warning: value provided is not in a moment.js:287 recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:3)
    at jn (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:24628)
    at mr (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28419)
    at Xi (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28284)
    at Ki (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28002)
    at Zn (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28780)
    at Fe (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:4:112815)
    at Function.ne [as tz] (https://sitename.erpnext.com/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:61602)
    at Object.convert_to_user_tz (https://sitename.erpnext.com/assets/frappe/dist/js/desk.bundle.TTIWYCMV.js:716:442)
    at ea (https://sitename.erpnext.com/assets/frappe/dist/js/desk.bundle.TTIWYCMV.js:710:4289)
ut @ moment.js:287
/api/method/frappe.model.mapper.make_mapped_doc:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
           ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 809, in make_delivery_note
    dn_item = get_mapped_doc(
              ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 81, in get_mapped_doc
    target_doc.raise_no_permission_to("create")
  File "apps/frappe/frappe/model/document.py", line 236, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError
