### ISSUE TITLE
Naming Series not Working in Version-15

### ISSUE THREAD

**Issue by trackomatic** [frappe/erpnext#37596]
### Information about bug

When we use **.FY.** as an argument in Naming Series and Set the Doc Name by Naming Series, then we receive an error the system does not allow us to create the record. Example:

1. In Buying Settings, Set the Supplier Name field based on Naming Series
2. Now go to Document Naming Setting and Set the Naming Series: SUP-.FY.-.###
3. Come back to supplier master and try to create a supplier.
4. The System won't allow you to create a supplier.

Same is the case with Customer, Employee. I haven't checked the documents pertaining to Sales and Purchase i.e. Sales/Purchase Invoice, Sales/Purchase Orders etc. but i believe that the problem exists there as well.

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional

### Version

Frappe Version: V15-DEV and V15-Beta
ERPENXT: V15-dev and V15-beta

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"email_delivery_service": "0.0.1",
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"india_compliance": "15.0.0-dev"
}
```
### Route
```
Form/Supplier/new-supplier-2
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 36, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 332, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 354, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 280, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 474, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 948, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1314, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1296, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 945, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 45, in autoname
    set_name_by_naming_series(self)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 270, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 69, in generate_next_name
    return parse_naming_series(parts, doc=doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
    part = frappe.get_attr(method[0])(doc, e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 1249, in parse_naming_series_variable
    return get_fiscal_year(date=date, company=company)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Supplier\",\"name\":\"new-supplier-2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"info.trackomatic@gmail.com\",\"naming_series\":\"SUP.FY.###\",\"country\":\"India\",\"supplier_type\":\"Company\",\"is_transporter\":0,\"is_internal_supplier\":0,\"language\":\"en\",\"gst_category\":\"Unregistered\",\"allow_purchase_invoice_creation_without_purchase_order\":0,\"allow_purchase_invoice_creation_without_purchase_receipt\":0,\"is_frozen\":0,\"disabled\":0,\"warn_rfqs\":0,\"warn_pos\":0,\"prevent_rfqs\":0,\"prevent_pos\":0,\"on_hold\":0,\"hold_type\":\"\",\"supplier_name\":\"Test Supplier 2\",\"represents_company\":\"\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery37000419932080369127551": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1729,
						"namespace": ""
					}
				]
			}
		},
		"__sn": {
			"type": 2,
			"tagName": "button",
			"attributes": {
				"class": "btn btn-primary btn-sm primary-action",
				"data-label": "Save"
			},
			"childNodes": [],
			"id": 45346
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "07d61904-c15c-4cad-b670-62052bb6d266"
}
```
### Response Data
```
{
	"exception": "KeyError: 0",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by ankush** [comment]
Do you have any FY created and set correctly? If not, it won't work in naming series.

**Comment by trackomatic** [comment]
> Do you have any FY created and set correctly? If not, it won't work in naming series.

Yes, I have setup the fiscal year in accounting settings.

![image](https://github.com/frappe/erpnext/assets/140053831/050c4dc0-5ef5-44b1-a01f-e844d535ade8)


Then I go to document naming setting and set the naming series for Supplier Dosc Type by using .FY. argument. and I try it on the same page. as expected, three serial numbers for suppliers are generated by the system here. It gives an impression that every thing is set properly.
![image](https://github.com/frappe/erpnext/assets/140053831/9036fb0d-0508-4b4b-94f6-c0e418fd287b)

Then I go to Supplier Master and try to create my first supplier with new Naming Series..
![image](https://github.com/frappe/erpnext/assets/140053831/8397555a-372b-4667-808d-f7c674b4912a)

When I hit Save then the error appears:
![image](https://github.com/frappe/erpnext/assets/140053831/3645b0e0-edf4-4311-af29-30504d9b144b)

Here is the complete error report:

### App Versions
```
{
	"chat": "0.0.1",
	"ecommerce_integrations": "1.18.4",
	"erpnext": "15.0.0",
	"frappe": "15.0.0",
	"hrms": "15.0.0-dev",
	"india_compliance": "15.0.0-dev",
	"payments": "0.0.1"
}
```
### Route
```
Form/Supplier/new-supplier-ikybmumvpo
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 281, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 476, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 45, in autoname
    set_name_by_naming_series(self)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 270, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 69, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
    part = frappe.get_attr(method[0])(doc, e)
  File "apps/erpnext/erpnext/accounts/utils.py", line 1249, in parse_naming_series_variable
    return get_fiscal_year(date=date, company=company)[0]
KeyError: 0

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Supplier\",\"name\":\"new-supplier-ikybmumvpo\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"info.trackomatic@gmail.com\",\"naming_series\":\"SUP-.FY.-\",\"country\":\"India\",\"supplier_type\":\"Company\",\"is_transporter\":0,\"is_internal_supplier\":0,\"language\":\"en\",\"gst_category\":\"Unregistered\",\"allow_purchase_invoice_creation_without_purchase_order\":0,\"allow_purchase_invoice_creation_without_purchase_receipt\":0,\"is_frozen\":0,\"disabled\":0,\"warn_rfqs\":0,\"warn_pos\":0,\"prevent_rfqs\":0,\"prevent_pos\":0,\"on_hold\":0,\"hold_type\":\"\",\"represents_company\":\"\",\"supplier_name\":\"Test Supplier 1\",\"supplier_group\":\"Distributor\",\"default_currency\":\"INR\",\"default_bank_account\":\"\",\"default_price_list\":\"Standard Buying\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370063332563471953931": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 954,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "KeyError: 0",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```

**Comment by fkalpana** [comment]
This is a bug on version-15, i tested on multiple instances.

**Comment by trackomatic** [comment]
> This is a bug on version-15, i tested on multiple instances.

Do we have a work arround for this bug???
