### ISSUE TITLE
Naming Series Not Working

### ISSUE THREAD

**Issue by trackomatic** [frappe/erpnext#37619]
### Information about bug

Naming Series not taking **.FY.** as a valid argument. although it generates the samples of document names under << Document Naming Settings>> but if we set a naming series for any document type i.e. Employee, Supplier, Customer etc. and set the documents naming from Naming Series in respective document master, the system does not allow us to create the document.

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit

### Version

Frappe Version - 15.0.0
ERPNext Version - 15.0.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0",
	"frappe": "15.0.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Supplier/Test Supplier
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/client.py", line 272, in delete
    delete_doc(doctype, name)
  File "apps/frappe/frappe/client.py", line 491, in delete_doc
    frappe.delete_doc(doctype, name, ignore_missing=False)
  File "apps/frappe/frappe/__init__.py", line 1324, in delete_doc
    return frappe.model.delete_doc.delete_doc(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/delete_doc.py", line 121, in delete_doc
    update_naming_series(doc)
  File "apps/frappe/frappe/model/delete_doc.py", line 177, in update_naming_series
    revert_series_if_last(doc.naming_series, doc.name, doc)
  File "apps/frappe/frappe/model/naming.py", line 410, in revert_series_if_last
    prefix = parse_naming_series(prefix.split("."), doc=doc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
    part = frappe.get_attr(method[0])(doc, e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 1249, in parse_naming_series_variable
    return get_fiscal_year(date=date, company=company)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Supplier",
		"name": "Test Supplier"
	},
	"freeze": true,
	"freeze_message": "Deleting Test Supplier...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.delete",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "KeyError: 0",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by ankush** [comment]
Duplicate: https://github.com/frappe/erpnext/issues/37596
