### ISSUE TITLE
Doctype cannot be saved

### ISSUE THREAD

**Issue by mrchenxxx** [frappe/erpnext#37639]
### Information about bug

v15.0  When I click the save button, there is no response and the console will report an error

### Module

other

### Version

ERPNext: v15.0.0

Frappe Framework: v15.0.0
![image](https://github.com/frappe/erpnext/assets/44868578/dae43fde-e51d-4970-bc6b-13105b34bbfe)

### Installation method

docker

**Comment by dotts48** [comment]
After creating a model Def, I tried to create a related Doctype to it but there is no feed back from the system what so ever (no popups)
I'm also receiving that error from the console:  (Included for searchability)
```
form.js:798 TypeError: Cannot read properties of undefined (reading 'undefined')
    at Object.<anonymous> (save.js:161:55)
    at Function.each (jquery.js:383:19)
    at d (save.js:121:5)
    at n (save.js:22:48)
    at frappe.ui.form.save (save.js:273:3)
    at form.js:820:22
 ```
