### ISSUE TITLE
Accounting Page Error 

### ISSUE THREAD

**Issue by IbrahimMahdi97** [frappe/erpnext#37653]
### Information about bug

when entering the accounting page, getting the following error 
### App Versions
```
{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev"
}
```
### Route
```
Workspaces/Accounting
```
### Traceback
```
Error in query:
column "tabSales Invoice.docstatus" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabSales Invoice".docstatus asc, "tabSales Inv...
                     ^

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/doctype/number_card/number_card.py", line 163, in get_result
    res = frappe.get_list(
          ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1948, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 201, in execute
    result = self.build_and_run()
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 241, in build_and_run
    return frappe.db.sql(
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/postgres/database.py", line 203, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabSales Invoice.docstatus" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabSales Invoice".docstatus asc, "tabSales Inv...
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Total Outgoing Bills\",\"owner\":\"Administrator\",\"creation\":\"2020-07-17 11:25:34.725416\",\"modified\":\"2020-07-22 13:07:19.633101\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"is_standard\":1,\"module\":\"Accounts\",\"label\":\"Total Outgoing Bills\",\"type\":\"Document Type\",\"function\":\"Sum\",\"aggregate_function_based_on\":\"base_net_total\",\"document_type\":\"Sales Invoice\",\"is_public\":1,\"show_percentage_stats\":1,\"stats_time_interval\":\"Monthly\",\"filters_json\":\"[[\\\"Sales Invoice\\\",\\\"docstatus\\\",\\\"=\\\",\\\"1\\\",false],[\\\"Sales Invoice\\\",\\\"posting_date\\\",\\\"Timespan\\\",\\\"this year\\\",false]]\",\"doctype\":\"Number Card\",\"__last_sync_on\":\"2023-10-24T07:35:44.468Z\"}",
		"filters": "[[\"Sales Invoice\",\"docstatus\",\"=\",\"1\",false],[\"Sales Invoice\",\"posting_date\",\"Timespan\",\"this year\",false]]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.doctype.number_card.number_card.get_result",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError"
}
```

### Module

accounts

### Version

"erpnext": "15.0.0-dev",
"frappe": "15.0.0-dev"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
when entering the accounting page, getting the following error 
### App Versions

{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev"
}
```
### Route
```
Workspaces/Accounting
```
### Traceback
```
Error in query:
column "tabSales Invoice.docstatus" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabSales Invoice".docstatus asc, "tabSales Inv...
                     ^

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/doctype/number_card/number_card.py", line 163, in get_result
    res = frappe.get_list(
          ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1948, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 201, in execute
    result = self.build_and_run()
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 241, in build_and_run
    return frappe.db.sql(
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/postgres/database.py", line 203, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabSales Invoice.docstatus" must appear in the GROUP BY clause or be used in an aggregate function
LINE 5:     order by "tabSales Invoice".docstatus asc, "tabSales Inv...
                     ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Total Outgoing Bills\",\"owner\":\"Administrator\",\"creation\":\"2020-07-17 11:25:34.725416\",\"modified\":\"2020-07-22 13:07:19.633101\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"is_standard\":1,\"module\":\"Accounts\",\"label\":\"Total Outgoing Bills\",\"type\":\"Document Type\",\"function\":\"Sum\",\"aggregate_function_based_on\":\"base_net_total\",\"document_type\":\"Sales Invoice\",\"is_public\":1,\"show_percentage_stats\":1,\"stats_time_interval\":\"Monthly\",\"filters_json\":\"[[\\\"Sales Invoice\\\",\\\"docstatus\\\",\\\"=\\\",\\\"1\\\",false],[\\\"Sales Invoice\\\",\\\"posting_date\\\",\\\"Timespan\\\",\\\"this year\\\",false]]\",\"doctype\":\"Number Card\",\"__last_sync_on\":\"2023-10-24T07:35:44.468Z\"}",
		"filters": "[[\"Sales Invoice\",\"docstatus\",\"=\",\"1\",false],[\"Sales Invoice\",\"posting_date\",\"Timespan\",\"this year\",false]]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.doctype.number_card.number_card.get_result",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "GroupingError"
}
```
```

**Comment by deepeshgarg007** [comment]
@IbrahimMahdi97 This is not replicable now hence closing this issue.
