### ISSUE TITLE
Insufficient Permission for Opportunity Item

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#37745]
### Information about bug

Greetings Nice People! When approving a new sales order using one of my previously created user accounts, I get an "Insufficient Opportunity Project Permissions" error. However, when I do this using an administrator account, the problem goes away.

Once approved, the server script will update the opportunity project field (sample_date). This is encoding

if doc.docstatus == 1 and doc.items:
    item_op_details = [item.op_detail for item in doc.items if item.against_opportunity and item.op_detail]
    opportunity_items = frappe.db.get_list('Opportunity Item', filters={'name': ('in', item_op_details)}, fields=['name', 'sample_date'])
        
    for opportunity_item in opportunity_items:
        if not opportunity_item.sample_date:
            opportunity_item_doc = frappe.get_doc('Opportunity Item', opportunity_item.name)
            opportunity_item_doc.sample_date = doc.transaction_date
            opportunity_item_doc.save(ignore_permissions=True)

User is Purchasing Manager, internal role profile; View Sales, Purchasing Manager, Leave Reviewer, and Employee roles. Is there anything I'm missing? I need help with this, thank you.

This is a screenshot.

### Module

selling, CRM

### Version

Frappe Version - 14.53.2
Erpenxt Version - 14.45.3

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
http://192.168.1.130/api/method/frappe.model.workflow.apply_workflow 403 (FORBIDDEN)
send @ jquery.js:10109
ajax @ jquery.js:9690
frappe.request.call @ request.js:268
frappe.call @ request.js:105
(anonymous) @ request.js:15
frappe.xcall @ request.js:14
(anonymous) @ workflow.js:110
Promise.then (async)
(anonymous) @ workflow.js:108
(anonymous) @ page.js:469
dispatch @ jquery.js:5430
et.handle @ jquery.js:5234
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/workflow.py", line 136, in apply_workflow
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1010, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 989, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 360, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1095, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 923, in run_method
    run_server_script_for_doc_event(self, method)
  File "apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 39, in run_server_script_for_doc_event
    frappe.get_doc("Server Script", script_name).execute_doc(doc)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 106, in execute_doc
    safe_exec(self.script, _locals={"doc": doc}, restrict_commit_rollback=True)
  File "apps/frappe/frappe/utils/safe_exec.py", line 85, in safe_exec
    exec(
  File "<serverscript>", line 3, in <module>
  File "apps/frappe/frappe/__init__.py", line 1912, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 120, in execute
    self.check_read_permission(self.doctype, parent_doctype=parent_doctype)
  File "apps/frappe/frappe/model/db_query.py", line 497, in check_read_permission
    self._set_permission_map(doctype, parent_doctype)
  File "apps/frappe/frappe/model/db_query.py", line 510, in _set_permission_map
    raise frappe.PermissionError(doctype)
frappe.exceptions.PermissionError: Opportunity Item
```

**Comment by s-aga-r** [comment]
@JasonFu06 provide `parent_doctype` OR `ignore_permissions=True` to the `frappe.db.get_list` in your custom-script.

Example: 

`opportunity_items = frappe.db.get_list('Opportunity Item', filters={'name': ('in', item_op_details)}, fields=['name', 'sample_date'], parent_doctype="Opportunity")` 

OR 

`opportunity_items = frappe.db.get_list('Opportunity Item', filters={'name': ('in', item_op_details)}, fields=['name', 'sample_date'], ignore_permissions=True)`
