### ISSUE TITLE
CoA Importer:   File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 115, in generate_data_from_csv     if not row[1]: IndexError: list index out of range

### ISSUE THREAD

**Issue by xhijack** [frappe/erpnext#37779]
### Information about bug

Can't import COA using COA Importer

### Module

other

### Version

	"erpnext": "15.0.0",
	"frappe": "15.0.1"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0",
	"frappe": "15.0.1"
}
```
### Route
```
Form/Chart of Accounts Importer/Chart of Accounts Importer
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 369, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 28, in validate
    get_coa(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 156, in get_coa
    data = generate_data_from_csv(file_doc)
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 115, in generate_data_from_csv
    if not row[1]:
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Chart of Accounts Importer\",\"owner\":\"Administrator\",\"modified\":\"2023-10-31 13:32:06.678748\",\"modified_by\":\"taufik@sopwer.net\",\"docstatus\":0,\"idx\":\"0\",\"company\":\"Magetsu Oota Go\",\"import_file\":\"/private/files/COA OOTA.csv\",\"doctype\":\"Chart of Accounts Importer\",\"__last_sync_on\":\"2023-10-31T07:16:42.956Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by nabinhait** [comment]
fixed via #38321
