### ISSUE TITLE
Delivery Note & Purchase Invoice  Showing Blank Screen

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#37868]
### Information about bug

Delivery Note is showing blank screen when i try to open any delivery note or try to create one.

Opening existing delivery note/Purchase invoice.
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/79db9895-e2d6-4d79-8821-6dd86e8ac99c">
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/0f0abe4c-4bdd-4cdd-ac17-9e3fa07d0714">

This comes when i try to create delivery note/Purchase Invoice.
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/857f917a-2414-4d61-b56f-de20b50bee29">
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/7925b8df-f677-42ab-9c50-dd886777a340">

Also similar issue is coming in purchase invoice

### Module

accounts, stock

### Version

Frappe Framework: v14.54.0 (HEAD)
ERPNext: v14.46.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:298 ReferenceError: E_WAYBILL_CLASS is not defined
    at eval (delivery_note__js:1307:17)
    at frappe.ui.form.ScriptManager.setup (script_manager.js:179:4)
    at frappe.ui.form.Form.setup (form.js:107:23)
    at frappe.ui.form.Form.refresh (form.js:426:10)
    at frappe.views.FormFactory.render (formview.js:117:45)
    at formview.js:101:9
    at Object.callback (model.js:278:19)
    at Object.e [as success_callback] (request.js:85:16)
    at 200 (request.js:128:34)
    at Object.<anonymous> (request.js:294:6)
```

**Comment by precihole** [comment]
This issue is resolved after updation of India Compliance App
