### ISSUE TITLE
Bench Update error - Unknown column 'return_against' in 'field list

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3790]
When doing a Bench Update on a development setup , erpnext.patches.v5.4 throws the following error:-

Executing erpnext.patches.v5_4.fix_invoice_outstanding in site1.local (1bd3e0294d)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/administrator/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/commands.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/commands.py", line 202, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/administrator/frappe-bench/apps/erpnext/erpnext/patches/v5_4/fix_invoice_outstanding.py", line 10, in execute
    fields=["debit_to", "customer", "return_against"])
  File "/home/administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 872, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/db_query.py", line 50, in execute
    return self.build_and_run()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/model/db_query.py", line 62, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/database.py", line 146, in sql
    self._cursor.execute(query)
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'return_against' in 'field list'")

Running Bench Update on Deployment Test server runs without error.
Please advise.  Thanks
Ardan

**Comment by nabinhait** [comment]
@ekpaxp Fixed the issue. Thanks for reporting.
