### ISSUE TITLE
DB exception when saving Subcontracting Receipt

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37912]
### Information about bug

![IMG_2023](https://github.com/frappe/erpnext/assets/46800703/ed3c9f74-b6c0-42dc-8423-988ba446938f)

### Module

stock

### Version

Frappe / ERPNext: dev

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"lending": "0.0.1"
}
```
### Route
```
Form/Subcontracting Receipt/new-subcontracting-receipt-duiialrtzq
```
### Traceback
```
Syntax error in query:
SELECT `tabSerial and Batch Entry`.`serial_no`,`tabSerial and Batch Bundle`.`warehouse`,`tabSerial and Batch Bundle`.`item_code`,`tabSerial and Batch Entry`.`batch_no`,`tabSerial and Batch Entry`.`qty`,`tabSerial and Batch Entry`.`incoming_rate`,`tabSerial and Batch Bundle`.`voucher_detail_no`,`tabSerial and Batch Bundle`.`voucher_no`,`tabSerial and Batch Bundle`.`posting_date`,`tabSerial and Batch Bundle`.`posting_time` FROM `tabSerial and Batch Bundle` JOIN `tabSerial and Batch Entry` ON `tabSerial and Batch Bundle`.`name`=`tabSerial and Batch Entry`.`parent` WHERE `tabSerial and Batch Bundle`.`docstatus`=1 AND `tabSerial and Batch Bundle`.`is_cancelled`=0 AND `tabSerial and Batch Bundle`.`type_of_transaction` IN (%(param1)s,%(param2)s) AND `tabSerial and Batch Bundle`.`voucher_no` IN () AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batch Bundle`.`posting_date`,`tabSerial and Batch Bundle`.`posting_time` {'param1': 'Inward', 'param2': 'Outward'}
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 57, in validate
    super(SubcontractingReceipt, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 54, in validate
    self.create_raw_materials_supplied()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 730, in create_raw_materials_supplied
    self.set_materials_for_subcontracted_items(raw_material_table)
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 726, in set_materials_for_subcontracted_items
    self.__prepare_supplied_items()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 680, in __prepare_supplied_items
    self.get_available_materials()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 346, in get_available_materials
    voucher_bundle_data = get_voucher_wise_serial_batch_from_bundle(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1542, in get_voucher_wise_serial_batch_from_bundle
    data = get_ledgers_from_serial_batch_bundle(**kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1618, in get_ledgers_from_serial_batch_bundle
    return query.run(as_dict=True)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batc...' at line 1")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"bos@mailbox.org\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"MAT-SCR-.YYYY.-\",\"supplier\":\"_Test Supplier\",\"supplier_name\":\"_Test Supplier\",\"company\":\"ALG\",\"posting_date\":\"2023-11-04\",\"posting_time\":\"13:33:30.338113\",\"set_posting_time\":0,\"is_return\":0,\"supplier_warehouse\":\"Finished Goods - ALG\",\"total_qty\":1,\"total\":318.57,\"distribute_additional_costs_based_on\":\"Qty\",\"total_additional_costs\":0,\"status\":\"Draft\",\"per_returned\":0,\"doctype\":\"Subcontracting Receipt\",\"supplied_items\":[],\"items\":[{\"owner\":\"bos@mailbox.org\",\"docstatus\":0,\"idx\":1,\"item_code\":\"_Test FG Item\",\"item_name\":\"_Test FG Item\",\"is_scrap_item\":0,\"description\":\"_Test FG Item 6\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"returned_qty\":0,\"stock_uom\":\"_Test UOM\",\"conversion_factor\":1,\"rate\":318.57,\"amount\":318.57,\"rm_cost_per_qty\":0,\"service_cost_per_qty\":0,\"additional_cost_per_qty\":0,\"scrap_cost_per_qty\":0,\"rm_supp_cost\":0,\"warehouse\":\"Stores - ALG\",\"subcontracting_order\":\"SC-ORD-2023-00002\",\"subcontracting_order_item\":\"5a23aa786b\",\"bom\":\"BOM-_Test FG Item-001\",\"schedule_date\":\"2023-11-29\",\"cost_center\":\"Main - ALG\",\"page_break\":0,\"parentfield\":\"items\",\"parenttype\":\"Subcontracting Receipt\",\"doctype\":\"Subcontracting Receipt Item\",\"__islocal\":1,\"__unsaved\":1,\"parent\":\"new-subcontracting-receipt-pbhyefrnqq\",\"name\":\"new-subcontracting-receipt-item-giovqfslea\"}],\"additional_costs\":[],\"__islocal\":1,\"__onload\":{\"load_after_mapping\":true},\"__unsaved\":1,\"name\":\"new-subcontracting-receipt-pbhyefrnqq\",\"__last_sync_on\":\"2023-11-04T12:33:30.361Z\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370098455906044151221": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 97153,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batc...' at line 1\")",
	"exc_type": "ProgrammingError"
}
```
```

**Comment by bosue** [comment]
SQL bug should be at `voucher_no IN ()`.

**Comment by rohitwaghchaure** [comment]
@bosue 

1) Have you created material transfer entry against the Subcontracting Order?
2) What option you have selected for the "Backflush Raw Materials of Subcontract Based On" in the Buying Settings?

**Comment by bosue** [comment]
Thanks for figuring it out! 🙏
I‘m not sure I would have been able to replicate, but otherwise would have tried to…
