### ISSUE TITLE
Process loss percentage in Manufacturing is not working

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37934]
### Information about bug

During the final Manufacturing entry based on process loss percentage given the system used to update the quantity of finished goods item. after recent update it stopped working

![image](https://github.com/frappe/erpnext/assets/112148467/ca63b89b-67e8-4cc9-a97a-6c60bd6c7fd3)

Steps to create :
Create manufacturing stock entry 
update process loss percentage
click submit 

in 
**ERPNext: v14.43.0 (HEAD)
Frappe Framework: v14.52.0 (HEAD)
Frappe HR: v14.13.0 (HEAD)**

the system is automatically calculating th finished item quantity by substracting process loss qty from final product

in 
**ERPNext: v14.46.2 (HEAD)
Frappe Framework: v14.54.0 (HEAD)
Frappe HR: v14.16.0 (HEAD)
Payments: v0.0.1 (HEAD)**

the system asks user to update the finished item qty based on process loss percentage given. it throws following error
![image](https://github.com/frappe/erpnext/assets/112148467/6529565d-f3da-4631-a59a-c950af98ae9b)

user have to update process loss percentage and also have to update the final qty. 

### Module

stock, manufacturing

### Version

ERPNext: v14.46.2 (HEAD)
Frappe Framework: v14.54.0 (HEAD)
Frappe HR: v14.16.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 140, in validate
    self.validate_fg_completed_qty()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 481, in validate_fg_completed_qty
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Since there is a process loss of <strong>0.1</strong> units for the finished good <strong>BAL0002</strong>, you should reduce the quantity by <strong>0.1</strong> units for the finished good <strong>BAL0002</strong> in the Items Table.
request.js:457:14
```

**Comment by KhadijaAMH** [comment]
I am facing the same issue.
