### ISSUE TITLE
invalid FY message on setup wizard

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#38050]
This shows up on setup wizard. 

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1673, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 56, in get_fiscal_year
    fiscal_years = get_fiscal_years(
                   ^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 142, in get_fiscal_years
    raise FiscalYearError(error_msg)
erpnext.accounts.utils.FiscalYearError: Date 12-11-2023 is not in any active Fiscal Year
```

![image](https://github.com/frappe/erpnext/assets/9079960/48bac70d-a134-4663-baa8-2204943c875a)

**Comment by ankush** [comment]
This is most likely caused by https://github.com/frappe/erpnext/pull/37393

- This is because `filters` attribute in this file is a static value computed the first time the page is loaded. 

![image](https://github.com/frappe/erpnext/assets/9079960/233e93d1-20ac-4402-abc1-e251e3154c25)
