### ISSUE TITLE
[V15] Ratio analysis report - Error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#38073]
### Information about bug

<img width="1042" alt="Screenshot 2023-11-13 at 3 51 03 PM" src="https://github.com/frappe/erpnext/assets/910238/58d2d5de-e409-47c3-99dd-50a1dd16bf2e">

### Module

accounts

### App Versions
```
{
	"erpnext": "15.0.0",
	"frappe": "15.1.0",
	"hrms": "15.2.0"
}
```

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0",
	"frappe": "15.1.0",
	"hrms": "15.2.0"
}
```
### Route
```
query-report/Financial Ratios
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 848, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 221, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 848, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 81, in generate_report_result
    res = get_report_result(report, filters) or []
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_script_report(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 164, in execute_script_report
    res = self.execute_module(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 181, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/report/financial_ratios/financial_ratios.py", line 29, in execute
    data = get_ratios_data(filters, period_list, years)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/report/financial_ratios/financial_ratios.py", line 113, in get_ratios_data
    add_solvency_ratios(
  File "apps/erpnext/erpnext/accounts/report/financial_ratios/financial_ratios.py", line 180, in add_solvency_ratios
    profit_after_tax = total_income[year] + total_expense[year]
                       ~~~~~~~~~~~~^^^^^^
KeyError: 'dec_2023'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Financial Ratios",
		"filters": "{\"company\":\"Al Falah Corp (Demo)\",\"from_fiscal_year\":\"2023\",\"to_fiscal_year\":\"2023\",\"periodicity\":\"Yearly\",\"period_start_date\":\"2023-01-01\",\"period_end_date\":\"2023-12-31\"}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": "6156f9a5-9565-4d33-859d-2c2af123cc07"
}
```
### Response Data
```
{
	"exception": "KeyError: 'dec_2023'",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by RitvikSardana** [comment]
The fix to this is already merged in the develop branch: 
https://github.com/frappe/erpnext/pull/37613.

Hence backporting the mentioned PR to v15,
