### ISSUE TITLE
[V15] Issue in Delivery Note form loading

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#38072]
### Information about bug

Was trying Stock Reservation feature

1. Created a Sales order, which didn't have a stock
2. Created a PO from Sales Order
3. Created Purchase Receipt
4. Created another purchase receipt, without PO and SO
5. Came back to first SO and tried creating DN, to check if Serial No. as per reservation is updated.

Issue: In the DN, field were not loaded

<img width="1434" alt="Screenshot 2023-11-13 at 3 18 46 PM" src="https://github.com/frappe/erpnext/assets/910238/723085d2-0409-483e-bda6-392775fedfbc">

### Module

stock

### Version

Frappe - 15
ERPNext - 15

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
TypeError: Cannot read properties of undefined (reading 'go_to_page')
    at form.js:524:34
    at Array.forEach (<anonymous>)
    at frappe.ui.form.Form.switch_doc (form.js:521:14)
    at frappe.ui.form.Form.refresh (form.js:385:9)
    at frappe.views.FormFactory.render (formview.js:107:45)
    at formview.js:91:9
    at Object.callback (model.js:317:19)
    at Object.t [as success_callback] (request.js:85:16)
    at 200 (request.js:133:34)
    at Object.<anonymous> (request.js:305:6)
```

**Comment by s-aga-r** [comment]
Steps to replicate (short):
- Create Delivery Note from Sales Order.
