### ISSUE TITLE
[Server Error] New Supplier Create issue with (Primary Contact & Primary Address) (Short Form & Full Form Both)

### ISSUE THREAD

**Issue by rssabbirdev** [frappe/erpnext#38124]
### Information about bug

![Screenshot_1](https://github.com/frappe/erpnext/assets/36847136/a80b689f-55ae-4631-a7ed-01ca512ad776)

![Screenshot_2](https://github.com/frappe/erpnext/assets/36847136/c3411882-cd88-4945-8e68-bdbd4021ee70)

### Module

buying

### Version

Erpnext: 15.0.0
Frappe: 15.1.0
Installed on 16th November 2023

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0",
	"frappe": "15.1.0"
}
```
### Route
```
List/Supplier/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/client.py", line 226, in save
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 50, in on_update
    self.create_primary_contact()
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 134, in create_primary_contact
    contact = make_contact(self)
              ^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/selling/doctype/customer/customer.py", line 647, in make_contact
    if args.customer_type == "Individual":
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'Supplier' object has no attribute 'customer_type'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Supplier\",\"name\":\"new-supplier-kbsodspyxe\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"kabbonil40@gmail.com\",\"naming_series\":\"SUP-.YYYY.-\",\"country\":\"Bangladesh\",\"supplier_type\":\"Company\",\"is_transporter\":0,\"is_internal_supplier\":0,\"language\":\"en\",\"allow_purchase_invoice_creation_without_purchase_order\":0,\"allow_purchase_invoice_creation_without_purchase_receipt\":0,\"is_frozen\":0,\"disabled\":0,\"warn_rfqs\":0,\"warn_pos\":0,\"prevent_rfqs\":0,\"prevent_pos\":0,\"on_hold\":0,\"hold_type\":\"\",\"__run_link_triggers\":1,\"supplier_name\":\"Demo\",\"address_line1\":\"Chouddagram\",\"pincode\":\"0000\",\"email_id\":\"demo@demo.com\",\"mobile_no\":\"01912345678\",\"email_address\":\"demo@demo.com\",\"mobile_number\":\"01912345678\"}"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.save",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'Supplier' object has no attribute 'customer_type'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by s-aga-r** [comment]
Fixed: https://github.com/frappe/erpnext/pull/38147
