### ISSUE TITLE
Version 15 Note doctype public field attribute missing

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#38186]
### Information about bug

AttributeError: 'Note' object has no attribute 'public'

When opening a existing note. 

Also cannot able to see Public field in the form when creating new note. 

![Screenshot 2023-11-19 101144](https://github.com/frappe/erpnext/assets/109452795/24e116ba-fa4c-4171-bcc0-dbbba866ae2c)

### Module

other

### Version

erpnext version 15

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.0.0",
	"frappe": "15.1.0",
	"hrms": "15.2.0",
	"india_compliance": "15.0.0-dev",
	"payments": "0.0.1"
}
```
### Route
```
Form/Note/a1e9968ae7
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/load.py", line 50, in getdoc
    get_docinfo(doc)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/load.py", line 122, in get_docinfo
    "permissions": get_doc_permissions(doc),
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/permissions.py", line 174, in get_doc_permissions
    if has_controller_permissions(doc, ptype, user=user) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/permissions.py", line 387, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/doctype/note/note.py", line 60, in has_permission
    return doc.public or doc.owner == user
           ^^^^^^^^^^
AttributeError: 'Note' object has no attribute 'public'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Note",
		"name": "a1e9968ae7"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoc",
	"request_id": "379a4c3e-b73c-4995-a0c1-324ab4476d66"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'Note' object has no attribute 'public'",
	"exc_type": "AttributeError"
}
```
```

**Comment by s-aga-r** [comment]
https://github.com/frappe/frappe/pull/22750
