### ISSUE TITLE
Scheduled Job Failed: bulk_transaction_log.retry_failing_transaction

### ISSUE THREAD

**Issue by mimiza** [frappe/erpnext#38193]
### Information about bug

I found this Scheduled Job Type repeatedly failed after the latest update: bulk_transaction_log.retry_failing_transaction

Details:
Traceback (most recent call last): File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 124, in execute frappe.get_attr(self.method)() File "apps/frappe/frappe/__init__.py", line 1663, in get_attr return getattr(get_module(modulename), methodname) AttributeError: module 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_transaction_log' has no attribute 'retry_failing_transaction'

### Module

other

### Version

Frappe: latest
Erpnext: latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 124, in execute
    frappe.get_attr(self.method)()
  File "apps/frappe/frappe/__init__.py", line 1663, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_transaction_log' has no attribute 'retry_failing_transaction'
```

**Comment by yahyaoudra** [comment]
having the same with ERPnext 15.2.0
![Screenshot 2023-11-20 at 01 55 41](https://github.com/frappe/erpnext/assets/67019341/6953453f-66f3-421e-ac9a-537f65a9e10c)

**Comment by s-aga-r** [comment]
@ruthra-kumar https://github.com/frappe/erpnext/pull/38038

**Comment by ruthra-kumar** [comment]
@mimiza Should be fixed in the upcoming minor version

**Comment by yahyaoudra** [comment]
Thank you

**Comment by mimiza** [comment]
Thank you

**Comment by mimiza** [comment]
> @mimiza Should be fixed in the upcoming minor version

Thank you
