### ISSUE TITLE
Material Request is not saving -AttributeError: 'MaterialRequestController' object has no attribute 'grand_total' 

### ISSUE THREAD

**Issue by dibbo116** [frappe/erpnext#38206]
### Information about bug

this error is showing while saving material request - AttributeError: 'MaterialRequestController' object has no attribute 'grand_total'

### Module

stock

### Version

"erpnext": "14.47.4",
"frappe": "14.54.1",
"hrms": "14.16.1",
"payments": "0.0.1"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/everlife/everlife/overrides/stock/material_request/material_request.py", line 12, in validate
    super(MaterialRequestController, self).validate()
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 70, in validate
    super(MaterialRequest, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 36, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 52, in validate
    super(SubcontractingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 221, in validate
    self.set_total_in_words()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 240, in set_total_in_words
    amount = abs(self.grand_total)
AttributeError: 'MaterialRequestController' object has no attribute 'grand_total'
(anonymous)
```

**Comment by shuvro-baset** [comment]
I am facing same issue in version 
erpnext 14.48.1
frappe 14.55.0
hrms 14.17.0
payments 0.0.1

**Comment by rohitwaghchaure** [comment]
```
  File "apps/everlife/everlife/overrides/stock/material_request/material_request.py", line 12, in validate
    super(MaterialRequestController, self).validate()
```

Customization related issue

**Comment by dibbo116** [comment]
Thanks
