### ISSUE TITLE
New Subcontract Receipt Returns a SQL Syntax Error

### ISSUE THREAD

**Issue by fungmankit** [frappe/erpnext#38232]
### Information about bug

Hi all,

I was trying to receive an subcontract order but the following error just prompted up and the receiving process cannot be completed, please help to have a look.
<img width="570" alt="image" src="https://github.com/frappe/erpnext/assets/39433251/1aa8b195-58aa-4f31-8be2-1ca987411bdd">

### Module

buying

### Version

Frappe Version - v15.0.2 (HEAD)
ERPnext Version - v15.0.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"email_delivery_service": "0.0.1",
	"erpnext": "15.0.0",
	"frappe": "15.0.2"
}
```
### Route
```
Form/Subcontracting Receipt/new-subcontracting-receipt-vpcmjepsbg
```
### Traceback
```
Syntax error in query:
SELECT `tabSerial and Batch Entry`.`serial_no`,`tabSerial and Batch Bundle`.`warehouse`,`tabSerial and Batch Bundle`.`item_code`,`tabSerial and Batch Entry`.`batch_no`,`tabSerial and Batch Entry`.`qty`,`tabSerial and Batch Entry`.`incoming_rate`,`tabSerial and Batch Bundle`.`voucher_detail_no`,`tabSerial and Batch Bundle`.`voucher_no`,`tabSerial and Batch Bundle`.`posting_date`,`tabSerial and Batch Bundle`.`posting_time` FROM `tabSerial and Batch Bundle` JOIN `tabSerial and Batch Entry` ON `tabSerial and Batch Bundle`.`name`=`tabSerial and Batch Entry`.`parent` WHERE `tabSerial and Batch Bundle`.`docstatus`=1 AND `tabSerial and Batch Bundle`.`is_cancelled`=0 AND `tabSerial and Batch Bundle`.`type_of_transaction` IN (%(param1)s,%(param2)s) AND `tabSerial and Batch Bundle`.`voucher_no` IN () AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batch Bundle`.`posting_date`,`tabSerial and Batch Bundle`.`posting_time` /* FRAPPE_TRACE_ID: 0f85a45e-f750-46e3-b33f-7fa9657f0dc2 */ {'param1': 'Inward', 'param2': 'Outward'}
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 57, in validate
    super(SubcontractingReceipt, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 54, in validate
    self.create_raw_materials_supplied()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 730, in create_raw_materials_supplied
    self.set_materials_for_subcontracted_items(raw_material_table)
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 726, in set_materials_for_subcontracted_items
    self.__prepare_supplied_items()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 680, in __prepare_supplied_items
    self.get_available_materials()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 346, in get_available_materials
    voucher_bundle_data = get_voucher_wise_serial_batch_from_bundle(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1542, in get_voucher_wise_serial_batch_from_bundle
    data = get_ledgers_from_serial_batch_bundle(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 1618, in get_ledgers_from_serial_batch_bundle
    return query.run(as_dict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batc...' at line 1")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Subcontracting Receipt\",\"name\":\"new-subcontracting-receipt-vpcmjepsbg\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"fungmankit@gmail.com\",\"naming_series\":\"MAT-SCR-.YYYY.-\",\"company\":\"NextGen ERP (Demo)\",\"posting_date\":\"2023-11-21\",\"set_posting_time\":1,\"is_return\":0,\"distribute_additional_costs_based_on\":\"Qty\",\"status\":\"Draft\",\"items\":[{\"owner\":\"fungmankit@gmail.com\",\"docstatus\":0,\"idx\":1,\"item_code\":\"1003-Trial\",\"item_name\":\"10003\",\"is_scrap_item\":0,\"description\":\"10003\",\"received_qty\":0,\"qty\":1,\"rejected_qty\":0,\"returned_qty\":0,\"stock_uom\":\"Unit\",\"conversion_factor\":1,\"rate\":50400,\"amount\":50400,\"rm_cost_per_qty\":0,\"service_cost_per_qty\":50000,\"additional_cost_per_qty\":0,\"scrap_cost_per_qty\":0,\"rm_supp_cost\":0,\"warehouse\":\"Finished Goods - NGED\",\"subcontracting_order\":\"SC-ORD-2023-00001\",\"subcontracting_order_item\":\"3d1396c351\",\"bom\":\"BOM-1003-Trial-001\",\"schedule_date\":\"2023-11-22\",\"cost_center\":\"Main - NGED\",\"page_break\":0,\"parent\":\"new-subcontracting-receipt-vpcmjepsbg\",\"parentfield\":\"items\",\"parenttype\":\"Subcontracting Receipt\",\"doctype\":\"Subcontracting Receipt Item\",\"__islocal\":1,\"__unsaved\":1,\"name\":\"new-subcontracting-receipt-item-eayuqrykwx\"}],\"supplier_name\":\"MA Inc.\",\"represents_company\":\"\",\"supplier\":\"MA Inc.\",\"idx\":0,\"set_warehouse\":\"Finished Goods - NGED\",\"supplier_warehouse\":\"Work In Progress - NGED\",\"total_qty\":1,\"total\":50400,\"total_additional_costs\":0,\"per_returned\":0,\"supplied_items\":[],\"additional_costs\":[],\"__onload\":{\"load_after_mapping\":true},\"posting_time\":\"11:09:22\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700312610680762720471": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1383,
						"namespace": ""
					}
				]
			}
		},
		"__sn": {
			"type": 2,
			"tagName": "button",
			"attributes": {
				"class": "btn btn-primary btn-sm primary-action",
				"data-label": "Save"
			},
			"childNodes": [],
			"id": 4586
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "0f85a45e-f750-46e3-b33f-7fa9657f0dc2"
}
```
### Response Data
```
{
	"exception": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `tabSerial and Batch Entry`.`is_outward`=0 ORDER BY `tabSerial and Batc...' at line 1\")",
	"exc_type": "ProgrammingError"
}
```
```

**Comment by rohitwaghchaure** [comment]
Already fixed https://github.com/frappe/erpnext/pull/38085
Please update your site and check
