### ISSUE TITLE
Migrating from 14 -> 15 E-Commerce Module Not Found Error

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#38246]
### Information about bug

When i tried to upgradef rom 14 to 15 in FrappeCloud, I get this error trying to access mywebiste. the second time i tried, I added the ecommerce module (which is now a seperate package with same issue.

Then waiting fro version 15.2 to come out, and still having this issue.

### Module

ecommerce

### Version

15

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 40, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 522, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 49, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 64, in update_context
    ret = self.doc.get_context(self.context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_page/web_page.py", line 112, in get_context
    self.set_page_blocks(context)
  File "apps/frappe/frappe/website/doctype/web_page/web_page.py", line 173, in set_page_blocks
    out = get_web_blocks_html(self.page_blocks)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_page/web_page.py", line 249, in get_web_blocks_html
    "web_template_html": web_template.render(block.web_template_values),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_template/web_template.py", line 126, in render
    template = self.get_template(self.standard)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_template/web_template.py", line 113, in get_template
    template = self.get_template_path()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_template/web_template.py", line 101, in get_template_path
    folder = self.get_template_folder()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/doctype/web_template/web_template.py", line 94, in get_template_folder
    module_path = get_module_path(module)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1429, in get_module_path
    app = get_module_app(module)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 262, in get_module_app
    frappe.throw(_("Module {} not found").format(module), exc=frappe.DoesNotExistError)
  File "apps/frappe/frappe/__init__.py", line 571, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 543, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 497, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Module E-commerce not found
```

**Comment by rohitwaghchaure** [comment]
@ablashek It looks like Web Templates has not moved to the new app, can you share the site name

**Comment by abhioncode** [comment]
indopar15.frappe.cloudOn 21/11/2023, at 6:43 AM, rohitwaghchaure ***@***.***> wrote:﻿
@ablashek It looks like Web Templates has not moved to the new app, can you share the site name

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

INDOPAR Sociedad AnónimaPLANTA INDUSTRIAL | KM 24, RUTA IICAPIATÁ, PARAGUAYWWW.INDOPAR.COM.PY   Conozcan nuestras Acciones

**Comment by rohitwaghchaure** [comment]
@ablashek You need to install the Frappe Webshop app (https://github.com/frappe/webshop)

Please read below docs 
https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-15

**Comment by abhioncode** [comment]
Thanks, but this app isn’t available yet on frappecloud. I should wait till it becomes available to migrate. On 21/11/2023, at 7:49 AM, rohitwaghchaure ***@***.***> wrote:﻿
@ablashek You need to install the Frappe Webshop app 
Please read below docs
https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-15

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

INDOPAR Sociedad AnónimaPLANTA INDUSTRIAL | KM 24, RUTA IICAPIATÁ, PARAGUAYWWW.INDOPAR.COM.PY   Conozcan nuestras Acciones
