### ISSUE TITLE
naming series fiscal_year fetch KeyError

### ISSUE THREAD

**Issue by Akapoor99** [frappe/erpnext#38334]
### Information about bug

when using `.FY.` (Fiscal Year) with naming series in DocType naming it gives error mentioned below:

`Server Error`
`KeyError: 0`
`Possible source of error: ERPNext (app)`

### Module

accounts

### Version

**ERPNext:** v14.x.x-develop () (develop)

**Frappe Framework:** v15.x.x-develop () (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
13:18:02 web.1         | Traceback (most recent call last):
13:18:02 web.1         |   File "apps/frappe/frappe/app.py", line 110, in application
13:18:02 web.1         |     response = frappe.api.handle(request)
13:18:02 web.1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/api/__init__.py", line 49, in handle
13:18:02 web.1         |     data = endpoint(**arguments)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
13:18:02 web.1         |     return frappe.handler.handle()
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/handler.py", line 49, in handle
13:18:02 web.1         |     data = execute_cmd(cmd)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
13:18:02 web.1         |     return frappe.call(method, **frappe.form_dict)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/__init__.py", line 1673, in call
13:18:02 web.1         |     return fn(*args, **newargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
13:18:02 web.1         |     return func(*args, **kwargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
13:18:02 web.1         |     doc.save()
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 334, in save
13:18:02 web.1         |     return self._save(*args, **kwargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 356, in _save
13:18:02 web.1         |     return self.insert()
13:18:02 web.1         |            ^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 281, in insert
13:18:02 web.1         |     self.set_new_name(set_name=set_name, set_child_names=set_child_names)
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 476, in set_new_name
13:18:02 web.1         |     set_new_name(self)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
13:18:02 web.1         |     set_name_from_naming_options(autoname, doc)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
13:18:02 web.1         |     set_name_by_naming_series(doc)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
13:18:02 web.1         |     doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
13:18:02 web.1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 270, in make_autoname
13:18:02 web.1         |     return series.generate_next_name(doc, ignore_validate=ignore_validate)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 69, in generate_next_name
13:18:02 web.1         |     return parse_naming_series(parts, doc=doc)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
13:18:02 web.1         |     part = frappe.get_attr(method[0])(doc, e)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/erpnext/erpnext/accounts/utils.py", line 1258, in parse_naming_series_variable
13:18:02 web.1         |     return get_fiscal_year(date=date, company=company)[0]
13:18:02 web.1         |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
13:18:02 web.1         | KeyError: 0
13:18:02 web.1         | 
13:18:02 web.1         | 127.0.0.1 - - [25/Nov/2023 13:18:02] "POST /api/method/frappe.desk.form.save.savedocs HTTP/1.1" 500 -
```

**Comment by jecinthamary** [comment]
Same Issue for me also 
ERPNext version 15
