### ISSUE TITLE
Same item can't be added under different branches of a single BOM Creator tree

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#38532]
### Information about bug

Let's say an object A is made of B and C. 
B is made of 2 units of D.
C is made of 1 unit of D. 

This scenario will result in failure to create BOMs.

From what I understand, all nodes containing the same Item are treated as a single node.

### Module

manufacturing

### Version

erpnext 15.4.0
frappe 15.3.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
File "apps/erpnext/erpnext/manufacturing/doctype/bom_creator/bom_creator.py", line 250, in create_boms
self.create_bom(fg_item_data, production_item_wise_rm)
File "apps/erpnext/erpnext/manufacturing/doctype/bom_creator/bom_creator.py", line 316, in create_bom
bom.save(ignore_permissions=True)
File "apps/frappe/frappe/model/document.py", line 334, in save
return self._save(*args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 356, in _save
return self.insert()
File "apps/frappe/frappe/model/document.py", line 286, in insert
self.run_before_save_methods()
File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
self.run_method("validate")
File "apps/frappe/frappe/model/document.py", line 950, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1316, in composer
return composed(self, method, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1298, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "apps/frappe/frappe/model/document.py", line 947, in fn
return method_object(*args, **kwargs)
File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 254, in validate
self.validate_materials()
File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 614, in validate_materials
frappe.throw(_("Raw Materials cannot be blank."))
File "apps/frappe/frappe/__init__.py", line 577, in throw
msgprint(
File "apps/frappe/frappe/__init__.py", line 549, in msgprint
_raise_exception()
File "apps/frappe/frappe/__init__.py", line 500, in _raise_exception
raise exc
frappe.exceptions.ValidationError: Raw Materials cannot be blank
```

**Comment by rohitwaghchaure** [comment]
We are not able to replicate the issue with the steps given by you, could you please update your site to latest v15 branch and check.
