### ISSUE TITLE
Not able to create the Serial and Batch Bundle - Most Urgent

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#38642]
### Information about bug

While creating the serial and batch Bundle cvs file is not uploading

<img width="406" alt="Screenshot 2023-12-08 at 5 37 24 PM" src="https://github.com/frappe/erpnext/assets/21578167/1f08fc6d-41b7-40f5-9a6c-a5b83588c249">

https://github.com/frappe/erpnext/assets/21578167/472609d7-b853-4834-ba33-445117491570

### Module

stock

### Version

ERPNext: v15.5.0 (version-15)

Frappe Framework: v15.4.1 (version-15)

Frappe HR: v15.5.0 (version-15)

India Compliance: v15.0.4 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
script_manager.js:32 ƒ validate_prompt_data(frm, prompt_data) {
		if (prompt_data.using_csv_file && !prompt_data.csv_file) {
			frappe.throw(__("Please attach CSV file"));
		}

		if (frm.doc.has_serial_no && !prompt_data.u…
d @ script_manager.js:32
script_manager.js:32 ƒ add_serial_batch(frm, prompt_data) {
		frm.events.validate_prompt_data(frm, prompt_data);

		frm.call({
			method: "add_serial_batch",
			doc: frm.doc,
			args: {
				"data": prompt_data,
			},
			ca…
d @ script_manager.js:32
script_manager.js:32 Uncaught Error: Please enter serial nos
    at frappe.throw (messages.js:26:8)
    at validate_prompt_data (serial_and_batch_bundle__js:131:16)
    at Object.d [as validate_prompt_data] (script_manager.js:30:12)
    at add_serial_batch (serial_and_batch_bundle__js:111:14)
    at Object.d [as add_serial_batch] (script_manager.js:30:12)
    at eval (serial_and_batch_bundle__js:64:17)
    at frappe.ui.Dialog.<anonymous> (messages.js:104:4)
    at HTMLButtonElement.<anonymous> (dialog.js:194:20)
    at HTMLButtonElement.dispatch (jquery.js:5135:27)
    at Rt.handle (jquery.js:4939:28)
```

**Comment by dineshpanchal93** [comment]
@rohitwaghchaure still not resolved

Sending you the error

request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 334, in run_doc_method
    response = doc.run_method(method, **args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 747, in add_serial_batch
    serial_nos, batch_nos = get_serial_batch_from_csv(self.item_code, data.get("csv_file"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 790, in get_serial_batch_from_csv
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './bhagwati.addon-s.com/files/serial_and_batch_bundle (2)cdccb8.csv'

https://github.com/frappe/erpnext/assets/21578167/50f3273f-cbb6-453c-8e97-0fedcf8c56a6
