### ISSUE TITLE
User Permission - Error  AttributeError: type object 'PaymentReconciliationPayment' has no attribute 'get_list'

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#38700]
### Information about bug

While giving user permission of warehouse on selected doctype

Applicable doctype list if not getting fetched

### Module

stock

### Version

ERPNext: v14.53.0 (version-14)

Frappe Framework: v14.58.0 (version-14)

Frappe HR: v14.18.1 (version-14)

India Compliance: v14.19.6 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 37, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 108, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 85, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 2424, in wrapper
    return fn(**kwargs)
  File "apps/frappe/frappe/core/doctype/user_permission/user_permission.py", line 142, in get_applicable_for_doctype_list
    linked_doctypes_map = get_linked_doctypes(doctype, True)
  File "apps/frappe/frappe/desk/form/linked_with.py", line 540, in get_linked_doctypes
    return frappe.cache().hget(
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 205, in hget
    value = generator()
  File "apps/frappe/frappe/desk/form/linked_with.py", line 543, in <lambda>
    lambda: _get_linked_doctypes(doctype, without_ignore_user_permissions_enabled),
  File "apps/frappe/frappe/desk/form/linked_with.py", line 553, in _get_linked_doctypes
    ret.update(get_dynamic_linked_fields(doctype, without_ignore_user_permissions_enabled))
  File "apps/frappe/frappe/desk/form/linked_with.py", line 649, in get_dynamic_linked_fields
    possible_link = frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 1946, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1918, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 187, in execute
    return controller.get_list(kwargs)
AttributeError: type object 'PaymentReconciliationPayment' has no attribute 'get_list'
```

**Comment by ruthra-kumar** [comment]
Fixed by https://github.com/frappe/erpnext/pull/38685
