### ISSUE TITLE
Batch Wise Stock Balance Report Issue

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#38903]
### Information about bug

```
Traceback (most recent call last):
File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 79, in generate_report
result = generate_report_result(report=report, filters=instance.filters, user=instance.owner)
File "apps/frappe/frappe/__init__.py", line 808, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File "apps/frappe/frappe/desk/query_report.py", line 89, in generate_report_result
res = get_report_result(report, filters) or []
File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
res = report.execute_script_report(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
res = self.execute_module(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
return frappe.get_attr(method_name)(frappe._dict(filters))
File "apps/erpnext/erpnext/stock/report/batch_wise_balance_history/batch_wise_balance_history.py", line 22, in execute
frappe.throw(_("Please select either the Item or Warehouse filter to generate the report."))
File "apps/frappe/frappe/__init__.py", line 540, in throw
msgprint(
File "apps/frappe/frappe/__init__.py", line 508, in msgprint
_raise_exception()
File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
raise raise_exception(msg)
frappe.exceptions.ValidationError: Please select either the Item or Warehouse filter to generate the report.
```

Item & Warehouse Filters Are Not Mandatory.So why This message Throwing,If There any Other report For fetching all warehouse data Once?

### Module

stock

### Version

ERPNext: v14.54.2 (version-14)

Frappe Framework: v14.59.0 (version-14)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@asoral set warehouse as All Warehouses in the filter and check
