### ISSUE TITLE
CSV not uploading to create the Serial & Batch Bundle

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#38902]
### Information about bug

Not able to upload the csv for the serial and Batch bundle list

### Module

stock

### Version

ERPNext: v15.7.0 (version-15)

Frappe Framework: v15.6.1 (version-15)

Frappe HR: v15.6.0 (version-15)

India Compliance: v15.1.0 (version-15)

Print Designer: v1.0.0 (main)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"bhagwati": "0.0.1",
	"erpnext": "15.7.0",
	"frappe": "15.6.1",
	"hrms": "15.6.0",
	"india_compliance": "15.1.0",
	"raven": "1.3.2"
}
```
### Route
```
Form/Serial and Batch Bundle/new-serial-and-batch-bundle-vphfpuodll
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 334, in run_doc_method
    response = doc.run_method(method, **args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 853, in add_serial_batch
    serial_nos, batch_nos = get_serial_batch_from_csv(self.item_code, data.get("csv_file"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 896, in get_serial_batch_from_csv
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './bhagwati.addon-s.com/files/serial_and_batch_bundle (2)5f9450.csv'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"data": "{\"csv_file\":\"/files/serial_and_batch_bundle (2)5f9450.csv\"}",
		"docs": "{\"docstatus\":0,\"doctype\":\"Serial and Batch Bundle\",\"name\":\"new-serial-and-batch-bundle-vphfpuodll\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"SABB-.########\",\"company\":\"Shree Bhagwati Industries\",\"has_serial_no\":1,\"has_batch_no\":1,\"type_of_transaction\":\"Inward\",\"is_cancelled\":0,\"is_rejected\":0,\"entries\":[{\"docstatus\":0,\"doctype\":\"Serial and Batch Entry\",\"name\":\"new-serial-and-batch-entry-tgmvfdqpwp\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"qty\":1,\"delivered_qty\":0,\"is_outward\":0,\"parent\":\"new-serial-and-batch-bundle-vphfpuodll\",\"parentfield\":\"entries\",\"parenttype\":\"Serial and Batch Bundle\",\"idx\":1,\"warehouse\":\"Finished Goods - SBI\",\"incoming_rate\":0,\"outgoing_rate\":0,\"stock_value_difference\":0}],\"item_code\":\"Batch & Serial\",\"warehouse\":\"Finished Goods - SBI\",\"voucher_type\":\"Stock Reconciliation\",\"idx\":0,\"total_qty\":0,\"avg_rate\":0,\"total_amount\":0,\"item_name\":\"Batch & Serial\",\"item_group\":\"Component\"}",
		"method": "add_serial_batch",
		"args": "{\"data\":{\"csv_file\":\"/files/serial_and_batch_bundle (2)5f9450.csv\"}}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: './bhagwati.addon-s.com/files/serial_and_batch_bundle (2)5f9450.csv'",
	"exc_type": "FileNotFoundError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by rohitwaghchaure** [comment]
@dineshpanchal93 

I have tried to replicate the issue on local system but it's working fine (check below GIF)

![serial-no-import](https://github.com/frappe/erpnext/assets/8780500/22e63f10-69ef-4c1b-a5d5-e366d209a31d)


If possible please share the steps to replicate the issue

**Comment by dineshpanchal93** [comment]
Ok will update you

**Comment by rohitwaghchaure** [comment]
@dineshpanchal93 We are closing this issue, kindly open the new ticket with steps to replicate the issue if the issue still persists

**Comment by dineshpanchal93** [comment]
@rohitwaghchaure Its working for the only serial no only

**Comment by dineshpanchal93** [comment]
raising the new issue.
