### ISSUE TITLE
Error when duplicating and attempting to save Quotation Doctype

### ISSUE THREAD

**Issue by mcerwin** [frappe/erpnext#39034]
### Information about bug

When duplicating the Quotation Doctype and attempting to save, I receive an error indicating "Could not find DocType:"

### Module

selling

### Version

ERPNext: v14.57.0 (version-14)

Frappe Framework: v14.61.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
11:49:03 web.1         | 10.10.8.133 - - [29/Dec/2023 11:49:03] "GET /api/method/frappe.client.get_value?doctype=DocType&fieldname=name&filters=Display%20Quote&_=1703872094152 HTTP/1.1" 200 -
11:49:04 web.1         | 10.10.8.133 - - [29/Dec/2023 11:49:04] "GET /api/method/frappe.client.get_value?doctype=DocType&fieldname=name&filters=Display%20Quote&_=1703872094153 HTTP/1.1" 200 -
11:49:10 web.1         | 10.10.8.133 - - [29/Dec/2023 11:49:10] "POST /api/method/frappe.desk.form.save.savedocs HTTP/1.1" 417 -
```

**Comment by s-aga-r** [comment]
@mcerwin Please share the browser console log.

**Comment by mcerwin** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1055, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 122, in validate
    self.make_repeatable()
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 770, in make_repeatable
    create_custom_field(self.name, df)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 191, in create_custom_field
    custom_field.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 887, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find DocType: Display Quote

**Comment by s-aga-r** [comment]
@mcerwin Looks like you have a custom link field for Display Quote DocType which is now deleted.

**Comment by mcerwin** [comment]
"Display Quote" is the new name for the duplicated Quotation DocType.  This is a fresh install so if there are any custom fields in Quotation, they would have been included as part of the base installation.  

I'm no expert but it looks to be a "chicken before the egg" scenario where on initial save the DocType is trying to reference itself via the custom field, Since the document has not been saved yet, the DocType (Display Quote) does not exist to be referenced.  

Since the Quotation DocType is system generated and cannot be modified, I cannot remove the custom field prior to duplication. 

The DocType cannot be saved because of the invalid field reference but the field reference cannot be validated until I'm able to save the DocType with the new name.

¯\_(ツ)_/¯

**Comment by s-aga-r** [comment]
@mcerwin Disable the `Allow Auto Repeat` under Form Settings before saving the Duplicate DocType. Also, since it's a submitable DocType you need to change the `Amended From` field `Options` value from Quotation to Display Quote.

https://github.com/frappe/erpnext/assets/63660334/7fc66b60-97ef-431a-a4b1-a62e7b31260e

**Comment by s-aga-r** [comment]
FW Team, I think this ^ should be handled internally (?).
