### ISSUE TITLE
Issue with KSA Configuration 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#39045]
### Information about bug

Hi, Team 

I am trying to create a new company in KSA, and the following error is occurring: I installed the 8848 KSA app.

Repo : https://github.com/8848digital/KSA.git

![image](https://github.com/frappe/erpnext/assets/12432802/b57bdc1f-c61f-4766-b6c1-e450d798b713)

### Module

accounts, other

### Version

ERPNext: v15.8.3 (version-15)

Frappe Framework: v15.7.0 (version-15)

Frappe HR: v15.7.1 (version-15)

Ksa: v0.0.1 (dev)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Console

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 303, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1300, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/ksa/ksa/saudi_arabia/wizard/operations/setup_tax_templates.py", line 11, in setup_templates
    from_detailed_data(doc.name,template)
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 98, in from_detailed_data
    make_taxes_and_charges_template(company_name, "Sales Taxes and Charges Template", template)
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 148, in make_taxes_and_charges_template
    account = get_or_create_account(company_name, account_data)
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 220, in get_or_create_account
    tax_group = get_or_create_tax_group(company_name, root_type)
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 259, in get_or_create_tax_group
    root_account = frappe.get_all(
IndexError: list index out of range
```

**Comment by deepeshgarg007** [comment]
@sammish Please raise the issue on the KSA repo
