### ISSUE TITLE
Work order is not submitted while transferring against production plan.

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#39157]
### Information about bug

While making a production plan, we add a double row with the same item but different quantity and planning date.
![01](https://github.com/frappe/erpnext/assets/75109236/18c114c6-32a7-46d8-8690-d98541ce09b5)

And we get sub Assembly Items,
![2 (2)](https://github.com/frappe/erpnext/assets/75109236/acc496fc-ee68-4309-a0d9-2f1327666ab6)

And We procced to  make Work order,
![3 (2)](https://github.com/frappe/erpnext/assets/75109236/607559af-931c-49a3-89eb-9615d68e0a34)

But the Work order is created only for Nine 
![4](https://github.com/frappe/erpnext/assets/75109236/dd8d0f05-a2b1-4a67-a320-f66cdd03b249)

And we are Submit this Work Order for further processing, ther is a message pop-up like "Cannot produce more than 120.0 items for MOBILE PHONE "
![5](https://github.com/frappe/erpnext/assets/75109236/d96d8d13-6959-4ddb-ab27-71c2a9f1b7c3)

Because It takes only 2nd Row.
![Screenshot 2024-01-05 125255](https://github.com/frappe/erpnext/assets/75109236/bb790b36-7c80-4e63-8297-7fcb87a3626b)

![Screenshot 2024-01-05 131455](https://github.com/frappe/erpnext/assets/75109236/0a6e4768-65c7-4c66-ac8b-b254509acef7)

### Module

manufacturing

### Version

ERPNext: v15.3.0 
Frappe Framework: v15.2.1 
Frappe HR: v15.4.0
India Compliance: v15.0.1 

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 369, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 82, in validate
    self.validate_qty()
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 891, in validate_qty
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 571, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 543, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 497, in _raise_exception
    raise exc
erpnext.manufacturing.doctype.work_order.work_order.OverProductionError: Cannot produce more than 120.0 items for MOBILE PHONE
```

**Comment by rohitwaghchaure** [comment]
@sowndharya998 We have identified and fixed the issue and we'll release the [fix](https://github.com/frappe/erpnext/pull/39200) tomorrow
