### ISSUE TITLE
Uncaught Server Exception: There was an error building this page Error Code: 500

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/erpnext#39172]
### Information about bug

Uncaught Server Exception: There was an error building this page Error Code: 500

After updating using

`bench update
`
now I'm facing this server error all over erpnext 

<img width="665" alt="Screenshot 2024-01-06 at 16 52 10" src="https://github.com/frappe/erpnext/assets/67019341/f871eda7-1c84-47bf-b179-b5ab7e4123b3">

```

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 27, in get_context
    hooks = frappe.get_hooks()
            ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 167, in get
    frappe.get_attr(hook)(bootinfo=bootinfo)
    ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1673, in get_attr
    and app_name not in get_installed_apps()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'erpnext.startup.boot' has no attribute 'bootinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 522, in cache_html_decorator
    frappe.local.response.from_cache = True
         ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 162, in update_context
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 224, in run_pymodule_method
    if inspect.getfullargspec(method).args:
            ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    boot = frappe.sessions.get()
```

### Module

other

### Version

erpnext 15.9.1
frappe 15.8.1
gameplan 0.0.1
helpdesk 0.10.0
hrms 16.0.0-dev
lms 1.0.0
raven 1.3.2

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught Server Exception
There was an error building this page

Error Code: 500

If you don't know what just happened, and wish to file a ticket please
copy the error below and share it.

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 27, in get_context
    hooks = frappe.get_hooks()
            ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 167, in get
    frappe.get_attr(hook)(bootinfo=bootinfo)
    ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1673, in get_attr
    and app_name not in get_installed_apps()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'erpnext.startup.boot' has no attribute 'bootinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 522, in cache_html_decorator
    frappe.local.response.from_cache = True
         ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 162, in update_context
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 224, in run_pymodule_method
    if inspect.getfullargspec(method).args:
            ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    boot = frappe.sessions.get()
frappe.exceptions.SessionBootFailed
Footer Logo
CXG Experience Portal [Beta]
```

**Comment by yahyaoudra** [comment]
Solved that by updating server packages using

`apt get update`
