### ISSUE TITLE
Importing deliverynote into salesinvoice fails

### ISSUE THREAD

**Issue by ReinhardGruber** [frappe/erpnext#39199]
### Information about bug

when i try to import deliverynotes into a new salesinvoice i get the error message below

### Module

selling

### Version

Frappe Framework 6697b8f frappe/frappe:version-14

ERPNext v14.58.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"email_delivery_service": "0.0.1",
	"erpnext": "14.58.0",
	"frappe": "14.62.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/REC-24-0006
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/mapper.py", line 53, in map_docs
    target_doc = method(*_args)
TypeError: make_sales_invoice() takes from 1 to 2 positional arguments but 3 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.selling.doctype.quotation.quotation.make_sales_invoice",
		"source_names": "[\"ANG-23-0004-2\",\"ANG-23-0012-1\"]",
		"target_doc": "{\"docstatus\":0,\"doctype\":\"Sales Invoice\",\"name\":\"new-sales-invoice-vudaktepss\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"****@***.cc\",\"naming_series\":\"REC-.YY.-.####\",\"company\":\"Reinhard Gruber\",\"posting_date\":\"2024-01-08\",\"set_posting_time\":0,\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"currency\":\"EUR\",\"selling_price_list\":\"Standard-Vertrieb\",\"price_list_currency\":\"EUR\",\"ignore_pricing_rule\":0,\"update_stock\":0,\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"is_cash_or_non_trade_discount\":0,\"total_billing_amount\":0,\"allocate_advances_automatically\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"territory\":\"Austria\",\"ignore_default_payment_terms_template\":0,\"party_account_currency\":\"EUR\",\"is_opening\":\"No\",\"letter_head\":\"Header\",\"group_same_items\":0,\"status\":\"Draft\",\"customer_group\":\"Einzelperson\",\"is_internal_customer\":0,\"is_discounted\":0,\"repost_required\":0,\"items\":[],\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_tax_id\":null,\"company_address\":null,\"posting_time\":\"09:42:03\",\"company_address_display\":null,\"debit_to\":\"Schuldner - RG\",\"taxes_and_charges\":\"Austria Tax - RG\",\"taxes\":[{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-nlgakvspgy\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"*****@****.cc\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Haupt - RG\",\"account_currency\":null,\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-vudaktepss\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"row_id\":null,\"account_head\":\"VAT - RG\",\"description\":\"Umsatzsteuer 20%\",\"rate\":20,\"tax_amount\":0,\"total\":0,\"tax_amount_after_discount_amount\":0,\"base_tax_amount\":0,\"base_total\":0,\"base_tax_amount_after_discount_amount\":0,\"item_wise_tax_detail\":\"{\\\"undefined\\\":[20,0]}\"}],\"base_net_total\":0,\"net_total\":0,\"base_total\":0,\"total\":0,\"total_qty\":0,\"rounding_adjustment\":0,\"grand_total\":0,\"base_grand_total\":0,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":0,\"base_rounded_total\":0,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"payments\":[],\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":0,\"amount_eligible_for_commission\":0,\"total_commission\":null,\"tax_id\":null,\"customer_name\":\"Max Mustermann\",\"loyalty_program\":null,\"represents_company\":null,\"customer\":\"KUN-0004\",\"due_date\":\"2024-01-08\",\"customer_address\":\"KUN-0004-Abrechnung\",\"address_display\":\"Strasse 18<br>Musterdorf<br>\\n1111<br>Austria<br>\\n\",\"shipping_address_name\":\"KUN-0004-Abrechnung\",\"shipping_address\":\"Strasse 18<br>Musterdorf<br>\\n1111<br>Austria<br>\\n\",\"tax_category\":\"\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"de\",\"payment_terms_template\":null,\"sales_team\":[]}",
		"args": "{\"party_name\":\"KUN-0004\",\"merge_taxes\":0,\"filtered_children\":[]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.map_docs"
}
```
### Response Data
```
{
	"exception": "TypeError: make_sales_invoice() takes from 1 to 2 positional arguments but 3 were given"
}
```
```

**Comment by ReinhardGruber** [comment]
update to v15 fixed the problem
