### ISSUE TITLE
Asst Data Import

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#39261]
### Information about bug

Hello, Team 

When importing the asset through Excel, we are encountering the following error.

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 149, in import_data
    doc = self.process_doc(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 243, in process_doc
    return self.insert_record(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 262, in insert_record
    new_doc.insert()
  File "apps/frappe/frappe/model/document.py", line 303, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 953, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 950, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 193, in after_insert
    add_asset_activity(self.name, _("Asset created"))
  File "apps/erpnext/erpnext/assets/doctype/asset_activity/asset_activity.py", line 27, in add_asset_activity
    frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 555, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 902, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [Asset Activity, 535e7d8827]: date

![image](https://github.com/frappe/erpnext/assets/12432802/2a3b3547-48a5-48ae-a8fe-8eeae56e89f9)

### Module

assets

### Version

ERPNext: v15.9.1 (version-15)

Frappe Framework: v15.8.1 (version-15)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/pull/39113
