### ISSUE TITLE
AttributeError: 'str' object has no attribute 'nodes_'

### ISSUE THREAD

**Issue by alsubaei** [frappe/erpnext#39413]
### Information about bug

it must ask me to enter the customer when checking the Allocate Advances Automatically  but
 the error message has appeared

### Module

accounts

### Version

ERPNext: v15.10.0 (version-15)
Frappe Framework: v15.9.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### Response Data

{
	"exception": "AttributeError: 'str' object has no attribute 'nodes_'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by aleks473** [comment]
## Route

```

List/Task/List

```

### Traceback

```

Traceback (most recent call last):

  File "apps/frappe/frappe/app.py", line 114, in application

    response = frappe.api.handle(request)

  File "apps/frappe/frappe/api/__init__.py", line 49, in handle

    data = endpoint(**arguments)

  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call

    return frappe.handler.handle()

  File "apps/frappe/frappe/handler.py", line 49, in handle

    data = execute_cmd(cmd)

  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd

    return frappe.call(method, **frappe.form_dict)

  File "apps/frappe/frappe/__init__.py", line 1768, in call

    return fn(*args, **newargs)

  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper

    return func(*args, **kwargs)

  File "apps/alerts/alerts/utils/alert.py", line 144, in sync_alerts

    data["alerts"] = get_user_alerts(user)

  File "apps/alerts/alerts/utils/alert.py", line 260, in get_user_alerts

    data = filter_seen_alerts(data, user, parents, today)

  File "apps/alerts/alerts/utils/alert.py", line 341, in filter_seen_alerts

    seen_by = get_alerts_seen_by(user, alerts)

  File "apps/alerts/alerts/utils/alert.py", line 327, in get_alerts_seen_by

    .where(doc.parent.isin(alerts))

  File "env/lib/python3.10/site-packages/pypika/utils.py", line 50, in _copy

    result = func(self_copy, *args, **kwargs)

  File "env/lib/python3.10/site-packages/pypika/queries.py", line 930, in where

    if not self._validate_table(criterion):

  File "env/lib/python3.10/site-packages/pypika/queries.py", line 1155, in _validate_table

    for field in term.fields_():

  File "env/lib/python3.10/site-packages/pypika/terms.py", line 57, in fields_

    return set(self.find_(Field))

  File "env/lib/python3.10/site-packages/pypika/terms.py", line 37, in find_

    return [node for node in self.nodes_() if isinstance(node, type)]

  File "env/lib/python3.10/site-packages/pypika/terms.py", line 37, in <listcomp>

    return [node for node in self.nodes_() if isinstance(node, type)]

  File "env/lib/python3.10/site-packages/pypika/terms.py", line 795, in nodes_

    yield from self.container.nodes_()

AttributeError: 'str' object has no attribute 'nodes_'



```

### Request Data

```

{

	"type": "POST",

	"args": {

  "init": 1

	},

	"headers": {},

	"error_handlers": {},

	"url": "/api/method/alerts.utils.sync_alerts",

	"request_id": null

}

```

### Response Data

```

{

	"exception": "AttributeError: 'str' object has no attribute 'nodes_'",

	"exc_type": "AttributeError",

	"_exc_source": "alerts (app)"

}

We get the same error. version 15.33.5

**Comment by nabinhait** [comment]
Can't replicate the issue. If you can replicate the issue, please reopen the issue with the replication steps and screenshots.

**Comment by aleks473** [comment]
![Image](https://github.com/user-attachments/assets/e03221f5-89fe-464c-b53e-a2b5db976f3c)
![Image](https://github.com/user-attachments/assets/7724c806-4241-46be-a818-d2953075fc3b)

### App Versions
```
{
  "alerts": "1.0.8",
  "dinord_erpnext_customization": "3.5.0",
  "dinord_timesheet": "0.0.1",
  "doctype_permission": "0.0.1",
  "erpnext": "15.44.0",
  "frappe": "15.48.0",
  "frappe_better_attach_control": "2.0.0",
  "frappe_better_list_view": "1.4.0",
  "frappe_better_select_control": "1.2.1",
  "frappe_telegram": "0.0.1",
  "hrms": "16.0.0-dev",
  "insights": "2.2.2",
  "lms": "2.4.0",
  "persona": "0.0.1",
  "print_designer": "1.0.0-dev",
  "quick_kanban": "0.0.1",
  "wiki": "2.0.0"
}
```
### Route
```
Workspaces/Home
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/alerts/alerts/utils/alert.py", line 144, in sync_alerts
    data["alerts"] = get_user_alerts(user)
  File "apps/alerts/alerts/utils/alert.py", line 260, in get_user_alerts
    data = filter_seen_alerts(data, user, parents, today)
  File "apps/alerts/alerts/utils/alert.py", line 341, in filter_seen_alerts
    seen_by = get_alerts_seen_by(user, alerts)
  File "apps/alerts/alerts/utils/alert.py", line 327, in get_alerts_seen_by
    .where(doc.parent.isin(alerts))
  File "env/lib/python3.10/site-packages/pypika/utils.py", line 50, in _copy
    result = func(self_copy, *args, **kwargs)
  File "env/lib/python3.10/site-packages/pypika/queries.py", line 930, in where
    if not self._validate_table(criterion):
  File "env/lib/python3.10/site-packages/pypika/queries.py", line 1155, in _validate_table
    for field in term.fields_():
  File "env/lib/python3.10/site-packages/pypika/terms.py", line 57, in fields_
    return set(self.find_(Field))
  File "env/lib/python3.10/site-packages/pypika/terms.py", line 37, in find_
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "env/lib/python3.10/site-packages/pypika/terms.py", line 37, in <listcomp>
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "env/lib/python3.10/site-packages/pypika/terms.py", line 795, in nodes_
    yield from self.container.nodes_()
AttributeError: 'str' object has no attribute 'nodes_'

```
### Request Data
```
{
  "type": "POST",
  "args": {
    "init": 1
  },
  "headers": {},
  "error_handlers": {},
  "url": "/api/method/alerts.utils.sync_alerts",
  "request_id": null
}
```
### Response Data
```
{
  "exception": "AttributeError: 'str' object has no attribute 'nodes_'",
  "exc_type": "AttributeError",
  "_exc_source": "alerts (app)"
}
```

**Comment by nabinhait** [comment]
@alsubaei @aleks473 This error is coming from an application called 'alerts' developed by 3rd party community developer. You should raise an issue on that repository (https://github.com/kid1194/frappe_alerts).
