### ISSUE TITLE
Problem with lending

### ISSUE THREAD

**Issue by bmelendez80** [frappe/erpnext#39455]
### Information about bug

Hi, I am testing out the lending app for ERPNext.  Upon trying to submit first loan repayment I get the below error.  Please advise.

The relevant part of the below block seems to be:

""exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'charges_receivable_account' in 'field list'\")",
	"exc_type": "OperationalError",
	"_exc_source": "lending (app)""

### Module

other

### Version

ERPNext: v15.10.1 (HEAD)

Frappe Framework: v15.10.0 (HEAD)

Frappe Lending: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.10.1",
	"frappe": "15.10.0",
	"lending": "0.0.1"
}
```
### Route
```
Form/Loan Repayment/LM-REP-0001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1042, in submit
    return self._submit()
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1023, in _submit
    return self.save()
           ^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 387, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1125, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 954, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1320, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1302, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 951, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/lending/lending/loan_management/doctype/loan_repayment/loan_repayment.py", line 56, in on_submit
    self.make_gl_entries()
  File "apps/lending/lending/loan_management/doctype/loan_repayment/loan_repayment.py", line 634, in make_gl_entries
    account_details = frappe.db.get_value(
                      ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 516, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 617, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 884, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 235, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'charges_receivable_account' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"LM-REP-0001\",\"owner\":\"brianm@getvst.com\",\"creation\":\"2024-01-18 14:18:22.160794\",\"modified\":\"2024-01-18 14:18:22.160794\",\"modified_by\":\"brianm@getvst.com\",\"docstatus\":0,\"idx\":0,\"against_loan\":\"ACC-LOAN-2024-00001\",\"applicant_type\":\"Customer\",\"applicant\":\"Green Screen Teks LLC - 1\",\"loan_product\":\"B\",\"repayment_type\":\"Normal Repayment\",\"loan_restructure\":null,\"company\":\"Brian Melendez Lending\",\"posting_date\":\"2024-02-15 14:15:52\",\"clearance_date\":null,\"rate_of_interest\":10,\"days_past_due\":0,\"is_term_loan\":1,\"offset_based_on_npa\":0,\"is_npa\":0,\"manual_npa\":0,\"due_date\":null,\"pending_principal_amount\":-10494.39,\"interest_payable\":0,\"payable_amount\":0,\"shortfall_amount\":0,\"payable_principal_amount\":0,\"penalty_amount\":0,\"amount_paid\":2125,\"cost_center\":\"Main - BML\",\"total_charges_payable\":0,\"total_paid_charges\":0,\"reference_number\":null,\"reference_date\":null,\"principal_amount_paid\":0,\"total_penalty_paid\":0,\"total_interest_paid\":0,\"amended_from\":null,\"payment_account\":\"Debtors - BML\",\"penalty_income_account\":\"Sales - BML\",\"loan_account\":\"Cash - BML\",\"doctype\":\"Loan Repayment\",\"repayment_details\":[],\"pending_charges\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-01-18T19:18:22.226Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370039763826111461941": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 10736,
						"namespace": ""
					}
				]
			}
		},
		"__sentry_instrumentation_handlers__": {
			"click": {
				"refCount": 1
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "3a24ceb8-07e5-4eb5-8a43-99b715c932cf"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'charges_receivable_account' in 'field list'\")",
	"exc_type": "OperationalError",
	"_exc_source": "lending (app)"
}
```
```

**Comment by Nihantra-Patel** [comment]
Please check using the newer version (version-1 or develop), as many changes and bugs have been fixed. If you have installed frappe erpnext version 15, then you should install lending version-15 or version-1. The develop version is not compatible with frappe erpnext version 15.
