### ISSUE TITLE
Attribute Error from Repost Item Valuation file that makes repost item valuations to fail

### ISSUE THREAD

**Issue by samuelvictor2019** [frappe/erpnext#39463]
### Information about bug

Repost Item Valuation transactions fail and show an error in the provided column of the tabRepost Item Valuation table of the database. Going through the files show that none of the two linked files carries the attribute meanwhile, it is referenced from the application side

### Module

stock

### Version

ERPNext: v14.60.1 (version-14)
Frappe Framework: v14.48.1 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
<br>Traceback: <br>Traceback (most recent call last):
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 254, in repost
    repost_sl_entries(doc)
  File "apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 288, in repost_sl_entries
    repost_future_sle(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 230, in repost_future_sle
    if doc and doc.reposting_data_file:
AttributeError: 'RepostItemValuation' object has no attribute 'reposting_data_file'
```

**Comment by thida-bcn** [comment]
i got following error
"Unknown column 'validate_negative_stock'

**Comment by samuelvictor2019** [comment]
@thida-bcn check that the target table in the database has the column named "validate_negative_stock". You can manually add it if you don't find it and the error should be resolved
