### ISSUE TITLE
ModuleNotFoundError: No module named 'education.education.setup'

### ISSUE THREAD

**Issue by Tomkar9** [frappe/erpnext#39504]
### Information about bug

i want to set domain to education but its giving me this error

ModuleNotFoundError: No module named 'education.education.setup'

### Module

education

### Version

Education: v0.0.1 (develop)

ERPNext: v15.0.0 (version-15)

Frappe Framework: v15.0.2 (version-15)

Frappe Health: v15.0.0-dev (develop)

Frappe HR: v16.0.0-dev (develop)

Frappe LMS: v1.0.0 (main)

Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by shakkeert** [comment]
Same here, could not not enable Retail domain in Domain settings getting same error.

Below is the error details.


### App Versions
```
{
	"education": "15.3.0",
	"erpnext": "14.69.0",
	"frappe": "14.73.0",
	"hrms": "16.0.0-dev",
	"posawesome": "6.3.0"
}
```
### Route
```
Form/Domain Settings/Domain Settings
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1098, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/domain_settings/domain_settings.py", line 28, in on_update
    self.restrict_roles_and_modules()
  File "apps/frappe/frappe/core/doctype/domain_settings/domain_settings.py", line 41, in restrict_roles_and_modules
    data = frappe.get_domain_data(domain)
  File "apps/frappe/frappe/__init__.py", line 884, in get_domain_data
    return _dict(get_attr(get_hooks("domains")[module][0] + ".data"))
  File "apps/frappe/frappe/__init__.py", line 1609, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'education.education.setup'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Domain Settings\",\"owner\":\"Administrator\",\"modified\":\"2023-12-24 13:49:11.992714\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":\"0\",\"doctype\":\"Domain Settings\",\"active_domains\":[{\"docstatus\":0,\"doctype\":\"Has Domain\",\"name\":\"new-has-domain-wwsfubnjjm\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"info@dockcode.ae\",\"parent\":\"Domain Settings\",\"parentfield\":\"active_domains\",\"parenttype\":\"Domain Settings\",\"idx\":1,\"domain\":\"Retail\"}],\"__last_sync_on\":\"2024-05-03T16:40:27.083Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600069118298822968161": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 399,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'education.education.setup'"
}
```

**Comment by nabinhait** [comment]
Education is now not a part of the erpnext product, it is a new product. You might need to install the Education app. 
https://github.com/frappe/education
