### ISSUE TITLE
SQL error when saving new task ("Out of range value for column 'actual_time' at row 1")

### ISSUE THREAD

**Issue by betoled** [frappe/erpnext#39515]
### Information about bug

I expect to save the new task without error.

### Module

projects

### Version

ERPNext: v15.10.4 (version-15)

Frappe Framework: v15.10.0 (version-15)

Frappe HR: v15.9.1 (version-15)

Payments: v0.0.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"betoled_integration": "0.0.1",
	"erpnext": "15.10.4",
	"frappe": "15.10.0",
	"hrms": "15.9.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Task/new-task-khhquizamo
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1122, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 954, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1302, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 951, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/projects/doctype/task/task.py", line 184, in on_update
    self.update_project()
  File "apps/erpnext/erpnext/projects/doctype/task/task.py", line 212, in update_project
    frappe.get_cached_doc("Project", self.project).update_project()
  File "apps/erpnext/erpnext/projects/doctype/project/project.py", line 205, in update_project
    self.db_update()
  File "apps/frappe/frappe/model/base_document.py", line 587, in db_update
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 235, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'actual_time' at row 1")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Task\",\"name\":\"new-task-khhquizamo\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"benjamien@betoled.com\",\"is_group\":0,\"is_template\":0,\"status\":\"Open\",\"priority\":\"Medium\",\"expected_time\":0,\"is_milestone\":0,\"depends_on\":[],\"company\":\"BETOWARE BV\",\"custom_klant\":\"A.A.B. bvba\",\"project\":\"AAB, V-P7.62SMS, 1.83x1.52, op paal\",\"subject\":\"Deel van rij blijft zwart\",\"task_weight\":0,\"type\":\"Interventie op locatie\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370068611833263690681": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1127,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.DataError: (1264, \"Out of range value for column 'actual_time' at row 1\")",
	"exc_type": "DataError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by diptanilsaha** [comment]
Reopen this issue if you are still facing the issue.
