### ISSUE TITLE
Error 500 and site completely broken

### ISSUE THREAD

**Issue by azambuilds** [frappe/erpnext#39781]
### Information about bug

Using the official ERPNext image. My site is now completely inoperable after a few days up. Deployed via docker

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit, other

### Version

Frappe/ERPNext:15.11.1 docker image

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "apps/frappe/frappe/website/path_resolver.py", line 112, in resolve_redirect
    redirects += frappe.get_all("Website Route Redirect", ["source", "target"], order_by=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1972, in get_all
    return get_list(doctype, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1947, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 179, in execute
    if is_virtual_doctype(self.doctype):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/caching.py", line 123, in site_cache_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/utils/__init__.py", line 133, in is_virtual_doctype
    if frappe.db.has_column("DocType", "is_virtual"):
       ^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/werkzeug/local.py", line 490, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: object is not bound
```

**Comment by azambuilds** [comment]
Okay turns out the backend service was running an image which wasn't the same as the image for the frontend service. This caused the scheduler to fail looking for an app that wasn't there. Closing
