### ISSUE TITLE
Gmail account setup issue in V15

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [frappe/erpnext#39791]
### Information about bug

We are trying to add Gmail account in V15 but can't create account or not showing any error msg, bcz we have already setup App password on Gmail account.

If I was checking in Inspect console log these error is showing, Now we are using Gmail account only, not using any domain or thirdparty services.

<img width="504" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/94045290-7142-43b5-8131-16aa7ac40576">

Last week I have successfully  setup same Gmail account on same server and tested but now I'm creating new user then system not delivered welcome email to user showing error
<img width="649" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/8cb2b610-faaf-4fc2-a5e9-1f1f575bb80f">

### Module

integrations, portal, other

### Version

<img width="161" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/f8c0d866-78ce-4ba4-b4b9-c1b1bebeb734">

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
websocket.js:121 WebSocket connection to 'ws://10.1.200.71:9000/socket.io/?EIO=4&transport=websocket&sid=PPl5gNNylXx6TBPjAAE2' failed: WebSocket is closed before the connection is established.
doClose @ websocket.js:121
Show 1 more frame
Show less
moment.js:287 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:11268:92)
    at configFromString (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:12805:19)
    at configFromInput (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:13098:13)
    at prepareConfig (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:13084:13)
    at createFromConfig (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:13059:46)
    at createLocalOrUTC (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:13131:18)
    at createUTC (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:11113:18)
    at Function.y [as tz] (http://10.1.200.71:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:15082:127)
    at Object.convert_to_user_tz (http://10.1.200.71:8000/assets/frappe/dist/js/desk.bundle.JID4EA3E.js:41066:27)
    at prettyDate (http://10.1.200.71:8000/assets/frappe/dist/js/desk.bundle.JID4EA3E.js:40914:30)
warn @ moment.js:287
Show 1 more frame
Show less
:8000/api/method/frappe.desk.form.save.savedocs:1 
        
        
       Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
request.js:362 Unable to handle failed response
request.js:363 SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at frappe.request.report_error (request.js:528:18)
    at 500 (request.js:224:20)
    at Object.<anonymous> (request.js:356:6)
    at fire (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at done (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
(anonymous) @ request.js:363
request.js:279 
        
        
       POST http://10.1.200.71:8000/api/method/frappe.desk.form.save.savedocs 500 (INTERNAL SERVER ERROR)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymous) @ form.js:820
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymous) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymous) @ page.js:281
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Show 4 more frames
Show less
request.js:362 Unable to handle failed response
request.js:363 SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at frappe.request.report_error (request.js:528:18)
    at 500 (request.js:224:20)
    at Object.<anonymous> (request.js:356:6)
    at fire (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at done (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
(anonymous) @ request.js:363
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymous) @ jquery.js:9878
load (async)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymous) @ form.js:820
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymous) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymous) @ page.js:281
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Show 8 more frames
Show less
request.js:279 
        
        
       POST http://10.1.200.71:8000/api/method/frappe.desk.form.save.savedocs 500 (INTERNAL SERVER ERROR)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymous) @ form.js:820
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymous) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymous) @ page.js:281
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Show 4 more frames
Show less
request.js:362 Unable to handle failed response
request.js:363 SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at frappe.request.report_error (request.js:528:18)
    at 500 (request.js:224:20)
    at Object.<anonymous> (request.js:356:6)
    at fire (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at done (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
```

**Comment by diptanilsaha** [comment]
@BHAGYASHRIMHASKE Email issues are fixed in the latest release of Frappe and ERPNext version 15. If you are still facing the issue, please open a new issue.
