### ISSUE TITLE
Workflow Actions Auto Email Not Send by System in V15

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [frappe/erpnext#39813]
### Information about bug

We have setup workflow on Purchase order and set send auto email alerts but email not send to user (User having permission and role for approval)

<img width="619" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/b08b84a5-1b25-42f0-9b76-0410a3b7dc0a">

****Scheduler Is Active but log failed and not showing in email queue list**
<img width="680" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/459619dd-4f0f-4893-baa4-40930f83b98a">

### Module

stock, buying, manufacturing, integrations, portal

### Version

<img width="184" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/14fb74c0-317e-4947-be18-c4e66645bbdd">

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 213, in execute_job
    retval = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/workflow/doctype/workflow_action/workflow_action.py", line 367, in send_workflow_action_email
    common_args = get_common_email_args(doc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/workflow/doctype/workflow_action/workflow_action.py", line 482, in get_common_email_args
    "attachments": [frappe.attach_print(doctype, docname, file_name=docname, doc=doc)],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/__init__.py", line 2133, in attach_print
    else get_print(doctype, name, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/__init__.py", line 2092, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 85, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "/home/aits/frappe-bench/env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
The switch --print-media-type, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --disable-smart-shrinking, is not support using unpatched qt, and will be ignored.Exit with code 1 due to network error: HostNotFoundError
```

**Comment by ankush** [comment]
INstall right version from here https://wkhtmltopdf.org/downloads.html
