### ISSUE TITLE
Changing qty in Sales Order or Delivery Note causes error

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#39944]
### Information about bug

Steps to reproduce:
1) Create a Sales Invoice.
2) Fetch Items from existing Sales Order
3) Change qty on any item
4) TypeError: remove_pricing_rule_for_item() missing 1 required positional argument: 'pricing_rules'
5) The error can be ignored. The document can still be saved and submitted.

The same issue occurs in Delivery Note.

### Module

selling

### Version

ERPNext - 15.14.0
Frappe - 15.14.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.14.0",
	"frappe": "15.14.0",
	"india_compliance": "15.5.1",
	"payments": "0.0.1",
	"print_designer": "1.0.0",
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-iqclwiszio
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
TypeError: remove_pricing_rule_for_item() missing 1 required positional argument: 'pricing_rules'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_details": "{\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-ebklazjpkd\",\"item_code\":\"SKU-00464\",\"parenttype\":\"Sales Invoice\",\"parent\":\"new-sales-invoice-iqclwiszio\",\"price_list_rate\":0}",
		"item_code": "SKU-00464",
		"rate": 0
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.pricing_rule.pricing_rule.remove_pricing_rule_for_item",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: remove_pricing_rule_for_item() missing 1 required positional argument: 'pricing_rules'",
	"exc_type": "TypeError"
}
```
```

**Comment by SvbZ3r0** [comment]
Duplicate of #39912
