### ISSUE TITLE
Unable to Deliver Full Available Stock Quantity

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#39989]
### Information about bug

I am encountering an issue within the Stock module where I am unable to deliver the full amount of available stock. Despite having a stock quantity of 101 (100 from one batch and 1 from another), the system restricts deliveries to approximately 50% of the available quantity. Attempting to create a delivery note for the full 100 units results in an error message indicating negative stock for the batch, despite sufficient stock being present in the warehouse.

**Steps to Reproduce:**

1. Create an Item with the 'Batch' option enabled.
2. Create a Purchase Receipt for the item with the following details:
_Batch No: Tab0001
Quantity: 100
Warehouse: Stores_
3. Create an additional Purchase Receipt for the same item with the following details:
_Batch No: Tab0002 (or any unique batch number)
Quantity: 1
Warehouse: Stores_
4. Confirm the total stock in the 'Stores - FSLD' warehouse is 101 qty.
5. Attempt to create a Delivery Note for the full 100 qty from Batch No Tab0001.

**Expected Result:**
The Delivery Note should be created successfully, allowing the delivery of the full 100 qty from Batch No Tab0001.

**Actual Result:**
Received an error message stating: "Batch No Tab0001 has negative stock of quantity -45.0 in the warehouse Stores - FSLD". This prevents the creation of a Delivery Note for more than 55 qty.

![Feb-21-2024 07-23-17](https://github.com/frappe/erpnext/assets/9102676/d35a4459-f6a7-43d7-b624-ac3493dac672)

### Module

stock

### Version

ERPNext: v15.14.3 (version-15)
Frappe Framework: v15.15.0 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1041, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1024, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 331, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 384, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1124, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 955, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1315, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1297, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 952, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py", line 405, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 529, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 645, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 95, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 222, in make_entry
    sle.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1041, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1024, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 331, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 353, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 309, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1124, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 955, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1315, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1297, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 952, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 172, in on_submit
    SerialBatchBundle(
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 23, in __init__
    self.process_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 33, in process_serial_and_batch_bundle
    self.process_batch_no()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 175, in process_batch_no
    self.make_serial_batch_no_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 77, in make_serial_batch_no_bundle
    ).make_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 849, in make_serial_and_batch_bundle
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1041, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1024, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 331, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 367, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1087, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 955, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1315, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1297, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 952, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 101, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 209, in set_incoming_rate
    self.set_incoming_rate_for_outward_transaction(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 265, in set_incoming_rate_for_outward_transaction
    self.validate_negative_batch(d.batch_no, available_qty)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 280, in validate_negative_batch
    frappe.throw(_(msg), BatchNegativeStockError)
  File "apps/frappe/frappe/__init__.py", line 589, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 561, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 512, in _raise_exception
    raise exc
erpnext.stock.doctype.serial_and_batch_bundle.serial_and_batch_bundle.BatchNegativeStockError: Batch No <strong>Tab0001</strong> has negative stock
				of quantity <strong>-45.0</strong> in the
				warehouse Stores - FSLD
```

**Comment by rohitwaghchaure** [comment]
@rknroot 

I have tested on latest v15 version and it's working fine

Created two purchase receipts 100, 1 qty respectively

<img width="1349" alt="Screenshot 2024-02-21 at 12 24 44 PM" src="https://github.com/frappe/erpnext/assets/8780500/e388389e-614f-4d78-9096-34bc8acd2ccb">


Then created delivery note 

 
<img width="1313" alt="Screenshot 2024-02-21 at 12 25 17 PM" src="https://github.com/frappe/erpnext/assets/8780500/5336510f-0dc9-4f14-b197-b03ffa8c6061">


Have you done any customization? could you update your site and check
