### ISSUE TITLE
AttributeError: 'MariaDBDatabase' object has no attribute 'unbuffered_cursor' - While Generating Stock Balance Report 

### ISSUE THREAD

**Issue by npkwild** [frappe/erpnext#40084]
### Information about bug

While Generating the stock balance report , error was raised in prepared report . 

Traceback (most recent call last):
File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 79, in generate_report
result = generate_report_result(report=report, filters=instance.filters, user=instance.owner)
File "apps/frappe/frappe/__init__.py", line 808, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File "apps/frappe/frappe/desk/query_report.py", line 89, in generate_report_result
res = get_report_result(report, filters) or []
File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
res = report.execute_script_report(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
res = self.execute_module(filters)
File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
return frappe.get_attr(method_name)(frappe._dict(filters))
File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 39, in execute
return StockBalanceReport(filters).run()
File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 66, in run
self.prepare_new_data()
File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 93, in prepare_new_data
self.item_warehouse_map = self.get_item_warehouse_map()
File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 144, in get_item_warehouse_map
with frappe.db.unbuffered_cursor():
AttributeError: 'MariaDBDatabase' object has no attribute 'unbuffered_cursor'

![error](https://github.com/frappe/erpnext/assets/83958109/1838bc73-5a5a-40b1-860f-1feb080e5fab)
![error2](https://github.com/frappe/erpnext/assets/83958109/d05425c5-ae13-4e5c-a646-40311006f707)

### Module

stock

### Version

ERPNext: v14.63.3 (version-14)
Frappe Framework: v14.62.2 (version-14)

### Installation method

None

**Comment by npkwild** [comment]
Sollution : Upgrade Frappe to latest version

**Comment by npkwild** [comment]
Solution : Upgrade the Frappe to latest version
