### ISSUE TITLE
Selling Trends and Buying Trends Reports Are not Open

### ISSUE THREAD

**Issue by creative-paramu** [frappe/erpnext#40115]
### Information about bug

Sales Invoice Trends and Purchase Invoice Trends Are sometimes open and sometimes not open only showing the fiscal year is mandatory, how to fix it?
![image](https://github.com/frappe/erpnext/assets/101092028/b5dbdab2-818e-4fe3-8c2e-f762152fa8f5)
![image](https://github.com/frappe/erpnext/assets/101092028/dcb6a28b-1baf-49ea-a56f-31b5ecf82657)

### Module

buying, selling

### Version

frappe 15.15.0
erpnext 15.14.6

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1785, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 954, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 219, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 954, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 81, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 162, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 179, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/purchase_invoice_trends/purchase_invoice_trends.py", line 12, in execute
    conditions = get_columns(filters, "Purchase Invoice")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 678, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 643, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 594, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Fiscal Year is mandatory
```

**Comment by donnieferdian** [comment]
@creative-paramu 
close the pop-up message, then refresh your browser,..
it will be works,...

**Comment by Nihantra-Patel** [comment]
Issue has been fixed: https://github.com/frappe/erpnext/pull/41544

Upcoming update will resolve your issue.
