### ISSUE TITLE
Subcontracting Receipt fails if rate is zero

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#40177]
### Information about bug

- Create a purchase order and set it as subcontracting. Set rate as zero in the item grid.
- Create and submit subcontracting order.
- Send raw materials to supplier.
- You will get below error when submitting the subcontracting receipt. 
"Incorrect number of General Ledger Entries found. You might have selected a wrong Account in the transaction"
![image](https://github.com/frappe/erpnext/assets/710051/97014b70-d3f6-46aa-8bd1-9a8d69a7fde2)

- If you cancel the documents and repeat the same process with given rate in the purchase order it is working as expected.

ERPNext v15 and v14 have the same result.

### Module

stock, buying

### Version

ERPNext v15
Frappe v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 361, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1098, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 922, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1284, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1266, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 919, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py", line 108, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 79, in make_gl_entries
    make_gl_entries(gl_entries, from_repost=from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 48, in make_gl_entries
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Incorrect number of General Ledger Entries found. You might have selected a wrong Account in the transaction.
```

**Comment by TurkerTunali** [comment]
I see that this statement checks for row count in the gl entry.
https://github.com/frappe/erpnext/blob/9dcdd5b5ef7b71fb1a51d5ee14ee61afd5c50465/erpnext/accounts/general_ledger.py#L39

When debugging this statement doesn't result to correct so it can't create a second row.
https://github.com/frappe/erpnext/blob/9dcdd5b5ef7b71fb1a51d5ee14ee61afd5c50465/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py#L550

So, it doesn't generate the needed gl entry. If there is only one gl entry it creates an exception.

I think that below line should be in an if statement. If there isn't any service cost, this statement should not be executed.
https://github.com/frappe/erpnext/blob/9dcdd5b5ef7b71fb1a51d5ee14ee61afd5c50465/erpnext/subcontracting/doctype/subcontracting_receipt/subcontracting_receipt.py#L522

**Comment by herdemhuseyin** [comment]
Same problem
