### ISSUE TITLE
No Option to mention Overproduction in Jobcards

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#40235]
### Information about bug

We have enabled over production in manufacturing setting. 
the situation is to manufacture 100 QTY but the manufactured quantity is 105
while submitting the jobcard am unable to set over production

![image](https://github.com/frappe/erpnext/assets/112148467/4905b21f-0ad9-4574-8ffa-e64efdee9f6b)

Qty to manufacture is 1
Qty Manufactured is 2 

over production is enabled 

but when i submit the job card following error happens

![image](https://github.com/frappe/erpnext/assets/112148467/e7d8c146-b43f-4447-a3bb-2e0a669654fb)

Kindly suggest

Snapshot of Manufacturing settings

![image](https://github.com/frappe/erpnext/assets/112148467/1a550c42-6086-4f61-b8c8-a1274b7f31f6)

### Module

manufacturing

### Version

ERPNext: v15.15.0 (HEAD)
Frappe Framework: v15.16.1 (HEAD)
Frappe HR: v15.12.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1697, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1041, in submit
    return self._submit()
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1024, in _submit
    return self.save()
           ^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 331, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 384, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1124, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 955, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1315, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1297, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 952, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 632, in on_submit
    self.validate_job_card()
  File "apps/erpnext/erpnext/manufacturing/doctype/job_card/job_card.py", line 677, in validate_job_card
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 593, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 565, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 516, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: The <strong>Total Completed Qty</strong> (<strong>2.0</strong>) must be equal to <strong>Qty to Manufacture</strong> (<strong>1</strong>)
desk.bundle.XAKBVE4M.js:453:7393
```

**Comment by mihir-kandoi** [comment]
I need exact replication steps.
