### ISSUE TITLE
Process Statement of Account fails when sender is set

### ISSUE THREAD

**Issue by borgmatthew** [frappe/erpnext#40247]
### Information about bug

When a "sender" is set for a Process Statement of Account doc, the emails are not sent and an exception is thrown. This is happening because the `sender` field is of type `Link`, but [here](https://github.com/frappe/erpnext/blob/e7d707797aeab2f5d209690c959e88851c9a6999/erpnext/accounts/doctype/process_statement_of_accounts/process_statement_of_accounts.py#L462) the value of the field is used as an email address.

The exception is attached (email redacted). The `sender` field can be configured when the `Enable Auto Email` is set.

### Module

accounts

### Version

Frappe version: v15.16.1
Erpnext version: v15.15.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Invalid email address Sender: Matthew Borg Seychell, Recipients: ***@gmail.com, 
Traceback: Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 745, in as_dict
    mail_to_string = cstr(mail.as_string())
                          ^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/email_body.py", line 338, in as_string
    self.validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/email_body.py", line 262, in validate
    validate_email_address(strip(self.sender), True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 196, in validate_email_address
    email = _check(e.strip())
            ^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 186, in _check
    frappe.throw(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 593, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 565, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 516, in _raise_exception
    raise exc
frappe.exceptions.InvalidEmailAddressError: Matthew Borg Seychell is not a valid Email Address
```

**Comment by precihole** [comment]
@borgmatthew can you share screenshot?

**Comment by borgmatthew** [comment]
This is the error message shown:
![image](https://github.com/frappe/erpnext/assets/6809592/5e5ec09a-b45a-48fd-9a88-b3e2deb642f7)

Do you require any additional information?

**Comment by precihole** [comment]
Yes, that is a bug originating from Frappe's end.
