### ISSUE TITLE
Unable to import data - frappe.ui.FileUploader is not a constructor

### ISSUE THREAD

**Issue by nonfatalexec** [frappe/erpnext#40319]
### Information about bug

When in the "Data Import" screen, and clicking the "Attach File" "Attach" button, nothing happens.
![Screenshot from 2024-03-06 13-15-52](https://github.com/frappe/erpnext/assets/17789634/1ef9c3e8-4b5e-4549-bd37-f2b0cb70b900)

### Module

other

### Version

ERPNext: v15.16.1
Frappe Framework: v15.17.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught TypeError: frappe.ui.FileUploader is not a constructor
    at frappe.ui.form.ControlAttach.on_attach_click (controls.bundle.5FRJCH7T.js:15316:747)
    at HTMLButtonElement.click (controls.bundle.5FRJCH7T.js:15307:1430)
    at HTMLButtonElement.dispatch (jquery.js:5135:27)
    at Rt.handle (jquery.js:4939:28)
```

**Comment by nonfatalexec** [comment]
Resolved with `bench --site sitename migrate`
