### ISSUE TITLE
Accounting Dimension  it is loading it in the POS Profile form

### ISSUE THREAD

**Issue by ernestoruiz89** [frappe/erpnext#40338]
### Information about bug

I have configured an accounting dimension, it is  loading it in the POS Profile form, therefore it gives an error on Save

![image](https://github.com/frappe/erpnext/assets/1592496/431da9a2-3eb8-4ed0-b634-a4a9e3f38290)

![image](https://github.com/frappe/erpnext/assets/1592496/904288d5-eff3-45ed-ab5a-87e7f84cc677)

![image](https://github.com/frappe/erpnext/assets/1592496/bda5b906-58a2-4c71-ae30-f586916fc80b)

### Module

accounts

### Version

ERPNext: v15.15.0
Frappe Framework: v15.16.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1697, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 331, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 353, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1084, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 955, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1315, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1297, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 952, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/pos_profile/pos_profile.py", line 68, in validate
    self.validate_accounting_dimensions()
  File "apps/erpnext/erpnext/accounts/doctype/pos_profile/pos_profile.py", line 74, in validate_accounting_dimensions
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 593, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 565, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 516, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: <Strong>Sucursal</Strong> is a mandatory Accounting Dimension. <br>Please set a value for <Strong>Sucursal</Strong> in Accounting Dimensions section.
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.

Please check it.


![image](https://github.com/frappe/erpnext/assets/141945075/38aa8a1b-89d9-4528-9d1f-0a1df9b7aa33)

![image](https://github.com/frappe/erpnext/assets/141945075/d35f99c8-9e5c-4dfd-8239-40887b6d6ead)
