### ISSUE TITLE
Exchange rate error in payment reconciliation 

### ISSUE THREAD

**Issue by albertfns** [frappe/erpnext#40345]
### Information about bug

Error reconciling payment in base currency. 

### Module

accounts

### Version

Frappé 15.17.1
Erpnext 15.6.2

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions  {   "erpnext": "15.16.2",   "frappe": "15.17.1",   "helpdesk": "0.10.0",   "hrms": "15.12.0",   "lending": "0.0.1",   "print_designer": "1.0.0" } ``` ### Route ``` Form/Payment Reconciliation/Payment Reconciliation ``` ### Traceback ``` Traceback (most recent call last): File "apps/frappe/frappe/app.py", line 110, in application response = frappe.api.handle(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/api/__init__.py", line 49, in handle data = endpoint(**arguments) ^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call return frappe.handler.handle() ^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/handler.py", line 49, in handle data = execute_cmd(cmd) ^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/handler.py", line 85, in execute_cmd return frappe.call(method, **frappe.form_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/__init__.py", line 1716, in call return fn(*args, **newargs) ^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/handler.py", line 327, in run_doc_method response = doc.run_method(method) ^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/model/document.py", line 959, in run_method out = Document.hook(fn)(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/model/document.py", line 1319, in composer return composed(self, method, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/model/document.py", line 1301, in runner add_to_return_value(self, fn(self, *args, **kwargs)) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/model/document.py", line 956, in fn return method_object(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 536, in reconcile self.reconcile_allocations() File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 510, in reconcile_allocations reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions) File "apps/erpnext/erpnext/accounts/utils.py", line 511, in reconcile_against_document referenced_row = update_reference_in_payment_entry( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "apps/erpnext/erpnext/accounts/utils.py", line 717, in update_reference_in_payment_entry payment_entry.set_missing_ref_details(ref_exchange_rate=d.exchange_rate or None) TypeError: EmployeePaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'ref_exchange_rate' ``` ### Request Data ``` {   "type": "POST",   "args": {     "docs": "{\"name\":\"Payment Reconciliation\",\"minimum_invoice_amount\":0,\"minimum_payment_amount\":0,\"maximum_invoice_amount\":0,\"maximum_payment_amount\":0,\"invoice_limit\":50,\"payment_limit\":50,\"doctype\":\"Payment Reconciliation\",\"allocation\":[{\"docstatus\":0,\"idx\":1,\"reference_type\":\"Payment Entry\",\"reference_name\":\"ACC-PAY-2023-00215\",\"invoice_type\":\"Sales Invoice\",\"invoice_number\":\"03520\",\"allocated_amount\":18628.39,\"unreconciled_amount\":18628.39,\"amount\":18628.39,\"difference_amount\":0,\"difference_account\":\"6101-01-03-06 - DIFERENCIAL CAMBIARIO - PTK\",\"exchange_rate\":1,\"currency\":\"NIO\",\"parent\":\"Payment Reconciliation\",\"parentfield\":\"allocation\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Allocation\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-allocation-khiblzhwlp\"}],\"invoices\":[{\"docstatus\":0,\"idx\":1,\"invoice_type\":\"Sales Invoice\",\"invoice_number\":\"03520\",\"invoice_date\":\"2023-04-21\",\"amount\":18628.39,\"outstanding_amount\":18628.39,\"currency\":\"NIO\",\"exchange_rate\":0,\"parent\":\"Payment Reconciliation\",\"parentfield\":\"invoices\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Invoice\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-invoice-oarnzjjumn\"},{\"docstatus\":0,\"idx\":2,\"invoice_type\":\"Sales Invoice\",\"invoice_number\":\"04007\",\"invoice_date\":\"2023-12-12\",\"amount\":64151.6,\"outstanding_amount\":64151.6,\"currency\":\"NIO\",\"exchange_rate\":0,\"parent\":\"Payment Reconciliation\",\"parentfield\":\"invoices\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Invoice\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-invoice-kwntezlpys\"}],\"payments\":[{\"docstatus\":0,\"idx\":1,\"reference_type\":\"Journal Entry\",\"reference_name\":\"2023-00002\",\"posting_date\":\"2023-01-31\",\"is_advance\":\"No\",\"reference_row\":\"fa8199d215\",\"amount\":682140.32,\"difference_amount\":0,\"currency\":\"NIO\",\"exchange_rate\":1,\"cost_center\":\"Principal - PTK\",\"parent\":\"Payment Reconciliation\",\"parentfield\":\"payments\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Payment\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-payment-rvzeuuzcof\"},{\"docstatus\":0,\"idx\":2,\"reference_type\":\"Payment Entry\",\"reference_name\":\"ACC-PAY-2023-00215\",\"posting_date\":\"2023-04-21\",\"amount\":18628.39,\"difference_amount\":0,\"currency\":\"NIO\",\"exchange_rate\":1,\"parent\":\"Payment Reconciliation\",\"parentfield\":\"payments\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Payment\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-payment-smuscnszzi\"}],\"company\":\"PROTELCA\",\"party_type\":\"Customer\",\"party\":\"CLI-00068\",\"receivable_payable_account\":\"1103-01-02-06 - ENATREL - PTK\",\"__unsaved\":1,\"default_advance_account\":\"2104-01-01-56 - ANTICIPO DE CLIENTES - PTK\",\"docstatus\":0,\"idx\":0,\"from_invoice_date\":\"2023-04-01\"}",     "method": "reconcile"   },   "headers": {},   "error_handlers": {},   "url": "/api/method/run_doc_method",   "request_id": null } ``` ### Response Data ``` {   "exception": "TypeError: EmployeePaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'ref_exchange_rate'",   "exc_type": "TypeError",   "_exc_source": "erpnext (app)" } ```
```

**Comment by dj12djdjs** [comment]
@albertfns 
`set_missing_ref_details` got a new argument `ref_exchange_rate` in version 15.16.0

~Please try upgrading to version 15.16.0~
**Disregard, I see you are actually running 15.16.2**

**Comment by dj12djdjs** [comment]
This is caused by hrms not releasing to version-15
https://github.com/frappe/hrms/pull/1491
https://github.com/frappe/hrms/pull/1476

**Comment by albertfns** [comment]
Thank you. I will wait for the new release of Hrms to upgrade

**Comment by albertfns** [comment]
Thank you @dj12djdjs . I will wait for the new release of Hrms to upgrade
