### ISSUE TITLE
Error while saving sales invoice / purchase invoice for both Customer and Supplier

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#40399]
### Information about bug

There is a error when saving sales invoice which has advance payment recorded thru Sales order.  the details of the error are attached below

### Module

accounts

### Version

"erpnext": "15.16.1",
"frappe": "15.17.0",
"hrms": "15.12.0",
"india_compliance": "15.5.6",
"payments": "0.0.1"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### Route

Form/Payment Reconciliation/Payment Reconciliation
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 327, in run_doc_method
    response = doc.run_method(method)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 536, in reconcile
    self.reconcile_allocations()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 510, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions)
  File "apps/erpnext/erpnext/accounts/utils.py", line 511, in reconcile_against_document
    referenced_row = update_reference_in_payment_entry(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 717, in update_reference_in_payment_entry
    payment_entry.set_missing_ref_details(ref_exchange_rate=d.exchange_rate or None)
TypeError: EmployeePaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'ref_exchange_rate'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"Payment Reconciliation\",\"minimum_invoice_amount\":0,\"minimum_payment_amount\":0,\"maximum_invoice_amount\":0,\"maximum_payment_amount\":0,\"invoice_limit\":50,\"payment_limit\":50,\"doctype\":\"Payment Reconciliation\",\"invoices\":[{\"docstatus\":0,\"idx\":1,\"invoice_type\":\"Purchase Invoice\",\"invoice_number\":\"P02476\",\"invoice_date\":\"2024-02-19\",\"amount\":1723,\"outstanding_amount\":1723,\"currency\":\"INR\",\"exchange_rate\":0,\"parent\":\"Payment Reconciliation\",\"parentfield\":\"invoices\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Invoice\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-invoice-xqzjcekikz\"}],\"payments\":[{\"docstatus\":0,\"idx\":1,\"reference_type\":\"Payment Entry\",\"reference_name\":\"PMT04142\",\"posting_date\":\"2024-02-14\",\"reference_row\":\"09220fdf18\",\"amount\":1723,\"difference_amount\":0,\"currency\":\"INR\",\"exchange_rate\":1,\"parent\":\"Payment Reconciliation\",\"parentfield\":\"payments\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Payment\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-payment-vsvjxzgonr\"}],\"allocation\":[{\"docstatus\":0,\"idx\":1,\"reference_type\":\"Payment Entry\",\"reference_name\":\"PMT04142\",\"reference_row\":\"09220fdf18\",\"invoice_type\":\"Purchase Invoice\",\"invoice_number\":\"P02476\",\"allocated_amount\":1723,\"unreconciled_amount\":1723,\"amount\":1723,\"difference_amount\":0,\"difference_account\":\"Exchange Gain/Loss - SAPL\",\"exchange_rate\":1,\"currency\":\"INR\",\"parent\":\"Payment Reconciliation\",\"parentfield\":\"allocation\",\"parenttype\":\"Payment Reconciliation\",\"doctype\":\"Payment Reconciliation Allocation\",\"__islocal\":1,\"name\":\"new-payment-reconciliation-allocation-tocggmvbki\"}],\"company\":\"Sensoware Automation Private Limited\",\"party_type\":\"Supplier\",\"party\":\"Plastowell Polymers\",\"receivable_payable_account\":\"Creditors - SAPL\",\"__unsaved\":1,\"docstatus\":0,\"idx\":0}",
		"method": "reconcile"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": "75d82e63-8581-4282-96bf-ee8c112b6050"
}
```
### Response Data
```
{
	"exception": "TypeError: EmployeePaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'ref_exchange_rate'",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by deepeshgarg007** [comment]
@sapl-santhosh This should be fixed now
