### ISSUE TITLE
Contact & appointment booking is not possible for guest users

### ISSUE THREAD

**Issue by yoitcc** [frappe/erpnext#40423]
### Information about bug

using the standard/CRM `/book_appointment` route (and also `/contact`), it is not possible to send the contact form or book appointments if not logged in

in my understanding `/contact` and `/book_appointment` should be accessible and usable for guest users

`/book_appointment`:
![image](https://github.com/frappe/erpnext/assets/48800592/905c375d-0a27-4adb-9e38-11c17eefd610)
`/contact`:
![image](https://github.com/frappe/erpnext/assets/48800592/0c386cef-c3e4-474b-9e06-7de2a4a24398)

the attached log is from `/book_appointment` 

thank you for your time,
have a nice day,
oswald

### Module

CRM

### Version

/o/b/frappe-bench> bench version
erpnext 15.16.2
frappe 15.17.2
hrms 15.13.0
payments 0.0.1
webshop 0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

`/book_appointment`:
```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 106, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/www/book_appointment/index.py", line 114, in create_appointment
    appointment.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 306, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/appointment/appointment.py", line 75, in after_insert
    self.auto_assign()
  File "apps/erpnext/erpnext/crm/doctype/appointment/appointment.py", line 166, in auto_assign
    self.assign_agent(agent[0])
  File "apps/erpnext/erpnext/crm/doctype/appointment/appointment.py", line 225, in assign_agent
    add_assignment({"doctype": self.doctype, "name": self.name, "assign_to": [agent]})
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/assign_to.py", line 67, in add
    frappe.get_doc(args["doctype"], args["name"]).check_permission()
  File "apps/frappe/frappe/model/document.py", line 218, in check_permission
    self.raise_no_permission_to(permtype)
  File "apps/frappe/frappe/model/document.py", line 239, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError
```
`/contact`:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 106, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/templates/utils.py", line 46, in send_message
    opportunity.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 306, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 104, in after_insert
    link_open_events(self.opportunity_from, self.party_name, self)
  File "apps/erpnext/erpnext/crm/utils.py", line 131, in link_open_events
    event_doc.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 361, in _save
    self.check_permission("write", "save")
  File "apps/frappe/frappe/model/document.py", line 218, in check_permission
    self.raise_no_permission_to(permtype)
  File "apps/frappe/frappe/model/document.py", line 239, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError
```

**Comment by Nihantra-Patel** [comment]
Testes with Guest User.

Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.
