### ISSUE TITLE
AttributeError: 'int' object has no attribute 'items'

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#40614]
### Information about bug

Getting below error on deletion of invoices, downloading reports..etc

### App Versions
```
{
	"XXXX": "0.0.1",
	"erpnext": "14.65.5",
	"frappe": "14.68.1",
	"hrms": "14.24.0"
}
```
### Route
```
query-report/Warehouse wise Item Balance Age and Value - Custom
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1611, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/query_report.py", line 151, in background_enqueue_run
    return make_prepared_report(report_name, filters)
  File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 105, in make_prepared_report
    prepared_report = frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 277, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1278, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 41, in after_insert
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 104, in enqueue
    q = get_queue(queue, is_async=is_async)
  File "apps/frappe/frappe/utils/background_jobs.py", line 345, in get_queue
    validate_queue(qtype)
  File "apps/frappe/frappe/utils/background_jobs.py", line 351, in validate_queue
    default_queue_list = list(get_queues_timeout())
  File "apps/frappe/frappe/utils/background_jobs.py", line 52, in get_queues_timeout
    worker: config.get("timeout", default_timeout) for worker, config in custom_workers_config.items()
AttributeError: 'int' object has no attribute 'items'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"report_name": "Warehouse wise Item Balance Age and Value - Custom",
		"filters": "{\"from_date\":\"2024-02-22\",\"to_date\":\"2024-03-22\",\"warehouse\":\"AJMAN - DITD\",\"filter_total_zero_qty\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.background_enqueue_run"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'int' object has no attribute 'items'"
}
```

### Module

stock, buying, selling

### Version

ERPNext: v14.65.5 (HEAD)

Frappe Framework: v14.68.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Craftint** [comment]
Issue was because of "workers" : 0 configuration in common_site_config.json in frappe cloud bench.
We have removed the same and the issue is resolved.
