### ISSUE TITLE
Uncaught Server Exception - There was an error building this page

### ISSUE THREAD

**Issue by WavesSkipper** [frappe/erpnext#40693]
### Information about bug

Hello,

I run those comamd:
/frappe-bench/apps/erpnext$ git pull
/frappe-bench$ sudo bench --site [My site name] migrate

Then I can't login to the site and got this error, could you help me to solve that, it's urgent. Thanks

![image](https://github.com/frappe/erpnext/assets/153442964/94994f8c-83bd-4a87-8642-82114a217af7)

Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 27, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 167, in get
    frappe.get_attr(hook)(bootinfo=bootinfo)
    ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1673, in get_attr
    return getattr(get_module(modulename), methodname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'erpnext.startup.boot' has no attribute 'bootinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 162, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 224, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 29, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed

### Module

integrations

### Version

Frappe Framework: v15.2.1 
ERPNext: v15.3.0 

### Installation method

None

**Comment by WavesSkipper** [comment]
Hello,

It's solved accidentally, I installed a new site where I restarted supervisor and nginx, so the old sites begin working with the last release.

**Comment by WavesSkipper** [comment]
It's solved as described above
