### ISSUE TITLE
Purchase Return entry not posting against Purchase receipt (Rejected Material Return to Supplier)

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#40740]
### Information about bug

Purchase Return entry not posting against Purchase receipt (Rejected Material Return to Supplier) against same Purchase receipt, We have using Serial & Batch No functionality, system does not allow to return rejected partial material to supplier by same batch. Error is showing on all V15 sites

<img width="773" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/85a9fcb1-e857-4e0b-92a5-b6853e55272a">

### Module

accounts, stock, buying, manufacturing

### Version

ERPNext: v15.16.2
Frappe Framework: v15.17.1

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 357, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 289, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 230, in validate
    super(PurchaseReceipt, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 64, in validate
    self.set_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 566, in set_serial_and_batch_bundle
    frappe.get_doc("Serial and Batch Bundle", row.get(field)).set_serial_and_batch_values(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 388, in set_serial_and_batch_values
    self.validate_quantity(row, qty_field=qty_field)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 499, in validate_quantity
    self.throw_error_message(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 197, in throw_error_message
    frappe.throw(_(message), exception, title=_("Error"))
  File "apps/frappe/frappe/__init__.py", line 600, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 565, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 516, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Total quantity 200.0 in the Serial and Batch Bundle <strong>SABB-00000144</strong> does not match with the quantity 10.0 for the Item <strong>Batch Item</strong> in the Purchase Receipt # PR-24-00057

(anonymous) @ request.js:473
request.js:279 
        
        
       POST https://demo.mannlowe.com/api/method/frappe.desk.form.save.savedocs 417 (Expectation Failed)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
f @ save.js:246
n @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymous) @ form.js:820
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymous) @ form.js:750
save @ form.js:747
Save @ toolbar.js:687
(anonymous) @ page.js:305
dispatch @ jquery.js:5135
Rt.handle @ jquery.js:4939
Show 4 more frames
Show less
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 357, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 289, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 230, in validate
    super(PurchaseReceipt, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 64, in validate
    self.set_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 566, in set_serial_and_batch_bundle
    frappe.get_doc("Serial and Batch Bundle", row.get(field)).set_serial_and_batch_values(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 388, in set_serial_and_batch_values
    self.validate_quantity(row, qty_field=qty_field)
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 499, in validate_quantity
    self.throw_error_message(
  File "apps/erpnext/erpnext/stock/doctype/serial_and_batch_bundle/serial_and_batch_bundle.py", line 197, in throw_error_message
    frappe.throw(_(message), exception, title=_("Error"))
  File "apps/frappe/frappe/__init__.py", line 600, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 565, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 516, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Total quantity 200.0 in the Serial and Batch Bundle <strong>SABB-00000144</strong> does not match with the quantity 10.0 for the Item <strong>Batch Item</strong> in the Purchase Receipt # PR-24-00057
```

**Comment by khushi8112** [comment]
Couldn't replicate. This must be fixed in the recently pushed updates in the system.
Please reopen the issue if you're still facing the problem.
