### ISSUE TITLE
No attribute customer_query in version 15

### ISSUE THREAD

**Issue by maveeshah** [frappe/erpnext#40879]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/35832293/0dcf41d6-f648-433b-ac46-3ba553b53f4e)
Getting this error in both v15.19.1 (version-15-hotfix) and v15.19.1 (version-15)

### Module

selling

### Version

Frappe V15
Erpnext V15 and V15 hotfix

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473  Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 93, in search_widget
    is_whitelisted(frappe.get_attr(query))
  File "apps/frappe/frappe/__init__.py", line 1708, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.controllers.queries' has no attribute 'customer_query'
```

**Comment by maveeshah** [comment]
fixed by bench update --reset
