### ISSUE TITLE
Trend Report issue in loading the report

### ISSUE THREAD

**Issue by moaazmf** [frappe/erpnext#40998]
### Information about bug

when trying to open one of the "Trend" reports for example like "Sales Invoice Trends", "Sales Order Trends",  "Purchase Order Trends"...and the rest.
some times it will load fine, and some times it will give the below error.
take note I did not remove the fiscal year this is the first load for the report. you need to reload the page couple of times so it will load the page fully. 

Maybe the system is trying to load the report before building the fiscal year field filter

![image](https://github.com/frappe/erpnext/assets/29341232/d219ca17-bd03-4d45-859a-1cd16a89a91a)

here when it load fine:

![image](https://github.com/frappe/erpnext/assets/29341232/222b62e6-e158-4da1-912d-bb13fde323f9)

so it seam the system is trying to load the report before building the fiscal year filter

### Module

other

### Version

Email Delivery Service: v0.0.1 (HEAD)

ERPNext: v15.18.3 (HEAD)

Frappe Framework: v15.20.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 878, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 219, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 878, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 81, in generate_report_result
    res = get_report_result(report, filters) or []
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_script_report(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 162, in execute_script_report
    res = self.execute_module(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 179, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Fiscal Year is mandatory

**Comment by donnieferdian** [comment]
Same Problem,

```
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/desk/query_report.py", line 220, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
      report_name = 'Sales Invoice Trends'
      filters = '{}'
      user = 'admin@example.com'
      ignore_prepared_report = 'false'
      custom_columns = None
      is_tree = False
      parent_field = None
      are_default_filters = 'true'
      report = <Report: Sales Invoice Trends>
      result = None
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
      args = (<Report: Sales Invoice Trends>, '{}', 'admin@example.com', None, False, None)
      kwargs = {}
      switched_connection = False
      fn = <function generate_report_result at 0x7fa6f53437e0>
  File "apps/frappe/frappe/desk/query_report.py", line 81, in generate_report_result
    res = get_report_result(report, filters) or []
      report = <Report: Sales Invoice Trends>
      filters = {}
      user = 'admin@example.com'
      custom_columns = None
      is_tree = False
      parent_field = None
  File "apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_script_report(filters)
      report = <Report: Sales Invoice Trends>
      filters = {}
      res = None
  File "apps/frappe/frappe/core/doctype/report/report.py", line 162, in execute_script_report
    res = self.execute_module(filters)
      self = <Report: Sales Invoice Trends>
      filters = {}
      threshold = 15
      res = []
      start_time = datetime.datetime(2024, 5, 6, 17, 49, 27, 97106)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 179, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
      self = <Report: Sales Invoice Trends>
      filters = {}
      module = 'Accounts'
      method_name = 'erpnext.accounts.report.sales_invoice_trends.sales_invoice_trends.execute'
  File "apps/erpnext/erpnext/accounts/report/sales_invoice_trends/sales_invoice_trends.py", line 12, in execute
    conditions = get_columns(filters, "Sales Invoice")
      filters = {}
      data = []
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
      filters = {}
      trans = 'Sales Invoice'
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
      filters = {}
      f = 'Fiscal Year'
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
      msg = 'Fiscal Year is mandatory'
      exc = <class 'frappe.exceptions.ValidationError'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
      msg = 'Fiscal Year is mandatory'
      title = None
      raise_exception = <class 'frappe.exceptions.ValidationError'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7fa6f5102f20>
      inspect = <module 'inspect' from '/usr/lib/python3.11/inspect.py'>
      out = {'message': 'Fiscal Year is mandatory', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '939991e034644daf5a2677ea11fae756420567d49c2ee2f0607c146b'}
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
      exc = ValidationError('Fiscal Year is mandatory')
      inspect = <module 'inspect' from '/usr/lib/python3.11/inspect.py'>
      msg = 'Fiscal Year is mandatory'
      out = {'message': 'Fiscal Year is mandatory', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '939991e034644daf5a2677ea11fae756420567d49c2ee2f0607c146b'}
      raise_exception = <class 'frappe.exceptions.ValidationError'>
frappe.exceptions.ValidationError: Fiscal Year is mandatory
```

@deepeshgarg007   @ruthra-kumar

**Comment by oguzbilgic** [comment]
Feedback: Not able to view "Sales Order Trend" report. Even after setting FY in session defaults.

**Comment by Sunil-Codes** [comment]
Same issue facing not able to load any trend report this issue is with every trend report

**Comment by Nihantra-Patel** [comment]
Issue has been fixed: https://github.com/frappe/erpnext/pull/41544

Upcoming update will resolve your issue.

**Comment by pro-nature** [comment]
This issue continues even after last update to ERPNEXT 15.25

**Comment by Nihantra-Patel** [comment]
Tested, worked properly.


https://github.com/frappe/erpnext/assets/141945075/d9a9cc15-b9d8-4a91-84f8-0b8ae18df166

**Comment by pro-nature** [comment]
Yes. Bench Build fixed the issue. Thanks
