### ISSUE TITLE
The customer name field disappear

### ISSUE THREAD

**Issue by manalErpnext** [frappe/erpnext#41002]
### Information about bug

i hope when i change the naming the doctype still work very well

### Module

selling

### Version

ERPNext: v15.20.3 (version-15)
Frappe Framework: v15.22.0 (version-15)
Frappe HR: v15.17.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
The field "customer name" disappears from the screen. When I change another field and save, I get an error message.
`
Message
Customer with the same name already exists. Please choose a different name`

request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_before_save_methods
    self.run_method("before_validate")
  File "apps/frappe/frappe/model/document.py", line 966, in run_method
    run_server_script_for_doc_event(self, method)
  File "apps/frappe/frappe/core/doctype/server_script/server_script_utils.py", line 42, in run_server_script_for_doc_event
    frappe.get_doc("Server Script", script_name).execute_doc(doc)
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 169, in execute_doc
    safe_exec(
  File "apps/frappe/frappe/utils/safe_exec.py", line 100, in safe_exec
    exec(
  File "<serverscript>: customer_name_validation", line 3, in <module>
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Customer with the same name already exists. Please choose a different name.
```
```

**Comment by Nihantra-Patel** [comment]
If you choose Customer Naming By Customer Name in the selling system and then create a customer, it checks if the customer is already in the list. If the customer is already listed, it will display "Customer with the same name already exists." Therefore, you must first decide whether to prioritize naming by customer name or naming series. Sometimes, users or clients may change settings, leading to such issues, but this is a default validation.

https://github.com/frappe/erpnext/blob/e706b4534c7d7d9e91e57b33346edc9a252fcef7/erpnext/selling/doctype/customer/customer.py#L99-L106
