### ISSUE TITLE
Delivery Trip Gets Stops From Button

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#41184]
### Information about bug

When using the Gets Stops From Button, a server script appears.

Server Error
TypeError: make_delivery_trip() takes from 1 to 2 positional arguments but 3 were given

### Module

stock

### Version

ERPNext: v14.67.2 (HEAD)
Frappe Framework: v14.72.0 (HEAD)
Frappe HR: v14.26.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
`### App Versions

{
	"erpnext": "14.67.2",
	"frappe": "14.72.0",
	"hrms": "14.26.0"
}
```
### Route
```
Form/Delivery Trip/new-delivery-trip-kzpcsatiat
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1611, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/mapper.py", line 53, in map_docs
    target_doc = method(*_args)
TypeError: make_delivery_trip() takes from 1 to 2 positional arguments but 3 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.stock.doctype.delivery_note.delivery_note.make_delivery_trip",
		"source_names": "[\"MAT-DN-2024-00001\",\"MAT-DN-2024-00002\",\"MAT-DN-2024-00003\",\"MAT-DN-2024-00004\",\"MAT-DN-2024-00006\"]",
		"target_doc": "{\"docstatus\":0,\"doctype\":\"Delivery Trip\",\"name\":\"new-delivery-trip-kzpcsatiat\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-DT-.YYYY.-\",\"company\":\"Malaya Corporation\",\"email_notification_sent\":0,\"status\":\"Draft\",\"delivery_stops\":[{\"docstatus\":0,\"doctype\":\"Delivery Stop\",\"name\":\"new-delivery-stop-hqvwippxkt\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"locked\":0,\"visited\":0,\"parent\":\"new-delivery-trip-kzpcsatiat\",\"parentfield\":\"delivery_stops\",\"parenttype\":\"Delivery Trip\",\"idx\":1}]}",
		"args": "{\"company\":\"Malaya Corporation\",\"merge_taxes\":0,\"filtered_children\":[]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.map_docs"
}
```
### Response Data
```
{
	"exception": "TypeError: make_delivery_trip() takes from 1 to 2 positional arguments but 3 were given"
}
````
```

**Comment by Ponyooooo** [comment]
is the bug fix not included for the version14?
