### ISSUE TITLE
New Version Error Choose Supplier on Purchase Order

### ISSUE THREAD

**Issue by xhijack** [frappe/erpnext#41276]
![Screenshot 2024-04-30 at 23 46 09](https://github.com/frappe/erpnext/assets/1784964/8d62f64f-0019-48e2-89ae-9300a6baadf7)

### Information about bug

I updated the new version and I got this. Also, I reinstall the site. It's still getting this issued

### Module

buying

### App Versions
```
{
	"erpnext": "15.21.2",
	"frappe": "15.25.0"
}
```
### Route
```
Form/Purchase Order/new-purchase-order-xqzrzkslxh
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1761, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 93, in search_widget
    is_whitelisted(frappe.get_attr(query))
  File "apps/frappe/frappe/__init__.py", line 1751, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.controllers.queries' has no attribute 'supplier_query'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Supplier",
		"ignore_user_permissions": 0,
		"reference_doctype": "Purchase Order",
		"page_length": 10,
		"query": "erpnext.controllers.queries.supplier_query"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: module 'erpnext.controllers.queries' has no attribute 'supplier_query'",
	"exc_type": "AttributeError"
}
```

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @xhijack,

Please migrate the site and build the app. (`bench build --force`).

Kindly upgrade to version 15, Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/4acb36bd-b8dc-4d36-84db-3581adca1d1b
