### ISSUE TITLE
Error on Bank Statement Import

### ISSUE THREAD

**Issue by innomalous** [frappe/erpnext#41289]
### Information about bug

Getting error while creating new Bank Statement Import
"FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/data_import_tools.bundle.3E3NNDZO.js'"

### Module

accounts

### Version

"erpnext": "14.67.2",
	"frappe": "14.72.0",
	"hrms": "14.26.0",
	"india_compliance": "14.26.3",
	"payments": "0.0.1"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.67.2",
	"frappe": "14.72.0",
	"hrms": "14.26.0",
	"india_compliance": "14.26.3",
	"payments": "0.0.1"
}
```
### Route
```
Form/Bank Statement Import/Bank Statement Import on 2024-05-02 12:12:12.872566
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 351, in get_js
    with open(contentpath) as srcfile:
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/data_import_tools.bundle.3E3NNDZO.js'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"items": "[\"/assets/frappe/dist/js/data_import_tools.bundle.3E3NNDZO.js\"]"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.get_js"
}
```
### Response Data
```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/data_import_tools.bundle.3E3NNDZO.js'"
}
```
```

**Comment by nabinhait** [comment]
Can't replicate
