### ISSUE TITLE
Unreadable bug while importing data

### ISSUE THREAD

**Issue by akhtarmohsin** [frappe/erpnext#41701]
Error message when importing data through XLSX

![Screenshot 2024-05-30 at 11 14 08 AM](https://github.com/frappe/frappe/assets/167299936/f50e3f85-9192-4990-9c67-95dcf9d8cd12)

## Description of the issue

Only for Frappe team, this is the data import record, where you can access the file as well.

https://mohsin.frappe.cloud/app/data-import/Quotation%20Import%20on%202024-05-30%2011%3A13%3A33.270896

### Stacktrace / full error message

```
### App Versions
```
{
	"erpnext": "15.23.0",
	"frappe": "15.26.0",
	"hrms": "15.20.3",
	"india_compliance": "15.7.4"
}
```
### Route
```
Form/Data Import/Quotation Import on 2024-05-30 11:13:33.270896
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 56, in validate
    self.set_payload_count()
  File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 75, in set_payload_count
    payloads = i.import_file.get_payloads_for_import()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 519, in get_payloads_for_import
    doc, rows, data = self.parse_next_row_for_import(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 555, in parse_next_row_for_import
    parent_doc = row.parse_doc(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 652, in parse_doc
    return self._parse_doc(doctype, columns, values, parent_doc, table_df)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 675, in _parse_doc
    value = self.validate_value(value, col)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 730, in validate_value
    value = self.get_date(value, col)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 793, in get_date
    return datetime.strptime(value, date_format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not int

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Quotation Import on 2024-05-30 11:13:33.270896\",\"owner\":\"mohsin@frappe.io\",\"creation\":\"2024-05-30 11:13:33.270896\",\"modified\":\"2024-05-30 11:13:33.270896\",\"modified_by\":\"mohsin@frappe.io\",\"docstatus\":0,\"idx\":0,\"reference_doctype\":\"Quotation\",\"import_type\":\"Insert New Records\",\"import_file\":\"/private/files/Quotation-duo.xlsx\",\"payload_count\":0,\"google_sheets_url\":null,\"status\":\"Pending\",\"submit_after_import\":0,\"mute_emails\":1,\"template_options\":\"\",\"template_warnings\":\"\",\"show_failed_logs\":0,\"doctype\":\"Data Import\",\"__last_sync_on\":\"2024-05-30T05:43:32.641Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "69f42fba-8ca8-4cb9-aed4-721a4f177bee"
}
```
### Response Data
```
{
	"exception": "TypeError: strptime() argument 1 must be str, not int",
	"exc_type": "TypeError"
}
```
```

**Comment by akhtarmohsin** [comment]
[Quotation-duo.xlsx](https://github.com/frappe/frappe/files/15494264/Quotation-duo.xlsx)

**Comment by Nihantra-Patel** [comment]
It worked properly. The issue is with the date format. I used the same field to update the data and import the quotation, and the quotation imported successfully. Please check it.

[Quotation-duo.xlsx](https://github.com/user-attachments/files/15509079/Quotation-duo.xlsx)

<img width="1440" alt="Screenshot 2024-05-31 at 11 42 19 AM" src="https://github.com/frappe/erpnext/assets/141945075/810008b8-8881-43dc-b458-c314fbe7f8e7">

**Output:**


![image](https://github.com/frappe/erpnext/assets/141945075/795cf96b-2ea2-4a56-83af-7ea78b74ff29)
