### ISSUE TITLE
Problem upgrading to latest version with bench update

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4176]
Hi, I've just tried to do a bench update on my erpnext installation and this error message popped up 

frappe@debian-erp:~/frappe-bench$ bench update
Already up-to-date.
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
Database backed up /home/frappe/frappe-bench/sites/erp.domain.gr/private/backups/20151014_90838860_database.sql.gz
Migrating erp.domain.gr

Executing execute:frappe.reload_doc('core', 'doctype', 'docfield', force=True) #2015-10-15 in erp.domain.gr (05dc55a2c4)
Success

Executing execute:frappe.reload_doc('core', 'doctype', 'custom_field') #2015-10-15 in erp.domain.gr (05dc55a2c4)
/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/custom_field/custom_field.json missing
Success

Executing frappe.patches.v6_4.reduce_varchar_length in erp.domain.gr (05dc55a2c4)
setting length of 'depends_on' in 'DocField' as 148
setting length of 'patch' in 'Patch Log' as 187
Success

Executing erpnext.patches.v6_4.fix_duplicate_bins in erp.domain.gr (05dc55a2c4)
Success

Executing erpnext.patches.v6_4.fix_sales_order_maintenance_status in erp.domain.gr (05dc55a2c4)
Success

Executing erpnext.patches.v6_4.email_digest_update in erp.domain.gr (05dc55a2c4)
Success

Executing execute:frappe.delete_doc_if_exists("DocType", "Applicable Territory") in erp.domain.gr (05dc55a2c4)
Success

Executing execute:frappe.delete_doc_if_exists("DocType", "Shopping Cart Price List") in erp.domain.gr (05dc55a2c4)
Success

Executing execute:frappe.delete_doc_if_exists("DocType", "Shopping Cart Taxes and Charges Master") in erp.domain.gr (05dc55a2c4)
Success

Executing erpnext.patches.v6_4.set_user_in_contact in erp.domain.gr (05dc55a2c4)
Success

Executing erpnext.patches.v6_4.make_image_thumbnail in erp.domain.gr (05dc55a2c4)
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Unable to make thumbnail for attach_files:
Success
Updating frappe                     : [========================================]
Updating erpnext                    : [==================================      ]Traceback (most recent call last):

  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals

  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 216, in migrate
    frappe.model.sync.sync_all(verbose=context.verbose)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 19, in sync_all
    sync_for(app, force, verbose=verbose)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 43, in sync_for
    import_file_by_path(doc_path, force=force)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import, pre_process=pre_process)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 122, in import_doc
    doc.insert()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 193, in insert
    self._validate()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 346, in _validate
    d._validate_length()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 465, in _validate_length
    .format(reference, _(df.label), max_length), frappe.CharacterLengthExceededError)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 257, in throw
    msgprint(msg, raise_exception=exc)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 250, in msgprint
    _raise_exception()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 235, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.CharacterLengthExceededError: DocField, Row 10: 'Depends On' will get truncated, as max characters allowed is 140
Traceback (most recent call last):

  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.92', 'console_scripts', 'bench')()

  File "/home/frappe/bench-repo/bench/cli.py", line 60, in cli
    bench()

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)

  File "/home/frappe/bench-repo/bench/cli.py", line 240, in _update
    update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, 
force=force)

  File "/home/frappe/bench-repo/bench/cli.py", line 270, in update
    patch_sites(bench=bench_path)

  File "/home/frappe/bench-repo/bench/utils.py", line 158, in patch_sites
    run_frappe_cmd('--site', 'all', 'migrate', bench=bench)

  File "/home/frappe/bench-repo/bench/utils.py", line 489, in run_frappe_cmd
    raise CommandFailedError(args)
bench.utils.CommandFailedError: ('--site', 'all', 'migrate')

Any ideas how i can fix the installation?

**Comment by gabtzi** [comment]
Update:

Seems the value that needs to be truncated is located in apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.json line 231

` "depends_on": "eval:in_list([\"Material Issue\", \"Material Transfer\", \"Manufacture\", \"Repack\", \t\t\t\t\t\"Subcontract\", \"Material Transfer for Manufacture\"], doc.purpose)", `

and related to the commit ee6862b277cb10eb984f491701dd66202e035a23

**Comment by system19** [comment]
I have the same issue here as well.
frappe.exceptions.CharacterLengthExceededError: DocField, Row 10: 'Depends On' will get truncated, as max characters allowed is 140

**Comment by rmehta** [comment]
@gabtzi @system19 We will make "depends_on" as a small text field and push in a bit. Thanks for reporting.

**Comment by rmehta** [comment]
Just pushed a fix to develop. Can you check @gabtzi @system19

**Comment by gabtzi** [comment]
Thank you very much the update worked perfectly on my end

**Comment by system19** [comment]
All good here too. You can close the issue. Thanking you.
