### ISSUE TITLE
Error showing incorrect - For Zero Stocks

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#41770]
### Information about bug

We have made one material Request from one warehouse to another someone else is trying to transfer the material against that material request (The item Is not available in the source warehouse ) 

Getting below error 

valuation rate error

https://github.com/frappe/erpnext/assets/21578167/9eca43d1-a4e8-4f3a-94a2-3994b0fefcac

### Module

stock

### Version

<img width="1195" alt="Screenshot 2024-06-04 at 1 33 53 PM" src="https://github.com/frappe/erpnext/assets/21578167/50670e00-7efe-4d69-a0c7-a75dbea112ac">

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"addon_s_stocks": "0.0.1",
	"addons_boms": "0.0.1",
	"addons_buying": "0.0.1",
	"bliss_employee": "0.0.1",
	"erpnext": "15.26.1",
	"frappe": "15.29.0",
	"hr_reports": "0.0.1",
	"hrms": "15.22.0",
	"india_compliance": "15.7.5",
	"qrcode_generator": "0.0.1",
	"reports": "0.0.1"
}
```
### Route
```
Form/Stock Entry/STE/2406/00457
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 243, in on_submit
    self.update_stock_ledger()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1350, in update_stock_ledger
    self.make_sl_entries(sl_entries)
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 855, in make_sl_entries
    make_sl_entries(sl_entries, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 95, in make_sl_entries
    sle_doc = make_entry(sle, allow_negative_stock, via_landed_cost_voucher)
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 224, in make_entry
    sle.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 315, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py", line 184, in on_submit
    SerialBatchBundle(
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 23, in __init__
    self.process_serial_and_batch_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 33, in process_serial_and_batch_bundle
    self.process_batch_no()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 224, in process_batch_no
    self.make_serial_batch_no_bundle()
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 116, in make_serial_batch_no_bundle
    self.set_serial_and_batch_bundle(sn_doc)
  File "apps/erpnext/erpnext/stock/serial_batch_bundle.py", line 194, in set_serial_and_batch_bundle
    frappe.db.set_value(self.child_doctype, self.sle.voucher_detail_no, values_to_update)
  File "apps/frappe/frappe/database/database.py", line 994, in set_value
    query.run(debug=debug)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'valuation_rate' cannot be null")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"STE/2406/00457\",\"owner\":\"Administrator\",\"creation\":\"2024-06-04 13:30:05.688631\",\"modified\":\"2024-06-04 13:30:05.688631\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"workflow_state\":null,\"naming_series\":\"STE/.YY.MM./.#####\",\"stock_entry_type\":\"Material Transfer\",\"outgoing_stock_entry\":null,\"purpose\":\"Material Transfer\",\"add_to_transit\":0,\"is_fg_transfer\":0,\"work_order\":null,\"purchase_order\":null,\"subcontracting_order\":null,\"delivery_note_no\":null,\"sales_invoice_no\":null,\"pick_list\":null,\"purchase_receipt_no\":null,\"company\":\"Blisstering Electronics Private Limited\",\"posting_date\":\"2024-06-04\",\"posting_time\":\"13:30:05.707706\",\"set_posting_time\":0,\"inspection_required\":0,\"apply_putaway_rule\":0,\"from_bom\":0,\"use_multi_level_bom\":1,\"bom_no\":null,\"fg_completed_qty\":0,\"process_loss_percentage\":0,\"process_loss_qty\":0,\"from_warehouse\":\"MI OQC 24-25 - BEPL\",\"source_warehouse_address\":null,\"source_address_display\":null,\"to_warehouse\":\"Finished Goods - BEPL\",\"target_warehouse_address\":null,\"target_address_display\":null,\"scan_barcode\":null,\"total_outgoing_value\":116999.7883902,\"total_incoming_value\":116999.7883902,\"value_difference\":0,\"total_additional_costs\":0,\"supplier\":null,\"supplier_name\":null,\"supplier_address\":null,\"address_display\":null,\"project\":null,\"select_print_heading\":null,\"letter_head\":null,\"is_opening\":\"No\",\"remarks\":null,\"per_transferred\":0,\"total_amount\":116999.7883902,\"job_card\":null,\"amended_from\":null,\"credit_note\":null,\"is_return\":0,\"doctype\":\"Stock Entry\",\"items\":[{\"name\":\"7nppo7nsm2\",\"owner\":\"Administrator\",\"creation\":\"2024-06-04 13:30:05.688631\",\"modified\":\"2024-06-04 13:30:05.688631\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"s_warehouse\":\"MI OQC 24-25 - BEPL\",\"t_warehouse\":\"Finished Goods - BEPL\",\"item_code\":\"AM4085600GF\",\"item_name\":\"FIGHTERPROLD15/220-240/350 CS MAXIC INOSRAM\",\"is_finished_item\":0,\"is_scrap_item\":0,\"quality_inspection\":null,\"subcontracted_item\":null,\"description\":\"FIGHTERPROLD15/220-240/350 CS MAXIC INOSRAM\",\"item_group\":\"CC Driver\",\"image\":null,\"qty\":1720,\"transfer_qty\":1720,\"retain_sample\":0,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":68.023132785,\"additional_cost\":0,\"valuation_rate\":68.023132785,\"allow_zero_valuation_rate\":0,\"set_basic_rate_manually\":0,\"basic_amount\":116999.7883902,\"amount\":116999.7883902,\"use_serial_batch_fields\":0,\"serial_and_batch_bundle\":null,\"serial_no\":null,\"batch_no\":null,\"expense_account\":\"5111 - Cost of Goods Sold - BEPL\",\"cost_center\":\"Main - BEPL\",\"project\":null,\"actual_qty\":0,\"transferred_qty\":0,\"bom_no\":null,\"allow_alternative_item\":0,\"material_request\":\"MAT-MR-2024-01461\",\"material_request_item\":\"t2chmndkrk\",\"original_item\":null,\"against_stock_entry\":null,\"ste_detail\":null,\"po_detail\":null,\"sco_rm_detail\":null,\"putaway_rule\":null,\"reference_purchase_receipt\":null,\"job_card_item\":null,\"parent\":\"STE/2406/00457\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"doctype\":\"Stock Entry Detail\",\"__unsaved\":1}],\"additional_costs\":[],\"__last_sync_on\":\"2024-06-04T08:00:05.697Z\",\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370050036404590031051": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 3519,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.IntegrityError: (1048, \"Column 'valuation_rate' cannot be null\")",
	"exc_type": "IntegrityError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/1ec6c060-6260-4855-8339-8923eca2fb2e

**Comment by Nihantra-Patel** [comment]
And Item have a Zero stock then check it.


https://github.com/frappe/erpnext/assets/141945075/4da85315-efdf-4c4b-bdca-c1f269035b6a

**Comment by dineshpanchal93** [comment]
Its already on Version 15 with latest updates

Last week i was not able to face this issue. After and recently updated then got an error
