### ISSUE TITLE
Payment reference in Journal entry

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#41794]
### Information about bug

While doing payment reconciliation with foreign currencies the system is throwing followiing error,

Row #2: Reference Type cannot be "Payment Entry". It should be one of "", "Sales Invoice", "Purchase Invoice", "Journal Entry", "Sales Order", "Purchase Order", "Expense Claim", "Asset", "Loan", "Payroll Entry", "Employee Advance", "Exchange Rate Revaluation", "Invoice Discounting", "Fees", "Full and Final Statement", "Petty Cash"

![image](https://github.com/frappe/erpnext/assets/112148467/7f58ee93-21e1-4694-8f58-f769db1388ba)

### Module

accounts

### Version

ERPNext: v14.70.2 (HEAD)

Frappe Framework: v14.75.0 (HEAD)

gte: v1.1.12 (HEAD)

Frappe HR: v14.28.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 312, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 467, in reconcile
    self.reconcile_allocations()
  File "apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py", line 441, in reconcile_allocations
    reconcile_against_document(entry_list, skip_ref_details_update_for_pe, self.dimensions)
  File "apps/erpnext/erpnext/accounts/utils.py", line 473, in reconcile_against_document
    referenced_row = update_reference_in_payment_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 691, in update_reference_in_payment_entry
    payment_entry.make_exchange_gain_loss_journal(
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1306, in make_exchange_gain_loss_journal
    je = create_gain_loss_journal(
  File "apps/erpnext/erpnext/accounts/utils.py", line 2045, in create_gain_loss_journal
    journal_entry.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 332, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 266, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 558, in _validate
    d._validate_selects()
  File "apps/frappe/frappe/model/base_document.py", line 849, in _validate_selects
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 548, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 509, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 455, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #2: Reference Type cannot be "Payment Entry". It should be one of "", "Sales Invoice", "Purchase Invoice", "Journal Entry", "Sales Order", "Purchase Order", "Expense Claim", "Asset", "Loan", "Payroll Entry", "Employee Advance", "Exchange Rate Revaluation", "Invoice Discounting", "Fees", "Full and Final Statement", "Petty Cash"
2 request.js:457:14
```

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 14.


https://github.com/frappe/erpnext/assets/141945075/d623cefe-dfd5-43b9-8934-09a9fdc7228a

**Comment by maveezmh** [comment]
@Nihantra-Patel its not happening. the entries above is working because there is no change in exchange rate during payment entry.

**Comment by Nihantra-Patel** [comment]
Can you share the video? for the better understanding.

**Comment by maveezmh** [comment]
@Nihantra-Patel you can refer to below recording

https://github.com/frappe/erpnext/assets/112148467/b7266b11-8e48-496c-b14f-01702e646d2e

**Comment by Nihantra-Patel** [comment]
Option of Payment Entry is available, and I think you have done some customization. Because there is a message even in the pop pop of reconciliation.

Please check the json of Journal Entry Account table
https://github.com/frappe/erpnext/blob/b6648eebfaf348e62e16806c91d0bde6f9390a1f/erpnext/accounts/doctype/journal_entry_account/journal_entry_account.json#L185-L185

https://github.com/frappe/erpnext/assets/141945075/e5cbac25-2915-4062-91a5-ef23dad70f62

**Comment by maveezmh** [comment]
@Nihantra-Patel Thanks for your feedback Will chack with the developer if one of the app is creating issue
