### ISSUE TITLE
Finishing Work Order, Error: Data missing in table: None, MandatoryError

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#41800]
### Information about bug

See tests reproducing the issue: https://github.com/frappe/erpnext/pull/41814

It is possible for the Stock Entry `create_serial_and_batch_bundle` to be called with no serial number and empty `row.batches_to_be_consume` thus resulting in an unpopulated Serial and Batch Bundle, causing `frappe.exceptions.MandatoryError: [Serial and Batch Bundle, SABB-00001343]: entries`

https://github.com/frappe/erpnext/blob/c76f466528e2e6651df5d72e14f9418b8d5bec65/erpnext/stock/doctype/stock_entry/stock_entry.py#L3156

EDIT:
It appears to be caused by the check for negative quantity (which all Outward SABBs are) which prevents the `batches_to_be_consume` being updated:

https://github.com/frappe/erpnext/blob/c76f466528e2e6651df5d72e14f9418b8d5bec65/erpnext/stock/doctype/stock_entry/stock_entry.py#L2192-L2198

![Screen Shot 2024-06-05 at 14 34 34](https://github.com/frappe/erpnext/assets/110036763/93bbc8e9-4c20-4cd6-84c7-d5b45804cb56)

### Module

stock, manufacturing

### Version

ERPNext: v15.22.2

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1393, in make_stock_entry
    stock_entry.get_items()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1751, in get_items
    self.add_transfered_raw_materials_in_items()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2170, in add_transfered_raw_materials_in_items
    self.update_item_in_stock_entry_detail(row, item, qty)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2209, in update_item_in_stock_entry_detail
    "serial_and_batch_bundle": create_serial_and_batch_bundle(self, row, item, "Outward")
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 3186, in create_serial_and_batch_bundle
    return doc.insert(ignore_permissions=True).name
  File "apps/frappe/frappe/model/document.py", line 292, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 574, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [Serial and Batch Bundle, SABB-00001343]: entries
```

**Comment by Nihantra-Patel** [comment]
Same issue: https://github.com/frappe/erpnext/issues/41859#issue-2346267393

https://github.com/frappe/erpnext/assets/21578167/cc806811-8dd9-4f28-b1db-42f42d213155

**Comment by casesolved-co-uk** [comment]
@rohitwaghchaure Looks like this was caused by https://github.com/frappe/erpnext/pull/34564 and untested. Now a blocking issue for an ERPNext customer.

**Comment by casesolved-co-uk** [comment]
@rohitwaghchaure These tests reproduce the issue and have been ignored and closed: https://github.com/frappe/erpnext/pull/41814

**Comment by casesolved-co-uk** [comment]
@nabinhait Please can you get @rohitwaghchaure to look at this?

**Comment by casesolved-co-uk** [comment]
@toofun666 Can you confirm you have seen this?
