### ISSUE TITLE
Work Order - Closed - Error in Return Components

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#41859]
### Information about bug

https://github.com/frappe/erpnext/assets/21578167/cc806811-8dd9-4f28-b1db-42f42d213155

### Module

manufacturing

### Version

Version - 15 Latest All

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1705, in make_stock_return_entry
    stock_entry.add_transfered_raw_materials_in_items()
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2167, in add_transfered_raw_materials_in_items
    self.update_item_in_stock_entry_detail(row, item, qty)
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 2206, in update_item_in_stock_entry_detail
    "serial_and_batch_bundle": create_serial_and_batch_bundle(self, row, item, "Outward")
  File "apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 3183, in create_serial_and_batch_bundle
    return doc.insert(ignore_permissions=True).name
  File "apps/frappe/frappe/model/document.py", line 292, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 574, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [Serial and Batch Bundle, SABB-00115080]: entries
```

**Comment by Nihantra-Patel** [comment]
Duplicate issue: https://github.com/frappe/erpnext/issues/41800
