### ISSUE TITLE
Restore asset issue in Asset

### ISSUE THREAD

**Issue by Nandhini8848** [frappe/erpnext#42038]
### Information about bug

While clicking 'Restore Asset' in Asset, an error is displayed.
![Screenshot from 2024-06-26 13-30-38](https://github.com/frappe/erpnext/assets/166362542/da5319e3-d6ba-4248-8952-49f1ecaae5d8)
[Screencast from 26-06-24 01:38:59 PM IST.webm](https://github.com/frappe/erpnext/assets/166362542/f203df55-67f9-474f-adb1-7fee5aedb66e)

### Module

assets

### Version

erpnext 15.27.6
frappe 15.28.0
hrms 15.0.0
india_compliance 15.7.5

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"cleartax": "0.0.1",
	"cleartax_integration": "0.0.1",
	"erpnext": "15.27.6",
	"frappe": "15.28.0",
	"hrms": "15.0.0",
	"india_compliance": "15.7.5",
	"om_logistics": "0.0.1"
}
```
### Route
```
Form/Asset/ACC-ASS-2024-00120
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 487, in restore_asset
    reset_depreciation_schedule(asset, asset.disposal_date, notes)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 528, in reset_depreciation_schedule
    modify_depreciation_schedule_for_asset_repairs(asset_doc, notes)
  File "apps/erpnext/erpnext/assets/doctype/asset/depreciation.py", line 541, in modify_depreciation_schedule_for_asset_repairs
    asset_repair.modify_depreciation_schedule()
  File "apps/erpnext/erpnext/assets/doctype/asset_repair/asset_repair.py", line 368, in modify_depreciation_schedule
    for row in self.asset_doc.finance_books:
AttributeError: 'AssetRepair' object has no attribute 'asset_doc'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"asset_name": "ACC-ASS-2024-00120"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.assets.doctype.asset.depreciation.restore_asset",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'AssetRepair' object has no attribute 'asset_doc'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by khushi8112** [comment]
https://github.com/frappe/erpnext/pull/50982
