### ISSUE TITLE
Payment Entry: Allocated Amount cannot be greater than outstanding amount

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#42062]
### Information about bug

Payment entry shows pop up message for Allocated Amount cannot be greater than outstanding amount when creating payments for expense claim. Not yet tested if the pop up message also shows up for purchase order and purchase invoice.

<img width="951" alt="image" src="https://github.com/frappe/erpnext/assets/60758795/a74d1c7c-ef47-426d-8faa-04b70e1f528f">

### Module

accounts

### Version

ERPNext: v14.70.7 (HEAD)
Frappe Framework: v14.77.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/workflow.py", line 131, in apply_workflow
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 345, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1061, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 89, in validate
    self.validate_allocated_amount()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 173, in validate_allocated_amount
    frappe.throw(fail_message.format(d.idx))
  File "apps/frappe/frappe/__init__.py", line 548, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 509, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 455, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Row #1: Allocated Amount cannot be greater than outstanding amount.
```

**Comment by Ponyooooo** [comment]
this is a bug from the recent version update. We do not usually experience this one.

**Comment by quebn** [comment]
Also Experiencing this also on latest version of version-15, message shows up on journal entry as references.

**Comment by Ponyooooo** [comment]
This is still not resolved

**Comment by Ponyooooo** [comment]
Any update on this? We cannot process payment entries due to the message :(

**Comment by Ponyooooo** [comment]
any update on this?

**Comment by szufisher** [comment]
added precision parameter in flt function solved the problem.
![image](https://github.com/frappe/erpnext/assets/12823863/aa2afbd0-5bb9-46fc-bccb-d74ccfbad460)

**Comment by Ponyooooo** [comment]
how can we add this when using frappecloud? looks like this bug is still not added to the latest version update

**Comment by Ponyooooo** [comment]
Any update on this?

**Comment by Ponyooooo** [comment]
@ruthra-kumar how can we fix the bug when using a frappecloud?

**Comment by ruthra-kumar** [comment]
@Ponyooooo If you are in FrappeCloud, would suggest you to raise a support ticket on this.

**Comment by Ponyooooo** [comment]
Hi @szufisher how can we integrate your solution using client script or server script since frappecloud does not allow us to edit the backcodes of the erpnext. Our only way is to use client or server script only unless your solution will be included on the next version update. :(

**Comment by Ramesh-Udhyam** [comment]
It looks like this issue is still not solved. Is this not impacting many people? How come it is not a P0 issue?

**Comment by Ponyooooo** [comment]
Still no progress on this one

**Comment by Ponyooooo** [comment]
Any progress? This is not possible to be added on the client script

**Comment by quebn** [comment]
Found the issue why this Bug happens.
in our case it's Because if the Journal Entry has the following Entries shown below:
![image](https://github.com/user-attachments/assets/fbc29cb0-33d3-49cc-b396-d79cc7163fca)
- if the accounting entries have a payable entry credited on a party. but has also an entry debited on the same party.
when we set them as references in the payment entry the system will calculated the outstanding by subtracting the debited entry on the credited entry despite the accounts of those entry clearly being different. so the payment entry will only show the difference as the outstanding show below
![image](https://github.com/user-attachments/assets/678e6d71-a2fa-4fbb-beb3-995919e909ef)
hence the error message below when we try to save/submit the payment entry
![image](https://github.com/user-attachments/assets/eb4e3841-5e32-4074-8c46-59b3c246ed8b)

**Comment by Ponyooooo** [comment]
can the fix be included for version 14? journal entry cannot close any invoices and expense claims for this bug.

**Comment by Ponyooooo** [comment]
current version: Bug still not resolved.

ERPNext: v14.74.6 (HEAD)
Frappe Framework: v14.82.2 (HEAD)

**Comment by Ponyooooo** [comment]
any fix for version 14?

**Comment by Ponyooooo** [comment]
any fix for 
ERPNext: v14.78.5 (HEAD)
Frappe Framework: v14.89.0 (HEAD)?

**Comment by Ponyooooo** [comment]
any fix for version 14?

**Comment by Ponyooooo** [comment]
found some previous fixes that can integrate to fix this bug for ERPNext: v14.80.0 (HEAD), Frappe Framework: v14.92.0 (HEAD)??? 

https://github.com/frappe/erpnext/pull/36030, https://github.com/frappe/erpnext/pull/36011

**Comment by kponsakthivel** [comment]
I this issue resolved in version-15

**Comment by DipenFrappe** [comment]
This is resolved; you can check in the latest v14 version. Also working in v15.
<img width="1280" height="756" alt="Image" src="https://github.com/user-attachments/assets/b4571171-5e33-47e4-abf4-f521e3af2a06" />
