### ISSUE TITLE
Create Quotation from web site

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#42129]
### Information about bug

choose items at website
![image](https://github.com/frappe/erpnext/assets/62122640/7e0d6353-62be-40f6-961b-db22f802618a)

>> click add to quote 
>> go to quote
![image](https://github.com/frappe/erpnext/assets/62122640/fd6badeb-4dc0-49f4-90ed-ac2508b6af36)
>>request for quote
![image](https://github.com/frappe/erpnext/assets/62122640/8b4819d4-04c0-44bd-9abf-169823bfc208)
>>
![image](https://github.com/frappe/erpnext/assets/62122640/aae7a6dc-ac08-496b-8e78-00144951f736)

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
  File "apps/webshop/webshop/templates/pages/order.py", line 43, in get_context
    "Customer", context.doc.customer, "loyalty_program"
AttributeError: 'Quotation' object has no attribute 'customer'

### Module

selling, ecommerce

### Version

ERPNext: v15.27.1 (version-15)

Frappe Framework: v15.29.1 (version-15)

Frappe HR: v15.22.1 (version-15)

Payments: v0.0.1 (version-15)

Webshop: v0.0.1 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Issue already raised in webshop app: https://github.com/frappe/webshop/issues/146 & https://github.com/frappe/webshop/issues/114

PR already raised: https://github.com/frappe/webshop/pull/139
