### ISSUE TITLE
"Column 'owner' in where clause is ambiguous" 

### ISSUE THREAD

**Issue by ilqc** [frappe/erpnext#42199]
### Information about bug

# An error occurred when the employee used the saved filter criteria for filtering

## About the doctype: Lead   1...n   CRM Note

![01ccc197719e480b153a807253868ba1](https://github.com/frappe/erpnext/assets/86349730/22e06a15-c9ad-4a58-af1e-7d0fd9c5b1cb)

![image](https://github.com/frappe/erpnext/assets/86349730/aa01a3c3-ce30-45af-af3f-4afc874ad730)

![35612b6c974cec6dbde32437515cb83c](https://github.com/frappe/erpnext/assets/86349730/9dffc8c9-1867-4f7f-8430-b84818360892)

### Module

CRM

### Version

erpnext 15.27.7 version-15 (fa6a479)
frappe 15.31.0 version-15 (c68fbdd)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
127.0.0.1 - - [06/Jul/2024 09:32:42] "POST /api/method/frappe.desk.reportview.get HTTP/1.1" 500 -
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/reportview.py", line 32, in get
    data = compress(execute(**args), args=args)
                    ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/reportview.py", line 78, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1052, "Column 'owner' in where clause is ambiguous")
```

**Comment by Nihantra-Patel** [comment]
If the Lead doctype has an owner field, you need to define it as follows:

```sql
AND (
    `tabLead`.`owner` IN ('XYZ')
)
```

We tested it, and it works fine, also you have to set for the lead owner. However, if you do not include `tabLead`, it will not work.

**Comment by ilqc** [comment]
Sorry, I didn't describe it clearly earlier. The SQL code on the image was obtained through debugging the build_and_run function in frappe/model/db_query.py. The administrator does not have this issue, but other users may have it

**Comment by ilqc** [comment]
> 如果 Lead 文档类型具有所有者字段，则需要按如下方式定义它：
> 
> ```sql
> AND (
>     `tabLead`.`owner` IN ('XYZ')
> )
> ```
> 
> 我们测试过，它运行良好，您还必须为潜在客户设置。但是，如果您不包含`tabLead`，它将不起作用。

Sorry, I didn't describe it clearly earlier. The SQL code on the image was obtained through debugging the build_and_run function in frappe/model/db_query.py. The administrator does not have this issue, but other users may have it

**Comment by ilqc** [comment]
> If the Lead doctype has an owner field, you need to define it as follows:
> 
> ```sql
> AND (
>     `tabLead`.`owner` IN ('XYZ')
> )
> ```
> 
> We tested it, and it works fine, also you have to set for the lead owner. However, if you do not include `tabLead`, it will not work.

Sorry, I didn't describe it clearly earlier. The SQL code on the image was obtained through debugging the build_and_run function in frappe/model/db_query.py. The administrator does not have this issue, but other users may have it
