### ISSUE TITLE
Issue with Error While Creating Sales Invoice from Sales Order

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#42228]
### Information about bug

Hello,
I am encountering an issue when creating a sales invoice from a sales order in our ERP system. Specifically, an error occurs during the submission process.

For your reference, kindly verify the error details provided in the attached clipboard.
![Screenshot 2024-07-08 114609](https://github.com/frappe/erpnext/assets/75109236/33d724c7-d95a-4b82-aae0-3aa525e52a0e)

### Module

selling

### Version

Frappe version :   15.33.2
ERPNext version : 15.29.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"backup_genie": "0.0.1",
	"erpnext": "15.29.1",
	"frappe": "15.33.2",
	"hrms": "15.23.1",
	"india_compliance": "15.9.2",
	"lending": "0.0.1",
	"non_profit": "0.0.1",
	"nx_theme": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/UM/24-25/8163
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 469, in on_submit
    self.update_against_document_in_jv()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1551, in update_against_document_in_jv
    reconcile_against_document(lst, active_dimensions=active_dimensions)
  File "apps/erpnext/erpnext/accounts/utils.py", line 501, in reconcile_against_document
    referenced_row, update_advance_paid = update_reference_in_payment_entry(
  File "apps/erpnext/erpnext/accounts/utils.py", line 727, in update_reference_in_payment_entry
    payment_entry.set_missing_ref_details(
TypeError: NonProfitPaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'update_ref_details_only_for'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"UM/24-25/8163\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":11,\"title\":\"Revathi C - 9884760730 , 9940426784\",\"naming_series\":\"UM/24-25/.####\",\"customer\":\"Revathi C - 9884760730 , 9940426784\",\"customer_name\":\"Revathi C - 9884760730 , 9940426784\",\"e_waybill_status\":\"\",\"company\":\"Test Industries\",\"posting_date\":\"2024-07-06\",\"posting_time\":\"13:09:31.746514\",\"set_posting_time\":0,\"due_date\":\"2024-07-06\",\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"reason_for_issuing_document\":\"\",\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"is_reverse_charge\":0,\"is_export_with_gst\":0,\"branch\":\"Choolaimedu\",\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"set_warehouse\":\"ORDER Godown - UM\",\"total_qty\":4,\"total_net_weight\":0,\"base_total\":12349,\"base_net_total\":10575.32,\"total\":12349,\"net_total\":10575.32,\"tax_category\":\"In-State\",\"taxes_and_charges\":\"Output GST In-state - UM\",\"base_total_taxes_and_charges\":1773.68,\"total_taxes_and_charges\":1773.68,\"base_grand_total\":12349,\"base_rounding_adjustment\":0,\"base_rounded_total\":12349,\"base_in_words\":\"\",\"grand_total\":12349,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":12349,\"in_words\":\"\",\"total_advance\":2900,\"outstanding_amount\":9449,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">HSN/SAC</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Output Tax SGST </th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Output Tax CGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>9404</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 9,576.27\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(9.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 861.86\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(9.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 861.86\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>6304</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 999.05\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(2.5%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 24.98\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(2.5%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 24.98\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"gst_breakup_table\":null,\"total_billing_hours\":0,\"total_billing_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"allocate_advances_automatically\":1,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"customer_address\":\"Home-Billing-3870\",\"address_display\":\"No : 31 <br>Bajanai Koil , 2nd Street <br>Choolaimedu<br>Chennai<br>\\nTamil Nadu, State Code: 33<br>Postal Code: 600094<br>India<br>\\n\",\"gst_category\":\"Unregistered\",\"place_of_supply\":\"33-Tamil Nadu\",\"contact_person\":\"Revathi C - 9884760730 , 9940426784-Revathi C - 9884760730 , 9940426784\",\"contact_display\":\"Revathi C - 9884760730 , 9940426784\",\"territory\":\"India\",\"shipping_address_name\":\"Home-Billing-3870\",\"shipping_address\":\"No : 31 <br>Bajanai Koil , 2nd Street <br>Choolaimedu<br>Chennai<br>\\nTamil Nadu, State Code: 33<br>Postal Code: 600094<br>India<br>\\n\",\"company_address\":\"HOME-Billing-3469\",\"company_address_display\":\"FLAT NO - D F 4 , NAVEEN\\\"S SHUBAHMANGALAA APPARTMENTS<br>KALASATHAAMMAN KOIL STREET , <br>NEAR - ROYALA NAGAR , RAMAPURAM<br>Chennai<br>\\nTamil Nadu, State Code: 33<br>Postal Code: 600089<br>India<br>\\n\",\"ignore_default_payment_terms_template\":0,\"payment_terms_template\":\"Retail Customer\",\"tc_name\":\"Sales Invoice 2\",\"terms\":\"<p align=\\\"left\\\"><u>Terms &amp; Conditions:</u></p>\\n<p align=\\\"left\\\">E &amp; OE ( Errors and Omissions Excepted )</p>\\n<p align=\\\"left\\\">100% Payment to be made before delivery</p>\\n<p align=\\\"left\\\">Subject to Chennai Jurisdiction</p>\\n<p align=\\\"left\\\"></p>\\n\\n\\n<p align=\\\"right\\\">For Test Industries</p><br>\\n<br>\\n<br>\\n<p align=\\\"right\\\">Authorized Signatory</p>\",\"po_no\":\"\",\"debit_to\":\"Debtors - UM\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"against_income_account\":\"Sales - UM\",\"amount_eligible_for_commission\":10575.32,\"commission_rate\":0,\"total_commission\":0,\"letter_head\":\"LH - Choolaimedu\",\"group_same_items\":0,\"invoice_copy\":\"Original for Recipient\",\"language\":\"en\",\"distance\":0,\"mode_of_transport\":\"Road\",\"lr_date\":\"2024-07-06\",\"gst_vehicle_type\":\"Regular\",\"ecommerce_supply_type\":null,\"status\":\"Draft\",\"einvoice_status\":\"\",\"customer_group\":\"Retail\",\"is_internal_customer\":0,\"is_discounted\":0,\"remarks\":\"No Remarks\",\"repost_required\":0,\"doctype\":\"Sales Invoice\",\"timesheets\":[],\"advances\":[{\"name\":\"j3o5kfsrjp\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:31.788451\",\"modified\":\"2024-07-06 13:09:31.788451\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"reference_type\":\"Payment Entry\",\"reference_name\":\"ACC-PAY-2024-00823\",\"remarks\":\"Amount INR 2900 received from Revathi C - 9884760730 , 9940426784\\nTransaction reference no G Pay dated 2024-07-04\\nAmount INR 2900 against Sales Order SO/23-24/0937\",\"reference_row\":\"v2a56vdisk\",\"advance_amount\":2900,\"allocated_amount\":2900,\"exchange_gain_loss\":0,\"ref_exchange_rate\":1,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"advances\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Advance\"}],\"taxes\":[{\"name\":\"j3motn9r3v\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"charge_type\":\"On Net Total\",\"account_head\":\"Output Tax SGST - UM\",\"description\":\"Output Tax SGST \",\"included_in_print_rate\":1,\"included_in_paid_amount\":0,\"cost_center\":\"Main - UM\",\"rate\":0,\"gst_tax_type\":\"sgst\",\"tax_amount\":886.84,\"total\":11462.16,\"tax_amount_after_discount_amount\":886.84,\"base_tax_amount\":886.84,\"base_total\":11462.16,\"base_tax_amount_after_discount_amount\":886.84,\"item_wise_tax_detail\":\"{\\\"SE4CB1SCS\\\":[9,861.71],\\\"SEPSL\\\":[9,0.15],\\\"TBSOQ\\\":[2.5,24.98]}\",\"dont_recompute_tax\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Taxes and Charges\"},{\"name\":\"j3mo849a4p\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"charge_type\":\"On Net Total\",\"account_head\":\"Output Tax CGST - UM\",\"description\":\"Output Tax CGST\",\"included_in_print_rate\":1,\"included_in_paid_amount\":0,\"cost_center\":\"Main - UM\",\"rate\":0,\"gst_tax_type\":\"cgst\",\"tax_amount\":886.84,\"total\":12349,\"tax_amount_after_discount_amount\":886.84,\"base_tax_amount\":886.84,\"base_total\":12349,\"base_tax_amount_after_discount_amount\":886.84,\"item_wise_tax_detail\":\"{\\\"SE4CB1SCS\\\":[9,861.71],\\\"SEPSL\\\":[9,0.15],\\\"TBSOQ\\\":[2.5,24.98]}\",\"dont_recompute_tax\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Taxes and Charges\"}],\"items\":[{\"name\":\"j3modqeek2\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"SE4CB1SCS\",\"item_name\":\"Sleep Essentials - 4CB1SCS\",\"description\":\"<div class=\\\"ql-editor read-mode\\\"><p>Sleep Essentials - Ortho Collection - 74.5 in x 45 in x 5 in</p><p>4in (Coir + Bonded) + 1in HR</p></div>\",\"gst_hsn_code\":\"9404\",\"item_group\":\"Mattress\",\"brand\":\"Sleep Essentials\",\"image\":\"\",\"qty\":1,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":12948,\"base_price_list_rate\":12948,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":12.743,\"discount_amount\":1650,\"base_rate_with_margin\":0,\"rate\":11298,\"amount\":11298,\"item_tax_template\":\"GST 18% - UM\",\"gst_treatment\":\"Taxable\",\"base_rate\":11298,\"base_amount\":11298,\"stock_uom_rate\":11298,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":9574.58,\"net_amount\":9574.57627118644,\"base_net_rate\":9574.58,\"base_net_amount\":9574.58,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":9,\"sgst_rate\":9,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":861.71,\"sgst_amount\":861.71,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"delivered_by_supplier\":0,\"income_account\":\"Sales - UM\",\"is_fixed_asset\":0,\"expense_account\":\"Cost of Goods Sold - UM\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"ORDER Godown - UM\",\"use_serial_batch_fields\":0,\"allow_zero_valuation_rate\":0,\"incoming_rate\":6779.66,\"item_tax_rate\":\"{\\\"Output Tax SGST - UM\\\": 9.0, \\\"Output Tax CGST - UM\\\": 9.0, \\\"Output Tax IGST - UM\\\": 18.0, \\\"Input Tax SGST - UM\\\": 9.0, \\\"Input Tax CGST - UM\\\": 9.0, \\\"Input Tax IGST - UM\\\": 18.0, \\\"Input Tax SGST RCM - UM\\\": 9.0, \\\"Input Tax CGST RCM - UM\\\": 9.0, \\\"Input Tax IGST RCM - UM\\\": 18.0}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SO/23-24/0937\",\"so_detail\":\"v1b5o7537d\",\"delivered_qty\":0,\"cost_center\":\"Main - UM\",\"page_break\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"},{\"name\":\"j3mogsb4cg\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"has_item_scanned\":0,\"item_code\":\"SEPSL\",\"item_name\":\"Sleep Essentials Shredded Latex Pillow\",\"description\":\"<div><p>Sleep Essentials Shredded Latex Pillow</p></div>\",\"gst_hsn_code\":\"9404\",\"item_group\":\"Pillow\",\"brand\":\"Sleep Essentials\",\"image\":\"\",\"qty\":2,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":2,\"price_list_rate\":1,\"base_price_list_rate\":1,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":1,\"amount\":2,\"item_tax_template\":\"GST 18% - UM\",\"gst_treatment\":\"Taxable\",\"base_rate\":1,\"base_amount\":2,\"stock_uom_rate\":1,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":0.85,\"net_amount\":1.6949152542372883,\"base_net_rate\":0.85,\"base_net_amount\":1.69,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":9,\"sgst_rate\":9,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":0.15,\"sgst_amount\":0.15,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"delivered_by_supplier\":0,\"income_account\":\"Sales - UM\",\"is_fixed_asset\":0,\"expense_account\":\"Cost of Goods Sold - UM\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"ORDER Godown - UM\",\"use_serial_batch_fields\":0,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0.85,\"item_tax_rate\":\"{\\\"Output Tax SGST - UM\\\": 9.0, \\\"Output Tax CGST - UM\\\": 9.0, \\\"Output Tax IGST - UM\\\": 18.0, \\\"Input Tax SGST - UM\\\": 9.0, \\\"Input Tax CGST - UM\\\": 9.0, \\\"Input Tax IGST - UM\\\": 18.0, \\\"Input Tax SGST RCM - UM\\\": 9.0, \\\"Input Tax CGST RCM - UM\\\": 9.0, \\\"Input Tax IGST RCM - UM\\\": 18.0}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SO/23-24/0937\",\"so_detail\":\"v1b5otqg9n\",\"delivered_qty\":0,\"cost_center\":\"Main - UM\",\"page_break\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"},{\"name\":\"j3mosam314\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":3,\"has_item_scanned\":0,\"item_code\":\"TBSOQ\",\"item_name\":\"Trident Occassion Bedsheet - Queen\",\"description\":\"Trident Occassion Bedsheet - Queen\",\"gst_hsn_code\":\"6304\",\"item_group\":\"Bed Linen - Medium\",\"brand\":\"Trident\",\"image\":\"\",\"qty\":1,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":1899,\"base_price_list_rate\":1899,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":44.76,\"discount_amount\":850,\"base_rate_with_margin\":0,\"rate\":1049,\"amount\":1049,\"item_tax_template\":\"GST 5% - UM\",\"gst_treatment\":\"Taxable\",\"base_rate\":1049,\"base_amount\":1049,\"stock_uom_rate\":1049,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":999.05,\"net_amount\":999.047619047619,\"base_net_rate\":999.05,\"base_net_amount\":999.05,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":2.5,\"sgst_rate\":2.5,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":24.98,\"sgst_amount\":24.98,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"delivered_by_supplier\":0,\"income_account\":\"Sales - UM\",\"is_fixed_asset\":0,\"expense_account\":\"Cost of Goods Sold - UM\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"ORDER Godown - UM\",\"use_serial_batch_fields\":0,\"allow_zero_valuation_rate\":0,\"incoming_rate\":584.74,\"item_tax_rate\":\"{\\\"Output Tax SGST - UM\\\": 2.5, \\\"Output Tax CGST - UM\\\": 2.5, \\\"Output Tax IGST - UM\\\": 5.0, \\\"Input Tax SGST - UM\\\": 2.5, \\\"Input Tax CGST - UM\\\": 2.5, \\\"Input Tax IGST - UM\\\": 5.0, \\\"Input Tax SGST RCM - UM\\\": 2.5, \\\"Input Tax CGST RCM - UM\\\": 2.5, \\\"Input Tax IGST RCM - UM\\\": 5.0}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SO/23-24/0937\",\"so_detail\":\"v1b5je14ht\",\"delivered_qty\":0,\"cost_center\":\"Main - UM\",\"page_break\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"}],\"packed_items\":[],\"pricing_rules\":[],\"payments\":[],\"payment_schedule\":[{\"name\":\"j3mqmt5mb8\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.444280\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"payment_term\":\"On Delivery\",\"due_date\":\"2024-07-06\",\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount_date\":\"2024-07-06\",\"discount\":0,\"payment_amount\":9449,\"outstanding\":9449,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":9449,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\"}],\"sales_team\":[{\"name\":\"j3moar5uop\",\"owner\":\"Administrator\",\"creation\":\"2024-07-06 13:09:27.194611\",\"modified\":\"2024-07-06 13:09:31.542775\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"sales_person\":\"Satish\",\"allocated_percentage\":100,\"allocated_amount\":10575.32,\"incentives\":0,\"parent\":\"UM/24-25/8163\",\"parentfield\":\"sales_team\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Team\"}],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-07-08T12:56:43.237Z\",\"_submitted_from_ui\":1}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700162719422162446171": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1149,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: NonProfitPaymentEntry.set_missing_ref_details() got an unexpected keyword argument 'update_ref_details_only_for'",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Nihantra-Patel** [comment]
We tested with advance payment and without advance payment, but everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/16b31a73-495e-4575-a90e-6c70f8df48a3


https://github.com/frappe/erpnext/assets/141945075/f6a15556-5c0c-4fa6-b3ce-cd4e24c3a6c3
