### ISSUE TITLE
Payment Entry against Employee Advanced ( Reference Doctype must be one of . at 0x10ac5d380> )

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#42690]
### Information about bug

![Screenshot 2024-08-09 at 11 10 15 AM](https://github.com/user-attachments/assets/829ed601-08ce-42c0-9a6c-8cb10ed6da4f)

https://github.com/user-attachments/assets/4f0aa396-a2c1-4e92-976c-6a95cf01e7e0

### Module

accounts, HR

### Version

ERPNext: v15.32.1 (version-15)

Frappe Framework: v15.37.0 (version-15)

Gameplan: v0.0.1 (main)

Helpdesk: v0.10.0 (main)

Frappe HR: v15.25.2 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 83, in validate
    self.validate_reference_documents()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 496, in validate_reference_documents
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Reference Doctype must be one of . at 0x10d546ea0>
```

**Comment by dineshpanchal93** [comment]
@ruchamahabal

**Comment by Nihantra-Patel** [comment]
But I don't face any such issue in the this version 🤔


https://github.com/user-attachments/assets/b3a691b4-a8fb-4fb6-8be1-5db95948417e

**Comment by dineshpanchal93** [comment]
Oh, I see let me check at my end.  We have not done any customization !!!
