### ISSUE TITLE
Sales invoice submission or saving error

### ISSUE THREAD

**Issue by mubarack** [frappe/erpnext#42752]
### Information about bug

While submitting or saving a sales invoice i get an error as detailed below 

### Module

selling

### Version

"crm": "2.0.0-dev",
	"erpnext": "15.32.1",
	"frappe": "15.37.0",
	"healthcare": "16.0.0-dev",
	"posawesome": "6.3.0"

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"crm": "2.0.0-dev",
	"education": "15.5.0",
	"erpnext": "15.32.1",
	"frappe": "15.37.0",
	"healthcare": "16.0.0-dev",
	"hrms": "16.0.0-dev",
	"lms": "2.0.0",
	"payments": "0.0.1",
	"posawesome": "6.3.0"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    hooks.append(frappe.get_attr(handler))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1758, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1476, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "apps/posawesome/posawesome/posawesome/api/invoice.py", line 12, in <module>
    from posawesome.posawesome.api.posapp import get_company_domain
  File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 15, in <module>
    from erpnext.stock.doctype.batch.batch import (
ImportError: cannot import name 'set_batch_nos' from 'erpnext.stock.doctype.batch.batch' (apps/erpnext/erpnext/stock/doctype/batch/batch.py)

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-SINV-2024-00001\",\"owner\":\"Administrator\",\"creation\":\"2024-08-13 14:12:03.008637\",\"modified\":\"2024-08-13 14:47:19.318347\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Mech Energy Limited\",\"naming_series\":\"ACC-SINV-.YYYY.-\",\"customer\":\"Mech Energy Limited\",\"customer_name\":\"Mech Energy Limited\",\"company\":\"Cyberforge Innovations Limited\",\"company_tax_id\":\"B20240403VGDDYK\",\"posting_date\":\"2024-08-13\",\"posting_time\":\"14:12:2.758364\",\"set_posting_time\":0,\"due_date\":\"2024-08-13\",\"is_pos\":0,\"posa_is_printed\":0,\"is_consolidated\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"currency\":\"USD\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"USD\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"total_qty\":26,\"total_net_weight\":0,\"base_total\":1398,\"base_net_total\":1398,\"total\":1398,\"net_total\":1398,\"exempt_from_sales_tax\":0,\"tax_category\":\"\",\"taxes_and_charges\":\"South Sudan Sales Tax 18% - CIL\",\"posa_delivery_charges_rate\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":1398,\"base_rounding_adjustment\":0,\"base_rounded_total\":1398,\"base_in_words\":\"\",\"grand_total\":1398,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":1398,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":1398,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">Item</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Sales Tax  18%</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>001</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 240.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(18.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 43.20\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>005</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 50.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(18.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 9.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>007</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 1,008.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(18.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 181.44\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>008</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 100.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(18.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 18.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"total_billing_hours\":0,\"total_billing_amount\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"customer_address\":\"Mech Energy Limited-Billing\",\"address_display\":\"Opposite Midan Rainbow Hai Kuwait<br>\\nJuba, CES 00211<br>South Sudan\",\"contact_person\":\"Mech Energy Limited-Mech Energy Limited\",\"contact_display\":\"Mech Energy Limited\",\"contact_mobile\":\"+211 920 101 024\",\"contact_email\":\"info@mechenergyltd.com\",\"shipping_address_name\":\"Mech Energy Limited-Billing\",\"shipping_address\":\"Opposite Midan Rainbow Hai Kuwait<br>\\nJuba, CES 00211<br>South Sudan\",\"ignore_default_payment_terms_template\":0,\"po_no\":\"PO001\",\"po_date\":\"2024-07-26\",\"debit_to\":\"1310 - Debtors - CIL\",\"party_account_currency\":\"USD\",\"is_opening\":\"No\",\"amount_eligible_for_commission\":1398,\"commission_rate\":0,\"total_commission\":0,\"letter_head\":\"CyberFoge Innovations Limited\",\"group_same_items\":0,\"language\":\"en-US\",\"status\":\"Draft\",\"is_internal_customer\":0,\"is_discounted\":0,\"doctype\":\"Sales Invoice\",\"posa_offers\":[],\"items\":[{\"name\":\"0uouhk9vnk\",\"owner\":\"Administrator\",\"creation\":\"2024-08-13 14:12:03.008637\",\"modified\":\"2024-08-13 14:12:03.008637\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"has_item_scanned\":0,\"item_code\":\"001\",\"item_name\":\"001 - Website Hosting\",\"description\":\"001\",\"item_group\":\"Services\",\"qty\":12,\"stock_uom\":\"Service\",\"uom\":\"Service\",\"conversion_factor\":1,\"stock_qty\":12,\"price_list_rate\":20,\"base_price_list_rate\":20,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":20,\"amount\":240,\"base_rate\":20,\"base_amount\":240,\"posa_offer_applied\":0,\"posa_is_offer\":0,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":20,\"net_amount\":240,\"base_net_rate\":20,\"base_net_amount\":240,\"delivered_by_supplier\":0,\"income_account\":\"4110 - Sales - CIL\",\"is_fixed_asset\":0,\"expense_account\":\"5111 - Cost of Goods Sold - CIL\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - CIL\",\"quality_inspection\":\"MAT-QA-2024-00001\",\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SAL-ORD-2024-00001\",\"so_detail\":\"vfbf2gslhu\",\"delivery_note\":\"MAT-DN-2024-00001\",\"dn_detail\":\"vmb21akafu\",\"delivered_qty\":0,\"cost_center\":\"Main - CIL\",\"page_break\":0,\"parent\":\"ACC-SINV-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"},{\"name\":\"0uoumntavq\",\"owner\":\"Administrator\",\"creation\":\"2024-08-13 14:12:03.008637\",\"modified\":\"2024-08-13 14:12:03.008637\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":2,\"has_item_scanned\":0,\"item_code\":\"005\",\"item_name\":\"005 - Domain Registration or Subscription\",\"description\":\"<div><p> Domain Registration or Subscription</p></div>\",\"item_group\":\"Services\",\"qty\":1,\"stock_uom\":\"Service\",\"uom\":\"Service\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":50,\"base_price_list_rate\":50,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":50,\"amount\":50,\"base_rate\":50,\"base_amount\":50,\"posa_offer_applied\":0,\"posa_is_offer\":0,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":50,\"net_amount\":50,\"base_net_rate\":50,\"base_net_amount\":50,\"delivered_by_supplier\":0,\"income_account\":\"4110 - Sales - CIL\",\"is_fixed_asset\":0,\"expense_account\":\"5111 - Cost of Goods Sold - CIL\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - CIL\",\"quality_inspection\":\"MAT-QA-2024-00002\",\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SAL-ORD-2024-00001\",\"so_detail\":\"vfbf9q3mp2\",\"delivery_note\":\"MAT-DN-2024-00001\",\"dn_detail\":\"vmb2m9112u\",\"delivered_qty\":0,\"cost_center\":\"Main - CIL\",\"page_break\":0,\"parent\":\"ACC-SINV-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"},{\"name\":\"0uourvmie8\",\"owner\":\"Administrator\",\"creation\":\"2024-08-13 14:12:03.008637\",\"modified\":\"2024-08-13 14:12:03.008637\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":3,\"has_item_scanned\":0,\"item_code\":\"007\",\"item_name\":\"007 - Email Hosting \",\"description\":\"007\",\"item_group\":\"Services\",\"qty\":12,\"stock_uom\":\"Service\",\"uom\":\"Service\",\"conversion_factor\":1,\"stock_qty\":12,\"price_list_rate\":84,\"base_price_list_rate\":84,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":84,\"amount\":1008,\"base_rate\":84,\"base_amount\":1008,\"posa_offer_applied\":0,\"posa_is_offer\":0,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":84,\"net_amount\":1008,\"base_net_rate\":84,\"base_net_amount\":1008,\"delivered_by_supplier\":0,\"income_account\":\"4110 - Sales - CIL\",\"is_fixed_asset\":0,\"expense_account\":\"5111 - Cost of Goods Sold - CIL\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - CIL\",\"quality_inspection\":\"MAT-QA-2024-00003\",\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SAL-ORD-2024-00001\",\"so_detail\":\"vfbf7l06g2\",\"delivery_note\":\"MAT-DN-2024-00001\",\"dn_detail\":\"vmb2lmia1a\",\"delivered_qty\":0,\"cost_center\":\"Main - CIL\",\"page_break\":0,\"parent\":\"ACC-SINV-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"},{\"name\":\"0uoultmle4\",\"owner\":\"Administrator\",\"creation\":\"2024-08-13 14:12:03.008637\",\"modified\":\"2024-08-13 14:12:03.008637\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":4,\"has_item_scanned\":0,\"item_code\":\"008\",\"item_name\":\"008 - Support and Maintenance\",\"description\":\"008 - Support and Maintenance\",\"item_group\":\"Services\",\"qty\":1,\"stock_uom\":\"Service\",\"uom\":\"Service\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":100,\"base_price_list_rate\":100,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":100,\"amount\":100,\"base_rate\":100,\"base_amount\":100,\"posa_offer_applied\":0,\"posa_is_offer\":0,\"stock_uom_rate\":0,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":100,\"net_amount\":100,\"base_net_rate\":100,\"base_net_amount\":100,\"delivered_by_supplier\":0,\"income_account\":\"4110 - Sales - CIL\",\"is_fixed_asset\":0,\"expense_account\":\"5111 - Cost of Goods Sold - CIL\",\"enable_deferred_revenue\":0,\"weight_per_unit\":0,\"total_weight\":0,\"warehouse\":\"Stores - CIL\",\"quality_inspection\":\"MAT-QA-2024-00004\",\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"sales_order\":\"SAL-ORD-2024-00001\",\"so_detail\":\"vfbf8ktpf8\",\"delivery_note\":\"MAT-DN-2024-00001\",\"dn_detail\":\"vmb2cbf7or\",\"delivered_qty\":0,\"cost_center\":\"Main - CIL\",\"page_break\":0,\"parent\":\"ACC-SINV-2024-00001\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\"}],\"packed_items\":[],\"posa_coupons\":[],\"taxes\":[],\"sales_team\":[],\"payment_schedule\":[],\"pricing_rules\":[],\"advances\":[],\"timesheets\":[],\"payments\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-08-13T11:54:34.931Z\",\"cost_center\":\"Main - CIL\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery370051537781519557961": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 2327,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ImportError: cannot import name 'set_batch_nos' from 'erpnext.stock.doctype.batch.batch' (apps/erpnext/erpnext/stock/doctype/batch/batch.py)",
	"exc_type": "ImportError",
	"_exc_source": "posawesome (app)"
}
```
```

**Comment by Nihantra-Patel** [comment]
Error from the posawesome side, not from the ERPNext side. so please raise the issue on posawesome github.
