### ISSUE TITLE
Server error: pymysql.err.ProgrammingError

### ISSUE THREAD

**Issue by artspark** [frappe/erpnext#43153]
### Information about bug

Getting an error while creating a “payment entry” from the drop down menu of a “purchase invoice”. Please refer the screenshot attached for reference. 
![univ1](https://github.com/user-attachments/assets/bd943633-5da1-4dea-af93-9a6fb451f26a)

### Module

accounts, buying

### Version

"erpnext": "13.55.2",
"frappe": "13.58.21"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.55.2",
	"frappe": "13.58.21"
}
```
### Route
```
Form/Payment Entry/new-payment-entry-2
```
### Traceback
```
Syntax error in query:
select sum(base_net_total) from `tabPurchase Order` where `name` in () order by modified desc limit 1
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 25, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 334, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 263, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1059, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1267, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1249, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 82, in validate
    self.set_tax_withholding()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 620, in set_tax_withholding
    order_amount = self.get_order_net_total()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 676, in get_order_net_total
    doctype, {"name": ["in", docnames]}, ["sum(base_net_total)"]
  File "apps/frappe/frappe/database/database.py", line 482, in get_value
    limit=1,
  File "apps/frappe/frappe/database/database.py", line 553, in get_values
    limit=limit,
  File "apps/frappe/frappe/database/database.py", line 752, in _get_values_from_table
    update=update,
  File "apps/frappe/frappe/database/database.py", line 187, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') order by modified desc limit 1' at line 1")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"owner\":\"server@whitepearl.biz\",\"idx\":0,\"docstatus\":0,\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Pay\",\"payment_order_status\":\"Initiated\",\"posting_date\":\"2024-09-10\",\"company\":\"University of Lunsar\",\"party_type\":\"Supplier\",\"party\":\"Whitepearl IT solutions pvt. ltd.\",\"party_name\":\"Whitepearl IT solutions pvt. ltd.\",\"party_balance\":-10774.43,\"paid_from\":\"1110 - Cash - UOL\",\"paid_from_account_currency\":\"SLL\",\"paid_from_account_balance\":150000,\"paid_to\":\"2110 - Creditors - UOL\",\"paid_to_account_currency\":\"SLL\",\"paid_to_account_balance\":0,\"paid_amount\":10774.43,\"paid_amount_after_tax\":0,\"source_exchange_rate\":1,\"base_paid_amount\":10774.43,\"base_paid_amount_after_tax\":0,\"received_amount\":10774.43,\"received_amount_after_tax\":0,\"target_exchange_rate\":1,\"base_received_amount\":10774.43,\"base_received_amount_after_tax\":0,\"total_allocated_amount\":10774.43,\"base_total_allocated_amount\":10774.43,\"unallocated_amount\":0,\"difference_amount\":0,\"apply_tax_withholding_amount\":1,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"reference_date\":\"2024-09-10\",\"cost_center\":\"Main - UOL\",\"status\":\"Draft\",\"custom_remarks\":0,\"letter_head\":\"uol-letter head\",\"doctype\":\"Payment Entry\",\"references\":[{\"modified\":\"2024-09-10 10:16:34.956672\",\"modified_by\":\"server@whitepearl.biz\",\"parentfield\":\"references\",\"parenttype\":\"Payment Entry\",\"idx\":1,\"docstatus\":0,\"reference_doctype\":\"Purchase Invoice\",\"reference_name\":\"ACC-PINV-2024-00001\",\"due_date\":\"2024-08-09\",\"bill_no\":\"39-08/2025\",\"total_amount\":10774.43,\"outstanding_amount\":10774.43,\"allocated_amount\":10774.43,\"exchange_rate\":1,\"exchange_gain_loss\":0,\"doctype\":\"Payment Entry Reference\",\"__islocal\":1,\"parent\":\"new-payment-entry-2\",\"name\":\"new-payment-entry-reference-2\"}],\"taxes\":[],\"deductions\":[],\"__islocal\":1,\"__unsaved\":1,\"name\":\"new-payment-entry-2\",\"__last_sync_on\":\"2024-09-10T10:16:34.459Z\",\"mode_of_payment\":\"Cash\",\"paid_from_account_type\":\"Cash\",\"tax_withholding_category\":\"With holding tax 6.5%\",\"reference_no\":\"1345677777\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery2240148155950403088931": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 2999,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') order by modified desc limit 1' at line 1\")"
}
```
```

**Comment by Nihantra-Patel** [comment]
If it's a bug, it hasn't been fixed in version 13 because they stopped fixing bugs for that version. It might still have problems. It's best to upgrade to version 14 or 15. But once you generate a [support ticket](https://support.frappe.io/) if the cloud plan has support.

**Comment by artspark** [comment]
Thank you @Nihantra-Patel 

1) How can I upgrade the version.

2) Will the upgrade process remove any changes(custom form designs etc) that I made in version 13.

Thanks,
Deepak

**Comment by Nihantra-Patel** [comment]
If there is any customization then first store it in your custom app. if minor changes (custom field etc.) then it will stored in the database so first you can take a backup.

How to Version Upgrade in Frappe Cloud?: https://frappecloud.com/docs/sites/version-upgrade

**Comment by artspark** [comment]
Thank you for the version upgrade link.
Can you share a link that explains about custom app and how to store in it.
Yes, I have custom fields/doctypes and renamed doctypes. 
I have backed up the db, private and public files, JSON file.

**Comment by Nihantra-Patel** [comment]
You can search it on [Frappe Forum](https://discuss.frappe.io), and there are lots of posts.

**Comment by artspark** [comment]
Great! Thanks @Nihantra-Patel
