### ISSUE TITLE
Payments app - UnboundLocalError: local variable 'grand_total' referenced before assignment

### ISSUE THREAD

**Issue by eleben** [frappe/erpnext#43286]
### Information about bug

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/1cd976a8-ba69-40d5-ad2c-6d90a1813cc5">

Clicked on "Pay $1000.00" and get the following message

error UnboundLocalError: local variable 'grand_total' referenced before assignment

### Module

accounts

### Version

Version - Frappe Cloud (latest versions for each under the "version-14" branch)
ERPNext: v14.74.1 (HEAD)
Frappe Framework: v14.81.4 (HEAD)
Payments: v0.0.1 (HEAD) 

<img width="565" alt="image" src="https://github.com/user-attachments/assets/bc89423e-4a57-4cfe-864c-1a6fd6057495">

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 410, in make_payment_request
    grand_total = get_amount(ref_doc, gateway_account.get("payment_account"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 522, in get_amount
    if grand_total > 0:
UnboundLocalError: local variable 'grand_total' referenced before assignment
```

**Comment by AlaaL** [comment]
i have the same issue
