### ISSUE TITLE
When Supplier is choose in purchase order 

### ISSUE THREAD

**Issue by IBSLPUNE** [frappe/erpnext#43359]
### Information about bug

      When the Supplier is selected in the purchase order an error is throwing. 
![image](https://github.com/user-attachments/assets/8759b7ce-334e-413d-b5ff-bae5137f753b)

### Module

buying

### Version

ERPNext: v15.36.1 (version-15)

Frappe Framework: v15.41.0 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"chat": "0.0.1",
	"crm": "1.23.2",
	"erpnext": "15.36.1",
	"frappe": "15.41.0",
	"hrms": "15.29.0",
	"india_compliance": "15.13.2",
	"lms": "2.5.0",
	"payments": "0.0.1",
	"suyog": "0.0.2",
	"twilio_integration": "0.0.1"
}
```
### Route
```
Form/Purchase Order/new-purchase-order-vyjhtaeewv
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 93, in search_widget
    is_whitelisted(frappe.get_attr(query))
  File "apps/frappe/frappe/__init__.py", line 1765, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.controllers.queries' has no attribute 'supplier_query'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Supplier",
		"ignore_user_permissions": 0,
		"reference_doctype": "Purchase Order",
		"page_length": 10,
		"query": "erpnext.controllers.queries.supplier_query"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: module 'erpnext.controllers.queries' has no attribute 'supplier_query'",
	"exc_type": "AttributeError"
}
```
```

**Comment by Nihantra-Patel** [comment]
Everything is working fine in locally and also on the frappe cloud. No problems were encountered in the latest version 15.


https://github.com/user-attachments/assets/c4d9f906-c5ee-496a-8d94-da4486c2010c
