### ISSUE TITLE
Bug in Chart of Accounts Importer

### ISSUE THREAD

**Issue by skyasir456** [frappe/erpnext#43582]
### Information about bug

Please check trace-back

### Module

accounts

### Version

"ecommerce_integrations": "1.20.1",
	"erpnext": "15.38.0",
	"frappe": "15.43.0",
	"payments": "0.0.1",
	"webshop": "0.0.1"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"ecommerce_integrations": "1.20.1",
	"erpnext": "15.38.0",
	"frappe": "15.43.0",
	"payments": "0.0.1",
	"webshop": "0.0.1"
}
```
### Route
```
Form/Chart of Accounts Importer/Chart of Accounts Importer
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 373, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 41, in validate
    get_coa("Chart of Accounts Importer", "All Accounts", file_name=self.import_file, for_validate=1)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 174, in get_coa
    validate_accounts(file_doc, extension)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/chart_of_accounts_importer/chart_of_accounts_importer.py", line 372, in validate_accounts
    accounts_dict.setdefault(account["account_name"], account)
                             ~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'account_name'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Chart of Accounts Importer\",\"owner\":\"Administrator\",\"modified\":\"2024-10-08 22:43:41.789891\",\"modified_by\":\"shadabfs@alazka.ai\",\"docstatus\":0,\"idx\":\"0\",\"doctype\":\"Chart of Accounts Importer\",\"company\":\"MARWA IMPEX PRIVATE LIMITED (24-25)\",\"import_file\":\"/private/files/COA7.csv\",\"__unsaved\":1}",
		"action": "Save"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "64a40c2a-5c3f-49f0-a542-ad7c0f6c7bf1"
}
```
### Response Data
```
{
	"exception": "KeyError: 'account_name'",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by khushi8112** [comment]
Hi,
Please share the steps to reproduce this issue in the latest version.
