### ISSUE TITLE
Getting math domain error upon creating Sales Order

### ISSUE THREAD

**Issue by rnd-nguyenth** [frappe/erpnext#43611]
### Information about bug

Hi folk,

I am getting "ValueError: math domain error. Possible source of error: erpnext (app)" while creating new Sales Order.

I have tried "bench update" and "bench migrate" but could resolved the issue.
![image](https://github.com/user-attachments/assets/094a6e22-225c-4c60-9cb9-10a7b71e9ddd)

### Module

selling

### Version

ERPNext: v15.x.x-develop () (develop)

Framework: v15.x.x-develop () (develop)

Frappe HR: v16.0.0-dev (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "16.0.0-dev",
	"frappe": "16.0.0-dev",
	"hrms": "16.0.0-dev"
}
```
### Route
```
Form/Sales Order/new-sales-order-udpgroetav
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 118, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1831, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 411, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 433, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 364, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1198, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 1050, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1433, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1411, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 1047, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 200, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 29, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 269, in validate
    self.set_total_in_words()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 135, in set_total_in_words
    self.base_in_words = money_in_words(base_amount, self.company_currency)
  File "apps/frappe/frappe/utils/data.py", line 1480, in money_in_words
    fraction_length = math.ceil(math.log10(fraction_units)) or number_format.precision
ValueError: math domain error

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Order\",\"name\":\"new-sales-order-udpgroetav\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"title\":\"{customer_name}\",\"naming_series\":\"SAL-ORD-.YYYY.-\",\"order_type\":\"Sales\",\"transaction_date\":\"2024-10-11\",\"company\":\"BizOS\",\"skip_delivery_note\":0,\"currency\":\"VND\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"VND\",\"ignore_pricing_rule\":0,\"reserve_stock\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Order Item\",\"name\":\"new-sales-order-item-vsntcsmcgs\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"ensure_delivery_based_on_produced_serial_no\":0,\"is_stock_item\":1,\"reserve_stock\":1,\"stock_uom\":\"Box\",\"stock_reserved_qty\":0,\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"against_blanket_order\":null,\"page_break\":0,\"parent\":\"new-sales-order-udpgroetav\",\"parentfield\":\"items\",\"parenttype\":\"Sales Order\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"distributed_discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":200000,\"amount\":200000,\"base_rate\":200000,\"base_amount\":200000,\"stock_uom_rate\":200000,\"net_rate\":200000,\"net_amount\":200000,\"base_net_rate\":200000,\"base_net_amount\":200000,\"billed_amt\":0,\"valuation_rate\":0,\"gross_profit\":0,\"weight_per_unit\":0,\"total_weight\":0,\"blanket_order_rate\":0,\"projected_qty\":50,\"actual_qty\":50,\"ordered_qty\":0,\"planned_qty\":0,\"production_plan_qty\":0,\"work_order_qty\":0,\"delivered_qty\":0,\"produced_qty\":0,\"returned_qty\":0,\"picked_qty\":0,\"delivery_date\":\"2024-10-31\",\"item_code\":\"Máy tính\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Máy tính\",\"description\":\"Máy tính\",\"image\":\"\",\"warehouse\":\"Stores - BizOS\",\"income_account\":\"Sales - BizOS\",\"expense_account\":\"Cost of Goods Sold - BizOS\",\"discount_account\":null,\"provisional_expense_account\":null,\"cost_center\":\"Main - BizOS\",\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Box\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"is_fixed_asset\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-10-11\",\"bom_no\":null,\"item_group\":\"Products\",\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-sales-order-item-vsntcsmcgs\"}],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"packed_items\":[],\"pricing_rules\":[],\"payment_schedule\":[],\"status\":\"Draft\",\"delivery_status\":\"Not Delivered\",\"billing_status\":\"Not Billed\",\"advance_payment_status\":\"Not Requested\",\"sales_team\":[],\"group_same_items\":0,\"language\":\"en\",\"is_internal_customer\":0,\"party_account_currency\":\"VND\",\"advance_paid\":0,\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_address\":null,\"company_address_display\":null,\"base_net_total\":200000,\"net_total\":200000,\"base_total\":200000,\"total\":200000,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":200000,\"base_grand_total\":200000,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":200000,\"base_rounded_total\":200000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"amount_eligible_for_commission\":200000,\"total_commission\":null,\"tax_id\":null,\"customer_name\":\"Công ty thiết bị gia dụng\",\"represents_company\":null,\"customer\":\"Công ty thiết bị gia dụng\",\"customer_address\":\"Công ty thiết bị gia dụng-Billing\",\"address_display\":\"Nam Từ Liêm<br>\\nHà Nội<br>\\nVietnam<br>\\n<br>\\n\",\"shipping_address_name\":\"Công ty thiết bị gia dụng-Billing\",\"shipping_address\":\"Nam Từ Liêm<br>\\nHà Nội<br>\\nVietnam<br>\\n<br>\\n\",\"tax_category\":\"\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"contact_phone\":null,\"customer_group\":null,\"territory\":null,\"payment_terms_template\":null,\"delivery_date\":\"2024-10-31\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370055552854108579951": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4387,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ValueError: math domain error",
	"exc_type": "ValueError",
	"_exc_source": "erpnext (app)",
	"_server_messages": "[\"{\\\"message\\\": \\\"Item Price added for M\\\\u00e1y t\\\\u00ednh in Price List Standard Selling\\\", \\\"title\\\": \\\"Message\\\", \\\"alert\\\": 1}\"]"
}
```
```

**Comment by Nihantra-Patel** [comment]
We tested in the frappe cloud and also in locally, we haven't found the issue in the dev version. we suggest checking with the stable version because every day lots of changes are added in the develop branch and we don't suggest a Live project in the dev branch.

[scrnli_Lo16MTUVqnM8vy.webm](https://github.com/user-attachments/assets/03444657-02b4-4278-b57d-09e6df537fcd)


Again update the version and check it.

First take a backup, if important data:

```
bench update --rest
bench --site sitename.com migrate
bench build --force
```

**Comment by rnd-nguyenth** [comment]
Hi @Nihantra-Patel,

Thanks for looking into this. I just want to explore the new version. Looking forward to the official release. Thanks again.
