### ISSUE TITLE
Purchase Order. Update Item Functionality throws error.

### ISSUE THREAD

**Issue by timeo-schmidt** [frappe/erpnext#43758]
### Information about bug

Hello!

I just found a bug in ERPNext, which I wanted to report.
To reproduce:
1. Create a sales order and submit
2. From the sales order Create > Purchase Order
3. Submit the new Purchase Order
4. On the purchase order > Update Items
5. Add a new item via the update items functionality
6. Afterwards via Update Items, try remove the newly created item.
7. This leads to the following exception:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 3324, in update_child_qty_rate
    _removed_items = validate_and_delete_children(parent, data)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 3203, in validate_and_delete_children
    parent.update_ordered_qty_in_so_for_removed_items(deleted_children)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 633, in update_ordered_qty_in_so_for_removed_items
    "Sales Order Item", item.get("sales_order_item"), "ordered_qty", prev_ordered_qty - item.qty
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

```

As far as I can tell, it is due to the incorrect assumption that a purchase order, which is created from a sales order has ALL items within linked to the sales order. This is not the case, if an item is added on the purchase order via the Update Items functionality.

### Module

buying

### Version

ERPNext: v15.38.1 (version-15)
Frappe Framework: v15.44.1 (version-15)

### Installation method

manual install

**Comment by bhavesh95863** [comment]
https://github.com/frappe/erpnext/pull/43762
