### ISSUE TITLE
Cannot Login due to Workspace Error

### ISSUE THREAD

**Issue by thorhat** [frappe/erpnext#43828]
### Information about bug

Please help, I don't know what I need to do. Suddenly, this happened after the update.

![error login](https://github.com/user-attachments/assets/142f5b55-fba2-46ee-8b0a-ff8a1fdc7b13)

### Module

other

### Version

erpnext 15.39.3
frappe 15.45.1
payments 0.0.1
print_designer 1.x.x-develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 30, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 142, in get
    bootinfo = get_bootinfo()
               ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/boot.py", line 55, in get_bootinfo
    load_desktop_data(bootinfo)
  File "apps/frappe/frappe/boot.py", line 147, in load_desktop_data
    bootinfo.module_wise_workspaces = get_controller("Workspace").get_module_wise_workspaces()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Document' has no attribute 'get_module_wise_workspaces'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 32, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed
```

**Comment by Savan120** [comment]
> ps aux | grep bench
> bench --site your-site-name set-maintenance-mode off
> bench --site your-site-name migrate (Bench must be running)

Use this command for this issue.

**Comment by thorhat** [comment]
> bench --site your-site-name set-maintenance-mode off

I tried that, but the error still persists.

**Comment by Savan120** [comment]
bench update Or bench update --reset
bench restart
bench clear-cache
bench build
bench migrate

Use this commands.

**Comment by thorhat** [comment]
> bench migrate

already tried, same error
