### ISSUE TITLE
TypeError: get_reference_details() takes 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by edkiefo** [frappe/erpnext#44143]
### Information about bug

I get this message everytime i click on Create > Payment . from any invoice page. and my error go like the following
### App Versions
```
{
	"ecommerce_integrations": "1.20.0",
	"erpnext": "14.65.1",
	"frappe": "14.67.1",
	"frappe_helper": "0.3.3",
	"hospitality": "0.0.1",
	"hrms": "16.0.0-dev",
	"payments": "0.0.1",
	"posawesome": "6.3.0",
	"restaurant_management": "1.3.7",
	"twilio_integration": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00241
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2111, in get_payment_entry
    pe.set_missing_ref_details()
  File "apps/hrms/hrms/overrides/employee_payment_entry.py", line 43, in set_missing_ref_details
    ref_details = get_payment_reference_details(
  File "apps/hrms/hrms/overrides/employee_payment_entry.py", line 214, in get_payment_reference_details
    return get_reference_details(
TypeError: get_reference_details() takes 3 positional arguments but 5 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"dt": "Purchase Invoice",
		"dn": "ACC-PINV-2024-00241"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_payment_entry"
}
```
### Response Data
```
{
	"exc_type": "DoesNotExistError",
	"exception": "TypeError: get_reference_details() takes 3 positional arguments but 5 were given"
}
```

### Module

accounts, buying

### Version

"erpnext": "14.65.1",
	"frappe": "14.67.1",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"ecommerce_integrations": "1.20.0",
	"erpnext": "14.65.1",
	"frappe": "14.67.1",
	"frappe_helper": "0.3.3",
	"hospitality": "0.0.1",
	"hrms": "16.0.0-dev",
	"payments": "0.0.1",
	"posawesome": "6.3.0",
	"restaurant_management": "1.3.7",
	"twilio_integration": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00241
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2111, in get_payment_entry
    pe.set_missing_ref_details()
  File "apps/hrms/hrms/overrides/employee_payment_entry.py", line 43, in set_missing_ref_details
    ref_details = get_payment_reference_details(
  File "apps/hrms/hrms/overrides/employee_payment_entry.py", line 214, in get_payment_reference_details
    return get_reference_details(
TypeError: get_reference_details() takes 3 positional arguments but 5 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"dt": "Purchase Invoice",
		"dn": "ACC-PINV-2024-00241"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_payment_entry"
}
```
### Response Data
```
{
	"exc_type": "DoesNotExistError",
	"exception": "TypeError: get_reference_details() takes 3 positional arguments but 5 were given"
}
```
```

**Comment by Nihantra-Patel** [comment]
This happened because you installed develop hrms, not version 14 hrms.

If you’ve installed ERPNext in version 14, make sure the hrms is also in version 14 to prevent errors.

We tested in the latest version 14 so we haven't found the issue.

[scrnli_NENN45b138KKyT.webm](https://github.com/user-attachments/assets/7d7b162a-28aa-4aab-817c-b33ba8d7dcc2)

**Comment by edkiefo** [comment]
I have upgraded hrms to V14.35.1...now, it has come up with a different error, everytime i try to make payment.
pymysql.err.OperationalError: (1054, "Unknown column 'outstanding_amount' in 'field list'")

### App Versions
```
{
	"ecommerce_integrations": "1.20.0",
	"erpnext": "14.75.1",
	"frappe": "14.67.1",
	"frappe_helper": "0.3.3",
	"hospitality": "0.0.1",
	"hrms": "14.35.1",
	"payments": "0.0.1",
	"posawesome": "6.3.0",
	"restaurant_management": "1.3.7",
	"twilio_integration": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/ACC-PINV-2024-00241
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2576, in get_payment_entry
    allocate_open_payment_requests_to_references(pe.references, pe.precision("paid_amount"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2660, in allocate_open_payment_requests_to_references
    references_open_payment_requests = get_open_payment_requests_for_references(references)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 2602, in get_open_payment_requests_for_references
    response = (
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 244, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'outstanding_amount' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"dt": "Purchase Invoice",
		"dn": "ACC-PINV-2024-00241"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.payment_entry.payment_entry.get_payment_entry"
}
```
### Response Data
```
{
	"exc_type": "DoesNotExistError",
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'outstanding_amount' in 'field list'\")"
}
```

Please help, many thanks in advance

**Comment by Nihantra-Patel** [comment]
Did you migrate and build an app because of the issue in the version? We tested multiple sites, but we haven’t replicated the issue. Please try on a new site.

**Comment by edkiefo** [comment]
Hello Nihantra, thanks for the migrate hint. I certainly needed to execute 
bench --site {site} migrate 
now it's smoothly working.
Question, is it normal to be consuming up 2.8GB RAM running only frappe, erpnext and some modules?
