### ISSUE TITLE
Hi @Spixmaster,

### ISSUE THREAD

**Issue by Nandani-20** [frappe/erpnext#44208]
Hi @Spixmaster,

Kindly upgrade to version 14 or 15, then refresh and check again.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!

_Originally posted by @Nihantra-Patel in https://github.com/frappe/erpnext/issues/36474#issuecomment-1997142481_
            

i'm using the erpnext v14 manual installation and facing this issue. After the successful payment, when redirecting to the payment success page, I'm facing this error

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/payments/payments/templates/pages/payment_success.py", line 10, in get_context
    doc = frappe.get_doc(frappe.local.form_dict.doctype, frappe.local.form_dict.docname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1346, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 75, in get_doc
    raise ValueError("First non keyword argument must be a string or dict")
ValueError: First non keyword argument must be a string or dict
![image](https://user-images.githubusercontent.com/171244053/387574861-3382f38b-1c9c-4a53-afe1-20713586a41f.png)

**Comment by Nandani-20** [comment]
![Uploading Screenshot 2024-11-19 143538.png…]()
