### ISSUE TITLE
ERPNext Payment Error

### ISSUE THREAD

**Issue by Nandani-20** [frappe/erpnext#44243]
### Information about bug

i'm using the erpnext v14 manual installation and facing this issue. After the successful payment, when redirecting to the payment success page, I'm facing this error.

After Looking into the code, I knew that in the payment_success.py file, frappe is trying to get the docname and doctype but unable to get this

![image](https://github.com/user-attachments/assets/39f922c6-e5e3-45d6-b00b-f950ff5eca2e)

i'm getting doctype and docname as none because form_dict only contains "redirect_to" field and due to this, error is occuring here

doc = frappe.get_doc(doctype, docname)

In the documentation, the only thing mentioned is to put the keys into the braintree settings to setup payment gateway and the payment is working successfully but not building the payment_success page only due to this error.

### Module

accounts, ecommerce

### Version

ERPNext: v14.76.0 (version-14)
Frappe Framework: v14.85.1 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
File "apps/frappe/frappe/website/serve.py", line 20, in get_response
response = renderer_instance.render()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
self.update_context()
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
data = self.run_pymodule_method("get_context")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
return method(self.context)
^^^^^^^^^^^^^^^^^^^^
File "apps/payments/payments/templates/pages/payment_success.py", line 10, in get_context
doc = frappe.get_doc(frappe.local.form_dict.doctype, frappe.local.form_dict.docname)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/init.py", line 1346, in get_doc
doc = frappe.model.document.get_doc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/model/document.py", line 75, in get_doc
raise ValueError("First non keyword argument must be a string or dict")
ValueError: First non keyword argument must be a string or dict
```

**Comment by ruthra-kumar** [comment]
@Nandani-20 

The code in the screenshot doesn't look like the standard **Payments** app. Also which version of the Payments app are you using.

**Comment by Nandani-20** [comment]
Payments: v0.0.1 (develop)

**Comment by ruthra-kumar** [comment]
Can you post the full replication steps

**Comment by Nandani-20** [comment]
![image](https://github.com/user-attachments/assets/480150e8-7bdf-4651-a237-411cf06351d5)

Braintree Settings

![image](https://github.com/user-attachments/assets/35b41c51-968d-4fca-a17e-9298f75baace)

This is payment gateway acccount

![image](https://github.com/user-attachments/assets/92afae45-ffed-4d7d-8dd3-e0ecc7c8f55c)

Here is payment gateway


The, I have added this payment gateway to ecommerce settings

![image](https://github.com/user-attachments/assets/bb5ac258-9baf-4d13-84e8-72b1e991ebfa)

This is the checkout page, till here things are going fine, when I will click on pay button then then payment will complete and also its logs will be shown to the braintree transaction but after its completion, when I get redirected to the payment _success page then error occured.

Behind the scene, payment request, sales order and other things are created

![image](https://github.com/user-attachments/assets/331623c9-f041-4985-bf1c-17b1c1c02c08)


![image](https://github.com/user-attachments/assets/2e189e7e-aab7-41bf-8a81-0d48cd27e2e4)

This is the error in payment success page

![image](https://github.com/user-attachments/assets/ba1bc0e5-dd4e-47f5-b059-d4ba3780ac8e)

**Comment by ruthra-kumar** [comment]
Since when did this issue started to occur?

**Comment by Nandani-20** [comment]
3 days ago
