### ISSUE TITLE
Updating Roles isn't possible

### ISSUE THREAD

**Issue by vogt31337** [frappe/erpnext#44310]
## Description of the issue

Hi trying to update a Role results in an error. Basically nothing happens, no sound nothing. Only way to "update" a role is by creating a new one.

## Context information (for bug reports)

I'am trying to give users a project user role so that they can book there times on their projects on their own. But updating a role fails horribly...

## Steps to reproduce the issue

1. Open Role list
2. Select a role
3. Change something
4. Try to save it

### Observed result

Nothing happens, no sound nothing. Even the save button doesn't change.

### Expected result

Updating the role, getting a sound and the dialog closes.

### Module

projects

### Version

erpnext 15.43.3
frappe 15.48.0
hrms 16.0.0-dev
nl_attendance_timesheet 0.0.1

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
### Stacktrace / full error message if available


XHRPOST
http://localhost:8080/api/method/frappe.desk.form.save.savedocs
[HTTP/1.1 417 EXPECTATION FAILED 16ms]

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 341, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 365, in _save
    self.check_if_locked()
  File "apps/frappe/frappe/model/document.py", line 337, in check_if_locked
    raise frappe.DocumentLockedError
frappe.exceptions.DocumentLockedError
request.js:473:14
    cleanup request.js:473
    cleanup request.js:471
    call request.js:325
    jQuery 6
    call request.js:279
    call request.js:109
    f save.js:246
    n save.js:23
    save save.js:273
    validate_and_save form.js:821
    (Async: promise callback)
    run_serially dom.js:262
    run_serially dom.js:260
    validate_and_save form.js:812
    save form.js:751
    save form.js:748
    Save toolbar.js:688
    set_action page.js:305
    jQuery 8
    set_action page.js:304
    set_primary_action page.js:319
    set_page_actions toolbar.js:705
    set_primary_action toolbar.js:618
    refresh toolbar.js:19
    refresh_header form.js:722
    render_form form.js:606
    (Async: promise callback)
    run_serially dom.js:262
    run_serially dom.js:260
    render_form form.js:603
    trigger_onload form.js:556
    refresh form.js:433
    render formview.js:107
    fetch_and_render formview.js:91
    with_doc model.js:316
    with_doc model.js:309
    fetch_and_render formview.js:80
    show_doc formview.js:75
    make formview.js:18
    show factory.js:25
    render_page router.js:326
    render router.js:305
    route router.js:157
    push_state router.js:503
    set_route router.js:379
    set_route router.js:368
    set_route router.js:579
    n router.js:46
    <anonym> router.js:78
    jQuery 2

```
```

**Comment by nabinhait** [comment]
Can't replicate the issue, please reopen it with screenshots, if you can replicate it on a clean (without any customization) frappecloud account.
