### ISSUE TITLE
Bug in asset. I couldn't save or submit in asset 

### ISSUE THREAD

**Issue by expert369** [frappe/erpnext#44454]
### Information about bug
After we've created purchase receipt for the item it automatically generate a document of assets but then from draft when I submit the document I have receive error.
 I am on the latest branch but still I have receive the error “Invalid Gross Purchase Amount” same as in our test site. Thank you
![image](https://github.com/user-attachments/assets/ab9929d9-56b8-44cb-903d-d64d7d66373a)
![image](https://github.com/user-attachments/assets/bf9a3fbb-91d8-4293-bfa3-9cf192a99309)
![image](https://github.com/user-attachments/assets/15bc5867-411b-4cc2-9c0c-23199a251d25)

### Module

other

### Version

Frappe Framework: v15.48.1 (HEAD)
ERPNext: v15.44.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 341, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 377, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1095, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 966, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1326, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1308, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 963, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 128, in validate
    self.validate_gross_and_purchase_amount()
  File "apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 374, in validate_gross_and_purchase_amount
    frappe.throw(error_message, title=_("Invalid Gross Purchase Amount"))
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Gross Purchase Amount should be <b>equal</b> to purchase amount of one single Asset.<br>Please do not book expense of multiple assets against one single Asset.
```

**Comment by MatthK** [comment]
I just came across the same error. I'm on Version 15.41.1.

Created a purchase order for 3 assets. The purchase order was in a different currency then the company currency. While creating the purchase receipt, 3 assets were automatically created. Now when I try to submit the draft assets, I get the same error message:

`Invalid Gross Purchase Amount
Gross Purchase Amount should be equal to purchase amount of one single Asset.
Please do not book expense of multiple assets against one single Asset.`

The Gross Purchase Amount is $5,449.64, while the Total Purchase Receipt amount is $16,348.93. I assume the small difference in the decimals is what triggers the error message, as the Gross Purchase Amount for one would be $5,449.6433333333

How to submit those assets?

**Comment by MatthK** [comment]
Ok, so I just deleted the automatically created drafts and created them manually. I could then submit the assets as expected, despite the small difference in the amount.

**Comment by expert369** [comment]
> Ok, so I just deleted the automatically created drafts and created them manually. I could then submit the assets as expected, despite the small difference in the amount.

Thank you for this, it is also one way to submit a document temporarily. But I've override the function that triggered the error and changed the frappe.throw to frappe.msgprint it provides a message but it doesn't stop you from saving, just temporarily.

**Comment by khushi8112** [comment]
Hello @expert369 

I have tried to replicate the issue but was unable to do so. Could you help me with the replication steps?

**Comment by expert369** [comment]
Hi @khushi8112 

So what I did to fix the issue is just override the method that is triggering the frappe throw
Step 1: Create a file for you override file ex.(override/override_asset.py)
Step 2: You're going to add basically the route in the hooks 
Example:
override_doctype_class = {
	"Asset": "erpnext.overrides.override_asset.CustomAsset",
}
Step 3: Add the method from erpnext which is "def validate_gross_and_purchase_amount(self):" and add your customize code there 
Example:
from erpnext.assets.doctype.asset.asset import Asset 

class CustomAsset(Asset):
       def validate_gross_and_purchase_amount
              //your script

Hope this would help
