### ISSUE TITLE
Opportunity not saving

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#44475]
### Information about bug

Steps:

1. Duplicated the Opportunity
2. Changed the Lead. 
3. Tried saving but got this error.
4. Change country and somehow Lead got saved.

<img width="1170" alt="Screenshot 2024-12-02 at 5 33 27 PM" src="https://github.com/user-attachments/assets/2eccf1ee-3856-47a7-9a46-1725b853d895">

### Module

CRM

### Version

V. 16

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
desk.js:116 Using this console may allow attackers to impersonate you and steal your information. Do not enter or paste code that you do not understand.
BaseChart.js:78 "" is not a valid color.
(anonymous) @ BaseChart.js:78Understand this warningAI
socketio_client.js:145 throttled
new-opportunity-qgxkeoamdr:1 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: button
Ancestor with aria-hidden:  <div class=​"modal fade" style=​"overflow:​ auto;​ display:​ none;​" tabindex=​"-1" aria-hidden=​"true">​…​</div>​Understand this errorAI
moment.js:287 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:3)
    at jn (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:24628)
    at mr (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28419)
    at Xi (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28284)
    at Ki (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28002)
    at Zn (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:28780)
    at Fe (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:4:112815)
    at Function.ne [as tz] (https://spindl16.frappe.cloud/assets/frappe/dist/js/libs.bundle.TIV7ZGVY.js:7:61602)
    at Object.convert_to_user_tz (https://spindl16.frappe.cloud/assets/frappe/dist/js/desk.bundle.BWT3JSG5.js:718:442)
    at sa (https://spindl16.frappe.cloud/assets/frappe/dist/js/desk.bundle.BWT3JSG5.js:712:4358)
ut @ moment.js:287Understand this warningAI
/api/method/frappe.desk.form.save.savedocs:1 
        
        
       Failed to load resource: the server responded with a status of 417 ()Understand this errorAI
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1808, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 293, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1117, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 969, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1352, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1330, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 966, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 121, in validate
    self.update_prospect()
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 185, in update_prospect
    prospect.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 375, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 937, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Row #1: Opportunity: CRM-OPP-2024-00002

(anonymous) @ request.js:473Understand this errorAI
/api/method/frappe.desk.form.save.savedocs:1 
        
        
       Failed to load resource: the server responded with a status of 417 ()Understand this errorAI
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1808, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 293, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1117, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 969, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1352, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1330, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 966, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 121, in validate
    self.update_prospect()
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 185, in update_prospect
    prospect.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 375, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 937, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Row #1: Opportunity: CRM-OPP-2024-00002

(anonymous) @ request.js:473Understand this errorAI
new-opportunity-qgxkeoamdr:1 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: div
Ancestor with aria-hidden:  <div class=​"modal fade" style=​"overflow:​ auto;​ z-index:​ 2000;​ display:​ none;​" tabindex=​"-1" aria-hidden=​"true">​…​</div>​Understand this errorAI
/api/method/frappe.desk.form.save.savedocs:1 
        
        
       Failed to load resource: the server responded with a status of 417 ()Understand this errorAI
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1808, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 293, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1117, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 969, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1352, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1330, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 966, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 121, in validate
    self.update_prospect()
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 185, in update_prospect
    prospect.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 375, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 937, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Row #1: Opportunity: CRM-OPP-2024-00002

(anonymous) @ request.js:473Understand this errorAI
/api/method/frappe.desk.form.save.savedocs:1 
        
        
       Failed to load resource: the server responded with a status of 417 ()Understand this errorAI
request.js:473 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1808, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 293, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1117, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 969, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1352, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1330, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 966, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 121, in validate
    self.update_prospect()
  File "apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 185, in update_prospect
    prospect.save()
  File "apps/frappe/frappe/model/document.py", line 340, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 375, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 937, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find Row #1: Opportunity: CRM-OPP-2024-00002
```

**Comment by iamejaaz** [comment]
Hi @umairsy 
Can't replicate this, Can you confirm if the issue still exists? If so, could you please share more details?
