### ISSUE TITLE
Debit and Credit Mismatch in Payment Entry (ERPNext V14)

### ISSUE THREAD

**Issue by CoderKal** [frappe/erpnext#44517]
### Information about bug

Summary: 
Submitting a Payment Entry where an employee is the party results in a debit-credit mismatch in the General Ledger. The GL posting logic doubles the posted amount, causing an imbalance error.

Affected Versions: ERPNext V14 (confirmed); not reproducible in V15.

Steps to Reproduce:
Create a Payment Entry where the party is an employee.
Submit the Payment Entry.
Observe the error: "Debit and Credit not equal for Payment Entry #XXXX. Difference is XXXX."

Root Cause:
Likely due to duplicated or incorrect GL entries in make_gl_entries or save_entries logic.

Solution: Fix GL posting logic to ensure debit and credit amounts match for Payment Entries. This issue is already resolved in V15.

### Module

accounts

### Version

ERPNext V14

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/model/workflow.py", line 133, in apply_workflow
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 999, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1101, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 102, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 1097, in make_gl_entries
    make_gl_entries(gl_entries, cancel=cancel, adv_adj=adv_adj)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 47, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 359, in save_entries
    process_debit_credit_difference(gl_map)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 432, in process_debit_credit_difference
    raise_debit_credit_not_equal_error(debit_credit_diff, voucher_type, voucher_no)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 469, in raise_debit_credit_not_equal_error
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 548, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 509, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 455, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Debit and Credit not equal for Payment Entry #2440PAY00008. Difference is 200000.0.

2440PAY00008:1 Uncaught (in promise) undefined
```

**Comment by diptanilsaha** [comment]
Please provide exact replication steps as I am not able to replicate this issue.

**Comment by diptanilsaha** [comment]
The issue is being closed due to a lack of response.
