### ISSUE TITLE
Work Order - Finishing Getting error ( Stock Entry ) Invalid "depends_on" expression

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#44624]
### Information about bug

Not able to finish the work order after updating the latest version

### Module

stock, manufacturing, regional

### Version

![Screenshot 2024-12-10 at 9 58 59 AM](https://github.com/user-attachments/assets/e8a48a3b-c75c-4632-ab33-7cc9aadcd7d5)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Ancestor with aria-hidden:  <div class=​"modal fade" style=​"overflow:​ auto;​ z-index:​ 2000;​ display:​ none;​" tabindex=​"-1" aria-hidden=​"true">​…​</div>​Understand this errorAI
utils.js:1086 let out =  india_compliance.is_e_waybill_applicable_for_subcontracting(doc); return out
eval @ utils.js:1086Understand this errorAI
messages.js:26 Uncaught (in promise) Error: Invalid "depends_on" expression
    at frappe.throw (messages.js:26:8)
    at frappe.ui.form.Layout.evaluate_depends_on_value (layout.js:785:12)
    at frappe.ui.form.Layout.refresh_dependency (layout.js:698:33)
    at frappe.ui.form.Layout.refresh (layout.js:349:8)
    at p.refresh_fields (form.js:667:15)
    at form.js:611:16
```

**Comment by dineshpanchal93** [comment]
@rohitwaghchaure Can you please look into the issue as work is being stopped
