### ISSUE TITLE
[v16] Error when converting Material Request into Purchase Order

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#44635]
### Information about bug

Steps:

1. Created Material Request
2. Trying to convert a MR into Purchase Order

<img width="669" alt="Screenshot 2024-11-27 at 3 18 04 PM" src="https://github.com/user-attachments/assets/1da75d1e-418e-4482-b4be-bc901dd14509">

### Module

buying

### Version

"erpnext": "16.0.0-dev",
	"frappe": "16.0.0-dev",
	"hrms": "16.0.0-dev",
	"india_compliance": "16.0.0-dev",
	"payments": "0.0.1"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "16.0.0-dev",
	"frappe": "16.0.0-dev",
	"hrms": "16.0.0-dev",
	"india_compliance": "16.0.0-dev",
	"payments": "0.0.1"
}
```
### Route
```
Form/Material Request/MAT-MR-2024-00346
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 118, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1812, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 37, in make_mapped_doc
    return method(source_name)
           ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 435, in make_purchase_order
    doclist = get_mapped_doc(
              ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 171, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 427, in postprocess
    set_missing_values(source, target_doc)
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 375, in set_missing_values
    target_doc.run_method("set_missing_values")
  File "apps/frappe/frappe/model/document.py", line 1069, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1456, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1434, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1066, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 662, in set_missing_values
    super().set_missing_values(for_validate)
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 149, in set_missing_values
    self.set_missing_item_details(for_validate)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 777, in set_missing_item_details
    ret = get_item_details(ctx, self, for_validate=for_validate, overwrite_warehouse=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/__init__.py", line 189, in wrapper
    return func(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 118, in get_item_details
    out.update(get_price_list_rate(ctx, item))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 862, in get_price_list_rate
    insert_item_price(ctx)
  File "apps/erpnext/erpnext/stock/get_item_details.py", line 928, in insert_item_price
    item_price.insert()
  File "apps/frappe/frappe/model/document.py", line 122, in wrapper
    raise frappe.DatabaseModificationError(error_msg)
frappe.exceptions.DatabaseModificationError: Cannot call insert in read-only document mode (doc-mapper)

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"method": "erpnext.stock.doctype.material_request.material_request.make_purchase_order",
		"source_name": "MAT-MR-2024-00346",
		"args": "{}",
		"selected_children": "{}"
	},
	"freeze": true,
	"freeze_message": "",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.mapper.make_mapped_doc",
	"request_id": "14497fe3-f2c5-4ec7-8980-eb39ca5ec77a"
}
```
### Response Data
```
{
	"exception": "frappe.exceptions.DatabaseModificationError: Cannot call insert in read-only document mode (doc-mapper)",
	"exc_type": "DatabaseModificationError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by blaggacao** [comment]
@ruthra-kumar is this legit that a price item would be _inserted_ into the database even **before** the mapping from one document into another would have been completed? &mdash; it feels very wrong, because we can't actually know without additional assumptions what the caller would do with the target document, at all. Maybe it's not meant for persistence.

**Comment by ruthra-kumar** [comment]
If 'Auto Insert Item Price If Missing' is enabled, Yes. You can disable it if not needed.

> it feels very wrong, because we can't actually know without additional assumptions what the caller would do with the target document, at all. Maybe it's not meant for persistence.

This is Quality-of-Life feature added upon users request, wherein system automatically creates a Price record without the need for user to manually create it first. And it is meant for persistence.

**Comment by ruthra-kumar** [comment]
@blaggacao 

I'm unclear on `DatabaseModificationError` exception. On which scenario is this thrown? Because based on the issue descripton, it looks like a normal sequence of actions where users are modifying and creating documents and the exception looks out-of-place.

**Comment by blaggacao** [comment]
The inner transaction span of what amounts to a type cast from one doctype to another (inside mapper control flow), i.e. the procedure of the type cast itself has been made read only, in order to add some sanity and soundness to the control flow, with the ulterior goal of avoiding intricate bugs due to complex state manipulations.

See: https://github.com/frappe/frappe/blob/develop/frappe%2Fmodel%2Fmapper.py#L106-L107

Note, that this didn't break any pre-existing automated tests across the ecosystem. I checked.

**Comment by blaggacao** [comment]
@ruthra-kumar Do you see a sane way to insert these records just after the mapping has finished so that the type cast itself can remain read-only? Maybe even by introducing a flag which holds "insert-suggestions" that would then be handled more transparently within the control flow of the caller.

Note, how the mapper only triggers `ret_doc.run_method("after_mapping", source_doc)` but never an insert on the target doc, so we can't presume actually persistence _within_ the context of the control flow of the mapper. Imo, that's a very good thing and all inserts should happen within the scope in which they can be presumed.

**Comment by yas8say** [comment]
Revert to [v15.44.0](https://github.com/frappe/erpnext/releases/tag/v15.44.0),
[v15.49.0](https://github.com/frappe/frappe/releases/tag/v15.49.0) & try again

**Comment by iamejaaz** [comment]
Closing this issue, it has been fixed.
