### ISSUE TITLE
Getting Error in Tally Migration During Day Book Import

### ISSUE THREAD

**Issue by sank8-2** [frappe/erpnext#44680]
### Information about bug

In the Tally Migration Tool, the Master Data gets imported successfully, but the Day Book gets processed and on clicking the Import Day Book button shows the error

### Module

integrations

### Version

Frappe Version - v15.50.0
ERPNext Version - v15.45.4

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Data:
"Importing Day Book Data"
----------------------------------------------------------------------------------------------------

Exception:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 554, in db_insert
    frappe.db.sql(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Tally Price List' for key 'PRIMARY'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 673, in _import_day_book_data
    create_price_list()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 650, in create_price_list
    ).insert()
      ^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 306, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 581, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Price List', 'Tally Price List', IntegrityError(1062, "Duplicate entry 'Tally Price List' for key 'PRIMARY'"))
```

**Comment by sank8-2** [comment]
```
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    retval = method(**kwargs)
      site = 'amiyasagar.frappe.cloud'
      method = <function run_doc_method at 0x7f89485432e0>
      event = None
      job_name = 'frappe.utils.background_jobs.run_doc_method'
      kwargs = {'doctype': 'Tally Migration', 'name': 'Tally Migration on 13-12-2024 09:38:35', 'doc_method': '_import_vouchers', 'start': 1, 'total': 1159, 'is_last': False}
      user = 'Administrator'
      is_async = True
      retry = 0
      retval = None
      method_name = 'frappe.utils.background_jobs.run_doc_method'
      before_job_task = 'frappe.monitor.start'
  File "apps/frappe/frappe/utils/background_jobs.py", line 186, in run_doc_method
    getattr(frappe.get_doc(doctype, name), doc_method)(**kwargs)
      doctype = 'Tally Migration'
      name = 'Tally Migration on 13-12-2024 09:38:35'
      doc_method = '_import_vouchers'
      kwargs = {'start': 1, 'total': 1159, 'is_last': False}
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 714, in _import_vouchers
    self.log(voucher_doc)
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      start = 1
      total = 1159
      is_last = False
      vouchers_file = <File: acbab01a07>
      vouchers = [{'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013b1', 'tally_voucher_no': 'SK/23-24/01', 'posting_date': '20230401', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Sundry Debtors - SKL', 'cost_center': 'Main - SKL', 'party_type': 'Customer', 'party': 'Custom Capsules Private Limited', 'debit_in_account_currency': '82600.00'}, {'account': 'Testing Charges - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '70000.00'}, {'account': 'Output CGST @ 9% - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '6300.00'}, {'account': 'Output SGST @ 9% - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '6300.00'}]}, {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013cf', 'tally_voucher_no': '1', 'posting_date': '20230402', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Petrol  Deisel - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '3068...
      chunk = [{'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013cf', 'tally_voucher_no': '1', 'posting_date': '20230402', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Petrol  Deisel - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '3068.93', 'doctype': 'Journal Entry Account'}, {'account': 'Yes Bank A/c 041261900000424 - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '3068.93', 'doctype': 'Journal Entry Account'}]}, {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013d0', 'tally_voucher_no': '2', 'posting_date': '20230402', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Staff Welfare - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '1481.00', 'doctype': 'Journal Entry Account'}, {'account': 'Yes Bank A/c 041261900000424 - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '1481.00', 'doctype': 'Journal Entry Account'}]}, {'doctype': 'J...
      index = 3
      voucher = {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013e6', 'tally_voucher_no': '3', 'posting_date': '20230402', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Printing  Stationery - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '610.00', 'doctype': 'Journal Entry Account'}, {'account': 'Cash - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '610.00', 'doctype': 'Journal Entry Account'}]}
      voucher_doc = <JournalEntry: unsaved>
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 750, in log
    self.save()
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      data = <JournalEntry: unsaved>
      failed_import_log = [{'doc': {'name': None, 'owner': 'Administrator', 'creation': None, 'modified': '2024-12-13 10:02:39.050047', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'tally_voucher_no': '1', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013cf', 'is_system_generated': 0, 'title': None, 'voucher_type': 'Journal Entry', 'naming_series': 'ACC-JV-.YYYY.-', 'finance_book': None, 'process_deferred_accounting': None, 'reversal_of': None, 'tax_withholding_category': None, 'from_template': None, 'company': 'Swen Konformity LLP', 'posting_date': '20230402', 'apply_tds': 0, 'cheque_no': None, 'cheque_date': None, 'user_remark': None, 'total_debit': 0.0, 'total_credit': 0.0, 'difference': 0.0, 'multi_currency': 0, 'total_amount_currency': None, 'total_amount': 0.0, 'total_amount_in_words': None, 'clearance_date': None, 'remark': None, 'paid_loan': None, 'inter_company_journal_entry_reference': None, 'bill_no': None, 'bill_date': None, 'due_date': None, 'write_off_based_on': 'Accounts Rec...
      doc = {'name': None, 'owner': 'Administrator', 'creation': None, 'modified': '2024-12-13 10:02:39.486598', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'tally_voucher_no': '3', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013e6', 'is_system_generated': 0, 'title': None, 'voucher_type': 'Journal Entry', 'naming_series': 'ACC-JV-.YYYY.-', 'finance_book': None, 'process_deferred_accounting': None, 'reversal_of': None, 'tax_withholding_category': None, 'from_template': None, 'company': 'Swen Konformity LLP', 'posting_date': '20230402', 'apply_tds': 0, 'cheque_no': None, 'cheque_date': None, 'user_remark': None, 'total_debit': 0.0, 'total_credit': 0.0, 'difference': 0.0, 'multi_currency': 0, 'total_amount_currency': None, 'total_amount': 0.0, 'total_amount_in_words': None, 'clearance_date': None, 'remark': None, 'paid_loan': None, 'inter_company_journal_entry_reference': None, 'bill_no': None, 'bill_date': None, 'due_date': None, 'write_off_based_on': 'Accounts Receivable',...
  File "apps/frappe/frappe/model/document.py", line 342, in save
    return self._save(*args, **kwargs)
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      args = ()
      kwargs = {}
  File "apps/frappe/frappe/model/document.py", line 378, in _save
    self.run_before_save_methods()
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      ignore_permissions = None
      ignore_version = None
  File "apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      method = 'validate'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f893e24ede0>
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      args = ()
      kwargs = {}
      hooks = [<function apply at 0x7f893e588b80>, <function check_for_running_deletion_job at 0x7f893e58a7a0>]
      method = 'validate'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      handler = 'erpnext.setup.doctype.transaction_deletion_record.transaction_deletion_record.check_for_running_deletion_job'
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f893e305940>
      compose = <function Document.hook.<locals>.compose at 0x7f893e265e40>
      f = <function Document.run_method.<locals>.fn at 0x7f893e24ede0>
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      method = 'validate'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f893e265ee0>
      fn = <function Document.run_method.<locals>.fn at 0x7f893e24ede0>
      hooks = (<function apply at 0x7f893e588b80>, <function check_for_running_deletion_job at 0x7f893e58a7a0>)
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      args = ()
      kwargs = {}
      method_object = <bound method TallyMigration.validate of <TallyMigration: Tally Migration on 13-12-2024 09:38:35>>
      method = 'validate'
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 78, in validate
    sorted_failed_import_log = sorted(failed_import_log, key=lambda row: row["doc"]["creation"])
      self = <TallyMigration: Tally Migration on 13-12-2024 09:38:35>
      failed_import_log = [{'doc': {'name': None, 'owner': 'Administrator', 'creation': None, 'modified': '2024-12-13 10:02:39.050047', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'tally_voucher_no': '1', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013cf', 'is_system_generated': 0, 'title': None, 'voucher_type': 'Journal Entry', 'naming_series': 'ACC-JV-.YYYY.-', 'finance_book': None, 'process_deferred_accounting': None, 'reversal_of': None, 'tax_withholding_category': None, 'from_template': None, 'company': 'Swen Konformity LLP', 'posting_date': '20230402', 'apply_tds': 0, 'cheque_no': None, 'cheque_date': None, 'user_remark': None, 'total_debit': 0.0, 'total_credit': 0.0, 'difference': 0.0, 'multi_currency': 0, 'total_amount_currency': None, 'total_amount': 0.0, 'total_amount_in_words': None, 'clearance_date': None, 'remark': None, 'paid_loan': None, 'inter_company_journal_entry_reference': None, 'bill_no': None, 'bill_date': None, 'due_date': None, 'write_off_based_on': 'Accounts Rec...
builtins.TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by sank8-2** [comment]
```
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    retval = method(**kwargs)
      site = 'amiyasagar.frappe.cloud'
      method = <function run_doc_method at 0x7f7930dd32e0>
      event = None
      job_name = 'frappe.utils.background_jobs.run_doc_method'
      kwargs = {'doctype': 'Tally Migration', 'name': 'Tally Migration on 29-11-2024 12:16:19', 'doc_method': '_import_vouchers', 'start': 501, 'total': 1159, 'is_last': False}
      user = 'Administrator'
      is_async = True
      retry = 0
      retval = None
      method_name = 'frappe.utils.background_jobs.run_doc_method'
      before_job_task = 'frappe.monitor.start'
  File "apps/frappe/frappe/utils/background_jobs.py", line 186, in run_doc_method
    getattr(frappe.get_doc(doctype, name), doc_method)(**kwargs)
      doctype = 'Tally Migration'
      name = 'Tally Migration on 29-11-2024 12:16:19'
      doc_method = '_import_vouchers'
      kwargs = {'start': 501, 'total': 1159, 'is_last': False}
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 714, in _import_vouchers
    self.log(voucher_doc)
      self = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
      start = 501
      total = 1159
      is_last = False
      vouchers_file = <File: 0434630086>
      vouchers = [{'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013b1', 'tally_voucher_no': 'SK/23-24/01', 'posting_date': '20230401', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Sundry Debtors - SKL', 'cost_center': 'Main - SKL', 'party_type': 'Customer', 'party': 'Custom Capsules Private Limited', 'debit_in_account_currency': '82600.00'}, {'account': 'Testing Charges - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '70000.00'}, {'account': 'Output CGST @ 9% - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '6300.00'}, {'account': 'Output SGST @ 9% - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '6300.00'}]}, {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000013cf', 'tally_voucher_no': '1', 'posting_date': '20230402', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Petrol  Deisel - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '3068...
      chunk = [{'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-0000155d', 'tally_voucher_no': '248', 'posting_date': '20230907', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'TDS on Professional Fees - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '1100.00', 'doctype': 'Journal Entry Account'}, {'account': 'ICICI Bank  - 336805000003 - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '1100.00', 'doctype': 'Journal Entry Account'}]}, {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000015a2', 'tally_voucher_no': 'AAFEE/3927/23-24', 'posting_date': '20230907', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Sundry Creditors - SKL', 'cost_center': 'Main - SKL', 'party_type': 'Supplier', 'party': 'Quality Council of India', 'credit_in_account_currency': '51840.00', 'doctype': 'Journal Entry Account'}, {'account': 'Techinical Service  Fees - SKL', 'cost_center': 'Main - SKL', 'debi...
      index = 502
      voucher = {'doctype': 'Journal Entry', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000015a2', 'tally_voucher_no': 'AAFEE/3927/23-24', 'posting_date': '20230907', 'company': 'Swen Konformity LLP', 'accounts': [{'account': 'Sundry Creditors - SKL', 'cost_center': 'Main - SKL', 'party_type': 'Supplier', 'party': 'Quality Council of India', 'credit_in_account_currency': '51840.00', 'doctype': 'Journal Entry Account'}, {'account': 'Techinical Service  Fees - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '48000.00', 'doctype': 'Journal Entry Account'}, {'account': 'Input IGST @ 18% - SKL', 'cost_center': 'Main - SKL', 'debit_in_account_currency': '8640.00', 'doctype': 'Journal Entry Account'}, {'account': 'TDS on Professional Fees - SKL', 'cost_center': 'Main - SKL', 'credit_in_account_currency': '4800.00', 'doctype': 'Journal Entry Account'}]}
      voucher_doc = <JournalEntry: unsaved>
  File "apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 750, in log
    self.save()
      self = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
      data = <JournalEntry: unsaved>
      failed_import_log = [{'doc': {'name': None, 'owner': 'Administrator', 'creation': None, 'modified': '2024-12-13 10:25:27.957047', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'tally_voucher_no': 'AAFEE/3927/23-24', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000015a2', 'is_system_generated': 0, 'title': None, 'voucher_type': 'Journal Entry', 'naming_series': 'ACC-JV-.YYYY.-', 'finance_book': None, 'process_deferred_accounting': None, 'reversal_of': None, 'tax_withholding_category': None, 'from_template': None, 'company': 'Swen Konformity LLP', 'posting_date': '20230907', 'apply_tds': 0, 'cheque_no': None, 'cheque_date': None, 'user_remark': None, 'total_debit': 0.0, 'total_credit': 0.0, 'difference': 0.0, 'multi_currency': 0, 'total_amount_currency': None, 'total_amount': 0.0, 'total_amount_in_words': None, 'clearance_date': None, 'remark': None, 'paid_loan': None, 'inter_company_journal_entry_reference': None, 'bill_no': None, 'bill_date': None, 'due_date': None, 'write_off_based_on'...
      doc = {'name': None, 'owner': 'Administrator', 'creation': None, 'modified': '2024-12-13 10:25:27.957047', 'modified_by': 'Administrator', 'docstatus': 0, 'idx': 0, 'tally_voucher_no': 'AAFEE/3927/23-24', 'tally_guid': 'f293ba3c-54da-4fdd-99e7-cf46bbe4be14-000015a2', 'is_system_generated': 0, 'title': None, 'voucher_type': 'Journal Entry', 'naming_series': 'ACC-JV-.YYYY.-', 'finance_book': None, 'process_deferred_accounting': None, 'reversal_of': None, 'tax_withholding_category': None, 'from_template': None, 'company': 'Swen Konformity LLP', 'posting_date': '20230907', 'apply_tds': 0, 'cheque_no': None, 'cheque_date': None, 'user_remark': None, 'total_debit': 0.0, 'total_credit': 0.0, 'difference': 0.0, 'multi_currency': 0, 'total_amount_currency': None, 'total_amount': 0.0, 'total_amount_in_words': None, 'clearance_date': None, 'remark': None, 'paid_loan': None, 'inter_company_journal_entry_reference': None, 'bill_no': None, 'bill_date': None, 'due_date': None, 'write_off_based_on': 'Accoun...
  File "apps/frappe/frappe/model/document.py", line 342, in save
    return self._save(*args, **kwargs)
      self = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
      args = ()
      kwargs = {}
  File "apps/frappe/frappe/model/document.py", line 372, in _save
    self.check_if_latest()
      self = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
      ignore_permissions = None
      ignore_version = None
  File "apps/frappe/frappe/model/document.py", line 827, in check_if_latest
    frappe.msgprint(
      self = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
      previous = <TallyMigration: Tally Migration on 29-11-2024 12:16:19>
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
      msg = 'Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.'
      title = None
      raise_exception = <class 'frappe.exceptions.TimestampMismatchError'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      sys = <module 'sys' (built-in)>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7f7932a6a3e0>
      inspect = <module 'inspect' from '/usr/lib/python3.11/inspect.py'>
      out = {'message': 'Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1950e66a485a6bbbce7eafad124f3b23120ab58fa383d9fbcc26435b'}
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
      exc = TimestampMismatchError('Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.')
      inspect = <module 'inspect' from '/usr/lib/python3.11/inspect.py'>
      msg = 'Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.'
      out = {'message': 'Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1950e66a485a6bbbce7eafad124f3b23120ab58fa383d9fbcc26435b'}
      raise_exception = <class 'frappe.exceptions.TimestampMismatchError'>
frappe.exceptions.TimestampMismatchError: Error: Document has been modified after you have opened it (2024-12-13 10:25:27.803618, 2024-12-13 10:25:27.963170). Please refresh to get the latest document.
```

**Comment by nabinhait** [comment]
We have removed Tally Migration in the latest version, closing the issue.
