### ISSUE TITLE
Error when open Asset Item. No tabs are loaded

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#44937]
### Information about bug

1. Filter Fixed Asset item
2. Open any item

Frappe team can replicate in the same site as mentioned below.

<img width="1158" alt="Screenshot 2024-12-27 at 3 13 21 PM" src="https://github.com/user-attachments/assets/e7833b18-3435-4c0b-9769-f72ff92eba77" />

### Module

stock

### Version

V16

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
utils.js:1078 let out = gst_settings.validate_hsn_code && doc.is_sales_item; return out
eval @ utils.js:1078Understand this errorAI
script_manager.js:32 ƒ (frm, asset_naming_series) {
		if ((frm.doc.__onload && frm.doc.__onload.asset_naming_series) || asset_naming_series) {
			let naming_series =
				(frm.doc.__onload && frm.doc.__onload.asset_naming_s…
d @ script_manager.js:32Understand this errorAI
script_manager.js:32 ƒ (frm) {
		india_compliance.set_hsn_code_query(frm.get_field("gst_hsn_code"));
	}
d @ script_manager.js:32Understand this errorAI
utils.js:1077 Error evaluating the following expression:
utils.js:1078 let out = gst_settings.validate_hsn_code && doc.is_sales_item; return out
eval @ utils.js:1078Understand this errorAI
messages.js:26 Uncaught (in promise) Error: Invalid "depends_on" expression
    at frappe.throw (messages.js:26:8)
    at frappe.ui.form.Layout.evaluate_depends_on_value (layout.js:795:12)
    at frappe.ui.form.Layout.set_dependant_property (layout.js:741:27)
    at frappe.ui.form.Layout.refresh_dependency (layout.js:725:10)
    at frappe.ui.form.Form.refresh_field (form.js:1408:16)
    at frappe.ui.form.Form.set_df_property (form.js:1650:10)
    at frappe.ui.form.Layout.set_dependant_property (layout.js:765:14)
    at frappe.ui.form.Layout.refresh_dependency (layout.js:725:10)
    at frappe.ui.form.Form.refresh_field (form.js:1408:16)
    at frappe.ui.form.Form.set_df_property (form.js:1650:10)Understand this errorAI
item__js:1027 Uncaught (in promise) ReferenceError: india_compliance is not defined
    at onload (item__js:1027:3)
    at d (script_manager.js:30:12)
    at n (script_manager.js:109:16)
    at script_manager.js:127:22Understand this errorAI
messages.js:26 Uncaught (in promise) Error: Invalid "depends_on" expression
    at frappe.throw (messages.js:26:8)
    at frappe.ui.form.Layout.evaluate_depends_on_value (layout.js:795:12)
    at frappe.ui.form.Layout.set_dependant_property (layout.js:741:27)
    at frappe.ui.form.Layout.refresh_dependency (layout.js:725:10)
    at frappe.ui.form.Layout.refresh (layout.js:351:8)
    at frappe.ui.form.Form.refresh_fields (form.js:687:15)
    at form.js:626:16
```

**Comment by umairsy** [comment]
@sokumon thanks for the fixes. In this case, was there any fix required?

**Comment by sokumon** [comment]
@umairsy no it was due to something which was fixed earlier
