### ISSUE TITLE
issue with bench version

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4719]
As I typed bench version, I got this error.

```
franky1@Capfresh:~$ bench version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 983, in get_version
    frappe.init(site=context.sites[0])
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 124, in init
    local.conf = _dict(get_site_config())
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 178, in get_site_config
    raise IncorrectSitePath, "{0} does not exist".format(site_config)
frappe.exceptions.IncorrectSitePath: ./site1.local/site_config.json does not exist
```

What am I missing in my site_config.json?

**Comment by anandpdoshi** [comment]
You need to run bench command from frappe-bench folder

**Comment by fderyckel** [comment]
Hi Anand, 
I did that and I got the same error.

```
franky1@Capfresh:~/frappe-bench$ bench version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/commands.py", line 983, in get_version
    frappe.init(site=context.sites[0])
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 124, in init
    local.conf = _dict(get_site_config())
  File "/home/franky1/frappe-bench/apps/frappe/frappe/__init__.py", line 178, in get_site_config
    raise IncorrectSitePath, "{0} does not exist".format(site_config)
frappe.exceptions.IncorrectSitePath: ./site1.local/site_config.json does not exist
franky1@Capfresh:~/frappe-bench$ 
```

**Comment by anandpdoshi** [comment]
I think this was fixed. Can you update and check?
