### ISSUE TITLE
Cannot allocate memory (1 GB Memory / 30 GB Disk / SGP1)

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4988]
[root@123 ~]# bench update
INFO:bench.utils:setting up sudoers
Already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mandrill_integration
From https://github.com/frappe/mandrill_integration
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mankem
From https://github.com/sbktechnology/mankem
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
  Error [Errno 12] Cannot allocate memory while executing command git config --get-regexp remote\..*\.url
Exception:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_set.py", line 477, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/req/req_install.py", line 578, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/vcs/git.py", line 120, in obtain
    if self.check_destination(dest, url, rev_options, rev_display):
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/vcs/__init__.py", line 205, in check_destination
    existing_url = self.get_url(dest)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/vcs/git.py", line 141, in get_url
    show_stdout=False, cwd=location)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/vcs/__init__.py", line 322, in run_command
    spinner)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/utils/__init__.py", line 678, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1205, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/cli.py", line 241, in _update
    update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/cli.py", line 259, in update
    update_requirements(bench=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 361, in update_requirements
    exec_cmd("{pip} install -q -r {req_file}".format(pip=pip, req_file=req_file))
  File "/home/frappe/bench-repo/bench/utils.py", line 105, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q -r ./apps/frappe/requirements.txt
[root@123 ~]#

**Comment by anandpdoshi** [comment]
You will need to setup swap. Some of the installation steps need more memory.
