### ISSUE TITLE
bench update error

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5083]
my server in digitalocean: 
ERPNext
1 GB Memory / 30 GB Disk / SGP1 - CentOS 6
1.i using `bench update`, and faced error, 
2.and i using `sudo yum install libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel` 
3.and i using `bench update` again, and still error happen.

please check:
`
[root@123 ~]# bench update
INFO:bench.utils:updating bench
Already up-to-date.
Traceback (most recent call last):
  File "./env/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/home/frappe/frappe-bench/env/lib64/python2.7/locale.py", line 547, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Please install these dependencies using the command:
sudo yum install libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 73, in _update
    before_update(bench=bench_path, requirements=requirements)
  File "/home/frappe/bench-repo/bench/utils.py", line 583, in before_update
    validate_pillow_dependencies(bench, requirements)
  File "/home/frappe/bench-repo/bench/utils.py", line 591, in validate_pillow_dependencies
    exec_cmd("{pip} install Pillow".format(pip=pip))
  File "/home/frappe/bench-repo/bench/utils.py", line 99, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install Pillow
[root@123 ~]# 
`

**Comment by omnison** [comment]
i try ti install pillow,but failed also
`[root@123 ~]# pip install -I pillow
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib64/python2.7/locale.py", line 547, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting`

**Comment by anandpdoshi** [comment]
This is a bug in pip. Try if an answer here helps: https://github.com/pypa/pip/issues/3575

**Comment by omnison** [comment]
yes. i fixed with `localedef -v -c -i en_US -f UTF-8 en_US.UTF-8`

**Comment by omnison** [comment]
`[root@123 ~]# bench update
INFO:bench.utils:updating bench
Already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mandrill_integration
From https://github.com/frappe/mandrill_integration
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mankem
From https://github.com/sbktechnology/mankem
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Migrating site1.local
Updating frappe                     : [========================================]
Updating erpnext                    : [========================================]
Updating mandrill_integration       : [========================================]
Wrote ./assets/js/print_format_v3.min.js - 18k
Wrote ./assets/js/frappe-web.min.js - 101k
Wrote ./assets/js/form.min.js - 113k
Wrote ./assets/js/report.min.js - 157k
Wrote ./assets/js/erpnext.min.js - 35k
Wrote ./assets/css/list.min.css - 6k
Wrote ./assets/js/erpnext-web.min.js - 1k
Wrote ./assets/css/report.min.css - 7k
Wrote ./assets/css/frappe-web.css - 51k
Wrote ./assets/js/list.min.js - 67k
Wrote ./assets/js/dialog.min.js - 58k
Wrote ./assets/js/desk.min.js - 875k
Wrote ./assets/css/form.min.css - 2k
Wrote ./assets/js/editor.min.js - 26k
Wrote ./assets/css/erpnext.css - 1k
Wrote ./assets/css/desk.min.css - 257k
Wrote ./assets/css/module.min.css - 2k
[sudo] password for frappe: `

when i input password here.

`Sorry, user frappe is not allowed to execute '/bin/supervisorctl restart frappe-bench-processes:' as root on 123.
error: <class 'xmlrpclib.Fault'>, <Fault 10: 'BAD_NAME: frappe'>: file: /usr/lib64/python2.7/xmlrpclib.py line: 794
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 96, in _update
    restart_supervisor_processes(bench=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 273, in restart_supervisor_processes
    exec_cmd('sudo supervisorctl restart frappe:', cwd=bench)
  File "/home/frappe/bench-repo/bench/utils.py", line 99, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: sudo supervisorctl restart frappe:
[root@123 ~]# sudo supervisorctl restart frappe:
error: <class 'xmlrpclib.Fault'>, <Fault 10: 'BAD_NAME: frappe'>: file: /usr/lib64/python2.7/xmlrpclib.py line: 794
[root@123 ~]# `

**Comment by omnison** [comment]
yes again, i solved to folow your previous code `bench setup sudoers frappe`

**Comment by sbkolate** [comment]
I am installing ERPNext on ubuntu 14.04
I got same error and solved using `sudo apt-get install --reinstall language-pack-en`

**Comment by emotilla** [comment]
# I'm getting this error while trying to update erpnext (version 8 and 9)

frappe@erp-instance3:/root$ bench update
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 30, in update
    patches.run(bench_path='.')
  File "/home/frappe/.bench/bench/patches/__init__.py", line 27, in run
    with open(target_patch_file, 'w') as f:
IOError: [Errno 13] Permission denied: '/root/patches.txt'
