### ISSUE TITLE
bench init frappe-bench fails!

### ISSUE THREAD

**Issue by zenny** [frappe/erpnext#5161]
Trying to build erpnext in pursuant to https://github.com/frappe/bench#production-deployment in alpine linux 3.3. Mariadb with reconfigured cnf and redis are running as per instructions at https://github.com/frappe/bench/wiki/Install-ERPNext-on-ArchLinux

But stuck with the following error:

```
$ bench init frappe-bench
Already using interpreter /usr/bin/python
INFO:bench.app:getting app frappe
Cloning into 'frappe'...
remote: Counting objects: 1591, done.
remote: Compressing objects: 100% (1466/1466), done.
remote: Total 1591 (delta 197), reused 645 (delta 75), pack-reused 0
Receiving objects: 100% (1591/1591), 9.80 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (197/197), done.
Checking connectivity... done.
installing frappe
INFO:bench.app:installing frappe
Command "/home/zenny/frappe-bench/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-YeMJgl/mysql-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LsGmUa-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/zenny/frappe-bench/env/include/site/python2.7/mysql-python" failed with error code 1 in /tmp/pip-build-YeMJgl/mysql-python/
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/zenny/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/zenny/bench-repo/bench/commands/make.py", line 17, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch, verbose=verbose)
  File "/home/zenny/bench-repo/bench/utils.py", line 62, in init
    get_app('frappe', frappe_path, branch=frappe_branch, bench=path, build_asset_files=False, verbose=verbose)
  File "/home/zenny/bench-repo/bench/app.py", line 56, in get_app
    install_app(app, bench=bench, verbose=verbose)
  File "/home/zenny/bench-repo/bench/app.py", line 82, in install_app
    find_links=find_links))
  File "/home/zenny/bench-repo/bench/utils.py", line 99, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
```

```
$ bench get-app erpnext https://github.com/frappe/erpnext
INFO:bench.app:getting app erpnext
Cloning into 'erpnext'...
remote: Counting objects: 3667, done.
remote: Compressing objects: 100% (3232/3232), done.
remote: Total 3667 (delta 545), reused 2134 (delta 310), pack-reused 0
Receiving objects: 100% (3667/3667), 76.29 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (545/545), done.
Checking connectivity... done.
installing erpnext
INFO:bench.app:installing erpnext
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fGdfsx/frappe/
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/zenny/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/zenny/bench-repo/bench/commands/make.py", line 28, in get_app
    get_app(name, git_url, branch=branch)
  File "/home/zenny/bench-repo/bench/app.py", line 56, in get_app
    install_app(app, bench=bench, verbose=verbose)
  File "/home/zenny/bench-repo/bench/app.py", line 82, in install_app
    find_links=find_links))
  File "/home/zenny/bench-repo/bench/utils.py", line 99, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q  -e ./apps/erpnext
```

UPDATE: I have tried with installing mariadb-dev and mariadb-bench packages, but the problem persists.

**Comment by vjFaLk** [comment]
Hi, can you post this over at https://discuss.erpnext.com/

You're more likely to get help there.

**Comment by zenny** [comment]
> Hi, can you post this over at https://discuss.erpnext.com/
> 
> You're more likely to get help there.

@vjFaLk: Thanks and already posted at https://discuss.erpnext.com/t/errors-with-bench-init/11676

**Comment by zenny** [comment]
@anandpdoshi I do not know why this unresolved issue is closed. There is no resolution found to this problem despite your inputs (See https://discuss.erpnext.com/t/errors-with-bench-init/11676/13?u=zenny)

**Comment by vjFaLk** [comment]
@zenny Usually technical issues are posted and discussed over at https:/discuss.erpnext.com

Which is why I asked you to post there in the first place . Github Issues is for bugs and feature requests. 

Hope you understand.

**Comment by zenny** [comment]
@vjFaLk This seems to be very bug pertaining to alpinelinux. It is important in the pretext that docker is moving officially to alpinelinux (https://www.brianchristner.io/docker-is-moving-to-alpine-linux/).
