### ISSUE TITLE
ERPNext Demo is not working

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#5200]
In develop : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vjfalk/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/commands.py", line 176, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/installer.py", line 136, in install_app
    frappe.get_attr(after_install)()
  File "/home/vjfalk/frappe-bench/apps/erpnext_demo/erpnext_demo/utils.py", line 31, in make_demo
    erpnext_demo.make_demo.make()
  File "/home/vjfalk/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 18, in make
    setup()
  File "/home/vjfalk/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 26, in setup
    make_items()
  File "/home/vjfalk/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 101, in make_items
    import_data("BOM", submit=True)
  File "/home/vjfalk/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 153, in import_data
    import_doc(get_json_path(doctype), submit=submit, overwrite=overwrite)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/data_import_tool.py", line 90, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import, pre_process=pre_process)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 122, in import_doc
    doc.insert()
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 194, in insert
    self.run_before_save_methods()
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 630, in run_before_save_methods
    self.run_method("validate")
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 588, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 582, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/vjfalk/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 43, in validate
    self.validate_materials()
  File "/home/vjfalk/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 223, in validate_materials
    validate_bom_no(m.item_code, m.bom_no)
  File "/home/vjfalk/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 434, in validate_bom_no
    bom = frappe.get_doc("BOM", bom_no)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/__init__.py", line 533, in get_doc
    return frappe.model.document.get_doc(arg1, arg2)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 46, in get_doc
    return controller(arg1, arg2)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 79, in __init__
    self.load_from_db()
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/model/document.py", line 110, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/__init__.py", line 264, in throw
    msgprint(msg, raise_exception=exc)
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/__init__.py", line 257, in msgprint
    _raise_exception()
  File "/home/vjfalk/frappe-bench/apps/frappe/frappe/__init__.py", line 242, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.DoesNotExistError: BOM BOM/Bearing Assembly/001 not found
```

**Comment by anandpdoshi** [comment]
master was fixed long time back via force push!

Try a reset hard. And, use master in conjunction with master branches of erpnext/frappe. Similarly for develop. Then you should get a different error :P


Best,
Anand Doshi

ERPNext

**Comment by vjFaLk** [comment]
Ah, my master branch wasn't being tracked with upstream, it was on develop.

**Comment by vjFaLk** [comment]
Are bhai, develop is still broken :P

**Comment by rmehta** [comment]
Raise the issue in erpnext_demo :P
