### ISSUE TITLE
Data import fails on `set_only_once` fields

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#52290]
## Description of the issue

I'm trying to import ERPNext **Subscriptions** with **Data Import** Tool.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.16.1 (version-13)
Frappe Framework: v13.16.0 (version-13)
```

## Steps to reproduce the issue

1. Enable "Allow Data Import" for **Subscription**
2. Create a new **Data import**
3. Download a Template for the following fields:

Party Type | Party | Subscription Start Date | Company | Submit Invoice Automatically | Sales Taxes and Charges Template | Generate New Invoices Past Due Date | Plan (Plans) | Quantity (Plans)
-- | -- | -- | -- | -- | -- | -- | -- | -- 

4. Add some data (with child table rows)
5. Import

### Observed result

Subscriptions won't get imported, errors for every row.

### Expected result

Subscriptions get imported correctly.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 126, in import_data
    doc = self.process_doc(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 194, in process_doc
    return self.insert_record(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 213, in insert_record
    new_doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_method("after_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1158, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1141, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/subscription/subscription.py", line 311, in after_insert
    self.set_subscription_status()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/subscription/subscription.py", line 208, in set_subscription_status
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 323, in _save
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 519, in _validate
    self.validate_set_only_once()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 565, in validate_set_only_once
    frappe.CannotChangeConstantError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 439, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CannotChangeConstantError: Value cannot be changed for Subscription Start Date
```

## Workaround

Create a **Property Setter** to disable `set_only_once` for the `start_date` field. Remove after successful import.

**Comment by cdiethelm** [comment]
@barredterra Do you know if there is a quick fix available? 
This issue is also mentioned in: https://discuss.erpnext.com/t/unable-to-import-subscription/85496

**Comment by barredterra** [comment]
@cdiethelm a workaround is mentioned at the end of the issue description.

**Comment by cdiethelm** [comment]
@barredterra Thank you! 👍

**Comment by s-aga-r** [comment]
@barredterra This doesn’t appear to be a general Data Import issue with DocTypes that has a `set_only_once field`.

Example:

<img width="1264" height="549" alt="Image" src="https://github.com/user-attachments/assets/0f5914a7-9df7-4ebe-9226-cc20c74a7d16" />
<img width="1264" height="889" alt="Image" src="https://github.com/user-attachments/assets/69f876eb-caf5-4b48-98f8-aca5c8276288" />
<img width="1264" height="272" alt="Image" src="https://github.com/user-attachments/assets/d19e7f71-e275-41d5-a667-0ece2b7dd7b8" />

Also, based on the logs you shared, `set_subscription_status` is being triggered in `after_insert`. Since the code has changed significantly, I’m closing this issue for now. Please feel free to open a new issue if the problem still exists in the latest v16.
