### ISSUE TITLE
Show or Hide Desktop Icons Not Updating

### ISSUE THREAD

**Issue by slushpuppy** [frappe/erpnext#5245]
### Issue Description

The show/Hide desktop icons don't seem to be updating. The AJAX query shows server response as "Updated" but when I refresh the page, all changes seems to be missing.

http://i.imgur.com/xfG3oL9.png

No error sinside
node-socketio.error.log
web.error.log
worker.error.log

http://pastebin.com/pC2kenr3 <-- debug dump

---

OS: Debian 8
ERPNext: v6.27.9
Frappe Framework: v6.27.10

**Comment by slushpuppy** [comment]
Here: I ticked "Website" view checkbox to show the Icon "Website", looking at the SQL dump logs, I don't see any statements that update the hidden colum to "0"

http://pastebin.com/EtSEAMiJ

**Comment by rmehta** [comment]
Are you on develop branch?

**Comment by slushpuppy** [comment]
Hi Rmehta,

   Thanks for the reply, how do I check?

Thanks

**Comment by slushpuppy** [comment]
sh-4.3$ bench update
INFO:bench.utils:updating bench
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/frappe/bench
   4d90001..ccea825  develop    -> origin/develop

I guess I am in the develop branch eh?

Running this command:

sh-4.3$ bench switch-to-master
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/var/www/erpnext/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/erpnext/bench-repo/bench/commands/update.py", line 123, in switch_to_master
    switch_to_master(upgrade=upgrade)
  File "/var/www/erpnext/bench-repo/bench/app.py", line 181, in switch_to_master
    switch_branch('master', apps=apps, bench=bench, upgrade=upgrade)
  File "/var/www/erpnext/bench-repo/bench/app.py", line 152, in switch_branch
    version_upgrade = is_version_upgrade(bench=bench, branch=branch)
  File "/var/www/erpnext/bench-repo/bench/app.py", line 99, in is_version_upgrade
    raise Exception("Current branch of 'frappe' not in upstream")
Exception: Current branch of 'frappe' not in upstream

I get an error :(

**Comment by anandpdoshi** [comment]
Go to `frappe-bench/apps/frappe` and check the output of `git branch`

**Comment by slushpuppy** [comment]
Yup, 100% on develop branch. So how do I switch now?

bench switch-to-master

throws an exception

File "/var/www/erpnext/bench-repo/bench/app.py", line 99, in is_version_upgrade
raise Exception("Current branch of 'frappe' not in upstream")
Exception: Current branch of 'frappe' not in upstream

**Comment by slushpuppy** [comment]
Problem fixed, you need to be in production mode. Take note that some of these commands

https://discuss.erpnext.com/t/howto-install-erpnext-v5-on-plain-vanilla-debian/6879

are outdated
