### ISSUE TITLE
"ImportError: No module named buying" When I try to create a Purchase Order

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#5270]
### Issue Description

After the last update I got this error when I try to create a new purchase order:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 855, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 65, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 75, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 20, in get_meta
    meta = frappe.cache().hget("form_meta", doctype, lambda: FormMeta(doctype))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 145, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 20, in 
    meta = frappe.cache().hget("form_meta", doctype, lambda: FormMeta(doctype))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 32, in __init__
    self.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 39, in load_assets
    self.add_code()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 62, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 77, in _add_code
    js = get_js(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 185, in get_js
    return render_include(js)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 49, in render_include
    with open(frappe.get_app_path(app, app_path), 'r') as f:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 645, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 660, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named buying

The same occurs when I try to create a sales order.

### Checklist

- [x] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [x] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [ ] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [x] I have not edited the code of Frappe and ERPNext
- [x] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  6.27.11
- Frappe version: 6.27.14
- Operating System: Ubuntu 14.04.4 LTS 32Bit
- Browser: Mozilla Firefox 45.0.2
- Language: Portuguese Brazil

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by anandpdoshi** [comment]
@applepipe are you using production setup?

**Comment by applepipe** [comment]
Yes, I've never used developer mode in this machine

**Comment by anandpdoshi** [comment]
ok. Try running `bench restart` from the frappe-bench folder

**Comment by applepipe** [comment]
Tried with no luck. I think you got the solution at https://discuss.erpnext.com/t/errors-after-upate-v6-27-12/12181/14

I'm using the virtualbox vm too, but I would like to use a stable release, is it possible?

**Comment by anandpdoshi** [comment]
@applepipe there might be issues because your frappe is new and patches were already applied. It is better to be on develop or it could lead to more errors.

**Comment by anandpdoshi** [comment]
we are using develop for our live data and it is working well so far

**Comment by applepipe** [comment]
I was concerned because I'm using this machine to my live data, tried to follow the instructions on the before mentioned topic but still no luck.

**Comment by anandpdoshi** [comment]
@applepipe what was the output when you ran update?

**Comment by applepipe** [comment]
Sorry, the less command and head where not showing the full output, my terminal abilities are rusty, I've posted the full output in the topic: https://discuss.erpnext.com/t/errors-after-upate-v6-27-12/12181/23?u=applepipe

**Comment by applepipe** [comment]
@anandpdoshi I added this to my /etc/locale.conf file: 
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

After a reboot, I noticed that locale simply ignores the file, so I did it manually using the command "export"

I've never modified the code, or any system configuration of the VM.

Here is the full output with all the commands:

frappe@erpnext:~/frappe-bench$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
frappe@erpnext:~/frappe-bench$ cat /etc/locale.conf 
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
frappe@erpnext:~/frappe-bench$ export LC_ALL=en_US.UTF-8
frappe@erpnext:~/frappe-bench$ export LC_CTYPE=en_US.UTF-8
frappe@erpnext:~/frappe-bench$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
frappe@erpnext:~/frappe-bench$ bench update
INFO:bench.utils:updating bench
Already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext_demo
From https://github.com/frappe/erpnext_demo
 * branch            master     -> FETCH_HEAD
Already up-to-date.
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Migrating erpnext.vm
Executing erpnext.patches.v4_2.repost_reserved_qty #2016-04-15 in erpnext.vm (d56cb677ea)
Success
Executing erpnext.patches.v6_20x.remove_customer_supplier_roles in erpnext.vm (d56cb677ea)
Success
Executing erpnext.patches.v6_24.rename_item_field in erpnext.vm (d56cb677ea)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 220, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 27, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 835, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named rename_item_field
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.0.0', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 61, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 91, in _update
    patch_sites(bench=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 131, in patch_sites
    run_frappe_cmd('--site', 'all', 'migrate', bench=bench)
  File "/home/frappe/bench-repo/bench/utils.py", line 468, in run_frappe_cmd
    raise CommandFailedError(args)
bench.utils.CommandFailedError: ('--site', 'all', 'migrate')

**Comment by anandpdoshi** [comment]
@applepipe can you update again? We've pushed a fix.

**Comment by applepipe** [comment]
@anandpdoshi Its working fine now! Thank you very much!
