### ISSUE TITLE
Server Error: Please check your server logs or contact tech support.

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5276]
When i click: http://128.199.200.6/desk#List/Sales Order
Error:
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 855, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 65, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 75, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 22, in get_meta
    meta = FormMeta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 32, in __init__
    self.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 39, in load_assets
    self.add_code()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 62, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 77, in _add_code
    js = get_js(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 185, in get_js
    return render_include(js)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 49, in render_include
    with open(frappe.get_app_path(app, app_path), 'r') as f:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 645, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 660, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named buying`

When i click http://128.199.200.6/desk#List/Purchase Order
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 855, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 65, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 75, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 22, in get_meta
    meta = FormMeta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 32, in __init__
    self.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 39, in load_assets
    self.add_code()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 62, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 77, in _add_code
    js = get_js(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 185, in get_js
    return render_include(js)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 49, in render_include
    with open(frappe.get_app_path(app, app_path), 'r') as f:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 645, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 660, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 622, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named buying`

**Comment by omnison** [comment]
ImportError: No module named selling
ImportError: No module named buying

**Comment by rmehta** [comment]
@omnison  can you please post this on the forum. Thanks!

**Comment by Iamshubhamsharma** [comment]
Traceback (most recent call last):
  File "/Users/cl-macmini-128/Documents/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/cl-macmini-128/Documents/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/cl-macmini-128/Documents/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/cl-macmini-128/Documents/frappe-bench/apps/frappe/frappe/__init__.py", line 900, in call
    return fn(*args, **newargs)
TypeError: get() takes exactly 1 argument (0 given)
