### ISSUE TITLE
error with sms sending

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#5404]
I've tried to send a sms and I got this error.  
Also when I tried to send the error report it said that I am not allowed to send email related to that document.

App Versions

{
    "erpnext": "6.27.21",
    "frappe": "6.27.20"
}
Route

Form/SMS Center/SMS Center
Error Report

Traceback (innermost last):
  File "/home/franky1/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/franky1/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/**init**.py", line 806, in call
    return fn(_args, *_newargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/handler.py", line 67, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 35, in runserverobj
    r = doc.run_method(method)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 579, in run_method
    return Document.hook(fn)(self, *args, *_kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in composer
    return composed(self, method, _args, *_kwargs)
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 718, in runner
    add_to_return_value(self, fn(self, _args, *_kwargs))
  File "/home/franky1/frappe-bench/apps/frappe/frappe/model/document.py", line 573, in 
    fn = lambda self, _args, *_kwargs: getattr(self, method)(_args, *_kwargs)
  File "/home/franky1/frappe-bench/apps/erpnext/erpnext/selling/doctype/sms_center/sms_center.py", line 79, in send_sms
    send_sms(receiver_list, cstr(self.message))
  File "/home/franky1/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 66, in send_sms
    send_via_gateway(arg)
  File "/home/franky1/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 79, in send_via_gateway
    status = send_request(ss.sms_gateway_url, args)
  File "/home/franky1/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 96, in send_request
    conn.request('GET', api_url + urllib.urlencode(args), headers = headers)    # send request
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known
Request Data

{
    "type": "POST",
    "args": {
        "docs": "{\"receiver_list\":\"260979466835\",\"modified_by\":\"Administrator\",\"name\":\"SMS Center\",\"total_messages\":1,\"creation\":\"2015-09-22 01:21:48.836840\",\"modified\":\"2015-09-22 01:21:48.836840\",\"send_to\":\"\",\"idx\":0,\"total_characters\":4,\"doctype\":\"SMS Center\",\"owner\":\"Administrator\",\"docstatus\":0,\"message\":\"yoyo\",\"__last_sync_on\":\"2016-05-27T05:08:05.925Z\",\"__unsaved\":1}",
        "method": "send_sms",
        "cmd": "runserverobj"
    },
    "btn": {
        "0": {},
        "length": 1,
        "prevObject": {
            "0": {},
            "length": 1
        }
    },
    "url": "/"
}
Response JSON

{}

**Comment by nabinhait** [comment]
Looks like the issue is related to SMS Settings.

**Comment by rmehta** [comment]
```
gaierror: [Errno -2] Name or service not known
```
Check your SMS settings

**Comment by sinaisix** [comment]
September 16, 2016. ERPNext 7.0.32 running on Ubuntu 14.04. Same error.
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 35, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 839, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 822, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/doctype/sms_center/sms_center.py", line 79, in send_sms
    send_sms(receiver_list, cstr(self.message))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 66, in send_sms
    send_via_gateway(arg)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 79, in send_via_gateway
    status = send_request(ss.sms_gateway_url, args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/sms_settings/sms_settings.py", line 96, in send_request
    conn.request('GET', api_url + urllib.urlencode(args), headers = headers)    # send request
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```

![screenshot from 2016-09-16 11-25-01](https://cloud.githubusercontent.com/assets/3254773/18584470/79eadeda-7c00-11e6-9b07-17f001d8a03c.png)

Attached is screenshot of my sms settings center. Using curl works fine.

**Comment by nabinhait** [comment]
It is related to your sms settings. Please post such queries in discuss.erpnext.com

**Comment by sinaisix** [comment]
I think it's a bug with the way the application tries to parse the sms api gateway.

This is my sms settings. If I remove the https:// and then the /v3/messages/send then ERPNext gives message that SMS sent when one tries sending sms. 

![screenshot from 2016-09-16 11-32-50](https://cloud.githubusercontent.com/assets/3254773/18584618/6fa41e7c-7c01-11e6-8b74-35b8910f39bb.png)

**Comment by sinaisix** [comment]
Well playing around the sms_settings.py module a bit

```
def send_request(gateway_url, args):
	import httplib, urllib
	server, api_url = scrub_gateway_url(gateway_url)
	conn = httplib.HTTPSConnection(server)  # open connection
	headers = {}
	headers['Accept'] = "text/plain, text/html, */*"
	conn.request('GET', api_url + urllib.urlencode(args), headers = headers)    # send request
	resp = conn.getresponse()     # get response
	return resp.status

# Split gateway url to server and api url
# =========================================================
def scrub_gateway_url(url):
	url = url.replace('https://', '').strip().split('/')
	server = url.pop(0)
	api_url = '/' + '/'.join(url)
	if not api_url.endswith('?'):
		api_url += '?'
	return server, api_url
```

Changing the urllib.HTTPSConnection to use the https and then the url.replace in the scrub_gateway_url method to replace the http with https, now the exception is no longer thrown. 

Trying to send an sms by pressing the send sms button, nothing happens. SMS too is not sent.

**Comment by sinaisix** [comment]
Just to be sure, this works curl --request GET 'https://api.smsgh.com/v3/messages/send?From=Emigoh&To=%2B233504733076&Content=This!!!&ClientId=bla&ClientSecret=bla&RegisteredDelivery=true'

**Comment by rmehta** [comment]
@sinaisix thanks for poking will check. If you think you found the issue, send in a patch :)

**Comment by sinaisix** [comment]
OK sure, still playing around a bit to see what I can do to help

**Comment by sinaisix** [comment]
Hello, I've kind of had a hack to this issue. I used the Python [requests](http://docs.python-requests.org/en/master/) library. With that I altered things thus

```
def send_via_gateway(arg):
    **params = {"ClientId":"bla", "ClientSecret":"bla", "From":"bla", "Content": str(arg.get("message"))}**
    ss = frappe.get_doc('SMS Settings', 'SMS Settings')
    args = {ss.message_parameter: arg.get('message')}
    for d in ss.get("parameters"):
        args[d.parameter] = d.value

    success_list = []
    for d in arg.get('receiver_list'):
        **params["To"] = str(d)**
        status = send_request(ss.sms_gateway_url, args, **params**)
        if status == **201**
            success_list.append(d)

    if len(success_list) > 0:
        args.update(arg)
        create_sms_log(args, success_list)
        frappe.msgprint(_("SMS sent to following numbers: {0}").format("\n" + "\n".join(success_list)))


def send_request(gateway_url, args, **params**):
    import httplib, urllib, **requests**
    server, api_url = scrub_gateway_url(gateway_url)
    params = {"ClientId": str(args["ClientId"]), "ClientSecret": str(args["ClientSecret"]),"Content":    str(args["Content"]), "To": str(args["To"]), "From":str(args["From"])}
    res = requests.get("https://api.smsgh.com/v3/messages/send", params=params)
    conn = httplib.HTTPSConnection(server)  # open connection
    headers = {}
    headers['Accept'] = "text/plain, text/html, */*"
    conn.request('GET', api_url + urllib.urlencode(args), headers=headers)  # send request
    resp = conn.getresponse()  # get response
    **response = requests.get("https://api.smsgh.com/v3/messages/send", params = params)**
    return **response.status_code**  # Split gateway url to server and api url

```

I had a few issues getting the params from the ss map because I really couldn't tell if the keys were strings or not and so knowing my api gateway params, I hard coded those parts. 

Being a Java EE developer, this was the best solution I could come up with, at least it works...for now. The changes I made are marked with **
