### ISSUE TITLE
[BUG] Opening Item Error with Request for Quotation [v7]

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#5433]
There is an issue when opening any item. Easy to replicate, just try to load an item on ERPNext. It appears to be an issue in db_query.execute where the Request for Quotation Item table isn't included, which causes an incorrect sql query to get sent.

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 854, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/item.py", line 636, in get_dashboard_data
    'count': get_open_count('Item', name),
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 198, in get_open_count
    filters=filters, limit=6, distinct=True, ignore_ifnull=True))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1061, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1034, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 76, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 147, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabRequest for Quotation.item_code' in 'where clause'")`

**Comment by rmehta** [comment]
Cannot replicate. Seems fixed.
