### ISSUE TITLE
[V7] Error when open Stock Projected Qty Report

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5552]
Server Error: Please check your server logs or contact tech support.

--- query explain ---
error in query explain
select item_code, warehouse, actual_qty, planned_qty, indented_qty,
		ordered_qty, reserved_qty, reserved_qty_for_production, projected_qty
		from tabBin where  order by item_code, warehouse 
Traceback (most recent call last):
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/__init__.py", line 874, in call
    return fn(*args, **newargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 88, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/stock/report/stock_projected_qty/stock_projected_qty.py", line 11, in execute
    return get_columns(), get_data(filters)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/stock/report/stock_projected_qty/stock_projected_qty.py", line 23, in get_data
    bin_list = get_bin_list(filters)
  File "/Users/umairsayyed/frappe-bench/apps/erpnext/erpnext/stock/report/stock_projected_qty/stock_projected_qty.py", line 73, in get_bin_list
    from tabBin where %s order by item_code, warehouse """% " and ".join(conditions), as_dict=1,debug=1)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order by item_code, warehouse' at line 3")

**Comment by saurabh6790** [comment]
WIP.

**Comment by saurabh6790** [comment]
@umairsy Fixed. Please close the issue.
