### ISSUE TITLE
Error while trying to delete warehouse in beta.erpnext.com

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5580]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 118, in delete
    frappe.delete_doc(doctype, name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 612, in delete_doc
    ignore_permissions, flags)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 76, in delete_doc
    doc.run_method("on_trash")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 603, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 768, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 751, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 597, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 116, in on_trash
    if self.check_sle_exists():
AttributeError: 'Warehouse' object has no attribute 'check_sle_exists'
```

**Comment by nabinhait** [comment]
Fixed via #5572
