### ISSUE TITLE
[V7] Error when attempting to open Purchase Invoice on beta.erpnext.com

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5587]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 32, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 577, in get_doc
    return frappe.model.document.get_doc(arg1, arg2)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 46, in get_doc
    return controller(arg1, arg2)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 52, in __init__
    ["Purchase Invoice Item", "parent", "=", self.item],
AttributeError: 'PurchaseInvoice' object has no attribute 'item'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 32, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 577, in get_doc
    return frappe.model.document.get_doc(arg1, arg2)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 46, in get_doc
    return controller(arg1, arg2)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 52, in __init__
    ["Purchase Invoice Item", "parent", "=", self.item],
AttributeError: 'PurchaseInvoice' object has no attribute 'item'
```
`

**Comment by rmehta** [comment]
fixed
