### ISSUE TITLE
[V7] Customers not buying since long time

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5589]
This report name still shows up in the list of reports for Sales Order. 

```
Traceback (most recent call last):
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 88, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 855, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/erpuser/frappe-bench/apps/frappe/frappe/__init__.py", line 642, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named customers_not_buying_since_long_time.customers_not_buying_since_long_time
```

**Comment by KanchanChauhan** [comment]
@cgpurbaugh When did you encountered this error because unfortunately I am not able to replicate this issue. This report was renamed to Inactive Customers.

**Comment by cgpurbaugh** [comment]
@KanchanChauhan Looks like this has been fixed.
