### ISSUE TITLE
Error in Time Sheet report builder

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#5669]
Hello, 

Whenever I go to start Report Builder in Time Sheet List -> Reports -> Report Builder  I get the following error. 

Traceback (most recent call last):
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 16, in get
    data = compress(execute(**args))
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 21, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabTime Sheet Detail.name as 'Time Sheet Detail:name'' in 'field list'")

**Comment by KanchanChauhan** [comment]
@ioweb-gr please "bench update" and try again.

**Comment by ioweb-gr** [comment]
Just did a bench update and problem still persists. 

Server Error: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 16, in get
    data = compress(execute(**args))
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 21, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabTime Sheet Detail.name as 'Time Sheet Detail:name'' in 'field list'")

**Comment by KanchanChauhan** [comment]
Run "Bench Migrate" as well

**Comment by ioweb-gr** [comment]
I ran bench migrate and bench update again and no difference. I think it also executed bench migrate when I used --upgrade option too. In any case I still have the same error.

**Comment by ioweb-gr** [comment]
Never mind I found it I'll issue a pull request in a while. It's a typo in the erpnext/projects/doctype/time_sheet_detail/time_sheet_detail.json file in line 537 
it should be "fieldname" instead of "name"

**Comment by KanchanChauhan** [comment]
It should be "name" only.

**Comment by ioweb-gr** [comment]
OK then I don't know why it fails. But it did allow me to view the report builder as soon as i changed it if it helps.
