### ISSUE TITLE
V7 -  Unable to use rename tool

### ISSUE THREAD

**Issue by it2sme** [frappe/erpnext#5782]
I get this message using the rename tool.
Something went wrong
Unable to open attached file. Please try again.Server Error: Please check your server logs or contact tech support.

Traceback (most recent call last):
  File "/home/xn/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/xn/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/xn/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/xn/frappe-bench/apps/frappe/frappe/__init__.py", line 876, in call
    return fn(*args, **newargs)
  File "/home/xn/frappe-bench/apps/erpnext/erpnext/utilities/doctype/rename_tool/rename_tool.py", line 29, in upload
    rows = read_csv_content_from_attached_file(frappe.get_doc("Rename Tool", "Rename Tool"))
  File "/home/xn/frappe-bench/apps/frappe/frappe/utils/csvutils.py", line 34, in read_csv_content_from_attached_file
    raise Exception
Exception

**Comment by rmehta** [comment]
Cannot replicate, are you sure you are using CSV format?

**Comment by it2sme** [comment]
Yes, from open office it uses the same format as data import tool, but only 2 rows. I have 2 servers running for development, v6 and v7 it only happens on v7. I will wait for final release and confirm if persists. thank you
