### ISSUE TITLE
[V7] Error on Make > Payment

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#5789]
I've got this error when trying to make a payment on an open Purchase Order:

App Versions

{
	"erpnext": "7.0.0-beta",
	"frappe": "7.0.0-beta"
}
Route

Form/Purchase Order/OC-00023
Error Report

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 876, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 638, in get_payment_entry
    if party_account_currency == bank.account_currency:
AttributeError: 'NoneType' object has no attribute 'account_currency'
Request Data

{
	"type": "POST",
	"args": {
		"dt": "Purchase Order",
		"dn": "OC-00023",
		"cmd": "erpnext.accounts.doctype.payment_entry.payment_entry.get_payment_entry"
	},
	"url": "/"
}
Response JSON

{}

**Comment by nabinhait** [comment]
fixed
