### ISSUE TITLE
[v7] Node Socketio: TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#5852]
```
/home/frappe/benches/bench-2016-07-24-a/apps/frappe/socketio.js:48
                                var room = get_user_room(socket, res.body.message.user);
                                                                                 ^
TypeError: Cannot read property 'user' of undefined
    at /home/frappe/benches/bench-2016-07-24-a/apps/frappe/socketio.js:48:54
    at Request.callback (/home/frappe/benches/bench-2016-07-24-a/node_modules/superagent/lib/node/index.js:591:12)
    at Stream.<anonymous> (/home/frappe/benches/bench-2016-07-24-a/node_modules/superagent/lib/node/index.js:766:18)
    at Stream.emit (events.js:117:20)
    at Unzip.<anonymous> (/home/frappe/benches/bench-2016-07-24-a/node_modules/superagent/lib/node/utils.js:108:12)
    at Unzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by rmehta** [comment]
works in local

**Comment by anandpdoshi** [comment]
could be due to an update in a js lib

**Comment by vqw** [comment]
We are encountering exactly the same issue, unfortunately we can't figure it out.
Is it because of wrong SID or unexpected response from frappe.async_get_user_info?

**Comment by rmehta** [comment]
Most likely you are using an older version of socketio
