### ISSUE TITLE
Import Custom Script to New Site with TypeError coercing to Unicode

### ISSUE THREAD

**Issue by KennethWKZ** [frappe/erpnext#5866]
Once update to latest version, found that when we import custom script from old to new site, it will got coercing to unicode error.

But I was found that if we create an empty Client Script with DocType name and save. Then start import, it will success. I also tried on latest master branch and develop 7.0.3 branch. All got same issue.

`{u'__islocal': True, u'modified_by': u'Administrator', u'name': u'User-Client', u'parent': None, u'script': u'cur_frm.add_fetch("company","abbr","companyabbr");', u'creation': '2016-07-26 00:37:16.784305', u'modified': '2016-07-26 00:37:16.784305', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'User', u'script_type': None, u'parentfield': None}
desk.min.js:138 `

`Traceback (most recent call last):
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/sunseap-prod/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found`

**Comment by rmehta** [comment]
You need to set `script_type` while importing.

**Comment by KennethWKZ** [comment]
too fast to close this issue thread?

From the thread you can see what can I debugged it out, and it was meaning when import custom script there missing a script_type value eg: Client.

So what I tried the ways to import are using command line - "bench import-csv myfile-path/Custom_Script.csv" and Setup > Import/Export Data in v7 and seems like the ERPNEXT didn't recognize this script as Client by default. 

Is it ERPNEXT v7 got any configuration can set this script_type value as default by ourself or it just same as ERPNEXT v6 but only v7 cannot work?

**Comment by rmehta** [comment]
why not just set it in the CSV?

**Comment by KennethWKZ** [comment]
At v6, It didn't need to set this. How come v7 need to set this manually in CSV? The Custom_Script.csv exported from this page - "Setup > Import/Export Data". It should be auto support right instead of manually set the column script_type in CSV?

**Comment by rmehta** [comment]
Not necessarily. Maybe there is a reason that field is not filled by default. Send a patch if you think better.
