### ISSUE TITLE
[V7] Error when running bench update

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#5876]
Hello,

I'm getting this error when trying to run "bench update"

~/frappe-bench$ bench update
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.0.0', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 30, in update
    patches.run(bench_path='.')
  File "/home/frappe/bench-repo/bench/patches/__init__.py", line 21, in run
    result = execute(bench_path)
  File "/home/frappe/bench-repo/bench/patches/v4/update_node.py", line 7, in execute
    result = subprocess.check_output(['node', '-v'])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by rmehta** [comment]
update again. You need nodejs 5+ installed for v7

**Comment by applepipe** [comment]
I think I need more help, I'm using the original VM, no modifications were made.

How can I install nodejs 5+ or upgrade it? Everything was fine on V7 until monday.

**Comment by rmehta** [comment]
Can you try update again? Head for the forum for more help.

**Comment by applepipe** [comment]
Tried already, same error.

**Comment by applepipe** [comment]
Found the topic! https://discuss.erpnext.com/t/solved-v7-bench-update-error-updating-to-nodejs-5-x-or-6-x/14452/5

All fine now, upgraded nodejs using the official repo.

Sorry for bothering you with this.
