### ISSUE TITLE
No module named list in v7

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#5900]
Hello there,

this error occurs when calling Knowledge Base "Help Article" or "Contact" page on the website.

```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 876, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 68, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 79, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 22, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 32, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 42, in load_assets
    self.load_templates()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 149, in load_templates
    module = load_doctype_module(self.name)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 64, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(get_module_name(doctype, module, prefix, suffix))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 643, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/frappe-bench/apps/knowledge_base/knowledge_base/knowledge_base/doctype/help_article/help_article.py", line 10, in 
    from frappe.templates.pages.list import get_list
ImportError: No module named list
```

This was since upgrading to v7.

**Comment by yashodhank** [comment]
@ci2014 You have knowledge_base app loaded earlier, it is not working with version 7, so either you uninstall it from the site using bench or just wait for update to rollover for knowledge_base app in coming days.

**Comment by ci2014** [comment]
@yashodhank Thank you. May I disable apps, without the data being deleted?

**Comment by ci2014** [comment]
@yashodhank Thank you. This thread may be closed. The bug is fixed.
