### ISSUE TITLE
Error when trying to import Custom Scripts V7

### ISSUE THREAD

**Issue by David-at-GitHub** [frappe/erpnext#5977]
Dear all,

in Version 7, when trying to import Custom Scripts, I'm getting the following error message: 

Import Failed

Error for row (#21) "Purchase Invoice-Client" : coercing to Unicode: need string or buffer, NoneType found

Here a print screen, please also find attached the import file I'm trying to use. Thanks, David
[Custom_Script.xlsx](https://github.com/frappe/erpnext/files/397100/Custom_Script.xlsx)

![image](https://cloud.githubusercontent.com/assets/15001320/17330370/9a6d182e-5894-11e6-8941-d044900d2393.png)

**Comment by rmehta** [comment]
can you share what is in your JS trace?

**Comment by David-at-GitHub** [comment]
@rmehta Thank you for your response, as follows the JS trace:

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Purchase Invoice-Client', u'parent': None, u'script': u'frappe.ui.form.on("Purchase Invoice", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.102059', u'modified': '2016-08-03 20:42:39.102059', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Purchase Invoice', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Purchase Receipt-Client', u'parent': None, u'script': u'frappe.ui.form.on("Purchase Receipt", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.103048', u'modified': '2016-08-03 20:42:39.103048', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Purchase Receipt', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Sales Invoice-Client', u'parent': None, u'script': u'frappe.ui.form.on("Sales Invoice", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.103813', u'modified': '2016-08-03 20:42:39.103813', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Sales Invoice', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Delivery Note-Client', u'parent': None, u'script': u'frappe.ui.form.on("Delivery Note", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.104568', u'modified': '2016-08-03 20:42:39.104568', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Delivery Note', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Purchase Order-Client', u'parent': None, u'script': u'frappe.ui.form.on("Purchase Order", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.105320', u'modified': '2016-08-03 20:42:39.105320', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Purchase Order', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Sales Order-Client', u'parent': None, u'script': u'frappe.ui.form.on("Sales Order", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync" && frm.doc.docstatus == "0") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});\ncur_frm.cscript.shipping_address_name = function(doc,cdt,cdn){\n\n\terpnext.utils.get_address_display(this.frm, "shipping_address_name","shipping_address_display");\n}', u'creation': '2016-08-03 20:42:39.106076', u'modified': '2016-08-03 20:42:39.106076', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Sales Order', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Item-Client', u'parent': None, u'script': u'frappe.ui.form.on("Item Master", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.106837', u'modified': '2016-08-03 20:42:39.106837', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Item', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Customer-Client', u'parent': None, u'script': u'frappe.ui.form.on("Customer", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.107610', u'modified': '2016-08-03 20:42:39.107610', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Customer', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Supplier-Client', u'parent': None, u'script': u'frappe.ui.form.on("Supplier", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.108358', u'modified': '2016-08-03 20:42:39.108358', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Supplier', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Address-Client', u'parent': None, u'script': u'frappe.ui.form.on("Address", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.109115', u'modified': '2016-08-03 20:42:39.109115', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Address', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

desk.min.js:1407 {u'__islocal': True, u'modified_by': u'Administrator', u'name': u'Contact-Client', u'parent': None, u'script': u'frappe.ui.form.on("Contact", "validate", function(frm) {\n    msgprint(frm.doc.sap_sync_setting)\n  if(frm.doc.sap_sync_setting != "Do not sync") {\n    cur_frm.set_value("sap_sync_setting", "Updates awaiting sync");\n            msgprint("SAP Sync setting updated");\n        }\n});', u'creation': '2016-08-03 20:42:39.109851', u'modified': '2016-08-03 20:42:39.109851', u'doctype': u'Custom Script', u'idx': 0, u'parenttype': None, u'owner': u'Administrator', u'docstatus': 0, u'dt': u'Contact', u'script_type': None, u'parentfield': None}
desk.min.js:1407 Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py", line 257, in upload
    doc.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 207, in insert
    self.set_new_name()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 325, in set_new_name
    set_new_name(self)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/naming.py", line 38, in set_new_name
    doc.run_method("autoname")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/custom/doctype/custom_script/custom_script.py", line 12, in autoname
    self.name = self.dt + "-" + self.script_type
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by rmehta** [comment]
Pushed a fix to develop

**Comment by David-at-GitHub** [comment]
Thanks for this. And sorry to re-open this issue, but I suspect that this is a general problem in the Version 7. I'm using ERPNext' RESTful API which worked fine in Version 6, but in Version 7 I'm getting for all type of calls the error below. It ends with a similar error message as the one for the script-import, so maybe this has a related cause. Could you please check and let me know? By the way, this test was done on ERPNext' hosted environment.

Thanks, David

<exceptionMsg>
com.sap.b1i.xcellerator.XcelleratorException: XCE212 Error performing the HTTP-call, HTTP-status is 500, INTERNAL SERVER ERROR
</exceptionMsg>
<returnData>
{"exc":"[\"Traceback (most recent call last):\\n File \\\"/home/frappe/benches/bench-2016-08-01-a/apps/frappe/frappe/app.py\\\", line 58, in application\\n response = frappe.api.handle()\\n File \\\"/home/frappe/benches/bench-2016-08-01-a/apps/frappe/frappe/api.py\\\", line 110, in handle\\n data = json.loads(frappe.local.form_dict.data)\\n File \\\"/usr/lib64/python2.7/json/__init__.py\\\", line 338, in loads\\n return _default_decoder.decode(s)\\n File \\\"/usr/lib64/python2.7/json/decoder.py\\\", line 365, in decode\\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\nTypeError: expected string or buffer\\n\"]"}
</returnData>
