### ISSUE TITLE
[ERROR] Run tests fails on module

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#5999]
The `bench run-tests --module XXX` seems to fail every time with this error:

```
frappe@erpnext:~/frappe-bench$ bench run-tests --module "Stock"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 302, in run_tests
    force=context.force, profile=profile)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/test_runner.py", line 37, in main
    ret = run_tests_for_module(module, verbose, tests, profile)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/test_runner.py", line 102, in run_tests_for_module
    module = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Stock

```

**Comment by rmehta** [comment]
module means python module. like `frappe.tests.test_email`

**Comment by gvyshnya** [comment]
@rmehta : is there a way to put this note into the updated documentation for frappe unit test framework? Right now, using Module key there is not explained comprehensively.

Thank you in advance!

**Comment by rmehta** [comment]
> is there a way to put this note into the updated documentation for frappe unit test

Add it your self :)

**Comment by gvyshnya** [comment]
Where is the right place to put? I am not oppose to edit the documentation,
i would like to just know the specific section which is the most suitable
for this type of details.

**Comment by rmehta** [comment]
@gvyshnya make a guess?

https://frappe.github.io/frappe/user/en/guides/basics/writing-tests.html or you can update the bench command too.

**Comment by safo-bora** [comment]
Doc was updated - https://github.com/frappe/frappe/pull/1978/files
