### ISSUE TITLE
Error in updating to V7

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6006]
> ubuntu@ip-172-31-14-55:~$ bench update
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/ubuntu/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/bench-repo/bench/commands/update.py", line 30, in update
    version_upgrade = is_version_upgrade()
  File "/home/ubuntu/bench-repo/bench/app.py", line 96, in is_version_upgrade
    upstream_version = get_upstream_version('frappe', bench=bench, branch=branch)
  File "/home/ubuntu/bench-repo/bench/app.py", line 139, in get_upstream_version
    return get_version_from_string(contents)
  File "/home/ubuntu/bench-repo/bench/app.py", line 195, in get_version_from_string
    return match.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by yashodhank** [comment]
@justinlusg Known issue and can be resolved by following steps > https://discuss.erpnext.com/t/important-error-in-bench-update/13248?u=yashodhan
Closing ticket. Thanks
