### ISSUE TITLE
V7: when clicking Chat notification in browser it tries to route to messages instead of new name "Chat"

### ISSUE THREAD

**Issue by it2sme** [frappe/erpnext#6014]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 879, in call
    return fn(_args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 28, in getpage
    doc = get(page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 15, in get
    page.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/page/page.py", line 114, in load_assets
    for fname in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/messages'

**Comment by netchampfaris** [comment]
Cannot replicate as of now. Closing.
