### ISSUE TITLE
Error when attempting to generate a PDF

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6025]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 58, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 49, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/print_format.py", line 50, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 16, in get_pdf
    pdfkit.from_string(html, fname, options=options or {})
  File "/home/frappe/frappe-bench/env/src/pdfkit/pdfkit/api.py", line 68, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/frappe-bench/env/src/pdfkit/pdfkit/pdfkit.py", line 143, in to_pdf
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, stderr.decode("utf-8")))
IOError: wkhtmltopdf exited with non-zero code -6. error:
The switch --no-outline, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.The switch --print-media-type, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display
```

**Comment by vCentre** [comment]
Missing ERPNext v4 at which PDF generation were working like a charm!
v5,6 and 7 there're always problems with PDF.

**Comment by nabinhait** [comment]
Can't replicate. Are you using custom print template?

**Comment by andmattia** [comment]
Hi
we have the same issue:
Ubuntu 16.04 (new install)
erpnext 7.0.44
frappe 7.0.32

with 
xvfb-run wkhtmltopdf http://erpnext.com erpnext.pdf
it's work
wkhtmltopdf http://erpnext.com erpnext.pdf
same error above.

Any idea to solve? It's very urgent

**Comment by andmattia** [comment]
Any news????

**Comment by cgpurbaugh** [comment]
Look here: https://discuss.erpnext.com/t/wkhtmltopdf-error-erpnext-v7/14673

wkhtmltopdf must have patched QT

**Comment by chris-aeviator** [comment]
BTW I will not get this error when using an Image in my letterhead that's hosted by erpnext (`/files/mylogo.png`) but will run into this error when using an external image like `https://external.com/image.png`

**Comment by chris-aeviator** [comment]
BTW I get 

```
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench/apps/frappe/frappe/utils/print_format.py", line 92, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "/home/frappe/bench/apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

```

with `wkhtmltopdf -V`
```
wkhtmltopdf 0.12.3 (with patched qt)
```

**Comment by mukuldeepfence** [comment]
i am getting the same error using this same version

File "/usr/local/lib/python3.6/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Loading pages (1/6)
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination
Exit with code 1, due to unknown error.



**with wkhtmltopdf -V**

**wkhtmltopdf 0.12.6 (with patched qt)**

**Comment by chris-aeviator** [comment]
@cgpurbaugh don't you think this issue should be re-opened

**Comment by ankush** [comment]
@mukuldeepfence  probably worth opening new issue. Share version info (ERPNext, Frappe) and also name of the file you were trying to generate.

this is worth checking out: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2934

**Comment by mukuldeepfence** [comment]
My issue has been solved my file name was a problem

**Comment by ankush** [comment]
@mukuldeepfence  Can you tell us a bit more about filename issue? Perhaps we can change something to improve UX.

**Comment by mukuldeepfence** [comment]
There should not be special char like "/" and ":" in filename specially.
and this error was related to directly wkhtmltopdf.

**Comment by chris-aeviator** [comment]
> There should not be special char like "/" and ":" in filename specially

since `/` is basically part of any path (at least on linux systems) this is confusing. Can you refer a document that states **why** this is a limitation?
