### ISSUE TITLE
[V7] Error on Calendar View

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#6027]
@rohitwaghchaure ,
I'm getting an odd error when trying to access the calendar on my production version of the server:

```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 30, in execute_cmd
    method = get_attr(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 114, in get_attr
    method = frappe.get_attr(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 859, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: 'module' object has no attribute 'get_events'
```

It does not happen on my develop server.

Also, it doesn't look like Timesheets shows up as on option in the Calendar Type dropdown box. I can't see anywhere in ERPNext where it specifies to add it, so I'm not sure how it gets handled.

**Comment by rohitwaghchaure** [comment]
Hi @bcornwellmott ,
You need to reload the supervisor 
run ```sudo supervisorctl reload``` on server.
