### ISSUE TITLE
Merge Knowledge base into frappe

### ISSUE THREAD

**Issue by vCentre** [frappe/erpnext#6030]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 27, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 47, in resolve_route
    return get_page_context_from_doctype(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 72, in get_page_context_from_doctype
    page_info = get_page_info_from_doctypes(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 104, in get_page_info_from_doctypes
    {1}""".format(doctype, condition), values=values, as_dict=True):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'route' in 'field list'")
```

**Comment by nabinhait** [comment]
Are you still getting this error?

**Comment by aacosae** [comment]
Yes still getting the error on Product Page, Contact Us & Jobs

**Comment by yashodhank** [comment]
Error occured after upgrading from version 6 to version 7
![image](https://cloud.githubusercontent.com/assets/1083792/18901930/aa73cf6a-856c-11e6-8196-42b241af51af.png)

**Comment by ossphcorp** [comment]
I'm also getting this error.

```

> > Traceback (most recent call last):
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
>     data = render_page_by_language(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
>     return render_page(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
>     return build(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
>     return build_page(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
>     context = get_context(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
>     context = get_page_context(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in get_page_context
>     page_context = make_page_context(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/router.py", line 27, in make_page_context
>     context = resolve_route(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/router.py", line 47, in resolve_route
>     return get_page_context_from_doctype(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/router.py", line 72, in get_page_context_from_doctype
>     page_info = get_page_info_from_doctypes(path)
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/website/router.py", line 104, in get_page_info_from_doctypes
>     {1}""".format(doctype, condition), values=values, as_dict=True):
>   File "/home/sysadmin/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
>     self._cursor.execute(query, values)
>   File "/home/sysadmin/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/sysadmin/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> OperationalError: (1054, "Unknown column 'route' in 'field list'")
> 

```

**Comment by ossphcorp** [comment]
I got this error again after installing Knowledge Base

**Comment by rmehta** [comment]
@ossphcorp Knowledge Base app is deprecated, maybe will merge it in frappe
