### ISSUE TITLE
frappe.exceptions.LinkValidationError: Could not find Row #10: Reference Doctype: Assessment

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#6036]
```
$ bench retry-upgrade
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
   a2c9d13..722b22a  master     -> upstream/master
Updating a2c9d13..722b22a
Fast-forward
 erpnext/__init__.py                                | 2 +-
 erpnext/patches/v7_0/migrate_schools_to_erpnext.py | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
Migrating eliteshop
Executing erpnext.patches.v7_0.fix_duplicate_icons in eliteshop (f3eb480827)
/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/examination/examination.json missing
Success
Updating frappe                     : [========================================]
Updating erpnext                    : [========================================]
Migrating hujra.pk
Executing execute:frappe.reload_doc('core', 'doctype', 'doctype', force=True) #2016-07-11 in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('core', 'doctype', 'role') in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.update_auth in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.rename_bulk_email_to_email_queue in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v6_20x.set_allow_draft_for_print in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v6_20x.remove_roles_from_website_user in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.set_user_fullname in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.desktop_icons_hidden_by_admin_as_blocked in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.add_communication_in_doc in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.update_send_after_in_bulk_email in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.setup_list_settings in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.db.sql('''delete from `tabSingles` where doctype="Email Settings"''') # 2016-06-13 in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.db.sql("delete from `tabWeb Page` where ifnull(template_path, '')!=''") in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.re_route #2016-06-27 in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.rename_newsletter_list_to_email_group in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.replace_upgrade_link_limit in hujra.pk (1ffca6225b)
Success
Executing frappe.patches.v7_0.set_email_group in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('stock', 'doctype', 'warehouse') in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('accounts', 'doctype', 'asset_category') in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.re_route #2016-06-27 in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.create_warehouse_nestedset in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.merge_account_type_stock_and_warehouse_to_stock in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.set_is_group_for_warehouse in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v4_2.repost_reserved_qty #2016-04-15 in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_party_status in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_item_projected in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.remove_features_setup in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_home_page in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.create_budget_record in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.delete_doc_if_exists("Page", "financial-analytics") in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_project_in_gl_entry in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.db.sql('update tabQuotation set status="Cancelled" where docstatus=2') in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.rename_doc("DocType", "Payments", "Sales Invoice Payment", force=True) in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_mins_to_first_response in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.system_settings_setup_complete in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.set_naming_series_for_timesheet #2016-07-27 in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('projects', 'doctype', 'project') in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('projects', 'doctype', 'project_user') in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.convert_timelogbatch_to_timesheet in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.convert_timelog_to_timesheet in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.move_timelogbatch_from_salesinvoiceitem_to_salesinvoicetimesheet in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.remove_doctypes_and_reports in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_maintenance_module_in_doctype in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.update_prevdoc_values_for_supplier_quotation_item in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.rename_advance_table_fields in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.rename_salary_components in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.rename_prevdoc_fields in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.rename_time_sheet_doctype in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.delete_doc_if_exists("Report", "Customers Not Buying Since Long Time") in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.make_is_group_fieldtype_as_check in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.reload_doc('projects', 'doctype', 'timesheet', force=True) in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.delete_doc_if_exists("Report", "Employee Holiday Attendance") in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.delete_doc_if_exists("DocType", "Payment Tool") in hujra.pk (1ffca6225b)
Success
Executing execute:frappe.delete_doc_if_exists("DocType", "Payment Tool Detail") in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.setup_account_table_for_expense_claim_type_if_exists in hujra.pk (1ffca6225b)
Success
Executing erpnext.patches.v7_0.migrate_schools_to_erpnext in hujra.pk (1ffca6225b)
/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/examination/examination.json missing
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 206, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 27, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 52, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 68, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v7_0/migrate_schools_to_erpnext.py", line 26, in execute
    frappe.get_doc('Portal Settings', 'Portal Settings').sync_menu()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/portal_settings/portal_settings.py", line 30, in sync_menu
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 272, in _save
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 388, in _validate
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 630, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 299, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 292, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 265, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.LinkValidationError: Could not find Row #10: Reference Doctype: Assessment
```

**Comment by nabinhait** [comment]
fixed via #6038
