### ISSUE TITLE
Error for sending email

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6090]
When attempting to send email, email queue shows the following error:
```
[Errno -3] Temporary failure in name resolution
```
If I attempt to send manually, I get the following error:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 32, in send_now
    send_one(doc, now=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 290, in send_one
    from `tabEmail Queue` where name=%s for update''', email, as_dict=True)[0]
IndexError: list index out of range
```

**Comment by PawanMeh** [comment]
Are you still having this error after latest bench updates?

**Comment by cgpurbaugh** [comment]
No, this has been fixed.
