### ISSUE TITLE
[develop] error when clicking 'Preview Salary Slip' when salary slip based on timesheet is checked 

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6132]
- Check on 'Salary slip based on timesheet' after setting up a structure

![screen shot 2016-08-21 at 10 04 37 pm](https://cloud.githubusercontent.com/assets/20460498/17838455/b2b18fa8-67eb-11e6-8853-d1e707b35633.png)

- Click on 'Preview Salary Slip', enter an employee ID and  try to preview the salary slip.
You would get an error as below:

  File "/Users/pawan/frappe-bench/env/lib/python2.7/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.

- This needs to be changed to a more user friendly message  or allowing checking of salary slip based on timesheets for formula based salary needs to be disabled

**Comment by KanchanChauhan** [comment]
Could not replicate.

**Comment by PawanMeh** [comment]
Here is the entire trace , if it helps to give any pointers

Traceback (most recent call last):
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/Users/pawan/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 55, in make_salary_slip
    }, target_doc, postprocess, ignore_child_tables=True)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/mapper.py", line 72, in get_mapped_doc
    postprocess(source_doc, target_doc)
  File "/Users/pawan/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_structure/salary_structure.py", line 45, in postprocess
    target.run_method('process_salary_structure')
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 839, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 822, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/pawan/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py", line 179, in process_salary_structure
    self.get_leave_details()
  File "/Users/pawan/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py", line 224, in get_leave_details
    lwp = self.calculate_lwp(holidays, working_days)
  File "/Users/pawan/frappe-bench/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py", line 274, in calculate_lwp
    dt = add_days(cstr(self.start_date), d)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/utils/data.py", line 93, in add_days
    return add_to_date(date, days=days)
  File "/Users/pawan/frappe-bench/apps/frappe/frappe/utils/data.py", line 80, in add_to_date
    date = parser.parse(date)
  File "/Users/pawan/frappe-bench/env/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/pawan/frappe-bench/env/lib/python2.7/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
