### ISSUE TITLE
ERPNext 7 Demo Data

### ISSUE THREAD

**Issue by stroudmw** [frappe/erpnext#6142]
I have been trying to load demo data into ERPNext 7. I have ERPnext setup locally on my laptop: ERPNext: v7.0.27 and Frappe Framework: v7.0.20. Ideally, I would like to find a set of files (xml?) so that I can practice with the data import. However, I found instructions for setting a demo site, so that is what I tried to do. Here is what happened:

mike@mike-HP-ProBook-4520s:**~/frappe-bench$ bench get-app erpnext_demo https://github.com/frappe/erpnext_demo**
INFO:bench.app:getting app erpnext_demo
Cloning into 'erpnext_demo'...
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 73 (delta 5), reused 35 (delta 1), pack-reused 0
Unpacking objects: 100% (73/73), done.
Checking connectivity... done.
installing erpnext_demo
INFO:bench.app:installing erpnext_demo
Wrote ./assets/js/print_format_v3.min.js - 18k
Wrote ./assets/js/frappe-web.min.js - 132k
Wrote ./assets/js/form.min.js - 136k
Wrote ./assets/js/report.min.js - 158k
Wrote ./assets/js/erpnext.min.js - 71k
Wrote ./assets/css/list.min.css - 7k
Wrote ./assets/js/item-dashboard.min.js - 6k
Wrote ./assets/js/d3.min.js - 343k
Wrote ./assets/css/report.min.css - 7k
Wrote ./assets/css/frappe-web.css - 53k
Wrote ./assets/js/list.min.js - 82k
Wrote ./assets/js/dialog.min.js - 61k
Wrote ./assets/js/desk.min.js - 238k
Wrote ./assets/css/form.min.css - 4k
Wrote ./assets/js/editor.min.js - 26k
Wrote ./assets/css/erpnext.css - 3k
Wrote ./assets/js/libs.min.js - 883k
Wrote ./assets/js/erpnext-web.min.js - 2k
Wrote ./assets/css/desk.min.css - 263k
Wrote ./assets/css/module.min.css - 2k
[sudo] password for mike: 
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: ERROR (spawn error)
mike@mike-HP-ProBook-4520s:~/frappe-bench$ 

mike@mike-HP-ProBook-4520s:**~/frappe-bench$ bench new-site mike**
MySQL root password: 
Installing frappe...
Updating frappe                     : [========================================]
Updating country info               : [========================================]
Set Administrator password: 
Re-enter Administrator password: 
Installing fixtures...
*** Scheduler is disabled ***
mike@mike-HP-ProBook-4520s:~/frappe-bench$ 

mike@mike-HP-ProBook-4520s:**~/frappe-bench$ bench --site mike install-app erpnext** 
Installing erpnext...
Updating erpnext                    : [========================================]
Installing fixtures...
mike@mike-HP-ProBook-4520s:~/frappe-bench$ 

mike@mike-HP-ProBook-4520s:~/frappe-bench$ bench --site mike install-app erpnext_demo
Installing erpnext_demo...
Complete Setup...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mike/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/mike/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mike/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/mike/frappe-bench/apps/frappe/frappe/commands/site.py", line 149, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/mike/frappe-bench/apps/frappe/frappe/installer.py", line 142, in install_app
    frappe.get_attr(after_install)()
  File "/home/mike/frappe-bench/apps/erpnext_demo/erpnext_demo/utils.py", line 32, in make_demo
    erpnext_demo.make_demo.make()
  File "/home/mike/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 18, in make
    setup()
  File "/home/mike/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 23, in setup
    complete_setup()
  File "/home/mike/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 66, in complete_setup
    "language": "english"
  File "/home/mike/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 37, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 36, in setup_complete
    if args.domain.lower() == 'education':
AttributeError: 'NoneType' object has no attribute 'lower'
mike@mike-HP-ProBook-4520s:~/frappe-bench$ 

As you can see, I was unsuccessful. All I want is some demo that I can practice with. I need to know the layout that ERPNext requires for the import (presumably XML) files. I had hoped that by setting up a demo site that I could do a data export, followed by an import. 

Remember, this is for version 7...

Please help! 
Regards,
Mike

**Comment by rmehta** [comment]
erpnext_demo is now deprecated

Run (on a new site):
```
bench --site [site] execute erpnext.demo.demo.make
```

**Comment by stroudmw** [comment]
That didn't work. I have resubmitted this as #6151
