### ISSUE TITLE
ERPNext 7 Demo Data 

### ISSUE THREAD

**Issue by stroudmw** [frappe/erpnext#6151]
#6142 I've tried the solution but this is what happened. FYI I'm running Ubuntu 16.04 64  bit.

mike@mike-HP-ProBook-4520s:~/frappe-bench$ **bench new-site miketest**
MySQL root password: 
Installing frappe...
Updating frappe                     : [========================================]
Updating country info               : [========================================]
Set Administrator password: 
Re-enter Administrator password: 
Installing fixtures...
*** Scheduler is disabled ***

mike@mike-HP-ProBook-4520s:~/frappe-bench$ **bench --site miketest install-app erpnext** 
Installing erpnext...
Updating erpnext                    : [========================================]
Installing fixtures...

mike@mike-HP-ProBook-4520s:~/frappe-bench$ **bench --site miketest execute erpnext.demo.demo.make**
Complete Setup...
Simulating 2016-03-25Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mike/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/mike/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mike/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mike/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/mike/frappe-bench/apps/frappe/frappe/commands/utils.py", line 110, in execute
    ret = frappe.get_attr(method)(*args, **kwargs)
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/demo/demo.py", line 34, in make
    simulate()
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/demo/demo.py", line 73, in simulate
    accounts.work()
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/demo/user/accounts.py", line 47, in work
    make_payment_entries("Sales Invoice", "Accounts Receivable")
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/demo/user/accounts.py", line 69, in make_payment_entries
    {"report_date": frappe.flags.current_date })["result"] if r[2]==ref_doctype]))
  File "/home/mike/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 88, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 281, in execute
    return ReceivablePayableReport(filters).run(args)
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 19, in run
    columns = self.get_columns(party_naming_by, args)
  File "/home/mike/frappe-bench/apps/erpnext/erpnext/accounts/report/accounts_receivable/accounts_receivable.py", line 56, in get_columns
    "{range1}-{range2}".format(range1=self.filters["range1"]+1, range2=self.filters["range2"]),
TypeError: coercing to Unicode: need string or buffer, int found
mike@mike-HP-ProBook-4520s:~/frappe-bench$

**Comment by nabinhait** [comment]
@neilLasrado has fixed in local, will push it tomorrow.
