### ISSUE TITLE
Error in POS Invoice

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#6228]
Replicating in bandra.erpnext.com

Keep POS Invoice page open for sometime, and this error should come.

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 191, in make_invoice
    submit_invoice(si_doc, name)
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 234, in submit_invoice
    save_invoice(e, si_doc, name)
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 240, in save_invoice
    si_doc.insert()
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 212, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 710, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 661, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 839, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 822, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2016-08-29/apps/frappe/frappe/model/document.py", line 655, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 53, in validate
    super(SalesInvoice, self).validate()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/selling_controller.py", line 32, in validate
    super(SellingController, self).validate()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/accounts_controller.py", line 35, in validate
    self.calculate_taxes_and_totals()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/accounts_controller.py", line 93, in calculate_taxes_and_totals
    calculate_taxes_and_totals(self)
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 16, in __init__
    self.calculate()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 27, in calculate
    self.calculate_total_advance()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 417, in calculate_total_advance
    self.calculate_outstanding_amount()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 424, in calculate_outstanding_amount
    self.calculate_paid_amount()
  File "/home/frappe/benches/bench-2016-08-29/apps/erpnext/erpnext/controllers/taxes_and_totals.py", line 456, in calculate_paid_amount
    payment.base_amount = flt(payment.amount * self.doc.conversion_rate)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by rohitwaghchaure** [comment]
This issue is fixed, we'll release it soon
