### ISSUE TITLE
Configuration wizard error

### ISSUE THREAD

**Issue by cereneto** [frappe/erpnext#6385]
Hi all,

I have an error at the end of configuration wizard when I execute it in french. If I do the same setup but with english language, everything all right. The error are : 

Traceback (most recent call last):
  File "/home/radpp/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/radpp/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/__init__.py", line 882, in call
    return fn(*args, **newargs)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 36, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/radpp/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 50, in setup_complete
    setup_domain(args.get('domain'))
  File "/home/radpp/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/domainify.py", line 78, in setup_domain
    setup_desktop_icons(data)
  File "/home/radpp/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/domainify.py", line 88, in setup_desktop_icons
    set_desktop_icons(data.desktop_icons)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 189, in set_desktop_icons
    frappe.db.set_value('Desktop Icon', icon_name, 'standard', 1)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/database.py", line 608, in set_value
    {2}""".format(dt, field, conditions), values, debug=debug)
  File "/home/radpp/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/radpp/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/radpp/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry 'Bon de commande-Administrator-1' for key 'unique_module_name_owner_standard'")

Is there a fix for this?

Best reagards.

René Mailloux

**Comment by cereneto** [comment]
I've found the problem. The translation in fr.csv for sales order and purchase order is the same; "Bon de commande". I've change sales order translation for "Bon de commande de vente" and purchases order translation for "Bon de commande d'achat" and everything work fine.

**Comment by nabinhait** [comment]
Fixed in the product via https://github.com/frappe/erpnext/pull/6562
