### ISSUE TITLE
V7, Cannot add Customer Information to any Sales Doc Type (HOSTED)

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#6446]
After the new update, we are unable to add the customer name to Delivery Notes, Leads, Opportunities, Sales Orders, or Quotations.

See Error Below:

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/desk/search.py", line 12, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/desk/search.py", line 34, in search_widget
    searchfield, start, page_len, filters, as_dict=as_dict)
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-09-07/apps/erpnext/erpnext/controllers/queries.py", line 113, in customer_query
    'page_len': page_len
  File "/home/frappe/benches/bench-2016-09-07/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/benches/bench-2016-09-07/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2016-09-07/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'address_html' in 'field list'")
Report this issue

**Comment by nabinhait** [comment]
I have fixed the issue, please check and confirm. It was related to your customization in Search Field value for Customer.
