### ISSUE TITLE
Remove python-ldap from requirements.txt. Let users install when they want to integrate LDAP

### ISSUE THREAD

**Issue by osmanahmed2712** [frappe/erpnext#6463]
[root@localhost erpnext]# bash setup_frappe.sh
Installing for centos 7 amd64
In case you encounter an error, you can post on https://discuss.frappe.io

Adding centos mariadb repo
Installing packages for centos. This might take time...
Installing wkhtmltopdf
Configuring CentOS services
Starting services
Adding frappe user
Installing frappe-bench
Already using interpreter /usr/bin/python
INFO:bench.app:getting app frappe
Cloning into 'frappe'...
INFO:bench.app:installing frappe
Command "/home/frappe/frappe-bench/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nviXGX/python-ldap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6qROVl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/frappe/frappe-bench/env/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-build-nviXGX/python-ldap/
installing frappe
Traceback (most recent call last):
  File "/bin/bench", line 9, in <module>
    load_entry_point('bench==4.1.0', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/make.py", line 19, in init
    verbose=verbose, clone_from=clone_from)
  File "/home/frappe/bench-repo/bench/utils.py", line 56, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, build_asset_files=False, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 73, in get_app
    install_app(app=app_name, bench_path=bench_path, verbose=verbose)
  File "/home/frappe/bench-repo/bench/app.py", line 103, in install_app
    find_links=find_links))
  File "/home/frappe/bench-repo/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
[root@localhost erpnext]#

**Comment by rmehta** [comment]
@saurabh6790  remove pyldap from requirements. Let users install it when they want to install the ldap integration. Show instructions on how to install the ldap module

**Comment by rmehta** [comment]
@osmanahmed2712 https://discuss.erpnext.com/t/frappe-v-7-1-beta-ldap-dependancies/15841

**Comment by osmanahmed2712** [comment]
Thank You
