### ISSUE TITLE
Article: How to make entry for Paypal account in payment entry

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#6506]
We can use below case for this
https://discuss.erpnext.com/t/payment-entry-problem/15720

**Comment by umairsy** [comment]
Not able to build locally from Develop branch. Content shared with @rohitwaghchaure .

Error message when local built.

```Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/commands/docs.py", line 43, in build_docs
    _build_docs_once(site, app, docs_version, target, local)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/commands/docs.py", line 70, in _build_docs_once
    make.make_docs(target, local)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/setup_docs.py", line 172, in make_docs
    self.write_files()
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/setup_docs.py", line 347, in write_files
    html = frappe.render_template(context.source, context)
  File "/Users/umairsayyed/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 50, in render_template
    return get_jenv().from_string(template).render(context)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/umairsayyed/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 47, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '/'
➜  frappe-bench 
```
