### ISSUE TITLE
Problem setting localhost SMTP server

### ISSUE THREAD

**Issue by slushpuppy** [frappe/erpnext#6581]
Hi,

I have an issue setting a local SMTP server for outgoing emails

This is my default outgoing account(only 1 email account)

http://i.imgur.com/txuy7QS.png

This is what happens when I try to send an email:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 251, in flush
    check_email_limit([])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 143, in check_email_limit
    smtp_server = SMTPServer()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 140, in **init**
    self.setup_email_account(append_to)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 143, in setup_email_account
    self.email_account = get_outgoing_email_account(raise_exception_not_set=False, append_to=append_to)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 62, in get_outgoing_email_account
    email_account = get_default_outgoing_email_account(raise_exception_not_set=raise_exception_not_set)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 92, in get_default_outgoing_email_account
    email_account.password = email_account.get_password()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 603, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password.py", line 19, in get_decrypted_password
    frappe.throw(_('Password not found'), frappe.AuthenticationError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 293, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in _raise_exception
    raise raise_exception, encode(msg)
AuthenticationError: Password not found

It's a local SMTP server, password should not be mandatory

**Comment by PawanMeh** [comment]
Appears this has been merged, closing it for now.
