### ISSUE TITLE
Adding new tax liability in Accounts causes crash

### ISSUE THREAD

**Issue by davemc50** [frappe/erpnext#6586]
OperationalError: (1054, "Unknown column 'tabCurrency.company' in 'where clause'")

There is no company field in tabCurrency

Accounts..Create new account in Current Liabilities .. Taxes

Tab to Currency field, get this error.

7.1.0-beta   Clean install, new database

Full error text
`Traceback (most recent call last):
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 884, in call
    return fn(*args, **newargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/search.py", line 12, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/desk/search.py", line 91, in search_widget
    as_list=not as_dict)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 1063, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabCurrency.company' in 'where clause'")
`

**Comment by nabinhait** [comment]
Can't replicate the issue. Which version are you using?

**Comment by davemc50** [comment]
The version is listed in the problem report. It is the latest trunk from Oct 9

It is rude of you to close the issue, when not even listing what you did to replicate it.  

It is straight forward to replicate, as above, is obviously a reference to a field that is not present.
