### ISSUE TITLE
demo.erpnext.com Login raises frappe.AuthenticationError

### ISSUE THREAD

**Issue by rish4bhn** [frappe/erpnext#6622]
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 114, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 47, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 104, in __init__
    self.login()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 119, in login
    self.authenticate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 188, in authenticate
    self.check_if_enabled(user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 195, in check_if_enabled
    self.fail('User disabled or missing')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 207, in fail
    raise frappe.AuthenticationError
AuthenticationError`

**Comment by nabinhait** [comment]
For now I have reset the password for the user demo@erpnext.com. 

@rmehta Can you please check and fix the actual issue, related to `update_password`?
