### ISSUE TITLE
Can not setup new instance of ERP Next

### ISSUE THREAD

**Issue by President** [frappe/erpnext#6744]
I have just installed ERP Next on Ubuntu 16.
Opened website:80 and started filling suggested properties. On the last page I receive this error:
```

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 36, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 27, in setup_complete
    create_sales_tax(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 250, in create_sales_tax
    if len(country_wise_tax)>0:
TypeError: object of type 'NoneType' has no len()
```

It is absolutely unclear what is it about and now to fix it. I entered some taxes, removed all of them - nothing helped.

**Comment by President** [comment]
PS. I am using country = Russia and I looked into the code - my file country_wise_tax.json do have Russia. So have no clue why this happens

**Comment by nabinhait** [comment]
@rohitwaghchaure send fix to hotfix branch

**Comment by rohitwaghchaure** [comment]
Hi @President 
Thanks for reporting an issue, we have [fixed](https://github.com/frappe/erpnext/pull/6750) the issue and we'll release it soon. It was because of translation Russia to Russian Federation.
