### ISSUE TITLE
[Error] V7 . The setup wizard is producing the following error

### ISSUE THREAD

**Issue by aambernath** [frappe/erpnext#6759]
The following error pops up. I think its got to do something with United Arab Emirates and Tax

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 36, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 27, in setup_complete
    create_sales_tax(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 250, in create_sales_tax
    if len(country_wise_tax)>0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by aambernath** [comment]
Ok we just need to add the country and its tax structure in data. sorry
