### ISSUE TITLE
Creating Timesheet from Sales Invoice

### ISSUE THREAD

**Issue by mnatalia** [frappe/erpnext#6805]
Traceback (most recent call last):
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
response = frappe.handler.handle()
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
execute_cmd(cmd)
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
ret = frappe.call(method, **frappe.form_dict)
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
return fn(*args, **newargs)
File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/timesheet/timesheet.py", line 302, in get_timesheet_data
'billing_hours': data[0].billing_hours,
IndexError: list index out of range

**Comment by rohitwaghchaure** [comment]
Hi @mnatalia 

Thanks for reporting an issue
I am not able to reproduce the issue at my side, can you provide the steps to reproduce the issue. If possible add screenshots or Gif for better understanding.

Also provide the version erpnext app

Thanks

**Comment by mnatalia** [comment]
Hi @rohitwaghchaure,

Thanks for your answer
I tried it on the https://demo.erpnext.com 
ERPNext: v7.1.5
Frappe Framework: v7.1.4

I tried to add new Timesheet documents from Sales Invoice
Sorry it is my first gif and it doesn't look nice


![output_nsvrbh](https://cloud.githubusercontent.com/assets/9428212/19965686/e600a762-a1d0-11e6-8a53-598454810252.gif)

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @mnatalia 

Thanks for sharing the Gif, we have fixed the issue and we'll release the fix soon

Thanks
