### ISSUE TITLE
Auto Email Report not working

### ISSUE THREAD

**Issue by mjomane** [frappe/erpnext#6821]
I was trying to create an Accounts Payable auto report
The new auto email feature won't work on my installation

```
Traceback (most recent call last):
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
response = frappe.handler.handle()
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
execute_cmd(cmd)
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
ret = frappe.call(method, **frappe.form_dict)
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
return fn(*args, **newargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 121, in send_now
auto_email_report.send()
File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 72, in send
data = self.get_report_content()
File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 45, in get_report_content
raw = report.get_data(limit=self.no_of_rows or 100, user = self.user, filters = self.filters)
File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 60, in get_data
out.append([d.split(':')[0] for d in data.get('columns')])
AttributeError: 'dict' object has no attribute 'split'
Report this issue
```

**Comment by yashodhank** [comment]
@mjomane are you still having this issue? tried `bench update`? share your version.
