### ISSUE TITLE
web》product

### ISSUE THREAD

**Issue by yyusea** [frappe/erpnext#6845]
Oops, a server error has occured

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 14, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 66, in get_page_context_from_template
    if os.path.exists(o) and not os.path.isdir(o):
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-56: ordinal not in range(128)

**Comment by KanchanChauhan** [comment]
@yyusea Are you still facing this issue?

**Comment by rmehta** [comment]
Tried a non ascii charcter and seems to work alright. What version are you on?
