### ISSUE TITLE
Error when selecting standard reply

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#6887]
When you select standard reply from dropdown in email window following error occurs:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/standard_reply/standard_reply.py", line 20, in get_standard_reply
    return frappe.render_template(standard_reply.response, doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 50, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "
```

**Comment by KanchanChauhan** [comment]
On what version and on what doctype it is happening. Tested on Sales Order and Stock, could not replicate it.

**Comment by sp9leo** [comment]
V7.1.7 also tested on demo.erpnext.com
It seems it happens only when you add a code ie. `{{doc.name}}`. Sorry, forgot to mention that ;)

**Comment by KanchanChauhan** [comment]
Instead of {{ doc.name }}, just use {{ name }}

**Comment by sp9leo** [comment]
That works thank you. 
You should also update the example on standard reply form to avoid confusion.
```
Transaction {{ doc.name }} has exceeded Due Date. Please take necessary action.

Details

- Customer: {{ doc.customer }}
- Amount: {{ doc.grand_total }}`
```

**Comment by KanchanChauhan** [comment]
@sp9leo Yes, on it. Thanks for reporting.
https://github.com/frappe/frappe/pull/2283
