### ISSUE TITLE
Error with mysql while I'm installing erpnext 

### ISSUE THREAD

**Issue by tienpham317** [frappe/erpnext#6895]
When I run command to install erpnext "bench --site site1.local install-app erpnext", this error is shown:
frappe@tien-HP-Notebook:~/frappe-bench-1$ bench --site site1.local install-app erpnext
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
main()
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
click.Group(commands=commands)(prog_name='bench')
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 716, in call
return self.main(*args, **kwargs)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/commands/init.py", line 24, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/commands/site.py", line 152, in install_app
_install_app(app, verbose=context.verbose)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/installer.py", line 100, in install_app
frappe.clear_cache()
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/init.py", line 468, in clear_cache
for fn in get_hooks("clear_cache"):
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/init.py", line 783, in get_hooks
hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/utils/redis_wrapper.py", line 68, in get_value
val = generator()
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/init.py", line 761, in load_app_hooks
for app in [app_name] if app_name else get_installed_apps(sort=True):
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/init.py", line 725, in get_installed_apps
installed = json.loads(db.get_global("installed_apps") or "[]")
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/database.py", line 655, in get_global
return self.get_default(key, user)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/database.py", line 667, in get_default
d = self.get_defaults(key, parent)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/database.py", line 673, in get_defaults
defaults = frappe.defaults.get_defaults(parent)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/defaults.py", line 72, in get_defaults
globald = get_defaults_for()
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/defaults.py", line 180, in get_defaults_for
where parent = %s order by creation""", (parent,), as_dict=1)
File "/home/frappe/frappe-bench-1/apps/frappe/frappe/database.py", line 137, in sql
self._cursor.execute(query, values)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
self.errorhandler(self, exc, value)
File "/home/frappe/frappe-bench-1/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table '1bd3e0294da19198.tabDefaultValue' doesn't exist")

Need some help to prove this issue! Does anyone have any idea about it?

**Comment by kickapoo** [comment]
Please create a topic for this in https://discuss.erpnext.com/. 
You will get more and faster help rather in github issue tracker.
