### ISSUE TITLE
Shipping rule error

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#6904]
This happens every time you make a new shipping rule and you want it valid for specific country. 
Some sort of workaround is to check worldwide shipping, wait few minutes open the rule and then uncheck worldwide shipping and select country. Currently on latest version, but it has happened before also.

![image](https://cloud.githubusercontent.com/assets/15377465/20214473/b315a87c-a80e-11e6-95d9-2804f460ae7d.png)

**Comment by KanchanChauhan** [comment]
@sp9leo When do you get this error message?
I am not able to replicate it. This error message appears only if there is no country selected and Worldwide Shipping is unchecked, which is the expected behavior.

**Comment by sp9leo** [comment]
Hi! Tested it again and still the same behavior. 
Steps I made are:
- make new shipping rule
- fill all the fields
- select country (via add new row) It defaults to "slovenia"
- After clicking save, message appears.

Sometimes if I select different country it gets trough, some other time if you try to change country after the error message, system hangs for a while. Perhaps something is wrong with my setup or database. I tested on two different virtualbox setups one running v7.0.55 another one 7.1.19.
However I was able to solve issue with a workaround decsribed in my first post.

**Comment by rmehta** [comment]
I am unable to replicate. Can you check the JS console on this?

**Comment by sp9leo** [comment]
This is from JS console on chrome. Erpnext version 7.1.25

Thank you

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 252, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 754, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 883, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 866, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/shipping_rule/shipping_rule.py", line 29, in validate
    frappe.throw(_("Please specify a country for this Shipping Rule or check Worldwide Shipping"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 293, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in _raise_exception
    raise raise_exception, encode(msg)
ValidationError: Please specify a country for this Shipping Rule or check Worldwide Shipping

desk.min.js:150 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 252, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 754, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 883, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 866, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/shipping_rule/shipping_rule.py", line 29, in validate
    frappe.throw(_("Please specify a country for this Shipping Rule or check Worldwide Shipping"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 293, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in _raise_exception
    raise raise_exception, encode(msg)
ValidationError: Please specify a country for this Shipping Rule or check Worldwide Shipping
`

**Comment by rmehta** [comment]
Unfortunately we are not able to replicate this on 7.2.0-beta

Please update the system and check after the 7.2 release tomorrow.
