### ISSUE TITLE
Error on update: erpnext.patches.v7.0.fix_duplicate_icons

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#6999]
erpnext 6.19.0
frappe 6.20.2

Running bench update --upgrade,  I get this:

INFO:bench.utils:updating bench
Already up-to-date.
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
* branch master -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
From https://github.com/frappe/erpnext
* branch master -> FETCH_HEAD
Already up-to-date.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Migrating site1.local
Executing finally:frappe.patches.v6_24.sync_desktop_icons in site1.local (1bd3e0294d)
Success
Executing erpnext.patches.v7_0.fix_duplicate_icons in site1.local (1bd3e0294d)
Module import failed for Desktop Icon (frappe.core.doctype.desktop_icon.desktop_icon)
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in runmodule_as_main
"main", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in runcode
exec code in run_globals
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in 
main()
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
click.Group(commands=commands)(prog_name='bench')
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in call
return self.main(*args, **kwargs)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 209, in migrate
migrate(context.verbose, rebuild_website=rebuild_website)
File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 30, in migrate
frappe.modules.patch_handler.run_all()
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
if not run_single(patchmodule = patch):
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
return execute_patch(patchmodule, method, methodargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
frappe.get_attr(patchmodule.split()[0] + ".execute")()
File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v7_0/fix_duplicate_icons.py", line 11, in execute
sync_desktop_icons()
File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 296, in sync_desktop_icons
sync_from_app(app)
File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 325, in sync_from_app
'owner': 'Administrator'
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 589, in get_doc
return frappe.model.document.get_doc(arg1, arg2)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 45, in get_doc
controller = get_controller(doctype)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 34, in get_controller
module = load_doctype_module(doctype, module_name)
File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 171, in load_doctype_module
doctype_python_modules[key] = frappe.get_module(module_name)
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 654, in get_module
return importlib.import_module(modulename)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
import(name)
ImportError: No module named desktop_icon.desktop_icon

**Comment by rmehta** [comment]
#7010

**Comment by Tropicalrambler** [comment]
And thanks again, this fix enabled me to complete the update from v6 to v7 successfully!
