### ISSUE TITLE
Mail Settings Erroring out with Gmail

### ISSUE THREAD

**Issue by mayank13** [frappe/erpnext#7048]
Getting the following error while setting up email:
[Errno 104] Connection reset by peer

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 68, in connect_pop
    self.pop = Timed_POP3_SSL(self.settings.host, timeout=frappe.conf.get("pop_timeout"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 422, in __init__
    self._super.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/poplib.py", line 360, in __init__
    self.sslobj = ssl.wrap_socket(self.sock, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

**Comment by ranjanprj** [comment]
Gmail has recently made changes to the way Gmail client can access it's mail due to security concerns.
It uses OAuth 2.0 mechanism to redirect you from your custom client to your gmail account and provides tokens which can be used to access and send emails.

I think a feature request should be made to enable the new Gmail account activation in ERPNext.
