### ISSUE TITLE
ImportError: No module named repost_gle_for_pi_with_update_stock

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7064]
Hello, i've tried to upgrade today and I receive this error. Any ideas?

```
Executing erpnext.patches.v7_1.repost_gle_for_pi_with_update_stock in extranet.ioweb.gr (e3bd60fe38)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/erpnext5/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/commands/site.py", line 209, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/migrate.py", line 30, in migrate
    frappe.modules.patch_handler.run_all()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 867, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/opt/erpnext5/frappe-bench/apps/frappe/frappe/__init__.py", line 651, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named repost_gle_for_pi_with_update_stock
```

**Comment by ci2014** [comment]
Same issue here

**Comment by marceloabelda** [comment]
same here

**Comment by pablomoreira** [comment]
another one

**Comment by marceloabelda** [comment]
edit
nano +355 frappe-bench/apps/erpnext/erpnext/patches.txt
comment
#erpnext.patches.v7_1.repost_gle_for_pi_with_update_stock
bench update
good luck

**Comment by nabinhait** [comment]
Thanks for reporting, pushed a fix in develop branch, please update again.
