### ISSUE TITLE
Server Error when "Edit Profile" is executed in Website Profile View [v7.1.19]

### ISSUE THREAD

**Issue by Nathaniel401** [frappe/erpnext#7073]
When you login, and then go to "My Profile" in the website view, and hit "Edit Profile" you get the below. This is in version v7.1.19

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 18, in get_context
    context = build_context(context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 73, in build_context
    ret = context.doc.get_context(context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 122, in get_context
    if frappe.form_dict.name and not has_web_form_permission(self.doc_type, frappe.form_dict.name):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 425, in has_web_form_permission
    elif frappe.has_website_permission(name, ptype=ptype):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 505, in has_website_permission
    doc = get_doc(doctype, doc)
UnboundLocalError: local variable 'doctype' referenced before assignment`

**Comment by KanchanChauhan** [comment]
Tested for website user and system user. I am not getting an errors. Can you please try again.

**Comment by Nathaniel401** [comment]
@KanchanChauhan tried on two instances, even a fresh install. I am on Ubuntu 16.04 LTS and set it up in a production configuration. Both instances have the same issue with both website and system user. 

Is there anything else I can provide to give more insight?

**Comment by Nathaniel401** [comment]
I attempted a fresh install on 14.04 LTS, and the same error @KanchanChauhan 
![error](https://cloud.githubusercontent.com/assets/1185140/20645956/df6c9892-b43c-11e6-8d85-17837dd2ec9b.png)

**Comment by Nathaniel401** [comment]
I think I figured it out. The username in 7.1.x when you create a user is the email address, but when the URL passes the email address as the username to edit the profile, the "@" symbol screws it up. I logged in with the Administrator account, which the username is Administrator, and it worked fine. @KanchanChauhan

**Comment by azad17** [comment]
This issue still exists. some email id's that having a '+' sign  in it are not able to open the edit profile. it gives 404 error ! .
Because Frappe failed to decode the url of (/update-profile?name=test.mail.com) when a '+' signs appears there
