### ISSUE TITLE
Can't Process Salary - Error -  Incorrect number of General Ledger Entries found

### ISSUE THREAD

**Issue by Ooops-404** [frappe/erpnext#7134]
Hi,

for the first time I am not able to fully process salary(ies).
I am able to Create Salary Slip, Submit Salary Slip but not Process the Pament.

First it asked to edit the basic component and add a default account. Which I did,, added the account Salary.
Then back on the process payroll page, I added the bank account to the Payment Account
field and clicked on "Make Bank Entry"......... and bam. I get an error (below)

``
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/handler.py", line 67, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/desk/form/run_method.py", line 41, in runserverobj
    r = doc.run_method(method, **args)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/model/document.py", line 655, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/model/document.py", line 883, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/model/document.py", line 866, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/model/document.py", line 649, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/erpnext/erpnext/hr/doctype/process_payroll/process_payroll.py", line 266, in make_journal_entry
    frappe.msgprint(e)
  File "/home/frappe/benches/bench-2016-11-28-a/apps/frappe/frappe/__init__.py", line 292, in msgprint
    message_log.append(json.dumps(out))
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValidationError('Incorrect number of General Ledger Entries found. You might have selected a wrong Account in the transaction.',) is not JSON serializable
Report this issue
``

I saw allot of issues about the HR module, but none of the reported errors seemed to be like this one.

**Comment by KanchanChauhan** [comment]
I am not able to replicate the issue.
Can you please provide more details. What type of account is Salary and what account you selected on Payment Account and what type of account was that.

**Comment by Ooops-404** [comment]
Hi @KanchanChauhan 

Thank you for wanting to help, i think it may be easier to show you. Please see attachments.

Salary Account
![image](https://cloud.githubusercontent.com/assets/9021875/20865737/6506cf60-ba12-11e6-97d7-7347e6f420e4.png)


Bank account
![image](https://cloud.githubusercontent.com/assets/9021875/20865751/ce153b86-ba12-11e6-87c8-a678e5b7eaf7.png)

**Comment by nabinhait** [comment]
@Ooops-404 Have you selected "Salary Account" in all the Salary Component records? And in the Payment Account field, have you selected "Bank Account"? Please confirm.

**Comment by Ooops-404** [comment]
@nabinhait 
Yes.

And I just tried again and now it works. This was definitely a bug that was in the meanwhile solved.
