### ISSUE TITLE
Error while updating 7.1.21

### ISSUE THREAD

**Issue by phamviet** [frappe/erpnext#7166]
Executing erpnext.patches.v7_0.update_status_of_po_so in abc (a9993e364706816a)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/viet/frappe/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/viet/frappe/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/viet/frappe/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/viet/frappe/apps/frappe/frappe/commands/site.py", line 209, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/Users/viet/frappe/apps/frappe/frappe/migrate.py", line 30, in migrate
    frappe.modules.patch_handler.run_all()
  File "/Users/viet/frappe/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/Users/viet/frappe/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/Users/viet/frappe/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/Users/viet/frappe/apps/erpnext/erpnext/patches/v7_0/update_status_of_po_so.py", line 10, in execute
    update_so_per_delivered_per_billed()
  File "/Users/viet/frappe/apps/erpnext/erpnext/patches/v7_0/update_status_of_po_so.py", line 35, in update_so_per_delivered_per_billed
    where parent = `tabSales Order`.name), 2)""")
  File "/Users/viet/frappe/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/viet/frappe/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1048, "Column 'per_billed' cannot be null")

**Comment by nabinhait** [comment]
fixed, will be released by the end of today
