### ISSUE TITLE
Error when clicking on main menu, top right of screen, "view website" - resolved with V 7.2 please close

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#7196]
I am using Erpnext SAAS version.

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/context.py", line 14, in get_context
    context = get_page_context(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/router.py", line 21, in resolve_route
    return get_page_context_from_doctype(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/router.py", line 72, in get_page_context_from_doctype
    page_info = get_page_info_from_doctypes(path)
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/website/router.py", line 104, in get_page_info_from_doctypes
    {1}""".format(doctype, condition), values=values, as_dict=True):
  File "/home/frappe/benches/bench-2016-12-06-a/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/benches/bench-2016-12-06-a/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2016-12-06-a/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'route' in 'field list'")

**Comment by fblauer** [comment]
It happens when I try to access anything on the external web site (not the erpnext internal apps)

**Comment by fblauer** [comment]
Started happening last week some time. Just wondering if all the other SAAS users are having the same problem?
