### ISSUE TITLE
error on uninstall-app erpnext

### ISSUE THREAD

**Issue by RobertSchouten** [frappe/erpnext#7197]
on bench uninstall-app erpnext

removing Module Projects...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 315, in uninstall
    remove_app(app, dry_run, yes)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 211, in remove_app
    frappe.delete_doc("Module Def", module_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 621, in delete_doc
    ignore_permissions, flags)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 93, in delete_doc
    check_if_doc_is_linked(doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 180, in check_if_doc_is_linked
    item.parent or item.name), frappe.LinkExistsError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 293, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Module Def <a href="#Form/Module Def/Projects">Projects</a> is linked with Web Form <a href="#Form/Web Form/tasks">tasks</a>

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/frappe/pull/2446
