### ISSUE TITLE
BOM Tree Expand All Error

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#7212]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/treeview.py", line 22, in get_all_nodes
    to_check = [d.value for d in data if d.expandable]
TypeError: 'NoneType' object is not iterable
```

**Comment by pratu16x7** [comment]
Can't seem to replicate it. Any specific level of nesting on which it occurs?

**Comment by KanchanChauhan** [comment]
@ishanloya Can we close this one, not able to replicate. Or please provide steps to replicate. Just the error snapshot does not help.

**Comment by ishanloya** [comment]
@pratu16x7 @KanchanChauhan  Yes it can be closed. I think it was fixed at some point. Thanks.
