### ISSUE TITLE
UnicodeEncodeError when first running on a fresh server

### ISSUE THREAD

**Issue by danieldids** [frappe/erpnext#7239]
After installing erpNext in a fresh new virtual server (ubuntu 14.04 64bits) and running for the first time, I can go all the wizard steps, but it fails when I hit continue in the last step. The message last line is as follows:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 48: ordinal not in range(128)

(and some more stuff, but this is the last line of the message error).

Interestingly, I can finish the wizard if the language selected in the beginning is English, but it doesn't work if I run the wizard in pt-BR.

**Full error message:**

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 39, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 33, in setup_complete
    create_letter_head(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 453, in create_letter_head
    fileurl = save_file(filename, content, "Letter Head", _("Standard"), decode=True).file_url
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 180, in save_file
    f.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 754, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 883, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 866, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 71, in validate
    self.validate_file()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 134, in validate_file
    if not os.path.exists(get_files_path(self.file_name.lstrip("/"))):
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 48: ordinal not in range(128)

**Comment by applepipe** [comment]
I have a similar issue with dropbox integration, using pt-BR as well.

"{'retry': 0, 'log': <function log at 0xb714aa74>, 'site': u'erpnext.vm', 'event': u'daily_long', 'method_name': u'frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily', 'method': <function take_backups_daily at 0xb7153d4c>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 158, in take_backups_daily
    take_backups_if("Daily")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 165, in take_backups_if
    take_backup_to_dropbox()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 178, in take_backup_to_dropbox
    frappe.errprint(error_message)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 230, in errprint
    print cstr(msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 8: ordinal not in range(128)"

**Comment by danieldids** [comment]
More info: I've tried removing "special" characters, like ç, ã, ó (common in pt-BR) from whatever info I was filling in in the first wizard, but it didn't work too.

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this
