### ISSUE TITLE
v7.2.0-beta Problem with editor

### ISSUE THREAD

**Issue by mnatalia** [frappe/erpnext#7241]
Missed headers for two sections in the editor field

![screenshot from 2016-12-15 23 56 13](https://cloud.githubusercontent.com/assets/9428212/21243687/8e0b0f02-c322-11e6-9a8e-f11b7540949c.png)

also when I tried to add image to editor with name "ääää.jpg" I received error 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 223, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 190, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 389, in _validate
    self._extract_images_from_text_editor()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 807, in _extract_images_from_text_editor
    extract_images_from_doc(self, df.fieldname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 100, in extract_images_from_doc
    content = extract_images_from_html(doc, content)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 133, in extract_images_from_html
    content = re.sub(']*src\s*=\s*["\'](?=data:)(.*?)["\']', _save_file, content)
  File "/home/frappe/frappe-bench/env/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 126, in _save_file
    file_url = save_file(filename, content, doctype, name, decode=True).get("file_url")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 181, in save_file
    f.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 879, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 862, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 72, in validate
    self.validate_file()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py", line 135, in validate_file
    if not os.path.exists(get_files_path(self.file_name.lstrip("/"))):
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-35: ordinal not in range(128)

**Comment by rmehta** [comment]
fixed
