### ISSUE TITLE
ERPNext Demo not working

### ISSUE THREAD

**Issue by akhileshdarjee** [frappe/erpnext#7251]
Hi Team,

I'm getting following error on console when trying to logging in demo account:

POST https://demo.erpnext.com/ 401 (UNAUTHORIZED)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
call @ frappe-web.min.js:631
(anonymous) @ VM65:262
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

frappe-web.min.js:642
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 114, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 47, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 104, in __init__
    self.login()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 119, in login
    self.authenticate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 188, in authenticate
    self.check_if_enabled(user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 195, in check_if_enabled
    self.fail('User disabled or missing')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 207, in fail
    raise frappe.AuthenticationError
AuthenticationError

I tried in "Incognito" mode and also hard refreshed the page, but nothing seems to work.
Steps to get the error:

1. Visit: https://demo.erpnext.com/
2. Click on "Launch Demo" without entering "Email ID"

**Comment by strixaluco** [comment]
For me it hangs with `Logging in...` over the button.

**Environment:**
Firefox ESR 45.5.1
Chromium 55.0.2883.75

**Comment by vrms** [comment]
I just logged in successfully to demo.erpnext.com

Firefix @Android 4.4

**Comment by yashodhank** [comment]
Seems to be fixed now and work well in
Chrome Version 55.0.2883.95 (64-bit)
Firefox Version 50.1.0
Safari Version 10.0.1 (12602.2.14.0.7)
