### ISSUE TITLE
[v7.2] Error on print

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7266]
Hello,

I'm getting this error when I try to print some documents with this kind of characters "ç à é ô" very common in pt-BR.

"Oops, a server error has occured

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 139, in build_page
    print 2, context.title, context.source
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 14: ordinal not in range(128)"

**Comment by rmehta** [comment]
Already fixed. Can you replicate?

**Comment by applepipe** [comment]
@rmehta working fine, thank you!
