### ISSUE TITLE
Dropbox setup fails

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#7301]
Receiving the following error when clicking 'Allow DropBox Access'

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 104, in get_dropbox_authorize_url
    request_token = sess.obtain_request_token()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/session.py", line 216, in obtain_request_token
    response = self.rest_client.POST(url, headers=headers, params=params, raw_response=True)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 322, in POST
    return cls.IMPL.POST(*n, **kw)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 260, in POST
    is_json_request=is_json_request)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/dropbox/rest.py", line 235, in request
    raise ErrorResponse(r, r.read())
ErrorResponse: [401] u'Unauthorized'
```

**Comment by rmehta** [comment]
Might be a problem with your API keys or passwords

**Comment by cgpurbaugh** [comment]
It seems copying and pasting doesn't work with the app secret.  I had to manually enter it.  But it's working now!

**Comment by cgpurbaugh** [comment]
Well, by working I mean it isn't giving an error.  But Clicking 'Take Backup now' has had no effect.  How can I check the status?
