### ISSUE TITLE
[Bug] Adding mandatory custom field to Territory causes issues

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#7305]
I've added a mandatory custom field via Customize Form to Territory

![image](https://cloud.githubusercontent.com/assets/6697133/21448283/dd3fb962-c906-11e6-8383-1e89a0aaf926.png)

Field shows up properly
![image](https://cloud.githubusercontent.com/assets/6697133/21448327/7902b192-c907-11e6-83f4-fa6569b65154.png)

But, on saving it gives a MandatoryError 

![image](https://cloud.githubusercontent.com/assets/6697133/21448337/86f7ee84-c907-11e6-8d8c-c3ed0425ec98.png)

```
Traceback (most recent call last):
  File "/home/frappe/frappe-master/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-master/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-master/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-master/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-master/apps/frappe/frappe/desk/treeview.py", line 36, in add_node
    doc.save()
  File "/home/frappe/frappe-master/apps/frappe/frappe/model/document.py", line 233, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-master/apps/frappe/frappe/model/document.py", line 252, in _save
    self.insert()
  File "/home/frappe/frappe-master/apps/frappe/frappe/model/document.py", line 204, in insert
    self._validate()
  File "/home/frappe/frappe-master/apps/frappe/frappe/model/document.py", line 384, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-master/apps/frappe/frappe/model/document.py", line 608, in _validate_mandatory
    name=self.name))
MandatoryError: [Territory, Test Area]: area_id
```

Can recreate on Master and Develop. Made sure that the parent node _does_ have an area ID and there are no other child nodes for that node. 

## Edit 

Found the issue. treeview.py is hardcoded to only take a the node name, group_node property and the parent node data 😕 
https://github.com/frappe/frappe/blob/develop/frappe/desk/treeview.py#L48

**Comment by rmehta** [comment]
@vjFaLk you should be able to debug this! Try and trace the request

**Comment by vjFaLk** [comment]
@rmehta I did notice about 5 mins after I made the issue, hah (Check the edit). I've implemented a fix for myself via hooks for now, but I'll have to rewrite some of treeview.py if I want to fix it.

**Comment by rmehta** [comment]
The right opportunity to make a contribution!
