### ISSUE TITLE
DN and Warehouse selectionsErrors in V 7.2 Production with exiting Database

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#7315]
Good day Community and Developers i just update to lastest 7.2.0 and im having a small issue when changing warehouse in sales order , sales invoices and quotation.

this error is throw in console:

Traceback (most recent call last):
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
response = frappe.handler.handle()
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
execute_cmd(cmd)
File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
ret = frappe.call(method, **frappe.form_dict)
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
return fn(*args, **newargs)
TypeError: get_bin_details_and_serial_nos() takes exactly 4 arguments (3 given)

I can just ignore the error and save the new warehouse but what could be causing this? Any feedback apreciated.

Also Im facing an issue when creating new delivery notes from sales order or sales invoices where i cant create new DN linked to the other doctypes.

Uncaught TypeError: Cannot set property 'get_route_options_for_new_doc' of undefined
at Class.setup_quality_inspection (http://192.168.1.104/assets/js/erpnext.min.js:154:260)
at Class.onload as _super
at Class.onload (eval at setup (http://192.168.1.104/assets/js/form.min.js:258:109), :351:8)
at Class.prototype.(anonymous function) as onload
at http://192.168.1.104/assets/js/form.min.js:256:92
at http://192.168.1.104/assets/js/form.min.js:255:478
at Function.map (http://192.168.1.104/assets/frappe/js/lib/jquery/jquery.min.js:2:3455)
at Class.trigger (http://192.168.1.104/assets/js/form.min.js:255:445)
at http://192.168.1.104/assets/js/form.min.js:76:148
at http://192.168.1.104/assets/js/form.min.js:255:478

**Comment by nabinhait** [comment]
Fixed the issue in local, will release in a while.
