### ISSUE TITLE
Problem after migration - UnicodeEncodeError: 'latin-1' codec can't encode characters in position ...

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7316]
Hi, 

I'm trying to migrate my site to another server using 
`bench backup` 
and 
`bench restore`
The setup in the servers was done using the installation script and both servers are running 7.2.1

Everything seems to be the same in the website in both servers however when I try to use my print formats I get the following error 

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/print.py", line 181, in get_html_and_style
    no_letterhead=no_letterhead, trigger_print=trigger_print),
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/print.py", line 108, in get_html
    template = get_template_from_string()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/print.py", line 105, in get_template_from_string
    print_format))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/print.py", line 212, in get_print_format
    if os.path.exists(path):
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 68-75: ordinal not in range(256)
```
//EDIT

As a sidenote it doesn't seem to matter what characters I put in the print format. Creating a new print format without data in it or a simple 'a' character still causes the same issue.

**Comment by ioweb-gr** [comment]
Never mind I'm answering my own question. It seems for OS File operations Python is using the system locale to determine encoding.
In my new server, the locale was not set to en_us.UTF-8 thus creating the issue. 

In short for anyone else that might face the same issue, 
for debian/ubuntu based servers make sure you run 
`dpkg-reconfigure locales` 
and select 
`en_US.UTF-8`

Then reboot the server after locale generation to make sure the locales are loaded.
Verify by running `locale` command.
