### ISSUE TITLE
[v. 7.2.2] Error thrown when creating a new purchase order

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#7334]
Hi there, 

i'm getting an error while creating a new purchase order, see log: 

```
[Log] Traceback (most recent call last): (desk.min.js, line 1499)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 426, in apply_price_list
    parent = get_price_list_currency_and_exchange_rate(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 479, in get_price_list_currency_and_exchange_rate
    price_list_currency = get_price_list_currency(args.price_list)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/get_item_details.py", line 471, in get_price_list_currency
    throw(_("Price List {0} is disabled").format(price_list))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 302, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 275, in _raise_exception
    raise raise_exception, encode(msg)
ValidationError: Price List Supplier 1 buy is disabled
```

The price list `Supplier 1 buy` is present, enabled and assigned to `Supplier`; 

It has been renamed from `Supplier 1 `to `Supplier 1 buy`

What's wrong with that?

**Comment by rmehta** [comment]
@umairsy can you replicate?

**Comment by umairsy** [comment]
Replicating.

Default Price List is updated in the Supplier master and in the Buying Setting. On Renaming Price List, value was correctly updated in Supplier master as well as in the Buying Settings.

Seems like in the purchase transactions, default Price List is being fetched from some other source. It still has "Standard Buying" is still fetched as a default Price List.

**Comment by rmehta** [comment]
This is because rename does not happen in unsaved data in the browser... Let me fix this.

**Comment by rmehta** [comment]
@joezsweet thanks for reporting. fixed.
