### ISSUE TITLE
E mail did not pull because of the character encoding?

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#7335]
It seem the problemis not solved:

email_account.receive

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 196, in receive
    communication = self.insert_communication(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 238, in insert_communication
    self.set_thread(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 285, in set_thread
    parent = self.create_new_parent(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 358, in create_new_parent
    parent.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 29, in validate
    self.make_new_lead_if_required()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 71, in make_new_lead_if_required
    lead.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 46, in validate
    self.image = has_gravatar(self.email_id)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 137, in has_gravatar
    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)

**Comment by krnkris** [comment]
pull_from_email_account

{'retry': 0, 'log': <function log at 0xb6094924>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb601ac6c>, 'user': u'Administrator', 'kwargs': {'email_account': u'Krnacs'}, 'async': True, 'job_name': u'pull_from_email_account|Krnacs'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 487, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 214, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 196, in receive\n    communication = self.insert_communication(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 238, in insert_communication\n    self.set_thread(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 285, in set_thread\n    parent = self.create_new_parent(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 358, in create_new_parent\n    parent.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 29, in validate\n    self.make_new_lead_if_required()\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 71, in make_new_lead_if_required\n    lead.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py\", line 46, in validate\n    self.image = has_gravatar(self.email_id)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py\", line 137, in has_gravatar\n    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 1: ordinal not in range(128)\n"
]

**Comment by krnkris** [comment]
In the mean time only this TWO message I received, nothing else
the other email pulls are OK:

email_account.receive

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 196, in receive
    communication = self.insert_communication(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 238, in insert_communication
    self.set_thread(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 282, in set_thread
    parent = self.find_parent_based_on_subject_and_sender(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 326, in find_parent_based_on_subject_and_sender
    }, fields="name")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 528, in get_all
    return frappe.get_all(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1102, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1075, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1267, "Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'")


THE SECOND ONE:

pull_from_email_account

{'retry': 0, 'log': <function log at 0xb6094924>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb601ac6c>, 'user': u'Administrator', 'kwargs': {'email_account': u'Krnacs'}, 'async': True, 'job_name': u'pull_from_email_account|Krnacs'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 487, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 214, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 196, in receive\n    communication = self.insert_communication(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 238, in insert_communication\n    self.set_thread(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 282, in set_thread\n    parent = self.find_parent_based_on_subject_and_sender(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 326, in find_parent_based_on_subject_and_sender\n    }, fields=\"name\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 528, in get_all\n    return frappe.get_all(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1102, in get_all\n    return get_list(doctype, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1075, in get_list\n    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py\", line 80, in execute\n    result = self.build_and_run()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py\", line 104, in build_and_run\n    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/database.py\", line 148, in sql\n    self._cursor.execute(query)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File \"/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1267, \"Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'\")\n"
]

**Comment by krnkris** [comment]
NOW I got this just now:

email_account.receive

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 196, in receive
    communication = self.insert_communication(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 238, in insert_communication
    self.set_thread(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 285, in set_thread
    parent = self.create_new_parent(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 358, in create_new_parent
    parent.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 29, in validate
    self.make_new_lead_if_required()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 71, in make_new_lead_if_required
    lead.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 46, in validate
    self.image = has_gravatar(self.email_id)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 137, in has_gravatar
    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
++++++++++++++++++++++++++


pull_from_email_account



{'retry': 0, 'log': <function log at 0xb6021994>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5fa8cdc>, 'user': u'Administrator', 'kwargs': {'email_account': u'Sales'}, 'async': True, 'job_name': u'pull_from_email_account|Sales'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 487, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 214, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 196, in receive\n    communication = self.insert_communication(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 238, in insert_communication\n    self.set_thread(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 285, in set_thread\n    parent = self.create_new_parent(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 358, in create_new_parent\n    parent.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 29, in validate\n    self.make_new_lead_if_required()\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 71, in make_new_lead_if_required\n    lead.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py\", line 46, in validate\n    self.image = has_gravatar(self.email_id)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py\", line 137, in has_gravatar\n    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 1: ordinal not in range(128)\n"
]


++++++++++++++++++++++++++++

email_account.receive

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 196, in receive
    communication = self.insert_communication(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 238, in insert_communication
    self.set_thread(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 285, in set_thread
    parent = self.create_new_parent(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 358, in create_new_parent
    parent.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 29, in validate
    self.make_new_lead_if_required()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py", line 71, in make_new_lead_if_required
    lead.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 189, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 46, in validate
    self.image = has_gravatar(self.email_id)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 137, in has_gravatar
    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
++++++++++++++++++++++++++

pull_from_email_account

{'retry': 0, 'log': <function log at 0xb6021994>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5fa8cdc>, 'user': u'Administrator', 'kwargs': {'email_account': u'Krnacs'}, 'async': True, 'job_name': u'pull_from_email_account|Krnacs'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 487, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 214, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 196, in receive\n    communication = self.insert_communication(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 238, in insert_communication\n    self.set_thread(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 285, in set_thread\n    parent = self.create_new_parent(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 358, in create_new_parent\n    parent.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 29, in validate\n    self.make_new_lead_if_required()\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/opportunity/opportunity.py\", line 71, in make_new_lead_if_required\n    lead.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 189, in insert\n    self.run_before_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 750, in run_before_save_methods\n    self.run_method(\"validate\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 651, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 858, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 841, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 645, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py\", line 46, in validate\n    self.image = has_gravatar(self.email_id)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py\", line 137, in has_gravatar\n    hexdigest = md5.md5(frappe.as_unicode(email)).hexdigest()\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 1: ordinal not in range(128)\n"
]

**Comment by rmehta** [comment]
#7145
