### ISSUE TITLE
Error on fresh install: type object 'WebsiteGenerator' has no attribute 'on_update'

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#7358]
Hi, error raised when setting up system right after setup wizard: 

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 39, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 23, in setup_complete
    install_fixtures.install(args.get("country"))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/install_fixtures.py", line 208, in install
    doc.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 212, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 776, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 655, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 871, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 854, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 649, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 31, in on_update
    WebsiteGenerator.on_update(self)
AttributeError: type object 'WebsiteGenerator' has no attribute 'on_update'
```
Can you please have a look?

**Comment by rmehta** [comment]
Thanks for reporting. Pushed a fix.

**Comment by faztp12** [comment]
@rmehta master branch still has that line
