### ISSUE TITLE
Permission error while calling erpnext.stock.utils.get_stock_balance

### ISSUE THREAD

**Issue by elitechweb** [frappe/erpnext#7364]
Hi Team,

Is it possible to call `erpnext.stock.utils.get_stock_balance` through Custom Script on account hosted at erpnext.com?

Because I have tried but it gives me following error.
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-12-29/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-12-29/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-12-29/apps/frappe/frappe/handler.py", line 38, in execute_cmd
    is_whitelisted(method)
  File "/home/frappe/benches/bench-2016-12-29/apps/frappe/frappe/handler.py", line 63, in is_whitelisted
    raise frappe.PermissionError('Not Allowed, {0}'.format(method))
PermissionError: Not Allowed, <function get_stock_balance at 0x4072cf8>
```
If not I guess we should have it to add more functions. 

Its very good to extend and add more functions at client end and its where ERPNext is winning at.

Thanks.

**Comment by rmehta** [comment]
Can you whitelist the method and send a pull request?

**Comment by nick9822** [comment]
@rmehta 
I will do it sir its good to have this.
