### ISSUE TITLE
[v. 7.2.6] Error while adding new warehouse

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#7383]
Hi there, 

i got an error while adding a new warehouse. I've customized the form adding a new field `code`, it is `mandatory`, `unique`. See pic:

<img width="1216" alt="schermata 2017-01-04 alle 10 58 39" src="https://cloud.githubusercontent.com/assets/11652845/21638785/20ae11c0-d26d-11e6-9fa5-a031ef4ae283.png">

When adding a new warehouse: 
<img width="1226" alt="schermata 2017-01-04 alle 10 56 55" src="https://cloud.githubusercontent.com/assets/11652845/21638787/20bf5e80-d26d-11e6-8f76-72c050d6eaec.png">

filled all fields:
<img width="1234" alt="schermata 2017-01-04 alle 10 57 37" src="https://cloud.githubusercontent.com/assets/11652845/21638786/20bec81c-d26d-11e6-888d-6701f4a812eb.png">

once saved:
<img width="1237" alt="schermata 2017-01-04 alle 10 57 46" src="https://cloud.githubusercontent.com/assets/11652845/21638788/20bf97e2-d26d-11e6-9a4a-542a5b00742d.png">

Can you please have a look?

**Comment by yashodhank** [comment]
```
POST http://erp-test.xxx.com/ 417 (EXPECTATION FAILED)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js:139
frappe.call @ desk.min.js:135
(anonymous) @ list.min.js:302
(anonymous) @ desk.min.js:539
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js:208
r.handle @ jquery.min.js:3
desk.min.js:151 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/warehouse/warehouse.py", line 291, in add_node
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 223, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 190, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 384, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 604, in _validate_mandatory
    name=self.name))
MandatoryError: [Warehouse, Test - ST]: code
```

**Comment by joezsweet** [comment]
fixed
