### ISSUE TITLE
Unknown column 'tabPurchase Order.item_code' in 'order clause

### ISSUE THREAD

**Issue by cypressamuel** [frappe/erpnext#7481]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/desk/reportview.py", line 17, in get
    data = compress(execute(**args), args = args)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/desk/reportview.py", line 22, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2017-01-13/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-01-13/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabPurchase Order.item_code' in 'order clause'")

![po](https://cloud.githubusercontent.com/assets/25105327/21936306/af662314-d9eb-11e6-9b1a-8f1dc6a7831d.png)

**Comment by bcornwellmott** [comment]
This issue happens when you go from a Report View of the Purchase Order doc to the List view. You'll notice that the Sorting of the list view is set to 'item_code', which isn't a field in Purchase Order (it is a field in Purchase Order Item, which is probably how the Report was sorted, causing this issue). The quick fix to resolve the issue if you face it is to just click on the sorting and go back to a proper field (Last Modified On is default I think).

The above said, this bug should still get fixed.

**Comment by KanchanChauhan** [comment]
@bcornwellmott not able to replicate it, when you say "Report View of the Purchase Order doc to the List view", you mean pressing the back button? How do you switch from Report view to List view?

**Comment by bcornwellmott** [comment]
I think it was any possible way - by hitting the back button, or having it open in another browser and refreshing. I can't seem to replicate it now.

**Comment by KanchanChauhan** [comment]
@bcornwellmott Yeah not able to replicate it, so closing it for now.
