### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by samehmreda** [frappe/erpnext#7558]
Hello,

i got around 47 error log & i do not know the reason for that , each day i open ERPNext i found some error logs .

Below is a sample of the message that i got , please advise.

{'retry': 0, 'log': <function log at 0x3eff1b8>, 'site': u'lavaloon.erpnext.com', 'event': u'daily', 'method_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily', 'method': <function send_daily at 0x40e5410>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.email.doctype.auto_email_report.auto_email_report.send_daily'}
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 139, in send_daily
    auto_email_report.send()
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 75, in send
    data = self.get_report_content()
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/email/doctype/auto_email_report/auto_email_report.py", line 45, in get_report_content
    raw = report.get_data(limit=self.no_of_rows or 100, user = self.user, filters = self.filters)
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/core/doctype/report/report.py", line 68, in get_data
    data = frappe.desk.query_report.run(self.name, filters=filters, user=user)
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/desk/query_report.py", line 93, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-2017-01-20/apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 11, in execute
    period_list = get_period_list(filters.from_fiscal_year, filters.to_fiscal_year, filters.periodicity)
  File "/home/frappe/benches/bench-2017-01-20/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 16, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "/home/frappe/benches/bench-2017-01-20/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 87, in validate_fiscal_year
    frappe.throw(_("End Year cannot be before Start Year"))
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/__init__.py", line 309, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/__init__.py", line 302, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-01-20/apps/frappe/frappe/__init__.py", line 275, in _raise_exception
    raise raise_exception, encode(msg)
ValidationError: End Year cannot be before Start Year

**Comment by rmehta** [comment]
One of the filters in your auto email report is wrongly set.

**Comment by samehmreda** [comment]
Thanks for your reply

can you guide me on how to remove this filter?

Regards,
