### ISSUE TITLE
Show / Hide Module

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#7608]
Hide the breadcrumbs if module is hide

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-27/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-01-27/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-01-27/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-01-27/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
TypeError: get() takes exactly 1 argument (0 given)

**Comment by mbauskar** [comment]
fixed via https://github.com/frappe/frappe/pull/2663
