### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by ulasaktas** [frappe/erpnext#7700]
Bir şeyler yanlış gitti
Kapat
Sunucu Hatası: sunucu günlükleri ya da kontakt teknik destek kontrol edin.
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/desk/reportview.py", line 17, in get
    data = compress(execute(**args), args = args)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/desk/reportview.py", line 22, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/model/db_query.py", line 80, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-2017-02-08/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2017-02-08/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-02-08/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabCustomer.account' in 'order clause'")
Bu sorunu bildir

**Comment by yashodhank** [comment]
@ulasaktas We accept **English** only posts.
Explain how, when and steps to reproduce this error in clear english with screenshot or animated gif to support the claim.
Also do not forget to share your version of ERPNext, frappe and bench with us.
Thanks

**Comment by ulasaktas** [comment]
Installed Apps
ERPNext: v7.2.19
ERPNext Shopify: v2.0.3
Frappe Framework: v7.2.15

When I enter "costumer" screen, I see this "error"...
screenshot:
![20170209_181505_hdr_resized](https://cloud.githubusercontent.com/assets/19535765/22789482/bb9a67d4-eeeb-11e6-869c-98d85c39a9c8.jpg)

thanks...

**Comment by umairsy** [comment]
Screenshot indicates that Customer List is sorted based on Account. Please change Sort Field to one of the Standard field, and then it should work just fine.

**Comment by ulasaktas** [comment]
Thankyou. Not, it is Oktay. Have a
 Nice day.
iPad'imden gönderildi

Umair Sayed <notifications@github.com> şunları yazdı (10 Şub 2017 08:00):
