### ISSUE TITLE
Email Inbox error in Dev 8.0 - Unknown column 'uid' in 'field list'"

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#7758]
using ERPNext 8 Dev, even after bench update a few moments ago, I always get the same error when trying to go into Email Inbox to test.

Here is the traceback. Some else had exactly same error in Forums about a week back.

Hope you dont mind me reporting bugs in Dev.

Julian
```
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 903, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 16, in get
>     data = compress(execute(**args), args = args)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 21, in execute
>     return DatabaseQuery(doctype).execute(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 81, in execute
>     result = self.build_and_run()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 105, in build_and_run
>     return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
>     self._cursor.execute(query)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> OperationalError: (1054, "Unknown column 'uid' in 'field list'")
> Report this issue

```

**Comment by joolsr** [comment]
When trying to report via 'Report this error' in ERPnext directly, I get another error, but will post this separately.

**Comment by mbauskar** [comment]
Closing the issue same issue is already open
