### ISSUE TITLE
Date time error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7800]
Steps:

1. Added new Lead.
2. Saved Lead successfully.
3. Select Next Contact Date in Lead.
4. Getting below error on Save.

![date-time-error](https://cloud.githubusercontent.com/assets/910238/23153888/fbf8fdec-f830-11e6-998d-e53872c29641.gif)

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 224, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 257, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 656, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 877, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 650, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/crm/doctype/lead/lead.py", line 49, in validate
    if self.contact_date and getdate(self.contact_date) < nowdate():
TypeError: can't compare datetime.date to str
```

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/7878
