### ISSUE TITLE
[v8] Stock balance error KeyError: u'from_date'

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7867]
Hello,

Stock balance report shows this error when opening: 

"Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 903, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 94, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 16, in execute
    iwb_map = get_item_warehouse_map(filters)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 92, in get_item_warehouse_map
    from_date = getdate(filters["from_date"])
KeyError: u'from_date'"

**Comment by KanchanChauhan** [comment]
Tested on couple of sites, worked fine. May be date filters were not loaded properly.
