### ISSUE TITLE
Upgrade error: Table tabJournal Entry Detail doesn't exist

### ISSUE THREAD

**Issue by betoled** [frappe/erpnext#7929]
Hi,

I'm trying to upgrade from version 6 to version 7, but I keep getting following error message :

`Executing frappe.patches.v6_4.reduce_varchar_length in site1.local (1bd3e0294d)
setting length of 'subject' in 'Feed' as 255
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/commands/site.py", line 209, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/migrate.py", line 30, in migrate
    frappe.modules.patch_handler.run_all()
File "/home/benjamien/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/patches/v6_4/reduce_varchar_length.py", line 8, in execute
    for column in frappe.db.sql("desc `tab{doctype}`".format(doctype=doctype), as_dict=True):
  File "/home/benjamien/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
    self._cursor.execute(query)
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/benjamien/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table '1bd3e0294d.tabJournal Entry Detail' doesn't exist")
`
Can I create this table ? Is there a create table script ?

Thanks in advance,
Benjamien

**Comment by rmehta** [comment]
@betoled this happens when your frappe is on `develop` and erpnext is on `master`

**Comment by betoled** [comment]
How can I switch both to master ?



Met vriendelijke groeten,
Kind regards,

Benjamien Toté
BETOWARE bvba

2017-03-10 7:13 GMT+01:00 Rushabh Mehta <notifications@github.com>:

**Comment by rmehta** [comment]
Go to `apps/[app name]` from your bench folder and then `git checkout [branchname]`
