### ISSUE TITLE
Error on creation of Email Account if Incoming enabled

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#7976]
```
Traceback (most recent call last):
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 770, in run_before_save_methods
    self.run_method("validate")
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 888, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 871, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 58, in validate
    self.get_incoming_server()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 145, in get_incoming_server
    "uid_validity": self.uidvalidity,
AttributeError: 'EmailAccount' object has no attribute 'uidvalidity'

Traceback (most recent call last):
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/__init__.py", line 904, in call
    return fn(*args, **newargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 770, in run_before_save_methods
    self.run_method("validate")
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 888, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 871, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 58, in validate
    self.get_incoming_server()
  File "/Users/nabinhait/projects/erpnext5/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 145, in get_incoming_server
    "uid_validity": self.uidvalidity,
AttributeError: 'EmailAccount' object has no attribute 'uidvalidity'
```

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/frappe/commit/40608add4f6ae169732fc93497a91fa49df861ce
