### ISSUE TITLE
list index out of index when we select update stock option for purchase invoice

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#8035]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 223, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 252, in _save
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 750, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 858, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 841, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-03-08/apps/frappe/frappe/model/document.py", line 645, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-03-08/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 43, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/benches/bench-2017-03-08/apps/erpnext/erpnext/controllers/buying_controller.py", line 45, in validate
    pc_obj.validate_for_items(self)
  File "/home/frappe/benches/bench-2017-03-08/apps/erpnext/erpnext/buying/doctype/purchase_common/purchase_common.py", line 62, in validate_for_items
    d.item_code, as_dict=1)[0]
IndexError: list index out of range

**Comment by mbauskar** [comment]
https://github.com/frappe/erpnext/pull/8034
