### ISSUE TITLE
[Error] module_name_owner_standard must be unique

### ISSUE THREAD

**Issue by franzos** [frappe/erpnext#8052]
<img width="597" alt="screen shot 2017-03-16 at 7 20 54 pm" src="https://cloud.githubusercontent.com/assets/2619225/24012265/a51393d4-0a7d-11e7-8f6c-d3e66f8a3266.png">

When I try to add a section to the 'Desktop', I get the following error message: `module_name_owner_standard must be unique`. This happens with both admin and users with limited rights.

**Version**
ERPNext: v7.2.27
Frappe Framework: v7.2.27

```
Failed to load resource: the server responded with a status of 417 (EXPECTATION FAILED) desk.min.js:151 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 145, in add_user_icon
    raise e
UniqueValidationError: (u'Desktop Icon', 'fc5434635c', IntegrityError(1062, "Duplicate entry 'Item-email@domain.de-0' for key 'unique_module_name_owner_standard'"))

```

**Comment by jwrober** [comment]
@franzos - is this still an issue in latest 8.x?

**Comment by franzos** [comment]
@jwrober thanks for the follow-up! We're on 8.0.20 but the issue remains. I will update to the latest version over the weekend.

ERPNext: v8.0.20 (master)
Frappe Framework: v8.0.31 (master)

Here's me adding 'Lead' to the Desktop:

```
jquery.min.js:4 POST https://erp.fitaseal.de/ 417 (EXPECTATION FAILED)

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 145, in add_user_icon
    raise e
UniqueValidationError: (u'Desktop Icon', 'f655bc3b67', IntegrityError(1062, "Duplicate entry 'Lead-name@domain.com-0' for key 'unique_module_name_owner_standard'"))

```

**Comment by tundebabzy** [comment]
hello @franzos 
Let's move this discussion to https://discuss.erpnext.com as I can't replicate this. On the thread you open on the forum, please post the result of this query:
```(sql)
select module_name, owner, standard from `tabDesktop Icon`;
```

**Comment by franzos** [comment]
@tundebabzy I've posted it on the forum, [here](https://discuss.erpnext.com/t/error-module-name-owner-standard-must-be-unique/25354). Thanks for your input!

**Comment by franzos** [comment]
@tundebabzy after the most recent updates, the error message has changed. Who knows, this may be a good opportunity to revisit this issue.

<img width="596" alt="screen shot 2017-07-08 at 1 52 46 am" src="https://user-images.githubusercontent.com/2619225/27979656-37729454-6380-11e7-8686-fb97bd1bc9b1.png">

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 164, in add_user_icon
    frappe.throw(_('Desktop Icon already exists'))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Desktop Icon existiert bereits
```

I've also noticed that when I set the icon, it saves but the option is not persistent.

<img width="1181" alt="screen shot 2017-07-08 at 1 56 16 am" src="https://user-images.githubusercontent.com/2619225/27979731-e8fbc4d4-6380-11e7-80a8-3a5778e9baff.png">

**Comment by bab1ch** [comment]
Same problem here on v9.2.10. When user tires to add new desktop icon: 
> module_name_owner_standard must be unique
Desktop Icon already exists

Issue should be re-opened.

**Comment by littlehera** [comment]
Not sure if this might help, but we encountered the same issue and changing the roles/permissions of the user managed to fix the problem.
