### ISSUE TITLE
Error on restore/migrate "ImportError: Module import failed for Project (erpnext.projects.doctype.project.project)"

### ISSUE THREAD

**Issue by slushpuppy** [frappe/erpnext#8059]
```
> frappe@server:~/frappe-bench$ bench --force restore /home/frappe/erp.local.host/private/backups/20170108_130002_33ea2f40_database.sql
> MySQL root password:
> *** Scheduler is disabled ***
> frappe@server:~/frappe-bench$ bench --site erp.local.host remove-from-installed-apps frappe_subscription
> frappe@server:~/frappe-bench$ bench --site erp.local.host migrate
> Migrating erp.local.host
> Executing execute:frappe.reload_doc('core', 'doctype', 'docfield', force=True) #2017-01-06 in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_1.set_backup_limit in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_1.disabled_print_settings_for_custom_print_format in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_2.set_doctype_engine in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_2.merge_knowledge_base in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_0.update_report_builder_json in erp.local.host (cfd511bd42332394)
> Success
> Executing frappe.patches.v7_2.set_in_standard_filter_property #1 in erp.local.host (cfd511bd42332394)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
>     main()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 209, in migrate
>     migrate(context.verbose, rebuild_website=rebuild_website)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 30, in migrate
>     frappe.modules.patch_handler.run_all()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
>     if not run_single(patchmodule = patch):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
>     return execute_patch(patchmodule, method, methodargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
>     frappe.get_attr(patchmodule.split()[0] + ".execute")()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v7_2/set_in_standard_filter_property.py", line 13, in execute
>     frappe.reload_doctype(doctype.name, force=True)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 642, in reload_doctype
>     force=force, reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 654, in reload_doc
>     return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 141, in reload_doc
>     return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
>     reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
>     ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 57, in import_file_by_path
>     reset_permissions=reset_permissions)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 125, in import_doc
>     doc.insert()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 212, in insert
>     self.run_post_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 770, in run_post_save_methods
>     self.run_method("on_update")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 860, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 843, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 197, in on_update
>     self.run_module_method("on_doctype_update")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 206, in run_module_method
>     module = load_doctype_module(self.name, self.module)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 173, in load_doctype_module
>     raise ImportError, 'Module import failed for {0} ({1})'.format(doctype, module_name)
> ImportError: Module import failed for Project (erpnext.projects.doctype.project.project)
> frappe@server:~/frappe-bench$
> 
```
Please advise thanks

**Comment by yashodhank** [comment]
are you trying to restore old version database with new version?
Post more details such as scenario and versions of bench, erpnext, frappe on your machine.

seek answers at https://discuss.erpnext.com

**Comment by slushpuppy** [comment]
hi @yashodhank Yes indeed, it is an old version with new version

frappe@server:~/frappe-bench$ bench version
erpnext 7.2.30
frappe 7.2.30

I can't remember the old version's number, but it was around 7.x

**Comment by slushpuppy** [comment]
Any updates?
