### ISSUE TITLE
[Bug] Unable to View Balance Sheet

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#8088]
Hi,

Faced with the following prompt when trying to view Balance Sheet.
https://discuss.erpnext.com/t/balance-sheet-giving-error-on-opening/14423/7

> Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 93, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/report/balance_sheet/balance_sheet.py", line 13, in execute
    asset = get_data(filters.company, "Asset", "Debit", period_list, only_current_fiscal_year=False)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 128, in get_data
    calculate_values(accounts_by_name, gl_entries_by_account, period_list, accumulated_values, ignore_accumulated_values_for_fy)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 148, in calculate_values
    d[period.key] = d.get(period.key, 0.0) + flt(entry.debit) - flt(entry.credit)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by rohitwaghchaure** [comment]
Hi @addymuliady 

Can you share the screenshots of your fiscal year, basically I want to see the start date and end date on the fiscal year

**Comment by addymuliady** [comment]
Hi @rohitwaghchaure 

Thank you for picking this up.

2016
![image](https://cloud.githubusercontent.com/assets/21187126/24293469/e16d478a-10cc-11e7-80d1-9d3ad1617f02.png)

2017
![image](https://cloud.githubusercontent.com/assets/21187126/24293485/f20423d4-10cc-11e7-9273-8f4062918124.png)

**Comment by addymuliady** [comment]
Hi

Any updates on this issue? Critical.

**Comment by joezsweet** [comment]
@addymuliady are u still facing the issue?

**Comment by addymuliady** [comment]
@joezsweet issue recently resolved as warehouse was in the wrong account type. It was supposed to be an Asset account type but user managed to change it to Expense account type.
