### ISSUE TITLE
Error when merging the new pos

### ISSUE THREAD

**Issue by elba7r** [frappe/erpnext#8215]
i have tried to embed the new 15 files by replacing the original ones by the new ones but when i tried to use the pos i got this error 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 37, in get_pos_data
    'address': get_customers_address(customers),
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 177, in get_customers_address
    and parenttype = 'Address')""", data.name, as_dict=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table '1bd3e0294da19198.tabDynamic Link' doesn't exist")

**Comment by mbauskar** [comment]
@elba7r,

please run the bench update command to pull and sync the `Dynamic Link` doctype, commit all the changes before running `bench update`

**Comment by nabinhait** [comment]
@elba7r It will not work that way. New POS is also dependent on the updates on frappe.

Version 8 will be released today, so you will get new POS automatically in master branch. Closing your issue.
