### ISSUE TITLE
[v8 upgrade] Unknown column 'uom' in 'field list'")

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8231]
I as a few others have found a bug on upgrading to vers 8 from 7.3.31 on the master branch.
Running 

sudo bench update --upgrade

Migrating li1370-250.members.linode.com
Executing erpnext.patches.v7_2.stock_uom_in_selling in li1370-250.members.linode.com (1bd3e0294da19198)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 210, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v7_2/stock_uom_in_selling.py", line 14, in execute
    set uom = stock_uom, conversion_factor = 1, stock_qty = qty""".format(doctype=doctype))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'uom' in 'field list'")

**Comment by nabinhait** [comment]
Fixed, please update again.

**Comment by joolsr** [comment]
ok, will do

**Comment by joolsr** [comment]
yes, this has fixed this problem - many thanks upgrade still running ;-)

**Comment by joolsr** [comment]
upgrade completed successfully. Pleased to help

**Comment by albed0** [comment]
Hi, similiar issue when upgrading to v8 from v7.3.14. 

_mysql_exceptions.OperationalError: (1054, "Unknown column 'is_sample_item' in 'field list'")

**Comment by nabinhait** [comment]
@albed0 Released a fix for the issue

**Comment by albed0** [comment]
@nabinhait Thanks. much appreciated. 

Additional info for those that find a blank login page after the upgrade, hard refresh (ctrl + f5) your browser to clear the cache.

**Comment by fproldan** [comment]
Hello, I'm trying to migrate from v7 to v8 and i'm facing with similar issue:

`_mysql_exceptions.OperationalError: (1054, "Unknown column 'roles' in 'field list'")
`

Thanks!

**Comment by nabinhait** [comment]
@fproldan Please create a new github issue with full traceback

**Comment by fproldan** [comment]
@nabinhait New issue open with full traceback, thanks.
https://github.com/frappe/erpnext/issues/8736
