### ISSUE TITLE
V8 error messages

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#8233]
Hello, 

I got v8.0.1 working. On my instance I have 641 of the same 2 errors.

1. **Title:** frappe.email.queue.flush
**Error:**
```
{'retry': 0, 'log': <function log at 0x7fd212507e60>, 'site': u'site1.local', 'event': u'all', 'method_name': u'frappe.email.queue.flush', 'method': <function flush at 0x7fd212442c08>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.email.queue.flush'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    else:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 281, in flush
    check_email_limit([])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 188, in check_email_limit
    smtp_server = SMTPServer()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 134, in __init__
    self.setup_email_account(append_to)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 137, in setup_email_account
    self.email_account = get_outgoing_email_account(raise_exception_not_set=False, append_to=append_to)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 54, in get_outgoing_email_account
    email_account = get_default_outgoing_email_account(raise_exception_not_set=raise_exception_not_set)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 82, in get_default_outgoing_email_account
    email_account = _get_email_account({"enable_outgoing": 1, "default_outgoing": 1})
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 117, in _get_email_account
    return frappe.get_doc("Email Account", name) if name else None
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 600, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 48, in get_doc
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 34, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 173, in load_doctype_module
ImportError: Module import failed for Email Account (frappe.email.doctype.email_account.email_account)
```

2. **Title:** frappe.utils.global_search.update_global_search
**Error:**

```
{'retry': 0, 'log': <function log at 0x7f59a9dee230>, 'site': u'site1.local', 'event': None, 'method_name': u'frappe.utils.global_search.update_global_search', 'method': <function update_global_search at 0x7f59a9deec08>, 'user': u'Administrator', 'kwargs': {'doc': <frappe.desk.doctype.desktop_icon.desktop_icon.DesktopIcon object at 0x7f59a9eeb110>}, 'async': True, 'job_name': u'frappe.utils.global_search.update_global_search'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    else:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/global_search.py", line 46, in update_global_search
    for field in doc.meta.get_global_search_fields():
AttributeError: 'Meta' object has no attribute 'get_global_search_fields'

```

**Comment by nabinhait** [comment]
I think your `bench update` did not worked properly. Seems like frappe repository does not have latest updates, it might be due to some local changes in frappe repo. Please try to update again.

**Comment by nabinhait** [comment]
I think we should disable background jobs while updating account, to avoid this issue. Will look into it tomorrow.

**Comment by DrTrills** [comment]
Sounds good, thanks Nabin!

With the error related to search, on the beta.erp site for example(same as mine) the search isn't working. Seems resources aren't loading. Searching for chair which should come up..

 PFA

![search-error-v8](https://cloud.githubusercontent.com/assets/1430005/24510757/5fb11c6a-156a-11e7-9879-710925a488e3.gif)

Thank you!

**Comment by joolsr** [comment]
i had the same issue for contacts. Ive just put up a forum post as not sure if this is by design or not. I suspect not
