### ISSUE TITLE
Unable to login using Facebook, after upgraded to version 8

### ISSUE THREAD

**Issue by akiato** [frappe/erpnext#8294]
Hi,
After upgraded to version 8, my users cannot login to ERPNext using their facebook account anymore. The system show the following error:
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/login.py", line 46, in login_via_facebook
    login_via_oauth2("facebook", code, state)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/oauth.py", line 168, in login_via_oauth2
    info = get_info_via_oauth(provider, code, decoder)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/oauth.py", line 186, in get_info_via_oauth
    session = flow.get_auth_session(**args)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rauth/service.py", line 556, in get_auth_session
    session = self.get_session(self.get_access_token(method, **kwargs))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rauth/service.py", line 542, in get_access_token
    access_token, = process_token_request(r, decoder, key)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/rauth/service.py", line 24, in process_token_request
    raise KeyError(PROCESS_TOKEN_ERROR.format(key=bad_key, raw=r.content))
KeyError: 'Decoder failed to handle access_token with data as returned by provider. A different decoder may be needed. Provider returned: {"access_token":"EAAQdF0K4OWUBAJ32CC89jTtQIZALGoBhOZBWleZB77xFcGG6h9M51k6RoAp8LgcdopyNokZBnmCZAvvKNxqw3uiwKN55N0exgki9tZC9ZBJiviEtq0Uks7sfIGtZAMC5D4kjdMfOY8x7FeYTrqZCVdnXtFxPJsX8ZALjAZD","token_type":"bearer","expires_in":5177093}'
`

**Comment by mbauskar** [comment]
fixed via https://github.com/frappe/frappe/pull/3108
