### ISSUE TITLE
[v8] OperationalError: (1054, "Unknown column 'tabContact.owner' in 'where clause'")

### ISSUE THREAD

**Issue by franzos** [frappe/erpnext#8297]
**Query String**

```
doctype:Contact
query:frappe.email.doctype.contact.contact.contact_query
filters:{"link_doctype":"Customer","link_name":"GmbH"}
cmd:frappe.desk.search.search_link
_:1491254439958
```

**Error Message**

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 12, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 34, in search_widget
    searchfield, start, page_len, filters, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/contact/contact.py", line 150, in contact_query
    'link_doctype': link_doctype
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 138, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabContact.owner' in 'where clause'")
```

`https://domain.de/?txt=&doctype=Contact&query=frappe.email.doctype.contact.contact.contact_query&filters=%7B%22link_doctype%22%3A%22Customer%22%2C%22link_name%22%3A%22GmbH%22%7D&cmd=frappe.desk.search.search_link&_=1491254439958 500 (INTERNAL SERVER ERROR)`

Release: v8.0.7 (latest)
Possible reference: #7911 and #7912 @mbauskar
Steps to reproduce:
1. Set 'Contact' permission to 'If Owner' in your group
2. Create a new Quotation (or any other document)
3. Select a Customer, erase pre-filled Contact
4. Error message!

_I can reproduce the same issue for Addresses._ #8305

**Comment by KanchanChauhan** [comment]
I tried to duplicate but it just gives me the error message which it should. Can you try again please.

![contact_error](https://cloud.githubusercontent.com/assets/16913064/24896154/3d33b648-1eb1-11e7-829e-abd59f797f6c.gif)

**Comment by franzos** [comment]
@KanchanChauhan thanks for your follow-up! In my case, I'm not supposed to receive a permission error because this user, also owns the contact (IF OWNER). However, if I remove this restriction, the error does not occur.

This error happens for both, the address and contact selection. #8305:

![erpnext_8297](https://cloud.githubusercontent.com/assets/2619225/24899182/a64a04be-1e9f-11e7-8023-13994f74192c.gif)

Here's how the permissions look like.

<img width="1049" alt="screen shot 2017-04-11 at 10 16 02 am" src="https://cloud.githubusercontent.com/assets/2619225/24899277/fc5da9dc-1e9f-11e7-8f92-3c3d4decfc6b.png">
