### ISSUE TITLE
[v8] OperationalError: (1054, "Unknown column 'tabAddress.company' in 'where clause'")

### ISSUE THREAD

**Issue by franzos** [frappe/erpnext#8305]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 12, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 34, in search_widget
    searchfield, start, page_len, filters, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/geo/doctype/address/address.py", line 224, in address_query
    'link_doctype': link_doctype
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 138, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabAddress.company' in 'where clause'")
```
Release: v8.0.7 (latest)
Steps to reproduce:

1. Set 'Address' permission to 'If Owner' in your group
2. Create a new Quotation (or any other document)
3. Select a Customer, erase pre-filled Address
4. Error message!

_I can reproduce the same issue for Contacts. #8297_

**Comment by mbauskar** [comment]
@franzos,

Address doctype doesn't have the company field did you add the custom field on Address doctype?

**Comment by franzos** [comment]
@mbauskar you're right. I did add a company field (sort of, the company that owns the address entry) but I get the same error, whether I restrict permission by IF OWNER or IF COMPANY.

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 12, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 34, in search_widget
    searchfield, start, page_len, filters, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/contact/contact.py", line 150, in contact_query
    'link_doctype': link_doctype
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 138, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'tabContact.owner' in 'where clause'")
```

The user has created the Customer, Address and Contact and when I open a new quote, all details are filled in automatically. However, when I try to change the selection, I don't get the usual dropdown (other customer address / contact) but this error. Even if this was a permission issue, why do I get this ugly error?

Below is a demonstration for addresses. It's basically the same error:

![erpnext_8297](https://cloud.githubusercontent.com/assets/2619225/24907932/8561c56a-1ebe-11e7-9fe9-69125013d7b3.gif)

**Comment by mbauskar** [comment]
fixed via https://github.com/frappe/frappe/pull/3065 can you please pull the latest update

**Comment by franzos** [comment]
@mbauskar fantastic work, thanks :) Nobody noticed.
