### ISSUE TITLE
Is there a database name maximum length?

### ISSUE THREAD

**Issue by dkastl** [frappe/erpnext#8307]
I tried to install a new site with custom database name, and I run into the following error. 
```
bench new-site my.domain --mariadb-root-username <snip> --mariadb-root-password <snip> \
    --admin-password <snip> --install-app erpnext_production  --force
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/srv/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/frappe/bench/apps/frappe/frappe/commands/site.py", line 26, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/srv/frappe/bench/apps/frappe/frappe/commands/site.py", line 57, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/srv/frappe/bench/apps/frappe/frappe/installer.py", line 35, in install_db
    create_database_and_user(force, verbose)
  File "/srv/frappe/bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    dbman.create_user(db_name, frappe.conf.db_password)
  File "/srv/frappe/bench/apps/frappe/frappe/model/db_schema.py", line 497, in create_user
    self.db.sql("CREATE USER '%s'@'%s' IDENTIFIED BY '%s';" % (user[:16], host, password))
  File "/srv/frappe/bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/srv/frappe/bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1396, "Operation CREATE USER failed for 'erpnext_producti'@'localhost'")
```
It didn't go away until I set a shorter database name, `erpnext` for example. 
Is there a database name length limit? If there is a length limitation, I think it's too short.

**Comment by adityaduggal** [comment]
@dkastl This seems more like a question instead of a bug or issue please post it on https://discuss.erpnext.com/
And if satisfied please close this issue.

**Comment by dkastl** [comment]
Well, I'm not asking this in the forum, because I think this is a bug. Maybe the question mark is misleading.

What I experience is, that I cannot provide a database name that exceeds a certain length. Interestingly it fails when creating a user. However, when I keep the database name short, it works.

My guess is, that the following line is the cause of the problem:
https://github.com/frappe/frappe/blob/ae088d22110ac84216694b10606764cd240d11b3/frappe/model/db_schema.py#L498

I do not understand, why it takes the database name for `user`. But when you count the length of the string `erpnext_producti` it's exactly the length of `16`.

So there is definitely something wrong, and that's why I posted it here.
