### ISSUE TITLE
[Error] Warehouse balance not matching account balance

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#8310]
My 'All Warehouses' Account does not seem to be linked to 'All Warehouses'. When I try to link them I'm receiving the following error
```

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 873, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 38, in validate
    self.validate_warehouse_account()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 192, in validate_warehouse_account
    .format(fmt_money(account_balance, self.account_currency),
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/data.py", line 363, in fmt_money
    amount = '%.*f' % (precision, flt(amount))
TypeError: * wants int
```

Any help would be greatly appreciated since this is our production server.
Thanks

**Comment by ishanloya** [comment]
I have the same problem on another server

**Comment by joezsweet** [comment]
Did u set account currency?

**Comment by ishanloya** [comment]
The number format is set and is the default option. I haven't changed it. Haven't changed the currency either.

**Comment by joezsweet** [comment]
That's kind of strange error, seems format is not found or similar ...

**Comment by ishanloya** [comment]
When I try to change any settings from Accounts Settings it throws this error "Account balance (0) and stock value _(All warehouses_value_from_warehouse_tree)_ must be same"

**Comment by ishanloya** [comment]
Does nobody else have this error?

**Comment by PawanMeh** [comment]
@ishanloya , are you still facing this error? If not, kindly close the issue
