### ISSUE TITLE
Encoding problem again in V8

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#8347]
email_account.receive

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 268, in receive
    communication = self.insert_communication(msg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 325, in insert_communication
    email = Email(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 360, in __init__
    self.set_from()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 396, in set_from
    _from_email = self.decode_email(self.mail.get("X-Original-From") or self.mail["From"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 412, in decode_email
    for part, encoding in decode_header(email.replace("\""," ").replace("\'"," ")):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 15: ordinal not in range(128)

----------------------------
pull_from_email_account

{'retry': 0, 'log': <function log at 0xb5f1d3ac>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5e9cca4>, 'user': u'Administrator', 'kwargs': {'email_account': u'Beerkezett valaszok'}, 'async': True, 'job_name': u'pull_from_email_account|Beerkezett valaszok'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 65, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 700, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 292, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 268, in receive\n    communication = self.insert_communication(msg, args=args)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 325, in insert_communication\n    email = Email(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 360, in __init__\n    self.set_from()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 396, in set_from\n    _from_email = self.decode_email(self.mail.get(\"X-Original-From\") or self.mail[\"From\"])\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 412, in decode_email\n    for part, encoding in decode_header(email.replace(\"\\\"\",\" \").replace(\"\\'\",\" \")):\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 15: ordinal not in range(128)\n"

E-mail is not working properly.

Installed Apps

ERPNext: v8.0.7 (master)

Frappe Framework: v8.0.6 (master) #

**Comment by krnkris** [comment]
Seem same problem as:

https://github.com/frappe/erpnext/issues/7145

**Comment by rmehta** [comment]
Pushed a fix. Please let us know if this comes again.

**Comment by krnkris** [comment]
Awesome support!
Thank you!

**Comment by krnkris** [comment]
This comes now:

email_account.receive

ERROR:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 268, in receive
    communication = self.insert_communication(msg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 325, in insert_communication
    email = Email(raw)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 360, in __init__
    self.set_from()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 396, in set_from
    _from_email = self.decode_email(self.mail.get("X-Original-From") or self.mail["From"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 412, in decode_email
    for part, encoding in decode_header(frappe.as_unicode(email).replace("\""," ").replace("\'"," ")):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 64, in as_unicode
    return unicode(text, encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 15: invalid continuation byte

----------------------------------


pull_from_email_account

ERROR:

{'retry': 0, 'log': <function log at 0xb5f53294>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5ecebfc>, 'user': u'Administrator', 'kwargs': {'email_account': u'Replies'}, 'async': True, 'job_name': u'pull_from_email_account|Replies'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 65, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 700, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 292, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 268, in receive\n    communication = self.insert_communication(msg, args=args)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 325, in insert_communication\n    email = Email(raw)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 360, in __init__\n    self.set_from()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 396, in set_from\n    _from_email = self.decode_email(self.mail.get(\"X-Original-From\") or self.mail[\"From\"])\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py\", line 412, in decode_email\n    for part, encoding in decode_header(frappe.as_unicode(email).replace(\"\\\"\",\" \").replace(\"\\'\",\" \")):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 64, in as_unicode\n    return unicode(text, encoding)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 15: invalid continuation byte\n"
]

**Comment by krnkris** [comment]
I get only these emails:

Several files in project 'O' were updated with new content 

May the    '  cause the problems?

**Comment by krnkris** [comment]
The latest problems is with the "<" and ">" beside the above mentioned " '  ".

---------------------------------------

email_account.receive

Hiba - ERROR

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 268, in receive
    communication = self.insert_communication(msg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 378, in insert_communication
    communication.insert(ignore_permissions = 1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 194, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 406, in _validate
    self._sanitize_content()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 614, in _sanitize_content
    elif (u"<" not in value and u">" not in value):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 4: ordinal not in range(128)

-------------------------------------------------------

pull_from_email_account

Hiba - ERROR

{'retry': 0, 'log': <function log at 0xb5f50294>, 'site': u'erpnext.vm', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5ecbbfc>, 'user': u'Administrator', 'kwargs': {'email_account': u'Replies'}, 'async': True, 'job_name': u'pull_from_email_account|Replies'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 65, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 700, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 292, in receive
    raise Exception, frappe.as_json(exceptions)
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 268, in receive\n    communication = self.insert_communication(msg, args=args)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 378, in insert_communication\n    communication.insert(ignore_permissions = 1)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 194, in insert\n    self._validate()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 406, in _validate\n    self._sanitize_content()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py\", line 614, in _sanitize_content\n    elif (u\"<\" not in value and u\">\" not in value):\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 4: ordinal not in range(128)\n"

---------------------------------------

Installed Apps

ERPNext: v8.0.21 (master)

Frappe Framework: v8.0.32 (master)

**Comment by krnkris** [comment]
Please take a look on this, because these characters are not recognised correctly in
E-mail:

The latest problems is with the "<" and ">" beside the above mentioned " ' ".

**Comment by rmehta** [comment]
Pushed another fix. Please start a new thread for new issues
