### ISSUE TITLE
There were errors while setting up erpnext through wizard.

### ISSUE THREAD

**Issue by atularvind** [frappe/erpnext#8371]
I am getting below error during one time setup everytime.

```
12:42:47 web.1            | --------------------------------------------------------------------------------
12:42:47 web.1            | Exception happened during processing of request from ('192.168.12.1', 50885)
12:42:47 web.1            | Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-18, stopped daemon 140375773214464)>>
12:42:47 web.1            | Traceback (most recent call last):
12:42:47 web.1            |   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
12:42:47 web.1            |     self.__bootstrap_inner()
12:42:47 web.1            |   File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
12:42:47 web.1            |     (self.name, _format_exc()))
12:42:47 web.1            |   File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
12:42:47 web.1            |     etype, value, tb = sys.exc_info()
12:42:47 web.1            | AttributeError: 'NoneType' object has no attribute 'exc_info'
12:42:47 web.1            |
12:42:47 web.1            | Exception happened during processing of request from ('192.168.12.1', 50866)
12:42:47 web.1            | Exception in thread Thread-16 (most likely raised during interpreter shutdown):
12:42:47 web.1            | Traceback (most recent call last):
12:42:47 web.1            |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
12:42:47 web.1            |   File "/usr/lib/python2.7/threading.py", line 754, in run
12:42:47 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
12:42:47 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 545, in handle_error
12:42:47 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 350, in handle_error
12:42:47 web.1            | <type 'exceptions.ImportError'>: No module named traceback

```

**Comment by atularvind** [comment]
also on the first time setup, erpnext is not let me complete the setup. it says "Setup Already Complete!!" & "There were errors." 
when I go to the dash again, the setup wizard appears and again it says as above.

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this.
