### ISSUE TITLE
v7 to v8 migrate error: frappe.exceptions.LinkValidationError: Could not find _doctype: Assessment

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#8409]
code commented to fix this issue.
https://github.com/frappe/frappe/blob/develop/frappe/model/document.py#L633-L636

Migrating mystic.local
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/sam/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in call
    return self.main(*args, **kwargs)
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sam/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), args, *kwargs)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), args, *kwargs)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/commands/site.py", line 210, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/migrate.py", line 37, in migrate
    sync_desktop_icons()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 296, in sync_desktop_icons
    sync_from_app(app)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 332, in sync_from_app
    desktop_icon.save()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/model/document.py", line 267, in _save
    self._validate()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/model/document.py", line 401, in _validate
    self._validate_links()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/model/document.py", line 636, in _validate_links
    frappe.LinkValidationError)
  File "/Users/sam/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/Users/sam/frappe-bench/apps/frappe/frappe/__init__.py", line 306, in msgprint
    _raise_exception()
  File "/Users/sam/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in _raise_exception
    raise raise_exception, encode(msg)
frappe.exceptions.LinkValidationError: Could not find _doctype: Assessment

**Comment by rmehta** [comment]
Cannot replicate. Lets reopen if it comes again.

**Comment by sbkolate** [comment]
I was migrating v7.1 instance to v8, and Assessment doctype is not present somehow, so its giving error. Now fixed this.

I will check add traceback if its come back in another instance.
