### ISSUE TITLE
Error report related to date range picker

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8484]
Issue received from hosted user as an Issue WN-SUP24339

I received the upgrade to erp 8 but I cannot use my erp anymore...

I have this error and the pages are empty so I cannot do anything.

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/client.py", line 281, in get_js
    with open(contentpath, "r") as srcfile:
IOError: [Errno 2] No such file or directory: u'./assets/frappe/css/daterangepicker.css'

**Comment by rmehta** [comment]
Screeshot needed
