### ISSUE TITLE
Error report for Kanban Board

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8485]
Issue received from hosted user - WN-SUP24341

Please type some additional information that could help us reproduce this issue:

App Versions

{
	"erpnext": "8.0.13",
	"frappe": "8.0.18"
}
Route

List/Quotation/Kanban/Kanban 1
Error Report

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/desk/reportview.py", line 228, in get_sidebar_stats
    return {"defined_cat":cat_tags, "stats":get_stats(stats, doctype, filters)}
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/desk/reportview.py", line 245, in get_stats
    filters = filters + ["ifnull(`%s`,'')!=''" % tag], group_by = tag, as_list = True)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/__init__.py", line 1112, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/model/db_query.py", line 83, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/model/db_query.py", line 107, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/benches/bench-2017-04-17/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2017-04-17/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-04-17/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1412, 'Table definition has changed, please retry transaction')
Request Data

{
	"type": "POST",
	"args": {
		"stats": "[\"_user_tags\"]",
		"doctype": "Quotation",
		"filters": "[[\"Quotation\",\"docstatus\",\"!=\",\"2\"]]",
		"cmd": "frappe.desk.reportview.get_sidebar_stats"
	},
	"url": "/"
}
Response JSON

{}

**Comment by rmehta** [comment]
Catch this error in get_sidebar_stats and pass
