### ISSUE TITLE
Error when trying to Submit or Cancel Sales Invoice [V8]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8507]
Hi,

The following error occurs when trying to Submit or Cancel Sales Invoices:

```
Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 741, in submit
    self._submit()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 730, in _submit
    self.save()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 775, in run_before_save_methods
    self.run_method("validate")
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 89, in validate
    self.set_status()
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 122, in set_status
    if frappe.safe_eval(s[1][5:], None, { "self": self.as_dict(), "getdate": getdate, "nowdate": nowdate }):
AttributeError: 'module' object has no attribute 'safe_eval'

Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 741, in submit
    self._submit()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 730, in _submit
    self.save()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 775, in run_before_save_methods
    self.run_method("validate")
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 89, in validate
    self.set_status()
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/status_updater.py", line 122, in set_status
    if frappe.safe_eval(s[1][5:], None, { "self": self.as_dict(), "getdate": getdate, "nowdate": nowdate }):
AttributeError: 'module' object has no attribute 'safe_eval'
```

"erpnext": "8.0.14"
"frappe": "8.0.7"

Please advise

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

"frappe": "8.0.7"
Kindly pull latest code for frappe application, it will resolve your issue

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

How do I do this? I thought it happens with bench update?

Please advise

**Comment by Olawale1** [comment]
@rohitwaghchaure I've tried bench update and bench update --pull
Frappe framework is still on 8.0.7

**Comment by Olawale1** [comment]
hi @rohitwaghchaure 

I've tried bench update again a couple of times but still the same:
Bench: 4.1.0
ERPNext: 8.0.14
Frappe: 8.0.7

Pls advise on how to proceed

Thanks

**Comment by Olawale1** [comment]
hi @rohitwaghchaure 

restarting the server seems to have taken care of the issue. The version number is bumped to 8.0.19 but there's a new issue. When I try to Cancel and Amend an existing Sales Invoice, I get the error below:

"Due Date cannot be before Posting Date"

Please advise

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Can you please change the due date

**Comment by nabinhait** [comment]
@rohitwaghchaure He can't change due date of an invoice to avoid the error. The problem is, posting date is resetting while amendment, which I think should not be.

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

The posting date actually seems to be the same as the original invoice but it still gives that error. If I reduce the posting time by even 1 second, the invoice gets submitted!

Thanks
