### ISSUE TITLE
Error when chaning User Password from the User master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8524]
Steps:

1. Logged in as admin in the hosted account.
2. Setup > User > User for which password needs to be changed.
3. Entered new password, checked notification field, and tried saving a User.

Following was the error message on Save. Please note that this error comes only when Send Notifiaction to User field is checked. If unchecked, password is changed successfully, but without notification to User.

`Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 79, in on_update
    self.send_password_notification(self.__new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 187, in send_password_notification
    self.email_new_password(new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 135, in email_new_password
    self.password_update_mail(new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 233, in password_update_mail
    "templates/emails/password_update.html", {"new_password": password}, now=True)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 278, in send_login_mail
    delayed=(not now) if now!=None else self.flags.delay_emails, retry=3)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/__init__.py", line 418, in sendmail
    communication=communication, now=now, read_receipt=read_receipt, is_notification=is_notification)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/queue.py", line 60, in send
    email_account = get_outgoing_email_account(True, append_to=reference_doctype)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/smtp.py", line 54, in get_outgoing_email_account
    email_account = get_default_outgoing_email_account(raise_exception_not_set=raise_exception_not_set)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/smtp.py", line 84, in get_default_outgoing_email_account
    email_account.password = email_account.get_password(raise_exception=False)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/base_document.py", line 660, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/utils/password.py", line 16, in get_decrypted_password
    return decrypt(auth[0][0])
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/utils/password.py", line 101, in decrypt
    plain_text = cstr(cipher_suite.decrypt(encode(pwd)))
  File "/home/frappe/benches/bench-2017-04-19/env/lib/python2.7/site-packages/cryptography/fernet.py", line 103, in decrypt
    raise InvalidToken
InvalidToken

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 281, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 790, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 79, in on_update
    self.send_password_notification(self.__new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 187, in send_password_notification
    self.email_new_password(new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 135, in email_new_password
    self.password_update_mail(new_password)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 233, in password_update_mail
    "templates/emails/password_update.html", {"new_password": password}, now=True)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/core/doctype/user/user.py", line 278, in send_login_mail
    delayed=(not now) if now!=None else self.flags.delay_emails, retry=3)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/__init__.py", line 418, in sendmail
    communication=communication, now=now, read_receipt=read_receipt, is_notification=is_notification)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/queue.py", line 60, in send
    email_account = get_outgoing_email_account(True, append_to=reference_doctype)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/smtp.py", line 54, in get_outgoing_email_account
    email_account = get_default_outgoing_email_account(raise_exception_not_set=raise_exception_not_set)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/email/smtp.py", line 84, in get_default_outgoing_email_account
    email_account.password = email_account.get_password(raise_exception=False)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/base_document.py", line 660, in get_password
    return get_decrypted_password(self.doctype, self.name, fieldname, raise_exception=raise_exception)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/utils/password.py", line 16, in get_decrypted_password
    return decrypt(auth[0][0])
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/utils/password.py", line 101, in decrypt
    plain_text = cstr(cipher_suite.decrypt(encode(pwd)))
  File "/home/frappe/benches/bench-2017-04-19/env/lib/python2.7/site-packages/cryptography/fernet.py", line 103, in decrypt
    raise InvalidToken
InvalidToken`

**Comment by mbauskar** [comment]
@umairsy, can not replicate the error, tried checking `Send Notification to User` field

**Comment by krnkris** [comment]
It may be a problem with the password?
I mean a character in the password?

**Comment by jwrober** [comment]
@umairsy - please help us validate this issue. If not, we will close.

**Comment by sagarvora** [comment]
Looks like this has been fixed, closing.
