### ISSUE TITLE
Error when creating new Attendance

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8526]
Reported by Customer via: https://frappe.erpnext.com/desk#Form/Issue/WN-SUP24429

Steps:

1. Select Employee
2. Update Status
3. Select Date
4. Save

When saving, getting following error message.

Please type some additional information that could help us reproduce this issue:

App Versions

{
	"erpnext": "8.0.13",
	"frappe": "8.0.18"
}
Route

Form/Attendance/New Attendance 1
Error Report

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 254, in _save
    self.insert()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 193, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/erpnext/erpnext/hr/doctype/attendance/attendance.py", line 52, in validate
    self.validate_attendance_date()
  File "/home/frappe/benches/bench-2017-04-19/apps/erpnext/erpnext/hr/doctype/attendance/attendance.py", line 40, in validate_attendance_date
    elif getdate(self.attendance_date) < frappe.db.get_value("Employee", self.employee, "date_of_joining"):
TypeError: can't compare datetime.date to NoneType

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 254, in _save
    self.insert()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 193, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-04-19/apps/frappe/frappe/model/document.py", line 661, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-04-19/apps/erpnext/erpnext/hr/doctype/attendance/attendance.py", line 52, in validate
    self.validate_attendance_date()
  File "/home/frappe/benches/bench-2017-04-19/apps/erpnext/erpnext/hr/doctype/attendance/attendance.py", line 40, in validate_attendance_date
    elif getdate(self.attendance_date) < frappe.db.get_value("Employee", self.employee, "date_of_joining"):
TypeError: can't compare datetime.date to NoneType

**Comment by mbauskar** [comment]
already fixed https://github.com/frappe/erpnext/pull/8483 and released in erpnext version 8.0.15
