### ISSUE TITLE
Problem with Web Forms in V8

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8555]
Hi,

It appears there's a major issue with Web Forms in V8. Please find steps to replicate below:

1. Created a new custom DocType ('Visitor' in CRM module)
2. Created a Web Form linked to the new DocType
3. Tried to view the web form and got the error below

```
Traceback (most recent call last):
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 32, in render
data = render_page_by_language(path)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 101, in render_page_by_language
return render_page(path)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
return build(path)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
return build_page(path)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
context = get_context(path)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/context.py", line 18, in get_context
context = build_context(context)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/context.py", line 80, in build_context
ret = context.doc.get_context(context)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 145, in get_context
self.build_as_list(context)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 207, in build_as_list
get_list_context(context)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/www/list.py", line 19, in get_context
context.update(get_list_context(context, doctype) or {})
File "/home/erpnext/frappe-bench/apps/frappe/frappe/www/list.py", line 117, in get_list_context
module = load_doctype_module(doctype)
File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/utils.py", line 173, in load_doctype_module
raise ImportError, 'Module import failed for {0} ({1})'.format(doctype, module_name)
ImportError: Module import failed for Visitor (erpnext.crm.doctype.visitor.visitor)
```

Kindly help resolve this

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Did you published web form visitor?

**Web Form**
![screen shot 2017-04-26 at 4 47 12 pm](https://cloud.githubusercontent.com/assets/8780500/25431900/1150c110-2aa0-11e7-959e-411bb592adbc.png)

**Portal View**

![screen shot 2017-04-26 at 4 47 22 pm](https://cloud.githubusercontent.com/assets/8780500/25431912/1bf6a242-2aa0-11e7-8f47-9dd144e38c46.png)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Yes I did. Please find below

![webform for custom doctype issue](https://cloud.githubusercontent.com/assets/9269337/25433349/0ca88eb0-2a80-11e7-828e-e9cb0f154c47.png)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

It appears the error comes up when the 'Allow Multiple' option is selected in the Web Form

Please check

Thanks

**Comment by rmehta** [comment]
pushed a fix
