### ISSUE TITLE
No such file or directory: u'./assets/frappe/css/daterangepicker.css'

### ISSUE THREAD

**Issue by mfazilp** [frappe/erpnext#8578]
Am getting this error 

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 281, in get_js
    with open(contentpath, "r") as srcfile:
IOError: [Errno 2] No such file or directory: u'./assets/frappe/css/daterangepicker.css'
Report this issue

**Comment by nabinhait** [comment]
Please refresh your browser using Ctrl + Shift + R and try again.
