### ISSUE TITLE
error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by mfazilp** [frappe/erpnext#8579]
Am getting this error while doing bench update

INFO:bench.utils:updating bench
INFO:bench.utils:git pull
error: cannot open .git/FETCH_HEAD: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/usr/src/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/bench-repo/bench/commands/update.py", line 35, in update
    update_bench()
  File "/usr/src/bench-repo/bench/utils.py", line 229, in update_bench
    exec_cmd("git pull", cwd=cwd)
  File "/usr/src/bench-repo/bench/utils.py", line 130, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git pull

**Comment by pratu16x7** [comment]
Looks like a permissions issue on the .git folder. 
Check if this helps: https://discuss.erpnext.com/t/solved-updating-from-7-to-7-1/17443/10?u=pratu16x7

**Comment by nabinhait** [comment]
You can also refer https://github.com/frappe/erpnext/issues/8575
