### ISSUE TITLE
ERPNext v8 Email setup.  Doesn't like names with an apostrophe in them

### ISSUE THREAD

**Issue by jvantslot** [frappe/erpnext#8606]
I set an account in v8 with my full name as the name for the account.  It appears that the MySQL insert isn't properly escaping the apostrophe in my last name.  FYI My last name is Van't Slot, but I assume it would have problems with Irish names as well.

Error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 't Slot'' at line 2")`

Here's the full error:

Title: pull_from_email_account
   
Error:`  {'retry': 0, 'log': <function log at 0xb5f6241c>, 'site': u'erp.earthlyte.com', 'event': u'all', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0xb5ec2d84>, 'user': u'Administrator', 'kwargs': {'email_account': u"James Van't Slot"}, 'async': True, 'job_name': u"pull_from_email_account|James Van't Slot"}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 65, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 700, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 253, in receive
    emails = email_server.get_messages()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 114, in get_messages
    uid_list = email_list = self.get_new_mails()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 169, in get_new_mails
    self.check_imap_uidvalidity()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 194, in check_imap_uidvalidity
    and email_account='{email_account}'""".format(email_account=self.settings.email_account))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
Programming
Error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 't Slot'' at line 2")`

**Comment by BradMK** [comment]
Same issue, apostrophes in email account names mess things up. We are in Ireland so majority of the  employees would have apostrophes in their names (O'Sullivan, O'Meara, O'Neill, O'Mahony) as those types of second names are very common, to make things worse our Company Name also has an apostrophe in it so account names like "Comp'any Name Sales", or "Comp'any Name Payroll" are not an option at the moment.
