### ISSUE TITLE
Error during `bench update --upgrade`

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#8618]
I'm encountering an error when running `bench update --upgrade`.

Upgrading from:
```
ERPNext: v6.27.25
Frappe Framework: v6.27.23
```

On a Ubuntu box, 14.04, all packages up-to-date

When patch `frappe.patches.v7_1.rename_scheduler_log_to_error_log` runs, I see the exception: `frappe.exceptions.MandatoryError: [Version, _VER000001]: doclist_json`

Rerunning `bench update --upgrade` seems to continue, and gets further, but the error I do see leaves me worried about data integrity. 

Full stack trace follows:

```
Executing frappe.patches.v7_1.rename_scheduler_log_to_error_log in ship (ship)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 211, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/patches/v7_1/rename_scheduler_log_to_error_log.py", line 5, in execute
    frappe.rename_doc('DocType', 'Scheduler Log', 'Error Log')
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 668, in rename_doc
    return rename_doc(*args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 75, in rename_doc
    new_doc.add_comment('Edit', _("renamed from {0} to {1}").format(frappe.bold(old), frappe.bold(new)))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 979, in add_comment
    out.insert(ignore_permissions=True)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 194, in insert
    self._validate()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 400, in _validate
    self._validate_mandatory()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py", line 620, in _validate_mandatory
    name=self.name))
frappe.exceptions.MandatoryError: [Version, _VER000001]: doclist_json
```

When running update again, immediately after, the update procedure continues, and starts by warning about Celery being replaced with Python RQ.

```
$ bench update --upgrade

This update will remove Celery config and prepare the bench to use Python RQ.
And it will overwrite Procfile and supervisor.conf.
If you don't know what this means, type Y ;)

Do you want to continue? [y/N]:
```

**Comment by vrms** [comment]
this seems to be better suited as a topic on the forum. Please post it there.

**Comment by sagar30051991** [comment]
try this
bench mysql
ALTER TABLE tabDocType ADD COLUMN restrict_to_domain VARCHAR(40);
bench migrate
bench --force reload-doc core doctype page
bench update
