### ISSUE TITLE
set-limits not working

### ISSUE THREAD

**Issue by hanselke** [frappe/erpnext#8634]
bench --site blahblah set-limits --limit users 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 425, in set_limits
    _set_limits(context, site, limits)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 458, in _set_limits
    update_limits(new_limits)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/limits.py", line 158, in update_limits
    disable_users(limits)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/user.py", line 303, in disable_users
    system_manager = get_system_managers(only_name=True)[-1]

**Comment by chdecultot** [comment]
Hi @hanselke,

It seems like you haven't created a system manager for your site.

Can you first create a system manager before trying to set limits again ?

To create a system manager just complete the setup wizard.

**Comment by adityaduggal** [comment]
@hanselke @chdecultot This is a forum query instead of github.
Please post it on forums https://discuss.erpnext.com/
Since the system needs you to create a System Manager first
