### ISSUE TITLE
Error when trying to export Financial Statements in Excel format

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8653]
Hi,

there's an error when trying to export Financial Statements (Trial Balance, Balance Sheet, P&L) in Excel format:

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/desk/query_report.py", line 155, in export_query
    xlsx_file = make_xlsx(result, "Query Report")
  File "/home/frappe/benches/bench-2017-05-02/apps/frappe/frappe/utils/xlsxutils.py", line 29, in make_xlsx
    obj = obj.handle(item)
  File "/home/frappe/benches/bench-2017-05-02/env/lib/python2.7/site-packages/html2text/__init__.py", line 134, in handle
    self.feed(data)
  File "/home/frappe/benches/bench-2017-05-02/env/lib/python2.7/site-packages/html2text/__init__.py", line 130, in feed
    data = data.replace("", "")
AttributeError: 'float' object has no attribute 'replace'
```

Kind regards,

**Comment by manassolanki** [comment]
Fixed
