### ISSUE TITLE
I have this error coming all the times, regardless the modules I am on

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#8654]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/client.py", line 281, in get_js
    with open(contentpath, "r") as srcfile:
IOError: [Errno 2] No such file or directory: u'./assets/frappe/css/daterangepicker.css'
```

**Comment by nabinhait** [comment]
Please try after clearing browser's cache or after hard refreshing using Ctrl + Shift + R, the error should go away.

**Comment by fderyckel** [comment]
It. Thank you very much for the tip. (It does work on chrome, but i could
not make it work on Safari)
Any explanation on why it did this.
Thanks again for your fantastic product.
Best,
François

2017-05-02 17:11 GMT+02:00 Nabin Hait <notifications@github.com>:
