### ISSUE TITLE
KeyError: u'print' from patch v7_1.disabled_print_settings_for_custom_print_format

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#8697]
Hello,

While updating from v6 to v8, i'm getting the following exception;
```
Executing frappe.patches.v7_1.disabled_print_settings_for_custom_print_format
KeyError: u'print'
```
```
# bench version
erpnext 8.0.22
frappe 8.0.35
```

Same issue has also been reported by another user on the discourse forum;
https://discuss.erpnext.com/t/keyerror-uprint-by-update-from-v6-to-v8/23405

Full stack trace follows;

```
Executing frappe.patches.v7_1.disabled_print_settings_for_custom_print_format in ship (ship)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 211, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/patches/v7_1/disabled_print_settings_for_custom_print_format.py", line 9, in execute
    frappe.reload_doctype('Print Format')
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 651, in reload_doctype
    force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 663, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/utils.py", line 152, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 23, in import_file
    path = get_file_path(module, dt, dn)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 30, in get_file_path
    path = os.path.join(get_module_path(module),
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/modules/utils.py", line 144, in get_module_path
    return frappe.get_module_path(module)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 688, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
KeyError: u'print'
```

**Comment by jwrober** [comment]
Would it be better to upgrade from v6 to v7 first, stabalize and then go from v7 to v8? I am not sure the platform is really designed to jump 2 major versions all at once.

**Comment by jevonearth** [comment]
@jwrober I don't think that will help with this particular error, but generally, I think you are correct.

We need to get `bench switch-to-v6` and `bench switch-to-v7` implemented in bench.

**Comment by nabinhait** [comment]
Pushed a fix for the above error, please try to update again.
