### ISSUE TITLE
[v8 upgrade] 'SystemSettings' object has no attribute 'enable_password_policy'

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#8736]
Hello, I'm trying upgrade from v7 t v8.

`bench update --upgrade`

A full detail is attached.
[full_detail.txt](https://github.com/frappe/erpnext/files/983437/full_detail.txt)

Thanks

```
Executing frappe.patches.v8_0.set_currency_field_precision in alecol (alecol)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands/site.py", line 214, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/erp/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erp/frappe-bench/apps/frappe/frappe/patches/v8_0/set_currency_field_precision.py", line 21, in execute
    ss.save()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.py", line 15, in validate
    enable_password_policy = cint(self.enable_password_policy) and True or False
AttributeError: 'SystemSettings' object has no attribute 'enable_password_policy'
```

**Comment by joolsr** [comment]
Enable password policy is new cose only added today, so I suspect that the patches.txt file needs updating to include this field for upgrades ..

**Comment by sahil19896** [comment]
go the address and open file
/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.py
then go to line number, comment the field "self.enable_password_policy" and "self.minimum_password_score" give below

```
enable_password_policy = "" #cint(self.enable_password_policy) and True or False
minimum_password_score = 0 #cint(self.minimum_password_score) or 0

```
now run the  
```
bench update --upgrade
```
after upgrade revert the changes to originals.

**Comment by nabinhait** [comment]
released a fix, please update again.

**Comment by sathishpy** [comment]
I have raised https://github.com/frappe/erpnext/issues/8767 for similar issue during restore.

**Comment by vishwajeet** [comment]
I am facing the same issue after trying to upgrade
