### ISSUE TITLE
[BUG] Error after fresh install: .tabStudent Batch' doesn't exist

### ISSUE THREAD

**Issue by paulator** [frappe/erpnext#8753]
Hi,

I did already multiple ERPNext installation but I never had this error:

After a fresh installation without any errors (productive environment) I get the following error message. 
Version:	"erpnext": "8.0.24",
Version:	"frappe": "8.0.39"

Error Report

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/page/desktop/desktop.py", line 21, in get_help_messages
    messages += frappe.get_attr(fn)()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/utilities/activation.py", line 54, in get_help_messages
    if get_level() > 6:
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/utilities/activation.py", line 40, in get_level
    if frappe.db.count('Student Batch') > 5:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 790, in count
    from `tab%s`""" % (dt,))[0][0]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'f8705b9035c2f476.tabStudent Batch' doesn't exist")
```
Request Data

{
	"type": "POST",
	"args": {
		"cmd": "frappe.core.page.desktop.desktop.get_help_messages"
	},
	"url": "/"
}

**Comment by paulator** [comment]
Unfortunately I was on branch master with frappe and on branch develop on erpnext. 
I had to do a "bench switch-to-develop && bench update --patch" and a  "bench switch-to-master && bench update --patch" to fix the problem.
