### ISSUE TITLE
Database restore results in error AttributeError: 'SystemSettings' object has no attribute 'enable_password_policy'

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#8767]
Hi,

I am trying to restore a backup taken from erpnext version
frappe@digitana:~/frappe-bench$ bench version
erpnext 8.0.17
frappe 8.0.24

on to another site running latest code
spoojary@osboxes:~/factory-bench$ bench version
erpnext 8.0.24
frappe 8.0.42

However the restore results in following error
spoojary@osboxes:~/factory-bench$ bench --site skpi.in --force restore 20170510_173004_4e98fd00_database.sql 
MySQL root password: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/spoojary/factory-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/spoojary/factory-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/spoojary/factory-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/commands/site.py", line 108, in restore
    force=context.force)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/commands/site.py", line 64, in _new_site
    frappe.utils.scheduler.toggle_scheduler(enable_scheduler)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/utils/scheduler.py", line 214, in toggle_scheduler
    ss.save()
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 231, in save
    return self._save(*args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 264, in _save
    self.run_before_save_methods()
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 667, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/spoojary/factory-bench/apps/frappe/frappe/model/document.py", line 661, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/spoojary/factory-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.py", line 15, in validate
    enable_password_policy = cint(self.enable_password_policy) and True or False
AttributeError: 'SystemSettings' object has no attribute 'enable_password_policy'

**Comment by nick9822** [comment]
@sathishpy 
Did you bench update?

**Comment by sathishpy** [comment]
Yes. That gave me the latest version on target.
erpnext 8.0.24
frappe 8.0.42
