### ISSUE TITLE
Update Error V7 to V8

### ISSUE THREAD

**Issue by faztp12** [frappe/erpnext#8822]
Hii
Update fails on migrating. This is the traceback:
`Executing erpnext.patches.v7_2.mark_students_active in ho (9a76a857ad399b49)
/home/consoleadmin/frappe-bench/apps/erpnext/erpnext/schools/doctype/student_batch_student/student_batch_student.json missing
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/commands/site.py", line 214, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/consoleadmin/frappe-bench/apps/erpnext/erpnext/patches/v7_2/mark_students_active.py", line 6, in execute
    frappe.db.sql("update `tabStudent Batch Student` set active=1")
  File "/home/consoleadmin/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/consoleadmin/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'active' in 'field list'")`

ERPNext: v7.2.18
Frappe: v7.2.14
I was able to update v7 to v8 without any trouble.
Thank you.

**Comment by taoxen** [comment]
How was the problem fixed? I am facing the same problem when I tried to upgrade the VM.

**Comment by nabinhait** [comment]
Pushed the fix in develop branch, pending to release (merge in master).

https://github.com/frappe/erpnext/commit/7bf810300e1a4b0a603819f457987d8e08d8d64d

**Comment by faztp12** [comment]
Hii @nabinhait 
The issue on `frappe.patches.v8_0.set_currency_field_precision` still persist in frappe release `8.0.45`.
The solution you had posted (https://discuss.erpnext.com/t/error-upgrading-to-v8/23718) works though.
reload the core doc in the patch itself might be a possible solution ?
Thank you :)

**Comment by Helkyd** [comment]
Does this means that for me to have this fix i need to make my Production server a Developer server fix the bug and return to Production Server ?

**Comment by nabinhait** [comment]
@faztp12 
> reload the core doc in the patch itself might be a possible solution ?
Yes, I already added the reload_doc in the patch.

@Helkyd The fix has already been merged to master and released. So, no need to switch the branch.
