### ISSUE TITLE
errors on 8.0.31 upgrade

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8932]
bench update

.
.
.
--Error in:/opt/prod_erpnext/apps/frappe/frappe/public/js/frappe/form/multi_select_dialog.js--
Traceback (most recent call last):
  File "/opt/prod_erpnext/apps/frappe/frappe/build.py", line 144, in pack
    jsm.minify(tmpin, tmpout)
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 210, in minify
    self._jsmin()
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 201, in _jsmin
    self._action(1)
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 131, in _action
    raise UnterminatedStringLiteral()
UnterminatedStringLiteral

Wrote ./assets/js/dialog.min.js - 69k
--Error in:/opt/prod_erpnext/apps/frappe/frappe/public/js/frappe/form/multi_select_dialog.js--
Traceback (most recent call last):
  File "/opt/prod_erpnext/apps/frappe/frappe/build.py", line 144, in pack
    jsm.minify(tmpin, tmpout)
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 210, in minify
    self._jsmin()
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 201, in _jsmin
    self._action(1)
  File "/opt/prod_erpnext/apps/frappe/frappe/utils/minify.py", line 131, in _action
    raise UnterminatedStringLiteral()
UnterminatedStringLiteral
.
.
.
.

**Comment by taiicare** [comment]
Same issue, I cannot build (minify) the js apps/frappe/frappe/public/js/frappe/form/multi_select_dialog.js  

This will lead to inactive button inside the erp

**Comment by fproldan** [comment]
Same issue here

**Comment by almeidapaulopt** [comment]
after frappe update 8.0.51 the error is

bench update
.
.
.
Syncing help database...
module.js:471
    throw err;
    ^

Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/prod_erpnext/apps/frappe/frappe/build.js:4:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by ishanloya** [comment]
Same issue

**Comment by tundebabzy** [comment]
Hello. Try to install less with:
`npm install less`

Make sure you are in the frappe-bench directory. I will also try to add this to the documentation.

Please reopen the issue if this does not work.

**Comment by tundebabzy** [comment]
Also Have a look at:

https://discuss.erpnext.com/t/bench-build-error-babel-core-module-not-found/24016/5?u=joez
