### ISSUE TITLE
Error on Release v8.0.33 update

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#8946]
```
Syncing help database...
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/erp/erpnext/apps/frappe/frappe/build.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by joezsweet** [comment]
Have a look at:

https://discuss.erpnext.com/t/bench-build-error-babel-core-module-not-found/24016/5?u=joez

**Comment by fproldan** [comment]
@joezsweet Thanks for your quick reply, it's works!
