### ISSUE TITLE
AttributeError: 'CustomerGroup' object has no attribute 'parent_doc'

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#9226]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-06-07/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-06-07/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-07/apps/frappe/frappe/model/document.py", line 262, in _save
    self.validate_higher_perm_levels()
  File "/home/frappe/benches/bench-2017-06-07/apps/frappe/frappe/model/document.py", line 454, in validate_higher_perm_levels
    self.reset_values_if_no_permlevel_access(has_access_to, high_permlevel_fields)
  File "/home/frappe/benches/bench-2017-06-07/apps/frappe/frappe/model/base_document.py", line 775, in reset_values_if_no_permlevel_access
    self.parent_doc.get_latest()
AttributeError: 'CustomerGroup' object has no attribute 'parent_doc'
```

**Comment by manassolanki** [comment]
No traces for the support
