### ISSUE TITLE
Deadlock Found while submitting Sales Invoice

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#9274]
**Traceback:**
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 741, in submit
    self._submit()
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 730, in _submit
    self.save()
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 280, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 793, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/model/document.py", line 660, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-13/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 114, in on_submit
    self.update_billing_status_in_dn()
  File "/home/frappe/benches/bench-2017-06-13/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 776, in update_billing_status_in_dn
    frappe.get_doc("Delivery Note", dn).update_billing_percentage(update_modified=update_modified)
  File "/home/frappe/benches/bench-2017-06-13/apps/erpnext/erpnext/controllers/stock_controller.py", line 313, in update_billing_percentage
    }, update_modified)
  File "/home/frappe/benches/bench-2017-06-13/apps/erpnext/erpnext/controllers/status_updater.py", line 287, in _update_percent_field
    where name='%(name)s'""" % args)
  File "/home/frappe/benches/bench-2017-06-13/apps/frappe/frappe/database.py", line 149, in sql
    self._cursor.execute(query)
  File "/home/frappe/benches/bench-2017-06-13/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-06-13/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**SHOW ENGINE INNODB STATUS**

------------------------
LATEST DETECTED DEADLOCK
------------------------
2017-06-13 13:06:49 7fcfbd886700
*** (1) TRANSACTION:
TRANSACTION 798542788, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 43 lock struct(s), heap size 6544, 25 row lock(s), undo log entries 24
MySQL thread id 15819508, OS thread handle 0x7fda459f6700, query id 441601750 localhost e1496133bfd42852 updating
update `tabSales Invoice` set idx = idx + 1 where name='SVSINV-16170197'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 847117 page no 38 n bits 80 index `PRIMARY` of table `e1496133bfd42852`.`tabSales Invoice` trx table locks 20 total table locks 2  trx id 798542788 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** (2) TRANSACTION:
TRANSACTION 798542634, ACTIVE 1 sec starting index read
mysql tables in use 2, locked 2
31 lock struct(s), heap size 6544, 22 row lock(s), undo log entries 13
MySQL thread id 15819487, OS thread handle 0x7fcfbd886700, query id 441602396 localhost e1496133bfd42852 updating
update `tabDelivery Note`
                                set per_billed = round(
                                        ifnull((select
                                                ifnull(sum(if(amount > billed_amt, abs(billed_amt), abs(amount))), 0)
                                                / sum(abs(amount)) * 100
                                        from `tabDelivery Note Item` where parent="SVSDN-00406"), 0), 2)
                                        , modified = now(), modified_by = "sales@xxxxx"
                                where name='SVSDN-00406'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 847117 page no 38 n bits 80 index `PRIMARY` of table `e1496133bfd42852`.`tabSales Invoice` trx table locks 13 total table locks 2  trx id 798542634 lock_mode X locks rec but not gap lock hold time 1 wait time before grant 0
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 847119 page no 37 n bits 72 index `PRIMARY` of table `e1496133bfd42852`.`tabDelivery Note` trx table locks 13 total table locks 2  trx id 798542634 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** WE ROLL BACK TRANSACTION (2)

**Comment by rmehta** [comment]
This will be fixed by https://github.com/frappe/frappe/pull/3495
