### ISSUE TITLE
Module import failed for Domain 

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#9398]
Executing erpnext.patches.v8_0.create_domain_docs	#16-05-2017 in test_site1.com (68543595c1b21b73)
/home/vishal/frappe-workshop/apps/frappe/frappe/core/doctype/domain/domain.json missing
/home/vishal/frappe-workshop/apps/frappe/frappe/core/doctype/domain_settings/domain_settings.json missing
/home/vishal/frappe-workshop/apps/frappe/frappe/core/doctype/has_domain/has_domain.json missing
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vishal/frappe-workshop/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/commands/site.py", line 214, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/vishal/frappe-workshop/apps/erpnext/erpnext/patches/v8_0/create_domain_docs.py", line 16, in execute
    create_domain(domain)
  File "/home/vishal/frappe-workshop/apps/erpnext/erpnext/patches/v8_0/create_domain_docs.py", line 50, in create_domain
    doc = frappe.new_doc("Domain")
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/__init__.py", line 582, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/model/create_new.py", line 19, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/model/create_new.py", line 37, in make_new_doc
    "docstatus": 0
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/__init__.py", line 606, in get_doc
    return frappe.model.document.get_doc(arg1, arg2)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/model/document.py", line 49, in get_doc
    controller = get_controller(doctype)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/model/base_document.py", line 35, in get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/vishal/frappe-workshop/apps/frappe/frappe/modules/utils.py", line 184, in load_doctype_module
    raise ImportError, 'Module import failed for {0} ({1})'.format(doctype, module_name)
ImportError: Module import failed for Domain (frappe.core.doctype.domain.domain)

**Comment by mbauskar** [comment]
@vishdha,

can you share the versions of frappe and erpnext? use `bench version` to get version

**Comment by tiwiex** [comment]
Hello. I am trying t run erpnext 8.0.36, frappe 8.0.36
I get ImportError: Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series)

Wizard works fine but I have an old backup and suspect I need an old install as the database import on latest erpnext breaks the site.

Any help would be appreciated greatly.
