### ISSUE TITLE
Bug in Password

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#9420]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 263, in _save
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 892, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 875, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/model/document.py", line 660, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/core/doctype/user/user.py", line 53, in validate
    self.password_strength_test()
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/core/doctype/user/user.py", line 417, in password_strength_test
    result = test_password_strength(self.__new_password, '', None, user_data)
  File "/home/frappe/benches/bench-2017-06-21/apps/frappe/frappe/core/doctype/user/user.py", line 547, in test_password_strength
    enable_password_policy = cint(password_policy.get("enable_password_policy", 0))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by rohitwaghchaure** [comment]
Fixed via PR https://github.com/frappe/frappe/pull/3536
