### ISSUE TITLE
Problem while updating from Ver 7 to Ver 8

### ISSUE THREAD

**Issue by yaochang007** [frappe/erpnext#9449]
Problem while updating from Ver 7 to Ver 8, 

[john@Full-20170605-1gb-sgp1-01 frappe-bench]$ bench update
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up-to-date.
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling erpnext
INFO:bench.utils:git pull  upstream master
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.utils:find . -name "*.pyc" -delete
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
INFO:bench.utils:./env/bin/pip install -q -r /home/john/.bench/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
Updating node libraries...
INFO:bench.utils:npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN frappe@ No description
Backing up sites...
Patching sites...
Migrating site1.local
Executing erpnext.patches.v8_0.move_perpetual_inventory_setting in site1.local (1bd3e0294da19198)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/john/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/john/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/john/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/commands/site.py", line 214, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/john/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/john/frappe-bench/apps/erpnext/erpnext/patches/v8_0/move_perpetual_inventory_setting.py", line 8, in execute
    frappe.reload_doctype('Company')
  File "/home/john/frappe-bench/apps/frappe/frappe/__init__.py", line 651, in reload_doctype
    force=force, reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/__init__.py", line 663, in reload_doc
    return frappe.modules.reload_doc(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/utils.py", line 152, in reload_doc
    return import_files(module, dt, dn, force=force, reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 19, in import_files
    reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 24, in import_file
    ret = import_file_by_path(path, force, pre_process=pre_process, reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 58, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 129, in import_doc
    doc.insert()
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 219, in insert
    self.run_post_save_methods()
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 789, in run_post_save_methods
    self.run_method("on_update")
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 874, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/john/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/john/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 208, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/john/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 257, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/john/frappe-bench/apps/frappe/frappe/modules/utils.py", line 184, in load_doctype_module
    raise ImportError, 'Module import failed for {0} ({1})'.format(doctype, module_name)
ImportError: Module import failed for Company (erpnext.setup.doctype.company.company)

**Comment by yaochang007** [comment]
@manassolanki ,

Hi I have created new thread here, how can we solve this issue?

**Comment by rmehta** [comment]
@yaochang007 do you have local changes?

**Comment by yaochang007** [comment]
@rmehta ,

I don't have local changes in company.py

**Comment by yaochang007** [comment]
@rmehta ,

What should I do to fix this? I confirm I didn't change anything in the company.py, so can I just run git pull in ERPnext to update the file?

**Comment by yaochang007** [comment]
@manassolanki @rmehta ,

I have run git pull in both frappe and erpnext directory, and execute bench migrate, then I executed the bench update, it successfully upgrade to 8.1 as shown below:

![image](https://user-images.githubusercontent.com/13130742/27683973-9970ecc8-5cfa-11e7-888c-a891b2f71bc1.png)

But when I enter my login page, the login page is spoiled and I can not login as shown below:

![image](https://user-images.githubusercontent.com/13130742/27684009-c28815c8-5cfa-11e7-9545-bd19de9d598a.png)

Do you know why this will happen?

**Comment by rohitwaghchaure** [comment]
Any error on console log? If yes, share an error traceback

**Comment by yaochang007** [comment]
@rohitwaghchaure 
In worker.error.log, there seems nothing special.

`18:01:04 short: frappe.utils.background_jobs.execute_job(async=True, event=u'hourly', job_name=u'frappe.model.utils.link_count.update_link_count', kwargs={}, method=u'frappe.model.utils.link_count.update_link_count', site=u'site1.local', user=u'Administrator') (247c463c-be81-4af4-969b-5c56f45645dd)
18:01:04 short: Job OK (247c463c-be81-4af4-969b-5c56f45645dd)
18:01:04 Result is kept for 500 seconds
18:01:04 Cleaning registries for queue: short
18:01:04 
18:01:04 *** Listening on short...
18:01:04 short: frappe.utils.background_jobs.execute_job(async=True, event=u'hourly', job_name=u'frappe.model.utils.user_settings.sync_user_settings', kwargs={}, method=u'frappe.model.utils.user_settings.sync_user_settings', site=u'site1.local', user=u'Administrator') (c1241b87-ca31-4881-a8bf-257aeaca2583)
18:01:04 short: Job OK (c1241b87-ca31-4881-a8bf-257aeaca2583)
18:01:04 Result is kept for 500 seconds
18:01:04 
18:01:04 *** Listening on short...
18:01:04 short: frappe.utils.background_jobs.execute_job(async=True, event=u'hourly', job_name=u'frappe.utils.error.collect_error_snapshots', kwargs={}, method=u'frappe.utils.error.collect_error_snapshots', site=u'site1.local', user=u'Administrator') (453d044c-e6cc-4ef4-9207-6a2d28f20fa0)
18:01:04 short: Job OK (453d044c-e6cc-4ef4-9207-6a2d28f20fa0)
18:01:04 Result is kept for 500 seconds
18:01:04 
18:01:04 *** Listening on short...
18:01:04 short: frappe.utils.background_jobs.execute_job(async=True, event=u'hourly', job_name=u'frappe.desk.page.backups.backups.delete_downloadable_backups', kwargs={}, method=u'frappe.desk.page.backups.backups.delete_downloadable_backups', site=u'site1.local', user=u'Administrator') (a2840731-75f6-431d-bd20-24553ad292d1)
18:01:04 short: Job OK (a2840731-75f6-431d-bd20-24553ad292d1)
18:01:04 Result is kept for 500 seconds`

in web.error.log, it only show below information for yesterday.

`[2017-06-29 10:36:15 +0000] [596] [INFO] Handling signal: term
[2017-06-29 10:36:15 +0000] [722] [INFO] Worker exiting (pid: 722)
[2017-06-29 10:36:15 +0000] [596] [INFO] Shutting down: Master
[2017-06-29 10:36:27 +0000] [28261] [INFO] Starting gunicorn 19.6.0
[2017-06-29 10:36:27 +0000] [28261] [INFO] Listening at: http://127.0.0.1:8000 (28261)
[2017-06-29 10:36:27 +0000] [28261] [INFO] Using worker: sync
[2017-06-29 10:36:27 +0000] [28292] [INFO] Booting worker with pid: 28292`

in frappe.log, it only show below info during the period.

`[DEBUG] 2017-06-29 18:09:05,145 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:13:05,457 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:17:05,783 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:21:06,114 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:25:06,431 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:29:06,754 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:33:07,093 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:37:07,394 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:41:07,718 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:45:08,009 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:49:08,337 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:53:08,652 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 18:57:08,956 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:01:09,313 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:05:09,633 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:09:09,930 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:13:10,263 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:17:10,586 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:21:10,882 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:25:11,203 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:29:11,520 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:33:11,842 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:37:12,148 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:41:12,453 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:45:12,746 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:49:13,051 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2017-06-29 19:53:13,357 | /home/john/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local`

in bench.log, it got below infor for yesterday.

`2017-06-29 08:30:09,941 INFO updating bench
2017-06-29 08:30:09,941 INFO git pull
2017-06-29 08:30:19,002 INFO ./env/bin/pip install Pillow
2017-06-29 08:30:20,434 INFO pulling erpnext
2017-06-29 08:30:20,442 INFO git pull  upstream master
2017-06-29 08:30:22,325 INFO find . -name "*.pyc" -delete
2017-06-29 08:30:22,391 INFO ./env/bin/pip install --upgrade pip
2017-06-29 08:30:25,625 INFO ./env/bin/pip install -q -r /home/john/.bench/requirements.txt
2017-06-29 08:30:26,701 INFO ./env/bin/pip install -q -r ./apps/frappe/requirements.txt
2017-06-29 08:30:32,417 INFO ./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
2017-06-29 08:30:34,069 INFO npm install
2017-06-29 10:33:36,568 INFO updating bench
2017-06-29 10:33:36,569 INFO git pull
2017-06-29 10:33:43,533 INFO ./env/bin/pip install Pillow
2017-06-29 10:33:44,635 INFO pulling erpnext
2017-06-29 10:33:44,644 INFO git pull  upstream master
2017-06-29 10:33:48,172 INFO find . -name "*.pyc" -delete
2017-06-29 10:33:48,370 INFO ./env/bin/pip install --upgrade pip
2017-06-29 10:33:50,285 INFO ./env/bin/pip install -q -r /home/john/.bench/requirements.txt
2017-06-29 10:33:51,702 INFO ./env/bin/pip install -q -r ./apps/frappe/requirements.txt
2017-06-29 10:34:02,482 INFO ./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
2017-06-29 10:34:04,531 INFO npm install
2017-06-29 10:36:12,628 INFO sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:`

If need to run anything in bench console, please let me know.

**Comment by rmehta** [comment]
Cannot replicate
