### ISSUE TITLE
Filter bugs 8.2

### ISSUE THREAD

**Issue by federojoavellaneda** [frappe/erpnext#9540]
Hi! we updated to the 8.2 version and we detect a bunch of filter errors.

When select the state does the folowing in the user list for example:
![bug](https://user-images.githubusercontent.com/7256766/27701074-1e20e344-5cd6-11e7-80fc-c20b1c5f80d7.gif)

When select state in others doctype (sales invoice, purchase invoice) the bug is distinct.
and it throws the follow traceback

```
Traceback (most recent call last):
  File "/home/erp/erpnext/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erp/erpnext/apps/frappe/frappe/__init__.py", line 914, in call
    return fn(*args, **newargs)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/reportview.py", line 18, in get
    data = compress(execute(**args), args = args)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/reportview.py", line 23, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 88, in execute
    result = self.build_and_run()
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 100, in build_and_run
    args = self.prepare_args()
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 249, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 270, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/erp/erpnext/apps/frappe/frappe/model/db_query.py", line 323, in prepare_filter_condition
    value = getdate(f.value).strftime("%Y-%m-%d")
  File "/home/erp/erpnext/apps/frappe/frappe/utils/data.py", line 40, in getdate
    return parser.parse(string_date).date()
  File "/home/erp/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/erp/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/erp/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/erp/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 192, in split
    return list(cls(s))
  File "/home/erp/erpnext/env/local/lib/python2.7/site-packages/dateutil/parser.py", line 61, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not list
```

Regards!

ERPNext: v8.2.0 (master)
ERPNext Shopify: v2.0.10 (develop)
Frappe Framework: v8.2.2 (master)

**Comment by rohitwaghchaure** [comment]
Hi @federojoavellaneda 

Can you please pull the latest code and check it again

**Comment by rmehta** [comment]
hi this is fixed in the latest develop

**Comment by federojoavellaneda** [comment]
Hi! this issue still here in ERPnext v8.5.2 y Frappe v8.5.5
