### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#9560]
WN-SUP26052
---
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-06-29/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-06-29/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-06-29/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-06-29/apps/frappe/frappe/__init__.py", line 914, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-06-29/apps/frappe/frappe/desk/query_report.py", line 95, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/benches/bench-2017-06-29/apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 20, in execute
    ignore_closing_entries=True, ignore_accumulated_values_for_fy= True)
  File "/home/frappe/benches/bench-2017-06-29/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 141, in get_data
    add_total_row(out, root_type, balance_must_be, period_list, company_currency)
  File "/home/frappe/benches/bench-2017-06-29/apps/erpnext/erpnext/accounts/report/financial_statements.py", line 236, in add_total_row
    total_row[period.key] += row.get(period.key, 0.0)
TypeError: unsupported operand type(s) for +=: 'float' and 'unicode'
```

**Comment by rohitwaghchaure** [comment]
Wrong end date in fiscal year causing an issue, In fiscal year user has set the end date as 21-12-2017 instead of 19-12-2017, because start date in the fiscal year is 20-12-2016. After update the end date from the backend the issue has resolved
