### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_data''

### ISSUE THREAD

**Issue by aartishinde31** [frappe/erpnext#9563]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 14, in get
    data = get_data(module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 30, in get_data
    data = build_config_from_file(module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 54, in build_config_from_file
    data += get_config(app, module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 157, in get_config
    config = config.get_data()
AttributeError: 'module' object has no attribute 'get_data'

**Comment by tundebabzy** [comment]
Hello @aartishinde31 
Please give details on how to reproduce this

**Comment by nabinhait** [comment]
@aartishinde31 Closing this, please reopen if you are still getting the error.
