### ISSUE TITLE
upgrade fail v7 to v8

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#9599]
<p>Executing erpnext.patches.v7_1.update_portal_roles in vcsing.com (voicecom)<br>Traceback (most recent call last):<br>  File "/usr/lib64/python2.7/runpy.py", line 162, in <em>run</em>module_as_main<br>    "<strong>main</strong>", fname, loader, pkg_name)<br>  File "/usr/lib64/python2.7/runpy.py", line 72, in <em>run</em>code<br>    exec code in run_globals<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 91, in <br>    main()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 17, in main<br>    click.Group(commands=commands)(prog_name='bench')<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 664, in <strong>call</strong><br>    return self.main(*args, **kwargs)<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 644, in main<br>    rv = self.invoke(ctx)<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke<br>    return <em>process</em>result(sub_ctx.command.invoke(sub_ctx))<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 991, in invoke<br>    return <em>process</em>result(sub_ctx.command.invoke(sub_ctx))<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 837, in invoke<br>    return ctx.invoke(self.callback, **ctx.params)<br>  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 464, in invoke<br>    return callback(*args, **kwargs)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func<br>    ret = f(frappe._dict(ctx.obj), *args, **kwargs)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 216, in migrate<br>    migrate(context.verbose, rebuild_website=rebuild_website)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate<br>    frappe.modules.patch_handler.run_all()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all<br>    if not run_single(patchmodule = patch):<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single<br>    return execute_patch(patchmodule, method, methodargs)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch<br>    frappe.get_attr(patchmodule.split()[0] + ".execute")()<br>  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v7_1/update_portal_roles.py", line 10, in execute<br>    frappe.get_doc(dict(doctype='Role', role_name=role_name, desk_access=0)).insert()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 182, in insert<br>    self.<em>set</em>defaults()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 493, in <em>set</em>defaults<br>    new_doc = frappe.new_doc(self.doctype, as_dict=True)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 589, in new_doc<br>    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 19, in get_new_doc<br>    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 40, in make_new_doc<br>    set_user_and_static_default_values(doc)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 55, in set_user_and_static_default_values<br>    user_default_value = get_user_default_value(df, defaults, user_permissions)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 70, in get_user_default_value<br>    if (frappe.get_meta(df.options).document_type=="Setup"<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 630, in get_meta<br>    return frappe.model.meta.get_meta(doctype, cached=cached)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 33, in get_meta<br>    lambda: Meta(doctype))<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 173, in hget<br>    value = generator()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 33, in <br>    lambda: Meta(doctype))<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 69, in <strong>init</strong><br>    super(Meta, self).<strong>init</strong>("DocType", doctype)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 84, in <strong>init</strong><br>    self.load_from_db()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 74, in load_from_db<br>    super(Meta, self).load_from_db()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 115, in load_from_db<br>    frappe.throw(<em>("{0} {1} not found").format(</em>(self.doctype), self.name), frappe.DoesNotExistError)<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 320, in throw<br>    msgprint(msg, raise_exception=exc, title=title, indicator='red')<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 310, in msgprint<br>    <em>raise</em>exception()<br>  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 283, in <em>raise</em>exception<br>    raise raise_exception(encode(msg))<br>frappe.exceptions.DoesNotExistError: DocType Domain not found</p>

**Comment by vishdha** [comment]
fixed via [fix]upgrade failed v7 to v8 #9609
