### ISSUE TITLE
Email Inbox - Filters Error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9602]
WN-SUP26087

![filter-error](https://user-images.githubusercontent.com/910238/27815396-7682f8e6-60a1-11e7-9df5-d1a08f5c7d2a.gif)

**Error traceback**

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 914, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/desk/reportview.py", line 232, in get_sidebar_stats
    return {"defined_cat":cat_tags, "stats":get_stats(stats, doctype, filters)}
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/desk/reportview.py", line 249, in get_stats
    filters = filters + ["ifnull(`%s`,'')!=''" % tag], group_by = tag, as_list = True)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 1120, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 88, in execute
    result = self.build_and_run()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 100, in build_and_run
    args = self.prepare_args()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 249, in build_conditions
    self.build_filter_conditions(self.filters, self.conditions)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 270, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/model/db_query.py", line 278, in prepare_filter_condition
    f = get_filter(self.doctype, f)
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/utils/data.py", line 734, in get_filter
    frappe.throw(frappe._("Filter must have 4 values (doctype, fieldname, operator, value): {0}").format(str(f)))
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 320, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 310, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 283, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Filter must have 4 values (doctype, fieldname, operator, value): [u'Communication', u'email_account', u'=', u"Tom Hagen's Email Account", True]

**Comment by mbauskar** [comment]
can not replicate the issue, check on test account as well as on client's account

**Comment by joolsr** [comment]
This was a problem for me in the same manner but was fixed last week and working fine now
