### ISSUE TITLE
Error "Setup Already Complete!!" in Setup Wizard

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9662]
We often receive an error message of Setup Already Complete!! After reinstalling site from backend, error message goes away.

Generally this error comes if user's Setup Wizard field due to some other validation first time, like Item Group and Code cannot be same.

`Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 39, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/benches/bench-2017-07-01/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 21, in setup_complete
    frappe.throw(_("Setup Already Complete!!"))
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 320, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 310, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-07-01/apps/frappe/frappe/__init__.py", line 283, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Setup Already Complete!!`

**Comment by rohitwaghchaure** [comment]
Duplicate https://github.com/frappe/erpnext/issues/9745
