### ISSUE TITLE
Setup Wizard error due to translation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9681]
Often receive a error report of setup wizard failure due to the translation of Item Group and UoM.

`Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 39, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/benches/bench-2017-07-06/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 35, in setup_complete
    create_items(args)
  File "/home/frappe/benches/bench-2017-07-06/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 377, in create_items
    "default_warehouse": default_warehouse
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/model/document.py", line 193, in insert
    self._validate()
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/model/document.py", line 400, in _validate
    self._validate_links()
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/model/document.py", line 635, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
LinkValidationError: No se pudo encontrar Grupo de artículos: Products, Unidad de Medida Predeterminada: Unit, Línea #1: UOM: Unit`

**Comment by umairsy** [comment]
Ref: WN-SUP26221
