### ISSUE TITLE
Deadlock Error report

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9719]
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/model/rename_doc.py", line 39, in rename_doc
    new = validate_rename(doctype, new, meta, merge, force, ignore_permissions)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/model/rename_doc.py", line 113, in validate_rename
    exists = frappe.db.sql("select name from `tab{doctype}` where name=%s for update".format(doctype=frappe.db.escape(doctype)), new)
  File "/home/frappe/benches/bench-2017-07-06/apps/frappe/frappe/database.py", line 142, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/benches/bench-2017-07-06/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/benches/bench-2017-07-06/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

**Comment by rmehta** [comment]
How can you replicate this?

**Comment by nabinhait** [comment]
It is really difficult to fix this without replicating or seeing "show engine innodb status" output. As we  can't replicate and no output of "show engine innodb status" can be found now after 21 days, I am closing this issue.
