### ISSUE TITLE
help table doesn't exist in database

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#9799]
After fresh install of latest ERPNext version ERPNext: v8.3.5 Frappe Framework: v8.3.9
When Clicking on Help in the top menu bar then choosing Documentation I got an error that help table doen't exist in database the error message is below:

_Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 33, in get_help_content
    return HelpDatabase().get_content(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/help.py", line 98, in get_content
    result = self.db.sql(query.format(path=path))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 153, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1146, "Table '1bd3e0294da19198.help' doesn't exist")_

**Comment by manassolanki** [comment]
Hi,
I have tried to replicate this. This is working properly in my local setup. You can use the following command `bench --site <sitename> setup-help` to setup the help in your site incase that's not installed before. For more queries and help, you can post this on discuss.erpnext.com
