### ISSUE TITLE
Exception on User rights on any module

### ISSUE THREAD

**Issue by adnanmunir83** [frappe/erpnext#9813]
if for any user, dosent have access to any module, and try to open that module from search box. the following exception occurred instead of "Permission Denied Message"

Traceback (most recent call last):
  File "/home/rf/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/rf/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/rf/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/rf/frappe-bench/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
TypeError: get() takes exactly 1 argument (0 given)

i'm using the lates version of ERP and Frappe.
ERPNext Release v8.3.6

**Comment by rmehta** [comment]
@pratu16x7 can you check? A module with no permission should ideally not appear in the aweseome bar

**Comment by tundebabzy** [comment]
@adnanmunir83 
Are you still experiencing this issue?
