### ISSUE TITLE
error if the production order is not set

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#9831]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-11/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-07-11/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-07-11/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-07-11/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
TypeError: get_production_order_details() takes exactly 1 argument (0 given)
```

**Comment by mona1977** [comment]
Hi , Still are you getting this problem? I will help you to resolve this issue. add my SKYPE - suren_gupta
