### ISSUE TITLE
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9863]
WN-SUP26466

Hello I’m trying to integrate my shopify store and my cloud ERPNext with URL test.erpnext.com, but when I sync the integration appears the next error.

Traceback (most recent call last):

  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/api.py", line 34, in sync_shopify_resources

    sync_orders()

  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 13, in sync_orders

    sync_shopify_orders()

  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 29, in sync_shopify_orders

    if e.args and e.args[0] and e.args[0].startswith("402"):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext_shopify/pull/161
