### ISSUE TITLE
error if we filter by childtable fields in Calendar view

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#9895]
```
Traceback (most recent call last):
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/frappe/frappe/__init__.py", line 921, in call
    return fn(*args, **newargs)
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 626, in get_events
    }, as_dict=True, update={"allDay": 0})
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/apps/frappe/frappe/database.py", line 142, in sql
    self._cursor.execute(query, values)
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/makarandbauskar/workspace/frappe/dev-frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'item_code' in 'where clause'")
```

**Comment by rmehta** [comment]
<img width="997" alt="screen shot 2017-08-22 at 4 28 00 pm" src="https://user-images.githubusercontent.com/140076/29562433-e9e74022-8756-11e7-8307-bd671a4da326.png">

Works...
