### ISSUE TITLE
Setup Wizard Failure - Error message

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9922]
`Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 39, in setup_complete
    frappe.get_attr(method)(args)
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 53, in setup_complete
    setup_domain(args.get('domain'))
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/setup/setup_wizard/domainify.py", line 82, in setup_domain
    update_module_def_restrict_to_domain()
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/setup/setup_wizard/domainify.py", line 160, in update_module_def_restrict_to_domain
    frappe.set_value("Module Def", module, "restrict_to_domain", _(domain, lang))
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/__init__.py", line 602, in set_value
    return frappe.client.set_value(doctype, docname, fieldname, value)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/client.py", line 107, in set_value
    doc.save()
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 256, in _save
    self.check_permission("write", "save")
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 146, in check_permission
    self.raise_no_permission_to(permlabel or permtype)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 160, in raise_no_permission_to
    raise frappe.PermissionError
PermissionError`

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/9923
