### ISSUE TITLE
erpnext.accounts.doctype.asset.depreciation.post_depreciation_entries

### ISSUE THREAD

**Issue by yousefbakir** [frappe/erpnext#9928]
{'retry': 0, 'log': <function log at 0x2444f50>, 'site': u'bentamarketing.erpnext.com', 'event': u'daily', 'method_name': u'erpnext.accounts.doctype.asset.depreciation.post_depreciation_entries', 'method': <function post_depreciation_entries at 0x23dfb18>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'erpnext.accounts.doctype.asset.depreciation.post_depreciation_entries'}
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/utils/background_jobs.py", line 66, in execute_job
    method(**kwargs)
  File "/home/frappe/benches/bench-2017-07-13/apps/erpnext/erpnext/accounts/doctype/asset/depreciation.py", line 18, in post_depreciation_entries
    make_depreciation_entry(asset, date)
  File "/home/frappe/benches/bench-2017-07-13/apps/erpnext/erpnext/accounts/doctype/asset/depreciation.py", line 65, in make_depreciation_entry
    je.submit()
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/model/document.py", line 741, in submit
    self._submit()
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/model/document.py", line 730, in _submit
    self.save()
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/benches/bench-2017-07-13/apps/frappe/frappe/model/document.py", line 207, in insert
    raise e
DuplicateEntryError: (u'Journal Entry', u'JV-00100', IntegrityError(1062, "Duplicate entry 'JV-00100' for key 'PRIMARY'"))

Please help ?

**Comment by tundebabzy** [comment]
Hello @yousefbakir 
You have not given sufficient information. Also we use github for dealing with confirmed bugs and sometimes, feature requests.

Please create a new topic on our forum at https://discuss.erpnext.com and don't forget to explain what you are attempting.
