### ISSUE TITLE
bench update error

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#9945]
Hello there,

can you help me with that error? Thank you.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 91, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 17, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/site.py", line 216, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/migrate.py", line 36, in migrate
    sync_customizations()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 95, in sync_customizations
    sync_customizations_for_doctype(data)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 119, in sync_customizations_for_doctype
    sync('property_setters', 'Property Setter', 'doc_type')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 112, in sync
    doc.db_insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py", line 311, in db_insert
    raise_(frappe.DuplicateEntryError, (self.doctype, self.name, e), traceback)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py", line 299, in db_insert
    ), d.values())
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 142, in sql
    self._cursor.execute(query, values)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
frappe.exceptions.DuplicateEntryError: (u'Property Setter', u'Sales Invoice Item-barcode-hidden', IntegrityError(1062, "Duplicate entry 'Sales Invoice Item-barcode-hidden' for key 'PRIMARY'"))

ERPNext: v8.4.3 (master)
Frappe Framework: v8.4.1 (master)

**Comment by umairsy** [comment]
Please post your technical queries on the community forum. https://discuss.erpnext.com
